include_guard(GLOBAL)

file(GLOB_RECURSE IO_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

if(APPLE)
    file(GLOB_RECURSE IO_MM_SOURCES CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_LIST_DIR}/*.mm"
    )
    list(APPEND IO_SOURCES ${IO_MM_SOURCES})
endif()

file(GLOB_RECURSE IO_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${IO_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${IO_HEADERS})
