include_guard(GLOBAL)

file(GLOB_RECURSE YANTRA_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE YANTRA_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${YANTRA_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${YANTRA_HEADERS})
