MayaFlux: MayaFlux::Core::RtAudioStream::open
open()
void MayaFlux::Core::RtAudioStream::open () override virtual
Initializes the audio stream and allocates required resources.
Opens the RtAudio stream with the configured parameters, making it ready for data transfer. Does not start the actual data flow.
Implements MayaFlux::Core::AudioStream.
Definition at line 210 of file RtAudioBackend.cpp.
{
    if (is_open()) {
        return;
    }
    try {
        RtAudioFormat format = RTAUDIO_FLOAT64;
        switch (m_stream_info.format) {
        case GlobalStreamInfo::AudioFormat::FLOAT32:
            format = RTAUDIO_FLOAT32;
            break;
        case GlobalStreamInfo::AudioFormat::FLOAT64:
            format = RTAUDIO_FLOAT64;
            break;
        case GlobalStreamInfo::AudioFormat::INT16:
            format = RTAUDIO_SINT16;
            break;
        case GlobalStreamInfo::AudioFormat::INT24:
            format = RTAUDIO_SINT24;
            break;
        case GlobalStreamInfo::AudioFormat::INT32:
            format = RTAUDIO_SINT32;
            break;
        }
        RtAudio::StreamParameters* inputParamsPtr = nullptr;
        if (m_stream_info.input.enabled && m_stream_info.input.channels > 0) {
            m_in_parameters.nChannels = m_stream_info.input.channels;
            inputParamsPtr = &m_in_parameters;
        }
        unsigned int requested_buffer = m_stream_info.buffer_size;
#ifdef MAYAFLUX_PLATFORM_LINUX
        if (m_context->getCurrentApi() == RtAudio::UNIX_JACK) {
            setenv("PIPEWIRE_QUANTUM",
                std::to_string(m_stream_info.buffer_size).c_str(), 0);
            setenv("PIPEWIRE_LATENCY",
                Journal::format_runtime("{}/{}", m_stream_info.buffer_size, m_stream_info.sample_rate).c_str(), 0);
        }
#endif // MAYAFLUX_PLATFORM_LINUX
        RtAudioSingleton::mark_stream_open();
        m_context->openStream(
            &m_out_parameters,
            inputParamsPtr,
            format,
            m_stream_info.sample_rate,
            &m_stream_info.buffer_size,
            &RtAudioStream::rtAudioCallback,
            this,
            &m_options);
        if (m_stream_info.buffer_size != requested_buffer) {
            MF_WARN(Journal::Component::Core,
                Journal::Context::AudioBackend,
                "Audio backend changed buffer size from {} to {}. "
                "Set GlobalStreamInfo.buffer_size = {} before initialization to avoid mismatch.",
                requested_buffer, m_stream_info.buffer_size, m_stream_info.buffer_size);
        }
        m_isOpen = true;
    } catch (const RtAudioErrorType& e) {
        RtAudioSingleton::mark_stream_closed();
        m_isOpen = false;
        error_rethrow(
            Journal::Component::Core,
            Journal::Context::AudioBackend,
            std::source_location::current(),
            "Failed to open RtAudio stream: {}",
            m_context->getErrorText());
    }
}
References MayaFlux::Journal::AudioBackend, MayaFlux::Core::GlobalStreamInfo::buffer_size, MayaFlux::Core::GlobalStreamInfo::ChannelConfig::channels, MayaFlux::Journal::Core, MayaFlux::Core::GlobalStreamInfo::ChannelConfig::enabled, MayaFlux::Core::GlobalStreamInfo::FLOAT32, MayaFlux::Core::GlobalStreamInfo::FLOAT64, MayaFlux::Core::GlobalStreamInfo::format, MayaFlux::Journal::format_runtime(), MayaFlux::Core::GlobalStreamInfo::input, MayaFlux::Core::GlobalStreamInfo::INT16, MayaFlux::Core::GlobalStreamInfo::INT24, MayaFlux::Core::GlobalStreamInfo::INT32, is_open(), m_context, m_in_parameters, m_isOpen, m_options, m_out_parameters, m_stream_info, MayaFlux::Core::RtAudioSingleton::mark_stream_closed(), MayaFlux::Core::RtAudioSingleton::mark_stream_open(), MF_WARN, rtAudioCallback(), and MayaFlux::Core::GlobalStreamInfo::sample_rate.