MayaFlux: MayaFlux::Kriya::Sequence::execute
execute() [1/2]
void MayaFlux::Kriya::Sequence::execute ()
Executes the sequence using the global managers.
This method executes the sequence of actions using the global node manager and scheduler. It's convenient for simple cases where only one processing engine is active.
The actions are executed in the order they were added, with any time delays respected.
Definition at line 78 of file Chain.cpp.
{
    execute(MayaFlux::get_node_graph_manager(), MayaFlux::get_scheduler());
}
References execute(), MayaFlux::get_node_graph_manager(), and MayaFlux::get_scheduler().
Referenced by execute().