MayaFlux: MayaFlux::Nodes::Network::ParticleNetwork::initialize_particle_positions
initialize_particle_positions()
void MayaFlux::Nodes::Network::ParticleNetwork::initialize_particle_positions (InitializationMode mode) private
Initialize particles based on mode.
Definition at line 547 of file ParticleNetwork.cpp.
{
    switch (mode) {
    case InitializationMode::RANDOM_VOLUME:
        for (auto& particle : m_particles) {
            particle.point->set_position(random_position_volume());
        }
        break;
    case InitializationMode::RANDOM_SURFACE:
        for (auto& particle : m_particles) {
            particle.point->set_position(random_position_surface());
        }
        break;
    case InitializationMode::GRID: {
        auto grid_size = static_cast<size_t>(std::cbrt(m_particles.size()));
        glm::vec3 spacing = (m_bounds_max - m_bounds_min) / static_cast<float>(grid_size);
        size_t idx = 0;
        for (size_t x = 0; x < grid_size && idx < m_particles.size(); ++x) {
            for (size_t y = 0; y < grid_size && idx < m_particles.size(); ++y) {
                for (size_t z = 0; z < grid_size && idx < m_particles.size(); ++z) {
                    glm::vec3 pos = m_bounds_min + glm::vec3(x, y, z) * spacing;
                    m_particles[idx++].point->set_position(pos);
                }
            }
        }
        break;
    }
    case InitializationMode::SPHERE_VOLUME: {
        glm::vec3 center = (m_bounds_min + m_bounds_max) * 0.5F;
        float radius = glm::length(m_bounds_max - center);
        for (auto& particle : m_particles) {
            particle.point->set_position(center + random_position_sphere(radius));
        }
        break;
    }
    case InitializationMode::SPHERE_SURFACE: {
        glm::vec3 center = (m_bounds_min + m_bounds_max) * 0.5F;
        float radius = glm::length(m_bounds_max - center);
        for (auto& particle : m_particles) {
            particle.point->set_position(center + random_position_sphere_surface(radius));
        }
        break;
    }
    case InitializationMode::CUSTOM:
        break;
    }
    update_point_nodes();
}
References CUSTOM, GRID, m_bounds_max, m_bounds_min, m_particles, random_position_sphere(), random_position_sphere_surface(), random_position_surface(), random_position_volume(), RANDOM_SURFACE, RANDOM_VOLUME, SPHERE_SURFACE, SPHERE_VOLUME, and update_point_nodes().
Referenced by initialize(), reinitialize_positions(), and reset().