MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::calculate_image_size
calculate_image_size()
size_t MayaFlux::Portal::Graphics::TextureLoom::calculate_image_size (uint32_t width, uint32_t height, uint32_t depth, ImageFormat format) static
Calculate image data size.
Definition at line 491 of file TextureLoom.cpp.
{
    return static_cast<size_t>(width) * height * depth * get_bytes_per_pixel(format);
}
References get_bytes_per_pixel().
Referenced by create_2d(), create_3d(), and create_cubemap().