MayaFlux: MayaFlux::Core::BufferProcessingHandle::ensure_valid
ensure_valid()
void MayaFlux::Core::BufferProcessingHandle::ensure_valid () const private
Definition at line 24 of file ProcessingArchitecture.cpp.
{
    if (!m_manager) {
        fatal(Journal::Component::Core, Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Invalid buffer processing handle: BufferManager is null");
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Core, and m_manager.
Referenced by cleanup_completed_routing(), process(), process_channel(), process_channel_with_node_data(), read_channel_data(), setup_channels(), update_routing_states(), and write_channel_data().