MayaFlux: MayaFlux::Buffers::BufferAccessControl::add_graphics_buffer
add_graphics_buffer()
void MayaFlux::Buffers::BufferAccessControl::add_graphics_buffer (const std::shared_ptr< Buffer > & buffer, ProcessingToken token)
Adds a graphics buffer to a token.
Parameters
buffer Graphics buffer to add (must be VKBuffer-derived)
token Processing domain
Definition at line 208 of file BufferAccessControl.cpp.
{
    if (auto vk_buffer = std::dynamic_pointer_cast<VKBuffer>(buffer)) {
        auto& unit = m_unit_manager.get_or_create_graphics_unit(token);
        auto processing_chain = unit.get_chain();
        if (auto buf_chain = buffer->get_processing_chain()) {
            if (buf_chain != processing_chain) {
                processing_chain->merge_chain(buf_chain);
            }
        } else {
            buffer->set_processing_chain(processing_chain, false);
        }
        try {
            if (!vk_buffer->is_initialized()) {
                if (!m_buffer_service) {
                    initialize_buffer_service();
                }
                m_buffer_service->initialize_buffer(vk_buffer);
                vk_buffer->setup_processors(token);
            }
        } catch (const std::exception& e) {
            error_rethrow(Journal::Component::Core, Journal::Context::BufferManagement,
                std::source_location::current(),
                "Failed to initialize graphics buffer for token {}: {}",
                static_cast<int>(token), e.what());
        }
        unit.get_buffer()->add_child_buffer(vk_buffer);
        MF_INFO(Journal::Component::Core, Journal::Context::BufferManagement,
            "Added graphics buffer to token {} (total: {})",
            static_cast<int>(token),
            unit.get_buffer()->get_buffer_count());
    } else {
        error<std::invalid_argument>(Journal::Component::Core, Journal::Context::BufferManagement,
            std::source_location::current(),
            "Unsupported graphics buffer type for token {}",
            static_cast<int>(token));
    }
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::RootGraphicsUnit::get_chain(), MayaFlux::Buffers::TokenUnitManager::get_or_create_graphics_unit(), MayaFlux::Registry::Service::BufferService::initialize_buffer, initialize_buffer_service(), m_buffer_service, m_unit_manager, and MF_INFO.
Referenced by add_buffer().