MayaFlux: MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor
remove_audio_processor()
void MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor (const std::shared_ptr< BufferProcessor > & processor, const std::shared_ptr< AudioBuffer > & buffer)
Removes a processor from a specific audio buffer.
Parameters
processor Processor to remove
buffer Target audio buffer
Definition at line 155 of file BufferProcessingControl.cpp.
{
    uint32_t channel_id = buffer->get_channel_id();
    for (const auto& token : m_unit_manager.get_active_audio_tokens()) {
        const auto& unit = m_unit_manager.get_audio_unit(token);
        if (channel_id < unit.channel_count) {
            auto processing_chain = unit.get_chain(channel_id);
            processing_chain->remove_processor(processor, buffer);
            if (auto buf_chain = buffer->get_processing_chain()) {
                buf_chain->remove_processor(processor, buffer);
            }
            return;
        }
    }
}
References MayaFlux::Buffers::TokenUnitManager::get_active_audio_tokens(), MayaFlux::Buffers::TokenUnitManager::get_audio_unit(), MayaFlux::Buffers::RootAudioUnit::get_chain(), and m_unit_manager.
Referenced by remove_processor().