MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::set_topology
set_topology()
virtual void MayaFlux::Nodes::Network::NodeNetwork::set_topology (Topology topology) inline virtual
Set the network's topology.
Reimplemented in MayaFlux::Nodes::Network::ParticleNetwork, and MayaFlux::Nodes::Network::PointCloudNetwork.
Definition at line 186 of file NodeNetwork.hpp.
{ m_topology = topology; }
Referenced by MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::Network::ParticleNetwork::set_topology(), MayaFlux::Nodes::Network::PointCloudNetwork::set_topology(), and MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideNetwork().