MayaFlux: MayaFlux::Nodes::Generator::Polynomial::process_sample
process_sample()
double MayaFlux::Nodes::Generator::Polynomial::process_sample (double input = 0.) override virtual
Processes a single sample.
Parameters
input Input value
Returns
The next sample value from the polynomial function
Computes the next output value based on the polynomial function and current mode.
Implements MayaFlux::Nodes::Node.
Definition at line 64 of file Polynomial.cpp.
{
    double result = 0.0;
    if (m_input_node) {
        atomic_inc_modulator_count(m_input_node->m_modulator_count, 1);
        uint32_t state = m_input_node->m_state.load();
        if (state & Utils::NodeState::PROCESSED) {
            input += m_input_node->get_last_output();
        } else {
            input = m_input_node->process_sample(input);
            atomic_add_flag(m_input_node->m_state, Utils::NodeState::PROCESSED);
        }
    }
    switch (m_mode) {
    case PolynomialMode::DIRECT:
        result = m_direct_function(input);
        break;
    case PolynomialMode::RECURSIVE:
        if (m_buffer_size > 0) {
            std::deque<double> combined_buffer = build_processing_buffer(input, true);
            result = m_buffer_function(combined_buffer);
            if (!m_use_external_context) {
                m_input_buffer.push_front(input);
                if (m_output_buffer.size() >= m_buffer_size) {
                    m_output_buffer.pop_back();
                }
            }
            m_output_buffer.push_front(result);
            if (m_input_buffer.size() > m_buffer_size) {
                m_input_buffer.pop_back();
            }
        }
        break;
    case PolynomialMode::FEEDFORWARD:
        if (m_buffer_size > 0) {
            std::deque<double> input_buffer = build_processing_buffer(input, false);
            result = m_buffer_function(input_buffer);
            if (!m_use_external_context) {
                m_input_buffer.push_front(input);
                if (m_input_buffer.size() > m_buffer_size) {
                    m_input_buffer.pop_back();
                }
            }
            m_output_buffer.push_front(result);
            if (m_output_buffer.size() > m_buffer_size) {
                m_output_buffer.pop_back();
            }
        }
        break;
    }
    result *= m_scale_factor;
    m_last_output = result;
    if ((!m_state_saved || (m_state_saved && m_fire_events_during_snapshot))
        && !m_networked_node) {
        notify_tick(result);
    }
    if (m_input_node) {
        atomic_dec_modulator_count(m_input_node->m_modulator_count, 1);
        try_reset_processed_state(m_input_node);
    }
    return result;
}
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), build_processing_buffer(), MayaFlux::Nodes::Generator::DIRECT, MayaFlux::Nodes::Generator::FEEDFORWARD, m_buffer_function, m_buffer_size, m_direct_function, MayaFlux::Nodes::Node::m_fire_events_during_snapshot, m_input_buffer, m_input_node, MayaFlux::Nodes::Node::m_last_output, m_mode, MayaFlux::Nodes::Node::m_networked_node, m_output_buffer, m_scale_factor, MayaFlux::Nodes::Node::m_state_saved, m_use_external_context, notify_tick(), MayaFlux::Utils::PROCESSED, MayaFlux::Nodes::Generator::RECURSIVE, and MayaFlux::Nodes::try_reset_processed_state().
Referenced by process_batch().