MayaFlux: MayaFlux::Buffers::MeshNetworkProcessor::allocate_gpu_buffers
allocate_gpu_buffers()
void MayaFlux::Buffers::MeshNetworkProcessor::allocate_gpu_buffers (const std::shared_ptr< VKBuffer > & vertex_buf) private
Definition at line 96 of file MeshNetworkProcessor.cpp.
{
    const size_t v_bytes = total_vertex_bytes();
    const size_t i_bytes = total_index_count() * sizeof(uint32_t);
    if (v_bytes == 0 || i_bytes == 0) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "MeshNetworkProcessor::allocate_gpu_buffers: network has no geometry");
        return;
    }
    if (!vertex_buf->is_host_visible())
        m_vertex_staging = create_staging_buffer(v_bytes);
    m_gpu_index_buffer = std::make_shared<VKBuffer>(
        i_bytes, VKBuffer::Usage::INDEX, Kakshya::DataModality::UNKNOWN);
    m_buffer_service->initialize_buffer(m_gpu_index_buffer);
    m_index_staging = create_staging_buffer(i_bytes);
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "MeshNetworkProcessor: allocated vertex ({} bytes) + index ({} bytes)",
        v_bytes, i_bytes);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Buffers::VKBuffer::INDEX, MayaFlux::Registry::Service::BufferService::initialize_buffer, MayaFlux::Buffers::VKBufferProcessor::m_buffer_service, m_gpu_index_buffer, m_index_staging, m_vertex_staging, MF_DEBUG, MF_WARN, total_index_count(), total_vertex_bytes(), and MayaFlux::Kakshya::UNKNOWN.
Referenced by on_attach().