MayaFlux: MayaFlux::Core::InputManager::start
start()
void MayaFlux::Core::InputManager::start ()
Start the processing thread.
Definition at line 43 of file InputManager.cpp.
{
    if (m_running.load()) {
        MF_WARN(Journal::Component::Core, Journal::Context::Init,
            "InputManager already running");
        return;
    }
    if (!m_input_service) {
        m_input_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::InputService>();
        if (!m_input_service) {
            MF_WARN(Journal::Component::Core, Journal::Context::InputManagement,
                "InputManager requires InputService but service not registered");
            return;
        }
    }
    m_stop_requested.store(false);
    m_running.store(true);
    m_processing_thread = std::thread(&InputManager::processing_loop, this);
    MF_INFO(Journal::Component::Core, Journal::Context::Init,
        "InputManager started");
}
References MayaFlux::Journal::Core, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Journal::Init, MayaFlux::Journal::InputManagement, MayaFlux::Registry::BackendRegistry::instance(), m_input_service, m_processing_thread, m_running, m_stop_requested, MF_INFO, MF_WARN, and processing_loop().