MayaFlux: MayaFlux::Nexus::Fabric::name
name()
const std::string & MayaFlux::Nexus::Fabric::name () const inline
Assigned name, empty if the Fabric was constructed outside a Tapestry.
Definition at line 66 of file Fabric.hpp.
{ return m_name; }
Referenced by MayaFlux::Nexus::StateEncoder::encode(), resolve_influence_fn(), and resolve_perception_fn().