MayaFlux: MayaFlux::IO::AudioStreamContext::open
open()
bool MayaFlux::IO::AudioStreamContext::open (const FFmpegDemuxContext & demux, bool planar_output = false, uint32_t target_rate = 0)
Open the audio stream from an already-probed demux context.
Finds the best audio stream, allocates and opens the codec context, caches audio parameters, and initialises the SwrContext for conversion to AV_SAMPLE_FMT_DBL (or AV_SAMPLE_FMT_DBLP if planar output requested).
Parameters
demux Open demux context (must outlive this object).
planar_output If true, configure swr for planar double output.
target_rate Resample target in Hz; 0 = keep source rate.
Returns
True on success.
Definition at line 44 of file AudioStreamContext.cpp.
{
    close();
    FFmpegDemuxContext::init_ffmpeg();
    if (!demux.is_open()) {
        m_last_error = "Demux context is not open";
        return false;
    }
    const AVCodec* codec = nullptr;
    stream_index = demux.find_best_stream(AVMEDIA_TYPE_AUDIO,
        reinterpret_cast<const void**>(&codec));
    if (stream_index < 0 || !codec) {
        m_last_error = "No audio stream found";
        return false;
    }
    codec_context = avcodec_alloc_context3(codec);
    if (!codec_context) {
        m_last_error = "avcodec_alloc_context3 failed";
        return false;
    }
    AVStream* stream = demux.get_stream(stream_index);
    if (avcodec_parameters_to_context(codec_context, stream->codecpar) < 0) {
        m_last_error = "avcodec_parameters_to_context failed";
        close();
        return false;
    }
    if (avcodec_open2(codec_context, codec, nullptr) < 0) {
        m_last_error = "avcodec_open2 failed";
        close();
        return false;
    }
    sample_rate = static_cast<uint32_t>(codec_context->sample_rate);
    channels = static_cast<uint32_t>(codec_context->ch_layout.nb_channels);
    if (stream->duration > 0) {
        total_frames = av_rescale_q(stream->duration, stream->time_base,
            AVRational { 1, (int)sample_rate });
    } else if (demux.format_context->duration != AV_NOPTS_VALUE) {
        double dur = (double)demux.format_context->duration / AV_TIME_BASE;
        total_frames = static_cast<uint64_t>(dur * sample_rate);
    }
    if (!setup_resampler(planar_output, target_rate)) {
        close();
        return false;
    }
    drain_resampler_init();
    return true;
}
References channels, close(), codec_context, drain_resampler_init(), MayaFlux::IO::FFmpegDemuxContext::find_best_stream(), MayaFlux::IO::FFmpegDemuxContext::format_context, MayaFlux::IO::FFmpegDemuxContext::get_stream(), MayaFlux::IO::FFmpegDemuxContext::init_ffmpeg(), MayaFlux::IO::FFmpegDemuxContext::is_open(), m_last_error, sample_rate, setup_resampler(), stream_index, and total_frames.