MayaFlux: MayaFlux::Kriya::NodeTimer::cleanup_current_operation
cleanup_current_operation()
void MayaFlux::Kriya::NodeTimer::cleanup_current_operation () private
Cleans up the current operation, disconnecting the node and resetting state.
This method is called when the timer completes its specified duration. It disconnects the currently active node from the output channels and resets internal state to allow new operations to be started.
Definition at line 171 of file Timers.cpp.
{
    if (m_current_node) {
        for (auto channel : m_channels) {
            if (m_current_node->is_used_by_channel(channel)) {
                m_node_graph_manager.get_root_node(token, channel).unregister_node(m_current_node);
            }
        }
        m_current_node = nullptr;
        m_channels.clear();
    }
}
References MayaFlux::Nodes::NodeGraphManager::get_root_node(), m_channels, m_current_node, m_node_graph_manager, token, and MayaFlux::Nodes::RootNode::unregister_node().
Referenced by cancel(), play_for(), and play_with_processing().