MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_audio_channel_count
get_audio_channel_count()
uint32_t MayaFlux::Buffers::TokenUnitManager::get_audio_channel_count (ProcessingToken token) const
Gets the number of channels in an audio unit.
Parameters
token Processing domain
Returns
Number of channels, or 0 if unit doesn't exist
Definition at line 207 of file TokenUnitManager.cpp.
{
    auto it = m_audio_units.find(token);
    return (it != m_audio_units.end()) ? it->second.channel_count : 0;
}
References m_audio_units.
Referenced by MayaFlux::Buffers::BufferAccessControl::get_num_audio_out_channels(), MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer(), and MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to().