MayaFlux: MayaFlux::Buffers::RenderProcessor::initialize_pipeline
initialize_pipeline()
void MayaFlux::Buffers::RenderProcessor::initialize_pipeline (const std::shared_ptr< VKBuffer > & buffer) override protected virtual
Implements MayaFlux::Buffers::ShaderProcessor.
Definition at line 110 of file RenderProcessor.cpp.
{
    if (m_shader_id == Portal::Graphics::INVALID_SHADER) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Vertex shader not loaded");
        return;
    }
    if (m_fragment_shader_id == Portal::Graphics::INVALID_SHADER) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Fragment shader not loaded");
        return;
    }
    auto& flow = Portal::Graphics::get_render_flow();
    if (!m_target_window) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Target window not set");
        return;
    }
    if (m_render_pass_id == Portal::Graphics::INVALID_RENDER_PASS) {
        vk::Format swapchain_format = vk::Format { m_display_service->get_swapchain_format(m_target_window) };
        m_render_pass_id = flow.create_simple_render_pass(swapchain_format);
        if (m_render_pass_id == Portal::Graphics::INVALID_RENDER_PASS) {
            MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Render pass not set");
            return;
        }
    }
    Portal::Graphics::get_render_flow().register_window_for_rendering(m_target_window, m_render_pass_id);
    Portal::Graphics::RenderPipelineConfig pipeline_config;
    pipeline_config.vertex_shader = m_shader_id;
    pipeline_config.fragment_shader = m_fragment_shader_id;
    pipeline_config.geometry_shader = m_geometry_shader_id;
    pipeline_config.tess_control_shader = m_tess_control_shader_id;
    pipeline_config.tess_eval_shader = m_tess_eval_shader_id;
    pipeline_config.render_pass = m_render_pass_id;
    pipeline_config.topology = m_primitive_topology;
    pipeline_config.rasterization.polygon_mode = m_polygon_mode;
    pipeline_config.rasterization.cull_mode = m_cull_mode;
    pipeline_config.blend_attachments.emplace_back();
    pipeline_config.push_constant_size = buffer->get_pipeline_context().push_constant_staging.size();
    auto it = m_buffer_info.find(buffer);
    if (it != m_buffer_info.end()) {
        const auto& vertex_info = it->second;
        pipeline_config.semantic_vertex_layout = vertex_info.semantic_layout;
        pipeline_config.use_vertex_shader_reflection = vertex_info.use_reflection;
    }
    auto& descriptor_bindings = buffer->get_pipeline_context().descriptor_buffer_bindings;
    std::map<std::pair<uint32_t, uint32_t>, Portal::Graphics::DescriptorBindingInfo> unified_bindings;
    for (const auto& binding : descriptor_bindings) {
        unified_bindings[{ binding.set, binding.binding }] = binding;
    }
    for (const auto& [name, binding] : m_config.bindings) {
        auto key = std::make_pair(binding.set, binding.binding);
        if (unified_bindings.find(key) == unified_bindings.end()) {
            unified_bindings[key] = Portal::Graphics::DescriptorBindingInfo {
                .set = binding.set,
                .binding = binding.binding,
                .type = binding.type,
                .buffer_info = {},
                .name = name
            };
        }
    }
    std::map<uint32_t, std::vector<Portal::Graphics::DescriptorBindingInfo>> bindings_by_set;
    for (const auto& [key, binding] : unified_bindings) {
        bindings_by_set[binding.set].push_back(binding);
    }
    for (const auto& [set_index, set_bindings] : bindings_by_set) {
        pipeline_config.descriptor_sets.push_back(set_bindings);
    }
    m_pipeline_id = flow.create_pipeline(pipeline_config);
    if (m_pipeline_id == Portal::Graphics::INVALID_RENDER_PIPELINE) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Failed to create render pipeline");
        return;
    }
    if (!pipeline_config.descriptor_sets.empty() && m_descriptor_set_ids.empty()) {
        m_descriptor_set_ids = flow.allocate_pipeline_descriptors(m_pipeline_id);
        if (m_descriptor_set_ids.empty()) {
            MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Failed to allocate descriptor sets for pipeline");
            return;
        }
        for (const auto& [binding, tex_binding] : m_texture_bindings) {
            auto config_it = std::ranges::find_if(m_config.bindings,
                [binding](const auto& pair) {
                    return pair.second.binding == binding;
                });
            if (config_it == m_config.bindings.end()) {
                MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                    "No config for binding {}", binding);
                continue;
            }
            uint32_t set_index = config_it->second.set;
            if (set_index >= m_descriptor_set_ids.size()) {
                MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                    "Descriptor set index {} out of range", binding);
                continue;
            }
            auto& foundry = Portal::Graphics::get_shader_foundry();
            foundry.update_descriptor_image(
                m_descriptor_set_ids[set_index],
                config_it->second.binding,
                tex_binding.texture->get_image_view(),
                tex_binding.sampler,
                vk::ImageLayout::eShaderReadOnlyOptimal);
        }
        MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Allocated {} descriptor sets and updated {} texture bindings",
            m_descriptor_set_ids.size(), m_texture_bindings.size());
    }
    m_needs_pipeline_rebuild = false;
}
References MayaFlux::Buffers::ShaderConfig::bindings, MayaFlux::Portal::Graphics::RenderPipelineConfig::blend_attachments, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::RasterizationConfig::cull_mode, MayaFlux::Portal::Graphics::RenderPipelineConfig::descriptor_sets, MayaFlux::Portal::Graphics::RenderPipelineConfig::fragment_shader, MayaFlux::Portal::Graphics::RenderPipelineConfig::geometry_shader, MayaFlux::Portal::Graphics::get_render_flow(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Registry::Service::DisplayService::get_swapchain_format, MayaFlux::Portal::Graphics::INVALID_RENDER_PASS, MayaFlux::Portal::Graphics::INVALID_RENDER_PIPELINE, MayaFlux::Portal::Graphics::INVALID_SHADER, m_buffer_info, MayaFlux::Buffers::ShaderProcessor::m_config, m_cull_mode, MayaFlux::Buffers::ShaderProcessor::m_descriptor_set_ids, m_display_service, m_fragment_shader_id, m_geometry_shader_id, MayaFlux::Buffers::ShaderProcessor::m_needs_pipeline_rebuild, m_pipeline_id, m_polygon_mode, m_primitive_topology, m_render_pass_id, MayaFlux::Buffers::ShaderProcessor::m_shader_id, m_target_window, m_tess_control_shader_id, m_tess_eval_shader_id, m_texture_bindings, MF_DEBUG, MF_ERROR, MF_RT_ERROR, MayaFlux::Portal::Graphics::RasterizationConfig::polygon_mode, MayaFlux::Portal::Graphics::RenderPipelineConfig::push_constant_size, MayaFlux::Portal::Graphics::RenderPipelineConfig::rasterization, MayaFlux::Portal::Graphics::RenderFlow::register_window_for_rendering(), MayaFlux::Portal::Graphics::RenderPipelineConfig::render_pass, MayaFlux::Portal::Graphics::RenderPipelineConfig::semantic_vertex_layout, MayaFlux::Portal::Graphics::DescriptorBindingInfo::set, MayaFlux::Portal::Graphics::RenderPipelineConfig::tess_control_shader, MayaFlux::Portal::Graphics::RenderPipelineConfig::tess_eval_shader, MayaFlux::Portal::Graphics::RenderPipelineConfig::topology, MayaFlux::Portal::Graphics::RenderPipelineConfig::use_vertex_shader_reflection, and MayaFlux::Portal::Graphics::RenderPipelineConfig::vertex_shader.
Referenced by execute_shader().