MayaFlux: MayaFlux::Core::AudioSubsystem::register_callbacks
register_callbacks()
void MayaFlux::Core::AudioSubsystem::register_callbacks () override virtual
Register audio backend callbacks for real-time processing.
Implements MayaFlux::Core::ISubsystem.
Definition at line 32 of file AudioSubsystem.cpp.
{
    if (!m_is_ready || !m_audio_stream) {
        error<std::runtime_error>(
            Journal::Component::Core,
            Journal::Context::AudioSubsystem,
            std::source_location::current(),
            "AudioSubsystem not initialized");
    }
    m_audio_stream->set_process_callback(
        [this](void* output_buffer, void* input_buffer, unsigned int num_frames) -> int {
            auto input_ptr = static_cast<double*>(input_buffer);
            auto output_ptr = static_cast<double*>(output_buffer);
            if (input_ptr && output_ptr) {
                return this->process_audio(input_ptr, output_ptr, num_frames);
            }
            if (output_ptr) {
                return this->process_output(output_ptr, num_frames);
            }
            if (input_ptr) {
                return this->process_input(input_ptr, num_frames);
            }
            return 0;
        });
}
References MayaFlux::Journal::AudioSubsystem, MayaFlux::Journal::Core, m_audio_stream, m_is_ready, process_audio(), process_input(), and process_output().