MayaFlux: MayaFlux::Portal::Graphics::SamplerForge::get_or_create
get_or_create()
vk::Sampler MayaFlux::Portal::Graphics::SamplerForge::get_or_create (const SamplerConfig & config)
Get or create a sampler with the given configuration.
Parameters
config Sampler configuration
Returns
Vulkan sampler handle (cached)
Samplers are cached - identical configs return the same sampler. All samplers are destroyed on shutdown.
Definition at line 71 of file SamplerForge.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "SamplerForge not initialized");
        return nullptr;
    }
    size_t hash = hash_config(config);
    auto it = m_sampler_cache.find(hash);
    if (it != m_sampler_cache.end()) {
        return it->second;
    }
    vk::Sampler sampler = create_sampler(config);
    if (sampler) {
        m_sampler_cache[hash] = sampler;
        MF_DEBUG(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "Created and cached sampler (hash: {}, total: {})",
            hash, m_sampler_cache.size());
    }
    return sampler;
}
References create_sampler(), hash_config(), MayaFlux::Journal::ImageProcessing, is_initialized(), m_sampler_cache, MF_DEBUG, MF_ERROR, and MayaFlux::Journal::Portal.
Referenced by get_anisotropic(), get_default_linear(), and get_default_nearest().