MayaFlux: MayaFlux::Nodes::RootNode::unregister_node
unregister_node()
void MayaFlux::Nodes::RootNode::unregister_node (const std::shared_ptr< Node > & node)
Removes a node from this root node.
Parameters
node The node to unregister
After unregistering, the node will no longer contribute to the root node's output. If called during processing, the operation is deferred until safe.
Definition at line 52 of file RootNode.cpp.
{
    if (!node)
        return;
    uint32_t state = node->m_state.load();
    atomic_add_flag(node->m_state, NodeState::PENDING_REMOVAL);
    if (m_is_processing.load(std::memory_order_acquire)) {
        for (auto& m_pending_op : m_pending_ops) {
            bool expected = false;
            if (m_pending_op.active.compare_exchange_strong(
                    expected, true,
                    std::memory_order_acquire,
                    std::memory_order_relaxed)) {
                m_pending_op.node = node;
                m_pending_count.fetch_add(1, std::memory_order_relaxed);
                return;
            }
        }
        while (m_is_processing.load(std::memory_order_acquire)) {
            m_is_processing.wait(true, std::memory_order_acquire);
        }
    }
    auto it = m_Nodes.begin();
    while (it != m_Nodes.end()) {
        if ((*it).get() == node.get()) {
            it = m_Nodes.erase(it);
            break;
        }
        ++it;
    }
    node->reset_processed_state();
    uint32_t flag = node->m_state.load();
    flag &= ~static_cast<uint32_t>(NodeState::PENDING_REMOVAL);
    flag &= ~static_cast<uint32_t>(NodeState::ACTIVE);
    flag |= static_cast<uint32_t>(NodeState::INACTIVE);
    atomic_set_flag_strong(node->m_state, static_cast<NodeState>(flag));
}
References MayaFlux::Nodes::ACTIVE, MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_set_flag_strong(), MayaFlux::Nodes::INACTIVE, m_is_processing, m_Nodes, m_pending_count, m_pending_ops, and MayaFlux::Nodes::PENDING_REMOVAL.
Referenced by MayaFlux::Kriya::TemporalActivation::cleanup_current_operation(), and terminate_all_nodes().