MayaFlux: MayaFlux::Buffers::GeometryWriteProcessor::processing_function
processing_function()
void MayaFlux::Buffers::GeometryWriteProcessor::processing_function (const std::shared_ptr< Buffer > & buffer) override protected virtual
The core processing function that must be implemented by derived classes.
Parameters
buffer Buffer to process
This method is where the actual transformation logic is implemented. It should contain the algorithmic details of how the buffer's data is transformed, analyzed, or processed. The implementation can utilize any backend capabilities available to the processor, including:
Parallel Processing: Using multi-threading or GPU compute for large datasets
Data Transformations: Applying mathematical operations, filters, or effects
Feature Extraction: Analyzing data characteristics for further processing
Derived classes must override this method to provide specific processing behavior.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 62 of file GeometryWriteProcessor.cpp.
{
    auto vk = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "GeometryWriteProcessor attached to non-VKBuffer");
        return;
    }
    if (m_vertices_dirty.test(std::memory_order_acquire)) {
        m_vertices_dirty.clear(std::memory_order_release);
        std::swap(m_active_vertices, m_pending_vertices);
        if (m_active_vertices.has_value()) {
            const size_t required = m_active_vertices->bytes.size();
            const size_t available = vk->get_size_bytes();
            if (required > available) {
                vk->resize(static_cast<size_t>((float)required * 1.5F), false);
                if (m_staging) {
                    m_staging = create_staging_buffer(vk->get_size_bytes());
                }
            }
            upload_to_gpu(m_active_vertices->bytes.data(),
                std::min<size_t>(required, vk->get_size_bytes()),
                vk, m_staging);
            vk->set_vertex_layout(m_active_vertices->layout);
            return;
        }
    }
    if (!m_data_dirty.test(std::memory_order_acquire)) {
        return;
    }
    m_data_dirty.clear(std::memory_order_release);
    std::swap(m_active_data, m_pending_data);
    if (!m_active_data.has_value()) {
        return;
    }
    std::optional<Kakshya::VertexAccess> access;
    switch (m_mode) {
    case GeometryWriteMode::LINE:
        access = Kakshya::as_line_vertex_access(*m_active_data, m_config);
        break;
    case GeometryWriteMode::MESH:
        access = Kakshya::as_mesh_vertex_access(*m_active_data, m_config);
        break;
    case GeometryWriteMode::POINT:
        access = Kakshya::as_point_vertex_access(*m_active_data, m_config);
        break;
    }
    if (!access.has_value()) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "GeometryWriteProcessor: as_vertex_access returned nullopt — unsupported variant type");
        return;
    }
    upload_resizing(access->data_ptr, access->byte_count, vk, m_staging);
    vk->set_vertex_layout(access->layout);
}
References MayaFlux::Kakshya::as_line_vertex_access(), MayaFlux::Kakshya::as_mesh_vertex_access(), MayaFlux::Kakshya::as_point_vertex_access(), MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Buffers::LINE, m_active_data, m_active_vertices, m_config, m_data_dirty, m_mode, m_pending_data, m_pending_vertices, m_staging, m_vertices_dirty, MayaFlux::Buffers::MESH, MF_RT_ERROR, MayaFlux::Buffers::POINT, MayaFlux::Buffers::upload_resizing(), and MayaFlux::Buffers::upload_to_gpu().