MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::process_unidirectional
process_unidirectional()
void MayaFlux::Nodes::Network::WaveguideNetwork::process_unidirectional (WaveguideSegment & seg, unsigned int num_samples) private
Definition at line 148 of file WaveguideNetwork.cpp.
{
    for (unsigned int i = 0; i < num_samples; ++i) {
        const double exciter = generate_exciter_sample();
        const double delayed = read_with_interpolation(
            seg.p_plus, m_delay_length_integer, m_delay_length_fraction);
        const double filtered = seg.loop_filter ? seg.loop_filter->process_sample(delayed)
                                                : delayed;
        seg.p_plus.push(
            exciter + filtered * seg.loss_factor * seg.reflection_closed);
        m_last_audio_buffer.push_back(observe_sample(seg));
    }
}
References generate_exciter_sample(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loop_filter, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loss_factor, m_delay_length_fraction, m_delay_length_integer, MayaFlux::Nodes::Network::NodeNetwork::m_last_audio_buffer, observe_sample(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::p_plus, MayaFlux::Memory::HistoryBuffer< T >::push(), read_with_interpolation(), and MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::reflection_closed.
Referenced by process_batch().