MayaFlux: Lila::EventBus::publish
publish()
void Lila::EventBus::publish (const StreamEvent & event)
Publish an event to all subscribers of its type.
Parameters
event The event to publish
Definition at line 18 of file EventBus.cpp.
{
    std::vector<std::shared_ptr<Subscription>> active_subscribers;
    {
        std::lock_guard lock(m_mutex);
        auto it = m_subscribers.find(event.type);
        if (it == m_subscribers.end())
            return;
        auto& subscribers = it->second;
        subscribers.erase(
            std::remove_if(subscribers.begin(), subscribers.end(),
                [&active_subscribers](const std::weak_ptr<Subscription>& weak) {
                    if (auto shared = weak.lock()) {
                        active_subscribers.push_back(shared);
                        return false;
                    }
                    return true;
                }),
            subscribers.end());
    }
    for (auto& subscriber : active_subscribers) {
        subscriber->on_event(event);
    }
}
References m_mutex, m_subscribers, and Lila::StreamEvent::type.
Referenced by Lila::Server::cleanup_client(), Lila::Server::handle_client(), Lila::Server::start(), and Lila::Server::stop().