MayaFlux: MayaFlux::Kriya::TemporalActivation::cleanup_current_operation
cleanup_current_operation()
void MayaFlux::Kriya::TemporalActivation::cleanup_current_operation () private
Cleans up the current operation, disconnecting the entity and resetting state.
This method is called when the timer completes its specified duration. It disconnects the currently active node/nodenetwork/buffer from the output channels or graphics syc, or active and resets internal state to allow new operations to be started.
Definition at line 148 of file Timers.cpp.
{
    switch (m_active_type) {
    case ActiveType::NODE:
        if (m_current_node) {
            if (m_channels.empty()) {
                m_node_graph_manager.get_root_node(m_node_token, 0).unregister_node(m_current_node);
            }
            for (auto channel : m_channels) {
                if (m_current_node->is_used_by_channel(channel)) {
                    m_node_graph_manager.get_root_node(m_node_token, channel).unregister_node(m_current_node);
                }
            }
            m_current_node = nullptr;
            m_channels.clear();
        }
        break;
    case ActiveType::NETWORK:
        if (m_current_network) {
            for (const auto& ch : m_channels) {
                m_current_network->remove_channel_usage(ch);
            }
            m_node_graph_manager.remove_network(m_current_network, m_node_token);
            m_current_network = nullptr;
        }
        break;
    case ActiveType::BUFFER:
        if (m_current_buffer) {
            for (auto channel : m_channels) {
                m_buffer_manager.remove_buffer(m_current_buffer, m_buffer_token, channel);
            }
            m_current_buffer = nullptr;
        }
        break;
    case ActiveType::NONE:
        break;
    }
    m_active_type = ActiveType::NONE;
}
References BUFFER, MayaFlux::Nodes::NodeGraphManager::get_root_node(), m_active_type, m_buffer_manager, m_buffer_token, m_channels, m_current_buffer, m_current_network, m_current_node, m_node_graph_manager, m_node_token, NETWORK, NODE, NONE, MayaFlux::Buffers::BufferManager::remove_buffer(), MayaFlux::Nodes::NodeGraphManager::remove_network(), and MayaFlux::Nodes::RootNode::unregister_node().
Referenced by activate_buffer(), activate_network(), activate_node(), and cancel().