MayaFlux: MayaFlux::Buffers::BufferAccessControl::add_audio_buffer
add_audio_buffer()
void MayaFlux::Buffers::BufferAccessControl::add_audio_buffer (const std::shared_ptr< AudioBuffer > & buffer, ProcessingToken token, uint32_t channel)
Adds an audio buffer to a token and channel.
Parameters
buffer Audio buffer to add
token Processing domain
channel Channel index
Definition at line 143 of file BufferAccessControl.cpp.
{
    ensure_audio_channels(token, channel + 1);
    auto& unit = m_unit_manager.get_or_create_audio_unit(token);
    auto processing_chain = unit.get_chain(channel);
    buffer->set_channel_id(channel);
    buffer->setup_processors(token);
    if (auto buf_chain = buffer->get_processing_chain()) {
        if (buf_chain != processing_chain) {
            processing_chain->merge_chain(buf_chain);
        }
    } else {
        buffer->set_processing_chain(processing_chain);
    }
    {
        if (buffer->get_num_samples() != unit.buffer_size) {
            MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
                "Resizing buffer to match unit size: {} samples", unit.buffer_size);
            std::lock_guard<std::mutex> lock(m_unit_manager.get_mutex());
            buffer->resize(unit.buffer_size);
        }
    }
    unit.get_buffer(channel)->add_child_buffer(buffer);
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, ensure_audio_channels(), MayaFlux::Buffers::RootAudioUnit::get_chain(), MayaFlux::Buffers::TokenUnitManager::get_mutex(), MayaFlux::Buffers::TokenUnitManager::get_or_create_audio_unit(), m_unit_manager, and MF_ERROR.
Referenced by add_buffer(), and MayaFlux::Buffers::BufferSupplyMixing::clone_audio_buffer_for_channels().