MayaFlux: MayaFlux::Nodes::NodeGraphManager::terminate_active_processing
terminate_active_processing()
void MayaFlux::Nodes::NodeGraphManager::terminate_active_processing ()
Terminates all active processing across all tokens and channels.
This method stops all active processing contexts in all root nodes and networks, ensuring a clean shutdown of processing activities.
Definition at line 624 of file NodeGraphManager.cpp.
{
    if (m_terminate_requested.load())
        return;
    for (auto& [token, networks] : m_audio_networks) {
        for (auto& network : networks) {
            if (network) {
                unregister_network_global(network);
            }
        }
    }
    for (auto& [token, networks] : m_token_networks) {
        for (auto& network : networks) {
            if (network) {
                unregister_network_global(network);
            }
        }
    }
    m_terminate_requested.store(true);
    for (auto token : get_active_tokens()) {
        auto roots = get_all_root_nodes(token);
        for (auto* root : roots) {
            root->terminate_all_nodes();
        }
    }
}
References get_active_tokens(), get_all_root_nodes(), m_audio_networks, m_terminate_requested, m_token_networks, and unregister_network_global().
Referenced by ~NodeGraphManager().