MayaFlux: MayaFlux::Nodes::GpuSync::GlyphGeometryNode::write_vertices
write_vertices()
void MayaFlux::Nodes::GpuSync::GlyphGeometryNode::write_vertices () private
Definition at line 145 of file GlyphGeometryNode.cpp.
{
    size_t total_pairs = 0;
    for (const auto& ol : m_outlines) {
        uint32_t prev_end = 0;
        for (uint32_t end : ol.contour_ends) {
            const uint32_t count = end - prev_end;
            if (count >= 2)
                total_pairs += count - 1;
            prev_end = end;
        }
    }
    std::vector<Kakshya::LineVertex> verts;
    verts.reserve(total_pairs * 2);
    for (size_t gi = 0; gi < m_outlines.size(); ++gi) {
        const auto& ol = m_outlines[gi];
        const glm::vec2 off = m_pen_offsets[gi];
        uint32_t prev_end = 0;
        for (uint32_t end : ol.contour_ends) {
            const uint32_t count = end - prev_end;
            if (count < 2) {
                prev_end = end;
                continue;
            }
            for (uint32_t pi = prev_end; pi < end - 1; ++pi) {
                const glm::vec2 a = ol.points[pi] + off;
                const glm::vec2 b = ol.points[pi + 1] + off;
                verts.push_back({ .position = { a.x, a.y, 0.F }, .color = m_color, .thickness = m_thickness });
                verts.push_back({ .position = { b.x, b.y, 0.F }, .color = m_color, .thickness = m_thickness });
            }
            prev_end = end;
        }
    }
    set_vertices<Kakshya::LineVertex>(std::span { verts.data(), verts.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(verts.size());
    set_vertex_layout(*layout);
    m_vertex_data_dirty = true;
    m_dirty = false;
}
References a, b, count, MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout(), m_color, m_dirty, m_outlines, m_pen_offsets, m_thickness, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout().
Referenced by compute_frame(), and rebuild_outlines().