MayaFlux: MayaFlux::Buffers::RenderProcessor::bind_texture
bind_texture() [2/2]
void MayaFlux::Buffers::RenderProcessor::bind_texture (uint32_t binding, const std::shared_ptr< Core::VKImage > & texture, vk::Sampler sampler = nullptr)
Bind a texture to a descriptor binding point.
Parameters
binding Binding index (matches shader layout(binding = N))
texture VKImage texture to bind
sampler Optional sampler (uses default linear if null)
Definition at line 121 of file RenderProcessor.cpp.
{
    if (!texture || !texture->is_initialized() || !texture->get_image_view()) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot bind null texture to binding {}", binding);
        return;
    }
    if (!sampler) {
        auto& loom = Portal::Graphics::get_texture_manager();
        sampler = loom.get_default_sampler();
    }
    m_texture_bindings[binding] = { .texture = texture, .sampler = sampler };
    m_needs_descriptor_rebuild = true;
    if (m_pipeline_id != Portal::Graphics::INVALID_RENDER_PIPELINE && !m_descriptor_set_ids.empty()) {
        auto& foundry = Portal::Graphics::get_shader_foundry();
        auto cfg_it = std::ranges::find_if(m_config.bindings,
            [binding](const auto& pair) {
                return binding >= pair.second.binding
                    && binding < pair.second.binding + pair.second.count;
            });
        if (cfg_it != m_config.bindings.end() && !m_descriptor_set_ids.empty()) {
            const uint32_t cfg_set = cfg_it->second.set;
            if (cfg_set == 0) {
                if (m_view_transform_descriptor_set_id != Portal::Graphics::INVALID_DESCRIPTOR_SET) {
                    uint32_t array_idx = 0;
                    if (cfg_it->second.count > 1 && binding >= cfg_it->second.binding) {
                        array_idx = binding - cfg_it->second.binding;
                    }
                    foundry.update_descriptor_image(
                        m_view_transform_descriptor_set_id,
                        cfg_it->second.binding,
                        texture->get_image_view(),
                        sampler,
                        vk::ImageLayout::eShaderReadOnlyOptimal,
                        array_idx);
                }
            } else {
                auto ds_index = resolve_ds_index(cfg_set);
                if (ds_index && *ds_index < m_descriptor_set_ids.size()) {
                    foundry.update_descriptor_image(
                        m_descriptor_set_ids[*ds_index],
                        cfg_it->second.binding,
                        texture->get_image_view(),
                        sampler,
                        vk::ImageLayout::eShaderReadOnlyOptimal);
                }
            }
        }
    }
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Bound texture to binding {}", binding);
}
References MayaFlux::Buffers::ShaderConfig::bindings, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::get_texture_manager(), MayaFlux::Portal::Graphics::INVALID_DESCRIPTOR_SET, MayaFlux::Portal::Graphics::INVALID_RENDER_PIPELINE, MayaFlux::Buffers::ShaderProcessor::m_config, MayaFlux::Buffers::ShaderProcessor::m_descriptor_set_ids, MayaFlux::Buffers::ShaderProcessor::m_needs_descriptor_rebuild, m_pipeline_id, m_texture_bindings, m_view_transform_descriptor_set_id, MF_DEBUG, MF_ERROR, and MayaFlux::Buffers::ShaderProcessor::resolve_ds_index().
Referenced by bind_texture().