MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized
is_initialized()
bool MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized () const inline
Check if compiler is initialized.
Definition at line 139 of file ShaderFoundry.hpp.
{ return m_backend != nullptr; }
Referenced by compile_from_file(), compile_from_source(), compile_from_spirv(), MayaFlux::Portal::Graphics::ComputePress::initialize(), MayaFlux::Portal::Graphics::RenderFlow::initialize(), load_shader(), MayaFlux::Portal::Graphics::ComputePress::shutdown(), and MayaFlux::Portal::Graphics::RenderFlow::shutdown().