MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::build_vertex_buffer
build_vertex_buffer()
void MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::build_vertex_buffer () private
Definition at line 251 of file TopologyGeneratorNode.cpp.
{
    m_vertices.clear();
    auto points = get_points();
    size_t num_points = points.size();
    if (m_mode == Kinesis::ProximityMode::SEQUENTIAL
        && num_points >= 2
        && m_path_interpolation_mode != Kinesis::InterpolationMode::LINEAR) {
        build_interpolated_path(points, num_points);
    } else {
        build_direct_connections(points, num_points);
    }
    m_vertex_data_dirty = true;
}
References build_direct_connections(), build_interpolated_path(), get_points(), MayaFlux::Kinesis::LINEAR, m_mode, m_path_interpolation_mode, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, m_vertices, and MayaFlux::Kinesis::SEQUENTIAL.
Referenced by compute_frame().