MayaFlux: MayaFlux::Core::BackendResourceManager::find_memory_type
find_memory_type()
uint32_t MayaFlux::Core::BackendResourceManager::find_memory_type (uint32_t type_filter, vk::MemoryPropertyFlags properties) const
Find a suitable memory type for Vulkan buffer allocation.
Parameters
type_filter Memory type bits filter
properties Desired memory property flags
Returns
Index of the suitable memory type
Definition at line 776 of file BackendResoureManager.cpp.
{
    vk::PhysicalDeviceMemoryProperties mem_properties;
    mem_properties = m_context.get_physical_device().getMemoryProperties();
    for (uint32_t i = 0; i < mem_properties.memoryTypeCount; i++) {
        if ((type_filter & (1 << i)) && (mem_properties.memoryTypes[i].propertyFlags & properties) == properties) {
            return i;
        }
    }
    error<std::runtime_error>(
        Journal::Component::Core,
        Journal::Context::GraphicsBackend,
        std::source_location::current(),
        "Failed to find suitable memory type");
    return 0;
}
References MayaFlux::Journal::Core, MayaFlux::Core::VKContext::get_physical_device(), MayaFlux::Journal::GraphicsBackend, and m_context.
Referenced by initialize_buffer(), and initialize_image().