MayaFlux: MayaFlux::IO::SoundFileReader::open
open()
bool MayaFlux::IO::SoundFileReader::open (const std::string & filepath, FileReadOptions options = FileReadOptions::ALL) override virtual
Open an audio file for reading.
Parameters
filepath Path to the file.
options File read options.
Returns
True if the file was opened successfully.
Implements MayaFlux::IO::FileReader.
Definition at line 130 of file SoundFileReader.cpp.
{
    std::unique_lock<std::shared_mutex> lock(m_context_mutex);
    if (m_context) {
        m_context.reset();
        m_current_frame_position = 0;
        m_cached_metadata.reset();
        m_cached_regions.clear();
    }
    m_filepath = filepath;
    m_options = options;
    clear_error();
    auto ctx = std::make_shared<FFmpegContext>();
    if (avformat_open_input(&ctx->format_context, filepath.c_str(), nullptr, nullptr) < 0) {
        set_error("Failed to open file: " + filepath);
        return false;
    }
    if (avformat_find_stream_info(ctx->format_context, nullptr) < 0) {
        set_error("Failed to find stream info");
        return false;
    }
    const AVCodec* codec = nullptr;
    ctx->audio_stream_index = av_find_best_stream(
        ctx->format_context, AVMEDIA_TYPE_AUDIO, -1, -1, &codec, 0);
    if (ctx->audio_stream_index < 0 || !codec) {
        set_error("No audio stream found");
        return false;
    }
    ctx->codec_context = avcodec_alloc_context3(codec);
    if (!ctx->codec_context) {
        set_error("Failed to allocate codec context");
        return false;
    }
    AVStream* stream = ctx->format_context->streams[ctx->audio_stream_index];
    if (avcodec_parameters_to_context(ctx->codec_context, stream->codecpar) < 0) {
        set_error("Failed to copy codec parameters");
        return false;
    }
    if (avcodec_open2(ctx->codec_context, codec, nullptr) < 0) {
        set_error("Failed to open codec");
        return false;
    }
    if (stream->duration != AV_NOPTS_VALUE && stream->time_base.num && stream->time_base.den) {
        double duration_seconds = stream->duration * av_q2d(stream->time_base);
        ctx->total_frames = static_cast<uint64_t>(duration_seconds * ctx->codec_context->sample_rate);
    } else if (ctx->format_context->duration != AV_NOPTS_VALUE) {
        double duration_seconds = ctx->format_context->duration / static_cast<double>(AV_TIME_BASE);
        ctx->total_frames = static_cast<uint64_t>(duration_seconds * ctx->codec_context->sample_rate);
    } else {
        ctx->total_frames = 0;
    }
    ctx->sample_rate = ctx->codec_context->sample_rate;
    ctx->channels = ctx->codec_context->ch_layout.nb_channels;
    if (!setup_resampler(ctx)) {
        set_error("Failed to setup resampler");
        return false;
    }
    if (!ctx->is_valid()) {
        set_error("Invalid context after initialization");
        return false;
    }
    if ((options & FileReadOptions::EXTRACT_METADATA) != FileReadOptions::NONE) {
        extract_metadata(ctx);
    }
    if ((options & FileReadOptions::EXTRACT_REGIONS) != FileReadOptions::NONE) {
        extract_regions(ctx);
    }
    m_context = std::move(ctx);
    m_current_frame_position = 0;
    return true;
}
References clear_error(), MayaFlux::IO::EXTRACT_METADATA, extract_metadata(), MayaFlux::IO::EXTRACT_REGIONS, extract_regions(), m_cached_metadata, m_cached_regions, m_context, m_context_mutex, m_current_frame_position, m_filepath, m_options, MayaFlux::IO::NONE, set_error(), and setup_resampler().