MayaFlux: MayaFlux::Nodes::RootNode::process_sample
process_sample()
double MayaFlux::Nodes::RootNode::process_sample ()
Processes a single sample from all registered nodes.
Returns
Combined output sample from all nodes
This method processes each registered node and combines their outputs into a single sample. It is typically called in a loop to process multiple samples, but can also be used for single-sample processing.
Definition at line 118 of file RootNode.cpp.
{
    if (!preprocess())
        return 0.;
    auto sample = 0.;
    for (auto& node : m_Nodes) {
        if (!node)
            continue;
        uint32_t state = node->m_state.load();
        double node_output = 0.0;
        if (!(state & NodeState::PROCESSED)) {
            auto generator = std::dynamic_pointer_cast<Nodes::Generator::Generator>(node);
            if (generator && generator->should_mock_process()) {
                generator->process_sample();
            } else {
                node_output = node->process_sample();
            }
            atomic_add_flag(node->m_state, NodeState::PROCESSED);
        } else {
            node_output = node->get_last_output();
        }
        if (node->needs_channel_routing()) {
            node_output *= node->get_routing_state().amount[m_channel];
        }
        sample += node_output;
    }
    postprocess();
    return sample;
}
References MayaFlux::Nodes::atomic_add_flag(), m_channel, m_Nodes, postprocess(), preprocess(), and MayaFlux::Nodes::PROCESSED.
Referenced by process_batch().