MayaFlux: MayaFlux::Kriya::BufferOperation::is_capture_phase_operation
is_capture_phase_operation()
bool MayaFlux::Kriya::BufferOperation::is_capture_phase_operation (const BufferOperation & op) static
Definition at line 243 of file BufferOperation.cpp.
{
    if (op.get_execution_phase() == BufferOperation::ExecutionPhase::CAPTURE) {
        return true;
    }
    if (op.get_execution_phase() == BufferOperation::ExecutionPhase::PROCESS) {
        return false;
    }
    switch (op.get_type()) {
    case BufferOperation::OpType::CAPTURE:
        return true;
    case BufferOperation::OpType::MODIFY:
        return op.is_streaming();
    default:
        return false;
    }
}
References CAPTURE, get_execution_phase(), get_type(), is_streaming(), MODIFY, and PROCESS.
Referenced by MayaFlux::Kriya::BufferPipeline::execute_phased().