MayaFlux: MayaFlux::IO::FFmpegMuxContext::open
open()
bool MayaFlux::IO::FFmpegMuxContext::open (const std::string & filepath, const std::string & explicit_format = {})
Allocate an output context and open the avio layer for writing.
Format is inferred from the filepath extension via avformat_alloc_output_context2. Pass explicit_format to override (e.g. "matroska" to force MKV regardless of extension).
Does NOT write any data to disk. Call write_header() after all stream contexts have been opened on this mux context.
Parameters
filepath Output file path. Extension determines container.
explicit_format FFmpeg short format name override; empty = infer.
Returns
True on success; false sets the internal error string.
Definition at line 26 of file FFmpegMuxContext.cpp.
{
    close();
    FFmpegDemuxContext::init_ffmpeg();
    const char* fmt = explicit_format.empty() ? nullptr : explicit_format.c_str();
    const auto resolved = resolve_write_path(filepath);
    int ret = avformat_alloc_output_context2(
        &format_context, nullptr, fmt, resolved.c_str());
    if (ret < 0 || !format_context) {
        char errbuf[AV_ERROR_MAX_STRING_SIZE];
        av_strerror(ret, errbuf, sizeof(errbuf));
        m_last_error = "avformat_alloc_output_context2 failed for \""
            + resolved + "\": " + errbuf;
        return false;
    }
    if (!(format_context->oformat->flags & AVFMT_NOFILE)) {
        ret = avio_open(&format_context->pb, resolved.c_str(), AVIO_FLAG_WRITE);
        if (ret < 0) {
            char errbuf[AV_ERROR_MAX_STRING_SIZE];
            av_strerror(ret, errbuf, sizeof(errbuf));
            m_last_error = "avio_open failed for \""
                + resolved + "\": " + errbuf;
            avformat_free_context(format_context);
            format_context = nullptr;
            return false;
        }
    }
    return true;
}
References close(), format_context, MayaFlux::IO::FFmpegDemuxContext::init_ffmpeg(), m_last_error, and MayaFlux::IO::resolve_write_path().
Referenced by MayaFlux::IO::SoundFileWriter::worker_loop(), and MayaFlux::IO::VideoFileWriter::worker_loop().