MayaFlux: MayaFlux::Nexus::Emitter::render
render() [2/2]
void MayaFlux::Nexus::Emitter::render (Buffers::BufferManager & mgr, const Portal::Graphics::RenderConfig & config, std::string fn_name, RenderFn fn) inline
Register a render output targeting window with a producer function.
Definition at line 111 of file Emitter.hpp.
    {
        add_render_sink(m_render_sinks, mgr, config, std::move(fn), std::move(fn_name), m_position);
    }
References MayaFlux::Nexus::add_render_sink(), fn(), fn_name(), m_position, and m_render_sinks.