MayaFlux: MayaFlux::IO::SoundFileReader::load_into_container
load_into_container()
bool MayaFlux::IO::SoundFileReader::load_into_container (std::shared_ptr< Kakshya::SignalSourceContainer > container) override virtual
Load file data into an existing SignalSourceContainer.
Parameters
container Target container.
Returns
True if loading succeeded.
Implements MayaFlux::IO::FileReader.
Definition at line 815 of file SoundFileReader.cpp.
{
    if (!container) {
        set_error("Invalid container");
        return false;
    }
    auto sound_container = std::dynamic_pointer_cast<Kakshya::SoundFileContainer>(container);
    if (!sound_container) {
        set_error("Container is not a SoundFileContainer");
        return false;
    }
    auto metadata = get_metadata();
    if (!metadata) {
        set_error("Failed to get metadata");
        return false;
    }
    auto total_frames = metadata->get_attribute<uint64_t>("total_frames").value_or(0);
    auto sample_rate = metadata->get_attribute<uint32_t>("sample_rate").value_or(48000);
    auto channels = metadata->get_attribute<uint32_t>("channels").value_or(2);
    sound_container->setup(total_frames, sample_rate, channels);
    if ((m_audio_options & AudioReadOptions::DEINTERLEAVE) != AudioReadOptions::NONE) {
        sound_container->get_structure().organization = Kakshya::OrganizationStrategy::PLANAR;
    } else {
        sound_container->get_structure().organization = Kakshya::OrganizationStrategy::INTERLEAVED;
    }
    std::vector<Kakshya::DataVariant> audio_data = read_all();
    if (audio_data.empty()) {
        set_error("Failed to read audio data");
        return false;
    }
    sound_container->set_raw_data(audio_data);
    auto regions = get_regions();
    auto region_groups = regions_to_groups(regions);
    for (const auto& [name, group] : region_groups) {
        sound_container->add_region_group(group);
    }
    sound_container->create_default_processor();
    sound_container->mark_ready_for_processing(true);
    return true;
}
References MayaFlux::IO::DEINTERLEAVE, get_metadata(), get_regions(), MayaFlux::Kakshya::INTERLEAVED, m_audio_options, MayaFlux::IO::NONE, MayaFlux::Kakshya::PLANAR, read_all(), MayaFlux::IO::FileReader::regions_to_groups(), and set_error().
Referenced by create_container().