MayaFlux: MayaFlux::Kakshya::WindowContainer::image_at
image_at() [2/2]
std::shared_ptr< Core::VKImage > MayaFlux::Kakshya::WindowContainer::image_at (uint32_t frame_index, const std::shared_ptr< Buffers::VKBuffer > & staging) const
Upload m_data[frame_index] reusing a caller-supplied staging buffer.
Parameters
frame_index Index into m_data in [0, frame_capacity).
staging Host-visible VKBuffer sized to at least w * h * bpp.
Definition at line 289 of file WindowContainer.cpp.
{
    if (frame_index >= m_data.size()) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::image_at(staging, {}) : out of range (capacity={})",
            frame_index, m_frame_capacity);
        return nullptr;
    }
    const uint64_t written = m_frames_written.load(std::memory_order_acquire);
    const uint32_t head = m_write_head.load(std::memory_order_acquire);
    const bool ring_full = written >= m_frame_capacity;
    if (!ring_full && frame_index >= head) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::image_at(staging, {}) : frame index is ahead of write head ({}), data may be stale or uninitialized",
            frame_index, head);
        return nullptr;
    }
    std::shared_ptr<Core::VKImage> img;
    seqlock_read_void(m_data_lock, 8, [&] {
        const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_data[frame_index]);
        if (!pixels || pixels->empty()) {
            MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
                "WindowContainer::image_at(staging, {}) — slot is empty", frame_index);
            return;
        }
        const auto img_fmt = surface_format_to_image_format(query_surface_format(m_window));
        auto& loom = Portal::Graphics::TextureLoom::instance();
        img = loom.create_2d(m_structure.get_width(), m_structure.get_height(), img_fmt, nullptr);
        if (!img) {
            MF_RT_ERROR(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
                "WindowContainer::image_at(staging, {}) : VKImage allocation failed", frame_index);
            return;
        }
        loom.upload_data(img, pixels->data(), pixels->size(), staging);
    });
    return img;
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), MayaFlux::Portal::Graphics::TextureLoom::instance(), MayaFlux::Journal::Kakshya, m_data, m_data_lock, m_frame_capacity, m_frames_written, m_structure, m_window, m_write_head, MF_RT_ERROR, MF_RT_WARN, pixels, and MayaFlux::Kakshya::query_surface_format().