MayaFlux: MayaFlux::Nodes::Input::InputNode::process_sample
process_sample()
double MayaFlux::Nodes::Input::InputNode::process_sample (double input = 0.0) override virtual
Process a single sample.
Parameters
input Unused (InputNodes generate from external input)
Returns
Current smoothed input value
Implements MayaFlux::Nodes::Node.
Definition at line 18 of file InputNode.cpp.
{
    double target = m_target_value.load();
    double current = m_current_value.load();
    double output = apply_smoothing(target, current);
    m_current_value.store(output);
    m_last_output = output;
    notify_tick(output);
    return output;
}
References apply_smoothing(), m_current_value, MayaFlux::Nodes::Node::m_last_output, m_target_value, and notify_tick().
Referenced by process_batch().