MayaFlux: MayaFlux::Buffers::BufferProcessingControl::connect_node_to_audio_channel
connect_node_to_audio_channel()
void MayaFlux::Buffers::BufferProcessingControl::connect_node_to_audio_channel (const std::shared_ptr< Nodes::Node > & node, ProcessingToken token, uint32_t channel, float mix = 0.5F, bool clear_before = false)
Connects a node to a specific audio token and channel.
Parameters
node Node to connect
token Processing domain
channel Channel index
mix Mix level (default: 0.5)
clear_before Whether to clear buffer before adding node output (default: false)
Creates a NodeSourceProcessor that feeds node output into the channel.
Definition at line 281 of file BufferProcessingControl.cpp.
{
    m_access_control.ensure_audio_channels(token, channel + 1);
    auto processor = std::make_shared<NodeSourceProcessor>(node, mix, clear_before);
    processor->set_processing_token(token);
    add_audio_processor_to_channel(processor, token, channel);
}
References add_audio_processor_to_channel(), MayaFlux::Buffers::BufferAccessControl::ensure_audio_channels(), m_access_control, and MayaFlux::mix().