MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::create_shader_module
create_shader_module()
std::shared_ptr< Core::VKShaderModule > MayaFlux::Portal::Graphics::ShaderFoundry::create_shader_module () private
Definition at line 1280 of file ShaderFoundry.cpp.
{
    return std::make_shared<Core::VKShaderModule>();
}
Referenced by compile_from_file(), compile_from_source(), and compile_from_spirv().