MayaFlux: MayaFlux::Buffers::BufferAccessControl::ensure_audio_channels
ensure_audio_channels()
void MayaFlux::Buffers::BufferAccessControl::ensure_audio_channels (ProcessingToken token, uint32_t channel_count)
Ensures minimum number of audio channels exist for a token.
Parameters
token Processing domain
channel_count Minimum number of channels to ensure
Definition at line 55 of file BufferAccessControl.cpp.
{
    m_unit_manager.ensure_audio_channels(token, channel_count);
}
References MayaFlux::Buffers::TokenUnitManager::ensure_audio_channels(), and m_unit_manager.
Referenced by add_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::connect_node_to_audio_channel(), and get_audio_processing_chain().