MayaFlux: MayaFlux::Nodes::GpuSync::PathGeneratorNode::generate_path_vertices
generate_path_vertices()
void MayaFlux::Nodes::GpuSync::PathGeneratorNode::generate_path_vertices () private
Definition at line 346 of file PathGeneratorNode.cpp.
{
    m_vertices.clear();
    const size_t num_points = m_control_points.size();
    if (num_points < 2) {
        return;
    }
    if (m_mode == Kinesis::InterpolationMode::LINEAR) {
        generate_direct_path();
    } else if (m_mode == Kinesis::InterpolationMode::CUSTOM && m_custom_func) {
        generate_custom_path();
    } else {
        generate_interpolated_path();
    }
    m_vertex_data_dirty = true;
}
References MayaFlux::Kinesis::CUSTOM, generate_custom_path(), generate_direct_path(), generate_interpolated_path(), MayaFlux::Kinesis::LINEAR, m_control_points, m_custom_func, m_mode, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, and m_vertices.
Referenced by regenerate_geometry().