MayaFlux: MayaFlux::Buffers::VideoContainerBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::VideoContainerBuffer::setup_processors (ProcessingToken token) override virtual
Override to wire VideoStreamReader as default and TextureProcessor as preprocessor.
Parameters
token Processing token (typically GRAPHICS_BACKEND).
Reimplemented from MayaFlux::Buffers::TextureBuffer.
Definition at line 224 of file VideoContainerBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<VideoContainerBuffer>(shared_from_this());
    m_video_reader = std::make_shared<VideoStreamReader>(m_container);
    m_video_reader->set_processing_token(token);
    set_default_processor(m_video_reader);
    enforce_default_processing(true);
    auto texture_proc = std::make_shared<TextureProcessor>();
    texture_proc->set_streaming_mode(true);
    texture_proc->set_processing_token(token);
    set_texture_processor(texture_proc);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
    chain->add_preprocessor(texture_proc, self);
    MF_INFO(Journal::Component::Buffers, Journal::Context::Init,
        "VideoContainerBuffer setup_processors: VideoStreamReader as default, "
        "TextureProcessor as preprocessor");
}
References MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::enforce_default_processing(), MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Journal::Init, m_container, m_video_reader, MF_INFO, MayaFlux::Buffers::VKBuffer::set_default_processor(), MayaFlux::Buffers::VKBuffer::set_processing_chain(), and MayaFlux::Buffers::TextureBuffer::set_texture_processor().