MayaFlux: MayaFlux::Yantra::GpuDispatchCore::readback_aux
readback_aux()
void MayaFlux::Yantra::GpuDispatchCore::readback_aux (GpuChannelResult & result) protected
Read back all OUTPUT bindings that have explicit size overrides into the aux map of a GpuChannelResult.
Parameters
result GpuChannelResult to write aux entries into.
Definition at line 364 of file GpuDispatchCore.cpp.
{
    for (size_t i = 0; i < m_bindings.size(); ++i) {
        if (m_bindings[i].skip_auto_readback)
            continue;
        const auto dir = m_bindings[i].direction;
        const auto et = m_bindings[i].element_type;
        const bool is_image = et == GpuBufferBinding::ElementType::IMAGE_STORAGE
            || et == GpuBufferBinding::ElementType::IMAGE_SAMPLED;
        if ((dir == GpuBufferBinding::Direction::OUTPUT
                || dir == GpuBufferBinding::Direction::INPUT_OUTPUT)
            && !is_image
            && i < m_output_size_overrides.size()
            && m_output_size_overrides[i] > 0) {
            const size_t sz = m_output_size_overrides[i];
            std::vector<uint8_t> raw(sz);
            m_resources.download(i, reinterpret_cast<float*>(raw.data()), sz);
            result.aux[i] = std::move(raw);
        }
    }
}
References MayaFlux::Yantra::GpuChannelResult::aux, MayaFlux::Yantra::GpuResourceManager::download(), MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, MayaFlux::Yantra::GpuBufferBinding::INPUT_OUTPUT, MayaFlux::is_image(), m_bindings, m_output_size_overrides, m_resources, and MayaFlux::Yantra::GpuBufferBinding::OUTPUT.
Referenced by MayaFlux::Yantra::ShaderExecutionContext< InputType, OutputType >::collect_result(), dispatch_core(), and dispatch_core_chained().