MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::stop
stop()
void MayaFlux::Portal::Graphics::ShaderFoundry::stop ()
Stop active command recording and free command buffers.
Frees all command buffers back to pool and destroys query pools. Call this BEFORE destroying pipelines/resources that command buffers reference. Does NOT destroy the command pool itself - that happens in shutdown().
Definition at line 54 of file ShaderFoundry.cpp.
{
    if (!s_initialized || !m_backend) {
        return;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "Stopping ShaderFoundry - freeing command buffers...");
    auto device = get_device();
    device.waitIdle();
    free_all_command_buffers();
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "ShaderFoundry stopped - command buffers freed");
}
References free_all_command_buffers(), get_device(), m_backend, MF_INFO, MayaFlux::Journal::Portal, s_initialized, and MayaFlux::Journal::ShaderCompilation.
Referenced by MayaFlux::Portal::Graphics::stop().