MayaFlux: MayaFlux::IO::ModelReader::open
open()
bool MayaFlux::IO::ModelReader::open (const std::string & filepath, FileReadOptions options = FileReadOptions::ALL) override virtual
Open a file for reading.
Parameters
filepath Path to the file.
options Reading options (see FileReadOptions).
Returns
true if file was successfully opened.
Implements MayaFlux::IO::FileReader.
Definition at line 247 of file ModelReader.cpp.
{
    close();
    auto resolved = resolve_path(filepath);
    if (!std::filesystem::exists(resolved)) {
        set_error("File not found: " + filepath);
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
            "ModelReader: {}", m_last_error);
        return false;
    }
    constexpr unsigned int flags = aiProcess_Triangulate
        | aiProcess_GenSmoothNormals
        | aiProcess_CalcTangentSpace
        | aiProcess_FlipUVs
        | aiProcess_JoinIdenticalVertices
        | aiProcess_SortByPType;
    m_impl->scene = m_impl->importer.ReadFile(resolved, flags);
    if (!m_impl->scene
        || (m_impl->scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE)
        || !m_impl->scene->mRootNode) {
        set_error(m_impl->importer.GetErrorString());
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
            "ModelReader: Assimp import failed — {}", m_last_error);
        m_impl->scene = nullptr;
        return false;
    }
    m_is_open = true;
    MF_INFO(Journal::Component::IO, Journal::Context::FileIO,
        "ModelReader: opened '{}' — {} meshes, {} materials",
        std::filesystem::path(resolved).filename().string(),
        m_impl->scene->mNumMeshes,
        m_impl->scene->mNumMaterials);
    return true;
}
References close(), MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, m_impl, m_is_open, m_last_error, MF_ERROR, MF_INFO, MayaFlux::IO::FileReader::resolve_path(), and set_error().
Referenced by load().