MayaFlux: MayaFlux::Kinesis::Stochastic::Stochastic::operator()
operator()()
double MayaFlux::Kinesis::Stochastic::Stochastic::operator() (double min, double max)
Generates single value in range.
Parameters
min Lower bound
max Upper bound
Returns
Generated value
For stateful algorithms, successive calls evolve internal state.
Definition at line 47 of file Stochastic.cpp.
{
    validate_range(min, max);
    switch (m_algorithm) {
    case Algorithm::UNIFORM:
    case Algorithm::NORMAL:
    case Algorithm::EXPONENTIAL:
    case Algorithm::POISSON:
        return generate_memoryless(min, max);
    case Algorithm::PERLIN:
        return generate_perlin_impl(m_state.phase, 0.0, 0.0);
    case Algorithm::GENDY:
        return generate_gendy_impl(min, max);
    case Algorithm::BROWNIAN:
        return generate_brownian_impl(min, max);
    case Algorithm::PINK:
    case Algorithm::BLUE:
        return generate_colored_noise_impl(min, max);
    default:
        return generate_memoryless(min, max);
    }
}
References MayaFlux::Kinesis::Stochastic::BLUE, MayaFlux::Kinesis::Stochastic::BROWNIAN, MayaFlux::Kinesis::Stochastic::EXPONENTIAL, MayaFlux::Kinesis::Stochastic::GENDY, generate_brownian_impl(), generate_colored_noise_impl(), generate_gendy_impl(), generate_memoryless(), generate_perlin_impl(), m_algorithm, m_state, MayaFlux::Kinesis::Stochastic::NORMAL, MayaFlux::Kinesis::Stochastic::PERLIN, MayaFlux::Kinesis::Stochastic::GeneratorState::phase, MayaFlux::Kinesis::Stochastic::PINK, MayaFlux::Kinesis::Stochastic::POISSON, MayaFlux::Kinesis::Stochastic::UNIFORM, and validate_range().