MayaFlux: MayaFlux::Buffers::MeshNetworkBuffer::MeshNetworkBuffer
MeshNetworkBuffer()
MayaFlux::Buffers::MeshNetworkBuffer::MeshNetworkBuffer (std::shared_ptr< Nodes::Network::MeshNetwork > network, float over_allocate_factor = 1.5F) explicit
Construct from an existing MeshNetwork.
Parameters
network Must be non-null and have at least one slot before setup_processors() is called.
over_allocate_factor Initial buffer size multiplier. Applied to the estimated total vertex byte count.
Definition at line 17 of file MeshNetworkBuffer.cpp.
    : VKBuffer(
          estimate_vertex_bytes(network, over_allocate_factor),
          Usage::VERTEX,
          Kakshya::DataModality::VERTEX_POSITIONS_3D)
    , m_network(std::move(network))
{
    if (!m_network) {
        error<std::invalid_argument>(
            Journal::Component::Buffers, Journal::Context::Init,
            std::source_location::current(),
            "MeshNetworkBuffer: null MeshNetwork");
    }
    RenderConfig defaults;
    defaults.topology = Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST;
    set_default_render_config(defaults);
    set_needs_depth_attachment(true);
    m_render_config = defaults;
    MF_INFO(Journal::Component::Buffers, Journal::Context::Init,
        "MeshNetworkBuffer: {} slots, {} bytes estimated",
        m_network->slot_count(), get_size_bytes());
}
References MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::get_size_bytes(), MayaFlux::Journal::Init, m_network, m_render_config, MF_INFO, MayaFlux::Buffers::VKBuffer::set_default_render_config(), MayaFlux::Buffers::VKBuffer::set_needs_depth_attachment(), MayaFlux::Portal::Graphics::RenderConfig::topology, and MayaFlux::Portal::Graphics::TRIANGLE_LIST.