MayaFlux: MayaFlux::Core::Engine::get_random_engine
get_random_engine()
Nodes::Generator::Stochastics::Random * MayaFlux::Core::Engine::get_random_engine () inline
Gets the stochastic signal generator engine.
Returns
Pointer to the Random node for random signal generation
The Random node provides various stochastic signal sources. Managed directly by Engine for optimal performance in generator nodes.
Definition at line 274 of file Engine.hpp.
{ return m_rng.get(); }
Referenced by MayaFlux::get_exponential_random(), MayaFlux::get_gaussian_random(), MayaFlux::get_poisson_random(), and MayaFlux::get_uniform_random().