MayaFlux: MayaFlux::Kinesis::Stochastic::Stochastic::generate_brownian_impl
generate_brownian_impl()
double MayaFlux::Kinesis::Stochastic::Stochastic::generate_brownian_impl (double min, double max) private
Definition at line 156 of file Stochastic.cpp.
{
    double step_size = 0.01;
    if (auto cfg = get_config("step_size"); cfg.has_value()) {
        step_size = std::any_cast<double>(*cfg);
    }
    double step = (fast_uniform() - 0.5) * 2.0 * step_size;
    m_state.current_value += step;
    m_state.current_value = std::clamp(m_state.current_value, min, max);
    m_state.step_count++;
    return m_state.current_value;
}
References MayaFlux::Kinesis::Stochastic::GeneratorState::current_value, fast_uniform(), get_config(), m_state, and MayaFlux::Kinesis::Stochastic::GeneratorState::step_count.
Referenced by operator()().