MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable
get_audio_unit_mutable()
RootAudioUnit & MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable (ProcessingToken token)
Gets an existing audio unit without creating if missing (mutable)
Parameters
token Processing domain
Returns
Reference to the audio unit
Exceptions
std::out_of_range if token not found
This is a query-only operation; will not create a unit if missing. Mutable version for operations that need to modify the unit in-place.
Definition at line 96 of file TokenUnitManager.cpp.
{
    auto it = m_audio_units.find(token);
    if (it == m_audio_units.end()) {
        throw std::out_of_range("Audio unit not found for token");
    }
    return it->second;
}
References m_audio_units.
Referenced by MayaFlux::Buffers::BufferSupplyMixing::cleanup_completed_routing(), MayaFlux::Buffers::BufferSupplyMixing::clone_audio_buffer_for_channels(), MayaFlux::Buffers::BufferSupplyMixing::fill_audio_from_interleaved(), MayaFlux::Buffers::BufferAccessControl::remove_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_channel(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_token(), MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer(), MayaFlux::Buffers::BufferSupplyMixing::route_buffer_to_channel(), MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor(), MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to(), MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers(), and MayaFlux::Buffers::BufferSupplyMixing::update_routing_states_for_cycle().