MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::get_frame_byte_size
get_frame_byte_size()
size_t MayaFlux::Kakshya::VideoStreamContainer::get_frame_byte_size () const
Get the total byte size of one frame (width * height * channels).
Definition at line 168 of file VideoStreamContainer.cpp.
{
    return static_cast<size_t>(m_width) * m_height * m_channels;
}
References m_channels, m_height, and m_width.
Referenced by MayaFlux::Kakshya::CameraContainer::CameraContainer(), MayaFlux::IO::VideoFileReader::decode_batch(), get_frame_pixels(), mutable_slot_ptr(), and setup_ring().