MayaFlux: MayaFlux::IO::FFmpegDemuxContext::get_stream
get_stream()
AVStream * MayaFlux::IO::FFmpegDemuxContext::get_stream (int index) const
Access a stream by index.
Parameters
index Stream index in format_context->streams[].
Returns
Pointer to AVStream, or nullptr if index is out of range.
Definition at line 119 of file FFmpegDemuxContext.cpp.
{
    if (!format_context || index < 0 || static_cast<unsigned>(index) >= format_context->nb_streams)
        return nullptr;
    return format_context->streams[index];
}
References format_context.
Referenced by MayaFlux::IO::AudioStreamContext::extract_cue_regions(), MayaFlux::IO::VideoStreamContext::extract_keyframe_regions(), MayaFlux::IO::AudioStreamContext::extract_stream_metadata(), MayaFlux::IO::VideoStreamContext::extract_stream_metadata(), MayaFlux::IO::AudioStreamContext::open(), MayaFlux::IO::VideoStreamContext::open(), and MayaFlux::IO::VideoStreamContext::open_device().