MayaFlux: MayaFlux::Core::VKSwapchain::recreate
recreate()
bool MayaFlux::Core::VKSwapchain::recreate (uint32_t width, uint32_t height)
Recreate swapchain (for window resize)
Parameters
width New width
height New height
Returns
True if recreation succeeded
Definition at line 138 of file VKSwapchain.cpp.
{
    if (!m_context) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot recreate swapchain: no context set");
        return false;
    }
    m_context->get_device().waitIdle();
    cleanup_swapchain();
    return create(*m_context, m_surface, *m_window_config);
}
References cleanup_swapchain(), MayaFlux::Journal::Core, create(), MayaFlux::Core::VKContext::get_device(), MayaFlux::Journal::GraphicsBackend, m_context, m_surface, m_window_config, and MF_ERROR.