MayaFlux: MayaFlux::IO::IOManager::stop_capture
stop_capture() [2/2]
void MayaFlux::IO::IOManager::stop_capture (uint32_t capture_id)
Stop a running capture and finalise the file.
Unregisters the AudioBackendService observer, calls writer->close(), and stores the encode future in m_save_tasks. Non-blocking.
Parameters
capture_id Handle returned by capture_output().
Definition at line 424 of file IOManager.cpp.
{
    AudioCaptureState state;
    {
        std::lock_guard lock(m_audio_captures_mutex);
        auto it = m_audio_captures.find(capture_id);
        if (it == m_audio_captures.end()) {
            MF_WARN(Journal::Component::IO, Journal::Context::FileIO,
                "stop_capture: unknown capture_id={}", capture_id);
            return;
        }
        state = std::move(it->second);
        m_audio_captures.erase(it);
    }
    auto* svc = Registry::BackendRegistry::instance()
                    .get_service<Registry::Service::AudioBackendService>();
    if (svc)
        svc->unregister_output_observer(state.observer_id);
    auto fut = state.writer->close();
    std::lock_guard lock(m_save_tasks_mutex);
    m_save_tasks.push_back(std::move(fut));
    std::erase_if(m_save_tasks, [](std::future<bool>& f) {
        return f.wait_for(std::chrono::seconds(0)) == std::future_status::ready;
    });
}
References MayaFlux::Journal::FileIO, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), MayaFlux::Journal::IO, m_audio_captures, m_audio_captures_mutex, m_save_tasks, m_save_tasks_mutex, MF_WARN, MayaFlux::IO::IOManager::AudioCaptureState::observer_id, MayaFlux::Registry::Service::AudioBackendService::unregister_output_observer, and MayaFlux::IO::IOManager::AudioCaptureState::writer.
Referenced by stop_capture(), and ~IOManager().