MayaFlux: MayaFlux::Portal::Forma::Plot::BarsBuilder::done
done()
SeriesSpec MayaFlux::Portal::Forma::Plot::BarsBuilder::done () const
Definition at line 371 of file SeriesBuilder.cpp.
{
    auto x_mappings = m_state.x_mappings();
    auto y_mappings = m_state.y_mappings();
    const auto global_palette = m_state.palette();
    return {
        .fn = [x_mappings, y_mappings, global_palette](
                  const std::shared_ptr<Kakshya::PlotContainer>& container,
                  std::vector<uint8_t>& out,
                  Element&) mutable {
            if (!container)
                return;
            container->process_default();
            AxisRange x_range = x_mappings.empty() ? AxisRange {} : merge_axis(x_mappings);
            out.clear();
            for (auto& y_mapping : y_mappings) {
                auto y_series = series_for_mapping(*container, y_mapping);
                if (y_series.empty())
                    continue;
                auto y_range = y_mapping.range;
                apply_auto_scale(y_range, y_series);
                for (size_t si = 0; si < y_series.size(); ++si) {
                    const auto& series = y_series[si];
                    const size_t n = series.size();
                    if (n == 0)
                        continue;
                    const glm::vec3 color = resolve_color(y_mapping, global_palette, si);
                    const float bar_w = (x_range.max - x_range.min) / static_cast<float>(n);
                    const float y_base = y_range.to_ndc(0.F);
                    for (size_t i = 0; i < n; ++i) {
                        const float x_left = x_range.to_ndc(x_range.min + static_cast<float>(i) * bar_w);
                        const float x_right = x_range.to_ndc(x_range.min + static_cast<float>(i + 1) * bar_w);
                        const float y_top = y_range.to_ndc(static_cast<float>(series[i]));
                        write_vertex(out, { x_left, y_base, 0.F }, color, 0.F);
                        write_vertex(out, { x_right, y_base, 0.F }, color, 0.F);
                        write_vertex(out, { x_left, y_top, 0.F }, color, 0.F);
                        write_vertex(out, { x_right, y_base, 0.F }, color, 0.F);
                        write_vertex(out, { x_right, y_top, 0.F }, color, 0.F);
                        write_vertex(out, { x_left, y_top, 0.F }, color, 0.F);
                    }
                }
            } },
        .topology = Graphics::PrimitiveTopology::TRIANGLE_LIST,
        .capacity_for = [](uint64_t n) { return n * 6 * k_stride; },
        .background_fn = m_state.has_background()
            ? std::optional<GeometryFn<float>> { background(m_state.background_bounds(), m_state.background_color()) }
            : std::nullopt,
        .plot_bounds = m_state.plot_bounds(),
        .labels = m_state.labels(),
        .tick_labels = m_state.resolved_tick_labels(),
        .legend = m_state.legend_spec(),
    };
}
References MayaFlux::Portal::Forma::Plot::apply_auto_scale(), MayaFlux::Portal::Forma::Plot::background(), MayaFlux::Portal::Forma::Plot::Series::background_bounds(), MayaFlux::Portal::Forma::Plot::Series::background_color(), MayaFlux::Portal::Forma::Plot::Series::has_background(), MayaFlux::Portal::Forma::Plot::Series::labels(), MayaFlux::Portal::Forma::Plot::Series::legend_spec(), m_state, MayaFlux::Portal::Forma::Plot::AxisRange::max, MayaFlux::Portal::Forma::Plot::AxisRange::min, MayaFlux::Portal::Forma::Plot::Series::palette(), MayaFlux::Portal::Forma::Plot::Series::plot_bounds(), MayaFlux::Portal::Forma::Plot::Series::resolved_tick_labels(), MayaFlux::Portal::Forma::Plot::series(), MayaFlux::Portal::Forma::Plot::AxisRange::to_ndc(), MayaFlux::Portal::Graphics::TRIANGLE_LIST, MayaFlux::Portal::Forma::Plot::Series::x_mappings(), and MayaFlux::Portal::Forma::Plot::Series::y_mappings().