MayaFlux: MayaFlux::Yantra::Granular::AttributeOp::analyze_implementation
analyze_implementation()
Datum< Kakshya::RegionGroup > MayaFlux::Yantra::Granular::AttributeOp::analyze_implementation (const Datum< Kakshya::RegionGroup > & input) override protected
Definition at line 571 of file GranularWorkflow.cpp.
{
    if (input.data.regions.empty())
        return input;
    std::shared_ptr<Kakshya::SignalSourceContainer> container;
    if (input.container && *input.container) {
        container = *input.container;
    } else {
        auto param = this->get_parameter("container");
        if (param.has_value()) {
            container = safe_any_cast_or_default<std::shared_ptr<Kakshya::SignalSourceContainer>>(
                param, nullptr);
        }
    }
    if (!container) {
        error<std::runtime_error>(
            Journal::Component::Yantra, Journal::Context::ComputeMatrix,
            std::source_location::current(),
            "AttributeOp: no container available via Datum or parameters");
    }
    const auto channel = this->template get_parameter_or_default<uint32_t>("channel", 0U);
    const auto feature_key = this->template get_parameter_or_default<std::string>("feature_key", std::string("feature"));
    ExecutionContext ctx;
    for (const auto& [k, v] : this->get_all_analysis_parameters())
        ctx.execution_metadata[k] = v;
    Datum<Kakshya::RegionGroup> out { input.data, container };
    for (auto& grain : out.data.regions) {
        const double value = compute_grain_attribute(grain, container, channel, ctx);
        grain.set_attribute(feature_key, value);
    }
    return out;
}
References channel, compute_grain_attribute(), MayaFlux::Journal::ComputeMatrix, MayaFlux::Yantra::Datum< T >::container, MayaFlux::Yantra::Datum< T >::data, MayaFlux::Yantra::ExecutionContext::execution_metadata, MayaFlux::Yantra::UniversalAnalyzer< InputType, OutputType >::get_all_analysis_parameters(), MayaFlux::Yantra::UniversalAnalyzer< InputType, OutputType >::get_parameter(), and MayaFlux::Journal::Yantra.