MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::mutable_slot_ptr
mutable_slot_ptr()
uint8_t * MayaFlux::Kakshya::VideoStreamContainer::mutable_slot_ptr (uint64_t frame_index)
Mutable pointer into m_data[0] for the decode thread to write into.
Parameters
frame_index Absolute frame index; mapped to slot via modulo.
Returns
Pointer into the pixel vector, or nullptr if not in ring mode.
Definition at line 124 of file VideoStreamContainer.cpp.
{
    if (m_ring_capacity == 0 || frame_index >= m_total_source_frames)
        return nullptr;
    auto* pixels = std::get_if<std::vector<uint8_t>>(&m_data[0]);
    if (!pixels)
        return nullptr;
    return pixels->data() + slot_for(frame_index) * get_frame_byte_size();
}
References get_frame_byte_size(), m_data, m_ring_capacity, m_total_source_frames, pixels, and slot_for().
Referenced by MayaFlux::IO::VideoFileReader::decode_batch().