MayaFlux: MayaFlux::Core::RtAudioStream::stop
stop()
void MayaFlux::Core::RtAudioStream::stop () override virtual
Deactivates the audio stream and halts data transfer.
Stops the RtAudio stream, suspending the real-time processing while maintaining the stream's configuration.
Implements MayaFlux::Core::AudioStream.
Definition at line 312 of file RtAudioBackend.cpp.
{
    if (!is_running()) {
        return;
    }
    try {
        m_context->stopStream();
        m_isRunning = false;
    } catch (const RtAudioErrorType& e) {
        error_rethrow(
            Journal::Component::Core,
            Journal::Context::AudioBackend,
            std::source_location::current(),
            "Failed to stop RtAudio stream: {}",
            m_context->getErrorText());
    }
}
References MayaFlux::Journal::AudioBackend, MayaFlux::Journal::Core, is_running(), m_context, and m_isRunning.
Referenced by close(), and ~RtAudioStream().