MayaFlux: MayaFlux::Vruta::TaskScheduler::seconds_to_samples
seconds_to_samples()
uint64_t MayaFlux::Vruta::TaskScheduler::seconds_to_samples (double seconds) const
Converts a time in seconds to a number of samples.
Parameters
seconds Time duration in seconds
Returns
Equivalent number of samples at the current sample rate
Convenience method that uses the audio domain's sample rate for conversion. For domain-specific conversions, use seconds_to_units() with the appropriate token.
Definition at line 156 of file Scheduler.cpp.
{
    return Utils::seconds_to_samples(seconds, get_rate(ProcessingToken::SAMPLE_ACCURATE));
}
References get_rate(), MayaFlux::Vruta::SAMPLE_ACCURATE, and MayaFlux::Utils::seconds_to_samples().
Referenced by MayaFlux::Kriya::BufferPipeline::execute_scheduled_at_rate(), MayaFlux::Kriya::metro(), MayaFlux::Kriya::pattern(), MayaFlux::Kriya::Timer::schedule(), MayaFlux::Kriya::sequence(), MayaFlux::Kriya::EventChain::start(), and MayaFlux::Kriya::CycleCoordinator::sync_pipelines_at_rate().