MayaFlux: MayaFlux::Nodes::Network::MeshNetwork::process_batch
process_batch()
void MayaFlux::Nodes::Network::MeshNetwork::process_batch (unsigned int num_samples) override virtual
Process the network for the given number of samples.
Parameters
num_samples Number of samples/frames to process
Subclasses implement their specific processing logic:
Update internal state (physics, relationships, etc.)
Process individual nodes
Apply inter-node interactions
Aggregate outputs if needed
Called by NodeGraphManager during token processing.
Implements MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 104 of file MeshNetwork.cpp.
{
    if (!is_enabled() || m_slots.empty())
        return;
    if (m_sort_dirty)
        rebuild_sort();
    for (unsigned int frame = 0; frame < num_samples; ++frame) {
        if (m_operator) {
            if (auto* mesh_op = dynamic_cast<MeshOperator*>(m_operator.get()))
                mesh_op->set_slots(m_slots, m_sorted_indices);
            m_operator->process(static_cast<float>(frame));
        } else {
            propagate_world_transforms();
        }
        if (m_operator_chain) {
            for (const auto& op : m_operator_chain->operators()) {
                if (auto* mesh_op = dynamic_cast<MeshOperator*>(op.get()))
                    mesh_op->set_slots(m_slots, m_sorted_indices);
                op->process(static_cast<float>(frame));
            }
        }
    }
    for (const auto& slot : m_slots) {
        if (slot.node)
            slot.node->compute_frame();
    }
}
References MayaFlux::Nodes::Network::NodeNetwork::is_enabled(), m_operator, MayaFlux::Nodes::Network::NodeNetwork::m_operator_chain, m_slots, m_sort_dirty, m_sorted_indices, propagate_world_transforms(), and rebuild_sort().