MayaFlux: MayaFlux::Registry::BackendRegistry::unregister_service
unregister_service()
template<typename Interface > void MayaFlux::Registry::BackendRegistry::unregister_service () inline
Unregister a service.
Template Parameters
Interface The service interface type to unregister
Thread-safe. Typically called during backend shutdown. Safe to call even if service not registered (no-op). After unregistration, get_service() will return nullptr.
Example: registry.unregister_service<IBufferService>();
Definition at line 158 of file BackendRegistry.hpp.
    {
        std::unique_lock lock(m_mutex);
        m_services.erase(typeid(Interface));
    }
Referenced by MayaFlux::IO::VideoFileReader::close(), MayaFlux::Core::NetworkSubsystem::shutdown(), MayaFlux::IO::CameraReader::~CameraReader(), and MayaFlux::IO::IOManager::~IOManager().