MayaFlux: MayaFlux::Platform::SystemConfig::find_dep_library
find_dep_library()
const std::string & MayaFlux::Platform::SystemConfig::find_dep_library (const std::string & library_name, const std::string & prefix = "") static
Definition at line 112 of file HostEnvironment.cpp.
{
    static std::unordered_map<std::string, std::string> cache;
    auto it = cache.find(library_name);
    if (it != cache.end()) {
        return it->second;
    }
    std::string& result = cache[library_name];
    std::string search_name = format_library_name(library_name, LibraryType::Shared);
    const fs::path resolved_prefix(prefix);
    for (const auto& subdir : { "lib", "lib64", "bin" }) {
        fs::path candidate = resolved_prefix / subdir / search_name;
        if (fs::exists(candidate)) {
            result = candidate.string();
            return result;
        }
    }
    for (const auto& lib_path : get_system_libraries()) {
        fs::path candidate = fs::path(lib_path) / search_name;
        if (fs::exists(candidate)) {
            result = candidate.string();
            return result;
        }
    }
    return result;
}
References format_library_name(), get_system_libraries(), and Shared.
Referenced by Lila::ClangInterpreter::initialize().