MayaFlux: MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer
get_root_audio_buffer() [1/2]
std::shared_ptr< RootAudioBuffer > MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer (ProcessingToken token, uint32_t channel)
Gets the root audio buffer for a specific token and channel.
Parameters
token Processing domain
channel Channel index
Returns
Shared pointer to the root audio buffer
Definition at line 64 of file BufferAccessControl.cpp.
{
    if (token != ProcessingToken::AUDIO_BACKEND && token != ProcessingToken::AUDIO_PARALLEL) {
        error<std::invalid_argument>(Journal::Component::Core, Journal::Context::BufferManagement,
            std::source_location::current(),
            "Invalid token for audio buffer access: {}", static_cast<int>(token));
    }
    auto& unit = m_unit_manager.get_or_create_audio_unit(token);
    return unit.get_buffer(channel);
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::AUDIO_PARALLEL, MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::get_or_create_audio_unit(), and m_unit_manager.
Referenced by MayaFlux::Buffers::BufferProcessingControl::add_audio_processor_to_channel(), get_audio_buffer_data(), and get_audio_buffer_data().