MayaFlux: MayaFlux::Core::VKContext::get_physical_device
get_physical_device()
vk::PhysicalDevice MayaFlux::Core::VKContext::get_physical_device () const inline
Get physical device.
Definition at line 44 of file VKContext.hpp.
{ return m_device.get_physical_device(); }
References MayaFlux::Core::VKDevice::get_physical_device(), and m_device.
Referenced by MayaFlux::Core::VKSwapchain::create(), and MayaFlux::Core::BackendResourceManager::find_memory_type().