MayaFlux: MayaFlux::Portal::Graphics::RenderFlow::instance
instance()
static RenderFlow & MayaFlux::Portal::Graphics::RenderFlow::instance () inline static
Definition at line 72 of file RenderFlow.hpp.
    {
        static RenderFlow flow;
        return flow;
    }
Referenced by MayaFlux::Portal::Graphics::get_render_flow(), MayaFlux::Portal::Graphics::initialize(), MayaFlux::Portal::Graphics::shutdown(), and MayaFlux::Portal::Graphics::stop().