MayaFlux: MayaFlux::IO::CameraReader::~CameraReader
~CameraReader()
MayaFlux::IO::CameraReader::~CameraReader ()
Definition at line 51 of file CameraReader.cpp.
{
    close();
    if (m_owns_service) {
        Registry::BackendRegistry::instance()
            .unregister_service<Registry::Service::IOService>();
    }
}
References close(), MayaFlux::Registry::BackendRegistry::instance(), m_owns_service, and MayaFlux::Registry::BackendRegistry::unregister_service().