MayaFlux: MayaFlux::Memory::HistoryBuffer::push
push()
template<typename T > void MayaFlux::Memory::HistoryBuffer< T >::push (const T & value) inline
Push new value to front of history.
Parameters
value New sample value
Inserts value at index 0, shifting all previous values back. Oldest value (at index capacity-1) is discarded.
Definition at line 373 of file RingBuffer.hpp.
    {
        if (m_capacity == 0)
            return;
        m_head = (m_head == 0) ? m_capacity - 1 : m_head - 1;
        m_data[m_head] = value;
        if (m_count < m_capacity) {
            ++m_count;
        }
    }
References MayaFlux::Memory::HistoryBuffer< T >::m_capacity, MayaFlux::Memory::HistoryBuffer< T >::m_count, MayaFlux::Memory::HistoryBuffer< T >::m_data, and MayaFlux::Memory::HistoryBuffer< T >::m_head.
Referenced by MayaFlux::Nodes::Network::WaveguideNetwork::process_bidirectional(), MayaFlux::Nodes::Generator::Polynomial::process_sample(), MayaFlux::Nodes::Network::WaveguideNetwork::process_unidirectional(), and MayaFlux::Buffers::FeedbackProcessor::processing_function().