MayaFlux: MayaFlux::Buffers::ShaderProcessor::processing_function
processing_function()
void MayaFlux::Buffers::ShaderProcessor::processing_function (const std::shared_ptr< Buffer > & buffer) override virtual
The core processing function that must be implemented by derived classes.
Parameters
buffer Buffer to process
This method is where the actual transformation logic is implemented. It should contain the algorithmic details of how the buffer's data is transformed, analyzed, or processed. The implementation can utilize any backend capabilities available to the processor, including:
Parallel Processing: Using multi-threading or GPU compute for large datasets
Data Transformations: Applying mathematical operations, filters, or effects
Feature Extraction: Analyzing data characteristics for further processing
Derived classes must override this method to provide specific processing behavior.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 36 of file ShaderProcessor.cpp.
{
    auto vk_buffer = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk_buffer) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "ShaderProcessor can only process VKBuffers");
        return;
    }
    if (!on_before_execute(m_last_command_buffer, vk_buffer)) {
        MF_RT_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "on_before_execute() reported failure, skipping shader execution");
        return;
    }
    if (!m_initialized) {
        initialize_shader();
        initialize_pipeline(vk_buffer);
        m_initialized = true;
    }
    if (m_needs_pipeline_rebuild) {
        initialize_pipeline(vk_buffer);
        m_needs_pipeline_rebuild = false;
        m_needs_descriptor_rebuild = true;
    }
    if (m_needs_descriptor_rebuild) {
        initialize_descriptors(vk_buffer);
        m_needs_descriptor_rebuild = false;
    } else {
        update_descriptors(vk_buffer);
    }
    execute_shader(vk_buffer);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, execute_shader(), initialize_descriptors(), initialize_pipeline(), initialize_shader(), m_initialized, m_last_command_buffer, m_needs_descriptor_rebuild, m_needs_pipeline_rebuild, MF_ERROR, MF_RT_DEBUG, on_before_execute(), and update_descriptors().