MayaFlux: MayaFlux::CreationHandle::apply_if_ready
apply_if_ready()
template<typename T > void MayaFlux::CreationHandle< T >::apply_if_ready () inline private
Definition at line 104 of file Creator.hpp.
    {
        if constexpr (std::is_base_of_v<Kakshya::SignalSourceContainer, T>) {
            if (m_ctx.domain) {
                apply_container_context();
                m_ctx = CreationContext {};
            }
        } else if (m_ctx.domain && (m_ctx.channel || m_ctx.channels)) {
            if constexpr (std::is_base_of_v<Nodes::Node, T>) {
                if (m_ctx.domain) {
                    apply_node_context();
                }
            } else if constexpr (std::is_base_of_v<Buffers::Buffer, T>) {
                if (m_ctx.domain) {
                    apply_buffer_context();
                }
            } else if constexpr (std::is_base_of_v<Nodes::Network::NodeNetwork, T>) {
                if (m_ctx.domain) {
                    apply_network_context();
                }
            }
            m_ctx = CreationContext {};
        } else if (m_ctx.domain) {
            if constexpr (std::is_base_of_v<Buffers::VKBuffer, T>) {
                apply_buffer_context();
            }
            if (m_ctx.domain == Domain::GRAPHICS) {
                if constexpr (std::is_base_of_v<Nodes::Node, T>) {
                    apply_node_context();
                }
                if constexpr (std::is_base_of_v<Nodes::Network::NodeNetwork, T>) {
                    apply_network_context();
                }
            }
            m_ctx = CreationContext {};
        }
    }
References MayaFlux::CreationHandle< T >::apply_buffer_context(), MayaFlux::CreationHandle< T >::apply_container_context(), MayaFlux::CreationHandle< T >::apply_network_context(), MayaFlux::CreationHandle< T >::apply_node_context(), MayaFlux::CreationContext::channel, MayaFlux::CreationContext::channels, MayaFlux::CreationContext::domain, MayaFlux::GRAPHICS, and MayaFlux::CreationHandle< T >::m_ctx.
Referenced by MayaFlux::CreationHandle< T >::channel(), MayaFlux::CreationHandle< T >::channels(), MayaFlux::CreationHandle< T >::channels(), MayaFlux::CreationHandle< T >::domain(), and MayaFlux::CreationHandle< T >::operator[]().