MayaFlux: MayaFlux::Core::InputSubsystem::register_backend_service
register_backend_service()
void MayaFlux::Core::InputSubsystem::register_backend_service () private
Definition at line 62 of file InputSubsystem.cpp.
{
    auto& registry = Registry::BackendRegistry::instance();
    auto input_service = std::make_shared<Registry::Service::InputService>();
    input_service->get_all_devices = [this]() {
        return get_all_devices();
    };
    input_service->open_device = [this](InputType type, uint32_t id) {
        return open_device(type, id);
    };
    input_service->close_device = [this](InputType type, uint32_t id) {
        close_device(type, id);
    };
    m_input_service = input_service;
    registry.register_service<Registry::Service::InputService>(
        [input_service]() -> void* {
            return input_service.get();
        });
}
References close_device(), get_all_devices(), MayaFlux::Registry::BackendRegistry::instance(), m_input_service, and open_device().
Referenced by initialize().