MayaFlux: MayaFlux::Buffers::MeshNetworkProcessor::on_attach
on_attach()
void MayaFlux::Buffers::MeshNetworkProcessor::on_attach (const std::shared_ptr< Buffer > &) override protected virtual
Called when this processor is attached to a buffer.
Parameters
buffer Buffer this processor is being attached to
Provides an opportunity for the processor to initialize buffer-specific state, allocate resources, or perform validation. With expanded processor capabilities, this method can also:
Analyze Buffer Characteristics: Examine data type, size, and format requirements
Select Optimal Backend: Choose the most appropriate processing backend for the buffer
Initialize Hardware Resources: Set up GPU contexts, CUDA streams, or other acceleration
Configure Processing Parameters: Adapt algorithm parameters to buffer characteristics
Establish Processing Strategy: Determine whether to use sequential or parallel execution
Validate Compatibility: Ensure the processor can handle the buffer's data type and format
Default implementation does nothing, but derived classes should override this method to leverage the full capabilities of the expanded processor architecture.
Reimplemented from MayaFlux::Buffers::BufferProcessor.
Definition at line 24 of file MeshNetworkProcessor.cpp.
{
    if (!m_network || m_network->slot_count() == 0) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "MeshNetworkProcessor attached to empty network");
        return;
    }
    auto vk_buf = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk_buf) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "MeshNetworkProcessor: attached buffer is not a VKBuffer");
        return;
    }
    m_network->ensure_sorted();
    ensure_initialized(vk_buf);
    allocate_gpu_buffers(vk_buf);
    upload_combined(vk_buf);
    link_index_resources(vk_buf);
    clear_slot_dirty_flags();
    MF_INFO(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "MeshNetworkProcessor: initialised — {} slots, {} bytes vertex, {} indices",
        m_network->slot_count(),
        m_vertex_aggregate.size(),
        m_index_aggregate.size());
}
References allocate_gpu_buffers(), MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, clear_slot_dirty_flags(), MayaFlux::Buffers::VKBufferProcessor::ensure_initialized(), link_index_resources(), m_index_aggregate, m_network, m_vertex_aggregate, MF_ERROR, MF_INFO, MF_WARN, and upload_combined().