MayaFlux: MayaFlux::Yantra::GpuResourceManager::initialise
initialise()
bool MayaFlux::Yantra::GpuResourceManager::initialise (const GpuShaderConfig & config, const std::vector< GpuBufferBinding > & bindings)
Definition at line 120 of file GpuResourceManager.cpp.
{
    if (m_ready)
        return true;
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& compute_press = Portal::Graphics::get_compute_press();
    if (config.shader_id != Portal::Graphics::INVALID_SHADER) {
        m_shader_id = config.shader_id;
    } else {
        m_shader_id = foundry.load_shader(config.shader_path);
    }
    if (m_shader_id == Portal::Graphics::INVALID_SHADER) {
        MF_ERROR(Journal::Component::Yantra, Journal::Context::BufferProcessing,
            "GpuResourceManager: failed to load shader '{}'",
            config.shader_path.empty() ? "<generated>" : config.shader_path);
        return false;
    }
    std::map<uint32_t, std::vector<Portal::Graphics::DescriptorBindingInfo>> by_set;
    for (const auto& b : bindings) {
        const auto et = b.element_type;
        const bool is_image = et == GpuBufferBinding::ElementType::IMAGE_STORAGE
            || et == GpuBufferBinding::ElementType::IMAGE_SAMPLED;
        if (is_image) {
            by_set[b.set].push_back({
                .set = b.set,
                .binding = b.binding,
                .type = element_type_to_vk(et),
            });
        }
    }
    for (const auto& b : bindings) {
        const auto et = b.element_type;
        const bool is_image = et == GpuBufferBinding::ElementType::IMAGE_STORAGE
            || et == GpuBufferBinding::ElementType::IMAGE_SAMPLED;
        if (!is_image) {
            by_set[b.set].push_back({
                .set = b.set,
                .binding = b.binding,
                .type = vk::DescriptorType::eStorageBuffer,
            });
        }
    }
    std::vector<std::vector<Portal::Graphics::DescriptorBindingInfo>> descriptor_sets;
    descriptor_sets.reserve(by_set.size());
    for (auto& [set_idx, set_bindings] : by_set)
        descriptor_sets.push_back(std::move(set_bindings));
    m_pipeline_id = compute_press.create_pipeline(
        m_shader_id, descriptor_sets, config.push_constant_size);
    if (m_pipeline_id == Portal::Graphics::INVALID_COMPUTE_PIPELINE) {
        MF_ERROR(Journal::Component::Yantra, Journal::Context::BufferProcessing,
            "GpuResourceManager: failed to create pipeline for '{}'",
            config.shader_path);
        foundry.destroy_shader(m_shader_id);
        m_shader_id = Portal::Graphics::INVALID_SHADER;
        return false;
    }
    m_descriptor_set_ids = compute_press.allocate_pipeline_descriptors(m_pipeline_id);
    if (m_descriptor_set_ids.empty()) {
        MF_ERROR(Journal::Component::Yantra, Journal::Context::BufferProcessing,
            "GpuResourceManager: failed to allocate descriptor sets");
        compute_press.destroy_pipeline(m_pipeline_id);
        m_pipeline_id = Portal::Graphics::INVALID_COMPUTE_PIPELINE;
        foundry.destroy_shader(m_shader_id);
        m_shader_id = Portal::Graphics::INVALID_SHADER;
        return false;
    }
    m_impl = std::make_unique<GpuResourceManagerImpl>();
    m_impl->buffers.resize(bindings.size());
    m_buffer_slots.resize(bindings.size());
    m_image_slots.resize(bindings.size());
    m_ready = true;
    return true;
}
References b, MayaFlux::Journal::BufferProcessing, MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, MayaFlux::Portal::Graphics::INVALID_SHADER, MayaFlux::is_image(), m_buffer_slots, m_descriptor_set_ids, m_image_slots, m_impl, m_pipeline_id, m_ready, m_shader_id, MF_ERROR, MayaFlux::Yantra::GpuShaderConfig::push_constant_size, MayaFlux::Yantra::GpuShaderConfig::shader_id, MayaFlux::Yantra::GpuShaderConfig::shader_path, and MayaFlux::Journal::Yantra.
Referenced by MayaFlux::Yantra::GpuDispatchCore::ensure_gpu_ready().