MayaFlux: MayaFlux::Kakshya::VideoFileContainer::get_duration_seconds
get_duration_seconds()
double MayaFlux::Kakshya::VideoFileContainer::get_duration_seconds () const
Total duration in seconds.
Definition at line 18 of file VideoFileContainer.cpp.
{
    return position_to_time(
        is_ring_mode() ? get_total_source_frames() : get_num_frames());
}
References MayaFlux::Kakshya::VideoStreamContainer::get_num_frames(), MayaFlux::Kakshya::VideoStreamContainer::get_total_source_frames(), MayaFlux::Kakshya::VideoStreamContainer::is_ring_mode(), and MayaFlux::Kakshya::VideoStreamContainer::position_to_time().