MayaFlux: MayaFlux::Yantra::OperationHelper::extract_numeric_data
extract_numeric_data() [1/3]
template<typename T > requires SingleVariant<T> static std::span< double > MayaFlux::Yantra::OperationHelper::extract_numeric_data (const T & compute_data) inline static
extract numeric data from single-variant types
Template Parameters
T ComputeData type
Parameters
compute_data Input data
Returns
Span of double data
Definition at line 73 of file OperationHelper.hpp.
    {
        if constexpr (std::is_same_v<T, Kakshya::DataVariant>) {
            auto const_span = Kakshya::convert_variant<double>(compute_data);
            return std::span<double>(const_cast<double*>(const_span.data()), const_span.size());
        }
        if constexpr (std::is_base_of_v<Eigen::MatrixBase<T>, T>) {
            Kakshya::DataVariant variant = create_data_variant_from_eigen(compute_data);
            return Kakshya::convert_variant<double>(variant, s_complex_strategy);
        }
        Kakshya::DataVariant variant { compute_data };
        return Kakshya::convert_variant_to_double(variant, s_complex_strategy);
    }
References MayaFlux::Kakshya::convert_variant_to_double(), create_data_variant_from_eigen(), and s_complex_strategy.
Referenced by MayaFlux::dynamic_range_global(), extract_structured_double(), MayaFlux::Yantra::generate_compute_data_indices(), MayaFlux::mean_combined(), MayaFlux::mix(), MayaFlux::mix_with_gains(), MayaFlux::rms_combined(), MayaFlux::Yantra::sort_compute_data_inplace(), MayaFlux::std_dev_combined(), MayaFlux::to_double_vector(), MayaFlux::to_double_vectors(), MayaFlux::Yantra::transform_regions(), and MayaFlux::Yantra::transform_regions().