MayaFlux: MayaFlux::Nodes::Network::FieldOperator::get_vertex_layout
get_vertex_layout()
Kakshya::VertexLayout MayaFlux::Nodes::Network::FieldOperator::get_vertex_layout () const override virtual
Get vertex layout describing vertex structure.
Implements MayaFlux::Nodes::Network::GraphicsOperator.
Definition at line 256 of file FieldOperator.cpp.
{
    Kakshya::VertexLayout layout;
    switch (m_vertex_type) {
    case VertexType::POINT:
        layout = Kakshya::VertexLayout::for_points(k_stride);
        break;
    case VertexType::LINE:
        layout = Kakshya::VertexLayout::for_lines(k_stride);
        break;
    case VertexType::MESH:
        layout = Kakshya::VertexLayout::for_meshes(k_stride);
        break;
    default:
        return {};
    }
    layout.vertex_count = static_cast<uint32_t>(m_count);
    return layout;
}
References MayaFlux::Kakshya::VertexLayout::for_lines(), MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Kakshya::VertexLayout::for_points(), k_stride, LINE, m_count, m_vertex_type, MESH, POINT, and MayaFlux::Kakshya::VertexLayout::vertex_count.