MayaFlux: MayaFlux::Kriya::Timer::schedule
schedule()
void MayaFlux::Kriya::Timer::schedule (double delay_seconds, std::function< void()> callback)
Schedules a callback to execute after a delay.
Parameters
delay_seconds Time to wait before executing the callback (in seconds)
callback Function to execute after the delay
This method schedules the provided callback to execute after exactly the specified delay. If a callback is already scheduled, it is cancelled and replaced with the new one.
The timing is sample-accurate, ensuring that the callback executes at precisely the right moment in the processing timeline.
Definition at line 18 of file Timers.cpp.
{
    cancel();
    m_callback = std::move(callback);
    m_active = true;
    auto routine_func = [](Vruta::TaskScheduler& scheduler, uint64_t delay_samples, Timer* timer_ptr) -> Vruta::SoundRoutine {
        auto& promise = co_await Kriya::GetAudioPromise {};
        co_await SampleDelay { delay_samples };
        if (timer_ptr && timer_ptr->is_active()) {
            timer_ptr->m_callback();
            timer_ptr->m_active = false;
        }
    };
    m_routine = std::make_shared<Vruta::SoundRoutine>(
        routine_func(m_Scheduler, m_Scheduler.seconds_to_samples(delay_seconds), this));
    Vruta::ProcessingToken token = m_routine->get_processing_token();
    uint64_t current_time = m_Scheduler.current_units(token);
    m_Scheduler.add_task(m_routine, "", false);
    m_routine->initialize_state(current_time);
}
References MayaFlux::Vruta::TaskScheduler::add_task(), cancel(), MayaFlux::Vruta::TaskScheduler::current_units(), delay_seconds, m_active, m_callback, m_routine, m_Scheduler, and MayaFlux::Vruta::TaskScheduler::seconds_to_samples().
Referenced by MayaFlux::Kriya::TemporalActivation::activate_buffer(), MayaFlux::Kriya::TemporalActivation::activate_network(), MayaFlux::Kriya::TemporalActivation::activate_node(), and MayaFlux::Kriya::TimedAction::execute().