MayaFlux: MayaFlux::Core::GlfwWindow::setup_callbacks
setup_callbacks()
void MayaFlux::Core::GlfwWindow::setup_callbacks () private
Definition at line 150 of file GlfwWindow.cpp.
{
    glfwSetWindowSizeCallback(m_window, glfw_window_size_callback);
    glfwSetWindowCloseCallback(m_window, glfw_window_close_callback);
    glfwSetWindowFocusCallback(m_window, glfw_window_focus_callback);
    glfwSetFramebufferSizeCallback(m_window, glfw_framebuffer_size_callback);
    glfwSetKeyCallback(m_window, glfw_key_callback);
    glfwSetCursorPosCallback(m_window, glfw_cursor_pos_callback);
    glfwSetMouseButtonCallback(m_window, glfw_mouse_button_callback);
    glfwSetScrollCallback(m_window, glfw_scroll_callback);
}
References glfw_cursor_pos_callback(), glfw_framebuffer_size_callback(), glfw_key_callback(), glfw_mouse_button_callback(), glfw_scroll_callback(), glfw_window_close_callback(), glfw_window_focus_callback(), glfw_window_size_callback(), and m_window.
Referenced by GlfwWindow().