MayaFlux: MayaFlux::Core::GraphicsSubsystem::stop
stop()
void MayaFlux::Core::GraphicsSubsystem::stop () override virtual
Stop the subsystem's processing/event loops.
Implements MayaFlux::Core::ISubsystem.
Definition at line 202 of file GraphicsSubsystem.cpp.
{
    if (!m_running.load(std::memory_order_acquire)) {
        return;
    }
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsSubsystem,
        "Stopping Graphics Subsystem...");
    m_running.store(false, std::memory_order_release);
    if (m_graphics_thread.joinable()) {
        m_graphics_thread.join();
    }
    m_backend->wait_idle();
    if (Portal::Graphics::is_initialized()) {
        Portal::Graphics::stop();
    }
    for (auto& window : m_registered_windows) {
        window->set_graphics_registered(false);
    }
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsSubsystem,
        "Graphics Subsystem stopped.");
}
References MayaFlux::Journal::Core, MayaFlux::Journal::GraphicsSubsystem, MayaFlux::Portal::Graphics::is_initialized(), m_backend, m_graphics_thread, m_registered_windows, m_running, MF_INFO, and MayaFlux::Portal::Graphics::stop().
Referenced by shutdown(), and ~GraphicsSubsystem().