MayaFlux: MayaFlux::Portal::Graphics::ComputePress::bind_all
bind_all()
void MayaFlux::Portal::Graphics::ComputePress::bind_all (CommandBufferID cmd_id, ComputePipelineID pipeline_id, const std::vector< DescriptorSetID > & descriptor_set_ids, const void * push_constants_data = nullptr, size_t push_constant_size = 0)
All-in-one: bind pipeline + descriptors + push constants.
Definition at line 380 of file ComputePress.cpp.
{
    bind_pipeline(cmd_id, pipeline_id);
    bind_descriptor_sets(cmd_id, pipeline_id, descriptor_set_ids);
    if (push_constants_data && push_constant_size > 0) {
        this->push_constants(cmd_id, pipeline_id, push_constants_data, push_constant_size);
    }
}
References bind_descriptor_sets(), bind_pipeline(), and push_constants().