MayaFlux: MayaFlux::Journal::Archivist::Impl::drain_ring_buffer
drain_ring_buffer()
void MayaFlux::Journal::Archivist::Impl::drain_ring_buffer () inline private
Definition at line 319 of file Archivist.cpp.
    {
        while (auto entry = m_ring_buffer.pop()) {
            std::lock_guard lock(m_mutex);
            if (m_sinks.empty()) {
                write_to_console(*entry);
            } else {
                write_to_sinks(*entry);
            }
        }
        auto dropped = m_dropped_messages.exchange(0, std::memory_order_acquire);
        if (dropped > 0) {
            std::lock_guard lock(m_mutex);
            std::cout << "[MayaFlux::Journal] WARNING: Dropped " << dropped
                      << " realtime log messages (buffer full)\n";
        }
    }
References m_dropped_messages, m_mutex, m_ring_buffer, m_sinks, write_to_console(), and write_to_sinks().
Referenced by shutdown(), stop_worker(), and worker_loop().