MayaFlux: MayaFlux::IO::VideoFileReader::open
open()
bool MayaFlux::IO::VideoFileReader::open (const std::string & filepath, FileReadOptions options = FileReadOptions::ALL) override virtual
Open a file for reading.
Parameters
filepath Path to the file.
options Reading options (see FileReadOptions).
Returns
true if file was successfully opened.
Implements MayaFlux::IO::FileReader.
Definition at line 71 of file VideoFileReader.cpp.
{
    close();
    auto resolved = resolve_path(filepath);
    m_filepath = resolved;
    m_options = options;
    auto demux = std::make_shared<FFmpegDemuxContext>();
    if (!demux->open(resolved)) {
        set_error(demux->last_error());
        return false;
    }
    auto video = std::make_shared<VideoStreamContext>();
    if (!video->open(*demux, m_target_width, m_target_height)) {
        set_error(video->last_error());
        return false;
    }
    std::shared_ptr<AudioStreamContext> audio;
    if ((m_video_options & VideoReadOptions::EXTRACT_AUDIO) != VideoReadOptions::NONE) {
        bool planar = (m_audio_options & AudioReadOptions::DEINTERLEAVE) != AudioReadOptions::NONE;
        audio = std::make_shared<AudioStreamContext>();
        if (!audio->open(*demux, planar, m_target_sample_rate)) {
            MF_WARN(Journal::Component::IO, Journal::Context::FileIO,
                "VideoFileReader: no audio stream found or audio open failed");
            audio.reset();
        }
    }
    {
        std::unique_lock lock(m_context_mutex);
        m_demux = std::move(demux);
        m_video = std::move(video);
        m_audio = std::move(audio);
    }
    if ((m_options & FileReadOptions::EXTRACT_METADATA) != FileReadOptions::NONE)
        build_metadata(m_demux, m_video);
    if ((m_options & FileReadOptions::EXTRACT_REGIONS) != FileReadOptions::NONE)
        build_regions(m_demux, m_video);
    return true;
}
References build_metadata(), build_regions(), close(), MayaFlux::IO::DEINTERLEAVE, MayaFlux::IO::EXTRACT_AUDIO, MayaFlux::IO::EXTRACT_METADATA, MayaFlux::IO::EXTRACT_REGIONS, MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, m_audio, m_audio_options, m_context_mutex, m_demux, m_filepath, m_options, m_target_height, m_target_sample_rate, m_target_width, m_video, m_video_options, MF_WARN, MayaFlux::IO::NONE, MayaFlux::IO::FileReader::resolve_path(), and set_error().