MayaFlux: MayaFlux::Buffers::VKBufferProcessor::initialize_compute_service
initialize_compute_service()
void MayaFlux::Buffers::VKBufferProcessor::initialize_compute_service () protected
Definition at line 416 of file VKBuffer.cpp.
{
    m_compute_service = Registry::BackendRegistry::instance()
                            .get_service<Registry::Service::ComputeService>();
}
References MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), and m_compute_service.
Referenced by MayaFlux::Buffers::ShaderProcessor::ShaderProcessor().