MayaFlux: MayaFlux::Buffers::MeshBuffer::MeshBuffer
MeshBuffer() [2/2]
MayaFlux::Buffers::MeshBuffer::MeshBuffer (std::shared_ptr< Nodes::GpuSync::MeshWriterNode > node)
Construct from a MeshWriterNode.
The node is polled each graphics cycle. compute_frame() is called on the node, and if its data changed, set_mesh_data() is called internally before MeshProcessor uploads.
Definition at line 51 of file MeshBuffer.cpp.
    : VKBuffer(
          node ? node->get_mesh_vertex_count() * sizeof(Kakshya::MeshVertex) : 0,
          Usage::VERTEX,
          Kakshya::DataModality::VERTEX_POSITIONS_3D)
    , m_node(std::move(node))
{
    if (m_node) {
        auto data = Kakshya::MeshData::empty();
        const auto verts = m_node->get_mesh_vertices();
        const auto indices = m_node->get_mesh_indices();
        Kakshya::MeshInsertion ins(data.vertex_variant, data.index_variant);
        ins.insert_flat(
            std::span<const uint8_t>(
                reinterpret_cast<const uint8_t*>(verts.data()),
                verts.size() * sizeof(Kakshya::MeshVertex)),
            std::span<const uint32_t>(indices),
            Kakshya::VertexLayout::for_meshes(sizeof(Kakshya::MeshVertex)));
        data.layout = Kakshya::VertexLayout::for_meshes(sizeof(Kakshya::MeshVertex));
        data.layout.vertex_count = static_cast<uint32_t>(verts.size());
        m_mesh_data = std::move(data);
    }
    RenderConfig defaults;
    defaults.vertex_shader = "triangle.vert.spv";
    defaults.topology = Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST;
    set_default_render_config(defaults);
    set_needs_depth_attachment(true);
}
References MayaFlux::Kakshya::MeshData::empty(), MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Kakshya::MeshInsertion::insert_flat(), m_mesh_data, m_node, MayaFlux::Buffers::VKBuffer::set_default_render_config(), MayaFlux::Buffers::VKBuffer::set_needs_depth_attachment(), MayaFlux::Portal::Graphics::RenderConfig::topology, MayaFlux::Portal::Graphics::TRIANGLE_LIST, and MayaFlux::Portal::Graphics::RenderConfig::vertex_shader.