MayaFlux: MayaFlux::Core::InputSubsystem::wire_backend_to_manager
wire_backend_to_manager()
void MayaFlux::Core::InputSubsystem::wire_backend_to_manager (IInputBackend * backend) private
Definition at line 285 of file InputSubsystem.cpp.
{
    backend->set_input_callback([this](const InputValue& value) {
        m_handle->inputs.enqueue_input(value);
    });
    backend->set_device_callback([](const InputDeviceInfo& info, bool connected) {
        MF_INFO(Journal::Component::Core, Journal::Context::InputSubsystem,
            "Device {}: {} ({})",
            connected ? "connected" : "disconnected",
            info.name, static_cast<int>(info.backend_type));
    });
}
References MayaFlux::Core::InputDeviceInfo::backend_type, MayaFlux::Journal::Core, MayaFlux::Core::InputManagerHandle::enqueue_input(), MayaFlux::Core::SubsystemProcessingHandle::inputs, MayaFlux::Journal::InputSubsystem, m_handle, MF_INFO, MayaFlux::Core::InputDeviceInfo::name, MayaFlux::Core::IInputBackend::set_device_callback(), and MayaFlux::Core::IInputBackend::set_input_callback().
Referenced by add_backend().