MayaFlux: MayaFlux::Portal::Forma::Inspector::inspect_task
inspect_task()
InspectResult MayaFlux::Portal::Forma::Inspector::inspect_task (const Vruta::TaskEntry & entry, Surface & surface, LayoutCursor & cursor, float x_min, float x_max, float row_h) private
Definition at line 12 of file SchedulerQuery.cpp.
{
    auto routine = entry.routine;
    const std::string name = entry.name;
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "name",
            .reader = [name] { return name.empty() ? "(unnamed)" : name; },
        },
        ValueSpec {
            .label = "token",
            .reader = [routine] {
                return std::string(Reflect::enum_to_string(routine->get_processing_token()));
            },
        },
        ValueSpec {
            .label = "active",
            .reader = [routine] { return routine->is_active() ? "true" : "false"; },
        },
        ValueSpec {
            .label = "delay",
            .reader = [routine] {
                return std::string(Reflect::enum_to_string(routine->get_delay_context()));
            },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), Reflect::short_dynamic_type_name(*entry.routine), dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(values.size());
    for (const auto& spec : values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto group = make_value_group(values, std::move(hbuf), rbufs,
        surface, cursor, x_min, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    return result;
}
References MayaFlux::Reflect::enum_to_string(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueSpec::label, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Vruta::TaskEntry::name, MayaFlux::Vruta::TaskEntry::routine, MayaFlux::Portal::Forma::row_pixel_dims(), MayaFlux::Reflect::short_dynamic_type_name(), and MayaFlux::Portal::Forma::Surface::window().
Referenced by scheduler(), and tasks().