MayaFlux: Lila::Server::cleanup_client
cleanup_client()
void Lila::Server::cleanup_client (int client_fd) private
Cleans up resources for a disconnected client.
Parameters
client_fd Client file descriptor
Definition at line 412 of file Server.cpp.
{
    std::optional<ClientInfo> client_info;
    {
        std::unique_lock lock(m_clients_mutex);
        if (auto it = m_connected_clients.find(client_fd); it != m_connected_clients.end()) {
            client_info = it->second;
            m_connected_clients.erase(it);
        }
    }
    if (client_info) {
        if (m_disconnect_handler) {
            m_disconnect_handler(*client_info);
        }
        m_event_bus.publish(StreamEvent { EventType::ClientDisconnected, *client_info });
        LILA_INFO(Emitter::SERVER, "Client disconnected (fd: " + std::to_string(client_fd) + ")");
    }
    socket_close(client_fd);
}
References LILA_INFO, m_clients_mutex, m_connected_clients, m_disconnect_handler, m_event_bus, Lila::EventBus::publish(), and Lila::socket_close().
Referenced by handle_client().