MayaFlux: MayaFlux::Buffers::NetworkGeometryBuffer::setup_rendering
setup_rendering()
void MayaFlux::Buffers::NetworkGeometryBuffer::setup_rendering (const RenderConfig & config)
Setup rendering with RenderProcessor.
Parameters
config Rendering configuration
Definition at line 111 of file NetworkGeometryBuffer.cpp.
{
    auto resolved_config = resolve_config(config);
    apply_render_config(resolved_config, ShaderConfig { resolved_config.vertex_shader });
    get_processing_chain()->add_processor(m_render_processor, shared_from_this());
    set_default_render_config(resolved_config);
}
References MayaFlux::Buffers::VKBuffer::apply_render_config(), MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Buffers::VKBuffer::m_render_processor, and MayaFlux::Buffers::VKBuffer::set_default_render_config().