MayaFlux: MayaFlux::Portal::Graphics::ComputePress::create_pipeline
create_pipeline()
ComputePipelineID MayaFlux::Portal::Graphics::ComputePress::create_pipeline (ShaderID shader_id, const std::vector< std::vector< DescriptorBindingInfo > > & descriptor_sets = {}, size_t push_constant_size = 0)
Create compute pipeline.
Definition at line 89 of file ComputePress.cpp.
{
    auto shader_module = m_shader_foundry->get_vk_shader_module(shader_id);
    if (!shader_module) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Invalid shader ID: {}", shader_id);
        return INVALID_COMPUTE_PIPELINE;
    }
    auto stage = m_shader_foundry->get_shader_stage(shader_id);
    if (stage != ShaderStage::COMPUTE) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Shader is not a compute shader (stage: {})", static_cast<int>(stage));
        return INVALID_COMPUTE_PIPELINE;
    }
    ComputePipelineID id = m_next_pipeline_id++;
    PipelineState& state = m_pipelines[id];
    state.shader_id = shader_id;
    auto device = m_shader_foundry->get_device();
    if (!m_descriptor_manager) {
        m_descriptor_manager = std::make_shared<Core::VKDescriptorManager>();
        m_descriptor_manager->initialize(device, 1024);
    }
    for (const auto& set_bindings : descriptor_sets) {
        Core::DescriptorSetLayoutConfig layout_config;
        for (const auto& binding : set_bindings) {
            layout_config.add_binding(
                binding.binding,
                binding.type,
                vk::ShaderStageFlagBits::eCompute,
                1);
        }
        state.layouts.push_back(m_descriptor_manager->create_layout(device, layout_config));
    }
    Core::ComputePipelineConfig pipeline_config;
    pipeline_config.shader = shader_module;
    pipeline_config.set_layouts = state.layouts;
    if (push_constant_size > 0) {
        pipeline_config.add_push_constant(
            vk::ShaderStageFlagBits::eCompute,
            static_cast<uint32_t>(push_constant_size));
    }
    state.pipeline = std::make_shared<Core::VKComputePipeline>();
    if (!state.pipeline->create(device, pipeline_config)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Failed to create compute pipeline");
        m_pipelines.erase(id);
        return INVALID_COMPUTE_PIPELINE;
    }
    state.layout = state.pipeline->get_layout();
    MF_INFO(Journal::Component::Portal, Journal::Context::GPUCompute,
        "Created compute pipeline (ID: {}, {} descriptor sets, {} bytes push constants)",
        id, state.layouts.size(), push_constant_size);
    return id;
}
References MayaFlux::Core::DescriptorSetLayoutConfig::add_binding(), MayaFlux::Core::ComputePipelineConfig::add_push_constant(), MayaFlux::Portal::Graphics::COMPUTE, MayaFlux::Portal::Graphics::ShaderFoundry::get_device(), MayaFlux::Portal::Graphics::ShaderFoundry::get_shader_stage(), MayaFlux::Portal::Graphics::ShaderFoundry::get_vk_shader_module(), MayaFlux::Journal::GPUCompute, MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, MayaFlux::Portal::Graphics::ComputePress::PipelineState::layout, MayaFlux::Portal::Graphics::ComputePress::PipelineState::layouts, m_descriptor_manager, m_next_pipeline_id, m_pipelines, m_shader_foundry, MF_ERROR, MF_INFO, MayaFlux::Portal::Graphics::ComputePress::PipelineState::pipeline, MayaFlux::Journal::Portal, MayaFlux::Core::ComputePipelineConfig::set_layouts, MayaFlux::Core::ComputePipelineConfig::shader, and MayaFlux::Portal::Graphics::ComputePress::PipelineState::shader_id.
Referenced by create_pipeline_auto().