MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::validate
validate()
uint64_t MayaFlux::Kakshya::DynamicSoundStream::validate (std::vector< std::span< const double > > & data, uint64_t start_frame = 0) private
Definition at line 12 of file DynamicSoundStream.cpp.
{
    if (data.empty() || data[0].empty()) {
        return 0;
    }
    uint64_t num_frames {};
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        num_frames = data[0].size() / get_num_channels();
    } else {
        if (data.size() < get_num_channels()) {
            std::cerr << "Insufficient channel data for planar organization" << '\n';
            return 0;
        }
        num_frames = data[0].size();
        if (!std::ranges::all_of(data | std::views::drop(1) | std::views::take(get_num_channels() - 1),
                [num_frames](const auto& span) { return span.size() == num_frames; })) {
            std::cerr << "Mismatched frame counts across channels" << '\n';
            return 0;
        }
    }
    if (num_frames == 0) {
        std::cerr << "Attempting to write to container with insufficient data for complete frame. Returning" << '\n';
        return 0;
    }
    if (uint64_t required_end_frame = start_frame + num_frames; m_auto_resize) {
        if (required_end_frame > get_num_frames()) {
            expand_to(required_end_frame);
        }
    } else {
        uint64_t available_frames = (start_frame < get_num_frames()) ? (get_num_frames() - start_frame) : 0;
        if (available_frames == 0) {
            return 0;
        }
        if (num_frames > available_frames) {
            num_frames = available_frames;
        }
        if (required_end_frame > m_num_frames) {
            m_num_frames = required_end_frame;
            setup_dimensions();
        }
    }
    return num_frames;
}
References expand_to(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::SoundStreamContainer::get_num_frames(), MayaFlux::Kakshya::INTERLEAVED, m_auto_resize, MayaFlux::Kakshya::SoundStreamContainer::m_num_frames, MayaFlux::Kakshya::SoundStreamContainer::m_structure, MayaFlux::Kakshya::ContainerDataStructure::organization, and MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions().
Referenced by write_frames().