MayaFlux: MayaFlux::Nodes::Input::InputNode::add_input_callback
add_input_callback()
void MayaFlux::Nodes::Input::InputNode::add_input_callback (const NodeHook & callback, InputEventType event_type, std::optional< double > threshold = {}, std::optional< std::pair< double, double > > range = {}, std::optional< NodeCondition > condition = {}) private
Definition at line 181 of file InputNode.cpp.
{
    m_input_callbacks.push_back({ .callback = callback,
        .event_type = event_type,
        .condition = std::move(condition),
        .threshold = threshold,
        .range = range });
}
References m_input_callbacks.
Referenced by on_button_press(), on_button_release(), on_range_enter(), on_range_exit(), on_threshold_falling(), on_threshold_rising(), and on_value_change().