MayaFlux: MayaFlux::Core::VKDevice::initialize
initialize()
bool MayaFlux::Core::VKDevice::initialize (vk::Instance instance, vk::SurfaceKHR temp_surface, const GraphicsBackendInfo & backend_info)
Initialize device (pick physical device and create logical device)
Parameters
instance Vulkan instance
backend_info Graphics surface configuration
temp_surface Temporary surface for presentation support checks (real surface created with windows and swapchain later)
Returns
true if initialization succeeded
Definition at line 49 of file VKDevice.cpp.
{
    if (!pick_physical_device(instance, nullptr)) {
        return false;
    }
    return create_logical_device(instance, backend_info);
}
References create_logical_device(), and pick_physical_device().
Referenced by MayaFlux::Core::VKContext::initialize().