MayaFlux: MayaFlux::Kriya::SamplingPipeline::SamplingPipeline
SamplingPipeline() [1/2]
MayaFlux::Kriya::SamplingPipeline::SamplingPipeline (std::shared_ptr< Kakshya::DynamicSoundStream > stream, Buffers::BufferManager & mgr, Vruta::TaskScheduler & scheduler, uint32_t channel, uint32_t buf_size)
Begin construction with a loaded stream and output channel.
Parameters
stream Loaded DynamicSoundStream.
mgr BufferManager for channel supply.
scheduler Scheduler for the internal BufferPipeline.
channel Output channel index.
buf_size Engine buffer size in frames.
After construction, optionally call pipeline() and capture() to configure the fluent chain, then call build() to start processing. If build() is never called, the destructor is a no-op.
Definition at line 11 of file SamplingPipeline.cpp.
    : m_stream(std::move(stream))
    , m_processor(std::make_shared<Buffers::StreamSliceProcessor>())
    , m_mgr(mgr)
    , m_capture(nullptr)
    , m_scheduler(scheduler)
    , m_channel(channel)
    , m_buf_size(buf_size)
{
    m_buffer = std::make_shared<Buffers::AudioBuffer>(channel, buf_size);
    m_buffer->set_default_processor(m_processor);
    m_capture = CaptureBuilder(m_buffer);
    m_capture.on_capture_processing().for_cycles(1);
    m_pipeline = BufferPipeline::create(m_scheduler);
    m_processor->set_on_end([this](size_t) {
        if (!any_active())
            m_pipeline->stop_continuous();
    });
}
References any_active(), channel, MayaFlux::Kriya::BufferPipeline::create(), MayaFlux::Kriya::CaptureBuilder::for_cycles(), m_buffer, m_capture, m_pipeline, m_processor, m_scheduler, and MayaFlux::Kriya::CaptureBuilder::on_capture_processing().