MayaFlux: MayaFlux::Buffers::ShaderProcessor::bind_buffer
bind_buffer()
void MayaFlux::Buffers::ShaderProcessor::bind_buffer (const std::string & descriptor_name, const std::shared_ptr< VKBuffer > & buffer)
Bind a VKBuffer to a named shader descriptor.
Parameters
descriptor_name Logical name (e.g., "input", "output")
buffer VKBuffer to bind
Registers the buffer for descriptor set binding. The descriptor_name must match a key in config.bindings.
Definition at line 114 of file ShaderProcessor.cpp.
{
    if (!buffer) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot bind null buffer to descriptor '{}'", descriptor_name);
        return;
    }
    if (m_config.bindings.find(descriptor_name) == m_config.bindings.end()) {
        ShaderBinding default_binding;
        default_binding.set = 0;
        default_binding.binding = static_cast<uint32_t>(m_config.bindings.size());
        default_binding.type = vk::DescriptorType::eStorageBuffer;
        m_config.bindings[descriptor_name] = default_binding;
        // MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        //     "Created default binding for '{}': set={}, binding={}",
        //     descriptor_name, default_binding.set, default_binding.binding);
    }
    m_bound_buffers[descriptor_name] = buffer;
    m_needs_descriptor_rebuild = true;
    // MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
    //     "Bound buffer to descriptor '{}' (size: {} bytes)",
    //     descriptor_name, buffer->get_size_bytes());
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, and MF_ERROR.
Referenced by auto_bind_buffer(), MayaFlux::Buffers::DescriptorBindingsProcessor::bind_matrix_node(), MayaFlux::Buffers::DescriptorBindingsProcessor::bind_scalar_node(), MayaFlux::Buffers::DescriptorBindingsProcessor::bind_structured_node(), and MayaFlux::Buffers::DescriptorBindingsProcessor::bind_vector_node().