MayaFlux: MayaFlux::Nodes::Network::ResonatorNetwork::compute_biquad
compute_biquad()
void MayaFlux::Nodes::Network::ResonatorNetwork::compute_biquad (ResonatorNode & r) private
Compute RBJ biquad bandpass coefficients and push them into a resonator's IIR.
Parameters
r Resonator to update (reads r.frequency, r.q, m_sample_rate)
Definition at line 161 of file ResonatorNetwork.cpp.
{
    /*
     * RBJ Audio EQ Cookbook — BPF (constant 0 dB peak gain):
     *
     *   w0    = 2π f0 / Fs
     *   alpha = sin(w0) / (2 Q)
     *   b0    =  alpha
     *   b1    =  0
     *   b2    = -alpha
     *   a0    =  1 + alpha
     *   a1    = -2 cos(w0)
     *   a2    =  1 - alpha
     *
     * Normalised (divide through by a0):
     *   b_coefs = { b0/a0, 0, b2/a0 }
     *   a_coefs = { 1,  a1/a0, a2/a0 }
     */
    const double w0 = 2.0 * std::numbers::pi * r.frequency / m_sample_rate;
    const double sinw0 = std::sin(w0);
    const double cosw0 = std::cos(w0);
    const double alpha = sinw0 / (2.0 * r.q);
    const double a0 = 1.0 + alpha;
    const std::vector<double> a = {
        1.0,
        (-2.0 * cosw0) / a0,
        (1.0 - alpha) / a0,
    };
    const std::vector<double> b = {
        alpha / a0,
        0.0,
        -alpha / a0,
    };
    r.filter->setACoefficients(a);
    r.filter->setBCoefficients(b);
    r.filter->reset();
}
References a, b, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::filter, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::frequency, MayaFlux::Nodes::Network::NodeNetwork::m_sample_rate, and MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::q.
Referenced by apply_preset(), build_resonators(), set_frequency(), and set_q().