MayaFlux: MayaFlux::Portal::Forma::Inspector::root_audio_buffer
root_audio_buffer() [1/2]
InspectResult MayaFlux::Portal::Forma::Inspector::root_audio_buffer (Buffers::ProcessingToken token, Layer & layer, Context & context, const std::shared_ptr< Core::Window > & window, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F, int depth = 0)
Inspect all root audio buffers for a token across every channel.
Header shows token and total channel count. Each channel is expanded as a nested root_audio_buffer() result, related for visibility cascade.
Definition at line 142 of file BufferQuery.cpp.
{
    const uint32_t ch_count = m_bm.get_num_channels(token);
    const float ind = x_min + static_cast<float>(depth) * k_inspect_indent;
    const std::string header_label = std::string(Reflect::enum_to_string(token))
        + " [" + std::to_string(ch_count) + " ch]";
    auto& bm = m_bm;
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "channels",
            .reader = [&bm, token] { return std::to_string(bm.get_num_channels(token)); },
        },
    };
    auto group = make_value_group(
        header_label, values,
        layer, context, window, cursor,
        ind, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    for (uint32_t ch = 0; ch < ch_count; ++ch) {
        auto ch_result = root_audio_buffer(
            token, ch,
            layer, context, window, cursor,
            x_min, x_max, row_h, depth + 1);
        layer.relate(result.group.header.header_id, ch_result.group.header.header_id);
        result.children.push_back(std::move(ch_result));
    }
    return result;
}
References MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Reflect::enum_to_string(), MayaFlux::Buffers::BufferManager::get_num_channels(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::k_inspect_indent, MayaFlux::Portal::Forma::ValueSpec::label, m_bm, MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::Layer::relate(), and root_audio_buffer().