MayaFlux: MayaFlux::Core::SubsystemManager::get_subsystem
get_subsystem()
std::shared_ptr< ISubsystem > MayaFlux::Core::SubsystemManager::get_subsystem (SubsystemType type)
Get access to a specific subsystem by type.
Parameters
type SubsystemType enum value identifying the subsystem
Returns
Shared pointer to subsystem or nullptr if not found
Provides access to registered subsystems for direct interaction. Returns nullptr if subsystem of specified type doesn't exist.
Definition at line 153 of file SubsystemManager.cpp.
{
    return has_subsystem(type) ? m_subsystems[type] : nullptr;
}
References has_subsystem(), and m_subsystems.
Referenced by get_audio_subsystem(), get_graphics_subsystem(), and get_input_subsystem().