MayaFlux: MayaFlux::Nodes::BinaryOpNode::process_sample
process_sample()
double MayaFlux::Nodes::BinaryOpNode::process_sample (double input = 0.) override virtual
Processes a single sample through both nodes and combines the results.
Parameters
input The input sample
Returns
The combined output after processing through both nodes
The input is processed by both the left and right nodes, and their outputs are combined using the specified function.
Implements MayaFlux::Nodes::Node.
Definition at line 229 of file NodeStructure.cpp.
{
    if (!m_lhs || !m_rhs) {
        return input;
    }
    if (!is_initialized())
        initialize();
    atomic_inc_modulator_count(m_lhs->m_modulator_count, 1);
    atomic_inc_modulator_count(m_rhs->m_modulator_count, 1);
    uint32_t lstate = m_lhs->m_state.load();
    if (lstate & NodeState::PROCESSED) {
        m_last_lhs_value = input + m_lhs->get_last_output();
    } else {
        m_last_lhs_value = m_lhs->process_sample(input);
        atomic_add_flag(m_lhs->m_state, NodeState::PROCESSED);
    }
    uint32_t rstate = m_rhs->m_state.load();
    if (rstate & NodeState::PROCESSED) {
        m_last_rhs_value = input + m_rhs->get_last_output();
    } else {
        m_last_rhs_value = m_rhs->process_sample(input);
        atomic_add_flag(m_rhs->m_state, NodeState::PROCESSED);
    }
    m_last_output = m_func(m_last_lhs_value, m_last_rhs_value);
    if (!m_state_saved || (m_state_saved && m_fire_events_during_snapshot))
        notify_tick(m_last_output);
    atomic_dec_modulator_count(m_lhs->m_modulator_count, 1);
    atomic_dec_modulator_count(m_rhs->m_modulator_count, 1);
    try_reset_processed_state(m_lhs);
    try_reset_processed_state(m_rhs);
    return m_last_output;
}
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), initialize(), is_initialized(), MayaFlux::Nodes::Node::m_fire_events_during_snapshot, m_func, m_last_lhs_value, MayaFlux::Nodes::Node::m_last_output, m_last_rhs_value, m_lhs, m_rhs, m_state_saved, notify_tick(), MayaFlux::Nodes::PROCESSED, and MayaFlux::Nodes::try_reset_processed_state().
Referenced by process_batch().