MayaFlux: MayaFlux::Vruta::TaskScheduler::ensure_domain
ensure_domain()
void MayaFlux::Vruta::TaskScheduler::ensure_domain (ProcessingToken token, unsigned int rate = 0) private
Initialize a processing domain if it doesn't exist.
Parameters
token Processing domain to initialize
rate Processing rate for the domain
Definition at line 231 of file Scheduler.cpp.
{
    auto clock_it = m_token_clocks.find(token);
    if (clock_it == m_token_clocks.end()) {
        unsigned int domain_rate = (rate > 0) ? rate : get_default_rate(token);
        switch (token) {
        case ProcessingToken::SAMPLE_ACCURATE:
            m_token_clocks[token] = std::make_unique<SampleClock>(domain_rate);
            break;
        case ProcessingToken::FRAME_ACCURATE:
            m_token_clocks[token] = std::make_unique<SampleClock>(domain_rate);
            break;
        case ProcessingToken::ON_DEMAND:
            m_token_clocks[token] = std::make_unique<SampleClock>(domain_rate);
            break;
        default:
            m_token_clocks[token] = std::make_unique<SampleClock>(domain_rate);
            break;
        }
    }
}
References MayaFlux::Vruta::FRAME_ACCURATE, get_default_rate(), m_token_clocks, MayaFlux::Vruta::ON_DEMAND, MayaFlux::Vruta::SAMPLE_ACCURATE, and token.
Referenced by add_task(), register_token_processor(), and TaskScheduler().