MayaFlux: MayaFlux::IO::SoundFileReader::read_frames
read_frames()
std::vector< Kakshya::DataVariant > MayaFlux::IO::SoundFileReader::read_frames (uint64_t num_frames, uint64_t offset = 0)
Read a specific number of frames from the file.
Parameters
num_frames Number of frames to read.
offset Frame offset from beginning.
Returns
DataVariant containing std::vector<double>.
Definition at line 515 of file SoundFileReader.cpp.
{
    std::shared_lock<std::shared_mutex> lock(m_context_mutex);
    if (!m_context || !m_context->is_valid()) {
        set_error("File not open");
        return {};
    }
    auto ctx = m_context;
    if (offset != m_current_frame_position.load()) {
        lock.unlock();
        std::unique_lock<std::shared_mutex> write_lock(m_context_mutex);
        if (!m_context || !m_context->is_valid()) {
            set_error("File closed during operation");
            return {};
        }
        ctx = m_context;
        if (!seek_internal(ctx, offset)) {
            return {};
        }
        write_lock.unlock();
        lock.lock();
        if (!m_context || !m_context->is_valid()) {
            set_error("File closed during operation");
            return {};
        }
        ctx = m_context;
    }
    return decode_frames(ctx, num_frames, offset);
}
References decode_frames(), m_context, m_context_mutex, m_current_frame_position, seek_internal(), and set_error().
Referenced by read_all(), and read_region().