MayaFlux: MayaFlux::Core::GLFWSingleton::initialize
initialize()
bool MayaFlux::Core::GLFWSingleton::initialize () static
Initializes the GLFW library if not already initialized.
Returns
True if initialization succeeded or was already done, false on failure
Sets up the GLFW error callback and calls glfwInit() if needed. Safe to call multiple times; initialization occurs only once.
Definition at line 59 of file GlfwSingleton.cpp.
{
    if (s_initialized)
        return true;
    if (!s_configured) {
        MF_WARN(Journal::Component::Core, Journal::Context::WindowingSubsystem,
            "GLFWSingleton::initialize() called without prior configure() — using default pre-init hints");
        configure(s_preinit_config);
    }
    glfwSetErrorCallback([](int error, const char* description) {
        MF_ERROR(Journal::Component::Core, Journal::Context::WindowingSubsystem, "GLFW Error {}: {}", error, description);
    });
    if (!glfwInit()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::WindowingSubsystem, "Failed to initialize GLFW");
        return false;
    }
    s_initialized = true;
    s_window_count = 0;
    return true;
}
References configure(), MayaFlux::Journal::Core, MF_ERROR, MF_WARN, s_configured, s_initialized, s_preinit_config, s_window_count, and MayaFlux::Journal::WindowingSubsystem.
Referenced by get_required_instance_extensions(), and MayaFlux::Core::GlfwWindow::GlfwWindow().