MayaFlux: MayaFlux::Kakshya::WindowContainer::get_frames
get_frames()
void MayaFlux::Kakshya::WindowContainer::get_frames (std::span< double > output, uint64_t start_frame, uint64_t num_frames) const override virtual
Get multiple frames efficiently.
Parameters
output Buffer to write frames into
start_frame First frame index
num_frames Number of frames to retrieve
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 591 of file WindowContainer.cpp.
{
    std::shared_lock lock(m_data_mutex);
    const uint64_t h = m_structure.get_height();
    if (start_frame >= h || output.empty() || m_processed_data.empty()) {
        std::ranges::fill(output, 0.0);
        return;
    }
    const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_processed_data[0]);
    if (!pixels || pixels->empty()) {
        std::ranges::fill(output, 0.0);
        return;
    }
    const uint64_t w = m_structure.get_width();
    const uint64_t c = m_structure.get_channel_count();
    const uint64_t row_elems = w * c;
    const uint64_t frames_to_copy = std::min(num_frames, h - start_frame);
    const uint64_t elems_to_copy = std::min(frames_to_copy * row_elems,
        static_cast<uint64_t>(output.size()));
    const uint64_t src_offset = start_frame * row_elems;
    for (uint64_t i = 0; i < elems_to_copy; ++i)
        output[i] = static_cast<double>((*pixels)[src_offset + i]) / 255.0;
    if (elems_to_copy < output.size())
        std::fill(output.begin() + elems_to_copy, output.end(), 0.0);
}
References MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), h, lock(), m_data_mutex, m_processed_data, m_structure, and pixels.