MayaFlux: Lila::Server::process_control_message
process_control_message()
void Lila::Server::process_control_message (int client_fd, std::string_view message) private
Processes control messages (e.g., session, ping)
Parameters
client_fd Client file descriptor
message Control message string
Definition at line 324 of file Server.cpp.
{
    if (message.starts_with("session ")) {
        std::string session_id(message.substr(8));
        set_client_session(client_fd, session_id);
        if (!send_message(client_fd, R"({"status":"success","message":"Session ID set to ')" + session_id + R"('"})")) {
            LILA_WARN(Emitter::SERVER, "Failed to send session confirmation to client fd " + std::to_string(client_fd));
        }
    } else if (message.starts_with("ping")) {
        if (!send_message(client_fd, R"({"status":"success","message":"pong"})")) {
            LILA_WARN(Emitter::SERVER, "Failed to send pong to client fd " + std::to_string(client_fd));
        }
    } else {
        if (!send_message(client_fd, "{\"status\":\"error\",\"message\":\"Unknown command: " + std::string(message) + "\"}")) {
            LILA_WARN(Emitter::SERVER, "Failed to send unknown command error to client fd " + std::to_string(client_fd));
        }
    }
}
References LILA_WARN, send_message(), and set_client_session().
Referenced by handle_client().