MayaFlux: MayaFlux::IO::FFmpegDemuxContext::open
open()
bool MayaFlux::IO::FFmpegDemuxContext::open (const std::string & filepath)
Open a media file and probe stream information.
Parameters
filepath Absolute or relative path to the media file.
Returns
True on success; false sets internal error string.
Definition at line 36 of file FFmpegDemuxContext.cpp.
{
    close();
    init_ffmpeg();
    if (avformat_open_input(&format_context, filepath.c_str(), nullptr, nullptr) < 0) {
        m_last_error = "avformat_open_input failed: " + filepath;
        return false;
    }
    if (avformat_find_stream_info(format_context, nullptr) < 0) {
        avformat_close_input(&format_context);
        m_last_error = "avformat_find_stream_info failed: " + filepath;
        return false;
    }
    return true;
}
References close(), format_context, init_ffmpeg(), and m_last_error.
Referenced by MayaFlux::IO::SoundFileReader::can_read().