MayaFlux: MayaFlux::Nodes::Network::ResonatorNetwork::apply_one_to_one_parameter
apply_one_to_one_parameter()
void MayaFlux::Nodes::Network::ResonatorNetwork::apply_one_to_one_parameter (const std::string & param, const std::shared_ptr< NodeNetwork > & source) private
Apply ONE_TO_ONE values from a source network to the named parameter.
Parameters
param "frequency", "q", or "gain"
source NodeNetwork providing one value per resonator
Definition at line 337 of file ResonatorNetwork.cpp.
{
    const size_t count = std::min(m_resonators.size(), source->get_node_count());
    for (size_t i = 0; i < count; ++i) {
        const auto val = source->get_node_output(i);
        if (!val.has_value()) {
            continue;
        }
        if (param == "frequency") {
            set_frequency(i, *val);
        } else if (param == "q") {
            set_q(i, *val);
        } else if (param == "gain") {
            m_resonators[i].gain = *val;
        }
    }
}
References count, m_resonators, set_frequency(), and set_q().
Referenced by update_mapped_parameters().