MayaFlux: MayaFlux::Kakshya::ContiguousAccessProcessor::store_metadata
store_metadata()
void ContiguousAccessProcessor::store_metadata (const std::shared_ptr< SignalSourceContainer > & container) private
Store dimension and layout metadata from the container.
Parameters
container The SignalSourceContainer to query.
Definition at line 40 of file ContiguousAccessProcessor.cpp.
{
    m_structure = container->get_structure();
    m_total_elements = container->get_total_elements();
    if (m_current_position.empty()) {
        uint64_t num_channels = m_structure.get_channel_count();
        m_current_position.assign(num_channels, 0);
    }
    if (m_output_shape.empty()) {
        uint64_t num_frames = m_structure.get_samples_count_per_channel();
        uint64_t num_channels = m_structure.get_channel_count();
        m_output_shape = {
            std::min<uint64_t>(1024UL, num_frames),
            num_channels
        };
    }
    if (auto stream = std::dynamic_pointer_cast<StreamContainer>(container)) {
        m_looping_enabled = stream->is_looping();
        m_loop_region = stream->get_loop_region();
        auto stream_positions = stream->get_read_position();
        if (!stream_positions.empty()) {
            m_current_position = stream_positions;
        }
    }
}
References MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_samples_count_per_channel(), MayaFlux::Kakshya::ContainerDataStructure::get_total_elements(), m_current_position, m_loop_region, m_looping_enabled, m_output_shape, m_structure, and m_total_elements.
Referenced by on_attach(), and set_output_size().