MayaFlux: MayaFlux::Nodes::GpuSync::GeometryReadbackNode::compute_frame
compute_frame()
void MayaFlux::Nodes::GpuSync::GeometryReadbackNode::compute_frame () override virtual
Download vertex data from GPU to CPU.
Issues a synchronous GPU-to-CPU transfer. Safe to call at VISUAL_RATE from a FRAME_ACCURATE metro callback.
Implements MayaFlux::Nodes::GpuSync::GpuSync.
Definition at line 48 of file GeometryReadbackNode.cpp.
{
    const size_t buf_bytes = m_gpu_buffer->get_size_bytes();
    if (!m_gpu_buffer || buf_bytes == 0)
        return;
    const size_t count = buf_bytes / sizeof(Kakshya::MeshVertex);
    m_vertices.resize(count);
    Buffers::download_from_gpu_async(m_gpu_buffer, m_vertices.data(), buf_bytes, m_staging_buffer);
    set_vertices<Kakshya::MeshVertex>(std::span { m_vertices.data(), m_vertices.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(count);
    set_vertex_layout(*layout);
}
References count, MayaFlux::Buffers::download_from_gpu_async(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout(), m_gpu_buffer, m_staging_buffer, m_vertices, and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout().