MayaFlux: MayaFlux::Buffers::DataWriteProcessor::processing_function
processing_function()
void MayaFlux::Buffers::DataWriteProcessor::processing_function (const std::shared_ptr< Buffer > & buffer) override protected virtual
The core processing function that must be implemented by derived classes.
Parameters
buffer Buffer to process
This method is where the actual transformation logic is implemented. It should contain the algorithmic details of how the buffer's data is transformed, analyzed, or processed. The implementation can utilize any backend capabilities available to the processor, including:
Parallel Processing: Using multi-threading or GPU compute for large datasets
Data Transformations: Applying mathematical operations, filters, or effects
Feature Extraction: Analyzing data characteristics for further processing
Derived classes must override this method to provide specific processing behavior.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 137 of file DataWriteProcessor.cpp.
{
    auto vk = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "DataWriteProcessor attached to non-VKBuffer");
        return;
    }
    if (m_texture_dirty.test(std::memory_order_acquire)) {
        m_texture_dirty.clear(std::memory_order_release);
        if (m_pending_texture) {
            if (auto rp = vk->get_render_processor()) {
                rp->bind_texture(m_pending_texture->binding, m_pending_texture->image);
            }
            m_pending_texture.reset();
        }
    }
    if (m_pixel_dirty.test(std::memory_order_acquire)) {
        m_pixel_dirty.clear(std::memory_order_release);
        std::swap(m_pixel_active, m_pixel_pending);
        upload_texture(vk, m_pixel_active);
    }
    if (m_gpu_texture) {
        if (auto rp = vk->get_render_processor()) {
            if (!m_tex_binding_confirmed) {
                rp->bind_texture(m_tex_binding, m_gpu_texture);
                m_tex_binding_confirmed = true;
            }
        }
    }
    if (!m_data_dirty.test(std::memory_order_acquire)) {
        return;
    }
    m_data_dirty.clear(std::memory_order_release);
    std::swap(m_active, m_data_pending);
    if (m_active.empty()) {
        return;
    }
    upload_primary(vk, m_active);
    for (size_t i = 1; i < m_active.size(); ++i) {
        if (i == 1 && m_tex_width > 0 && is_vertex_modality(m_modality)) {
            upload_texture(vk, m_active[i]);
        } else {
            upload_secondary(vk, m_active[i]);
        }
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, is_vertex_modality(), m_active, m_data_dirty, m_data_pending, m_gpu_texture, m_modality, m_pending_texture, m_pixel_active, m_pixel_dirty, m_pixel_pending, m_tex_binding, m_tex_binding_confirmed, m_tex_width, m_texture_dirty, MF_RT_ERROR, upload_primary(), upload_secondary(), and upload_texture().