MayaFlux: MayaFlux::Platform::SystemConfig::get_clang_includes
get_clang_includes()
std::vector< std::string > MayaFlux::Platform::SystemConfig::get_clang_includes () static private
Definition at line 228 of file HostEnvironment.cpp.
{
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    const char* cmd = "echo. | clang -v -E -x c++ - 2>&1";
#else
    const char* cmd = "clang -v -E -x c++ - 2>&1 < /dev/null";
#endif
    auto clang_output = exec_command(cmd);
    return parse_clang_search_paths(clang_output);
}
References cmd, exec_command(), and parse_clang_search_paths().
Referenced by get_system_includes().