MayaFlux: MayaFlux::Nodes::NodeGraphManager::add_to_root
add_to_root() [1/2]
void MayaFlux::Nodes::NodeGraphManager::add_to_root (const std::shared_ptr< Node > & node, ProcessingToken token, unsigned int channel = 0)
Add node to specific processing token and channel.
Parameters
node Node to add
token Processing domain (AUDIO_RATE, VISUAL_RATE, etc.)
channel Channel within that domain
Registers the node with the specified processing domain and channel. The node's output will contribute to that token/channel's output. If the node is not already globally registered, it will be registered automatically.
Definition at line 19 of file NodeGraphManager.cpp.
{
    set_channel_mask(node, channel);
    node->set_sample_rate(m_registered_sample_rate);
    node->set_frame_rate(m_registered_frame_rate);
    if (token == ProcessingToken::VISUAL_RATE) {
        node->set_gpu_compatible(true);
    }
    auto& root = get_root_node(token, channel);
    root.register_node(node);
}
References channel, get_root_node(), m_registered_frame_rate, m_registered_sample_rate, set_channel_mask(), and MayaFlux::Nodes::VISUAL_RATE.
Referenced by MayaFlux::Kriya::TemporalActivation::activate_node(), MayaFlux::Nodes::detail::composite_initialize(), MayaFlux::Nodes::ChainNode::initialize(), MayaFlux::Nodes::BinaryOpNode::initialize(), and route_node_to_channels().