MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::enable_circular_buffer
enable_circular_buffer()
void MayaFlux::Kakshya::DynamicSoundStream::enable_circular_buffer (uint64_t capacity)
Enable circular buffer mode with fixed capacity.
Writes wrap around at capacity boundary, potentially overwriting older data.
Parameters
capacity Fixed number of frames the circular buffer can hold
Definition at line 316 of file DynamicSoundStream.cpp.
{
    ensure_capacity(capacity);
    Region circular_region {
        { 0, 0 },
        { capacity - 1, get_num_channels() - 1 }
    };
    set_loop_region(circular_region);
    set_looping(true);
    m_circular_capacity = capacity;
    m_is_circular = true;
}
References ensure_capacity(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), m_circular_capacity, m_is_circular, MayaFlux::Kakshya::SoundStreamContainer::set_loop_region(), and MayaFlux::Kakshya::SoundStreamContainer::set_looping().