MayaFlux: MayaFlux::Core::InputSubsystem::initialize_hid_backend
initialize_hid_backend()
void MayaFlux::Core::InputSubsystem::initialize_hid_backend () private
Definition at line 299 of file InputSubsystem.cpp.
{
    HIDBackend::Config hid_config;
    hid_config.filters = m_config.hid.filters;
    hid_config.read_buffer_size = m_config.hid.read_buffer_size;
    hid_config.poll_timeout_ms = m_config.hid.poll_timeout_ms;
    hid_config.auto_reconnect = m_config.hid.auto_reconnect;
    hid_config.reconnect_interval_ms = m_config.hid.reconnect_interval_ms;
    auto hid = std::make_unique<HIDBackend>(hid_config);
    if (add_backend(std::move(hid))) {
        if (m_config.hid.auto_open) {
            auto* backend = dynamic_cast<HIDBackend*>(get_backend(InputType::HID));
            for (const auto& dev : backend->get_devices()) {
                backend->open_device(dev.id);
            }
        }
    }
}
References add_backend(), MayaFlux::Core::HIDBackendInfo::auto_open, MayaFlux::Core::HIDBackend::Config::auto_reconnect, MayaFlux::Core::HIDBackendInfo::auto_reconnect, MayaFlux::Core::HIDBackend::Config::filters, MayaFlux::Core::HIDBackendInfo::filters, get_backend(), MayaFlux::Core::GlobalInputConfig::hid, MayaFlux::Core::HID, m_config, MayaFlux::Core::HIDBackend::open_device(), MayaFlux::Core::HIDBackend::Config::poll_timeout_ms, MayaFlux::Core::HIDBackendInfo::poll_timeout_ms, MayaFlux::Core::HIDBackend::Config::read_buffer_size, MayaFlux::Core::HIDBackendInfo::read_buffer_size, MayaFlux::Core::HIDBackend::Config::reconnect_interval_ms, and MayaFlux::Core::HIDBackendInfo::reconnect_interval_ms.
Referenced by initialize().