MayaFlux: MayaFlux::Vruta::NetworkSource::NetworkSource
NetworkSource() [1/3]
MayaFlux::Vruta::NetworkSource::NetworkSource (const Core::EndpointInfo & info) explicit
Open a network endpoint and begin receiving.
Parameters
info Endpoint configuration.
Opens the endpoint via NetworkService and registers a receive callback that calls signal(). Logs a warning and remains inert if NetworkService is unavailable.
Definition at line 10 of file NetworkSource.cpp.
{
    auto* svc = Registry::BackendRegistry::instance()
                    .get_service<Registry::Service::NetworkService>();
    if (!svc) {
        MF_WARN(Journal::Component::Vruta, Journal::Context::Networking,
            "Cannot open NetworkSource: NetworkService not available");
        return;
    }
    m_endpoint_id = svc->open_endpoint(info);
    if (m_endpoint_id == 0) {
        MF_WARN(Journal::Component::Vruta, Journal::Context::Networking,
            "NetworkSource: endpoint open failed");
        return;
    }
    svc->set_endpoint_receive_callback(m_endpoint_id,
        [this](uint64_t id, const uint8_t* data, size_t size, std::string_view addr) {
            Core::NetworkMessage msg;
            msg.endpoint_id = id;
            msg.data.assign(data, data + size);
            msg.sender_address = std::string(addr);
            signal(msg);
        });
    MF_DEBUG(Journal::Component::Vruta, Journal::Context::Networking,
        "NetworkSource opened endpoint {}", m_endpoint_id);
}
References MayaFlux::Core::NetworkMessage::data, MayaFlux::Core::NetworkMessage::endpoint_id, MayaFlux::Registry::BackendRegistry::get_service(), id, MayaFlux::Registry::BackendRegistry::instance(), m_endpoint_id, MF_DEBUG, MF_WARN, MayaFlux::Journal::Networking, MayaFlux::Core::NetworkMessage::sender_address, signal(), size, and MayaFlux::Journal::Vruta.