MayaFlux: MayaFlux::Yantra::StatisticalAnalyzer::compute_statistical_values
compute_statistical_values()
template<ComputeData InputType = std::vector<Kakshya::DataVariant>, ComputeData OutputType = Eigen::VectorXd> std::vector< double > MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values (std::span< const double > data, StatisticalMethod method) const inline private
Compute statistical values using span (zero-copy processing)
Definition at line 496 of file StatisticalAnalyzer.hpp.
    {
        const size_t num_windows = calculate_num_windows(data.size());
        namespace D = MayaFlux::Kinesis::Discrete;
        switch (method) {
        case StatisticalMethod::MEAN:
            return D::mean(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::VARIANCE:
            return D::variance(data, num_windows, m_hop_size, m_window_size, m_sample_variance);
        case StatisticalMethod::STD_DEV:
            return D::std_dev(data, num_windows, m_hop_size, m_window_size, m_sample_variance);
        case StatisticalMethod::SKEWNESS:
            return D::skewness(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::KURTOSIS:
            return D::kurtosis(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::MEDIAN:
            return D::median(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::PERCENTILE:
            return D::percentile(data, num_windows, m_hop_size, m_window_size, m_percentile_value);
        case StatisticalMethod::ENTROPY:
            return D::entropy(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::MIN:
            return D::min(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::MAX:
            return D::max(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::RANGE:
            return D::range(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::SUM:
            return D::sum(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::COUNT:
            return D::count(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::RMS:
            return D::rms(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::MAD:
            return D::mad(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::CV:
            return D::coefficient_of_variation(data, num_windows, m_hop_size, m_window_size, m_sample_variance);
        case StatisticalMethod::MODE:
            return D::mode(data, num_windows, m_hop_size, m_window_size);
        case StatisticalMethod::ZSCORE:
            return D::mean_zscore(data, num_windows, m_hop_size, m_window_size, m_sample_variance);
        default:
            return D::mean(data, num_windows, m_hop_size, m_window_size);
        }
    }
References MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::calculate_num_windows(), MayaFlux::Kinesis::Discrete::coefficient_of_variation(), MayaFlux::Kinesis::Discrete::count(), MayaFlux::Yantra::COUNT, MayaFlux::Yantra::CV, MayaFlux::Kinesis::Discrete::entropy(), MayaFlux::Yantra::ENTROPY, MayaFlux::Kinesis::Discrete::kurtosis(), MayaFlux::Yantra::KURTOSIS, MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::m_hop_size, MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::m_percentile_value, MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::m_sample_variance, MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::m_window_size, MayaFlux::Kinesis::Discrete::mad(), MayaFlux::Yantra::MAD, MayaFlux::Kinesis::Discrete::max(), MayaFlux::Yantra::MAX, MayaFlux::Kinesis::Discrete::mean(), MayaFlux::Yantra::MEAN, MayaFlux::Kinesis::Discrete::mean_zscore(), MayaFlux::Kinesis::Discrete::median(), MayaFlux::Yantra::MEDIAN, MayaFlux::Kinesis::Discrete::min(), MayaFlux::Yantra::MIN, MayaFlux::Kinesis::Discrete::mode(), MayaFlux::Yantra::MODE, MayaFlux::Kinesis::Discrete::percentile(), MayaFlux::Yantra::PERCENTILE, MayaFlux::Kinesis::Discrete::range(), MayaFlux::Yantra::RANGE, MayaFlux::Kinesis::Discrete::rms(), MayaFlux::Yantra::RMS, MayaFlux::Kinesis::Discrete::skewness(), MayaFlux::Yantra::SKEWNESS, MayaFlux::Kinesis::Discrete::std_dev(), MayaFlux::Yantra::STD_DEV, MayaFlux::Kinesis::Discrete::sum(), MayaFlux::Yantra::SUM, MayaFlux::Kinesis::Discrete::variance(), MayaFlux::Yantra::VARIANCE, and MayaFlux::Yantra::ZSCORE.
Referenced by MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::analyze_implementation().