MayaFlux: MayaFlux::Nodes::NodeGraphManager::ensure_root_exists
ensure_root_exists()
void MayaFlux::Nodes::NodeGraphManager::ensure_root_exists (ProcessingToken token, unsigned int channel) private
Ensures a root node exists for the given token and channel.
Parameters
token Processing domain
channel Channel index
Creates and registers a new root node if one does not already exist.
Definition at line 318 of file NodeGraphManager.cpp.
{
    if (m_token_roots[token].find(channel) == m_token_roots[token].end()) {
        m_token_roots[token][channel] = std::make_shared<RootNode>(token, channel);
    }
}
References m_token_roots.
Referenced by add_network(), ensure_token_exists(), get_root_node(), NodeGraphManager(), and route_network_to_channels().