MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_or_create_graphics_unit
get_or_create_graphics_unit()
RootGraphicsUnit & MayaFlux::Buffers::TokenUnitManager::get_or_create_graphics_unit (ProcessingToken token)
Gets or creates a root graphics unit for the specified token.
Parameters
token Processing domain
Returns
Reference to the root graphics unit
If the unit doesn't exist, creates it and initializes it. Thread-safe creation via lock guard.
Definition at line 134 of file TokenUnitManager.cpp.
{
    auto it = m_graphics_units.find(token);
    if (it == m_graphics_units.end()) {
        std::lock_guard<std::mutex> lock(m_manager_mutex);
        auto [inserted_it, success] = m_graphics_units.emplace(token, RootGraphicsUnit {});
        inserted_it->second.initialize(token);
        MF_INFO(Journal::Component::Core, Journal::Context::BufferManagement,
            "Created new graphics unit for token {}", static_cast<int>(token));
        return inserted_it->second;
    }
    return it->second;
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, m_graphics_units, m_manager_mutex, and MF_INFO.
Referenced by MayaFlux::Buffers::BufferAccessControl::add_graphics_buffer(), MayaFlux::Buffers::BufferAccessControl::get_graphics_processing_chain(), and MayaFlux::Buffers::BufferAccessControl::get_root_graphics_buffer().