MayaFlux: MayaFlux::Nodes::Input::InputNode::process_input
process_input()
void MayaFlux::Nodes::Input::InputNode::process_input (const Core::InputValue & value) virtual
Process an input value from a backend.
Parameters
value The input value
Called by InputManager when input arrives. This is the main entry point.
Extracts scalar value via extract_value()
Applies smoothing
Stores result
Fires notify_tick() which triggers user callbacks
Thread-safe. Called from InputManager's processing thread.
Definition at line 40 of file InputNode.cpp.
{
    double extracted = extract_value(value);
    double current = m_current_value.load();
    double smoothed = apply_smoothing(extracted, current);
    m_target_value.store(extracted);
    m_current_value.store(smoothed);
    m_last_output = smoothed;
    m_has_new_input.store(true);
    m_last_device_id.store(value.device_id);
    m_last_source_type = value.source_type;
    (void)m_input_history.push(value);
    notify_tick(smoothed);
}
References apply_smoothing(), MayaFlux::Core::InputValue::device_id, extract_value(), m_current_value, m_has_new_input, m_input_history, m_last_device_id, MayaFlux::Nodes::Node::m_last_output, m_last_source_type, m_target_value, notify_tick(), and MayaFlux::Core::InputValue::source_type.