MayaFlux: MayaFlux::Nodes::RootNode::process_frame
process_frame()
void MayaFlux::Nodes::RootNode::process_frame ()
Processes a single frame from all registered nodes.
This method processes each registered node for a single frame. It is useful in scenarios where frame-based processing is required, such as visual or animation data processing.
Definition at line 156 of file RootNode.cpp.
{
    if (!preprocess())
        return;
    for (auto& node : m_Nodes) {
        uint32_t state = node->m_state.load();
        if (!(state & NodeState::PROCESSED)) {
            node->process_sample();
            atomic_add_flag(node->m_state, NodeState::PROCESSED);
        }
    }
    postprocess();
}
References MayaFlux::Nodes::atomic_add_flag(), m_Nodes, postprocess(), preprocess(), and MayaFlux::Nodes::PROCESSED.
Referenced by process_batch_frame().