MayaFlux: MayaFlux::IO::TextFileWriter::write_bytes
write_bytes()
bool MayaFlux::IO::TextFileWriter::write_bytes (const void * data, size_t size) override virtual
Write raw bytes.
Implements MayaFlux::IO::FileWriter.
Definition at line 96 of file TextFileWriter.cpp.
{
    std::lock_guard lock(m_mutex);
    if (!m_is_open || !m_file.is_open()) {
        m_last_error = "File not open";
        return false;
    }
    if (should_rotate()) {
        if (!rotate_file()) {
            return false;
        }
    }
    m_file.write(static_cast<const char*>(data), size);
    if (!m_file.good()) {
        m_last_error = "Write failed";
        return false;
    }
    m_bytes_written += size;
    if ((m_options & FileWriteOptions::SYNC) != FileWriteOptions::NONE) {
        m_file.flush();
    }
    return true;
}
References m_bytes_written, m_file, m_is_open, m_last_error, m_mutex, m_options, MayaFlux::IO::NONE, rotate_file(), should_rotate(), and MayaFlux::IO::SYNC.
Referenced by write_line(), and write_string().