MayaFlux: MayaFlux::Kinesis::SpatialIndex::hash_cell
hash_cell()
template<typename PointT > uint64_t MayaFlux::Kinesis::SpatialIndex< PointT >::hash_cell (const PointT & p) const private
Definition at line 221 of file SpatialIndex.cpp.
{
    if constexpr (std::is_same_v<PointT, glm::vec3>) {
        auto [cx, cy, cz] = detail::cell_coords_3d(p, m_inv_cell);
        return detail::hash_cell_3d(cx, cy, cz);
    } else {
        return detail::hash_cell_nd(p, m_inv_cell);
    }
}
References MayaFlux::Kinesis::detail::cell_coords_3d(), MayaFlux::Kinesis::detail::hash_cell_3d(), and MayaFlux::Kinesis::detail::hash_cell_nd().