MayaFlux: MayaFlux::Nodes::Network::PhysicsOperator::process
process()
void MayaFlux::Nodes::Network::PhysicsOperator::process (float dt) override virtual
Process for one batch cycle.
Parameters
dt Time delta or sample count (operator-specific)
Implements MayaFlux::Nodes::Network::NetworkOperator.
Definition at line 88 of file PhysicsOperator.cpp.
{
    if (m_collections.empty()) {
        return;
    }
    apply_forces();
    integrate(dt);
    handle_boundary_conditions();
    sync_to_point_collection();
    for (auto& group : m_collections) {
        group.collection->compute_frame();
    }
}
References apply_forces(), handle_boundary_conditions(), integrate(), m_collections, and sync_to_point_collection().