MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::get_metadata
get_metadata()
std::unordered_map< std::string, std::string > MayaFlux::Nodes::Network::WaveguideNetwork::get_metadata () const override virtual
Get network metadata for debugging/visualization.
Returns
Map of property names to string representations
Subclasses can override to expose internal state:
Particle count, average velocity
Modal frequencies, decay times
Waveguide delay lengths etc.
Reimplemented from MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 486 of file WaveguideNetwork.cpp.
{
    auto metadata = NodeNetwork::get_metadata();
    metadata["type"] = std::string(Reflect::enum_to_string(m_type));
    metadata["fundamental"] = std::to_string(m_fundamental) + " Hz";
    metadata["delay_length"] = std::to_string(m_delay_length_integer)
        + " + " + std::to_string(m_delay_length_fraction) + " samples";
    metadata["loss_factor"] = std::to_string(get_loss_factor());
    metadata["pickup_position"] = std::to_string(get_pickup_position());
    metadata["exciter_type"] = std::string(Reflect::enum_to_string(m_exciter_type));
    return metadata;
}
References MayaFlux::Reflect::enum_to_string(), get_loss_factor(), MayaFlux::Nodes::Network::NodeNetwork::get_metadata(), get_pickup_position(), m_delay_length_fraction, m_delay_length_integer, m_exciter_type, m_fundamental, and m_type.