MayaFlux: MayaFlux::Buffers::SDFMeshProcessor::on_before_execute
on_before_execute()
bool MayaFlux::Buffers::SDFMeshProcessor::on_before_execute (Portal::Graphics::CommandBufferID cmd_id, const std::shared_ptr< VKBuffer > & buffer) override protected virtual
Called before each process callback.
Parameters
cmd Command buffer
buffer Currently processing buffer
Returns
True to proceed with execution, false to skip
Override to update push constants or dynamic descriptors.
Reimplemented from MayaFlux::Buffers::ShaderProcessor.
Definition at line 157 of file SDFMeshProcessor.cpp.
{
    if (!m_dirty)
        return false;
    if (m_owns_buffers)
        evaluate_grid();
    std::memset(m_counter_buf->get_mapped_ptr(), 0, sizeof(uint32_t));
    const glm::vec3 extent = m_bounds_max - m_bounds_min;
    const McPC pc {
        .bounds_min = m_bounds_min,
        .iso_level = m_iso_level,
        .step = {
            extent.x / static_cast<float>(m_res_x),
            extent.y / static_cast<float>(m_res_y),
            extent.z / static_cast<float>(m_res_z),
        },
        .res_x = m_res_x,
        .res_y = m_res_y,
        .res_z = m_res_z,
    };
    set_push_constant_data(pc);
    const uint32_t groups = (voxel_count() + 63U) / 64U;
    set_manual_dispatch(groups, 1, 1);
    return true;
}
References MayaFlux::Buffers::SDFMeshProcessor::McPC::bounds_min, evaluate_grid(), m_bounds_max, m_bounds_min, m_counter_buf, m_dirty, m_iso_level, m_owns_buffers, m_res_x, m_res_y, m_res_z, MayaFlux::Buffers::ComputeProcessor::set_manual_dispatch(), MayaFlux::Buffers::ShaderProcessor::set_push_constant_data(), and voxel_count().