MayaFlux: MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork
ModalNetwork() [1/2]
MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork (size_t num_modes, double fundamental = 220.0, Spectrum spectrum = Spectrum::HARMONIC, double base_decay = 1.0)
Create modal network with predefined spectrum.
Parameters
num_modes Number of resonant modes
fundamental Base frequency in Hz
spectrum Frequency relationship pattern
base_decay Base decay time in seconds (modes get proportional decay)
Definition at line 13 of file ModalNetwork.cpp.
    : m_spectrum(spectrum)
    , m_fundamental(fundamental)
{
    set_output_mode(OutputMode::AUDIO_SINK);
    set_topology(Topology::INDEPENDENT);
    auto ratios = generate_spectrum_ratios(spectrum, num_modes);
    initialize_modes(ratios, base_decay);
}
References MayaFlux::Nodes::Network::NodeNetwork::AUDIO_SINK, generate_spectrum_ratios(), MayaFlux::Nodes::Network::NodeNetwork::INDEPENDENT, initialize_modes(), MayaFlux::Nodes::Network::NodeNetwork::set_output_mode(), and MayaFlux::Nodes::Network::NodeNetwork::set_topology().