MayaFlux: MayaFlux::Portal::Graphics::ComputePress::shutdown
shutdown()
void MayaFlux::Portal::Graphics::ComputePress::shutdown ()
Definition at line 36 of file ComputePress.cpp.
{
    if (!s_initialized) {
        return;
    }
    if (!m_shader_foundry || !m_shader_foundry->is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Cannot shutdown ComputePress: ShaderFoundry not initialized");
        return;
    }
    auto device = m_shader_foundry->get_device();
    if (!device) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Cannot shutdown ComputePress: Vulkan device is null");
        return;
    }
    for (auto& [id, state] : m_pipelines) {
        if (state.pipeline) {
            state.pipeline->cleanup(device);
        }
        if (state.layout && device) {
            device.destroyPipelineLayout(state.layout);
        }
    }
    if (m_descriptor_manager && device) {
        m_descriptor_manager->cleanup(device);
        m_descriptor_manager = nullptr;
    }
    m_pipelines.clear();
    s_initialized = false;
    MF_INFO(Journal::Component::Portal, Journal::Context::GPUCompute,
        "ComputePress shutdown complete");
}
References MayaFlux::Portal::Graphics::ShaderFoundry::get_device(), MayaFlux::Journal::GPUCompute, MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized(), m_descriptor_manager, m_pipelines, m_shader_foundry, MF_ERROR, MF_INFO, MayaFlux::Journal::Portal, and s_initialized.
Referenced by MayaFlux::Portal::Graphics::shutdown().