MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::compute_delay_length
compute_delay_length()
void MayaFlux::Nodes::Network::WaveguideNetwork::compute_delay_length () private
Definition at line 63 of file WaveguideNetwork.cpp.
{
    double total_delay = static_cast<double>(m_sample_rate) / m_fundamental;
    total_delay -= 0.5;
    m_delay_length_integer = static_cast<size_t>(total_delay);
    m_delay_length_fraction = total_delay - static_cast<double>(m_delay_length_integer);
    m_pickup_sample = m_delay_length_integer / 2;
}
References m_delay_length_fraction, m_delay_length_integer, m_fundamental, m_pickup_sample, and MayaFlux::Nodes::Network::NodeNetwork::m_sample_rate.
Referenced by initialize(), set_fundamental(), and WaveguideNetwork().