MayaFlux: MayaFlux::Nodes::Node::get_gpu_data_buffer
get_gpu_data_buffer()
std::span< const float > MayaFlux::Nodes::Node::get_gpu_data_buffer () const
Provides access to the GPU data buffer.
Returns
Span of floats representing the GPU data buffer This method returns a span of floats that represents the GPU data buffer associated with this node. The buffer contains data that can be uploaded to the GPU for processing, enabling efficient execution in GPU-accelerated pipelines.
Definition at line 78 of file Node.cpp.
{
    return { m_gpu_data_buffer.data(), m_gpu_data_buffer.size() };
}
References m_gpu_data_buffer.
Referenced by MayaFlux::Nodes::Filters::Filter::create_context(), MayaFlux::Nodes::Generator::Generator::create_context(), MayaFlux::Nodes::Generator::Logic::create_context(), MayaFlux::Nodes::Generator::Polynomial::create_context(), MayaFlux::Nodes::Generator::Stochastics::Random::create_context(), and MayaFlux::Nodes::BinaryOpNode::create_context().