MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::has_gpu
has_gpu()
bool MayaFlux::Buffers::BufferTokenDistributor::has_gpu (ProcessingToken token) static private
Definition at line 76 of file BufferTokenDistributor.cpp.
{
    return token & ProcessingToken::GPU_PROCESS;
}
References MayaFlux::Buffers::GPU_PROCESS.
Referenced by can_transfer(), decide_audio_buffer(), decide_transfer(), decide_vk_buffer(), is_valid_audio_token(), and is_valid_vk_token().