MayaFlux: MayaFlux::Core::BackendResourceManager::flush_deferred_commands
flush_deferred_commands()
vk::Semaphore MayaFlux::Core::BackendResourceManager::flush_deferred_commands ()
Flush deferred commands and return a semaphore that signals when they are complete.
Returns
Semaphore that will be signaled when deferred commands are finished
Definition at line 1068 of file BackendResoureManager.cpp.
{
    if (!m_command_manager.has_deferred_commands())
        return nullptr;
    vk::CommandBuffer cmd = m_command_manager.get_deferred_cmd();
    cmd.end();
    if (!m_deferred_semaphore) {
        vk::SemaphoreCreateInfo sem_info {};
        m_deferred_semaphore = m_context.get_device().createSemaphore(sem_info);
    }
    vk::SubmitInfo submit {};
    submit.commandBufferCount = 1;
    submit.pCommandBuffers = &cmd;
    submit.signalSemaphoreCount = 1;
    submit.pSignalSemaphores = &m_deferred_semaphore;
    if (m_context.get_graphics_queue().submit(1, &submit, nullptr) != vk::Result::eSuccess) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to submit deferred command buffer");
    }
    m_command_manager.reset_deferred();
    return m_deferred_semaphore;
}
References cmd, MayaFlux::Journal::Core, MayaFlux::Core::VKCommandManager::get_deferred_cmd(), MayaFlux::Core::VKContext::get_device(), MayaFlux::Core::VKContext::get_graphics_queue(), MayaFlux::Journal::GraphicsBackend, MayaFlux::Core::VKCommandManager::has_deferred_commands(), m_command_manager, m_context, m_deferred_semaphore, MF_ERROR, and MayaFlux::Core::VKCommandManager::reset_deferred().