MayaFlux: MayaFlux::IO::VideoFileWriter::open
open()
bool MayaFlux::IO::VideoFileWriter::open (const std::string & filepath, uint32_t width, uint32_t height, double frame_rate, AVPixelFormat src_pixel_format, AVCodecID explicit_codec = AV_CODEC_ID_NONE)
Definition at line 213 of file VideoFileWriter.cpp.
{
    if (m_open.load(std::memory_order_acquire)) {
        set_error("open() called while already open");
        return false;
    }
    m_width = width;
    m_height = height;
    m_src_fmt = src_pixel_format;
    m_close_promise = std::promise<bool> {};
    m_closing.store(false, std::memory_order_release);
    m_worker = std::thread(&VideoFileWriter::worker_loop, this,
        filepath, width, height, frame_rate, src_pixel_format, explicit_codec);
    constexpr int k_spin_ms = 500;
    constexpr int k_sleep_us = 500;
    for (int i = 0; i < (k_spin_ms * 1000 / k_sleep_us); ++i) {
        if (m_open.load(std::memory_order_acquire))
            return true;
        std::this_thread::sleep_for(std::chrono::microseconds(k_sleep_us));
    }
    if (m_worker.joinable())
        m_worker.join();
    return false;
}
References m_close_promise, m_closing, m_height, m_open, m_src_fmt, m_width, m_worker, set_error(), width, and worker_loop().
Referenced by record().