MayaFlux: MayaFlux::Yantra::GpuDispatchCore::dispatch_core_chained
dispatch_core_chained()
GpuChannelResult MayaFlux::Yantra::GpuDispatchCore::dispatch_core_chained (const std::vector< std::vector< double > > & channels, const DataStructureInfo & structure_info, const ExecutionContext & ctx) protected
Multi-pass (chained) dispatch.
Calls dispatch_batched on GpuResourceManager and reads back once after all passes.
Parameters
channels Extracted double channels.
structure_info Dimension/modality metadata.
ctx ExecutionContext carrying pass_count and pc_updater.
Returns
GpuChannelResult containing primary float readback and aux buffers.
Definition at line 259 of file GpuDispatchCore.cpp.
{
    on_before_gpu_dispatch(channels, structure_info);
    prepare_gpu_inputs(channels, structure_info);
    for (size_t i = 0; i < m_bindings.size(); ++i) {
        const auto et = m_bindings[i].element_type;
        if (et != GpuBufferBinding::ElementType::IMAGE_STORAGE
            && et != GpuBufferBinding::ElementType::IMAGE_SAMPLED)
            m_resources.bind_descriptor(i, m_bindings[i]);
    }
    const size_t effective = m_staging_floats.empty()
        ? largest_binding_data_element_count()
        : m_staging_floats.size();
    const auto groups = calculate_dispatch_size(effective, structure_info);
    if (!ctx.execution_metadata.contains("pass_count") || !ctx.execution_metadata.contains("pc_updater")) {
        error<std::runtime_error>(Journal::Component::Yantra,
            Journal::Context::Runtime,
            std::source_location::current(),
            "GpuDispatchCore: dispatch_core_chained requires 'pass_count' and 'pc_updater' in execution_metadata");
    }
    const auto pass_count = safe_any_cast_or_throw<uint32_t>(ctx.execution_metadata.at("pass_count"));
    const auto& pc_updater = safe_any_cast_or_throw<std::function<void(uint32_t, void*)>>(ctx.execution_metadata.at("pc_updater"));
    m_resources.dispatch_batched(
        pass_count, groups, m_bindings,
        [&](uint32_t pass, std::vector<uint8_t>& pc_data) { pc_updater(pass, pc_data.data()); },
        m_gpu_config.push_constant_size,
        ctx.execution_metadata);
    GpuChannelResult result;
    result.primary = readback_primary(effective);
    readback_aux(result);
    return result;
}
References MayaFlux::Yantra::GpuResourceManager::bind_descriptor(), calculate_dispatch_size(), MayaFlux::Yantra::GpuResourceManager::dispatch_batched(), MayaFlux::Yantra::ExecutionContext::execution_metadata, MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, largest_binding_data_element_count(), m_bindings, m_gpu_config, m_resources, m_staging_floats, on_before_gpu_dispatch(), prepare_gpu_inputs(), MayaFlux::Yantra::GpuChannelResult::primary, MayaFlux::Yantra::GpuShaderConfig::push_constant_size, readback_aux(), readback_primary(), MayaFlux::Journal::Runtime, and MayaFlux::Journal::Yantra.