MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames
get_channel_frames() [1/2]
void MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames (std::span< double > output, uint32_t channel, uint64_t start_frame) const
Definition at line 260 of file DynamicSoundStream.cpp.
{
    if (channel >= get_num_channels() || output.empty()) {
        return;
    }
    uint64_t num_frames = output.size();
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        std::shared_lock lock(m_data_mutex);
        if (m_data.empty()) {
            std::ranges::fill(output, 0.0);
            return;
        }
        const auto& interleaved_data = std::get<std::vector<double>>(m_data[0]);
        uint32_t num_channels = get_num_channels();
        for (uint64_t frame = 0; frame < num_frames; ++frame) {
            uint64_t interleaved_index = (start_frame + frame) * num_channels + channel;
            if (interleaved_index < interleaved_data.size()) {
                output[frame] = interleaved_data[interleaved_index];
            } else {
                output[frame] = 0.0;
            }
        }
    } else {
        std::shared_lock lock(m_data_mutex);
        if (channel >= m_data.size()) {
            std::ranges::fill(output, 0.0);
            return;
        }
        const auto& channel_data = std::get<std::vector<double>>(m_data[channel]);
        for (uint64_t frame = 0; frame < num_frames; ++frame) {
            uint64_t data_index = start_frame + frame;
            if (data_index < channel_data.size()) {
                output[frame] = channel_data[data_index];
            } else {
                output[frame] = 0.0;
            }
        }
    }
}
References MayaFlux::Kakshya::SoundStreamContainer::channel_data(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Kakshya::SoundStreamContainer::lock(), MayaFlux::Kakshya::SoundStreamContainer::m_data, MayaFlux::Kakshya::SoundStreamContainer::m_data_mutex, MayaFlux::Kakshya::SoundStreamContainer::m_structure, and MayaFlux::Kakshya::ContainerDataStructure::organization.