MayaFlux: MayaFlux::Core::RtAudioStream::close
close()
void MayaFlux::Core::RtAudioStream::close () override virtual
Terminates the audio stream and releases all resources.
Closes the RtAudio stream, releasing all allocated resources and disconnecting from hardware endpoints.
Implements MayaFlux::Core::AudioStream.
Definition at line 331 of file RtAudioBackend.cpp.
{
    if (!m_isOpen || !m_context) {
        return;
    }
    if (is_running()) {
        stop();
    }
    try {
        if (m_context->isStreamOpen()) {
            m_context->closeStream();
            RtAudioSingleton::mark_stream_closed();
        }
        m_isOpen = false;
    } catch (const RtAudioErrorType& e) {
        m_isOpen = false;
        RtAudioSingleton::mark_stream_closed();
        error_rethrow(
            Journal::Component::Core,
            Journal::Context::AudioBackend,
            std::source_location::current(),
            "Failed to close RtAudio stream: {}",
            m_context->getErrorText());
    }
}
References MayaFlux::Journal::AudioBackend, MayaFlux::Journal::Core, is_running(), m_context, m_isOpen, MayaFlux::Core::RtAudioSingleton::mark_stream_closed(), and stop().
Referenced by ~RtAudioStream().