MayaFlux: MayaFlux::Buffers::BufferProcessingChain::process_pending_processor_operations
process_pending_processor_operations()
void MayaFlux::Buffers::BufferProcessingChain::process_pending_processor_operations () private
Process pending processor operations.
Definition at line 173 of file BufferProcessingChain.cpp.
{
    for (auto& m_pending_op : m_pending_ops) {
        if (m_pending_op.active.load(std::memory_order_acquire)) {
            auto& op = m_pending_op;
            if (op.is_addition) {
                add_processor_direct(op.processor, op.buffer);
            } else {
                remove_processor_direct(op.processor, op.buffer);
            }
            op.processor.reset();
            op.buffer.reset();
            op.active.store(false, std::memory_order_release);
            m_pending_count.fetch_sub(1, std::memory_order_relaxed);
        }
    }
}
References add_processor_direct(), m_pending_count, m_pending_ops, and remove_processor_direct().
Referenced by process(), and process_non_owning().