MayaFlux: MayaFlux::Buffers::BufferProcessingControl::remove_processor_from_token
remove_processor_from_token()
void MayaFlux::Buffers::BufferProcessingControl::remove_processor_from_token (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token, uint32_t channel = 0)
Removes a processor from a token (dispatches based on token)
Parameters
processor Processor to remove
token Processing domain
channel Channel index (optional, used for audio tokens)
Definition at line 79 of file BufferProcessingControl.cpp.
{
    if (token == ProcessingToken::AUDIO_BACKEND || token == ProcessingToken::AUDIO_PARALLEL) {
        if (channel == 0) {
            remove_audio_processor_from_token(processor, token);
        } else {
            remove_audio_processor_from_channel(processor, token, channel);
        }
    } else if (token == ProcessingToken::GRAPHICS_BACKEND) {
        remove_graphics_processor(processor, token);
    }
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::AUDIO_PARALLEL, channel, MayaFlux::Buffers::GRAPHICS_BACKEND, remove_audio_processor_from_channel(), remove_audio_processor_from_token(), and remove_graphics_processor().