MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::shutdown
shutdown()
void MayaFlux::Portal::Graphics::ShaderFoundry::shutdown ()
Shutdown and cleanup all ShaderFoundry resources.
Destroys sync objects, descriptor resources, and shader modules. Must be called AFTER stop() and AFTER pipeline consumers (RenderFlow/ComputePress) shutdown.
Definition at line 73 of file ShaderFoundry.cpp.
{
    if (!s_initialized) {
        return;
    }
    if (!m_backend) {
        return;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "Shutting down ShaderFoundry...");
    if (!m_command_buffers.empty()) {
        MF_WARN(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "{} command buffers still exist during shutdown - freeing now",
            m_command_buffers.size());
        free_all_command_buffers();
    }
    cleanup_sync_objects();
    cleanup_descriptor_resources();
    cleanup_shader_modules();
    m_backend = nullptr;
    s_initialized = false;
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "ShaderFoundry shutdown complete");
}
References cleanup_descriptor_resources(), cleanup_shader_modules(), cleanup_sync_objects(), free_all_command_buffers(), m_backend, m_command_buffers, MF_INFO, MF_WARN, MayaFlux::Journal::Portal, s_initialized, and MayaFlux::Journal::ShaderCompilation.
Referenced by MayaFlux::Portal::Graphics::shutdown().