MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::commit_frame
commit_frame()
void MayaFlux::Kakshya::VideoStreamContainer::commit_frame (uint64_t frame_index)
Publish a decoded frame.
Sets validity, pushes to ready queue, notifies any thread blocked in get_frame_pixels().
Parameters
frame_index Absolute frame index just written.
Definition at line 136 of file VideoStreamContainer.cpp.
{
    if (m_ring_capacity == 0)
        return;
    m_slot_frame[slot_for(frame_index)].store(frame_index, std::memory_order_release);
    (void)m_ready_queue.push(frame_index);
    advance_cache_head(frame_index);
}
References advance_cache_head(), m_ready_queue, m_ring_capacity, m_slot_frame, and slot_for().
Referenced by MayaFlux::IO::VideoFileReader::decode_batch().