MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_active_audio_tokens
get_active_audio_tokens()
std::vector< ProcessingToken > MayaFlux::Buffers::TokenUnitManager::get_active_audio_tokens () const
Gets all active audio processing tokens.
Returns
Vector of tokens that have audio units
Definition at line 119 of file TokenUnitManager.cpp.
{
    std::vector<ProcessingToken> tokens;
    for (const auto& [token, unit] : m_audio_units) {
        if (!unit.root_buffers.empty()) {
            tokens.push_back(token);
        }
    }
    return tokens;
}
References m_audio_units.
Referenced by MayaFlux::Buffers::BufferProcessingControl::add_audio_processor(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor(), and MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers().