MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::get_or_create_sampler
get_or_create_sampler()
vk::Sampler MayaFlux::Portal::Graphics::TextureLoom::get_or_create_sampler (const SamplerConfig & config)
Get or create a sampler with the given configuration.
Parameters
config Sampler configuration
Returns
Vulkan sampler handle (cached)
Samplers are cached - identical configs return same sampler. Managed by TextureLoom, destroyed on shutdown.
Definition at line 359 of file TextureLoom.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "TextureLoom not initialized");
        return nullptr;
    }
    size_t hash = hash_sampler_config(config);
    auto it = m_sampler_cache.find(hash);
    if (it != m_sampler_cache.end()) {
        return it->second;
    }
    vk::Sampler sampler = create_sampler(config);
    m_sampler_cache[hash] = sampler;
    return sampler;
}
References create_sampler(), hash_sampler_config(), MayaFlux::Journal::ImageProcessing, is_initialized(), m_sampler_cache, MF_ERROR, and MayaFlux::Journal::Portal.
Referenced by get_default_sampler(), and get_nearest_sampler().