MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::compute_frame
compute_frame()
void MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::compute_frame () override virtual
Compute frame - generates vertex data from points and connections.
Implements MayaFlux::Nodes::GpuSync::GpuSync.
Definition at line 269 of file TopologyGeneratorNode.cpp.
{
    if (!m_vertex_data_dirty) {
        return;
    }
    build_vertex_buffer();
#ifdef MAYAFLUX_PLATFORM_MACOS
    std::vector<LineVertex> expanded = expand_lines_to_triangles(m_vertices);
    set_vertices<LineVertex>(std::span { expanded.data(), expanded.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(expanded.size());
    set_vertex_layout(*layout);
#else
    set_vertices<LineVertex>(std::span { m_vertices.data(), m_vertices.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(m_vertices.size());
    set_vertex_layout(*layout);
#endif
}
References build_vertex_buffer(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, m_vertices, and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout().