MayaFlux: MayaFlux::Yantra::ShaderExecutionContext::collect_result
collect_result()
template<ComputeData InputType = std::vector<Kakshya::DataVariant>, ComputeData OutputType = InputType> GpuChannelResult MayaFlux::Yantra::ShaderExecutionContext< InputType, OutputType >::collect_result () inline
Collect the result of the last async dispatch.
Must be called only after ShaderFoundry::is_fence_signaled returns true for the FenceID returned by dispatch_async. Calls readback_primary and readback_aux using the element count cached by dispatch_core_async.
Returns
GpuChannelResult with primary float data and aux buffers.
Definition at line 366 of file ShaderExecutionContext.hpp.
    {
        GpuChannelResult result;
        result.primary = this->readback_primary(this->last_effective_element_count());
        this->readback_aux(result);
        return result;
    }
References MayaFlux::Yantra::GpuDispatchCore::last_effective_element_count(), MayaFlux::Yantra::GpuChannelResult::primary, MayaFlux::Yantra::GpuDispatchCore::readback_aux(), and MayaFlux::Yantra::GpuDispatchCore::readback_primary().