MayaFlux: MayaFlux::Buffers::TextureBuffer::TextureBuffer
TextureBuffer()
MayaFlux::Buffers::TextureBuffer::TextureBuffer (uint32_t width, uint32_t height, Portal::Graphics::ImageFormat format, const void * initial_pixel_data = nullptr)
Create texture buffer with dimensions.
Parameters
width Texture width in pixels
height Texture height in pixels
format Pixel format
initial_pixel_data Optional initial pixel data (nullptr = uninitialized)
The VKBuffer itself contains fullscreen quad vertices. The texture pixels are stored separately and uploaded to VKImage.
Definition at line 18 of file TextureBuffer.cpp.
    : VKBuffer(
          calculate_quad_vertex_size(),
          Usage::VERTEX,
          Kakshya::DataModality::VERTEX_POSITIONS_3D)
    , m_width(width)
    , m_height(height)
    , m_format(format)
{
    RenderConfig default_config;
    default_config.vertex_shader = "texture.vert.spv";
    default_config.fragment_shader = "texture.frag.spv";
    default_config.default_texture_binding = "texSampler";
    default_config.topology = Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP;
    set_default_render_config(default_config);
    if (initial_pixel_data) {
        size_t pixel_bytes = static_cast<size_t>(width) * height * Portal::Graphics::TextureLoom::get_bytes_per_pixel(format);
        m_pixel_data.resize(pixel_bytes);
        std::memcpy(m_pixel_data.data(), initial_pixel_data, pixel_bytes);
    }
    generate_default_quad();
    MF_INFO(Journal::Component::Buffers, Journal::Context::Init,
        "Created TextureBuffer: {}x{} ({} pixel bytes, {} vertex bytes)",
        m_width, m_height, m_pixel_data.size(), m_vertex_bytes.size());
}
References MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::RenderConfig::default_texture_binding, MayaFlux::Portal::Graphics::RenderConfig::fragment_shader, generate_default_quad(), MayaFlux::Portal::Graphics::TextureLoom::get_bytes_per_pixel(), MayaFlux::Journal::Init, m_height, m_pixel_data, m_vertex_bytes, m_width, MF_INFO, MayaFlux::Buffers::VKBuffer::set_default_render_config(), MayaFlux::Portal::Graphics::RenderConfig::topology, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, and MayaFlux::Portal::Graphics::RenderConfig::vertex_shader.