MayaFlux: MayaFlux::Registry::BackendRegistry::get_service
get_service()
template<typename Interface > Interface * MayaFlux::Registry::BackendRegistry::get_service () inline
Query for a backend service.
Template Parameters
Interface The service interface type needed
Returns
Pointer to service implementation or nullptr if unavailable
Thread-safe. Returns nullptr if service not registered - callers must always check for nullptr before use.
The returned pointer is valid as long as the backend remains alive. Do not cache pointers across backend lifetime boundaries.
Example: auto* service = registry.get_service<IBufferService>(); if (service) { auto buffer = service->create_buffer(...); } else { // Handle missing service gracefully }
Definition at line 115 of file BackendRegistry.hpp.
    {
        std::shared_lock lock(m_mutex);
        auto it = m_services.find(typeid(Interface));
        if (it != m_services.end()) {
            return static_cast<Interface*>(it->second());
        }
        return nullptr;
    }
Referenced by MayaFlux::Buffers::DescriptorBindingsProcessor::create_descriptor_buffer(), MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Portal::Graphics::TextureLoom::download_data_async(), MayaFlux::Buffers::download_device_local(), MayaFlux::Buffers::download_from_gpu(), MayaFlux::Buffers::download_host_visible(), MayaFlux::Buffers::VKBufferProcessor::ensure_initialized(), MayaFlux::Buffers::PresentProcessor::fallback_renderer(), MayaFlux::Buffers::VKBuffer::get_device_address(), MayaFlux::Portal::Graphics::RenderFlow::initialize(), MayaFlux::Buffers::BufferAccessControl::initialize_buffer_service(), MayaFlux::Buffers::VKBufferProcessor::initialize_buffer_service(), MayaFlux::Buffers::VKBufferProcessor::initialize_compute_service(), MayaFlux::Buffers::FormaBindingsProcessor::make_descriptor_buffer(), MayaFlux::Portal::Network::NetworkSink::NetworkSink(), MayaFlux::Vruta::NetworkSource::NetworkSource(), MayaFlux::Buffers::MeshProcessor::on_attach(), MayaFlux::Buffers::RenderProcessor::on_attach(), MayaFlux::Buffers::BufferDownloadProcessor::on_attach(), MayaFlux::Buffers::BufferUploadProcessor::on_attach(), MayaFlux::Buffers::NodeTextureProcessor::on_attach(), MayaFlux::Buffers::TextureProcessor::on_attach(), MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer(), MayaFlux::Buffers::VKBuffer::resize(), MayaFlux::Kakshya::CameraContainer::setup_io(), MayaFlux::Core::InputManager::setup_osc_bridge(), MayaFlux::Kakshya::VideoStreamContainer::setup_ring(), MayaFlux::Core::InputManager::start(), MayaFlux::Core::InputManager::teardown_osc_bridge(), MayaFlux::Buffers::upload_device_local(), MayaFlux::Buffers::upload_host_visible(), and MayaFlux::Vruta::NetworkSource::~NetworkSource().