MayaFlux: MayaFlux::Core::VKContext::initialize
initialize()
bool MayaFlux::Core::VKContext::initialize (const GlobalGraphicsConfig & graphics_config, bool enable_validation = true, const std::vector< const char * > & required_extensions = {})
Initialize Vulkan context.
Parameters
global_config Global graphics configuration
enable_validation Enable validation layers
required_extensions Required instance extensions
Returns
true if successful
Definition at line 14 of file VKContext.cpp.
{
    m_graphics_config = graphics_config;
    if (graphics_config.requested_api != GlobalGraphicsConfig::GraphicsApi::VULKAN) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Vulkan context initialization requested, but graphics API is not set to Vulkan!");
        return false;
    }
    std::vector<const char*> extensions;
    if (graphics_config.windowing_backend == GlobalGraphicsConfig::WindowingBackend::GLFW) {
        GLFWSingleton::configure(graphics_config.glfw_preinit_config);
        extensions = GLFWSingleton::get_required_instance_extensions();
        for (const char* ext : required_extensions) {
            if (std::ranges::find(extensions, ext) == extensions.end()) {
                extensions.push_back(ext);
            }
        }
    } else {
        extensions = required_extensions;
    }
    if (!m_instance.initialize(enable_validation, extensions)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to initialize Vulkan instance!");
        return false;
    }
    if (!m_device.initialize(m_instance.get_instance(), nullptr, m_graphics_config.backend_info)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to initialize Vulkan device!");
        cleanup();
        return false;
    }
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Vulkan context initialized successfully.");
    return true;
}
References MayaFlux::Core::GlobalGraphicsConfig::backend_info, cleanup(), MayaFlux::Core::GLFWSingleton::configure(), MayaFlux::Journal::Core, MayaFlux::Core::VKInstance::get_instance(), MayaFlux::Core::GLFWSingleton::get_required_instance_extensions(), MayaFlux::Core::GlobalGraphicsConfig::GLFW, MayaFlux::Core::GlobalGraphicsConfig::glfw_preinit_config, MayaFlux::Journal::GraphicsBackend, MayaFlux::Core::VKInstance::initialize(), MayaFlux::Core::VKDevice::initialize(), m_device, m_graphics_config, m_instance, MF_ERROR, MF_INFO, MayaFlux::Core::GlobalGraphicsConfig::requested_api, MayaFlux::Core::GlobalGraphicsConfig::VULKAN, and MayaFlux::Core::GlobalGraphicsConfig::windowing_backend.