MayaFlux: MayaFlux::Buffers::SoundFileBridge::setup_processors
setup_processors()
void MayaFlux::Buffers::SoundFileBridge::setup_processors (Buffers::ProcessingToken token) override virtual
Setup the processing chain with automatic input/output.
Configures:
Default processor: SoundStreamReader (inherited, reads from file)
Postprocessor: SoundStreamWriter (writes to stream)
User processors can be inserted into the main chain between these stages.
After calling setup_chain(), the buffer is ready for process_complete() cycles.
Reimplemented from MayaFlux::Buffers::AudioBuffer.
Definition at line 21 of file SoundFileBridge.cpp.
{
    m_capture_stream = std::make_shared<Kakshya::DynamicSoundStream>(
        s_registered_sample_rate,
        static_cast<uint32_t>(get_container()->get_structure().get_channel_count()));
    m_stream_writer = std::make_shared<SoundStreamWriter>(m_capture_stream);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
    chain->add_postprocessor(m_stream_writer, shared_from_this());
    enforce_default_processing(true);
}
References MayaFlux::Buffers::AudioBuffer::enforce_default_processing(), MayaFlux::Buffers::SoundContainerBuffer::get_container(), MayaFlux::Buffers::AudioBuffer::get_processing_chain(), m_capture_stream, m_stream_writer, MayaFlux::Buffers::s_registered_sample_rate, and MayaFlux::Buffers::AudioBuffer::set_processing_chain().