MayaFlux: MayaFlux::Core::VKContext::get_device
get_device()
vk::Device MayaFlux::Core::VKContext::get_device () const inline
Get logical device.
Definition at line 49 of file VKContext.hpp.
{ return m_device.get_device(); }
References MayaFlux::Core::VKDevice::get_device(), and m_device.
Referenced by MayaFlux::Core::VKSwapchain::acquire_next_image(), MayaFlux::Core::BackendResourceManager::cleanup(), MayaFlux::Core::WindowRenderContext::cleanup(), MayaFlux::Core::BackendResourceManager::cleanup_buffer(), MayaFlux::Core::BackendResourceManager::cleanup_image(), MayaFlux::Core::VKSwapchain::cleanup_swapchain(), MayaFlux::Core::VKSwapchain::create(), MayaFlux::Core::BackendPipelineManager::create_compute_pipeline(), MayaFlux::Core::BackendPipelineManager::create_descriptor_layout(), MayaFlux::Core::BackendPipelineManager::create_descriptor_manager(), MayaFlux::Core::BackendPipelineManager::create_graphics_pipeline(), MayaFlux::Core::VKSwapchain::create_image_views(), MayaFlux::Core::BackendResourceManager::create_sampler(), MayaFlux::Core::BackendPipelineManager::create_shader_module(), MayaFlux::Core::BackendResourceManager::destroy_sampler(), MayaFlux::Core::BackendResourceManager::download_image_data(), MayaFlux::Core::BackendResourceManager::flush_pending_buffer_operations(), MayaFlux::Core::BackendResourceManager::get_buffer_device_address(), MayaFlux::Core::BackendResourceManager::initialize_buffer(), MayaFlux::Core::BackendResourceManager::initialize_image(), MayaFlux::Core::VKSwapchain::recreate(), MayaFlux::Core::BackendResourceManager::setup_backend_service(), MayaFlux::Core::BackendWindowHandler::setup_backend_service(), MayaFlux::Core::BackendResourceManager::upload_image_data(), and MayaFlux::Core::BackendResourceManager::upload_image_data_with_staging().