MayaFlux: MayaFlux::Buffers::VKBuffer::clear
clear()
void MayaFlux::Buffers::VKBuffer::clear () override virtual
Clear buffer contents.
If the buffer is host-visible and mapped the memory is zeroed. For device-local buffers the backend must provide a ClearBufferProcessor that performs the appropriate GPU-side clear.
Implements MayaFlux::Buffers::Buffer.
Definition at line 33 of file VKBuffer.cpp.
{
    if (!is_initialized()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "Cannot clear uninitialized VKBuffer");
        return;
    }
    if (is_host_visible() && m_resources.mapped_ptr) {
        std::memset(m_resources.mapped_ptr, 0, m_size_bytes);
    } else {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "clear() on device-local buffer requires ClearBufferProcessor");
    }
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, is_host_visible(), is_initialized(), m_resources, m_size_bytes, MayaFlux::Buffers::VKBufferResources::mapped_ptr, and MF_WARN.
Referenced by set_data().