MayaFlux: MayaFlux::IO::SoundFileReader::seek_internal
seek_internal()
bool MayaFlux::IO::SoundFileReader::seek_internal (std::shared_ptr< FFmpegContext > & ctx, uint64_t frame_position) private
Internal seek implementation.
Parameters
ctx FFmpeg context.
frame_position Target frame position.
Returns
True if seek succeeded.
Definition at line 730 of file SoundFileReader.cpp.
{
    if (!ctx || !ctx->is_valid()) {
        set_error("Invalid context for seeking");
        return false;
    }
    if (frame_position > ctx->total_frames) {
        frame_position = ctx->total_frames;
    }
    if (ctx->sample_rate == 0) {
        set_error("Invalid sample rate");
        return false;
    }
    if (ctx->audio_stream_index < 0 || ctx->audio_stream_index >= static_cast<int>(ctx->format_context->nb_streams)) {
        set_error("Invalid audio stream index");
        return false;
    }
    AVStream* stream = ctx->format_context->streams[ctx->audio_stream_index];
    int64_t timestamp = av_rescale_q(
        frame_position,
        AVRational { 1, static_cast<int>(ctx->sample_rate) },
        stream->time_base);
    int ret = av_seek_frame(
        ctx->format_context,
        ctx->audio_stream_index,
        timestamp,
        AVSEEK_FLAG_BACKWARD);
    if (ret < 0) {
        set_error("Seek operation failed");
        return false;
    }
    avcodec_flush_buffers(ctx->codec_context);
    if (ctx->swr_context) {
        uint8_t** dummy = nullptr;
        int linesize = 0;
        int alloc_ret = av_samples_alloc_array_and_samples(
            &dummy, &linesize,
            ctx->channels, 2048, AV_SAMPLE_FMT_DBL, 0);
        if (alloc_ret >= 0 && dummy) {
            while (swr_convert(ctx->swr_context, dummy, 2048, nullptr, 0) > 0) {
            }
            av_freep(&dummy[0]);
            av_freep(&dummy);
        }
    }
    m_current_frame_position = frame_position;
    return true;
}
References m_current_frame_position, and set_error().
Referenced by read_frames(), and seek().