MayaFlux: MayaFlux::Yantra::GpuDispatchCore::dispatch_core
dispatch_core()
GpuChannelResult MayaFlux::Yantra::GpuDispatchCore::dispatch_core (const std::vector< std::vector< double > > & channels, const DataStructureInfo & structure_info) protected
Full single-pass dispatch.
Drives prepare_gpu_inputs, on_before_gpu_dispatch, bind_descriptor, and GpuResourceManager::dispatch.
Parameters
channels Extracted double channels from the input Datum.
structure_info Dimension/modality metadata from OperationHelper.
Returns
GpuChannelResult containing primary float readback and aux buffers.
Definition at line 229 of file GpuDispatchCore.cpp.
{
    on_before_gpu_dispatch(channels, structure_info);
    prepare_gpu_inputs(channels, structure_info);
    for (size_t i = 0; i < m_bindings.size(); ++i) {
        const auto et = m_bindings[i].element_type;
        if (et != GpuBufferBinding::ElementType::IMAGE_STORAGE
            && et != GpuBufferBinding::ElementType::IMAGE_SAMPLED)
            m_resources.bind_descriptor(i, m_bindings[i]);
    }
    const size_t effective = m_staging_floats.empty()
        ? largest_binding_data_element_count()
        : m_staging_floats.size();
    const auto groups = calculate_dispatch_size(effective, structure_info);
    m_resources.dispatch(
        groups, m_bindings,
        m_push_constants.empty() ? nullptr : m_push_constants.data(),
        m_push_constants.size());
    GpuChannelResult result;
    result.primary = readback_primary(effective);
    readback_aux(result);
    return result;
}
References MayaFlux::Yantra::GpuResourceManager::bind_descriptor(), calculate_dispatch_size(), MayaFlux::Yantra::GpuResourceManager::dispatch(), MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, largest_binding_data_element_count(), m_bindings, m_push_constants, m_resources, m_staging_floats, on_before_gpu_dispatch(), prepare_gpu_inputs(), MayaFlux::Yantra::GpuChannelResult::primary, readback_aux(), and readback_primary().