MayaFlux: MayaFlux::Buffers::BufferSupplyMixing::update_routing_states_for_cycle
update_routing_states_for_cycle()
void MayaFlux::Buffers::BufferSupplyMixing::update_routing_states_for_cycle (ProcessingToken token)
Updates routing states for all buffers undergoing transitions.
Parameters
token Processing domain to update
Should be called once per processing cycle to advance routing fade states.
Definition at line 235 of file BufferSupplyMixing.cpp.
{
    if (!m_unit_manager.has_audio_unit(token)) {
        return;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    for (uint32_t channel = 0; channel < unit.channel_count; ++channel) {
        auto root_buffer = unit.get_buffer(channel);
        for (auto& child : root_buffer->get_child_buffers()) {
            if (!child->needs_routing()) {
                continue;
            }
            auto& state = child->get_routing_state();
            if (state.phase != BufferRoutingState::ACTIVE) {
                continue;
            }
            update_routing_state(state);
            auto root_target = unit.get_buffer(state.to_channel);
            auto chain_target = unit.get_chain(state.to_channel);
            if (auto mix_proc = chain_target->get_processor<MixProcessor>(root_target)) {
                mix_proc->update_source_mix(child, state.to_amount);
            }
        }
    }
}
References MayaFlux::Buffers::BufferRoutingState::ACTIVE, MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), m_unit_manager, and update_routing_state().