MayaFlux: MayaFlux::Core::VKComputePipeline::calculate_workgroups
calculate_workgroups()
uint32_t MayaFlux::Core::VKComputePipeline::calculate_workgroups (uint32_t element_count, uint32_t workgroup_size) static private
Calculate number of workgroups needed.
Parameters
element_count Total elements to process
workgroup_size Elements per workgroup
Returns
Number of workgroups (rounded up)
Definition at line 346 of file VKComputePipeline.cpp.
{
    if (workgroup_size == 0) {
        return 0;
    }
    return (element_count + workgroup_size - 1) / workgroup_size;
}
Referenced by calculate_dispatch_1d(), calculate_dispatch_2d(), calculate_dispatch_3d(), dispatch_1d(), dispatch_2d(), and dispatch_3d().