MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::set_all_data
set_all_data() [2/2]
void MayaFlux::Kakshya::DynamicSoundStream::set_all_data (const std::vector< DataVariant > & new_data) private
Definition at line 339 of file DynamicSoundStream.cpp.
{
    std::unique_lock lock(m_data_mutex);
    m_data.resize(data.size());
    std::ranges::for_each(std::views::zip(data, m_data),
        [](auto&& pair) {
            auto&& [source, dest] = pair;
            safe_copy_data_variant(source, dest);
        });
    m_num_frames = std::visit([](const auto& vec) {
        return static_cast<uint64_t>(vec.size());
    },
        m_data[0]);
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        m_num_frames = (get_num_channels() > 0) ? m_num_frames / get_num_channels() : 0;
    }
    setup_dimensions();
    update_processing_state(ProcessingState::READY);
}
References MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Kakshya::SoundStreamContainer::lock(), MayaFlux::Kakshya::SoundStreamContainer::m_data, MayaFlux::Kakshya::SoundStreamContainer::m_data_mutex, MayaFlux::Kakshya::SoundStreamContainer::m_num_frames, MayaFlux::Kakshya::SoundStreamContainer::m_structure, MayaFlux::Kakshya::ContainerDataStructure::organization, MayaFlux::Kakshya::READY, MayaFlux::Kakshya::safe_copy_data_variant(), MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions(), and MayaFlux::Kakshya::SoundStreamContainer::update_processing_state().