MayaFlux: MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride
set_vertex_stride()
void MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride (size_t stride)
Set vertex stride (bytes per vertex)
Parameters
stride Stride in bytes
Must be called before filling buffer. Common values:
12 (vec3 positions only)
24 (vec3 positions + vec3 colors)
32 (vec3 positions + vec3 normals + vec2 texcoords)
Definition at line 129 of file GeometryWriterNode.cpp.
{
    m_vertex_stride = stride;
    m_needs_layout_update = true;
}
References m_needs_layout_update, and m_vertex_stride.
Referenced by MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointNode::PointNode(), MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode(), and MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode().