MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::reorganize_data_layout
reorganize_data_layout()
void MayaFlux::Kakshya::SoundStreamContainer::reorganize_data_layout (MemoryLayout new_layout) protected
Definition at line 747 of file SoundStreamContainer.cpp.
{
    if (new_layout == m_structure.memory_layout) {
        return;
    }
    if (m_structure.organization == OrganizationStrategy::PLANAR) {
        m_structure.memory_layout = new_layout;
        setup_dimensions();
        return;
    }
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED && (m_data.empty() || m_num_channels <= 1)) {
        m_structure.memory_layout = new_layout;
        setup_dimensions();
        return;
    }
    auto current_span = convert_variant<double>(m_data[0]);
    std::vector<double> current_data(current_span.begin(), current_span.end());
    auto channels = deinterleave_channels<double>(
        std::span<const double>(current_data.data(), current_data.size()),
        m_num_channels);
    std::vector<double> reorganized_data;
    if (new_layout == MemoryLayout::ROW_MAJOR) {
        reorganized_data = interleave_channels(channels);
    } else {
        reorganized_data.reserve(current_data.size());
        for (const auto& channel : channels) {
            reorganized_data.insert(reorganized_data.end(), channel.begin(), channel.end());
        }
    }
    m_data[0] = DataVariant(std::move(reorganized_data));
    invalidate_span_cache();
    m_double_extraction_dirty.store(true, std::memory_order_release);
    m_structure.memory_layout = new_layout;
    setup_dimensions();
}
References MayaFlux::Kakshya::interleave_channels(), MayaFlux::Kakshya::INTERLEAVED, invalidate_span_cache(), m_data, m_double_extraction_dirty, m_num_channels, m_structure, MayaFlux::Kakshya::ContainerDataStructure::memory_layout, MayaFlux::Kakshya::ContainerDataStructure::organization, MayaFlux::Kakshya::PLANAR, MayaFlux::Kakshya::ROW_MAJOR, and setup_dimensions().
Referenced by set_memory_layout().