MayaFlux: MayaFlux::Portal::Forma::Inspector::node_network
node_network()
InspectResult MayaFlux::Portal::Forma::Inspector::node_network (const std::shared_ptr< Nodes::Network::NodeNetwork > & net, Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F, int depth = 0)
Inspect a NodeNetwork and its per-network metadata.
Builds a collapsible ValueGroup whose header is the network's topology and output mode, with body rows for node count and enabled state. Intended to be nested inside node_graph_manager() but callable independently when the caller already holds a network reference.
Definition at line 205 of file NodeQuery.cpp.
{
    const float ind = x_min + static_cast<float>(depth) * k_inspect_indent;
    const std::string header_label
        = std::string(Reflect::enum_to_string(net->get_topology()))
        + " / "
        + std::string(Reflect::enum_to_string(net->get_output_mode()));
    auto net_ref = net;
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "nodes",
            .reader = [net_ref] { return std::to_string(net_ref->get_node_count()); },
        },
        ValueSpec {
            .label = "enabled",
            .reader = [net_ref] { return net_ref->is_enabled() ? "true" : "false"; },
        },
        ValueSpec {
            .label = "channels",
            .reader = [net_ref] {
                const auto ch = net_ref->get_registered_channels();
                std::string s;
                for (size_t i = 0; i < ch.size(); ++i) {
                    if (i)
                        s += ',';
                    s += std::to_string(ch[i]);
                }
                return s.empty() ? "-" : s;
            },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), ind, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), header_label, dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(values.size());
    for (const auto& spec : values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto group = make_value_group(values, std::move(hbuf), rbufs,
        surface, cursor, ind, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    return result;
}
References MayaFlux::Reflect::enum_to_string(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::k_inspect_indent, MayaFlux::Portal::Forma::ValueSpec::label, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::row_pixel_dims(), and MayaFlux::Portal::Forma::Surface::window().
Referenced by node_graph_manager().