MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::regenerate_topology
regenerate_topology()
void MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::regenerate_topology ()
Manually trigger connection regeneration.
Call this if auto_connect is false and you've made multiple changes.
Definition at line 139 of file TopologyGeneratorNode.cpp.
{
    m_connections.clear();
    if (m_points.empty()) {
        m_vertex_data_dirty = true;
        return;
    }
    Eigen::MatrixXd positions = points_to_eigen();
    Kinesis::ProximityConfig config;
    config.mode = m_mode;
    config.k_neighbors = m_k_neighbors;
    config.radius = m_connection_radius;
    config.custom_function = m_custom_func;
    m_connections = Kinesis::generate_proximity_graph(positions, config);
    m_vertex_data_dirty = true;
}
References MayaFlux::Kinesis::ProximityConfig::custom_function, MayaFlux::Kinesis::generate_proximity_graph(), MayaFlux::Kinesis::ProximityConfig::k_neighbors, m_connection_radius, m_connections, m_custom_func, m_k_neighbors, m_mode, m_points, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, MayaFlux::Kinesis::ProximityConfig::mode, points_to_eigen(), and MayaFlux::Kinesis::ProximityConfig::radius.
Referenced by add_point(), clear(), remove_point(), set_connection_mode(), set_connection_radius(), set_k_neighbors(), set_points(), and update_point().