MayaFlux: MayaFlux::IO::ImageReader::open
open()
bool MayaFlux::IO::ImageReader::open (const std::string & filepath, FileReadOptions options = FileReadOptions::ALL) override virtual
Open a file for reading.
Parameters
filepath Path to the file.
options Reading options (see FileReadOptions).
Returns
true if file was successfully opened.
Implements MayaFlux::IO::FileReader.
Definition at line 266 of file ImageReader.cpp.
{
    if (m_is_open) {
        close();
    }
    if (!can_read(filepath)) {
        m_last_error = "Unsupported image format: " + filepath;
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO, m_last_error);
        return false;
    }
    auto resolved = resolve_path(filepath);
    m_image_data = load(resolved, 4); // Force RGBA
    if (!m_image_data) {
        m_last_error = "Failed to load image data";
        return false;
    }
    m_filepath = filepath;
    m_is_open = true;
    MF_INFO(Journal::Component::IO, Journal::Context::FileIO,
        "Opened image: {} ({}x{}, {} channels)",
        filepath, m_image_data->width, m_image_data->height, m_image_data->channels);
    return true;
}
References can_read(), close(), MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, load(), m_filepath, m_image_data, m_is_open, m_last_error, MF_ERROR, MF_INFO, and MayaFlux::IO::FileReader::resolve_path().