MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::compile_from_spirv_asm
compile_from_spirv_asm()
std::shared_ptr< Core::VKShaderModule > MayaFlux::Portal::Graphics::ShaderFoundry::compile_from_spirv_asm (const std::string & spirv_asm, ShaderStage stage, const std::string & entry_point = "main") private
Definition at line 250 of file ShaderFoundry.cpp.
{
    auto shader = create_shader_module();
    if (!shader->create_from_spirv_asm(
            get_device(), spirv_asm, to_vulkan_stage(stage),
            entry_point, m_config.enable_reflection)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Failed to assemble generated SPIR-V");
        return nullptr;
    }
    return shader;
}
References create_shader_module(), MayaFlux::Portal::Graphics::ShaderCompilerConfig::enable_reflection, get_device(), m_config, MF_ERROR, MayaFlux::Journal::Portal, MayaFlux::Journal::ShaderCompilation, and to_vulkan_stage().
Referenced by compile().