MayaFlux: MayaFlux::Buffers::TextureBuffer::generate_default_quad
generate_default_quad()
void MayaFlux::Buffers::TextureBuffer::generate_default_quad () private
Definition at line 229 of file TextureBuffer.cpp.
{
    m_vertex_bytes.resize(base_quad.size() * sizeof(QuadVertex));
    std::memcpy(m_vertex_bytes.data(), base_quad.data(), m_vertex_bytes.size());
    Kakshya::VertexLayout vertex_layout {
        .vertex_count = 4,
        .stride_bytes = sizeof(QuadVertex),
        .attributes = {
            { .component_modality = Kakshya::DataModality::VERTEX_POSITIONS_3D,
                .offset_in_vertex = offsetof(QuadVertex, position),
                .name = "position" },
            { .component_modality = Kakshya::DataModality::TEXTURE_COORDS_2D,
                .offset_in_vertex = offsetof(QuadVertex, texcoord),
                .name = "texcoord" } }
    };
    set_vertex_layout(vertex_layout);
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "TextureBuffer: generated default fullscreen quad");
}
References MayaFlux::Buffers::base_quad, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, m_vertex_bytes, MF_DEBUG, MayaFlux::Buffers::VKBuffer::set_vertex_layout(), MayaFlux::Kakshya::TEXTURE_COORDS_2D, MayaFlux::Kakshya::VertexLayout::vertex_count, and MayaFlux::Kakshya::VERTEX_POSITIONS_3D.
Referenced by TextureBuffer(), and use_default_quad().