MayaFlux: MayaFlux::Nodes::Generator::Generator::get_last_context
get_last_context()
NodeContext & MayaFlux::Nodes::Generator::Generator::get_last_context () override virtual
Gets the last created context object.
Returns
Reference to the last GeneratorContext object
Implements MayaFlux::Nodes::Node.
Reimplemented in MayaFlux::Nodes::Generator::Logic, MayaFlux::Nodes::Generator::Polynomial, and MayaFlux::Nodes::Generator::Random.
Definition at line 49 of file Generator.cpp.
{
    if (is_gpu_compatible()) {
        return m_context_gpu;
    }
    return m_context;
}
References MayaFlux::Nodes::Node::is_gpu_compatible(), m_context, and m_context_gpu.
Referenced by MayaFlux::Nodes::Generator::Impulse::notify_tick(), MayaFlux::Nodes::Generator::Phasor::notify_tick(), and MayaFlux::Nodes::Generator::Sine::notify_tick().