MayaFlux: MayaFlux::Buffers::RenderProcessor::processing_function
processing_function()
void MayaFlux::Buffers::RenderProcessor::processing_function (std::shared_ptr< Buffer > buffer) override protected virtual
The core processing function that must be implemented by derived classes.
Parameters
buffer Buffer to process
This method is where the actual transformation logic is implemented. It should contain the algorithmic details of how the buffer's data is transformed, analyzed, or processed. The implementation can utilize any backend capabilities available to the processor, including:
Parallel Processing: Using multi-threading or GPU compute for large datasets
Data Transformations: Applying mathematical operations, filters, or effects
Feature Extraction: Analyzing data characteristics for further processing
Derived classes must override this method to provide specific processing behavior.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 135 of file RenderProcessor.cpp.
{
    auto vk_buffer = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk_buffer || !m_target_window) {
        return;
    }
    if (m_buffer_info.find(vk_buffer) == m_buffer_info.end()) {
        if (vk_buffer->has_vertex_layout()) {
            auto vertex_layout = vk_buffer->get_vertex_layout();
            if (vertex_layout.has_value()) {
                m_buffer_info[vk_buffer] = {
                    .semantic_layout = vertex_layout.value(),
                    .use_reflection = false
                };
            }
        }
    }
    if (m_needs_pipeline_rebuild) {
        initialize_pipeline(buffer);
    }
    if (m_render_pipeline_id == Portal::Graphics::INVALID_RENDER_PIPELINE) {
        return;
    }
    auto vertex_layout = vk_buffer->get_vertex_layout();
    if (!vertex_layout.has_value()) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "VKBuffer has no vertex layout set. Use buffer->set_vertex_layout()");
        return;
    }
    if (vertex_layout->vertex_count == 0) {
        MF_RT_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Vertex layout has zero vertices, skipping draw");
        return;
    }
    if (vertex_layout->attributes.empty()) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Vertex layout has no attributes");
        return;
    }
    vk_buffer->set_pipeline_window(m_render_pipeline_id, m_target_window);
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& flow = Portal::Graphics::get_render_flow();
    auto cmd_id = foundry.begin_commands(Portal::Graphics::ShaderFoundry::CommandBufferType::GRAPHICS);
    flow.begin_render_pass(cmd_id, m_target_window);
    uint32_t width = 0, height = 0;
    m_display_service->get_swapchain_extent(m_target_window, width, height);
    if (width > 0 && height > 0) {
        auto cmd = foundry.get_command_buffer(cmd_id);
        vk::Viewport viewport { 0.0F, 0.0F, static_cast<float>(width), static_cast<float>(height), 0.0F, 1.0F };
        cmd.setViewport(0, 1, &viewport);
        vk::Rect2D scissor { { 0, 0 }, { width, height } };
        cmd.setScissor(0, 1, &scissor);
    }
    flow.bind_pipeline(cmd_id, m_render_pipeline_id);
    flow.bind_vertex_buffers(cmd_id, { vk_buffer });
    flow.draw(cmd_id, vertex_layout->vertex_count);
    flow.end_render_pass(cmd_id);
    vk_buffer->set_pipeline_command(m_render_pipeline_id, cmd_id);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_render_flow(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Registry::Service::DisplayService::get_swapchain_extent, MayaFlux::Portal::Graphics::ShaderFoundry::GRAPHICS, initialize_pipeline(), MayaFlux::Portal::Graphics::INVALID_RENDER_PIPELINE, m_buffer_info, m_display_service, MayaFlux::Buffers::ShaderProcessor::m_needs_pipeline_rebuild, m_render_pipeline_id, m_target_window, MF_RT_ERROR, and MF_RT_WARN.