MayaFlux: MayaFlux::Buffers::BufferProcessingControl::add_audio_processor_to_channel
add_audio_processor_to_channel()
void MayaFlux::Buffers::BufferProcessingControl::add_audio_processor_to_channel (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token, uint32_t channel)
Adds a processor to a specific audio token and channel.
Parameters
processor Processor to add
token Processing domain
channel Channel index
Definition at line 133 of file BufferProcessingControl.cpp.
{
    auto chain = m_access_control.get_audio_processing_chain(token, channel);
    auto root_buffer = m_access_control.get_root_audio_buffer(token, channel);
    chain->add_processor(processor, root_buffer);
}
References MayaFlux::Buffers::BufferAccessControl::get_audio_processing_chain(), MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer(), and m_access_control.
Referenced by add_processor(), attach_quick_process(), and connect_node_to_audio_channel().