MayaFlux: MayaFlux::Portal::Text::GlyphAtlas::get_or_rasterize
get_or_rasterize() [1/2]
const GlyphMetrics * MayaFlux::Portal::Text::GlyphAtlas::get_or_rasterize (FT_UInt glyph_index)
Return metrics for a glyph, rasterizing it into the atlas if needed.
Parameters
glyph_index FT_UInt glyph index (from FT_Get_Char_Index).
Returns
Pointer to cached GlyphMetrics, or nullptr if rasterization fails.
Definition at line 16 of file GlyphAtlas.cpp.
{
    auto it = m_cache.find(glyph_index);
    if (it != m_cache.end()) {
        return &it->second;
    }
    if (!rasterize(glyph_index)) {
        return nullptr;
    }
    return &m_cache.at(glyph_index);
}
References m_cache, and rasterize().
Referenced by get_or_rasterize(), and MayaFlux::Portal::Text::lay_out().