MayaFlux: MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to
supply_audio_buffer_to()
bool MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to (const std::shared_ptr< AudioBuffer > & buffer, ProcessingToken token, uint32_t channel, double mix = 1.0)
Supplies an external audio buffer to a specific token and channel.
Parameters
buffer Buffer to supply
token Processing domain
channel Channel index
mix Mix level (default: 1.0)
Returns
True if the buffer was successfully supplied, false otherwise
The buffer data is added, mixed, and normalized at the end of the processing chain of the channel's root buffer, but before final processing. This is useful when one AudioBuffer needs to be supplied to multiple channels.
Definition at line 24 of file BufferSupplyMixing.cpp.
{
    if (!buffer) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Invalid buffer for supplying");
        return false;
    }
    if (buffer->get_channel_id() == channel) {
        MF_WARN(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Buffer already has the correct channel ID {}", channel);
        return false;
    }
    if (!m_unit_manager.has_audio_unit(token) || channel >= m_unit_manager.get_audio_channel_count(token)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Token/channel combination out of range for supplying (token: {}, channel: {})",
            static_cast<int>(token), channel);
        return false;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    auto root_buffer = unit.get_buffer(channel);
    auto processing_chain = unit.get_chain(channel);
    std::shared_ptr<MixProcessor> mix_processor = processing_chain->get_processor<MixProcessor>(root_buffer);
    if (!mix_processor) {
        mix_processor = std::make_shared<MixProcessor>();
        processing_chain->add_processor(mix_processor, root_buffer);
    }
    return mix_processor->register_source(buffer, mix, false);
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::TokenUnitManager::get_audio_channel_count(), MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), m_unit_manager, MF_ERROR, MF_WARN, and MayaFlux::mix().
Referenced by route_buffer_to_channel().