MayaFlux: MayaFlux::Buffers::VKBuffer::set_default_render_config
set_default_render_config()
void MayaFlux::Buffers::VKBuffer::set_default_render_config (const RenderConfig & config) inline protected
Called by derived classes to set their context-specific defaults.
Parameters
config RenderConfig with default values for this buffer type
Example (GeometryBuffer calls this in constructor): RenderConfig defaults; defaults.vertex_shader = "point.vert.spv"; defaults.fragment_shader = "point.frag.spv"; defaults.topology = PrimitiveTopology::POINT_LIST; set_default_render_config(defaults);
Definition at line 492 of file VKBuffer.hpp.
    {
        m_render_config = config;
        m_render_config_dirty = false;
    }
Referenced by MayaFlux::Buffers::NodeTextureBuffer::NodeTextureBuffer(), MayaFlux::Buffers::GeometryBuffer::setup_rendering(), MayaFlux::Buffers::NetworkGeometryBuffer::setup_rendering(), and MayaFlux::Buffers::TextureBuffer::TextureBuffer().