MayaFlux: MayaFlux::Buffers::ShaderProcessor::update_descriptors
update_descriptors()
void MayaFlux::Buffers::ShaderProcessor::update_descriptors (const std::shared_ptr< VKBuffer > & buffer) protected virtual
Definition at line 368 of file ShaderProcessor.cpp.
{
    if (m_descriptor_set_ids.empty()) {
        return;
    }
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& descriptor_bindings = buffer->get_pipeline_context().descriptor_buffer_bindings;
    std::set<std::pair<uint32_t, uint32_t>> updated_pairs;
    for (const auto& binding : descriptor_bindings) {
        auto ds_index = resolve_ds_index(binding.set);
        if (!ds_index) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Descriptor set index {} out of range or reserved", binding.set);
            continue;
        }
        foundry.update_descriptor_buffer(
            m_descriptor_set_ids[*ds_index],
            binding.binding,
            binding.type,
            binding.buffer_info.buffer,
            binding.buffer_info.offset,
            binding.buffer_info.range);
        updated_pairs.emplace(binding.set, binding.binding);
    }
    for (const auto& [descriptor_name, buf] : m_bound_buffers) {
        auto binding_it = m_config.bindings.find(descriptor_name);
        if (binding_it == m_config.bindings.end()) {
            continue;
        }
        const auto& binding = binding_it->second;
        auto key = std::make_pair(binding.set, binding.binding);
        if (updated_pairs.count(key)) {
            continue;
        }
        auto ds_index = resolve_ds_index(binding.set);
        if (!ds_index) {
            MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Invalid descriptor set index {} for binding '{}'",
                binding.set, descriptor_name);
            continue;
        }
        foundry.update_descriptor_buffer(
            m_descriptor_set_ids[*ds_index],
            binding.binding,
            binding.type,
            buf->get_buffer(),
            0,
            buf->get_size_bytes());
    }
}
References MayaFlux::Buffers::ShaderConfig::bindings, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_shader_foundry(), m_bound_buffers, m_config, m_descriptor_set_ids, MF_ERROR, MF_RT_ERROR, and resolve_ds_index().
Referenced by MayaFlux::Buffers::ComputeProcessor::initialize_descriptors(), MayaFlux::Buffers::RenderProcessor::initialize_descriptors(), and processing_function().