MayaFlux: MayaFlux::Buffers::BufferAccessControl::remove_audio_buffer
remove_audio_buffer()
void MayaFlux::Buffers::BufferAccessControl::remove_audio_buffer (const std::shared_ptr< AudioBuffer > & buffer, ProcessingToken token, uint32_t channel)
Removes an audio buffer from a token and channel.
Parameters
buffer Audio buffer to remove
token Processing domain
channel Channel index
Definition at line 176 of file BufferAccessControl.cpp.
{
    if (!m_unit_manager.has_audio_unit(token)) {
        return;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    if (channel >= unit.channel_count) {
        return;
    }
    unit.get_buffer(channel)->remove_child_buffer(buffer);
}
References MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), and m_unit_manager.
Referenced by remove_buffer().