MayaFlux: MayaFlux::Nexus::Fabric::fire
fire() [2/2]
void MayaFlux::Nexus::Fabric::fire (uint32_t id)
Fire a single object against the current snapshot without republishing.
Parameters
id Id assigned at registration.
Definition at line 185 of file Fabric.cpp.
{
    auto it = m_registrations.find(id);
    if (it == m_registrations.end()) {
        MF_WARN(Journal::Component::Nexus, Journal::Context::Runtime,
            "Fabric::fire: id {} not registered", id);
        return;
    }
    fire(it->second);
}
References fire(), m_registrations, MF_WARN, MayaFlux::Journal::Nexus, and MayaFlux::Journal::Runtime.
Referenced by MayaFlux::Nexus::Wiring::bind(), commit(), and fire().