MayaFlux: MayaFlux::Nodes::Generator::Logic::notify_tick
notify_tick()
void MayaFlux::Nodes::Generator::Logic::notify_tick (double value) override protected virtual
Notifies all registered callbacks about a new sample.
Parameters
value The newly generated sample
This method is called internally whenever a new sample is generated, creating the appropriate context and invoking all registered callbacks that should receive notification about this sample.
Implements MayaFlux::Nodes::Node.
Definition at line 497 of file Logic.cpp.
{
    update_context(value);
    bool state_changed = (value != m_last_output);
    auto& ctx = get_last_context();
    for (const auto& cb : m_all_callbacks) {
        bool should_call = false;
        switch (cb.event_type) {
        case LogicEventType::TICK:
            should_call = true;
            break;
        case LogicEventType::WHILE_TRUE:
            should_call = (bool)value;
            break;
        case LogicEventType::WHILE_FALSE:
            should_call = !value;
            break;
        case LogicEventType::CHANGE:
            should_call = state_changed;
            break;
        case LogicEventType::TRUE:
            should_call = state_changed && (bool)value;
            break;
        case LogicEventType::FALSE:
            should_call = state_changed && !value;
            break;
        case LogicEventType::CONDITIONAL:
            should_call = cb.condition && cb.condition.value()(ctx);
            break;
        }
        if (should_call) {
            cb.callback(ctx);
        }
    }
}
References MayaFlux::Nodes::Generator::CHANGE, MayaFlux::Nodes::Generator::CONDITIONAL, MayaFlux::Nodes::Generator::FALSE, get_last_context(), m_all_callbacks, MayaFlux::Nodes::Node::m_last_output, MayaFlux::Nodes::Generator::TICK, MayaFlux::Nodes::Generator::TRUE, update_context(), MayaFlux::Nodes::Generator::WHILE_FALSE, and MayaFlux::Nodes::Generator::WHILE_TRUE.
Referenced by process_multi_input(), and process_sample().