MayaFlux: MayaFlux::Vruta::TaskScheduler::find_task_by_name
find_task_by_name() [1/2]
std::vector< TaskEntry >::iterator MayaFlux::Vruta::TaskScheduler::find_task_by_name (const std::string & name) private
Find task entry by name.
Parameters
name Task name to find
Returns
Iterator to task entry or end()
Definition at line 197 of file Scheduler.cpp.
{
    return std::find_if(m_tasks.begin(), m_tasks.end(),
        [&name](const TaskEntry& entry) { return entry.name == name; });
}
References m_tasks.
Referenced by add_task(), cancel_task(), get_task(), and restart_task().