MayaFlux: MayaFlux::Nodes::Input::MIDINode::matches_filters
matches_filters()
bool MayaFlux::Nodes::Input::MIDINode::matches_filters (const Core::InputValue & value) const private
Definition at line 63 of file MIDINode.cpp.
{
    const auto& midi = value.as_midi();
    if (m_config.channel.has_value() && midi.channel() != m_config.channel.value()) {
        return false;
    }
    if (m_config.message_type.has_value() && midi.type() != m_config.message_type.value()) {
        return false;
    }
    uint8_t msg_type = midi.type();
    if (m_config.note_number.has_value() && (msg_type == 0x90 || msg_type == 0x80)) {
        if (midi.data1 != m_config.note_number.value()) {
            return false;
        }
    }
    if (m_config.cc_number.has_value() && msg_type == 0xB0) {
        if (midi.data1 != m_config.cc_number.value()) {
            return false;
        }
    }
    return true;
}
References MayaFlux::Core::InputValue::as_midi(), MayaFlux::Nodes::Input::MIDIConfig::cc_number, MayaFlux::Nodes::Input::MIDIConfig::channel, m_config, MayaFlux::Nodes::Input::MIDIConfig::message_type, MayaFlux::Nodes::Input::MIDIConfig::note_number, and MayaFlux::Core::InputValue::MIDIMessage::type().
Referenced by extract_value().