MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::decide_audio_buffer
decide_audio_buffer()
DistributionDecision MayaFlux::Buffers::BufferTokenDistributor::decide_audio_buffer (const std::shared_ptr< AudioBuffer > & audio, ProcessingToken token) static private
Definition at line 103 of file BufferTokenDistributor.cpp.
{
    if (!is_valid_audio_token(token)) {
        return DistributionDecision {
            .result = DistributionResult::REJECTED,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_BACKEND,
            .reason = "AudioBuffer requires SAMPLE_RATE token with CPU or GPU device"
        };
    }
    // Decision 1: AUDIO_PARALLEL (GPU audio) → INTERNAL_ONLY
    if (has_sample_rate(token) && has_gpu(token)) {
        audio->force_internal_usage(true);
        return DistributionDecision {
            .result = DistributionResult::INTERNAL_ONLY,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_BACKEND,
            .reason = "Audio buffer with GPU processing marked internal"
        };
    }
    // Decision 2: Normal audio (SAMPLE_RATE + CPU) → DIRECT_ROOT
    if (has_sample_rate(token) && has_cpu(token)) {
        audio->force_internal_usage(false);
        return DistributionDecision {
            .result = DistributionResult::DIRECT_ROOT,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_BACKEND,
            .reason = "Audio buffer registered to root"
        };
    }
    return DistributionDecision {
        .result = DistributionResult::REJECTED,
        .transfer_processor = nullptr,
        .transfer_direction = ProcessingToken::AUDIO_BACKEND,
        .reason = "AudioBuffer token combination not handled"
    };
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::DIRECT_ROOT, has_cpu(), has_gpu(), has_sample_rate(), MayaFlux::Buffers::INTERNAL_ONLY, is_valid_audio_token(), MayaFlux::Buffers::REJECTED, and MayaFlux::Buffers::DistributionDecision::result.
Referenced by distribute().