MayaFlux: MayaFlux::Portal::Forma::Inspector::node_graph_manager
node_graph_manager()
InspectResult MayaFlux::Portal::Forma::Inspector::node_graph_manager (Layer & layer, Context & context, const std::shared_ptr< Core::Window > & window, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F)
Inspect the full NodeGraphManager state across all active tokens.
Emits one collapsible per active Nodes::ProcessingToken. Each token expands per-channel children, each of which recursively calls node() for every node registered to that channel. Networks for the token are appended after the channel children, showing topology, output mode, node count, enabled state, and registered channels.
Definition at line 176 of file NodeQuery.cpp.
{
    const auto tokens = m_ngm.get_active_tokens();
    const std::string root_label = "NodeGraphManager ["
        + std::to_string(tokens.size()) + " token"
        + (tokens.size() == 1 ? "" : "s") + "]";
    auto& ngm = m_ngm;
    std::vector<ValueSpec> root_values {
        ValueSpec {
            .label = "tokens",
            .reader = [&ngm] { return std::to_string(ngm.get_active_tokens().size()); },
        },
    };
    auto root_group = make_value_group(
        root_label, root_values,
        layer, context, window, cursor,
        x_min, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(root_group);
    for (const auto tok : tokens) {
        const std::string tok_label = std::string(Reflect::enum_to_string(tok));
        const auto channels = m_ngm.get_all_channels(tok);
        std::vector<ValueSpec> tok_values {
            ValueSpec {
                .label = "nodes",
                .reader = [&ngm, tok] { return std::to_string(ngm.get_node_count(tok)); },
            },
            ValueSpec {
                .label = "networks",
                .reader = [&ngm, tok] { return std::to_string(ngm.get_network_count(tok)); },
            },
        };
        auto tok_group = make_value_group(
            tok_label, tok_values,
            layer, context, window, cursor,
            x_min + k_inspect_indent, x_max, row_h, false);
        InspectResult tok_result;
        tok_result.group = std::move(tok_group);
        layer.relate(result.group.header.header_id, tok_result.group.header.header_id);
        for (const auto ch : channels) {
            const std::string ch_label = "ch " + std::to_string(ch);
            const auto& nodes = m_ngm.get_nodes(tok, ch);
            std::vector<ValueSpec> ch_values {
                ValueSpec {
                    .label = "nodes",
                    .reader = [n = nodes.size()] { return std::to_string(n); },
                },
            };
            auto ch_group = make_value_group(
                ch_label, ch_values,
                layer, context, window, cursor,
                x_min + 2.F * k_inspect_indent, x_max, row_h, false);
            InspectResult ch_result;
            ch_result.group = std::move(ch_group);
            layer.relate(tok_result.group.header.header_id, ch_result.group.header.header_id);
            for (const auto& n : nodes) {
                if (!n)
                    continue;
                auto node_result = node(
                    n, layer, context, window, cursor,
                    x_min, x_max, row_h, 3);
                layer.relate(ch_result.group.header.header_id, node_result.group.header.header_id);
                ch_result.children.push_back(std::move(node_result));
            }
            for (const auto& net : m_ngm.get_networks(tok, ch)) {
                if (!net)
                    continue;
                auto net_result = node_network(
                    net, layer, context, window, cursor,
                    x_min, x_max, row_h, 2);
                layer.relate(tok_result.group.header.header_id, net_result.group.header.header_id);
                tok_result.children.push_back(std::move(net_result));
            }
            tok_result.children.push_back(std::move(ch_result));
        }
        result.children.push_back(std::move(tok_result));
    }
    return result;
}
References MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Reflect::enum_to_string(), MayaFlux::Nodes::NodeGraphManager::get_active_tokens(), MayaFlux::Nodes::NodeGraphManager::get_all_channels(), MayaFlux::Nodes::NodeGraphManager::get_networks(), MayaFlux::Nodes::NodeGraphManager::get_nodes(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::k_inspect_indent, MayaFlux::Portal::Forma::ValueSpec::label, m_ngm, MayaFlux::Portal::Forma::make_value_group(), node(), node_network(), and MayaFlux::Portal::Forma::Layer::relate().