MayaFlux: MayaFlux::Yantra::EnergyAnalyzer::compute_energy_values
compute_energy_values()
template<ComputeData InputType = std::vector<Kakshya::DataVariant>, ComputeData OutputType = Eigen::VectorXd> std::vector< double > MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::compute_energy_values (std::span< const double > data, EnergyMethod method) const inline private
Compute energy values using span (zero-copy processing)
Definition at line 564 of file EnergyAnalyzer.hpp.
    {
        namespace D = MayaFlux::Kinesis::Discrete;
        const size_t num_windows = calculate_num_windows(data.size());
        switch (method) {
        case EnergyMethod::PEAK:
            return D::peak(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::ZERO_CROSSING:
            return D::zero_crossing_rate(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::POWER:
            return D::power(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::DYNAMIC_RANGE:
            return D::dynamic_range(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::SPECTRAL:
            return D::spectral_energy(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::HARMONIC:
            return D::low_frequency_energy(data, num_windows, m_hop_size, m_window_size);
        case EnergyMethod::RMS:
        default:
            return D::rms(data, num_windows, m_hop_size, m_window_size);
        }
    }
References MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::calculate_num_windows(), MayaFlux::Kinesis::Discrete::dynamic_range(), MayaFlux::Yantra::DYNAMIC_RANGE, MayaFlux::Yantra::HARMONIC, MayaFlux::Kinesis::Discrete::low_frequency_energy(), MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::m_hop_size, MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::m_window_size, MayaFlux::Kinesis::Discrete::peak(), MayaFlux::Yantra::PEAK, MayaFlux::Kinesis::Discrete::power(), MayaFlux::Yantra::POWER, MayaFlux::Kinesis::Discrete::rms(), MayaFlux::Yantra::RMS, MayaFlux::Yantra::SPECTRAL, MayaFlux::Kinesis::Discrete::spectral_energy(), MayaFlux::Yantra::ZERO_CROSSING, and MayaFlux::Kinesis::Discrete::zero_crossing_rate().
Referenced by MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::analyze_implementation().