MayaFlux: MayaFlux::Nodes::Generator::Stochastics::Random::random_array
random_array()
std::vector< double > MayaFlux::Nodes::Generator::Stochastics::Random::random_array (double start, double end, unsigned int num_samples)
Generates an array of stochastic values within a specified range.
Parameters
start Lower bound of the range
end Upper bound of the range
num_samples Number of values to generate
Returns
Vector of values within the specified range
Generates a collection of values following the current distribution, mapped to the specified numerical range.
Definition at line 29 of file Stochastic.cpp.
{
    validate_range(start, end);
    m_current_start = start;
    m_current_end = end;
    std::vector<double> samples;
    samples.reserve(num_samples);
    for (unsigned int i = 0; i < num_samples; ++i) {
        samples.push_back(transform_sample(generate_distributed_sample(), start, end) * m_amplitude);
    }
    return samples;
}
References generate_distributed_sample(), MayaFlux::Nodes::Generator::Generator::m_amplitude, m_current_end, m_current_start, transform_sample(), and validate_range().
Referenced by process_batch().