MayaFlux: MayaFlux::Nodes::Generator::Logic::add_callback
add_callback()
void MayaFlux::Nodes::Generator::Logic::add_callback (const NodeHook & callback, LogicEventType type, const std::optional< NodeCondition > & condition = std::nullopt) inline private
Adds a callback to the list of all callbacks.
Parameters
callback The callback function to add
type The type of event to trigger the callback
condition Optional condition for conditional callbacks
Definition at line 598 of file Logic.hpp.
    {
        m_all_callbacks.emplace_back(callback, type, condition);
    }
Referenced by on_change(), on_change_to(), on_tick(), on_tick_if(), while_false(), and while_true().