MayaFlux: MayaFlux::Nodes::Filters::Filter::notify_tick
notify_tick()
void MayaFlux::Nodes::Filters::Filter::notify_tick (double value) override protected virtual
Notifies all registered callbacks with the current filter context.
Parameters
value The current output sample value
This method is called by the filter implementation when a new output value is produced. It creates a FilterContext object using create_context(), then calls all registered callbacks with that context.
For unconditional callbacks (registered with on_tick()), the callback is always called. For conditional callbacks (registered with on_tick_if()), the callback is called only if its condition returns true.
Filter implementations should call this method at appropriate points in their processing flow to trigger callbacks, typically after computing a new output value.
Implements MayaFlux::Nodes::Node.
Definition at line 250 of file Filter.cpp.
{
    m_last_context = create_context(value);
    for (auto& callback : m_callbacks) {
        callback(*m_last_context);
    }
    for (auto& [callback, condition] : m_conditional_callbacks) {
        if (condition(*m_last_context)) {
            callback(*m_last_context);
        }
    }
}
References create_context(), MayaFlux::Nodes::Node::m_callbacks, MayaFlux::Nodes::Node::m_conditional_callbacks, and MayaFlux::Nodes::Node::m_last_context.
Referenced by MayaFlux::Nodes::Filters::FIR::process_sample(), and MayaFlux::Nodes::Filters::IIR::process_sample().