MayaFlux: MayaFlux::Kakshya::WindowContainer::clear
clear()
void MayaFlux::Kakshya::WindowContainer::clear () override virtual
Clear all data in the container.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 160 of file WindowContainer.cpp.
{
    std::unique_lock lock(m_data_mutex);
    const size_t sz = m_structure.get_total_elements();
    m_processed_data.resize(1);
    m_processed_data[0] = std::vector<uint8_t>(sz, 0U);
    update_processing_state(ProcessingState::IDLE);
}
References MayaFlux::Kakshya::ContainerDataStructure::get_total_elements(), MayaFlux::Kakshya::IDLE, lock(), m_data_mutex, m_processed_data, m_structure, and update_processing_state().