MayaFlux: MayaFlux::Portal::Forma::Inspector::root_audio_buffer
root_audio_buffer() [2/2]
InspectResult MayaFlux::Portal::Forma::Inspector::root_audio_buffer (Buffers::ProcessingToken token, uint32_t channel, Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F, int depth = 0)
Inspect the root audio buffer for a specific token and channel.
Header shows channel index and token. Rows show sample count and child count. The root buffer itself is expanded via buffer(), then each child buffer is expanded via buffer() in order.
Definition at line 96 of file BufferQuery.cpp.
{
    auto root = m_bm.get_root_audio_buffer(token, channel);
    const auto children = root->get_child_buffers();
    const float ind = x_min + static_cast<float>(depth) * k_inspect_indent;
    const std::string header_label = "ch " + std::to_string(channel);
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "samples",
            .reader = [root] { return std::to_string(root->get_num_samples()); },
        },
        ValueSpec {
            .label = "children",
            .reader = [root] { return std::to_string(root->get_num_children()); },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), ind, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), header_label, dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(values.size());
    for (const auto& spec : values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto group = make_value_group(values, std::move(hbuf), rbufs,
        surface, cursor, ind, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    auto root_result = buffer(
        root, surface, cursor,
        x_min, x_max, row_h, depth + 1);
    surface.layer().relate(result.group.header.header_id, root_result.group.header.header_id);
    result.children.push_back(std::move(root_result));
    for (const auto& child : children) {
        auto child_result = buffer(
            child, surface, cursor,
            x_min, x_max, row_h, depth + 2);
        surface.layer().relate(result.group.header.header_id, child_result.group.header.header_id);
        result.children.push_back(std::move(child_result));
    }
    return result;
}
References buffer(), MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Buffers::BufferManager::get_root_audio_buffer(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::k_inspect_indent, MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Portal::Forma::Surface::layer(), m_bm, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::Layer::relate(), MayaFlux::Portal::Forma::row_pixel_dims(), and MayaFlux::Portal::Forma::Surface::window().
Referenced by buffer_manager(), and root_audio_buffer().