MayaFlux: MayaFlux::Core::RtAudioStream::~RtAudioStream
~RtAudioStream()
MayaFlux::Core::RtAudioStream::~RtAudioStream () override
Ensures proper cleanup of stream resources.
Automatically closes the stream if it's still open during destruction.
Definition at line 158 of file RtAudioBackend.cpp.
{
    if (is_running()) {
        stop();
    }
    if (is_open()) {
        close();
    }
}
References close(), is_open(), is_running(), and stop().