MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::get_span_cache
get_span_cache()
const std::vector< std::span< double > > & MayaFlux::Kakshya::SoundStreamContainer::get_span_cache () const protected
Get the cached spans for each channel, recomputing if dirty.
Definition at line 844 of file SoundStreamContainer.cpp.
{
    if (!m_span_cache_dirty.load(std::memory_order_acquire) && m_span_cache.has_value()) {
        return *m_span_cache;
    }
    std::unique_lock data_lock(m_data_mutex);
    if (!m_span_cache_dirty.load(std::memory_order_acquire) && m_span_cache.has_value()) {
        return *m_span_cache;
    }
    auto spans = m_data
        | std::views::transform([](auto& variant) {
              return convert_variant<double>(const_cast<DataVariant&>(variant));
          })
        | std::ranges::to<std::vector>();
    m_span_cache = std::move(spans);
    m_span_cache_dirty.store(false, std::memory_order_release);
    return *m_span_cache;
}
References m_data, m_data_mutex, m_span_cache, and m_span_cache_dirty.
Referenced by get_data_as_double(), get_frame(), get_region_data(), get_region_group_data(), get_segments_data(), get_value_at(), and set_value_at().