MayaFlux: MayaFlux::Core::RtAudioStream::is_open
is_open()
bool MayaFlux::Core::RtAudioStream::is_open () const override virtual
Checks if the stream is initialized and ready for activation.
Returns
True if the stream is open, false otherwise
Implements MayaFlux::Core::AudioStream.
Definition at line 365 of file RtAudioBackend.cpp.
{
    return m_isOpen && m_context->isStreamOpen();
}
References m_context, and m_isOpen.
Referenced by open(), start(), and ~RtAudioStream().