MayaFlux: MayaFlux::IO::AudioEncodeContext::open
open()
bool MayaFlux::IO::AudioEncodeContext::open (FFmpegMuxContext & mux, uint32_t sample_rate, uint32_t channels, AVCodecID codec_id)
Open the encoder and register an audio stream in the mux context.
Selects the encoder: if codec_id is AV_CODEC_ID_NONE the container's default audio codec is used (WAV → PCM_S16LE, MP4/MKV → AAC, OGG → Vorbis, FLAC → FLAC). Allocates and opens AVCodecContext, copies parameters to the new AVStream, initialises SwrContext (AV_SAMPLE_FMT_DBL → encoder native format), and allocates AVAudioFifo sized to two encoder frames.
Must be called after FFmpegMuxContext::open() and before FFmpegMuxContext::write_header().
Parameters
mux Open mux context that will own the output stream.
sample_rate PCM sample rate in Hz.
channels Number of interleaved channels.
codec_id Encoder override; AV_CODEC_ID_NONE = container default.
Returns
True on success; false sets the internal error string.
Definition at line 52 of file AudioEncodeContext.cpp.
{
    close();
    FFmpegDemuxContext::init_ffmpeg();
    if (!mux.is_open()) {
        m_last_error = "AudioEncodeContext::open called on unopened mux";
        return false;
    }
    if (codec_id == AV_CODEC_ID_NONE)
        codec_id = mux.format_context->oformat->audio_codec;
    if (codec_id == AV_CODEC_ID_NONE) {
        m_last_error = "container has no default audio codec";
        return false;
    }
    const AVCodec* codec = avcodec_find_encoder(codec_id);
    if (!codec) {
        m_last_error = std::string("avcodec_find_encoder failed for codec ")
            + avcodec_get_name(codec_id);
        return false;
    }
    codec_context = avcodec_alloc_context3(codec);
    if (!codec_context) {
        m_last_error = "avcodec_alloc_context3 failed";
        return false;
    }
    AVSampleFormat enc_fmt = AV_SAMPLE_FMT_FLTP;
    {
        const AVSampleFormat* fmts = nullptr;
        int n_fmts = 0;
        if (avcodec_get_supported_config(nullptr, codec, AV_CODEC_CONFIG_SAMPLE_FORMAT,
                0, reinterpret_cast<const void**>(&fmts), &n_fmts)
                >= 0
            && fmts && n_fmts > 0) {
            enc_fmt = fmts[0];
            for (int i = 0; i < n_fmts; ++i) {
                if (fmts[i] == AV_SAMPLE_FMT_S16) {
                    enc_fmt = AV_SAMPLE_FMT_S16;
                    break;
                }
                if (fmts[i] == AV_SAMPLE_FMT_FLTP) {
                    enc_fmt = AV_SAMPLE_FMT_FLTP;
                    break;
                }
            }
        }
    }
    uint32_t enc_rate = sample_rate;
    {
        const int* rates = nullptr;
        int n_rates = 0;
        if (avcodec_get_supported_config(nullptr, codec, AV_CODEC_CONFIG_SAMPLE_RATE,
                0, reinterpret_cast<const void**>(&rates), &n_rates)
                >= 0
            && rates && n_rates > 0) {
            bool found = false;
            for (int i = 0; i < n_rates; ++i) {
                if (static_cast<uint32_t>(rates[i]) == sample_rate) {
                    found = true;
                    break;
                }
            }
            if (!found)
                enc_rate = static_cast<uint32_t>(rates[0]);
        }
    }
    av_channel_layout_default(&codec_context->ch_layout,
        static_cast<int>(channels));
    codec_context->sample_rate = static_cast<int>(enc_rate);
    codec_context->sample_fmt = enc_fmt;
    codec_context->time_base = { .num = 1, .den = static_cast<int>(enc_rate) };
    if (mux.format_context->oformat->flags & AVFMT_GLOBALHEADER)
        codec_context->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
    if (avcodec_open2(codec_context, codec, nullptr) < 0) {
        m_last_error = "avcodec_open2 failed";
        close();
        return false;
    }
    stream = mux.add_stream();
    if (!stream) {
        m_last_error = mux.last_error();
        close();
        return false;
    }
    if (avcodec_parameters_from_context(stream->codecpar, codec_context) < 0) {
        m_last_error = "avcodec_parameters_from_context failed";
        close();
        return false;
    }
    stream->time_base = codec_context->time_base;
    m_stream_index = stream->index;
    m_sample_rate = enc_rate;
    m_channels = channels;
    if (!setup_resampler() || !setup_fifo()) {
        close();
        return false;
    }
    return true;
}
References MayaFlux::IO::FFmpegMuxContext::add_stream(), close(), codec_context, MayaFlux::IO::FFmpegMuxContext::format_context, MayaFlux::IO::FFmpegDemuxContext::init_ffmpeg(), MayaFlux::IO::FFmpegMuxContext::is_open(), MayaFlux::IO::FFmpegMuxContext::last_error(), m_channels, m_last_error, m_sample_rate, m_stream_index, setup_fifo(), setup_resampler(), and stream.
Referenced by MayaFlux::IO::SoundFileWriter::worker_loop().