MayaFlux: MayaFlux::Nexus::Fabric::id
id()
uint32_t MayaFlux::Nexus::Fabric::id () const inline
Stable id for this Fabric, assigned by Tapestry at construction.
Definition at line 77 of file Fabric.hpp.
{ return m_fabric_id; }
Referenced by add_expanse(), assign_id(), and MayaFlux::Nexus::StateEncoder::encode().