MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::apply_broadcast_parameter
apply_broadcast_parameter()
void MayaFlux::Nodes::Network::WaveguideNetwork::apply_broadcast_parameter (const std::string & param, double value) private
Definition at line 425 of file WaveguideNetwork.cpp.
{
    if (param == "frequency") {
        set_fundamental(value);
    } else if (param == "damping" || param == "loss") {
        set_loss_factor(value);
    } else if (param == "position") {
        set_pickup_position(value);
    } else if (param == "scale") {
        m_output_scale = std::max(0.0, value);
    }
}
References MayaFlux::Nodes::Network::NodeNetwork::m_output_scale, set_fundamental(), set_loss_factor(), and set_pickup_position().
Referenced by update_mapped_parameters().