MayaFlux: MayaFlux::IO::STBImageWriter::write
write()
bool MayaFlux::IO::STBImageWriter::write (const std::string & filepath, const ImageData & data, const ImageWriteOptions & options = {}) override virtual
Write image data to disk.
Parameters
filepath Destination path.
data Image data. Must satisfy ImageData::is_consistent().
options Format-specific options.
Returns
true on success. On failure call get_last_error().
Implements MayaFlux::IO::ImageWriter.
Definition at line 94 of file STBImageWriter.cpp.
{
    m_last_error.clear();
    if (!data.is_consistent()) {
        m_last_error = "ImageData variant does not match declared ImageFormat";
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO, m_last_error);
        return false;
    }
    if (data.width == 0 || data.height == 0 || data.channels == 0) {
        m_last_error = "ImageData has zero dimensions";
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO, m_last_error);
        return false;
    }
    const auto ext = extension_of(filepath);
    if (ext == "png")
        return write_png(filepath, data, options);
    if (ext == "jpg" || ext == "jpeg")
        return write_jpg(filepath, data, options);
    if (ext == "bmp")
        return write_bmp(filepath, data);
    if (ext == "tga")
        return write_tga(filepath, data);
    if (ext == "hdr")
        return write_hdr(filepath, data);
    m_last_error = "Unsupported extension: " + ext;
    MF_ERROR(Journal::Component::IO, Journal::Context::FileIO, m_last_error);
    return false;
}
References MayaFlux::IO::ImageData::channels, MayaFlux::Journal::FileIO, MayaFlux::IO::ImageData::height, MayaFlux::Journal::IO, MayaFlux::IO::ImageData::is_consistent(), m_last_error, MF_ERROR, MayaFlux::IO::ImageData::width, write_bmp(), write_hdr(), write_jpg(), write_png(), and write_tga().