MayaFlux: MayaFlux::Vruta::TaskScheduler::add_task
add_task()
void MayaFlux::Vruta::TaskScheduler::add_task (const std::shared_ptr< Routine > & routine, const std::string & name = "", bool initialize = false)
Add a routine to the scheduler based on its processing token.
Parameters
routine Routine to add (SoundRoutine, GraphicsRoutine, or ComplexRoutine)
name Optional name for the routine (for task management)
initialize Whether to initialize the routine's state immediately
The routine's processing token determines which domain it belongs to and which clock it synchronizes with. Automatically dispatches to the appropriate token-specific task list and clock synchronization.
Definition at line 23 of file Scheduler.cpp.
{
    if (!routine) {
        MF_ERROR(Journal::Component::Vruta, Journal::Context::CoroutineScheduling, "Failed to initiate routine; routine is null. Exiting add_task.");
        return;
    }
    std::string task_name = name.empty() ? auto_generate_name(routine) : name;
    ProcessingToken token = routine->get_processing_token();
    ensure_domain(token);
    if (initialize)
        initialize_routine_state(routine, token);
    if (token == ProcessingToken::CONDITIONAL) {
        routine->set_auto_resume(true);
        for (auto& op : m_conditional_pending_ops) {
            bool expected = false;
            if (op.active.compare_exchange_strong(expected, true,
                    std::memory_order_relaxed, std::memory_order_relaxed)) {
                op.is_addition = true;
                op.entry = { routine, task_name };
                m_conditional_pending_count.fetch_add(1, std::memory_order_release);
                start_conditional_thread();
                return;
            }
        }
        MF_ERROR(Journal::Component::Vruta, Journal::Context::CoroutineScheduling,
            "Conditional pending queue full, could not add task '{}'", task_name);
        return;
    }
    for (auto& op : m_pending_ops) {
        bool expected = false;
        if (op.active.compare_exchange_strong(expected, true,
                std::memory_order_acquire, std::memory_order_relaxed)) {
            op.entry = { routine, task_name };
            op.is_addition = true;
            m_pending_count.fetch_add(1, std::memory_order_relaxed);
            return;
        }
    }
    MF_ERROR(Journal::Component::Vruta, Journal::Context::CoroutineScheduling,
        "Pending task queue full, could not add task '{}'", task_name);
}
References auto_generate_name(), MayaFlux::Vruta::CONDITIONAL, MayaFlux::Journal::CoroutineScheduling, ensure_domain(), initialize(), initialize_routine_state(), m_conditional_pending_count, m_conditional_pending_ops, m_pending_count, m_pending_ops, MF_ERROR, start_conditional_thread(), and MayaFlux::Journal::Vruta.
Referenced by MayaFlux::Kriya::BufferPipeline::dispatch_branch_async(), MayaFlux::Kriya::BufferPipeline::execute_buffer_rate(), MayaFlux::Kriya::BufferPipeline::execute_for_cycles(), MayaFlux::Kriya::BufferPipeline::execute_once(), MayaFlux::Kriya::BufferPipeline::execute_scheduled(), MayaFlux::Kriya::Timer::schedule(), MayaFlux::Portal::Forma::Bridge::spawn_inbound(), MayaFlux::Portal::Forma::Bridge::spawn_sync(), MayaFlux::Kriya::EventChain::start(), MayaFlux::Portal::Forma::Bridge::write(), MayaFlux::Portal::Forma::Bridge::write(), MayaFlux::Portal::Forma::Bridge::write(), and MayaFlux::Portal::Forma::Bridge::write().