MayaFlux: MayaFlux::Nodes::Network::PhysicsOperator::apply_forces
apply_forces()
void MayaFlux::Nodes::Network::PhysicsOperator::apply_forces () private
Definition at line 388 of file PhysicsOperator.cpp.
{
    for (auto& group : m_collections) {
        for (auto& state : group.physics_state) {
            state.force = m_gravity * state.mass;
        }
    }
    if (m_has_attraction_point) {
        apply_attraction_forces();
    }
    if (m_turbulence_strength > 0.001F) {
        apply_turbulence();
    }
    if (m_spatial_interactions_enabled && m_interaction_radius > 0.0F) {
        apply_spatial_interactions();
    }
    if (!m_force_fields.empty()) {
        for (auto& group : m_collections) {
            auto& points = group.collection->get_points();
            for (size_t i = 0; i < points.size(); ++i) {
                for (const auto& field : m_force_fields) {
                    group.physics_state[i].force += field(points[i].position);
                }
            }
        }
    }
}
References apply_attraction_forces(), apply_spatial_interactions(), apply_turbulence(), m_collections, m_force_fields, m_gravity, m_has_attraction_point, m_interaction_radius, m_spatial_interactions_enabled, m_turbulence_strength, and position.
Referenced by process().