MayaFlux: MayaFlux::Buffers::DataWriteProcessor::on_attach
on_attach()
void MayaFlux::Buffers::DataWriteProcessor::on_attach (const std::shared_ptr< Buffer > &) override protected virtual
Called when this processor is attached to a buffer.
Parameters
buffer Buffer this processor is being attached to
Provides an opportunity for the processor to initialize buffer-specific state, allocate resources, or perform validation. With expanded processor capabilities, this method can also:
Analyze Buffer Characteristics: Examine data type, size, and format requirements
Select Optimal Backend: Choose the most appropriate processing backend for the buffer
Initialize Hardware Resources: Set up GPU contexts, CUDA streams, or other acceleration
Configure Processing Parameters: Adapt algorithm parameters to buffer characteristics
Establish Processing Strategy: Determine whether to use sequential or parallel execution
Validate Compatibility: Ensure the processor can handle the buffer's data type and format
Default implementation does nothing, but derived classes should override this method to leverage the full capabilities of the expanded processor architecture.
Reimplemented from MayaFlux::Buffers::BufferProcessor.
Definition at line 79 of file DataWriteProcessor.cpp.
{
    auto vk = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk) {
        error<std::invalid_argument>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "DataWriteProcessor requires a VKBuffer");
    }
    m_modality = vk->get_modality();
    m_topology = vk->get_render_config().topology;
    if (!vk->is_host_visible()) {
        m_staging = create_staging_buffer(vk->get_size_bytes());
    }
    if (is_vertex_modality(m_modality)) {
        if (m_modality == Kakshya::DataModality::VERTICES_3D) {
            vk->set_vertex_layout(Kakshya::VertexLayout::for_raw());
        } else {
            switch (m_topology) {
            case Portal::Graphics::PrimitiveTopology::LINE_LIST:
            case Portal::Graphics::PrimitiveTopology::LINE_STRIP:
                vk->set_vertex_layout(Kakshya::VertexLayout::for_lines());
                break;
            case Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST:
            case Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP:
                vk->set_vertex_layout(Kakshya::VertexLayout::for_meshes());
                break;
            default:
                vk->set_vertex_layout(Kakshya::VertexLayout::for_points());
                break;
            }
        }
    }
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "DataWriteProcessor attached (modality: {}, staging: {})",
        Kakshya::modality_to_string(m_modality),
        m_staging ? "yes" : "no");
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Kakshya::VertexLayout::for_lines(), MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Kakshya::VertexLayout::for_points(), MayaFlux::Kakshya::VertexLayout::for_raw(), is_vertex_modality(), MayaFlux::Portal::Graphics::LINE_LIST, MayaFlux::Portal::Graphics::LINE_STRIP, m_modality, m_staging, m_topology, MF_DEBUG, MayaFlux::Kakshya::modality_to_string(), MayaFlux::Portal::Graphics::TRIANGLE_LIST, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, and MayaFlux::Kakshya::VERTICES_3D.