MayaFlux: MayaFlux::Nodes::ChainNode::initialize
initialize()
void MayaFlux::Nodes::ChainNode::initialize ()
Initializes the chain node.
This method performs necessary setup for the chain node, ensuring both the source and target nodes are properly initialized and registered. It should be called before the chain is used for processing to ensure correct signal flow through the connected nodes.
Initialization is particularly important for chains to ensure that the signal path is properly established before processing begins.
Definition at line 22 of file NodeStructure.cpp.
{
    if (!m_is_initialized) {
        auto self = shared_from_this();
        if (m_Target) {
            for (auto& channel : get_active_channels(m_Target, 0)) {
                MayaFlux::register_audio_node(self, channel);
            }
        } else {
            MayaFlux::register_audio_node(self, 0);
        }
        m_is_initialized = true;
    }
    auto semantics = MayaFlux::Config::get_node_config().chain_semantics;
    switch (semantics) {
    case NodeChainSemantics::REPLACE_TARGET:
        if (m_Target) {
            for (auto& channel : get_active_channels(m_Target, 0)) {
                MayaFlux::unregister_audio_node(m_Target, channel);
            }
        }
        break;
    case NodeChainSemantics::ONLY_CHAIN:
        if (m_Source) {
            for (auto& channel : get_active_channels(m_Source, 0)) {
                MayaFlux::unregister_audio_node(m_Source, channel);
            }
        }
        if (m_Target) {
            for (auto& channel : get_active_channels(m_Target, 0)) {
                MayaFlux::unregister_audio_node(m_Target, channel);
            }
        }
        break;
    case NodeChainSemantics::PRESERVE_BOTH:
    default:
        break;
    }
}
References MayaFlux::Nodes::NodeConfig::chain_semantics, MayaFlux::Nodes::get_active_channels(), MayaFlux::Config::get_node_config(), m_is_initialized, m_Source, m_Target, MayaFlux::Nodes::ONLY_CHAIN, MayaFlux::Nodes::PRESERVE_BOTH, MayaFlux::register_audio_node(), MayaFlux::Nodes::REPLACE_TARGET, and MayaFlux::unregister_audio_node().
Referenced by process_sample().