MayaFlux: MayaFlux::Nodes::Network::ResonatorNetwork::build_resonators
build_resonators()
void MayaFlux::Nodes::Network::ResonatorNetwork::build_resonators (const std::vector< double > & frequencies, const std::vector< double > & qs) private
Initialise all resonators from a frequency/Q pair list.
Parameters
frequencies Centre frequencies in Hz
qs Q factors
Definition at line 140 of file ResonatorNetwork.cpp.
{
    m_resonators.clear();
    m_resonators.reserve(frequencies.size());
    for (size_t i = 0; i < frequencies.size(); ++i) {
        ResonatorNode r;
        r.frequency = std::clamp(frequencies[i], 1.0, m_sample_rate * 0.5 - 1.0);
        r.q = std::clamp(qs[i], 0.1, 1000.0);
        r.gain = 1.0;
        r.last_output = 0.0;
        r.index = i;
        r.filter = std::make_shared<Filters::IIR>(
            std::vector<double> { 1.0, 0.0, 0.0 },
            std::vector<double> { 0.0, 0.0, 0.0 });
        compute_biquad(r);
        m_resonators.push_back(std::move(r));
    }
}
References compute_biquad(), MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::filter, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::frequency, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::gain, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::index, MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::last_output, m_resonators, MayaFlux::Nodes::Network::NodeNetwork::m_sample_rate, and MayaFlux::Nodes::Network::ResonatorNetwork::ResonatorNode::q.
Referenced by ResonatorNetwork(), and ResonatorNetwork().