MayaFlux: MayaFlux::Kakshya::SoundFileContainer::setup
setup()
void MayaFlux::Kakshya::SoundFileContainer::setup (uint64_t num_frames, uint32_t sample_rate, uint32_t num_channels)
Setup the container with file parameters.
Parameters
num_frames Total number of frames in the file
sample_rate Sample rate of the audio
num_channels Number of audio channels
Definition at line 15 of file SoundFileContainer.cpp.
{
    std::unique_lock lock(m_data_mutex);
    m_num_frames = num_frames;
    m_sample_rate = sample_rate;
    m_num_channels = num_channels;
    setup_dimensions();
    update_processing_state(ProcessingState::IDLE);
}
References MayaFlux::Kakshya::IDLE, MayaFlux::Kakshya::SoundStreamContainer::lock(), MayaFlux::Kakshya::SoundStreamContainer::m_data_mutex, MayaFlux::Kakshya::SoundStreamContainer::m_num_channels, MayaFlux::Kakshya::SoundStreamContainer::m_num_frames, MayaFlux::Kakshya::SoundStreamContainer::m_sample_rate, MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions(), and MayaFlux::Kakshya::SoundStreamContainer::update_processing_state().