MayaFlux: MayaFlux::Buffers::BufferProcessingChain::process_non_owning
process_non_owning()
void MayaFlux::Buffers::BufferProcessingChain::process_non_owning (const std::shared_ptr< Buffer > & buffer) private
Internal processing method for non-owning buffer contexts.
Parameters
buffer Buffer to process
This method is used internally by BufferProcessingChain to process buffers that are not owned by the chain itself. It ensures that the processor's processing function is called in a thread-safe manner, managing the active processing state to prevent concurrent access issues.
Definition at line 98 of file BufferProcessingChain.cpp.
{
    if (m_pending_count.load(std::memory_order_relaxed) > 0) {
        process_pending_processor_operations();
    }
    auto it = m_buffer_processors.find(buffer);
    if (it == m_buffer_processors.end() || it->second.empty()) {
        return;
    }
    for (auto& processor : it->second) {
        bool should_process = true;
        if (m_enforcement_strategy == TokenEnforcementStrategy::OVERRIDE_SKIP) {
            auto processor_token = processor->get_processing_token();
            should_process = are_tokens_compatible(m_token_filter_mask, processor_token);
        }
        if (should_process) {
            processor->process_non_owning(buffer);
        }
    }
    if (m_enforcement_strategy == TokenEnforcementStrategy::OVERRIDE_REJECT) {
        cleanup_rejected_processors(buffer);
    }
}
References MayaFlux::Buffers::are_tokens_compatible(), cleanup_rejected_processors(), m_buffer_processors, m_enforcement_strategy, m_pending_count, m_token_filter_mask, MayaFlux::Buffers::OVERRIDE_REJECT, MayaFlux::Buffers::OVERRIDE_SKIP, and process_pending_processor_operations().