MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::has_data
has_data()
bool MayaFlux::Kakshya::VideoStreamContainer::has_data () const override virtual
Check if the container currently holds any data.
Returns
true if data is present, false otherwise
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 488 of file VideoStreamContainer.cpp.
{
    if (m_ring_capacity > 0)
        return m_total_source_frames > 0;
    std::shared_lock lock(m_data_mutex);
    if (m_data.empty())
        return false;
    return std::visit([](const auto& vec) { return !vec.empty(); }, m_data[0]);
}
References lock(), m_data, m_data_mutex, m_ring_capacity, and m_total_source_frames.
Referenced by is_ready(), is_ready_for_processing(), and mark_ready_for_processing().