MayaFlux: MayaFlux::Buffers::ShaderProcessor::execute_dispatch
execute_dispatch()
void MayaFlux::Buffers::ShaderProcessor::execute_dispatch (const std::shared_ptr< VKBuffer > & buffer) private
Definition at line 513 of file ShaderProcessor.cpp.
{
    if (m_pipeline_id == Portal::Graphics::INVALID_COMPUTE_PIPELINE || m_descriptor_set_ids.empty()) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot dispatch without pipeline and descriptors");
        return;
    }
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& compute_press = Portal::Graphics::get_compute_press();
    auto cmd_id = foundry.begin_commands(Portal::Graphics::ShaderFoundry::CommandBufferType::COMPUTE);
    m_last_command_buffer = cmd_id;
    m_last_processed_buffer = buffer;
    compute_press.bind_pipeline(cmd_id, m_pipeline_id);
    compute_press.bind_descriptor_sets(cmd_id, m_pipeline_id, m_descriptor_set_ids);
    if (!m_push_constant_data.empty()) {
        compute_press.push_constants(
            cmd_id,
            m_pipeline_id,
            m_push_constant_data.data(),
            m_push_constant_data.size());
    }
    on_before_dispatch(cmd_id, buffer);
    auto dispatch_size = calculate_dispatch_size(buffer);
    compute_press.dispatch(cmd_id, dispatch_size[0], dispatch_size[1], dispatch_size[2]);
    on_after_dispatch(cmd_id, buffer);
    foundry.buffer_barrier(
        cmd_id,
        buffer->get_buffer(),
        vk::AccessFlagBits::eShaderWrite,
        vk::AccessFlagBits::eShaderRead | vk::AccessFlagBits::eTransferRead,
        vk::PipelineStageFlagBits::eComputeShader,
        vk::PipelineStageFlagBits::eComputeShader | vk::PipelineStageFlagBits::eTransfer);
    foundry.submit_and_wait(cmd_id);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, calculate_dispatch_size(), MayaFlux::Portal::Graphics::ShaderFoundry::COMPUTE, MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, m_descriptor_set_ids, m_last_command_buffer, m_last_processed_buffer, m_pipeline_id, m_push_constant_data, MF_ERROR, on_after_dispatch(), and on_before_dispatch().
Referenced by processing_function().