MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::to_vulkan_format
to_vulkan_format()
vk::Format MayaFlux::Portal::Graphics::TextureLoom::to_vulkan_format (ImageFormat format) static
Convert Portal ImageFormat to Vulkan format.
Definition at line 606 of file TextureLoom.cpp.
{
    switch (format) {
    case ImageFormat::R8:
        return vk::Format::eR8Unorm;
    case ImageFormat::RG8:
        return vk::Format::eR8G8Unorm;
    case ImageFormat::RGB8:
        return vk::Format::eR8G8B8Unorm;
    case ImageFormat::RGBA8:
        return vk::Format::eR8G8B8A8Unorm;
    case ImageFormat::RGBA8_SRGB:
    case ImageFormat::BGRA8:
        return vk::Format::eB8G8R8A8Unorm;
    case ImageFormat::BGRA8_SRGB:
        return vk::Format::eB8G8R8A8Srgb;
        return vk::Format::eR8G8B8A8Srgb;
    case ImageFormat::R16:
        return vk::Format::eR16Unorm;
    case ImageFormat::RG16:
        return vk::Format::eR16G16Unorm;
    case ImageFormat::RGBA16:
        return vk::Format::eR16G16B16A16Unorm;
    case ImageFormat::R16F:
        return vk::Format::eR16Sfloat;
    case ImageFormat::RG16F:
        return vk::Format::eR16G16Sfloat;
    case ImageFormat::RGBA16F:
        return vk::Format::eR16G16B16A16Sfloat;
    case ImageFormat::R32F:
        return vk::Format::eR32Sfloat;
    case ImageFormat::RG32F:
        return vk::Format::eR32G32Sfloat;
    case ImageFormat::RGBA32F:
        return vk::Format::eR32G32B32A32Sfloat;
    case ImageFormat::DEPTH16:
        return vk::Format::eD16Unorm;
    case ImageFormat::DEPTH24:
        return vk::Format::eX8D24UnormPack32;
    case ImageFormat::DEPTH32F:
        return vk::Format::eD32Sfloat;
    case ImageFormat::DEPTH24_STENCIL8:
        return vk::Format::eD24UnormS8Uint;
    default:
        return vk::Format::eR8G8B8A8Unorm;
    }
}
References MayaFlux::Portal::Graphics::BGRA8, MayaFlux::Portal::Graphics::BGRA8_SRGB, MayaFlux::Portal::Graphics::DEPTH16, MayaFlux::Portal::Graphics::DEPTH24, MayaFlux::Portal::Graphics::DEPTH24_STENCIL8, MayaFlux::Portal::Graphics::DEPTH32F, MayaFlux::Portal::Graphics::R16, MayaFlux::Portal::Graphics::R16F, MayaFlux::Portal::Graphics::R32F, MayaFlux::Portal::Graphics::R8, MayaFlux::Portal::Graphics::RG16, MayaFlux::Portal::Graphics::RG16F, MayaFlux::Portal::Graphics::RG32F, MayaFlux::Portal::Graphics::RG8, MayaFlux::Portal::Graphics::RGB8, MayaFlux::Portal::Graphics::RGBA16, MayaFlux::Portal::Graphics::RGBA16F, MayaFlux::Portal::Graphics::RGBA32F, MayaFlux::Portal::Graphics::RGBA8, and MayaFlux::Portal::Graphics::RGBA8_SRGB.
Referenced by create_2d(), create_3d(), create_cubemap(), create_render_target(), and create_storage_image().