MayaFlux: MayaFlux::Buffers::BufferProcessingControl::add_processor
add_processor() [1/3]
void MayaFlux::Buffers::BufferProcessingControl::add_processor (const std::shared_ptr< BufferProcessor > & processor, const std::shared_ptr< Buffer > & buffer, ProcessingToken token = ProcessingToken::AUDIO_BACKEND)
Adds a processor to a buffer (dispatches based on buffer/token)
Parameters
processor Processor to add
buffer Target buffer
token Processing domain (optional, used for routing)
Definition at line 30 of file BufferProcessingControl.cpp.
{
    if (token == ProcessingToken::AUDIO_BACKEND || token == ProcessingToken::AUDIO_PARALLEL) {
        if (auto audio_buffer = std::dynamic_pointer_cast<AudioBuffer>(buffer)) {
            add_audio_processor(processor, audio_buffer);
        }
    } else if (token == ProcessingToken::GRAPHICS_BACKEND) {
        add_graphics_processor(processor, buffer, token);
    }
}
References add_audio_processor(), add_graphics_processor(), MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::AUDIO_PARALLEL, and MayaFlux::Buffers::GRAPHICS_BACKEND.
Referenced by attach_quick_process(), attach_quick_process(), attach_quick_process(), and attach_quick_process().