MayaFlux: MayaFlux::Kriya::BufferPipeline::execute_scheduled
execute_scheduled()
void MayaFlux::Kriya::BufferPipeline::execute_scheduled (uint64_t max_cycles = 0, uint64_t samples_per_operation = 1)
Execute pipeline with sample-accurate timing between operations.
Parameters
max_cycles Maximum number of cycles to execute (0 = infinite)
samples_per_operation Number of samples to wait between operations (default: 1)
Schedules pipeline execution with precise timing control. After each operation within a cycle, the pipeline waits for the specified number of samples before proceeding. Useful for rate-limiting operations or creating timed sequences.
Exceptions
std::runtime_error if pipeline has no scheduler
Note
Execution is asynchronous. The pipeline keeps itself alive until completion.
Definition at line 143 of file BufferPipeline.cpp.
{
    if (!m_scheduler) {
        error<std::runtime_error>(Journal::Component::Kriya,
            Journal::Context::CoroutineScheduling,
            std::source_location::current(),
            "Pipeline must have scheduler for scheduled execution");
    }
    auto self = shared_from_this();
    if (max_cycles == 0) {
        max_cycles = UINT64_MAX;
        m_continuous_execution = true;
    }
    m_max_cycles = max_cycles;
    auto routine = std::make_shared<Vruta::SoundRoutine>(
        execute_internal(max_cycles, samples_per_operation));
    m_scheduler->add_task(std::move(routine));
    m_active_self = self;
}
References MayaFlux::Vruta::TaskScheduler::add_task(), MayaFlux::Journal::CoroutineScheduling, execute_internal(), MayaFlux::Journal::Kriya, m_active_self, m_continuous_execution, m_max_cycles, and m_scheduler.
Referenced by execute_scheduled_at_rate().