MayaFlux: MayaFlux::Buffers::BufferProcessingChain::process_complete
process_complete()
void MayaFlux::Buffers::BufferProcessingChain::process_complete (const std::shared_ptr< Buffer > & buffer)
Applies preprocessors, processing chain, post processors and final processors sequentially to a buffer.
Parameters
buffer Buffer to transform
Use this when explicit control of order is not needed, and you want to ensure that all stages of the processing pipeline are applied in a strict sequence. This method guarantees that preprocessors, main processors, postprocessors, and final processors are executed one after the other, maintaining the exact order of operations as defined in the chain.
Definition at line 165 of file BufferProcessingChain.cpp.
{
    preprocess(buffer);
    process(buffer);
    postprocess(buffer);
    process_final(buffer);
}
References postprocess(), preprocess(), process(), and process_final().