MayaFlux: MayaFlux::Registry::BackendRegistry::instance
instance()
static BackendRegistry & MayaFlux::Registry::BackendRegistry::instance () inline static
Get the global registry instance.
Returns
Reference to singleton registry
Thread-safe initialization via static local variable (C++11 guarantee). Instance is never destroyed - lives for program duration.
Definition at line 61 of file BackendRegistry.hpp.
    {
        static BackendRegistry registry;
        return registry;
    }
Referenced by MayaFlux::Core::VulkanBackend::cleanup(), MayaFlux::IO::VideoFileReader::close(), MayaFlux::Buffers::DescriptorBindingsProcessor::create_descriptor_buffer(), MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Portal::Graphics::TextureLoom::download_data_async(), MayaFlux::Buffers::download_device_local(), MayaFlux::Buffers::download_from_gpu(), MayaFlux::Buffers::download_host_visible(), MayaFlux::Buffers::VKBufferProcessor::ensure_initialized(), MayaFlux::Buffers::PresentProcessor::fallback_renderer(), MayaFlux::Buffers::VKBuffer::get_device_address(), MayaFlux::Portal::Graphics::RenderFlow::initialize(), MayaFlux::Buffers::BufferAccessControl::initialize_buffer_service(), MayaFlux::Buffers::VKBufferProcessor::initialize_buffer_service(), MayaFlux::Buffers::VKBufferProcessor::initialize_compute_service(), MayaFlux::IO::IOManager::IOManager(), MayaFlux::Buffers::FormaBindingsProcessor::make_descriptor_buffer(), MayaFlux::Portal::Network::NetworkSink::NetworkSink(), MayaFlux::Vruta::NetworkSource::NetworkSource(), MayaFlux::Buffers::MeshProcessor::on_attach(), MayaFlux::Buffers::RenderProcessor::on_attach(), MayaFlux::Buffers::BufferDownloadProcessor::on_attach(), MayaFlux::Buffers::BufferUploadProcessor::on_attach(), MayaFlux::Buffers::NodeTextureProcessor::on_attach(), MayaFlux::Buffers::TextureProcessor::on_attach(), MayaFlux::Core::InputSubsystem::register_backend_service(), MayaFlux::Core::NetworkSubsystem::register_backend_service(), MayaFlux::Core::VulkanBackend::register_backend_services(), MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer(), MayaFlux::Buffers::VKBuffer::resize(), MayaFlux::Kakshya::CameraContainer::setup_io(), MayaFlux::IO::CameraReader::setup_io_service(), MayaFlux::IO::VideoFileReader::setup_io_service(), MayaFlux::Core::InputManager::setup_osc_bridge(), MayaFlux::Kakshya::VideoStreamContainer::setup_ring(), MayaFlux::Core::InputSubsystem::shutdown(), MayaFlux::Core::NetworkSubsystem::shutdown(), MayaFlux::Core::InputManager::start(), MayaFlux::Core::InputManager::teardown_osc_bridge(), MayaFlux::Buffers::upload_device_local(), MayaFlux::Buffers::upload_host_visible(), MayaFlux::IO::CameraReader::~CameraReader(), MayaFlux::IO::IOManager::~IOManager(), and MayaFlux::Vruta::NetworkSource::~NetworkSource().