MayaFlux: MayaFlux::Nodes::Network::PhysicsOperator::apply_one_to_one
apply_one_to_one()
void MayaFlux::Nodes::Network::PhysicsOperator::apply_one_to_one (std::string_view param, const std::shared_ptr< NodeNetwork > & source) override virtual
Apply ONE_TO_ONE parameter for physics-specific properties.
Supports:
"force_x/y/z": Per-particle force application
"mass": Per-particle mass
"color": Per-particle color (delegated to base)
"size": Per-particle size (delegated to base)
Reimplemented from MayaFlux::Nodes::Network::GraphicsOperator.
Definition at line 319 of file PhysicsOperator.cpp.
{
    size_t point_count = get_point_count();
    if (source->get_node_count() != point_count) {
        MF_WARN(Journal::Component::Nodes, Journal::Context::NodeProcessing,
            "ONE_TO_ONE size mismatch: {} particles vs {} source nodes",
            point_count, source->get_node_count());
        return;
    }
    if (param == "force_x" || param == "force_y" || param == "force_z") {
        apply_per_particle_force(param, source);
    } else if (param == "mass") {
        apply_per_particle_mass(source);
    } else {
        GraphicsOperator::apply_one_to_one(param, source);
    }
}
References MayaFlux::Nodes::Network::GraphicsOperator::apply_one_to_one(), apply_per_particle_force(), apply_per_particle_mass(), get_point_count(), MF_WARN, MayaFlux::Journal::NodeProcessing, and MayaFlux::Journal::Nodes.