MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::allocate_descriptor_set
allocate_descriptor_set()
DescriptorSetID MayaFlux::Portal::Graphics::ShaderFoundry::allocate_descriptor_set (vk::DescriptorSetLayout layout)
Allocate descriptor set for a pipeline.
Parameters
pipeline_id Which pipeline this is for
set_index Which descriptor set (0, 1, 2...)
Returns
Descriptor set ID
Definition at line 589 of file ShaderFoundry.cpp.
{
    DescriptorSetID id = m_next_descriptor_set_id++;
    DescriptorSetState& state = m_descriptor_sets[id];
    state.descriptor_set = m_global_descriptor_manager->allocate_set(get_device(), layout);
    return id;
}
References MayaFlux::Portal::Graphics::ShaderFoundry::DescriptorSetState::descriptor_set, get_device(), id, m_descriptor_sets, m_global_descriptor_manager, and m_next_descriptor_set_id.
Referenced by MayaFlux::Portal::Graphics::ComputePress::allocate_pipeline_descriptors(), and MayaFlux::Portal::Graphics::RenderFlow::allocate_pipeline_descriptors().