MayaFlux: MayaFlux::Core::AudioSubsystem::process_input
process_input()
int MayaFlux::Core::AudioSubsystem::process_input (double * input_buffer, unsigned int num_frames)
Processes input data from audio interface.
Parameters
input_buffer Pointer to interleaved input data
num_frames Number of frames to process
Returns
Status code (0 for success)
Handles incoming audio data from the audio interface, converting from interleaved format and routing to appropriate buffer channels for processing.
Definition at line 163 of file AudioSubsystem.cpp.
{
    m_callback_active.fetch_add(1, std::memory_order_acquire);
    if (m_handle == nullptr) {
        MF_RT_ERROR(Journal::Component::Core, Journal::Context::AudioCallback,
            "Invalid processing handle");
        m_callback_active.fetch_sub(1, std::memory_order_release);
        return 1;
    }
    if (!m_is_running.load(std::memory_order_acquire)) {
        if (input_buffer) {
            auto total_samples = static_cast<uint32_t>(num_frames * m_stream_info.input.channels);
            std::memset(input_buffer, 0, total_samples * sizeof(double));
        }
        m_callback_active.fetch_sub(1, std::memory_order_release);
        return 0;
    }
    m_handle->buffers.process_input(input_buffer, m_stream_info.input.channels, num_frames);
    m_callback_active.fetch_sub(1, std::memory_order_release);
    return 0;
}
References MayaFlux::Journal::AudioCallback, MayaFlux::Core::SubsystemProcessingHandle::buffers, MayaFlux::Core::GlobalStreamInfo::ChannelConfig::channels, MayaFlux::Journal::Core, MayaFlux::Core::GlobalStreamInfo::input, m_callback_active, m_handle, m_is_running, m_stream_info, MF_RT_ERROR, and MayaFlux::Core::BufferProcessingHandle::process_input().
Referenced by process_audio(), and register_callbacks().