MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::get_frames_typed
get_frames_typed()
void MayaFlux::Kakshya::VideoStreamContainer::get_frames_typed (std::span< uint8_t > output, uint64_t start_frame, uint64_t num_frames) const private
Definition at line 506 of file VideoStreamContainer.cpp.
{
    const size_t frame_size = get_frame_byte_size();
    const size_t required = static_cast<size_t>(num_frames) * frame_size;
    if (output.size() < required) {
        error<std::runtime_error>(
            Journal::Component::Kakshya,
            Journal::Context::Runtime,
            std::source_location::current(),
            "VideoStreamContainer::get_frames_typed: output buffer too small ({} < {})",
            output.size(), required);
    }
    for (uint64_t i = 0; i < num_frames; ++i) {
        auto frame = get_frame_typed(start_frame + i);
        std::ranges::copy(frame, output.begin() + static_cast<size_t>(i) * frame_size);
    }
}
References get_frame_byte_size(), get_frame_typed(), MayaFlux::Journal::Kakshya, and MayaFlux::Journal::Runtime.
Referenced by get_frames_impl().