MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::set_region_data
set_region_data()
void MayaFlux::Kakshya::SoundStreamContainer::set_region_data (const Region & region, const std::vector< DataVariant > & data) override virtual
Set data for a specific region.
Parameters
region The region to write data to
data The data to write
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 112 of file SoundStreamContainer.cpp.
{
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        if (m_data.empty() || data.empty())
            return;
        std::unique_lock lock(m_data_mutex);
        auto dest_span = convert_variant<double>(m_data[0]);
        auto src_span = convert_variant<double>(data[0]);
        set_or_update_region_data<double>(
            dest_span, src_span, region, m_structure.dimensions);
    } else {
        size_t channels_to_update = std::min(m_data.size(), data.size());
        std::unique_lock lock(m_data_mutex);
        for (size_t i = 0; i < channels_to_update; ++i) {
            auto dest_span = convert_variant<double>(m_data[i]);
            auto src_span = convert_variant<double>(data[i]);
            set_or_update_region_data<double>(
                dest_span, src_span, region, m_structure.dimensions);
        }
    }
    invalidate_span_cache();
    m_double_extraction_dirty.store(true, std::memory_order_release);
}
References MayaFlux::Kakshya::ContainerDataStructure::dimensions, MayaFlux::Kakshya::INTERLEAVED, invalidate_span_cache(), lock(), m_data, m_data_mutex, m_double_extraction_dirty, m_structure, and MayaFlux::Kakshya::ContainerDataStructure::organization.
Referenced by MayaFlux::Kakshya::DynamicSoundStream::write_frames().