MayaFlux: MayaFlux::Buffers::RootGraphicsBuffer::process_default
process_default()
void MayaFlux::Buffers::RootGraphicsBuffer::process_default () override virtual
Processes this root buffer using default processing.
For graphics root buffers, this:
Processes all child buffers through process_children()
Executes final processor if one is set (typically for debug/profiling)
Handles pending buffer operations
Implements MayaFlux::Buffers::Buffer.
Definition at line 328 of file RootGraphicsBuffer.cpp.
{
    if (this->has_pending_operations()) {
        this->process_pending_buffer_operations();
    }
    get_default_processor()->process(shared_from_this());
}
References MayaFlux::Buffers::VKBuffer::get_default_processor(), MayaFlux::Buffers::RootBuffer< VKBuffer >::has_pending_operations(), and MayaFlux::Buffers::RootBuffer< VKBuffer >::process_pending_buffer_operations().