MayaFlux: MayaFlux::Core::WindowManager::create_window
create_window()
std::shared_ptr< Window > MayaFlux::Core::WindowManager::create_window (const WindowCreateInfo & create_info)
Creates a new window.
Parameters
create_info Window creation parameters
Returns
Pointer to created window (owned by manager)
Definition at line 29 of file WindowManager.cpp.
{
    if (m_window_lookup.count(create_info.title) > 0) {
        MF_WARN(Journal::Component::Core, Journal::Context::WindowingSubsystem,
            "Window with title '{}' already exists", create_info.title);
        return nullptr;
    }
    MF_INFO(Journal::Component::Core, Journal::Context::WindowingSubsystem,
        "Creating window '{}' ({}x{}), for platform {}", create_info.title, create_info.width, create_info.height, GLFWSingleton::get_platform());
    auto window = create_window_internal(create_info);
    if (!window) {
        return nullptr;
    }
    m_windows.push_back(window);
    m_window_lookup[create_info.title] = window;
    if (window->get_create_info().register_for_processing) {
        m_processing_windows.push_back(window);
    }
    MF_INFO(Journal::Component::Core, Journal::Context::WindowingSubsystem,
        "Created window '{}' - total: {}", create_info.title, m_windows.size());
    return window;
}
References MayaFlux::Journal::Core, create_window_internal(), MayaFlux::Core::GLFWSingleton::get_platform(), MayaFlux::Core::WindowCreateInfo::height, m_processing_windows, m_window_lookup, m_windows, MF_INFO, MF_WARN, MayaFlux::Core::WindowCreateInfo::title, MayaFlux::Core::WindowCreateInfo::width, and MayaFlux::Journal::WindowingSubsystem.
Referenced by MayaFlux::create_window().