MayaFlux: MayaFlux::Nodes::Filters::FIR::process_sample
process_sample()
double MayaFlux::Nodes::Filters::FIR::process_sample (double input = 0.) override virtual
Processes a single sample through the FIR filter.
Parameters
input The input sample
Returns
The filtered output sample
Implements the FIR filtering algorithm, computing the weighted sum of the current input and previous inputs according to the filter coefficients. This is the core processing method called for each sample.
Implements MayaFlux::Nodes::Filters::Filter.
Definition at line 20 of file FIR.cpp.
{
    if (is_bypass_enabled()) {
        return input;
    }
    double processed_input = input;
    if (m_input_node) {
        atomic_inc_modulator_count(m_input_node->m_modulator_count, 1);
        uint32_t state = m_input_node->m_state.load();
        if (state & NodeState::PROCESSED) {
            processed_input += m_input_node->get_last_output();
        } else {
            processed_input += m_input_node->process_sample(input);
            atomic_add_flag(m_input_node->m_state, NodeState::PROCESSED);
        }
    }
    if (m_use_external_input_context) {
        build_input_history(processed_input);
    } else {
        update_inputs(processed_input);
    }
    double output = 0.0;
    const size_t num_taps = std::min(m_coef_b.size(), m_input_history.size());
    for (size_t i = 0; i < num_taps; ++i) {
        output += m_coef_b[i] * m_input_history[i];
    }
    update_outputs(output);
    if ((!m_state_saved || (m_state_saved && m_fire_events_during_snapshot))
        && !m_networked_node) {
        notify_tick(output);
    }
    if (m_input_node) {
        atomic_dec_modulator_count(m_input_node->m_modulator_count, 1);
        try_reset_processed_state(m_input_node);
    }
    return output * get_gain();
}
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), MayaFlux::Nodes::Filters::Filter::build_input_history(), MayaFlux::Nodes::Filters::Filter::get_gain(), MayaFlux::Nodes::Filters::Filter::is_bypass_enabled(), MayaFlux::Nodes::Filters::Filter::m_coef_b, MayaFlux::Nodes::Node::m_fire_events_during_snapshot, MayaFlux::Nodes::Filters::Filter::m_input_history, MayaFlux::Nodes::Filters::Filter::m_input_node, MayaFlux::Nodes::Node::m_networked_node, MayaFlux::Nodes::Node::m_state_saved, MayaFlux::Nodes::Filters::Filter::m_use_external_input_context, MayaFlux::Nodes::Filters::Filter::notify_tick(), MayaFlux::Nodes::PROCESSED, MayaFlux::Nodes::try_reset_processed_state(), MayaFlux::Nodes::Filters::Filter::update_inputs(), and MayaFlux::Nodes::Filters::Filter::update_outputs().