MayaFlux: MayaFlux::Core::BackendPipelineManager::create_compute_pipeline
create_compute_pipeline()
std::shared_ptr< VKComputePipeline > MayaFlux::Core::BackendPipelineManager::create_compute_pipeline (const std::shared_ptr< VKShaderModule > & shader, const std::vector< vk::DescriptorSetLayout > & layouts, uint32_t push_constant_size)
Create a compute pipeline.
Parameters
shader Shader module to use for the compute pipeline
layouts Vector of descriptor set layouts used by the pipeline
push_constant_size Size of push constant range in bytes
Returns
Shared pointer to the created VKComputePipeline
Definition at line 81 of file BackendPipelineManager.cpp.
{
    auto pipeline = std::make_shared<VKComputePipeline>();
    ComputePipelineConfig config;
    config.shader = shader;
    config.set_layouts = layouts;
    if (push_constant_size > 0) {
        config.add_push_constant(vk::ShaderStageFlagBits::eCompute, push_constant_size);
    }
    pipeline->create(m_context.get_device(), config);
    track_compute_pipeline(pipeline);
    return pipeline;
}
References MayaFlux::Core::ComputePipelineConfig::add_push_constant(), MayaFlux::Core::VKContext::get_device(), m_context, MayaFlux::Core::ComputePipelineConfig::set_layouts, MayaFlux::Core::ComputePipelineConfig::shader, and track_compute_pipeline().
Referenced by setup_backend_service().