MayaFlux: MayaFlux::Core::MIDIBackend::initialize
initialize()
bool MayaFlux::Core::MIDIBackend::initialize () override virtual
Initialize the input backend.
Returns
true if initialization succeeded
Should discover available devices but not start polling/listening.
Implements MayaFlux::Core::IInputBackend.
Definition at line 25 of file MIDIBackend.cpp.
{
    if (m_initialized.load()) {
        MF_WARN(Journal::Component::Core, Journal::Context::InputBackend,
            "MIDIBackend already initialized");
        return true;
    }
    try {
        MF_INFO(Journal::Component::Core, Journal::Context::InputBackend,
            "Initializing MIDI Backend (RtMidi version: {})", get_version());
        m_initialized.store(true);
        refresh_devices();
        create_virtual_port_if_enabled();
        MF_INFO(Journal::Component::Core, Journal::Context::InputBackend,
            "MIDIBackend initialized with {} port(s)", m_enumerated_devices.size());
        return true;
    } catch (const RtMidiError& error) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputBackend,
            "RtMidi error during initialization: {}", error.getMessage());
        return false;
    }
}
References MayaFlux::Journal::Core, create_virtual_port_if_enabled(), get_version(), MayaFlux::Journal::InputBackend, m_enumerated_devices, m_initialized, MF_ERROR, MF_INFO, MF_WARN, and refresh_devices().