MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideNetwork
WaveguideNetwork()
MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideNetwork (WaveguideType type, double fundamental_freq, double sample_rate = 48000.0)
Create waveguide network with specified type and frequency.
Parameters
type Physical structure to model
fundamental_freq Fundamental frequency in Hz
sample_rate Sample rate in Hz
Definition at line 13 of file WaveguideNetwork.cpp.
    : m_type(type)
    , m_fundamental(fundamental_freq)
{
    m_sample_rate = static_cast<uint32_t>(sample_rate);
    set_output_mode(OutputMode::AUDIO_SINK);
    set_topology(Topology::RING);
    compute_delay_length();
    const auto prop_mode = (m_type == WaveguideType::TUBE)
        ? WaveguideSegment::PropagationMode::BIDIRECTIONAL
        : WaveguideSegment::PropagationMode::UNIDIRECTIONAL;
    m_segments.emplace_back(m_delay_length_integer + 2, prop_mode);
    create_default_loop_filter();
}
References MayaFlux::Nodes::Network::AUDIO_SINK, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::BIDIRECTIONAL, compute_delay_length(), create_default_loop_filter(), m_delay_length_integer, MayaFlux::Nodes::Network::NodeNetwork::m_sample_rate, m_segments, m_type, MayaFlux::Nodes::Network::RING, MayaFlux::Nodes::Network::NodeNetwork::set_output_mode(), MayaFlux::Nodes::Network::NodeNetwork::set_topology(), TUBE, and MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::UNIDIRECTIONAL.