MayaFlux: MayaFlux::Portal::Graphics::RenderFlow::initialize
initialize()
bool MayaFlux::Portal::Graphics::RenderFlow::initialize ()
Definition at line 47 of file RenderFlow.cpp.
{
    if (s_initialized) {
        MF_WARN(Journal::Component::Portal, Journal::Context::Rendering,
            "RenderFlow already initialized (static flag)");
        return true;
    }
    if (m_shader_foundry) {
        MF_WARN(Journal::Component::Portal, Journal::Context::Rendering,
            "RenderFlow already initialized");
        return true;
    }
    m_shader_foundry = &ShaderFoundry::instance();
    if (!m_shader_foundry->is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "ShaderFoundry must be initialized before RenderFlow");
        return false;
    }
    m_display_service = Registry::BackendRegistry::instance()
                            .get_service<Registry::Service::DisplayService>();
    if (!m_display_service) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "DisplayService not found in BackendRegistry");
        return false;
    }
    s_initialized = true;
    MF_INFO(Journal::Component::Portal, Journal::Context::Rendering,
        "RenderFlow initialized");
    return true;
}
References MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Portal::Graphics::ShaderFoundry::instance(), MayaFlux::Registry::BackendRegistry::instance(), MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized(), m_display_service, m_shader_foundry, MF_ERROR, MF_INFO, MF_WARN, MayaFlux::Journal::Portal, MayaFlux::Journal::Rendering, and s_initialized.