MayaFlux: MayaFlux::Nodes::ModalNetwork::process_batch
process_batch()
void MayaFlux::Nodes::ModalNetwork::process_batch (unsigned int num_samples) override virtual
Process the network for the given number of samples.
Parameters
num_samples Number of samples/frames to process
Subclasses implement their specific processing logic:
Update internal state (physics, relationships, etc.)
Process individual nodes
Apply inter-node interactions
Aggregate outputs if needed
Called by NodeGraphManager during token processing.
Implements MayaFlux::Nodes::NodeNetwork.
Definition at line 133 of file ModalNetwork.cpp.
{
    ensure_initialized();
    m_last_audio_buffer.clear();
    if (!is_enabled()) {
        m_last_audio_buffer.assign(num_samples, 0.0);
        m_last_output = 0.0;
        return;
    }
    update_mapped_parameters();
    m_last_audio_buffer.reserve(num_samples);
    for (unsigned int i = 0; i < num_samples; ++i) {
        double sum = 0.0;
        for (auto& mode : m_modes) {
            if (mode.amplitude > 0.0001) {
                mode.amplitude *= mode.decay_coefficient;
            } else {
                mode.amplitude = 0.0;
            }
            double sample = mode.oscillator->process_sample(0.0) * mode.amplitude;
            sum += sample;
        }
        m_last_audio_buffer.push_back(sum);
    }
    m_last_output = m_last_audio_buffer.back();
}
References MayaFlux::Nodes::NodeNetwork::ensure_initialized(), MayaFlux::Nodes::NodeNetwork::is_enabled(), MayaFlux::Nodes::NodeNetwork::m_last_audio_buffer, m_last_output, m_modes, and update_mapped_parameters().