MayaFlux: MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout
set_vertex_layout()
void MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout (const Kakshya::VertexLayout & layout) inline
Set cached vertex layout.
Parameters
layout VertexLayout describing attribute structure
Called internally or by GeometryBindingsProcessor to describe the semantic meaning of vertex data (positions, colors, normals, etc.)
Definition at line 251 of file GeometryWriterNode.hpp.
{ m_vertex_layout = layout; }
Referenced by MayaFlux::Nodes::GpuSync::PathGeneratorNode::compute_frame(), MayaFlux::Nodes::GpuSync::PointCollectionNode::compute_frame(), MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::compute_frame(), MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointNode::PointNode(), MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode(), and MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode().