MayaFlux: MayaFlux::Core::GLFWSingleton::configure
configure()
void MayaFlux::Core::GLFWSingleton::configure (const GlfwPreInitConfig & config) static
Configures GLFW with pre-initialization hints.
Parameters
config Configuration parameters to set before initialization
Must be called before initialize() to take effect. Sets various GLFW windowing and context hints based on the provided configuration. If called after initialization, the hints will be ignored.
Definition at line 16 of file GlfwSingleton.cpp.
{
    if (s_initialized) {
        MF_WARN(Journal::Component::Core, Journal::Context::WindowingSubsystem,
            "GLFWSingleton::configure() called after GLFW was initialized — pre-init hints will be ignored");
        return;
    }
    if (config.platform != GlfwPreInitConfig::Platform::Default) {
        int glfw_platform = GLFW_ANY_PLATFORM;
        switch (config.platform) {
        case GlfwPreInitConfig::Platform::Wayland:
            glfw_platform = GLFW_PLATFORM_WAYLAND;
            break;
        case GlfwPreInitConfig::Platform::X11:
            glfw_platform = GLFW_PLATFORM_X11;
            break;
        default:
            break;
        }
        glfwInitHint(GLFW_PLATFORM, glfw_platform);
    }
    glfwInitHint(GLFW_WAYLAND_LIBDECOR, config.disable_libdecor ? GLFW_FALSE : GLFW_TRUE);
    glfwInitHint(GLFW_COCOA_CHDIR_RESOURCES, config.cocoa_chdir_resources ? GLFW_TRUE : GLFW_FALSE);
    glfwInitHint(GLFW_COCOA_MENUBAR, config.cocoa_menubar ? GLFW_TRUE : GLFW_FALSE);
    s_configured = true;
    MF_INFO(Journal::Component::Core, Journal::Context::WindowingSubsystem,
        "GLFW pre-initialization configured: platform={}, libdecor={}, cocoa_chdir_resources={}, cocoa_menubar={}",
        (config.platform == GlfwPreInitConfig::Platform::Default
                ? "default"
                : config.platform == GlfwPreInitConfig::Platform::Wayland
                ? "wayland"
                : "x11"),
        config.disable_libdecor ? "disabled" : "enabled",
        config.cocoa_chdir_resources ? "enabled" : "disabled",
        config.cocoa_menubar ? "enabled" : "disabled");
    s_preinit_config = config;
}
References MayaFlux::Core::GlfwPreInitConfig::cocoa_chdir_resources, MayaFlux::Core::GlfwPreInitConfig::cocoa_menubar, MayaFlux::Journal::Core, MayaFlux::Core::GlfwPreInitConfig::Default, MayaFlux::Core::GlfwPreInitConfig::disable_libdecor, MF_INFO, MF_WARN, MayaFlux::Core::GlfwPreInitConfig::platform, s_configured, s_initialized, s_preinit_config, MayaFlux::Core::GlfwPreInitConfig::Wayland, MayaFlux::Journal::WindowingSubsystem, and MayaFlux::Core::GlfwPreInitConfig::X11.
Referenced by MayaFlux::Core::GlfwWindow::GlfwWindow(), initialize(), and MayaFlux::Core::VKContext::initialize().