MayaFlux: MayaFlux::Portal::Forma::Inspector::event
event()
InspectResult MayaFlux::Portal::Forma::Inspector::event (const std::shared_ptr< Vruta::Event > & ev, std::string_view name, Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F)
Inspect a single Event by name and pointer.
Header is the event's registered name, or "(unnamed)" if empty. Body rows expose token and active state.
Definition at line 10 of file EventQuery.cpp.
{
    const std::string header_label = name.empty() ? "(unnamed)" : std::string(name);
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "token",
            .reader = [ev] {
                return std::string(Reflect::enum_to_string(ev->get_processing_token()));
            },
        },
        ValueSpec {
            .label = "active",
            .reader = [ev] { return ev->is_active() ? "true" : "false"; },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), header_label, dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(values.size());
    for (const auto& spec : values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto group = make_value_group(values, std::move(hbuf), rbufs,
        surface, cursor, x_min, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    return result;
}
References MayaFlux::Reflect::enum_to_string(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueSpec::label, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::row_pixel_dims(), and MayaFlux::Portal::Forma::Surface::window().