MayaFlux: MayaFlux::Kakshya::FrameAccessProcessor::store_metadata
store_metadata()
void FrameAccessProcessor::store_metadata (const std::shared_ptr< SignalSourceContainer > & container) private
Cache dimension metadata and frame geometry from the container.
Parameters
container The SignalSourceContainer to query.
Definition at line 58 of file FrameAccessProcessor.cpp.
{
    m_structure = container->get_structure();
    const auto& dims = m_structure.dimensions;
    m_total_frames = ContainerDataStructure::get_frame_count(dims);
    m_height = ContainerDataStructure::get_height(dims);
    m_width = ContainerDataStructure::get_width(dims);
    m_channels = ContainerDataStructure::get_channel_count(dims);
    m_frame_byte_size = m_width * m_height * m_channels;
    if (auto stream = std::dynamic_pointer_cast<StreamContainer>(container)) {
        m_looping_enabled = stream->is_looping();
        m_loop_region = stream->get_loop_region();
        const auto& stream_positions = stream->get_read_position();
        if (!stream_positions.empty()) {
            m_current_frame = stream_positions[0];
        }
    }
    if (auto vc = std::dynamic_pointer_cast<VideoStreamContainer>(container))
        m_frame_rate = vc->get_frame_rate();
}
References MayaFlux::Kakshya::ContainerDataStructure::dimensions, MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_frame_count(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), m_channels, m_current_frame, m_frame_byte_size, m_frame_rate, m_height, m_loop_region, m_looping_enabled, m_structure, m_total_frames, and m_width.
Referenced by on_attach().