MayaFlux: MayaFlux::Nodes::Input::HIDNode::extract_value
extract_value()
double MayaFlux::Nodes::Input::HIDNode::extract_value (const Core::InputValue & value) override protected virtual
Extract a scalar value from an InputValue.
Parameters
value The input value to extract from
Returns
Scalar value for smoothing/output
Override in derived classes for specific input types. Default handles SCALAR and MIDI CC values.
Reimplemented from MayaFlux::Nodes::Input::InputNode.
Definition at line 15 of file HIDNode.cpp.
{
    if (value.type != Core::InputValue::Type::BYTES) {
        return m_config.default_value;
    }
    const auto& bytes = value.as_bytes();
    switch (m_config.mode) {
    case HIDParseMode::AXIS:
        return parse_axis(bytes);
    case HIDParseMode::BUTTON:
        return parse_button(bytes);
    case HIDParseMode::CUSTOM:
        return m_config.custom_parser
            ? m_config.custom_parser(bytes)
            : m_config.default_value;
    }
    return m_config.default_value;
}
References MayaFlux::Core::InputValue::as_bytes(), MayaFlux::Nodes::Input::AXIS, MayaFlux::Nodes::Input::BUTTON, MayaFlux::Core::InputValue::BYTES, MayaFlux::Nodes::Input::CUSTOM, MayaFlux::Nodes::Input::HIDConfig::custom_parser, MayaFlux::Nodes::Input::InputConfig::default_value, m_config, MayaFlux::Nodes::Input::HIDConfig::mode, parse_axis(), parse_button(), and MayaFlux::Core::InputValue::type.