MayaFlux: MayaFlux::Nodes::GpuSync::GeometryReadbackNode::GeometryReadbackNode
GeometryReadbackNode()
MayaFlux::Nodes::GpuSync::GeometryReadbackNode::GeometryReadbackNode (std::shared_ptr< Buffers::VKBuffer > buffer, size_t vertex_count = 0) explicit
Construct from a GPU vertex buffer.
Parameters
buffer GPU vertex buffer to download from. Must remain valid for the lifetime of this node.
vertex_count Expected number of MeshVertex elements. Used to size the readback vector. If 0, the count is derived from buffer->get_size_bytes().
Definition at line 10 of file GeometryReadbackNode.cpp.
    : GeometryWriterNode(0)
    , m_gpu_buffer(std::move(buffer))
{
    set_vertex_stride(sizeof(Kakshya::MeshVertex));
    set_vertex_layout(Kakshya::VertexLayout::for_meshes(sizeof(Kakshya::MeshVertex)));
    if (vertex_count > 0)
        m_vertices.resize(vertex_count);
}
References MayaFlux::Kakshya::VertexLayout::for_meshes(), m_vertices, MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride().