MayaFlux: MayaFlux::Core::VKSwapchain::cleanup_swapchain
cleanup_swapchain()
void MayaFlux::Core::VKSwapchain::cleanup_swapchain () private
Cleanup old swapchain during recreation.
Definition at line 159 of file VKSwapchain.cpp.
{
    if (!m_context) {
        return;
    }
    vk::Device device = m_context->get_device();
    for (auto image_view : m_image_views) {
        device.destroyImageView(image_view);
    }
    m_image_views.clear();
    if (m_swapchain) {
        device.destroySwapchainKHR(m_swapchain);
        m_swapchain = nullptr;
    }
    m_images.clear();
}
References MayaFlux::Core::VKContext::get_device(), m_context, m_image_views, m_images, and m_swapchain.
Referenced by cleanup(), create(), and recreate().