MayaFlux: MayaFlux::Nodes::Network::FieldOperator::process
process()
void MayaFlux::Nodes::Network::FieldOperator::process (float dt) override virtual
Process for one batch cycle.
Parameters
dt Time delta or sample count (operator-specific)
Implements MayaFlux::Nodes::Network::NetworkOperator.
Definition at line 59 of file FieldOperator.cpp.
{
    if (m_count == 0)
        return;
    if (m_mode == FieldMode::ABSOLUTE) {
        std::memcpy(m_vertex_data.data(), m_reference_data.data(), m_count * k_stride);
    }
    bool has_position = !m_position_fields.empty();
    bool has_color = !m_color_fields.empty();
    bool has_normal = !m_normal_fields.empty();
    bool has_tangent = !m_tangent_fields.empty();
    bool has_scalar = !m_scalar_fields.empty();
    bool has_uv = !m_uv_fields.empty();
    for (size_t i = 0; i < m_count; ++i) {
        glm::vec3& pos = vec3_at(i, k_position_offset);
        if (has_position) {
            glm::vec3 displacement(0.0F);
            for (const auto& field : m_position_fields) {
                displacement += field(pos);
            }
            pos += displacement;
        }
        if (has_color) {
            glm::vec3 color(0.0F);
            for (const auto& field : m_color_fields) {
                color += field(pos);
            }
            vec3_at(i, k_color_offset) = color;
        }
        if (has_normal) {
            glm::vec3 normal(0.0F);
            for (const auto& field : m_normal_fields) {
                normal += field(pos);
            }
            float len = glm::length(normal);
            vec3_at(i, k_normal_offset) = len > 1e-6F ? normal / len : glm::vec3(0.0F, 0.0F, 1.0F);
        }
        if (has_tangent) {
            glm::vec3 tangent(0.0F);
            for (const auto& field : m_tangent_fields) {
                tangent += field(pos);
            }
            float len = glm::length(tangent);
            vec3_at(i, k_tangent_offset) = len > 1e-6F ? tangent / len : glm::vec3(1.0F, 0.0F, 0.0F);
        }
        if (has_scalar) {
            float value = 0.0F;
            for (const auto& field : m_scalar_fields) {
                value += field(pos);
            }
            float_at(i, k_scalar_offset) = value;
        }
        if (has_uv) {
            const glm::vec3 ref = ref_position_at(i);
            glm::vec2 uv(0.0F);
            for (const auto& field : m_uv_fields)
                uv += field(ref);
            *reinterpret_cast<glm::vec2*>(
                m_vertex_data.data() + i * k_stride + k_uv_offset) = uv;
        }
    }
    m_dirty = true;
}
References MayaFlux::Nodes::Network::ABSOLUTE, color, float_at(), k_color_offset, k_normal_offset, k_position_offset, k_scalar_offset, k_stride, k_tangent_offset, k_uv_offset, m_color_fields, m_count, m_dirty, m_mode, m_normal_fields, m_position_fields, m_reference_data, m_scalar_fields, m_tangent_fields, m_uv_fields, m_vertex_data, ref_position_at(), and vec3_at().