MayaFlux: MayaFlux::Yantra::ShaderExecutionContext::dispatch_async
dispatch_async()
template<ComputeData InputType = std::vector<Kakshya::DataVariant>, ComputeData OutputType = InputType> Portal::Graphics::FenceID MayaFlux::Yantra::ShaderExecutionContext< InputType, OutputType >::dispatch_async (const input_type & input) inline
Dispatch asynchronously and return a fence for polling.
Equivalent to calling extract_inputs then dispatch_core_async. The fence becomes signaled when the GPU work completes. Call collect_result() once signaled to obtain the GpuChannelResult.
Parameters
input Input Datum. Channels are extracted before submission.
Returns
FenceID to poll with ShaderFoundry::is_fence_signaled. Returns INVALID_FENCE if GPU initialisation fails.
Definition at line 348 of file ShaderExecutionContext.hpp.
    {
        if (!this->ensure_gpu_ready())
            return Portal::Graphics::INVALID_FENCE;
        auto [channels, structure_info] = this->extract_inputs(input);
        return this->dispatch_core_async(channels, structure_info);
    }
References MayaFlux::Yantra::GpuDispatchCore::dispatch_core_async(), MayaFlux::Yantra::GpuDispatchCore::ensure_gpu_ready(), MayaFlux::Yantra::GpuExecutionContext< InputType, OutputType >::extract_inputs(), and MayaFlux::Portal::Graphics::INVALID_FENCE.