MayaFlux: MayaFlux::Journal::Archivist::Impl::write_to_console
write_to_console() [1/2]
static void MayaFlux::Journal::Archivist::Impl::write_to_console (const JournalEntry & entry) inline static private
Definition at line 159 of file Archivist.cpp.
    {
        if (colors_enabled) {
            switch (entry.severity) {
            case Severity::TRACE:
                std::cout << AnsiColors::Cyan;
                break;
            case Severity::DEBUG:
                std::cout << AnsiColors::Blue;
                break;
            case Severity::INFO:
                std::cout << AnsiColors::Green;
                break;
            case Severity::WARN:
                std::cout << AnsiColors::Yellow;
                break;
            case Severity::ERROR:
                std::cout << AnsiColors::BrightRed;
                break;
            case Severity::FATAL:
                std::cout << AnsiColors::BrightRed << AnsiColors::White;
                break;
            case Severity::NONE:
            default:
                std::cout << AnsiColors::Reset;
                break;
            }
        }
        std::cout << "[" << Reflect::enum_to_string(entry.severity) << "]" << AnsiColors::Reset;
        if (colors_enabled) {
            std::cout << AnsiColors::Magenta;
        }
        std::cout << "[" << Reflect::enum_to_string(entry.component) << "]" << AnsiColors::Reset;
        if (colors_enabled) {
            std::cout << AnsiColors::Cyan;
        }
        std::cout << "[" << Reflect::enum_to_string(entry.context) << "]" << AnsiColors::Reset << " ";
        std::cout << entry.message;
        if (entry.location.file_name() != nullptr && entry.location.line() != 0) {
            if (colors_enabled) {
                std::cout << AnsiColors::BrightBlue;
            }
            std::cout << " (" << entry.location.file_name()
                      << ":" << entry.location.line() << ")" << AnsiColors::Reset;
        }
        std::cout << '\n';
    }
References MayaFlux::Journal::AnsiColors::Blue, MayaFlux::Journal::AnsiColors::BrightBlue, MayaFlux::Journal::AnsiColors::BrightRed, MayaFlux::Journal::colors_enabled, MayaFlux::Journal::JournalEntry::component, MayaFlux::Journal::JournalEntry::context, MayaFlux::Journal::AnsiColors::Cyan, MayaFlux::Journal::DEBUG, MayaFlux::Reflect::enum_to_string(), MayaFlux::Journal::ERROR, MayaFlux::Journal::FATAL, MayaFlux::Journal::AnsiColors::Green, MayaFlux::Journal::INFO, MayaFlux::Journal::JournalEntry::location, MayaFlux::Journal::AnsiColors::Magenta, MayaFlux::Journal::JournalEntry::message, MayaFlux::Journal::NONE, MayaFlux::Journal::AnsiColors::Reset, MayaFlux::Journal::JournalEntry::severity, MayaFlux::Journal::TRACE, MayaFlux::Journal::WARN, MayaFlux::Journal::AnsiColors::White, and MayaFlux::Journal::AnsiColors::Yellow.
Referenced by drain_ring_buffer(), and scribe().