MayaFlux: MayaFlux::Buffers::BufferSupplyMixing::route_buffer_to_channel
route_buffer_to_channel()
void MayaFlux::Buffers::BufferSupplyMixing::route_buffer_to_channel (const std::shared_ptr< AudioBuffer > & buffer, uint32_t target_channel, uint32_t fade_cycles, ProcessingToken token)
Routes a buffer's processing from one channel to another with fade.
Parameters
buffer Buffer to route
target_channel Destination channel
fade_cycles Number of processing cycles to fade over
token Processing domain
Transitions the buffer's channel_id from its current channel to the target channel with smooth crossfade. During transition, buffer continues processing in its original channel while fading in via supply to the target channel.
Definition at line 186 of file BufferSupplyMixing.cpp.
{
    if (!buffer) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Invalid buffer for routing");
        return;
    }
    uint32_t current_channel = buffer->get_channel_id();
    if (current_channel == target_channel) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Buffer already on target channel {}", target_channel);
        return;
    }
    if (!m_unit_manager.has_audio_unit(token)) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Invalid token for routing");
        return;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    if (target_channel >= unit.channel_count) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Target channel {} out of range", target_channel);
        return;
    }
    uint32_t fade_blocks = std::max(1U, fade_cycles);
    BufferRoutingState state;
    state.from_channel = current_channel;
    state.to_channel = target_channel;
    state.fade_cycles = fade_blocks;
    state.from_amount = 1.0;
    state.to_amount = 0.0;
    state.cycles_elapsed = 0;
    state.phase = BufferRoutingState::ACTIVE;
    buffer->get_routing_state() = state;
    supply_audio_buffer_to(buffer, token, target_channel, 0.0);
}
References MayaFlux::Buffers::BufferRoutingState::ACTIVE, MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, MayaFlux::Buffers::BufferRoutingState::cycles_elapsed, MayaFlux::Buffers::BufferRoutingState::fade_cycles, MayaFlux::Buffers::BufferRoutingState::from_amount, MayaFlux::Buffers::BufferRoutingState::from_channel, MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), m_unit_manager, MF_ERROR, MF_WARN, supply_audio_buffer_to(), MayaFlux::Buffers::BufferRoutingState::to_amount, and MayaFlux::Buffers::BufferRoutingState::to_channel.