MayaFlux: MayaFlux::Core::Engine::Init
Init() [1/3]
void MayaFlux::Core::Engine::Init ()
Initializes all system components and prepares for processing.
Orchestrates the initialization sequence for all core components:
Creates and configures the task scheduler with the specified sample rate
Initializes the node graph manager and buffer manager
Sets up subsystem managers and audio backend
Establishes proper component interconnections
This method must be called before Start().
Definition at line 93 of file Engine.cpp.
{
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    if (Parallel::g_MainThreadId == 0) {
        Parallel::g_MainThreadId = GetCurrentThreadId();
    }
#endif // MAYAFLUX_PLATFORM_WINDOWS
    Init(m_stream_info, m_graphics_config, m_input_config, m_network_config);
}
References Init(), m_graphics_config, m_input_config, m_network_config, and m_stream_info.
Referenced by Init(), Init(), and Start().