MayaFlux: MayaFlux::Portal::Graphics::RenderFlow::shutdown
shutdown()
void MayaFlux::Portal::Graphics::RenderFlow::shutdown ()
Definition at line 94 of file RenderFlow.cpp.
{
    if (!s_initialized) {
        return;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::Rendering,
        "Shutting down RenderFlow...");
    if (!m_shader_foundry || !m_shader_foundry->is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "Cannot shutdown RenderFlow: ShaderFoundry not initialized");
        return;
    }
    auto device = m_shader_foundry->get_device();
    if (!device) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "Cannot shutdown RenderFlow: Vulkan device is null");
        return;
    }
    cleanup_pipelines();
    m_window_associations.clear();
    m_shader_foundry = nullptr;
    m_display_service = nullptr;
    s_initialized = false;
    MF_INFO(Journal::Component::Portal, Journal::Context::Rendering,
        "RenderFlow shutdown complete");
}
References cleanup_pipelines(), MayaFlux::Portal::Graphics::ShaderFoundry::get_device(), MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized(), m_display_service, m_shader_foundry, m_window_associations, MF_ERROR, MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Journal::Rendering, and s_initialized.
Referenced by MayaFlux::Portal::Graphics::shutdown().