MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::is_ready_for_processing
is_ready_for_processing()
bool MayaFlux::Kakshya::VideoStreamContainer::is_ready_for_processing () const override virtual
Check if the container is ready for processing.
Returns
true if ready to process, false otherwise
Used for scheduling and dependency resolution in data-driven pipelines.
Implements MayaFlux::Kakshya::SignalSourceContainer.
Definition at line 530 of file VideoStreamContainer.cpp.
{
    auto state = get_processing_state();
    return has_data() && (state == ProcessingState::READY || state == ProcessingState::PROCESSED);
}
References get_processing_state(), has_data(), MayaFlux::Kakshya::PROCESSED, and MayaFlux::Kakshya::READY.
Referenced by process_default().