MayaFlux: MayaFlux::Buffers::VKBuffer::is_host_visible
is_host_visible()
bool MayaFlux::Buffers::VKBuffer::is_host_visible () const inline
Whether this VKBuffer should be host-visible.
Returns
True for staging or uniform buffers, false for device-local types.
Definition at line 374 of file VKBuffer.hpp.
    {
        return m_usage == Usage::STAGING
            || m_usage == Usage::UNIFORM
            || m_usage == Usage::UNIFORM_BDA
            || m_usage == Usage::STORAGE_BDA;
    }
Referenced by clear(), clone_to(), get_data(), get_memory_properties(), mark_dirty_range(), mark_invalid_range(), resize(), and set_data().