MayaFlux: MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_network
update_from_network()
void MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_network (DescriptorBinding & binding) private
Definition at line 610 of file DescriptorBindingsProcessor.cpp.
{
    if (!binding.network) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "NETWORK binding '{}' has null network", binding.descriptor_name);
        return;
    }
    if (binding.source_type == SourceType::NETWORK_AUDIO) {
        auto data = binding.network->get_audio_buffer();
        if (!data) {
            MF_RT_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Network audio binding '{}' has no audio buffer", binding.descriptor_name);
            return;
        }
        const auto& samples = *data;
        size_t required = samples.size() * sizeof(float);
        thread_local std::vector<float> conv;
        conv.resize(samples.size());
        std::ranges::transform(samples, conv.begin(),
            [](double d) { return static_cast<float>(d); });
        upload_to_gpu(conv.data(), required, binding.gpu_buffer, nullptr);
        return;
    }
    auto gpu_data = extract_network_gpu_data(binding.network, binding.descriptor_name);
    if (gpu_data.vertex_data.empty()) {
        return;
    }
    ensure_buffer_capacity(binding, gpu_data.vertex_data.size_bytes());
    upload_to_gpu(
        gpu_data.vertex_data.data(),
        gpu_data.vertex_data.size_bytes(),
        binding.gpu_buffer,
        nullptr);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::descriptor_name, ensure_buffer_capacity(), MayaFlux::Buffers::extract_network_gpu_data(), MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::gpu_buffer, MF_RT_ERROR, MF_RT_WARN, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::network, NETWORK_AUDIO, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::source_type, and MayaFlux::Buffers::upload_to_gpu().
Referenced by update_descriptor_data().