MayaFlux: MayaFlux::Portal::Graphics::RenderFlow::create_render_pass
create_render_pass()
RenderPassID MayaFlux::Portal::Graphics::RenderFlow::create_render_pass (const std::vector< RenderPassAttachment > & attachments)
Create a render pass.
Parameters
attachments Attachment descriptions
Returns
Render pass ID
Definition at line 269 of file RenderFlow.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "RenderFlow not initialized");
        return INVALID_RENDER_PASS;
    }
    if (attachments.empty()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "Cannot create render pass with no attachments");
        return INVALID_RENDER_PASS;
    }
    auto render_pass = std::make_shared<Core::VKRenderPass>();
    Core::RenderPassCreateInfo create_info {};
    for (const auto& att : attachments) {
        Core::AttachmentDescription desc;
        desc.format = att.format;
        desc.samples = att.samples;
        desc.load_op = att.load_op;
        desc.store_op = att.store_op;
        desc.initial_layout = att.initial_layout;
        desc.final_layout = att.final_layout;
        create_info.attachments.push_back(desc);
    }
    Core::SubpassDescription subpass;
    subpass.bind_point = vk::PipelineBindPoint::eGraphics;
    for (uint32_t i = 0; i < attachments.size(); ++i) {
        vk::AttachmentReference ref;
        ref.attachment = i;
        ref.layout = vk::ImageLayout::eColorAttachmentOptimal;
        subpass.color_attachments.push_back(ref);
    }
    create_info.subpasses.push_back(subpass);
    // create_info.dependencies.emplace_back(
    //     VK_SUBPASS_EXTERNAL, 0,
    //     vk::PipelineStageFlagBits::eColorAttachmentOutput,
    //     vk::PipelineStageFlagBits::eColorAttachmentOutput,
    //     vk::AccessFlagBits::eColorAttachmentWrite,
    //     vk::AccessFlagBits::eColorAttachmentRead | vk::AccessFlagBits::eColorAttachmentWrite);
    // create_info.dependencies.emplace_back(
    //     0, VK_SUBPASS_EXTERNAL,
    //     vk::PipelineStageFlagBits::eColorAttachmentOutput,
    //     vk::PipelineStageFlagBits::eBottomOfPipe,
    //     vk::AccessFlagBits::eColorAttachmentWrite,
    //     vk::AccessFlagBits::eMemoryRead);
    if (!render_pass->create(m_shader_foundry->get_device(), create_info)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Rendering,
            "Failed to create VKRenderPass");
        return INVALID_RENDER_PASS;
    }
    auto render_pass_id = m_next_render_pass_id.fetch_add(1);
    RenderPassState state;
    state.render_pass = render_pass;
    state.attachments = attachments;
    m_render_passes[render_pass_id] = std::move(state);
    MF_DEBUG(Journal::Component::Portal, Journal::Context::Rendering,
        "Render pass created (ID: {}, {} attachments)",
        render_pass_id, attachments.size());
    return render_pass_id;
}
References MayaFlux::Portal::Graphics::RenderFlow::RenderPassState::attachments, MayaFlux::Core::SubpassDescription::bind_point, MayaFlux::Core::SubpassDescription::color_attachments, MayaFlux::Core::AttachmentDescription::final_layout, MayaFlux::Core::AttachmentDescription::format, MayaFlux::Portal::Graphics::ShaderFoundry::get_device(), MayaFlux::Core::AttachmentDescription::initial_layout, MayaFlux::Portal::Graphics::INVALID_RENDER_PASS, is_initialized(), MayaFlux::Core::AttachmentDescription::load_op, m_next_render_pass_id, m_render_passes, m_shader_foundry, MF_DEBUG, MF_ERROR, MayaFlux::Journal::Portal, MayaFlux::Portal::Graphics::RenderFlow::RenderPassState::render_pass, MayaFlux::Journal::Rendering, MayaFlux::Core::AttachmentDescription::samples, and MayaFlux::Core::AttachmentDescription::store_op.
Referenced by create_simple_render_pass().