MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::create_storage_image
create_storage_image()
std::shared_ptr< Core::VKImage > MayaFlux::Portal::Graphics::TextureLoom::create_storage_image (uint32_t width, uint32_t height, ImageFormat format = ImageFormat::RGBA8)
Create a storage image (compute shader read/write)
Parameters
width Width in pixels
height Height in pixels
format Image format
Returns
Initialized VKImage configured for compute storage
Definition at line 289 of file TextureLoom.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "TextureLoom not initialized");
        return nullptr;
    }
    auto vk_format = to_vulkan_format(format);
    auto image = std::make_shared<Core::VKImage>(
        width, height, 1, vk_format,
        Core::VKImage::Usage::STORAGE,
        Core::VKImage::Type::TYPE_2D,
        1, 1, Kakshya::DataModality::IMAGE_COLOR);
    m_resource_manager->initialize_image(image);
    if (!image->is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "Failed to initialize storage image VKImage");
        return nullptr;
    }
    m_resource_manager->transition_image_layout(
        image->get_image(),
        vk::ImageLayout::eUndefined,
        vk::ImageLayout::eGeneral,
        1, 1, vk::ImageAspectFlagBits::eColor);
    image->set_current_layout(vk::ImageLayout::eGeneral);
    m_textures.push_back(image);
    MF_INFO(Journal::Component::Portal, Journal::Context::ImageProcessing,
        "Created storage image: {}x{}, format: {}",
        width, height, vk::to_string(vk_format));
    return image;
}
References MayaFlux::Kakshya::IMAGE_COLOR, MayaFlux::Journal::ImageProcessing, MayaFlux::Core::BackendResourceManager::initialize_image(), is_initialized(), m_resource_manager, m_textures, MF_ERROR, MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Core::VKImage::STORAGE, to_vulkan_format(), MayaFlux::Core::BackendResourceManager::transition_image_layout(), and MayaFlux::Core::VKImage::TYPE_2D.