MayaFlux: MayaFlux::Nodes::NodeGraphManager::print_summary
print_summary()
void MayaFlux::Nodes::NodeGraphManager::print_summary () const
Prints a summary of all tokens, channels, and node counts.
Outputs a human-readable summary of the current node graph structure, including the number of tokens, channels, and nodes per domain. Useful for debugging and introspection.
Definition at line 407 of file NodeGraphManager.cpp.
{
    MF_PRINT(Journal::Component::Nodes,
        Journal::Context::NodeProcessing,
        "=== NodeGraphManager Summary ===");
    for (auto token : get_active_tokens()) {
        auto channels = get_all_channels(token);
        size_t total_nodes = get_node_count(token);
        MF_PRINT(Journal::Component::Nodes,
            Journal::Context::NodeProcessing,
            "Token {}: {} nodes across {} channels",
            static_cast<int>(token), total_nodes, channels.size());
        for (auto channel : channels) {
            auto& root = const_cast<NodeGraphManager*>(this)->get_root_node(token, channel);
            auto networks = get_networks(token, channel);
            MF_PRINT(Journal::Component::Nodes,
                Journal::Context::NodeProcessing,
                "  Channel {}: {} nodes, {} networks",
                channel, root.get_node_size(), networks.size());
            for (const auto& network : networks) {
                if (network) {
                    MF_PRINT(Journal::Component::Nodes,
                        Journal::Context::NodeProcessing,
                        "    Network: {} internal nodes, mode={}, enabled={}",
                        network->get_node_count(),
                        static_cast<int>(network->get_output_mode()),
                        network->is_enabled());
                }
            }
        }
    }
}
References channel, get_active_tokens(), get_all_channels(), get_networks(), get_node_count(), get_root_node(), MF_PRINT, MayaFlux::Journal::NodeProcessing, and MayaFlux::Journal::Nodes.