MayaFlux: MayaFlux::Kinesis::Vision::VisionSequence::Builder::push
push()
Builder & MayaFlux::Kinesis::Vision::VisionSequence::Builder::push (VisionOp op, VisionParams p = std::monostate {}) inline private
Definition at line 323 of file VisionOp.hpp.
                                                                 {})
        {
            m_steps.push_back({ .op = op, .params = std::move(p) });
            return *this;
        }
Referenced by canny(), close(), dilate(), downsample_2x(), erode(), extract_peaks(), filter_separable(), find_contours(), gaussian_blur(), gray_to_rgba(), harris_response(), morph_gradient(), normalize(), normalize_range(), open(), rgba_to_gray(), rgba_to_hsv(), scharr(), snapshot(), sobel(), threshold(), threshold_adaptive(), threshold_otsu(), and track_keypoints().