MayaFlux: MayaFlux::Buffers::BufferProcessingControl::remove_graphics_processor
remove_graphics_processor()
void MayaFlux::Buffers::BufferProcessingControl::remove_graphics_processor (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token)
Removes a processor from the graphics processing chain.
Parameters
processor Processor to remove
token Processing domain
Definition at line 339 of file BufferProcessingControl.cpp.
{
    if (!m_unit_manager.has_graphics_unit(token)) {
        MF_WARN(Journal::Component::Core, Journal::Context::BufferManagement,
            "Token {} not found when removing graphics processor",
            static_cast<int>(token));
        return;
    }
    auto& unit = m_unit_manager.get_graphics_unit_mutable(token);
    auto chain = unit.get_chain();
    auto root_buffer = unit.get_buffer();
    chain->remove_processor(processor, root_buffer);
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::RootGraphicsUnit::get_chain(), MayaFlux::Buffers::TokenUnitManager::get_graphics_unit_mutable(), MayaFlux::Buffers::TokenUnitManager::has_graphics_unit(), m_unit_manager, and MF_WARN.
Referenced by remove_processor(), and remove_processor_from_token().