MayaFlux: MayaFlux::Buffers::FilterProcessor::process_single_sample
process_single_sample()
void MayaFlux::Buffers::FilterProcessor::process_single_sample (double & sample) private
Definition at line 8 of file FilterProcessor.cpp.
{
    if (m_use_internal) {
        sample = m_filter->process_sample(sample);
        return;
    }
    Nodes::atomic_inc_modulator_count(m_filter->m_modulator_count, 1);
    uint32_t state = m_filter->m_state.load();
    if (state & Nodes::NodeState::PROCESSED) {
        sample = m_filter->get_last_output();
    } else {
        sample = m_filter->process_sample(sample);
        Nodes::atomic_add_flag(m_filter->m_state, Nodes::NodeState::PROCESSED);
    }
    Nodes::atomic_dec_modulator_count(m_filter->m_modulator_count, 1);
    Nodes::try_reset_processed_state(m_filter);
}
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), m_filter, m_use_internal, MayaFlux::Nodes::PROCESSED, and MayaFlux::Nodes::try_reset_processed_state().