MayaFlux: MayaFlux::Kakshya::RegionCacheManager::cache_region
cache_region()
void MayaFlux::Kakshya::RegionCacheManager::cache_region (const RegionCache & cache)
Definition at line 26 of file RegionCacheManager.cpp.
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex);
    const Region& region = cache.source_region;
    auto it = m_cache.find(region);
    if (it != m_cache.end()) {
        it->second = cache;
        update_lru(region);
    } else {
        evict_lru_if_needed();
        m_cache[region] = cache;
        m_lru_list.push_front(region);
    }
}
References evict_lru_if_needed(), m_cache, m_lru_list, m_mutex, MayaFlux::Kakshya::RegionCache::source_region, and update_lru().
Referenced by cache_segment().