MayaFlux: MayaFlux::IO::ImageReader::load
load() [2/2]
std::optional< ImageData > MayaFlux::IO::ImageReader::load (const std::string & path, int desired_channels = 4) static
Load image from file (static utility)
Parameters
path Image file path
desired_channels Force channel count (0 = keep original, 4 = RGBA)
Returns
Image data or nullopt on failure
Definition at line 348 of file ImageReader.cpp.
{
    return load(std::filesystem::path(path), desired_channels);
}
References load().
Referenced by load(), load_texture(), and open().