MayaFlux: MayaFlux::Buffers::MeshProcessor::allocate_gpu_buffers
allocate_gpu_buffers()
void MayaFlux::Buffers::MeshProcessor::allocate_gpu_buffers (const std::shared_ptr< MeshBuffer > & buf) private
Definition at line 113 of file MeshProcessor.cpp.
{
    const auto* vb = std::get_if<std::vector<uint8_t>>(
        &buf->m_mesh_data.vertex_variant);
    const auto* ib = std::get_if<std::vector<uint32_t>>(
        &buf->m_mesh_data.index_variant);
    if (!vb || vb->empty() || !ib || ib->empty()) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "MeshProcessor::allocate_gpu_buffers: empty vertex or index data");
        return;
    }
    if (!buf->is_host_visible()) {
        m_vertex_staging = create_staging_buffer(vb->size());
    }
    const size_t idx_bytes = ib->size() * sizeof(uint32_t);
    m_gpu_index_buffer = std::make_shared<VKBuffer>(
        idx_bytes,
        VKBuffer::Usage::INDEX,
        Kakshya::DataModality::UNKNOWN);
    ensure_initialized(m_gpu_index_buffer);
    m_index_staging = create_staging_buffer(idx_bytes);
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "MeshProcessor: allocated vertex buffer ({} bytes) + index buffer ({} bytes)",
        vb->size(), idx_bytes);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::create_staging_buffer(), MayaFlux::Buffers::VKBufferProcessor::ensure_initialized(), MayaFlux::Buffers::VKBuffer::INDEX, m_gpu_index_buffer, m_index_staging, m_vertex_staging, MF_DEBUG, MF_ERROR, and MayaFlux::Kakshya::UNKNOWN.
Referenced by on_attach().