MayaFlux: MayaFlux::CreationHandle::domain
domain()
template<typename T > CreationHandle & MayaFlux::CreationHandle< T >::domain (Domain d) inline
Definition at line 57 of file Creator.hpp.
    {
        m_ctx.domain = d;
        apply_if_ready();
        return *this;
    }
References MayaFlux::CreationHandle< T >::apply_if_ready(), MayaFlux::CreationContext::domain, and MayaFlux::CreationHandle< T >::m_ctx.
Referenced by MayaFlux::CreationHandle< T >::operator|(), and MayaFlux::operator|().