MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::compile_from_spirv
compile_from_spirv()
std::shared_ptr< Core::VKShaderModule > MayaFlux::Portal::Graphics::ShaderFoundry::compile_from_spirv (const std::string & spirv_path, ShaderStage stage, const std::string & entry_point = "main") private
Definition at line 211 of file ShaderFoundry.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "ShaderFoundry not initialized");
        return nullptr;
    }
    auto it = m_shader_cache.find(spirv_path);
    if (it != m_shader_cache.end()) {
        MF_DEBUG(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Using cached SPIR-V shader: {}", spirv_path);
        return it->second;
    }
    auto shader = create_shader_module();
    auto vk_stage = to_vulkan_stage(stage);
    if (!shader->create_from_spirv_file(
            get_device(), spirv_path, vk_stage, entry_point,
            m_config.enable_reflection)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Failed to load SPIR-V shader: {}", spirv_path);
        return nullptr;
    }
    m_shader_cache[spirv_path] = shader;
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "Loaded SPIR-V shader: {}", spirv_path);
    return shader;
}
References create_shader_module(), MayaFlux::Portal::Graphics::ShaderCompilerConfig::enable_reflection, get_device(), is_initialized(), m_config, m_shader_cache, MF_DEBUG, MF_ERROR, MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Journal::ShaderCompilation, and to_vulkan_stage().
Referenced by compile(), and load_shader().