MayaFlux: MayaFlux::Core::OscParser::parse
parse()
std::optional< InputValue > MayaFlux::Core::OscParser::parse (const uint8_t * data, size_t size, uint32_t device_id = 0) static
Parse a single OSC message from raw bytes.
Parameters
data Pointer to datagram payload.
size Payload size in bytes.
device_id Device id to stamp on the resulting InputValue.
Returns
Parsed InputValue with Type::OSC, or nullopt on parse failure.
Definition at line 7 of file OscParser.cpp.
{
    if (size < 4 || data[0] != '/') {
        return std::nullopt;
    }
    size_t offset = 0;
    std::string address = Transitive::Protocol::read_string(data, size, offset);
    if (address.empty() || offset >= size) {
        return std::nullopt;
    }
    std::string type_tags;
    if (offset < size && data[offset] == ',') {
        type_tags = Transitive::Protocol::read_string(data, size, offset);
        if (!type_tags.empty() && type_tags[0] == ',') {
            type_tags = type_tags.substr(1);
        }
    }
    std::vector<InputValue::OSCArg> arguments;
    arguments.reserve(type_tags.size());
    for (char tag : type_tags) {
        if (offset > size) {
            break;
        }
        switch (tag) {
        case 'i':
            if (offset + 4 <= size) {
                arguments.emplace_back(Transitive::Protocol::read_int32(data, offset));
            }
            break;
        case 'f':
            if (offset + 4 <= size) {
                arguments.emplace_back(Transitive::Protocol::read_float(data, offset));
            }
            break;
        case 's':
            arguments.emplace_back(Transitive::Protocol::read_string(data, size, offset));
            break;
        case 'b':
            arguments.emplace_back(Transitive::Protocol::read_blob(data, size, offset));
            break;
        default:
            break;
        }
    }
    return InputValue::make_osc(std::move(address), std::move(arguments), device_id);
}
References MayaFlux::Core::InputValue::make_osc(), MayaFlux::Transitive::Protocol::read_blob(), MayaFlux::Transitive::Protocol::read_float(), MayaFlux::Transitive::Protocol::read_int32(), MayaFlux::Transitive::Protocol::read_string(), and size.
Referenced by MayaFlux::Portal::Network::as_osc(), and MayaFlux::Core::InputManager::setup_osc_bridge().