MayaFlux: MayaFlux::Core::GlfwWindow::GlfwWindow
GlfwWindow() [1/3]
MayaFlux::Core::GlfwWindow::GlfwWindow (const WindowCreateInfo & create_info, const GraphicsSurfaceInfo & surface_info, GlobalGraphicsConfig::GraphicsApi api, GlfwPreInitConfig pre_init_config = {})
Creates a window with the given configuration.
Parameters
create_info Window creation parameters
surface_info Graphics surface parameters
api Requested graphics API
pre_init_config Optional pre-initialization configuration
Definition at line 18 of file GlfwWindow.cpp.
    : m_create_info(create_info)
{
    GLFWSingleton::configure(pre_init_config);
    if (!GLFWSingleton::initialize()) {
        error<std::runtime_error>(Journal::Component::Core, Journal::Context::WindowingSubsystem, std::source_location::current(),
            "Failed to initialize GLFW for window creation");
    }
    configure_window_hints(surface_info, api);
    GLFWmonitor* monitor = nullptr;
    if (create_info.fullscreen) {
        if (create_info.monitor_id >= 0) {
            int count {};
            std::span<GLFWmonitor*> monitors(glfwGetMonitors(&count), count);
            if (create_info.monitor_id < count) {
                monitor = monitors[create_info.monitor_id];
            }
        } else {
            monitor = glfwGetPrimaryMonitor();
        }
    }
    m_window = glfwCreateWindow(
        (int32_t)create_info.width,
        (int32_t)create_info.height,
        create_info.title.c_str(),
        monitor,
        nullptr);
    if (!m_window) {
        error<std::runtime_error>(Journal::Component::Core, Journal::Context::WindowingSubsystem, std::source_location::current(),
            "Failed to create GLFW window: {}", create_info.title);
    }
    glfwSetWindowUserPointer(m_window, this);
    setup_callbacks();
    int w {}, h {};
    glfwGetWindowSize(m_window, &w, &h);
    m_state.current_width = w;
    m_state.current_height = h;
    m_state.is_visible = false;
    GLFWSingleton::mark_window_created();
    MF_INFO(Journal::Component::Core, Journal::Context::WindowingSubsystem,
        "Created window '{}' ({}x{})", create_info.title, w, h);
}
References MayaFlux::Core::GLFWSingleton::configure(), configure_window_hints(), MayaFlux::Journal::Core, count, MayaFlux::Core::WindowState::current_height, MayaFlux::Core::WindowState::current_width, MayaFlux::Core::WindowCreateInfo::fullscreen, h, MayaFlux::Core::WindowCreateInfo::height, MayaFlux::Core::GLFWSingleton::initialize(), MayaFlux::Core::WindowState::is_visible, m_state, m_window, MayaFlux::Core::GLFWSingleton::mark_window_created(), MF_INFO, MayaFlux::Core::WindowCreateInfo::monitor_id, setup_callbacks(), MayaFlux::Core::WindowCreateInfo::title, MayaFlux::Core::WindowCreateInfo::width, and MayaFlux::Journal::WindowingSubsystem.