MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::can_transfer
can_transfer()
bool MayaFlux::Buffers::BufferTokenDistributor::can_transfer (const std::shared_ptr< Buffer > & source, ProcessingToken src_token, const std::shared_ptr< Buffer > & target, ProcessingToken tgt_token) static private
Definition at line 192 of file BufferTokenDistributor.cpp.
{
    if (source == target && src_token == tgt_token) {
        return false;
    }
    auto audio_src = std::dynamic_pointer_cast<AudioBuffer>(source);
    auto audio_tgt = std::dynamic_pointer_cast<AudioBuffer>(target);
    auto vk_src = std::dynamic_pointer_cast<VKBuffer>(source);
    auto vk_tgt = std::dynamic_pointer_cast<VKBuffer>(target);
    // Audio (SAMPLE_RATE, CPU) → VK (SAMPLE_RATE or FRAME_RATE, GPU)
    if (audio_src && vk_tgt) {
        if (has_sample_rate(src_token) && has_cpu(src_token)) {
            if (has_gpu(tgt_token)) {
                return true;
            }
        }
    }
    // VK (any rate, GPU) → Audio (SAMPLE_RATE, CPU)
    if (vk_src && audio_tgt) {
        if (has_gpu(src_token)) {
            if (has_sample_rate(tgt_token) && has_cpu(tgt_token)) {
                return true;
            }
        }
    }
    // Audio (SAMPLE_RATE, GPU) → Audio (SAMPLE_RATE, CPU)
    if (audio_src && audio_tgt) {
        if (has_sample_rate(src_token) && has_gpu(src_token)) {
            if (has_sample_rate(tgt_token) && has_cpu(tgt_token)) {
                return true;
            }
        }
    }
    // VK → VK (GPU to GPU, rate-dependent)
    if (vk_src && vk_tgt) {
        if (has_gpu(src_token) && has_gpu(tgt_token)) {
            return true;
        }
    }
    return false;
}
References has_cpu(), has_gpu(), and has_sample_rate().
Referenced by decide_transfer().