MayaFlux: MayaFlux::Buffers::ImageCVProcessor::processing_function
processing_function()
template<GpuImageSource T> void MayaFlux::Buffers::ImageCVProcessor< T >::processing_function (const std::shared_ptr< Buffer > &) inline override virtual
Download the current GPU image, run the VisionSequence, store the result.
No-op if the buffer has expired or the image is unavailable.
Parameters
buffer The GpuImageSource buffer to read from.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 91 of file ImageCVProcessor.hpp.
    {
        auto typed = m_buffer.lock();
        if (!typed)
            return;
        auto image = resolve_gpu_image(*typed);
        if (!image || !image->is_initialized())
            return;
        auto frame = download_and_normalise(image, m_raw_staging, m_float_work, m_gpu_staging);
        if (frame.empty())
            return;
        m_is_processing.store(true, std::memory_order_release);
        m_result = m_executor.run(
            m_sequence, frame,
            image->get_width(), image->get_height());
        if (m_result_source)
            m_result_source->signal(m_result);
        m_is_processing.store(false, std::memory_order_release);
    }
References MayaFlux::Buffers::download_and_normalise(), image, MayaFlux::Buffers::ImageCVProcessor< T >::m_buffer, MayaFlux::Buffers::ImageCVProcessor< T >::m_executor, MayaFlux::Buffers::ImageCVProcessor< T >::m_float_work, MayaFlux::Buffers::ImageCVProcessor< T >::m_gpu_staging, MayaFlux::Buffers::ImageCVProcessor< T >::m_is_processing, MayaFlux::Buffers::ImageCVProcessor< T >::m_raw_staging, MayaFlux::Buffers::ImageCVProcessor< T >::m_result, MayaFlux::Buffers::ImageCVProcessor< T >::m_result_source, MayaFlux::Buffers::ImageCVProcessor< T >::m_sequence, MayaFlux::Buffers::resolve_gpu_image(), and MayaFlux::Kinesis::Vision::VisionExecutor::run().