MayaFlux: MayaFlux::Nodes::NodeGraphManager::postprocess_networks
postprocess_networks()
void MayaFlux::Nodes::NodeGraphManager::postprocess_networks (ProcessingToken token, std::optional< uint32_t > channel) private
Postprocess networks for a specific token and channel.
Parameters
token Processing domain
channel Channel index
Definition at line 170 of file NodeGraphManager.cpp.
{
    if (token == ProcessingToken::AUDIO_RATE && channel.has_value()) {
        auto ch = channel.value_or(0U);
        reset_audio_network_state(token, ch);
    } else if (auto it = m_token_networks.find(token); it != m_token_networks.end()) {
        for (auto& network : it->second) {
            if (network && network->is_enabled()) {
                network->mark_processed(false);
            }
        }
    }
    if (auto it = m_token_network_processing.find(token); it != m_token_network_processing.end()) {
        it->second->store(false, std::memory_order_release);
    }
}
References MayaFlux::Nodes::AUDIO_RATE, m_token_network_processing, m_token_networks, and reset_audio_network_state().
Referenced by process_audio_networks(), and process_token().