MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::update_processing_state
update_processing_state()
void MayaFlux::Kakshya::SoundStreamContainer::update_processing_state (ProcessingState new_state) override virtual
Update the processing state of the container.
Parameters
new_state New ProcessingState to set
May trigger registered state change callbacks for event-driven workflows.
Implements MayaFlux::Kakshya::SignalSourceContainer.
Definition at line 609 of file SoundStreamContainer.cpp.
{
    ProcessingState old_state = m_processing_state.exchange(new_state);
    if (old_state != new_state) {
        notify_state_change(new_state);
        if (new_state == ProcessingState::READY) {
            std::lock_guard<std::mutex> lock(m_reader_mutex);
            m_consumed_dimensions.clear();
        }
    }
}
References lock(), m_consumed_dimensions, m_processing_state, m_reader_mutex, notify_state_change(), and MayaFlux::Kakshya::READY.
Referenced by clear(), mark_ready_for_processing(), process_default(), MayaFlux::Kakshya::DynamicSoundStream::set_all_data(), and MayaFlux::Kakshya::SoundFileContainer::setup().