MayaFlux: MayaFlux::Kriya::BufferPipeline::execute_streaming
execute_streaming()
Vruta::SoundRoutine MayaFlux::Kriya::BufferPipeline::execute_streaming (uint64_t max_cycles, uint64_t samples_per_operation) private
Definition at line 930 of file BufferPipeline.cpp.
{
    auto& promise = co_await Kriya::GetAudioPromise {};
    if (m_operations.empty()) {
        co_return;
    }
    m_data_states.resize(m_operations.size(), DataState::EMPTY);
    uint32_t cycles_executed = 0;
    while ((max_cycles == 0 || cycles_executed < max_cycles) && (m_continuous_execution || cycles_executed < max_cycles)) {
        if (promise.should_terminate) {
            break;
        }
        if (m_cycle_start_callback) {
            m_cycle_start_callback(m_current_cycle);
        }
        for (size_t i = 0; i < m_operations.size(); ++i) {
            auto& op = m_operations[i];
            if (op.get_type() == BufferOperation::OpType::CONDITION) {
                if (!op.m_condition || !op.m_condition(m_current_cycle)) {
                    continue;
                }
            }
            if (m_current_cycle % op.m_cycle_interval != 0) {
                continue;
            }
            uint32_t op_iterations = 1;
            if (op.get_type() == BufferOperation::OpType::CAPTURE) {
                op_iterations = op.m_capture.get_cycle_count();
            }
            for (uint32_t iter = 0; iter < op_iterations; ++iter) {
                process_operation(op, m_current_cycle + iter);
                m_data_states[i] = DataState::READY;
                for (size_t j = i + 1; j < m_operations.size(); ++j) {
                    auto& dependent_op = m_operations[j];
                    if (BufferOperation::is_process_phase_operation(dependent_op)) {
                        process_operation(dependent_op, m_current_cycle + iter);
                        m_data_states[j] = DataState::READY;
                    }
                    break;
                }
                if (m_capture_timing == Vruta::DelayContext::BUFFER_BASED) {
                    co_await BufferDelay { 1 };
                } else if (samples_per_operation > 0) {
                    co_await SampleDelay { samples_per_operation };
                }
            }
        }
        for (auto& branch : m_branches) {
            if (branch.condition(m_current_cycle)) {
                dispatch_branch_async(branch, m_current_cycle);
            }
        }
        cleanup_completed_branches();
        if (m_cycle_end_callback) {
            m_cycle_end_callback(m_current_cycle);
        }
        cleanup_expired_data();
        m_current_cycle++;
        cycles_executed++;
    }
    if (m_on_complete)
        m_on_complete();
}
References MayaFlux::Vruta::BUFFER_BASED, MayaFlux::Kriya::BufferOperation::CAPTURE, cleanup_completed_branches(), cleanup_expired_data(), MayaFlux::Kriya::BufferOperation::CONDITION, dispatch_branch_async(), EMPTY, MayaFlux::Kriya::BufferOperation::is_process_phase_operation(), m_branches, m_capture_timing, m_continuous_execution, m_current_cycle, m_cycle_end_callback, m_cycle_start_callback, m_data_states, m_on_complete, m_operations, process_operation(), and READY.
Referenced by execute_internal().