MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_or_create_audio_unit
get_or_create_audio_unit()
RootAudioUnit & MayaFlux::Buffers::TokenUnitManager::get_or_create_audio_unit (ProcessingToken token)
Gets or creates a root audio unit for the specified token.
Parameters
token Processing domain
Returns
Reference to the root audio unit
If the unit doesn't exist, creates it and returns it. Thread-safe creation via lock guard.
Definition at line 71 of file TokenUnitManager.cpp.
{
    auto it = m_audio_units.find(token);
    if (it == m_audio_units.end()) {
        std::lock_guard<std::mutex> lock(m_manager_mutex);
        auto [inserted_it, success] = m_audio_units.emplace(token, RootAudioUnit {});
        return inserted_it->second;
    }
    return it->second;
}
References m_audio_units, and m_manager_mutex.
Referenced by MayaFlux::Buffers::BufferAccessControl::add_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::add_audio_processor_to_token(), ensure_and_get_audio_unit(), ensure_audio_channels(), MayaFlux::Buffers::BufferAccessControl::get_audio_processing_chain(), MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer(), and resize_audio_buffers().