MayaFlux: MayaFlux::Nodes::Generator::Stochastics::Random::random_sample
random_sample()
double MayaFlux::Nodes::Generator::Stochastics::Random::random_sample (double start, double end)
Generates a stochastic value within a specified range.
Parameters
start Lower bound of the range
end Upper bound of the range
Returns
Value within the specified range based on current distribution
This method provides precise control over the output range while maintaining the statistical properties of the selected distribution.
Definition at line 26 of file Stochastic.cpp.
{
    validate_range(start, end);
    m_current_start = start;
    m_current_end = end;
    return transform_sample(generate_distributed_sample(), start, end) * m_amplitude;
}
References generate_distributed_sample(), MayaFlux::Nodes::Generator::Generator::m_amplitude, m_current_end, m_current_start, transform_sample(), and validate_range().
Referenced by MayaFlux::get_exponential_random(), MayaFlux::get_gaussian_random(), MayaFlux::get_poisson_random(), MayaFlux::get_uniform_random(), and process_sample().