MayaFlux: MayaFlux::Buffers::RenderProcessor::initialize_descriptors
initialize_descriptors()
void MayaFlux::Buffers::RenderProcessor::initialize_descriptors (const std::shared_ptr< VKBuffer > & buffer) override protected virtual
Implements MayaFlux::Buffers::ShaderProcessor.
Definition at line 325 of file RenderProcessor.cpp.
{
    if (m_pipeline_id == Portal::Graphics::INVALID_RENDER_PIPELINE) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot allocate descriptor sets without pipeline");
        return;
    }
    on_before_descriptors_create();
    auto& flow = Portal::Graphics::get_render_flow();
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto vt_layout = flow.get_view_transform_layout(m_pipeline_id);
    if (vt_layout) {
        m_view_transform_descriptor_set_id = foundry.allocate_descriptor_set(vt_layout);
        m_view_transform_ubo = std::make_shared<VKBuffer>(
            sizeof(Kinesis::ViewTransform),
            VKBuffer::Usage::UNIFORM,
            Kakshya::DataModality::UNKNOWN);
        ensure_initialized(m_view_transform_ubo);
        foundry.update_descriptor_buffer(
            m_view_transform_descriptor_set_id,
            0,
            vk::DescriptorType::eUniformBuffer,
            m_view_transform_ubo->get_buffer(),
            0,
            sizeof(Kinesis::ViewTransform));
        MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "ViewTransform UBO allocated (pipeline {})", m_pipeline_id);
    }
    m_descriptor_set_ids = flow.allocate_pipeline_descriptors(m_pipeline_id, 1);
    for (const auto& [binding, tex_binding] : m_texture_bindings) {
        if (!tex_binding.texture
            || !tex_binding.texture->is_initialized()
            || !tex_binding.texture->get_image_view()) {
            continue;
        }
        auto config_it = std::ranges::find_if(m_config.bindings,
            [binding](const auto& pair) {
                return binding >= pair.second.binding
                    && binding < pair.second.binding + pair.second.count;
            });
        if (config_it == m_config.bindings.end()) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "No config for binding {}", binding);
            continue;
        }
        const uint32_t set_index = config_it->second.set;
        if (set_index == 0) {
            if (m_view_transform_descriptor_set_id == Portal::Graphics::INVALID_DESCRIPTOR_SET) {
                MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                    "Engine descriptor set not allocated for set=0 texture binding {}", binding);
                continue;
            }
            foundry.update_descriptor_image(
                m_view_transform_descriptor_set_id,
                config_it->second.binding,
                tex_binding.texture->get_image_view(),
                tex_binding.sampler,
                vk::ImageLayout::eShaderReadOnlyOptimal,
                binding - config_it->second.binding);
            continue;
        }
        auto ds_index = resolve_ds_index(set_index);
        if (!ds_index) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Descriptor set index {} out of range", binding);
            continue;
        }
        foundry.update_descriptor_image(
            m_descriptor_set_ids[*ds_index],
            config_it->second.binding,
            tex_binding.texture->get_image_view(),
            tex_binding.sampler,
            vk::ImageLayout::eShaderReadOnlyOptimal,
            binding - config_it->second.binding);
    }
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Allocated {} descriptor sets and updated {} texture bindings",
        m_descriptor_set_ids.size(), m_texture_bindings.size());
    update_descriptors(buffer);
    on_descriptors_created();
}
References MayaFlux::Buffers::ShaderConfig::bindings, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBufferProcessor::ensure_initialized(), MayaFlux::Portal::Graphics::get_render_flow(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_DESCRIPTOR_SET, MayaFlux::Portal::Graphics::INVALID_RENDER_PIPELINE, MayaFlux::Buffers::ShaderProcessor::m_config, MayaFlux::Buffers::ShaderProcessor::m_descriptor_set_ids, m_pipeline_id, m_texture_bindings, m_view_transform_descriptor_set_id, m_view_transform_ubo, MF_DEBUG, MF_ERROR, MF_RT_ERROR, MayaFlux::Buffers::ShaderProcessor::on_before_descriptors_create(), MayaFlux::Buffers::ShaderProcessor::on_descriptors_created(), MayaFlux::Buffers::ShaderProcessor::resolve_ds_index(), MayaFlux::Buffers::VKBuffer::UNIFORM, MayaFlux::Kakshya::UNKNOWN, and MayaFlux::Buffers::ShaderProcessor::update_descriptors().