MayaFlux: MayaFlux::Core::InputSubsystem::add_backend
add_backend()
bool MayaFlux::Core::InputSubsystem::add_backend (std::unique_ptr< IInputBackend > backend)
Add a custom input backend.
Parameters
backend Backend instance (takes ownership)
Returns
true if added successfully
Definition at line 196 of file InputSubsystem.cpp.
{
    if (!backend)
        return false;
    InputType type = backend->get_type();
    std::unique_lock lock(m_backends_mutex);
    if (m_backends.find(type) != m_backends.end()) {
        MF_WARN(Journal::Component::Core, Journal::Context::InputSubsystem,
            "Backend type {} already registered", static_cast<int>(type));
        return false;
    }
    if (!backend->initialize()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputSubsystem,
            "Failed to initialize backend: {}", backend->get_name());
        return false;
    }
    wire_backend_to_manager(backend.get());
    m_backends[type] = std::move(backend);
    MF_INFO(Journal::Component::Core, Journal::Context::InputSubsystem,
        "Added input backend: {}", m_backends[type]->get_name());
    return true;
}
References MayaFlux::Journal::Core, MayaFlux::Journal::InputSubsystem, m_backends, m_backends_mutex, MF_ERROR, MF_INFO, MF_WARN, and wire_backend_to_manager().
Referenced by initialize_hid_backend(), and initialize_midi_backend().