MayaFlux: MayaFlux::Buffers::TokenUnitManager::has_audio_unit
has_audio_unit()
bool MayaFlux::Buffers::TokenUnitManager::has_audio_unit (ProcessingToken token) const
Checks if an audio unit exists for the given token.
Parameters
token Processing domain
Returns
True if the unit exists, false otherwise
Definition at line 114 of file TokenUnitManager.cpp.
{
    return m_audio_units.find(token) != m_audio_units.end();
}
References m_audio_units.
Referenced by MayaFlux::Buffers::BufferSupplyMixing::cleanup_completed_routing(), MayaFlux::Buffers::BufferSupplyMixing::clone_audio_buffer_for_channels(), MayaFlux::Buffers::BufferSupplyMixing::fill_audio_from_interleaved(), MayaFlux::Buffers::BufferSupplyMixing::fill_audio_interleaved(), MayaFlux::Buffers::BufferAccessControl::remove_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_channel(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_token(), MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer(), MayaFlux::Buffers::BufferSupplyMixing::route_buffer_to_channel(), MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor(), MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to(), and MayaFlux::Buffers::BufferSupplyMixing::update_routing_states_for_cycle().