MayaFlux: MayaFlux::Core::DescriptorUpdateBatch::sampler
sampler()
DescriptorUpdateBatch & MayaFlux::Core::DescriptorUpdateBatch::sampler (uint32_t binding, vk::Sampler sampler)
Definition at line 718 of file VKDescriptorManager.cpp.
{
    vk::DescriptorImageInfo image_info;
    image_info.sampler = sampler;
    image_info.imageView = nullptr;
    image_info.imageLayout = vk::ImageLayout::eUndefined;
    m_image_infos.push_back(image_info);
    vk::WriteDescriptorSet write;
    write.dstSet = m_set;
    write.dstBinding = binding;
    write.dstArrayElement = 0;
    write.descriptorCount = 1;
    write.descriptorType = vk::DescriptorType::eSampler;
    write.pImageInfo = &m_image_infos.back();
    m_writes.push_back(write);
    return *this;
}
References m_image_infos, m_set, m_writes, and sampler().
Referenced by combined_image_sampler(), sampler(), and storage_image().