MayaFlux: MayaFlux::Portal::Forma::Inspector::root_node
root_node() [2/2]
InspectResult MayaFlux::Portal::Forma::Inspector::root_node (Nodes::ProcessingToken token, uint32_t channel, Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F, int depth = 0)
Inspect a single RootNode for a specific token and channel.
Header is "root [ch N]" for AUDIO_RATE or "root" for all other tokens. Body row exposes live node count from RootNode::get_node_size(). Each registered node is expanded via node() as a child. Networks for the token/channel are appended after the node children.
Definition at line 132 of file NodeQuery.cpp.
{
    auto& root = m_ngm.get_root_node(token, channel);
    const float ind = x_min + static_cast<float>(depth) * k_inspect_indent;
    const std::string header_label = token == Nodes::ProcessingToken::AUDIO_RATE
        ? "root [ch " + std::to_string(channel) + "]"
        : "root";
    std::vector<ValueSpec> values {
        ValueSpec {
            .label = "nodes",
            .reader = [&root] { return std::to_string(root.get_node_size()); },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), ind, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), header_label, dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(values.size());
    for (const auto& spec : values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto group = make_value_group(values, std::move(hbuf), rbufs,
        surface, cursor, ind, x_max, row_h, false);
    InspectResult result;
    result.group = std::move(group);
    for (const auto& n : root.nodes()) {
        if (!n)
            continue;
        auto node_result = node(
            n, surface, cursor,
            x_min, x_max, row_h, depth + 1);
        surface.layer().relate(result.group.header.header_id, node_result.group.header.header_id);
        result.children.push_back(std::move(node_result));
    }
    return result;
}
References MayaFlux::Nodes::AUDIO_RATE, MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Nodes::NodeGraphManager::get_root_node(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::k_inspect_indent, MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Portal::Forma::Surface::layer(), m_ngm, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), node(), MayaFlux::Portal::Forma::Layer::relate(), MayaFlux::Portal::Forma::row_pixel_dims(), and MayaFlux::Portal::Forma::Surface::window().
Referenced by node_graph_manager(), and root_node().