MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::to_vulkan_stage
to_vulkan_stage()
vk::ShaderStageFlagBits MayaFlux::Portal::Graphics::ShaderFoundry::to_vulkan_stage (ShaderStage stage) static
Convert Portal ShaderStage to Vulkan ShaderStageFlagBits.
Definition at line 1227 of file ShaderFoundry.cpp.
{
    switch (stage) {
    case ShaderStage::COMPUTE:
        return vk::ShaderStageFlagBits::eCompute;
    case ShaderStage::VERTEX:
        return vk::ShaderStageFlagBits::eVertex;
    case ShaderStage::FRAGMENT:
        return vk::ShaderStageFlagBits::eFragment;
    case ShaderStage::GEOMETRY:
        return vk::ShaderStageFlagBits::eGeometry;
    case ShaderStage::TESS_CONTROL:
        return vk::ShaderStageFlagBits::eTessellationControl;
    case ShaderStage::TESS_EVALUATION:
        return vk::ShaderStageFlagBits::eTessellationEvaluation;
    case ShaderStage::MESH:
        return vk::ShaderStageFlagBits::eMeshEXT;
    case ShaderStage::TASK:
        return vk::ShaderStageFlagBits::eTaskEXT;
    default:
        return vk::ShaderStageFlagBits::eCompute;
    }
}
References MayaFlux::Portal::Graphics::COMPUTE, MayaFlux::Portal::Graphics::FRAGMENT, MayaFlux::Portal::Graphics::GEOMETRY, MayaFlux::Portal::Graphics::MESH, MayaFlux::Portal::Graphics::TASK, MayaFlux::Portal::Graphics::TESS_CONTROL, MayaFlux::Portal::Graphics::TESS_EVALUATION, and MayaFlux::Portal::Graphics::VERTEX.
Referenced by compile_from_file(), compile_from_source(), and compile_from_spirv().