MayaFlux: MayaFlux::Nodes::Network::ParticleNetwork::initialize
initialize()
void MayaFlux::Nodes::Network::ParticleNetwork::initialize () override virtual
Called once before first process_batch()
Use for expensive one-time initialization:
Building neighbor maps
Allocating buffers
Computing lookup tables
Reimplemented from MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 52 of file ParticleNetwork.cpp.
{
    initialize_particle_positions(m_init_mode);
    if (m_topology == Topology::SPATIAL) {
        rebuild_spatial_neighbors();
    } else if (m_topology == Topology::GRID_2D) {
        auto grid_size = static_cast<size_t>(std::sqrt(m_particles.size()));
        m_neighbor_map = build_grid_2d_neighbors(grid_size, grid_size);
    } else if (m_topology == Topology::RING) {
        m_neighbor_map = build_ring_neighbors(m_particles.size());
    } else if (m_topology == Topology::CHAIN) {
        m_neighbor_map = build_chain_neighbors(m_particles.size());
    }
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "Initialized ParticleNetwork: {} particles, topology={}",
        m_particles.size(), static_cast<int>(m_topology));
}
References MayaFlux::Nodes::Network::NodeNetwork::build_chain_neighbors(), MayaFlux::Nodes::Network::NodeNetwork::build_grid_2d_neighbors(), MayaFlux::Nodes::Network::NodeNetwork::build_ring_neighbors(), MayaFlux::Nodes::Network::NodeNetwork::CHAIN, MayaFlux::Nodes::Network::NodeNetwork::GRID_2D, initialize_particle_positions(), m_init_mode, m_neighbor_map, m_particles, MayaFlux::Nodes::Network::NodeNetwork::m_topology, MF_DEBUG, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, rebuild_spatial_neighbors(), MayaFlux::Nodes::Network::NodeNetwork::RING, and MayaFlux::Nodes::Network::NodeNetwork::SPATIAL.