MayaFlux: MayaFlux::Nodes::GpuSync::PathGeneratorNode::compute_frame
compute_frame()
void MayaFlux::Nodes::GpuSync::PathGeneratorNode::compute_frame () override virtual
Compute frame - generates interpolated vertices from control points.
Implements MayaFlux::Nodes::GpuSync::GpuSync.
Definition at line 465 of file PathGeneratorNode.cpp.
{
    if (m_control_points.empty() && m_draw_vertices.empty() && m_completed_draws.empty()) {
        resize_vertex_buffer(0);
        return;
    }
    if (m_geometry_dirty) {
        regenerate_geometry();
        m_geometry_dirty = false;
    }
    if (!m_vertex_data_dirty) {
        return;
    }
    m_combined_cache.clear();
    m_combined_cache.reserve(m_vertices.size() + m_completed_draws.size() + m_draw_vertices.size());
    m_combined_cache.insert(m_combined_cache.end(), m_vertices.begin(), m_vertices.end());
    m_combined_cache.insert(m_combined_cache.end(), m_completed_draws.begin(), m_completed_draws.end());
    m_combined_cache.insert(m_combined_cache.end(), m_draw_vertices.begin(), m_draw_vertices.end());
    if (m_combined_cache.empty()) {
        resize_vertex_buffer(0);
        return;
    }
#ifdef MAYAFLUX_PLATFORM_MACOS
    std::vector<LineVertex> expanded = expand_lines_to_triangles(m_combined_cache);
    set_vertices<LineVertex>(std::span { expanded.data(), expanded.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(expanded.size());
    set_vertex_layout(*layout);
#else
    set_vertices<LineVertex>(std::span { m_combined_cache.data(), m_combined_cache.size() });
    auto layout = get_vertex_layout();
    layout->vertex_count = static_cast<uint32_t>(m_combined_cache.size());
    set_vertex_layout(*layout);
#endif
}
References MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout(), m_combined_cache, m_completed_draws, m_control_points, m_draw_vertices, m_geometry_dirty, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, m_vertices, regenerate_geometry(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout().