MayaFlux: MayaFlux::Journal::Archivist::instance
instance()
Archivist & MayaFlux::Journal::Archivist::instance () static
Get the singleton instance of the Archivist.
Returns
Reference to the Archivist instance.
Definition at line 352 of file Archivist.cpp.
{
    static Archivist archivist;
    return archivist;
}
Referenced by MayaFlux::Journal::error(), MayaFlux::Journal::error(), MayaFlux::Journal::error_rethrow(), MayaFlux::Journal::fatal(), MayaFlux::Journal::fatal(), MayaFlux::Journal::print(), MayaFlux::Journal::print(), MayaFlux::Journal::scribe(), MayaFlux::Journal::scribe(), MayaFlux::Journal::scribe_rt(), MayaFlux::Journal::scribe_rt(), MayaFlux::Config::set_journal_severity(), shutdown(), MayaFlux::Config::sink_journal_to_console(), and MayaFlux::Config::store_journal_entries().