MayaFlux: MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer
resize_vertex_buffer()
void MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer (uint32_t vertex_count, bool preserve_data = false)
Resize vertex buffer to hold specified number of vertices.
Parameters
vertex_count Number of vertices
preserve_data If true, keep existing data; if false, clear buffer
Allocates/reallocates buffer to hold vertex_count vertices at current stride. If stride is 0, logs error and does nothing.
Definition at line 20 of file GeometryWriterNode.cpp.
{
    if (m_vertex_stride == 0) {
        MF_ERROR(Journal::Component::Nodes, Journal::Context::NodeProcessing,
            "Cannot resize vertex buffer: stride is 0. Call set_vertex_stride() first");
        return;
    }
    size_t new_size_bytes = static_cast<size_t>(vertex_count) * m_vertex_stride;
    if (!preserve_data) {
        m_vertex_buffer.clear();
        m_vertex_buffer.resize(new_size_bytes, 0.0F);
    } else if (m_vertex_buffer.size() < new_size_bytes) {
        m_vertex_buffer.resize(new_size_bytes, 0.0F);
    } else if (m_vertex_buffer.size() > new_size_bytes) {
        m_vertex_buffer.resize(new_size_bytes);
    }
    m_vertex_count = vertex_count;
    m_needs_layout_update = true;
    m_vertex_data_dirty = true;
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "GeometryWriterNode: Resized vertex buffer to {} vertices ({} bytes total)",
        vertex_count, new_size_bytes * sizeof(float));
}
References m_needs_layout_update, m_vertex_buffer, m_vertex_count, m_vertex_data_dirty, m_vertex_stride, MF_DEBUG, MF_ERROR, MayaFlux::Journal::NodeProcessing, and MayaFlux::Journal::Nodes.
Referenced by clear_and_resize(), MayaFlux::Nodes::GpuSync::MeshWriterNode::compute_frame(), MayaFlux::Nodes::GpuSync::PathGeneratorNode::compute_frame(), MayaFlux::Nodes::GpuSync::PointCollectionNode::compute_frame(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), and MayaFlux::Nodes::GpuSync::PointNode::PointNode().