MayaFlux: MayaFlux::Buffers::VKBuffer::get_data
get_data()
std::vector< Kakshya::DataVariant > MayaFlux::Buffers::VKBuffer::get_data ()
Read buffer contents as Kakshya DataVariant.
For host-visible buffers this returns a single DataVariant containing the raw bytes. For device-local buffers this warns and returns empty — a BufferDownloadProcessor should be used to read GPU-only memory.
Returns
Vector of DataVariant objects representing buffer contents.
Definition at line 89 of file VKBuffer.cpp.
{
    if (!is_initialized()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "Cannot get_data from uninitialized VKBuffer");
        return {};
    }
    if (is_host_visible() && m_resources.mapped_ptr) {
        mark_invalid_range(0, m_size_bytes);
        std::vector<uint8_t> raw_bytes(m_size_bytes);
        std::memcpy(raw_bytes.data(), m_resources.mapped_ptr, m_size_bytes);
        return { raw_bytes };
    }
    MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
        "get_data() on device-local buffer requires BufferDownloadProcessor");
    return {};
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, is_host_visible(), is_initialized(), m_resources, m_size_bytes, MayaFlux::Buffers::VKBufferResources::mapped_ptr, mark_invalid_range(), and MF_WARN.
Referenced by clone_to().