MayaFlux: MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork
ModalNetwork() [2/2]
MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork (const std::vector< double > & frequency_ratios, double fundamental = 220.0, double base_decay = 1.0)
Create modal network with custom frequency ratios.
Parameters
frequency_ratios Vector of frequency multipliers relative to fundamental
fundamental Base frequency in Hz
base_decay Base decay time in seconds
Definition at line 25 of file ModalNetwork.cpp.
    : m_spectrum(Spectrum::CUSTOM)
    , m_fundamental(fundamental)
{
    set_output_mode(OutputMode::AUDIO_SINK);
    set_topology(Topology::INDEPENDENT);
    initialize_modes(frequency_ratios, base_decay);
}
References MayaFlux::Nodes::Network::NodeNetwork::AUDIO_SINK, MayaFlux::Nodes::Network::NodeNetwork::INDEPENDENT, initialize_modes(), MayaFlux::Nodes::Network::NodeNetwork::set_output_mode(), and MayaFlux::Nodes::Network::NodeNetwork::set_topology().