MayaFlux: MayaFlux::Nexus::Agent::invoke_influence
invoke_influence()
void MayaFlux::Nexus::Agent::invoke_influence (const InfluenceContext & ctx) const inline
Invoke the influence function with the supplied context.
Parameters
ctx Populated context for this commit.
Definition at line 279 of file Agent.hpp.
    {
        if (m_influence_fn) {
            m_influence_fn(ctx);
        }
        dispatch_audio_sinks(m_audio_sinks, ctx);
        dispatch_render_sinks(m_render_sinks, ctx);
        if (m_influence_ubo)
            upload_influence_ubo(ctx);
    }
References MayaFlux::Nexus::dispatch_audio_sinks(), MayaFlux::Nexus::dispatch_render_sinks(), m_audio_sinks, m_influence_fn, m_influence_ubo, m_render_sinks, and upload_influence_ubo().