MayaFlux: MayaFlux::Buffers::VKBuffer::get_device_address
get_device_address()
uint64_t MayaFlux::Buffers::VKBuffer::get_device_address () const
Get the Vulkan device address for this buffer (if applicable)
Returns
64-bit device address, or 0 if not BDA-capable or not initialized
Only buffers created with Usage::UNIFORM_BDA or Usage::STORAGE_BDA and registered with the backend will return a valid device address. This is used by processors that need to bind buffers via device address (e.g., for ray tracing or bindless access).
Definition at line 49 of file VKBuffer.cpp.
{
    if (!is_initialized()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "Cannot get device address of uninitialized VKBuffer");
        return 0;
    }
    if (m_usage != Usage::UNIFORM_BDA && m_usage != Usage::STORAGE_BDA) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "get_device_address() called on buffer without BDA usage flags");
        return 0;
    }
    auto* buffer_service = Registry::BackendRegistry::instance()
                               .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferManagement,
            std::source_location::current(),
            "Cannot query buffer device address: BufferService not available");
    }
    auto shared_this = std::const_pointer_cast<VKBuffer>(
        std::static_pointer_cast<const VKBuffer>(shared_from_this()));
    return buffer_service->get_buffer_device_address(
        std::static_pointer_cast<void>(shared_this));
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), is_initialized(), m_usage, MF_WARN, STORAGE_BDA, and UNIFORM_BDA.