MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::compile
compile()
std::shared_ptr< Core::VKShaderModule > MayaFlux::Portal::Graphics::ShaderFoundry::compile (const ShaderSource & shader_source)
Compile shader from ShaderSource descriptor.
Parameters
shader_source Shader descriptor (path or source + type + stage)
Returns
Compiled shader module, or nullptr on failure
Unified interface that dispatches to appropriate compile method. Useful for abstracted shader loading pipelines.
Definition at line 266 of file ShaderFoundry.cpp.
{
    switch (shader_source.type) {
    case ShaderSource::SourceType::GLSL_FILE:
        return compile_from_file(shader_source.content, shader_source.stage, shader_source.entry_point);
    case ShaderSource::SourceType::GLSL_STRING:
        return compile_from_source(shader_source.content, shader_source.stage, shader_source.entry_point);
    case ShaderSource::SourceType::SPIRV_FILE:
        return compile_from_spirv(shader_source.content, shader_source.stage, shader_source.entry_point);
    case ShaderSource::SourceType::SPIRV_ASM:
        return compile_from_spirv_asm(shader_source.content, shader_source.stage, shader_source.entry_point);
    default:
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Unknown shader source type");
        return nullptr;
    }
}
References compile_from_file(), compile_from_source(), compile_from_spirv(), compile_from_spirv_asm(), MayaFlux::Portal::Graphics::ShaderSource::content, MayaFlux::Portal::Graphics::ShaderSource::entry_point, MayaFlux::Portal::Graphics::ShaderSource::GLSL_FILE, MayaFlux::Portal::Graphics::ShaderSource::GLSL_STRING, MF_ERROR, MayaFlux::Journal::Portal, MayaFlux::Journal::ShaderCompilation, MayaFlux::Portal::Graphics::ShaderSource::SPIRV_ASM, MayaFlux::Portal::Graphics::ShaderSource::SPIRV_FILE, MayaFlux::Portal::Graphics::ShaderSource::stage, and MayaFlux::Portal::Graphics::ShaderSource::type.