MayaFlux: MayaFlux::Buffers::ShaderProcessor::initialize_shader
initialize_shader()
void MayaFlux::Buffers::ShaderProcessor::initialize_shader () private
Definition at line 392 of file ShaderProcessor.cpp.
{
    on_before_compile(m_config.shader_path);
    auto& foundry = Portal::Graphics::get_shader_foundry();
    m_shader_id = foundry.load_shader(m_config.shader_path, m_config.stage, m_config.entry_point);
    if (m_shader_id == Portal::Graphics::INVALID_SHADER) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Failed to load shader: {}", m_config.shader_path);
        return;
    }
    on_shader_loaded(m_shader_id);
    MF_INFO(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Shader loaded: {} (ID: {})", m_config.shader_path, m_shader_id);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::ShaderProcessorConfig::entry_point, MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_SHADER, m_config, m_shader_id, MF_ERROR, MF_INFO, on_before_compile(), on_shader_loaded(), MayaFlux::Buffers::ShaderProcessorConfig::shader_path, and MayaFlux::Buffers::ShaderProcessorConfig::stage.
Referenced by processing_function(), set_config(), and set_shader().