MayaFlux: MayaFlux::Nexus::Fabric::add_expanse
add_expanse()
uint32_t MayaFlux::Nexus::Fabric::add_expanse (std::shared_ptr< Expanse > expanse)
Register an Expanse for per-commit crossing detection.
On each commit, after the snapshot publishes, the Expanse's predicate is evaluated against every indexed position and membership is diffed against the previous commit. Entry and exit actions fire for the difference.
Parameters
expanse Expanse to register. Its id is assigned here.
Returns
Stable id assigned to the Expanse.
Definition at line 100 of file Fabric.cpp.
{
    const uint32_t id = m_next_id++;
    expanse->m_id = id;
    m_expanses.try_emplace(id, std::move(expanse));
    return id;
}
References id(), m_expanses, and m_next_id.
Referenced by MayaFlux::Nexus::StateDecoder::decode(), and MayaFlux::Nexus::StateDecoder::reconstruct().