MayaFlux: MayaFlux::Core::GraphicsSubsystem::process
process()
void MayaFlux::Core::GraphicsSubsystem::process ()
Unified processing callback (alternative to separate methods)
This is called once per frame and handles all processing:
Visual nodes (VISUAL_RATE)
Graphics buffers (GRAPHICS_BACKEND)
Frame coroutines (FRAME_ACCURATE)
Can be overridden or extended via hooks.
Definition at line 277 of file GraphicsSubsystem.cpp.
{
    if (!m_handle) {
        return;
    }
    for (auto& [name, hook] : m_handle->pre_process_hooks) {
        hook(1);
    }
    m_handle->tasks.process(1);
    m_handle->nodes.process(1);
    m_handle->buffers.process(1);
    register_windows_for_processing();
    m_backend->handle_window_resize();
    render_all_windows();
    m_handle->windows.process();
    cleanup_closed_windows();
    for (auto& [name, hook] : m_handle->post_process_hooks) {
        hook(1);
    }
}
References MayaFlux::Core::SubsystemProcessingHandle::buffers, cleanup_closed_windows(), m_backend, m_handle, MayaFlux::Core::SubsystemProcessingHandle::nodes, MayaFlux::Core::SubsystemProcessingHandle::post_process_hooks, MayaFlux::Core::SubsystemProcessingHandle::pre_process_hooks, MayaFlux::Core::WindowManagerHandle::process(), MayaFlux::Core::NodeProcessingHandle::process(), MayaFlux::Core::BufferProcessingHandle::process(), MayaFlux::Core::TaskSchedulerHandle::process(), register_windows_for_processing(), render_all_windows(), MayaFlux::Core::SubsystemProcessingHandle::tasks, and MayaFlux::Core::SubsystemProcessingHandle::windows.
Referenced by graphics_thread_loop().