MayaFlux: MayaFlux::Nodes::RootNode::preprocess
preprocess()
bool MayaFlux::Nodes::RootNode::preprocess ()
Checks if the root node can process pending operations.
Returns
True if successful
This method can be used to determine if the root node is in the middle of a processing cycle. If true, queued pending operations will be executed
Definition at line 87 of file RootNode.cpp.
{
    if (m_skip_state_management)
        return true;
    bool expected = false;
    if (m_request_terminate.load(std::memory_order_acquire)) {
        return false;
    }
    if (!m_is_processing.compare_exchange_strong(expected, true,
            std::memory_order_acquire, std::memory_order_relaxed)) {
        return false;
    }
    if (m_pending_count.load(std::memory_order_relaxed) > 0) {
        process_pending_operations();
    }
    return true;
}
References m_is_processing, m_pending_count, m_request_terminate, m_skip_state_management, and process_pending_operations().
Referenced by process_frame(), and process_sample().