MayaFlux: MayaFlux::Buffers::VKBuffer::set_processing_chain
set_processing_chain()
void MayaFlux::Buffers::VKBuffer::set_processing_chain (std::shared_ptr< Buffers::BufferProcessingChain > chain, bool force = false) override virtual
Replace the buffer's processing chain.
Parameters
chain New processing chain to assign.
force If true, replaces existing chain even if one is set.
Implements MayaFlux::Buffers::Buffer.
Definition at line 286 of file VKBuffer.cpp.
{
    if (m_processing_chain && !force) {
        m_processing_chain->merge_chain(chain);
        return;
    }
    m_processing_chain = chain;
}
References m_processing_chain.
Referenced by MayaFlux::Buffers::TextureBindBuffer::setup_processors(), MayaFlux::Buffers::GeometryBuffer::setup_processors(), MayaFlux::Buffers::NetworkGeometryBuffer::setup_processors(), and MayaFlux::Buffers::TextureBuffer::setup_processors().