MayaFlux: MayaFlux::IO::VideoEncodeContext::encode_frame
encode_frame()
bool MayaFlux::IO::VideoEncodeContext::encode_frame (const uint8_t * src_data, size_t src_size, uint32_t src_width, uint32_t src_height, FFmpegMuxContext & mux)
Encode one raw pixel frame into the mux context.
Converts src_data from the source pixel format to the encoder's required format via SwsContext, stamps the monotonic PTS, and submits the frame to the encoder. Drains any available packets to the mux immediately.
src_data must be a packed, row-major image of exactly width * height * bytes_per_pixel(src_pixel_format) bytes as delivered by the swapchain readback. No stride padding is expected; the source linesize is computed as width * bytes_per_pixel.
Non-blocking with respect to the observer thread: this runs exclusively on the VideoFileWriter worker thread.
Parameters
src_data Pointer to the first byte of the packed source image.
src_size Byte count of src_data; must equal width * height * bpp.
mux Mux context to receive encoded packets.
Returns
True on success.
Definition at line 255 of file VideoEncodeContext.cpp.
{
    if (!is_valid())
        return false;
    if (src_width == 0 || src_height == 0) {
        m_last_error = "encode_frame: zero source dimensions";
        return false;
    }
    const size_t expected = static_cast<size_t>(src_width)
        * static_cast<size_t>(src_height)
        * static_cast<size_t>(m_src_src_bpp);
    if (src_size < expected) {
        m_last_error = "encode_frame: src_size too small for declared dimensions";
        return false;
    }
    if (av_frame_make_writable(m_scratch_frame) < 0) {
        m_last_error = "av_frame_make_writable failed";
        return false;
    }
    if (static_cast<int>(src_width) != m_cached_src_width
        || static_cast<int>(src_height) != m_cached_src_height) {
        sws_freeContext(sws_context);
        sws_context = sws_getContext(
            static_cast<int>(src_width),
            static_cast<int>(src_height),
            m_src_pixel_fmt,
            codec_context->width,
            codec_context->height,
            codec_context->pix_fmt,
            SWS_BILINEAR,
            nullptr, nullptr, nullptr);
        if (!sws_context) {
            m_last_error = "sws_getContext failed on dimension change";
            return false;
        }
        m_cached_src_width = static_cast<int>(src_width);
        m_cached_src_height = static_cast<int>(src_height);
    }
    const int src_stride = static_cast<int>(src_width) * m_src_src_bpp;
    sws_scale(sws_context,
        &src_data, &src_stride,
        0, static_cast<int>(src_height),
        m_scratch_frame->data, m_scratch_frame->linesize);
    m_scratch_frame->pts = m_pts++;
    if (avcodec_send_frame(codec_context, m_scratch_frame) < 0) {
        m_last_error = "avcodec_send_frame failed";
        return false;
    }
    return drain_packets(mux);
}
References codec_context, drain_packets(), is_valid(), m_cached_src_height, m_cached_src_width, m_last_error, m_pts, m_scratch_frame, m_src_pixel_fmt, m_src_src_bpp, and sws_context.
Referenced by MayaFlux::IO::VideoFileWriter::worker_loop().