MayaFlux: MayaFlux::Nodes::Input::InputNode::notify_tick
notify_tick()
void MayaFlux::Nodes::Input::InputNode::notify_tick (double value) override protected virtual
Notify callbacks (minimal for InputNode)
InputNodes fire callbacks sparingly - the input event IS the notification. Override if you need per-sample callbacks (rare for input).
Implements MayaFlux::Nodes::Node.
Reimplemented in MayaFlux::Nodes::Input::MIDINode.
Definition at line 195 of file InputNode.cpp.
{
    update_context(value);
    auto& ctx = get_last_context();
    for (auto& callback : m_callbacks) {
        callback(ctx);
    }
    for (auto& [callback, condition] : m_conditional_callbacks) {
        if (condition(ctx)) {
            callback(ctx);
        }
    }
    for (auto& cb : m_input_callbacks) {
        bool should_fire = false;
        switch (cb.event_type) {
        case InputEventType::TICK:
            should_fire = true;
            break;
        case InputEventType::VALUE_CHANGE: {
            double epsilon = cb.threshold.value_or(0.0001);
            should_fire = std::abs(value - m_previous_value) > epsilon;
            break;
        }
        case InputEventType::THRESHOLD_RISING:
            should_fire = (m_previous_value < cb.threshold.value() && value >= cb.threshold.value());
            break;
        case InputEventType::THRESHOLD_FALLING:
            should_fire = (m_previous_value >= cb.threshold.value() && value < cb.threshold.value());
            break;
        case InputEventType::RANGE_ENTER: {
            auto [min, max] = cb.range.value();
            bool in_range_now = (value >= min && value <= max);
            should_fire = (!m_was_in_range && in_range_now);
            m_was_in_range = in_range_now;
            break;
        }
        case InputEventType::RANGE_EXIT: {
            auto [min, max] = cb.range.value();
            bool in_range_now = (value >= min && value <= max);
            should_fire = (m_was_in_range && !in_range_now);
            m_was_in_range = in_range_now;
            break;
        }
        case InputEventType::BUTTON_PRESS:
            should_fire = (m_previous_value < 0.5 && value >= 0.5);
            break;
        case InputEventType::BUTTON_RELEASE:
            should_fire = (m_previous_value >= 0.5 && value < 0.5);
            break;
        case InputEventType::CONDITIONAL:
            should_fire = cb.condition && cb.condition.value()(ctx);
            break;
        }
        if (should_fire) {
            cb.callback(ctx);
        }
    }
    m_previous_value = value;
}
References MayaFlux::Nodes::Input::BUTTON_PRESS, MayaFlux::Nodes::Input::BUTTON_RELEASE, MayaFlux::Nodes::Input::CONDITIONAL, get_last_context(), MayaFlux::Nodes::Node::m_callbacks, MayaFlux::Nodes::Node::m_conditional_callbacks, m_input_callbacks, m_previous_value, m_was_in_range, MayaFlux::Nodes::Input::RANGE_ENTER, MayaFlux::Nodes::Input::RANGE_EXIT, MayaFlux::Nodes::Input::THRESHOLD_FALLING, MayaFlux::Nodes::Input::THRESHOLD_RISING, MayaFlux::Nodes::Input::TICK, update_context(), and MayaFlux::Nodes::Input::VALUE_CHANGE.
Referenced by MayaFlux::Nodes::Input::MIDINode::notify_tick(), process_input(), and process_sample().