MayaFlux: MayaFlux::Buffers::BufferAccessControl::get_graphics_processing_chain
get_graphics_processing_chain()
std::shared_ptr< BufferProcessingChain > MayaFlux::Buffers::BufferAccessControl::get_graphics_processing_chain (ProcessingToken token)
Gets the processing chain for a graphics token.
Parameters
token Processing domain
Returns
Shared pointer to the processing chain
Definition at line 333 of file BufferAccessControl.cpp.
{
    auto& unit = m_unit_manager.get_or_create_graphics_unit(token);
    return unit.get_chain();
}
References MayaFlux::Buffers::RootGraphicsUnit::get_chain(), MayaFlux::Buffers::TokenUnitManager::get_or_create_graphics_unit(), m_unit_manager, and token.
Referenced by MayaFlux::Buffers::BufferProcessingControl::add_graphics_processor(), and MayaFlux::Buffers::BufferProcessingControl::add_graphics_processor().