MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::reload_shader
reload_shader()
ShaderID MayaFlux::Portal::Graphics::ShaderFoundry::reload_shader (const std::string & filepath)
Hot-reload shader (returns new ID)
Definition at line 423 of file ShaderFoundry.cpp.
{
    invalidate_cache(filepath);
    auto cache_it = m_shader_filepath_cache.find(filepath);
    if (cache_it != m_shader_filepath_cache.end()) {
        destroy_shader(cache_it->second);
        m_shader_filepath_cache.erase(cache_it);
    }
    return load_shader(filepath);
}
References destroy_shader(), invalidate_cache(), load_shader(), and m_shader_filepath_cache.