MayaFlux: MayaFlux::Buffers::NodeBindingsProcessor::update_push_constants_from_nodes
update_push_constants_from_nodes()
void MayaFlux::Buffers::NodeBindingsProcessor::update_push_constants_from_nodes () private
Definition at line 92 of file NodeBindingsProcessor.cpp.
{
    if (m_bindings.empty()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "No node bindings configured for NodeBindingsProcessor");
        return;
    }
    auto& pc_data = get_push_constant_data();
    for (auto& [name, binding] : m_bindings) {
        size_t required_size = binding.push_constant_offset + binding.size;
        if (pc_data.size() < required_size) {
            pc_data.resize(required_size);
        }
        if (!binding.node) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Node binding '{}' has null node", name);
            continue;
        }
        double value {};
        ProcessingMode mode = binding.processing_mode.load(std::memory_order_acquire);
        if (mode == ProcessingMode::INTERNAL) {
            value = Buffers::extract_single_sample(binding.node);
        } else {
            value = binding.node->get_last_output();
        }
        if (binding.size == sizeof(float)) {
            auto float_val = static_cast<float>(value);
            std::memcpy(
                pc_data.data() + binding.push_constant_offset,
                &float_val,
                sizeof(float));
        } else if (binding.size == sizeof(double)) {
            std::memcpy(
                pc_data.data() + binding.push_constant_offset,
                &value,
                sizeof(double));
        }
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::extract_single_sample(), MayaFlux::Buffers::ShaderProcessor::get_push_constant_data(), INTERNAL, m_bindings, MF_RT_ERROR, and MF_WARN.
Referenced by execute_shader().