MayaFlux: MayaFlux::IO::VideoFileReader::set_error
set_error()
void MayaFlux::IO::VideoFileReader::set_error (const std::string & msg) const private
Definition at line 686 of file VideoFileReader.cpp.
{
    std::lock_guard lock(m_error_mutex);
    m_last_error = msg;
    MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
        "VideoFileReader: {}", msg);
}
References MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, m_error_mutex, m_last_error, and MF_ERROR.
Referenced by create_container(), load_into_container(), open(), seek(), and seek_internal().