MayaFlux: MayaFlux::Nodes::Input::MIDINode::extract_value
extract_value()
double MayaFlux::Nodes::Input::MIDINode::extract_value (const Core::InputValue & value) override protected virtual
Extract a scalar value from an InputValue.
Parameters
value The input value to extract from
Returns
Scalar value for smoothing/output
Override in derived classes for specific input types. Default handles SCALAR and MIDI CC values.
Reimplemented from MayaFlux::Nodes::Input::InputNode.
Definition at line 10 of file MIDINode.cpp.
{
    if (value.type != Core::InputValue::Type::MIDI) {
        return m_last_output;
    }
    const auto& midi = value.as_midi();
    m_last_midi_message = midi;
    if (!matches_filters(value)) {
        return m_last_output;
    }
    uint8_t msg_type = midi.type();
    switch (msg_type) {
    case 0x90:
        if (m_config.note_off_only) {
            return m_last_output;
        }
        // Velocity 0 is actually Note Off
        if (midi.data2 == 0 && m_config.note_on_only) {
            return m_last_output;
        }
        return m_config.velocity_curve
            ? m_config.velocity_curve(midi.data2)
            : static_cast<double>(midi.data2) / 127.0;
    case 0x80: // Note Off
        if (m_config.note_on_only) {
            return m_last_output;
        }
        return 0.0;
    case 0xB0: { // Control Change
        double value = static_cast<double>(midi.data2) / 127.0;
        return m_config.invert_cc ? (1.0 - value) : value;
    }
    case 0xE0: {
        // Pitch bend is 14-bit: combine data1 and data2
        int bend_value = (midi.data2 << 7) | midi.data1;
        return (static_cast<double>(bend_value) - 8192.0) / 8192.0;
    }
    case 0xD0: // Channel Pressure (Aftertouch)
    case 0xC0: // Program Change
    default:
        return static_cast<double>(midi.data1) / 127.0;
    }
}
References MayaFlux::Core::InputValue::as_midi(), MayaFlux::Nodes::Input::MIDIConfig::invert_cc, m_config, m_last_midi_message, MayaFlux::Nodes::Node::m_last_output, matches_filters(), MayaFlux::Core::InputValue::MIDI, MayaFlux::Nodes::Input::MIDIConfig::note_off_only, MayaFlux::Nodes::Input::MIDIConfig::note_on_only, MayaFlux::Core::InputValue::MIDIMessage::type(), MayaFlux::Core::InputValue::type, and MayaFlux::Nodes::Input::MIDIConfig::velocity_curve.