MayaFlux: MayaFlux::Kriya::SamplingPipeline::build_for
build_for()
void MayaFlux::Kriya::SamplingPipeline::build_for (uint64_t milliseconds)
Finalize configuration and start processing for a bounded duration.
Converts milliseconds to pipeline cycles via sample rate and buffer size, then starts execution for exactly that many cycles. When the cycle count exhausts, the pipeline stops unconditionally regardless of voice state. Any active voice is cut immediately with no fade or drain.
Must not be called if build() has already been called.
Parameters
milliseconds Duration in milliseconds.
Definition at line 73 of file SamplingPipeline.cpp.
{
    if (m_built)
        return;
    m_mgr.supply_buffer_to(m_buffer,
        Buffers::ProcessingToken::AUDIO_BACKEND, m_channel, 1.0, true);
    m_pipeline >> static_cast<BufferOperation>(m_capture);
    const double seconds = static_cast<double>(milliseconds) / 1000.0;
    const uint64_t cycles = Vruta::seconds_to_blocks(
        seconds, m_mgr.get_sample_rate(), m_mgr.get_buffer_size(Buffers::ProcessingToken::AUDIO_BACKEND));
    m_pipeline->on_complete([this] {
        std::ranges::fill(m_buffer->get_data(), 0.0);
    });
    m_pipeline->execute_buffer_rate(cycles);
    m_built = true;
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::BufferManager::get_buffer_size(), MayaFlux::Buffers::BufferManager::get_sample_rate(), m_buffer, m_built, m_capture, m_channel, m_mgr, m_pipeline, MayaFlux::Vruta::seconds_to_blocks(), and MayaFlux::Buffers::BufferManager::supply_buffer_to().