MayaFlux: MayaFlux::Buffers::NodeTextureBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::NodeTextureBuffer::setup_processors (ProcessingToken token) override virtual
Initialize the buffer, create GPU texture, and setup processors.
Reimplemented from MayaFlux::Buffers::VKBuffer.
Definition at line 44 of file NodeTextureBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<NodeTextureBuffer>(shared_from_this());
    generate_fullscreen_quad();
    auto& loom = Portal::Graphics::get_texture_manager();
    m_gpu_texture = loom.create_2d(
        m_texture_node->get_width(),
        m_texture_node->get_height(),
        Portal::Graphics::ImageFormat::RGBA32F,
        nullptr,
        1);
    if (!m_gpu_texture) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::Init,
            std::source_location::current(),
            "Failed to create GPU texture for NodeTextureBuffer '{}'",
            m_binding_name);
    }
    m_texture_processor = std::make_shared<NodeTextureProcessor>();
    m_texture_processor->set_processing_token(token);
    m_texture_processor->bind_texture_node(
        m_binding_name,
        m_texture_node,
        m_gpu_texture);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
    set_default_processor(m_texture_processor);
    MF_INFO(Journal::Component::Buffers, Journal::Context::Init,
        "NodeTextureBuffer '{}' ready: staging={} bytes, GPU texture={}x{}",
        m_binding_name,
        get_size_bytes(),
        m_texture_node->get_width(),
        m_texture_node->get_height());
}
References MayaFlux::Journal::Buffers, generate_fullscreen_quad(), MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Buffers::VKBuffer::get_size_bytes(), MayaFlux::Portal::Graphics::get_texture_manager(), MayaFlux::Journal::Init, m_binding_name, m_gpu_texture, m_texture_node, m_texture_processor, MF_INFO, MayaFlux::Portal::Graphics::RGBA32F, MayaFlux::Buffers::VKBuffer::set_default_processor(), and MayaFlux::Buffers::VKBuffer::set_processing_chain().