MayaFlux: MayaFlux::Yantra::OperationHelper::setup_operation_buffer
setup_operation_buffer()
template<OperationReadyData T> static auto MayaFlux::Yantra::OperationHelper::setup_operation_buffer (T & input, std::vector< std::vector< double > > & working_buffer) inline static
Setup operation buffer from IO or ComputeData type.
Template Parameters
T IO or ComputeData type
Parameters
input IO container or direct ComputeData
working_buffer Buffer to setup (will be resized)
Returns
Tuple of [working_spans, structure_info]
Definition at line 307 of file OperationHelper.hpp.
    {
        auto [data_spans, structure_info] = extract_structured_double(input);
        if (working_buffer.size() != data_spans.size()) {
            working_buffer.resize(data_spans.size());
        }
        std::vector<std::span<double>> working_spans(working_buffer.size());
        for (size_t i = 0; i < data_spans.size(); i++) {
            working_buffer[i].resize(data_spans[i].size());
            std::ranges::copy(data_spans[i], working_buffer[i].begin());
            working_spans[i] = std::span<double>(working_buffer[i].data(), working_buffer[i].size());
        }
        return std::make_tuple(working_spans, structure_info);
    }
References extract_structured_double().
Referenced by MayaFlux::Yantra::sort_compute_data_extract(), MayaFlux::Yantra::sort_compute_data_extract(), MayaFlux::Yantra::transform_auto_correlate_fft(), MayaFlux::Yantra::transform_by_energy(), MayaFlux::Yantra::transform_channel_operation(), MayaFlux::Yantra::transform_convolve(), MayaFlux::Yantra::transform_convolve_with_fir(), MayaFlux::Yantra::transform_cross_correlate(), MayaFlux::Yantra::transform_crossfade_regions(), MayaFlux::Yantra::transform_delay(), MayaFlux::Yantra::transform_fade(), MayaFlux::Yantra::transform_linear(), MayaFlux::Yantra::transform_matrix(), MayaFlux::Yantra::transform_matrix_multichannel(), MayaFlux::Yantra::transform_outliers(), MayaFlux::Yantra::transform_pitch_shift(), MayaFlux::Yantra::transform_polynomial(), MayaFlux::Yantra::transform_power(), MayaFlux::Yantra::transform_regions(), MayaFlux::Yantra::transform_slice(), MayaFlux::Yantra::transform_spectral_filter(), MayaFlux::Yantra::transform_spectral_invert(), MayaFlux::Yantra::transform_time_reverse(), MayaFlux::Yantra::transform_time_stretch(), and MayaFlux::Yantra::transform_window().