MayaFlux: MayaFlux::IO::IOManager::IOManager
IOManager() [1/3]
MayaFlux::IO::IOManager::IOManager (uint64_t sample_rate, uint32_t buffer_size, uint32_t frame_rate, const std::shared_ptr< Buffers::BufferManager > & buffer_manager)
Construct IOManager and register the IOService into BackendRegistry.
Must be constructed before any VideoFileReader::load_into_container() call that should participate in managed dispatch.
Definition at line 50 of file IOManager.cpp.
    : m_sample_rate(sample_rate)
    , m_buffer_size(buffer_size)
    , m_frame_rate(frame_rate)
    , m_buffer_manager(buffer_manager)
{
    m_io_service = std::make_shared<Registry::Service::IOService>();
    m_io_service->request_decode = [this](uint64_t reader_id) {
        dispatch_decode_request(reader_id);
    };
    Registry::BackendRegistry::instance()
        .register_service<Registry::Service::IOService>(
            [svc = m_io_service]() -> void* { return svc.get(); });
    m_io_service->request_frame = [this](uint64_t reader_id) {
        dispatch_frame_request(reader_id);
    };
    STBImageWriter::register_with_registry();
    EXRWriter::register_with_registry();
    MF_INFO(Journal::Component::Core, Journal::Context::Init, "IOManager initialised");
}
References MayaFlux::Journal::Core, dispatch_decode_request(), dispatch_frame_request(), MayaFlux::Journal::Init, MayaFlux::Registry::BackendRegistry::instance(), m_io_service, MF_INFO, MayaFlux::Registry::BackendRegistry::register_service(), MayaFlux::IO::EXRWriter::register_with_registry(), MayaFlux::IO::STBImageWriter::register_with_registry(), and MayaFlux::Registry::Service::IOService::request_frame.