MayaFlux: MayaFlux::IO::FFmpegDemuxContext::close
close()
void MayaFlux::IO::FFmpegDemuxContext::close ()
Close the format context and release all demux resources.
Safe to call multiple times.
Definition at line 55 of file FFmpegDemuxContext.cpp.
{
    if (format_context) {
        avformat_close_input(&format_context);
        format_context = nullptr;
    }
    m_last_error.clear();
}
References format_context, and m_last_error.
Referenced by open(), open_device(), and ~FFmpegDemuxContext().