MayaFlux: MayaFlux::Yantra::GpuResourceManager::dispatch_async
dispatch_async()
Portal::Graphics::FenceID MayaFlux::Yantra::GpuResourceManager::dispatch_async (const std::array< uint32_t, 3 > & groups, const std::vector< GpuBufferBinding > & bindings, const uint8_t * push_constant_data, size_t push_constant_size)
Submit a compute dispatch without blocking.
Records the same command sequence as dispatch() but submits via ShaderFoundry::submit_async instead of submit_and_wait. Returns a FenceID immediately. Readback must be deferred until ShaderFoundry::is_fence_signaled returns true for the returned ID.
Parameters
groups Workgroup counts {x, y, z}.
bindings Binding declarations; output barriers inserted.
push_constant_data Pointer to push constant bytes, or nullptr.
push_constant_size Byte count of push constant data.
Returns
FenceID to poll with ShaderFoundry::is_fence_signaled. Returns INVALID_FENCE if not ready or submission fails.
Definition at line 454 of file GpuResourceManager.cpp.
{
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& compute_press = Portal::Graphics::get_compute_press();
    auto cmd_id = foundry.begin_commands(
        Portal::Graphics::ShaderFoundry::CommandBufferType::COMPUTE);
    compute_press.bind_all(
        cmd_id, m_pipeline_id, m_descriptor_set_ids,
        push_constant_data, push_constant_size);
    compute_press.dispatch(cmd_id, groups[0], groups[1], groups[2]);
    for (size_t i = 0; i < bindings.size(); ++i) {
        const auto et = bindings[i].element_type;
        const bool is_image = et == GpuBufferBinding::ElementType::IMAGE_STORAGE
            || et == GpuBufferBinding::ElementType::IMAGE_SAMPLED;
        const bool is_output = bindings[i].direction == GpuBufferBinding::Direction::OUTPUT
            || bindings[i].direction == GpuBufferBinding::Direction::INPUT_OUTPUT;
        if (is_output && !is_image) {
            foundry.buffer_barrier(
                cmd_id,
                m_impl->buffers[i].buffer,
                vk::AccessFlagBits::eShaderWrite,
                vk::AccessFlagBits::eHostRead,
                vk::PipelineStageFlagBits::eComputeShader,
                vk::PipelineStageFlagBits::eHost);
        }
    }
    return foundry.submit_async(cmd_id);
}
References MayaFlux::Portal::Graphics::ShaderFoundry::COMPUTE, MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, MayaFlux::Yantra::GpuBufferBinding::INPUT_OUTPUT, MayaFlux::is_image(), m_descriptor_set_ids, m_impl, m_pipeline_id, and MayaFlux::Yantra::GpuBufferBinding::OUTPUT.
Referenced by MayaFlux::Yantra::GpuDispatchCore::dispatch_core_async().