MayaFlux: MayaFlux::Buffers::TextureProcessor::update_pixels_if_dirty
update_pixels_if_dirty()
void MayaFlux::Buffers::TextureProcessor::update_pixels_if_dirty () private
Re-upload pixels to GPU if they changed.
Definition at line 178 of file TextureProcessor.cpp.
{
    if (!m_texture_buffer || !m_texture_buffer->m_texture_dirty) {
        return;
    }
    if (!m_texture_buffer->has_texture()) {
        m_texture_buffer->m_gpu_texture = create_gpu_texture();
    }
    const auto& pixel_data = m_texture_buffer->m_pixel_data;
    if (pixel_data.empty()) {
        return;
    }
    auto& loom = Portal::Graphics::get_texture_manager();
    if (m_streaming_mode && !m_stream_staging) {
        m_stream_staging = create_image_staging_buffer(
            m_texture_buffer->get_texture()->get_size_bytes());
    }
    if (m_streaming_mode && m_stream_staging) {
        loom.upload_data(
            m_texture_buffer->get_texture(),
            pixel_data.data(),
            pixel_data.size(),
            m_stream_staging);
    } else {
        loom.upload_data(
            m_texture_buffer->get_texture(),
            pixel_data.data(),
            pixel_data.size());
    }
    m_texture_buffer->m_texture_dirty = false;
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "TextureProcessor: pixel data updated ({} bytes)", pixel_data.size());
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, create_gpu_texture(), MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Portal::Graphics::get_texture_manager(), m_stream_staging, m_streaming_mode, m_texture_buffer, and MF_DEBUG.
Referenced by processing_function().