MayaFlux: MayaFlux::Buffers::BufferManager::process_token
process_token()
void MayaFlux::Buffers::BufferManager::process_token (ProcessingToken token, uint32_t processing_units)
Processes all buffers for a specific token.
Parameters
token Processing domain to process
processing_units Number of processing units (samples for audio, frames for video)
Definition at line 56 of file BufferManager.cpp.
{
    if (token == ProcessingToken::AUDIO_BACKEND || token == ProcessingToken::AUDIO_PARALLEL) {
        process_audio_token_default(token, processing_units);
    }
    if (token == ProcessingToken::GRAPHICS_BACKEND) {
        process_graphics_token_default(token, processing_units);
    }
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::AUDIO_PARALLEL, MayaFlux::Buffers::GRAPHICS_BACKEND, process_audio_token_default(), and process_graphics_token_default().
Referenced by process_all_tokens().