MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::instance
instance()
static ShaderFoundry & MayaFlux::Portal::Graphics::ShaderFoundry::instance () inline static
Definition at line 96 of file ShaderFoundry.hpp.
    {
        static ShaderFoundry compiler;
        return compiler;
    }
Referenced by MayaFlux::Portal::Graphics::get_shader_foundry(), get_vk_shader_module(), MayaFlux::Portal::Graphics::RenderFlow::initialize(), MayaFlux::Portal::Graphics::initialize(), MayaFlux::Portal::Graphics::shutdown(), and MayaFlux::Portal::Graphics::stop().