MayaFlux: MayaFlux::Buffers::ComputeMeshBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::ComputeMeshBuffer::setup_processors (ProcessingToken token) override virtual
Setup processors with a processing token.
Parameters
token ProcessingToken to assign.
For VKBuffer this is a no-op as processors get the token. This is meant for derived classes that need to setup default processors
Reimplemented from MayaFlux::Buffers::VKBuffer.
Definition at line 74 of file ComputeMeshBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<ComputeMeshBuffer>(shared_from_this());
    auto layout = Kakshya::VertexLayout::for_meshes(sizeof(Kakshya::MeshVertex));
    layout.vertex_count = static_cast<uint32_t>(
        worst_case_bytes(m_res_x, m_res_y, m_res_z) / sizeof(Kakshya::MeshVertex));
    set_vertex_layout(layout);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
    if (m_gpu_field) {
        m_prep_processor = std::make_shared<SDFPrepProcessor>(m_res_x, m_res_y, m_res_z);
        m_prep_processor->set_processing_token(token);
        set_default_processor(m_prep_processor);
        m_field_processor = std::make_shared<SDFFieldProcessor>(
            m_prep_processor->grid_buf(),
            m_bounds_min, m_bounds_max,
            m_res_x, m_res_y, m_res_z,
            m_field_shader);
        m_field_processor->set_processing_token(token);
        chain->add_preprocessor(m_field_processor, self);
        m_sdf_processor = std::make_shared<SDFMeshProcessor>(
            m_prep_processor->grid_buf(),
            m_prep_processor->counter_buf(),
            m_bounds_min, m_bounds_max,
            m_res_x, m_res_y, m_res_z,
            m_iso_level);
        m_sdf_processor->set_processing_token(token);
        chain->add_processor(m_sdf_processor, self);
    } else {
        m_sdf_processor = std::make_shared<SDFMeshProcessor>(
            std::move(m_field),
            m_bounds_min, m_bounds_max,
            m_res_x, m_res_y, m_res_z,
            m_iso_level);
        m_sdf_processor->set_processing_token(token);
        set_default_processor(m_sdf_processor);
    }
}
References MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Buffers::VKBuffer::get_processing_chain(), m_bounds_max, m_bounds_min, m_field, m_field_processor, m_field_shader, m_gpu_field, m_iso_level, m_prep_processor, m_res_x, m_res_y, m_res_z, m_sdf_processor, MayaFlux::Buffers::VKBuffer::set_default_processor(), MayaFlux::Buffers::VKBuffer::set_processing_chain(), MayaFlux::Buffers::VKBuffer::set_vertex_layout(), and worst_case_bytes().