MayaFlux: MayaFlux::Kriya::NodeTimer::cancel
cancel()
void MayaFlux::Kriya::NodeTimer::cancel ()
Cancels any currently active node.
This method deactivates any currently active node, disconnecting it from the output channel. If no node is active, this method has no effect.
Definition at line 184 of file Timers.cpp.
{
    if (m_timer.is_active()) {
        cleanup_current_operation();
    }
    m_timer.cancel();
}
References MayaFlux::Kriya::Timer::cancel(), cleanup_current_operation(), MayaFlux::Kriya::Timer::is_active(), and m_timer.
Referenced by play_for(), and play_with_processing().