MayaFlux: MayaFlux::Portal::Text::FontFace::load
load()
bool MayaFlux::Portal::Text::FontFace::load (const std::string & path, FT_Long index = 0)
Load a font file from disk.
Parameters
path Absolute or relative path to a TTF, OTF, or collection file.
index Face index within a collection; 0 for ordinary font files.
Returns
true on success.
Precondition
FreeTypeContext::instance().is_initialized() must be true.
Definition at line 8 of file FontFace.cpp.
{
    unload();
    auto& ctx = TypeFaceFoundry::instance();
    if (!ctx.is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "FontFace::load called before TypeFaceFoundry is initialized");
        return false;
    }
    if (const FT_Error err = FT_New_Face(ctx.get_library(), path.c_str(), index, &m_face);
        err != 0) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "FT_New_Face failed for '{}' (index {}) with error {}",
            path, index, static_cast<int>(err));
        m_face = nullptr;
        return false;
    }
    m_path = path;
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "FontFace loaded: '{}' ({} glyphs)", path, m_face->num_glyphs);
    return true;
}
References MayaFlux::Journal::API, MayaFlux::Portal::Text::TypeFaceFoundry::instance(), m_face, m_path, MF_ERROR, MF_INFO, path(), MayaFlux::Journal::Portal, and unload().