MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::get_num_channels
get_num_channels()
virtual uint32_t MayaFlux::Kakshya::SoundStreamContainer::get_num_channels () const inline virtual
Definition at line 169 of file SoundStreamContainer.hpp.
    {
        return static_cast<uint32_t>(m_structure.get_channel_count());
    }
Referenced by MayaFlux::Kakshya::DynamicSoundStream::create_expanded_data(), MayaFlux::Kakshya::DynamicSoundStream::enable_circular_buffer(), MayaFlux::Kakshya::DynamicSoundStream::ensure_capacity(), MayaFlux::Kakshya::DynamicSoundStream::expand_to(), MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames(), MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames(), MayaFlux::Kakshya::DynamicSoundStream::set_all_data(), MayaFlux::Kakshya::DynamicSoundStream::validate(), MayaFlux::Kakshya::DynamicSoundStream::validate_single_channel(), MayaFlux::Kakshya::DynamicSoundStream::write_frames(), and MayaFlux::Kakshya::DynamicSoundStream::write_frames().