MayaFlux: MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor
set_audio_final_processor()
void MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token)
Sets a final processor for an audio token (applied to all channels)
Parameters
processor Final processor to apply
token Processing domain
Final processors are applied as the last step in the processing chain.
Definition at line 209 of file BufferProcessingControl.cpp.
{
    if (!m_unit_manager.has_audio_unit(token)) {
        return;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    for (uint32_t i = 0; i < unit.channel_count; ++i) {
        auto root_buffer = unit.get_buffer(i);
        auto chain = root_buffer->get_processing_chain();
        chain->add_final_processor(processor, root_buffer);
    }
}
References MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), and m_unit_manager.
Referenced by set_final_processor().