MayaFlux: MayaFlux::Core::Engine::Start
Start()
void MayaFlux::Core::Engine::Start ()
Starts the coordinated processing of all subsystems.
Initiates the processing lifecycle by:
Starting the audio backend and opening streams
Beginning task scheduler execution
Activating node graph processing
Enabling real-time audio I/O
Init() must be called first to prepare all components.
Definition at line 158 of file Engine.cpp.
{
    if (!m_is_initialized) {
        Init();
    }
    m_subsystem_manager->start_all_subsystems();
    Portal::Forma::initialize(m_buffer_manager, m_scheduler, m_event_manager);
}
References Init(), MayaFlux::Portal::Forma::initialize(), m_buffer_manager, m_event_manager, m_is_initialized, m_scheduler, and m_subsystem_manager.
Referenced by MayaFlux::Start().