MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::get_vk_shader_module
get_vk_shader_module()
std::shared_ptr< Core::VKShaderModule > MayaFlux::Portal::Graphics::ShaderFoundry::get_vk_shader_module (ShaderID shader_id) private
Definition at line 1209 of file ShaderFoundry.cpp.
{
    auto& foundry = ShaderFoundry::instance();
    auto it = foundry.m_shaders.find(shader_id);
    if (it != foundry.m_shaders.end()) {
        return it->second.module;
    }
    return nullptr;
}
References instance().
Referenced by MayaFlux::Portal::Graphics::RenderFlow::create_pipeline(), and MayaFlux::Portal::Graphics::ComputePress::create_pipeline().