MayaFlux: MayaFlux::IO::IOManager::save_image
save_image() [3/4]
bool MayaFlux::IO::IOManager::save_image (const std::shared_ptr< Core::VKImage > & image, const std::string & filepath, const IO::ImageWriteOptions & options = {})
Save image data to disk asynchronously.
The source is downloaded from the GPU on the calling thread (must have command queue access) and the encode + disk flush is dispatched to a worker. Returns once the download completes and the encode task is queued; encode/flush failures are logged but do not block the caller.
For synchronous semantics (e.g. shutdown flush, tests) use the IO::save_image / IO::save_texture_buffer free functions in ImageExport.hpp.
The extension of filepath selects the writer via ImageWriterRegistry. Format-variant compatibility is the writer's responsibility (PNG wants uint8, EXR wants float, etc.).
Returns
True if the download succeeded and the encode task was queued.
Definition at line 655 of file IOManager.cpp.
{
    if (!image) {
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
            "save_image: null image");
        return false;
    }
    auto fut = std::async(std::launch::async,
        [image, filepath, options]() -> bool {
            auto data = IO::download_image(image);
            if (!data) {
                MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
                    "save_image task: download failed for '{}'", filepath);
                return false;
            }
            auto writer = IO::ImageWriterRegistry::instance().create_writer(filepath);
            if (!writer) {
                MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
                    "save_image task: no writer registered for '{}'", filepath);
                return false;
            }
            const bool ok = writer->write(filepath, *data, options);
            if (!ok) {
                MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
                    "save_image task: writer failed for '{}': {}",
                    filepath, writer->get_last_error());
            } else {
                MF_INFO(Journal::Component::IO, Journal::Context::FileIO,
                    "save_image task: wrote '{}'", filepath);
            }
            return ok;
        });
    std::lock_guard lock(m_save_tasks_mutex);
    m_save_tasks.push_back(std::move(fut));
    std::erase_if(m_save_tasks, [](std::future<bool>& f) {
        return f.wait_for(std::chrono::seconds(0)) == std::future_status::ready;
    });
    return true;
}
References MayaFlux::IO::ImageWriterRegistry::create_writer(), MayaFlux::IO::download_image(), MayaFlux::Journal::FileIO, image, MayaFlux::IO::ImageWriterRegistry::instance(), MayaFlux::Journal::IO, m_save_tasks, m_save_tasks_mutex, MF_ERROR, and MF_INFO.
Referenced by save_image(), and save_image().