MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::distribute
distribute()
DistributionDecision MayaFlux::Buffers::BufferTokenDistributor::distribute (const std::shared_ptr< Buffer > & buffer, ProcessingToken requested_token) static
Distribute a buffer based on its type and requested token.
Parameters
buffer The buffer to distribute
requested_token The token being requested
Returns
Distribution decision with routing instructions
Definition at line 14 of file BufferTokenDistributor.cpp.
{
    if (!buffer) {
        return DistributionDecision {
            .result = DistributionResult::REJECTED,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_BACKEND,
            .reason = "Null buffer provided"
        };
    }
    if (auto audio = std::dynamic_pointer_cast<AudioBuffer>(buffer)) {
        return decide_audio_buffer(audio, requested_token);
    }
    if (auto vk = std::dynamic_pointer_cast<VKBuffer>(buffer)) {
        return decide_vk_buffer(vk, requested_token);
    }
    return DistributionDecision {
        .result = DistributionResult::REJECTED,
        .transfer_processor = nullptr,
        .transfer_direction = ProcessingToken::AUDIO_BACKEND,
        .reason = "Unknown buffer type"
    };
}
References MayaFlux::Buffers::AUDIO_BACKEND, decide_audio_buffer(), decide_vk_buffer(), MayaFlux::Buffers::REJECTED, and MayaFlux::Buffers::DistributionDecision::result.
Referenced by distribute_with_transfer().