MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::is_initialized
is_initialized()
bool MayaFlux::Portal::Graphics::TextureLoom::is_initialized () const inline
Check if manager is initialized.
Definition at line 106 of file TextureLoom.hpp.
{ return m_backend != nullptr; }
Referenced by create_2d(), create_3d(), create_cubemap(), create_depth_buffer(), create_render_target(), create_storage_image(), download_data(), get_or_create_sampler(), upload_data(), and upload_data().