MayaFlux: MayaFlux::Nodes::Network::ParticleNetwork::update_point_nodes
update_point_nodes()
void MayaFlux::Nodes::Network::ParticleNetwork::update_point_nodes () private
Update PointNode states from physics.
Definition at line 490 of file ParticleNetwork.cpp.
{
    for (auto& particle : m_particles) {
        float speed = glm::length(particle.velocity);
        float normalized_speed = glm::clamp(speed / 10.0F, 0.0F, 1.0F);
        // Map speed to color: blue (slow) → red (fast)
        glm::vec3 color(normalized_speed, 0.3F, 1.0F - normalized_speed);
        particle.point->set_color(color);
        particle.point->compute_frame();
    }
}
References m_particles.
Referenced by initialize_particle_positions(), process_batch(), and reset().