MayaFlux: MayaFlux::IO::ModelReader::load
load()
std::vector< Kakshya::MeshData > MayaFlux::IO::ModelReader::load (const std::string & filepath)
Load all meshes from a file in one call.
Opens, imports, extracts, and closes in a single synchronous operation. Returns an empty vector on failure; check get_last_error().
Parameters
filepath Path to the model file.
Returns
One MeshData per aiMesh in the scene, in scene order.
Definition at line 63 of file ModelReader.cpp.
{
    if (!open(filepath)) {
        return {};
    }
    auto result = extract_meshes();
    close();
    return result;
}
References close(), extract_meshes(), and open().