MayaFlux: MayaFlux::Nodes::GpuSync::GlyphGeometryNode::GlyphGeometryNode
GlyphGeometryNode() [2/2]
MayaFlux::Nodes::GpuSync::GlyphGeometryNode::GlyphGeometryNode (Portal::Text::FontFace & face, uint32_t pixel_size, std::string text, float pen_x = 0.F, float pen_y = 0.F, float tolerance = 0.5F)
Construct from a UTF-8 string with an explicit FontFace.
Parameters
face FontFace to decompose from. Must outlive this node.
pixel_size Glyph size in pixels.
text UTF-8 string to decompose.
pen_x Starting horizontal pen position in pixels.
pen_y Starting vertical pen position in pixels (baseline).
tolerance Bezier flatness tolerance in pixels.
Definition at line 27 of file GlyphGeometryNode.cpp.
    : GeometryWriterNode(0)
    , m_face(&face)
    , m_pixel_size(pixel_size)
    , m_text(std::move(text))
    , m_pen_x(pen_x)
    , m_pen_y(pen_y)
    , m_tolerance(tolerance)
{
    set_vertex_stride(sizeof(Kakshya::LineVertex));
    set_vertex_layout(Kakshya::VertexLayout::for_lines(sizeof(Kakshya::LineVertex)));
    rebuild_outlines();
}
References MayaFlux::Kakshya::VertexLayout::for_lines(), rebuild_outlines(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride().