MayaFlux: MayaFlux::Nodes::NodeGraphManager::register_network_global
register_network_global()
void MayaFlux::Nodes::NodeGraphManager::register_network_global (const std::shared_ptr< Network::NodeNetwork > & network)
Register network globally (like nodes)
Definition at line 596 of file NodeGraphManager.cpp.
{
    if (!is_network_registered(network)) {
        std::stringstream ss;
        ss << "network_" << network.get();
        std::string generated_id = ss.str();
        m_network_registry[generated_id] = network;
        network->set_sample_rate(m_registered_sample_rate);
        network->set_block_size(m_registered_block_size);
    }
}
References is_network_registered(), m_network_registry, m_registered_block_size, and m_registered_sample_rate.
Referenced by add_network(), and route_network_to_channels().