MayaFlux: MayaFlux::IO::CameraReader::start_decode_thread
start_decode_thread()
void MayaFlux::IO::CameraReader::start_decode_thread () private
Definition at line 277 of file CameraReader.cpp.
{
    stop_decode_thread();
    m_decode_stop.store(false);
    m_decode_active.store(true);
    m_decode_thread = std::thread(&CameraReader::decode_thread_func, this);
}
References decode_thread_func(), m_decode_active, m_decode_stop, m_decode_thread, and stop_decode_thread().
Referenced by set_container().