MayaFlux: MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_node
update_from_node()
void MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_node (DescriptorBinding & binding) private
Definition at line 511 of file DescriptorBindingsProcessor.cpp.
{
    if (!binding.node) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Binding has null node");
        return;
    }
    float value {};
    if (binding.processing_mode.load(std::memory_order_acquire) == ProcessingMode::INTERNAL) {
        value = static_cast<float>(Buffers::extract_single_sample(binding.node));
    } else {
        value = static_cast<float>(binding.node->get_last_output());
    }
    Nodes::NodeContext& ctx = binding.node->get_last_context();
    switch (binding.binding_type) {
    case BindingType::SCALAR: {
        ensure_buffer_capacity(binding, sizeof(float));
        upload_to_gpu(&value, sizeof(float), binding.gpu_buffer, nullptr);
        break;
    }
    case BindingType::VECTOR: {
        auto* gpu_vec = dynamic_cast<Nodes::GpuVectorData*>(&ctx);
        if (!gpu_vec || !gpu_vec->has_gpu_data()) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Node context does not provide GpuVectorData");
            return;
        }
        auto data = gpu_vec->gpu_data();
        ensure_buffer_capacity(binding, data.size_bytes());
        upload_to_gpu(data.data(), data.size_bytes(), binding.gpu_buffer, nullptr);
        break;
    }
    case BindingType::MATRIX: {
        auto* gpu_mat = dynamic_cast<Nodes::GpuMatrixData*>(&ctx);
        if (!gpu_mat || !gpu_mat->has_gpu_data()) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Node context does not provide GpuMatrixData");
            return;
        }
        auto data = gpu_mat->gpu_data();
        ensure_buffer_capacity(binding, data.size_bytes());
        upload_to_gpu(data.data(), data.size_bytes(), binding.gpu_buffer, nullptr);
        break;
    }
    case BindingType::STRUCTURED: {
        auto* gpu_struct = dynamic_cast<Nodes::GpuStructuredData*>(&ctx);
        if (!gpu_struct || !gpu_struct->has_gpu_data()) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Node context does not provide GpuStructuredData");
            return;
        }
        auto data = gpu_struct->gpu_data();
        ensure_buffer_capacity(binding, data.size_bytes());
        upload_to_gpu(data.data(), data.size_bytes(), binding.gpu_buffer, nullptr);
        break;
    }
    }
}
References MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::binding_type, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, ensure_buffer_capacity(), MayaFlux::Buffers::extract_single_sample(), MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::gpu_buffer, INTERNAL, MATRIX, MF_RT_ERROR, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::node, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::processing_mode, SCALAR, STRUCTURED, MayaFlux::Buffers::upload_to_gpu(), and VECTOR.
Referenced by update_descriptor_data().