MayaFlux: MayaFlux::Kakshya::WindowContainer::WindowContainer
WindowContainer() [1/3]
MayaFlux::Kakshya::WindowContainer::WindowContainer (std::shared_ptr< Core::Window > window) explicit
Construct from an existing managed window.
Parameters
window Live window whose surface will be addressed as NDData.
Definition at line 13 of file WindowContainer.cpp.
    : m_window(std::move(window))
{
    if (!m_window) {
        error<std::invalid_argument>(
            Journal::Component::Kakshya,
            Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "WindowContainer requires a valid window");
    }
    setup_dimensions();
    create_default_processor();
    MF_INFO(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
        "WindowContainer created for window '{}' ({}x{})",
        m_window->get_create_info().title,
        m_structure.get_width(), m_structure.get_height());
}
References MayaFlux::Journal::ContainerProcessing, create_default_processor(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), MayaFlux::Journal::Kakshya, m_structure, m_window, MF_INFO, and setup_dimensions().