MayaFlux: MayaFlux::Core::BackendResourceManager::cleanup_buffer
cleanup_buffer()
void MayaFlux::Core::BackendResourceManager::cleanup_buffer (const std::shared_ptr< Buffers::VKBuffer > & buffer)
Cleanup a buffer and release associated resources.
Parameters
buffer Shared pointer to the buffer to cleanup
Definition at line 239 of file BackendResoureManager.cpp.
{
    if (!buffer) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Attempted to cleanup null VulkanBuffer");
        return;
    }
    auto it = std::ranges::find(m_managed_buffers, buffer);
    if (it == m_managed_buffers.end()) {
        return;
    }
    auto& res = it->get()->get_buffer_resources();
    if (res.mapped_ptr) {
        m_context.get_device().unmapMemory(res.memory);
    }
    if (res.index_buffer) {
        m_context.get_device().destroyBuffer(res.index_buffer);
    }
    if (res.index_memory) {
        m_context.get_device().freeMemory(res.index_memory);
    }
    if (res.buffer) {
        m_context.get_device().destroyBuffer(res.buffer);
    }
    if (res.memory) {
        m_context.get_device().freeMemory(res.memory);
    }
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "VulkanBuffer cleaned up: {:p}", static_cast<void*>(res.buffer));
    m_managed_buffers.erase(it);
}
References MayaFlux::Journal::Core, MayaFlux::Core::VKContext::get_device(), MayaFlux::Journal::GraphicsBackend, m_context, m_managed_buffers, MF_ERROR, and MF_INFO.
Referenced by cleanup(), download_image_data(), setup_backend_service(), and upload_image_data().