MayaFlux: MayaFlux::Kakshya::WindowContainer::to_image
to_image() [1/2]
std::shared_ptr< Core::VKImage > MayaFlux::Kakshya::WindowContainer::to_image () const
Upload the full surface readback to a new VKImage.
Requires at least one completed readback (processed_data[0] non-empty and of type vector<uint8_t>). A fresh VKImage is created and uploaded on each call via TextureLoom; callers driving a per-frame path should prefer the staging-buffer overload to avoid per-call VkBuffer churn.
Returns
Newly created VKImage, or nullptr on failure.
Definition at line 152 of file WindowContainer.cpp.
{
    std::shared_lock lock(m_data_mutex);
    if (m_processed_data.empty()) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::to_image — no readback data available for '{}'",
            m_window->get_create_info().title);
        return nullptr;
    }
    const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_processed_data[0]);
    if (!pixels || pixels->empty()) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::to_image — processed_data[0] is not uint8_t or is empty for '{}'",
            m_window->get_create_info().title);
        return nullptr;
    }
    const auto fmt = query_surface_format(m_window);
    const auto img_fmt = surface_format_to_image_format(fmt);
    const uint32_t w = m_structure.get_width();
    const uint32_t h = m_structure.get_height();
    auto img = Portal::Graphics::TextureLoom::instance().create_2d(
        w, h, img_fmt, pixels->data());
    if (!img) {
        MF_RT_ERROR(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::to_image — TextureLoom::create_2d failed for '{}'",
            m_window->get_create_info().title);
    }
    return img;
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Portal::Graphics::TextureLoom::create_2d(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), h, MayaFlux::Portal::Graphics::TextureLoom::instance(), MayaFlux::Journal::Kakshya, lock(), m_data_mutex, m_processed_data, m_structure, m_window, MF_RT_ERROR, MF_RT_WARN, pixels, and MayaFlux::Kakshya::query_surface_format().