MayaFlux: MayaFlux::Buffers::VKBufferProcessor::initialize_buffer_service
initialize_buffer_service()
void MayaFlux::Buffers::VKBufferProcessor::initialize_buffer_service () protected
Definition at line 410 of file VKBuffer.cpp.
{
    m_buffer_service = Registry::BackendRegistry::instance()
                           .get_service<Registry::Service::BufferService>();
}
References MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), and m_buffer_service.
Referenced by MayaFlux::Buffers::CompositeGeometryProcessor::CompositeGeometryProcessor(), MayaFlux::Buffers::GeometryBindingsProcessor::GeometryBindingsProcessor(), MayaFlux::Buffers::NetworkGeometryProcessor::NetworkGeometryProcessor(), MayaFlux::Buffers::NodeTextureProcessor::NodeTextureProcessor(), MayaFlux::Buffers::ShaderProcessor::ShaderProcessor(), and MayaFlux::Buffers::TextureProcessor::TextureProcessor().