MayaFlux: MayaFlux::Nodes::RootNode::process_pending_operations
process_pending_operations()
void MayaFlux::Nodes::RootNode::process_pending_operations () private
Processes any pending node registration/unregistration operations.
This method is called after the processing cycle completes to handle any node registration or unregistration requests that came in during processing. It ensures that node collection modifications happen safely between processing cycles, maintaining audio continuity while allowing dynamic changes to the node graph.
Definition at line 206 of file RootNode.cpp.
{
    for (auto& m_pending_op : m_pending_ops) {
        if (m_pending_op.active.load(std::memory_order_acquire)) {
            auto& op = m_pending_op;
            uint32_t state = op.node->m_state.load();
            if (!(state & NodeState::ACTIVE)) {
                m_Nodes.push_back(op.node);
                state &= ~static_cast<uint32_t>(NodeState::INACTIVE);
                state |= static_cast<uint32_t>(NodeState::ACTIVE);
                atomic_set_flag_strong(op.node->m_state, static_cast<NodeState>(state));
            } else if (state & NodeState::PENDING_REMOVAL) {
                auto it = m_Nodes.begin();
                while (it != m_Nodes.end()) {
                    if ((*it).get() == op.node.get()) {
                        it = m_Nodes.erase(it);
                        break;
                    }
                    ++it;
                }
                op.node->reset_processed_state();
                state &= ~static_cast<uint32_t>(NodeState::PENDING_REMOVAL);
                state &= ~static_cast<uint32_t>(NodeState::ACTIVE);
                state |= static_cast<uint32_t>(NodeState::INACTIVE);
                atomic_set_flag_strong(op.node->m_state, static_cast<NodeState>(state));
            }
            op.node.reset();
            op.active.store(false, std::memory_order_release);
            m_pending_count.fetch_sub(1, std::memory_order_relaxed);
        }
    }
}
References MayaFlux::Nodes::ACTIVE, MayaFlux::Nodes::atomic_set_flag_strong(), MayaFlux::Nodes::INACTIVE, m_Nodes, m_pending_count, m_pending_ops, and MayaFlux::Nodes::PENDING_REMOVAL.
Referenced by postprocess(), preprocess(), and terminate_all_nodes().