MayaFlux: MayaFlux::Buffers::NetworkGeometryBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::NetworkGeometryBuffer::setup_processors (ProcessingToken token) override virtual
Initialize the buffer and its processors.
Reimplemented from MayaFlux::Buffers::VKBuffer.
Definition at line 37 of file NetworkGeometryBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<NetworkGeometryBuffer>(shared_from_this());
    m_processor = std::make_shared<NetworkGeometryProcessor>();
    m_processor->set_processing_token(token);
    m_processor->bind_network(
        m_binding_name,
        m_network,
        self);
    set_default_processor(m_processor);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::Init,
        "Setup NetworkGeometryProcessor for '{}' with token {}",
        m_binding_name, static_cast<int>(token));
}
References MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Journal::Init, m_binding_name, m_network, m_processor, MF_DEBUG, MayaFlux::Buffers::VKBuffer::set_default_processor(), and MayaFlux::Buffers::VKBuffer::set_processing_chain().