MayaFlux: MayaFlux::Yantra::VisionAnalyzer::create_pipeline_output
create_pipeline_output()
template<ComputeData InputType = std::vector<Kakshya::DataVariant>, ComputeData OutputType = std::vector<Kakshya::DataVariant>> output_type MayaFlux::Yantra::VisionAnalyzer< InputType, OutputType >::create_pipeline_output (const input_type & input, const Kinesis::Vision::VisionResult & vr, const DataStructureInfo & info) inline private
Definition at line 273 of file VisionAnalyzer.hpp.
    {
        std::vector<Kakshya::DataVariant> out_variants;
        const auto* pix = std::get_if<std::vector<float>>(&vr.pixel_image);
        if (pix && !pix->empty())
            out_variants.emplace_back(*pix);
        output_type out = this->convert_result(
            std::vector<std::vector<double>> {}, info);
        out.data = OperationHelper::reconstruct_from_double<OutputType>({}, info);
        if constexpr (std::is_same_v<OutputType, std::vector<Kakshya::DataVariant>>) {
            out.data = std::move(out_variants);
        }
        out.dimensions = {
            Kakshya::DataDimension::spatial_2d(vr.w, vr.h)
        };
        out.modality = Kakshya::DataModality::IMAGE_2D;
        out.metadata = input.metadata;
        out.metadata["source_analyzer"] = std::string("VisionAnalyzer");
        out.metadata["vision_w"] = vr.w;
        out.metadata["vision_h"] = vr.h;
        return out;
    }
References MayaFlux::Yantra::ComputeOperation< InputType, OutputType >::convert_result(), MayaFlux::Yantra::Datum< T >::data, MayaFlux::Yantra::Datum< T >::dimensions, MayaFlux::Kinesis::Vision::VisionResult::h, MayaFlux::Kakshya::IMAGE_2D, input, MayaFlux::Yantra::Datum< T >::metadata, MayaFlux::Yantra::Datum< T >::modality, MayaFlux::Kinesis::Vision::VisionResult::pixel_image, MayaFlux::Kakshya::DataDimension::spatial_2d(), and MayaFlux::Kinesis::Vision::VisionResult::w.
Referenced by MayaFlux::Yantra::VisionAnalyzer< InputType, OutputType >::analyze_implementation().