MayaFlux: MayaFlux::Portal::Graphics::SamplerForge::instance
instance()
static SamplerForge & MayaFlux::Portal::Graphics::SamplerForge::instance () inline static
Definition at line 32 of file SamplerForge.hpp.
    {
        static SamplerForge factory;
        return factory;
    }
Referenced by MayaFlux::Portal::Graphics::get_sampler_factory(), MayaFlux::Portal::Graphics::initialize(), and MayaFlux::Portal::Graphics::shutdown().