MayaFlux: MayaFlux::Kinesis::Stochastic::Stochastic::fast_uniform
fast_uniform()
double MayaFlux::Kinesis::Stochastic::Stochastic::fast_uniform () inline private noexcept
Definition at line 320 of file Stochastic.hpp.
    {
        m_xorshift_state ^= m_xorshift_state >> 12;
        m_xorshift_state ^= m_xorshift_state << 25;
        m_xorshift_state ^= m_xorshift_state >> 27;
        return static_cast<double>(m_xorshift_state * 0x2545F4914F6CDD1DULL)
            * (1.0 / 18446744073709551616.0);
    }
Referenced by generate_brownian_impl(), generate_colored_noise_impl(), generate_gendy_impl(), and generate_memoryless().