MayaFlux: MayaFlux::Kriya::BufferCapture::with_processing_control
with_processing_control()
BufferCapture & MayaFlux::Kriya::BufferCapture::with_processing_control (ProcessingControl control)
Set processing control strategy.
Parameters
control ProcessingControl strategy (default: AUTOMATIC)
Returns
Reference to this BufferCapture for chaining
Definition at line 19 of file Capture.cpp.
{
    m_processing_control = control;
    return *this;
}
References m_processing_control.
Referenced by MayaFlux::Kriya::CaptureBuilder::auto_processing(), MayaFlux::Kriya::CaptureBuilder::manual_processing(), and MayaFlux::Kriya::CaptureBuilder::on_capture_processing().