MayaFlux: MayaFlux::Core::SubsystemManager::get_validated_handle
get_validated_handle()
SubsystemProcessingHandle * MayaFlux::Core::SubsystemManager::get_validated_handle (SubsystemType type) const
Get processing handle with validation.
Parameters
type Subsystem type
Returns
Valid handle or nullptr if validation fails
Definition at line 256 of file SubsystemManager.cpp.
{
    auto subsystem_it = m_subsystems.find(type);
    if (subsystem_it == m_subsystems.end()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::Runtime,
            "Invalid subsystem type: Subsystem not found.");
        return nullptr;
    }
    auto handle = subsystem_it->second->get_processing_context_handle();
    if (!handle) {
        MF_ERROR(Journal::Component::Core, Journal::Context::Runtime,
            "Invalid processing context handle: Handle is null.");
        return nullptr;
    }
    return handle;
}
References MayaFlux::Journal::Core, m_subsystems, MF_ERROR, and MayaFlux::Journal::Runtime.
Referenced by has_process_hook(), register_process_hook(), and unregister_process_hook().