MayaFlux: MayaFlux::Buffers::InstanceNetworkBuffer::InstanceNetworkBuffer
InstanceNetworkBuffer()
MayaFlux::Buffers::InstanceNetworkBuffer::InstanceNetworkBuffer (std::shared_ptr< Nodes::Network::InstanceNetwork > network, float over_allocate_factor = 1.5F) explicit
Definition at line 15 of file InstanceNetworkBuffer.cpp.
    : VKBuffer(
          estimate_vertex_bytes(network, over_allocate_factor),
          Usage::VERTEX,
          Kakshya::DataModality::VERTEX_POSITIONS_3D)
    , m_network(std::move(network))
{
    if (!m_network) {
        error<std::invalid_argument>(
            Journal::Component::Buffers, Journal::Context::Init,
            std::source_location::current(),
            "InstanceNetworkBuffer: null InstanceNetwork");
    }
    const auto& slots = m_network->slots();
    const Portal::Graphics::PrimitiveTopology topo
        = (!slots.empty() && slots[0].node)
        ? slots[0].node->get_primitive_topology()
        : Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST;
    RenderConfig defaults;
    defaults.topology = topo;
    set_default_render_config(defaults);
    m_render_config = defaults;
    set_needs_depth_attachment(true);
    MF_INFO(Journal::Component::Buffers, Journal::Context::Init,
        "InstanceNetworkBuffer: {} slots, {} bytes estimated",
        m_network->slot_count(), get_size_bytes());
}
References MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::get_size_bytes(), MayaFlux::Journal::Init, m_network, MayaFlux::Buffers::VKBuffer::m_render_config, MF_INFO, MayaFlux::Buffers::VKBuffer::set_default_render_config(), MayaFlux::Buffers::VKBuffer::set_needs_depth_attachment(), MayaFlux::Portal::Graphics::RenderConfig::topology, and MayaFlux::Portal::Graphics::TRIANGLE_LIST.