MayaFlux: MayaFlux::Yantra::OperationHelper::extract_structured_double
extract_structured_double()
template<OperationReadyData T> static std::tuple< std::vector< std::span< double > >, DataStructureInfo > MayaFlux::Yantra::OperationHelper::extract_structured_double (T & compute_data) inline static
Extract structured double data from IO container or direct ComputeData with automatic container handling.
Template Parameters
T OperationReadyData type
Parameters
compute_data or IO container with data and optional container
Returns
Tuple of [spans, structure_info]
Exceptions
std::runtime_error if container required but not provided
Definition at line 215 of file OperationHelper.hpp.
    {
        if constexpr (is_IO<T>::value) {
            DataStructureInfo info {};
            info.original_type = std::type_index(typeid(std::decay_t<decltype(compute_data.data)>));
            info.dimensions = compute_data.dimensions;
            info.modality = compute_data.modality;
            if constexpr (RequiresContainer<std::decay_t<decltype(compute_data.data)>>) {
                if (!compute_data.has_container()) {
                    throw std::runtime_error("Container is required for region-like data extraction but not provided");
                }
                std::vector<std::span<double>> double_data = extract_numeric_data(compute_data.data, compute_data.container.value());
                return std::make_tuple(double_data, info);
            } else {
                std::vector<std::span<double>> double_data = extract_numeric_data(compute_data.data, compute_data.needs_processig());
                return std::make_tuple(double_data, info);
            }
        } else {
            DataStructureInfo info {};
            info.original_type = std::type_index(typeid(T));
            std::vector<std::span<double>> double_data = extract_numeric_data(compute_data);
            auto [dimensions, modality] = infer_structure(compute_data);
            info.dimensions = dimensions;
            info.modality = modality;
            return std::make_tuple(double_data, info);
        }
    }
References extract_numeric_data(), MayaFlux::Yantra::infer_structure(), and MayaFlux::Yantra::DataStructureInfo::original_type.
Referenced by setup_operation_buffer(), MayaFlux::Yantra::transform_auto_correlate_fft(), MayaFlux::Yantra::transform_by_energy(), MayaFlux::Yantra::transform_channel_operation(), MayaFlux::Yantra::transform_convolve(), MayaFlux::Yantra::transform_convolve_with_fir(), MayaFlux::Yantra::transform_cross_correlate(), MayaFlux::Yantra::transform_crossfade_regions(), MayaFlux::Yantra::transform_deconvolve(), MayaFlux::Yantra::transform_delay(), MayaFlux::Yantra::transform_exponential(), MayaFlux::Yantra::transform_fade(), MayaFlux::Yantra::transform_linear(), MayaFlux::Yantra::transform_matrix(), MayaFlux::Yantra::transform_matrix_multichannel(), MayaFlux::Yantra::transform_outliers(), MayaFlux::Yantra::transform_pitch_shift(), MayaFlux::Yantra::transform_polynomial(), MayaFlux::Yantra::transform_power(), MayaFlux::Yantra::transform_regions(), MayaFlux::Yantra::transform_slice(), MayaFlux::Yantra::transform_spectral_filter(), MayaFlux::Yantra::transform_spectral_invert(), MayaFlux::Yantra::transform_time_reverse(), MayaFlux::Yantra::transform_time_stretch(), and MayaFlux::Yantra::transform_window().