MayaFlux: MayaFlux::Nodes::Input::InputNode::extract_value
extract_value()
double MayaFlux::Nodes::Input::InputNode::extract_value (const Core::InputValue & value) protected virtual
Extract a scalar value from an InputValue.
Parameters
value The input value to extract from
Returns
Scalar value for smoothing/output
Override in derived classes for specific input types. Default handles SCALAR and MIDI CC values.
Reimplemented in MayaFlux::Nodes::Input::HIDNode, and MayaFlux::Nodes::Input::MIDINode.
Definition at line 78 of file InputNode.cpp.
{
    switch (value.type) {
    case Core::InputValue::Type::SCALAR:
        return value.as_scalar();
    case Core::InputValue::Type::VECTOR: {
        const auto& vec = value.as_vector();
        return vec.empty() ? m_config.default_value : vec[0];
    }
    case Core::InputValue::Type::MIDI: {
        // Default: treat data2 as 0-127 normalized value
        const auto& midi = value.as_midi();
        return static_cast<double>(midi.data2) / 127.0;
    }
    default:
        return m_config.default_value;
    }
}
References MayaFlux::Core::InputValue::as_midi(), MayaFlux::Core::InputValue::as_scalar(), MayaFlux::Core::InputValue::as_vector(), MayaFlux::Nodes::Input::InputConfig::default_value, m_config, MayaFlux::Core::InputValue::MIDI, MayaFlux::Core::InputValue::SCALAR, MayaFlux::Core::InputValue::type, and MayaFlux::Core::InputValue::VECTOR.
Referenced by process_input().