MayaFlux: MayaFlux::Kakshya::RegionOrganizationProcessor::process
process()
void MayaFlux::Kakshya::RegionOrganizationProcessor::process (const std::shared_ptr< SignalSourceContainer > & container) override virtual
Processes audio data according to the current region organization.
Applies region selection, transitions, and looping as configured.
Parameters
container The signal container to process.
Implements MayaFlux::Kakshya::DataProcessor.
Definition at line 45 of file RegionProcessors.cpp.
{
    if (!container || m_organized_regions.empty()) {
        return;
    }
    m_is_processing.store(true);
    try {
        std::vector<uint64_t> output_shape;
        uint64_t current_region_frames = 0;
        if (m_current_region_index < m_organized_regions.size()) {
            auto& current_region = m_organized_regions[m_current_region_index];
            for (const auto& segment : current_region.segments) {
                current_region_frames += segment.segment_size[0];
            }
        }
        output_shape.push_back(current_region_frames);
        output_shape.push_back(m_structure.get_frame_size());
        auto& output_data = container->get_processed_data();
        ensure_output_dimensioning(output_data, output_shape);
        process_organized_regions(container, output_data);
        container->update_processing_state(ProcessingState::PROCESSED);
    } catch (const std::exception& e) {
        container->update_processing_state(ProcessingState::ERROR);
        error_rethrow(
            Journal::Component::Kakshya,
            Journal::Context::Runtime,
            std::source_location::current(),
            "Error during region organization processing: {}",
            e.what());
    }
    m_is_processing.store(false);
}
References MayaFlux::Kakshya::RegionProcessorBase::ensure_output_dimensioning(), MayaFlux::Kakshya::ERROR, MayaFlux::Kakshya::ContainerDataStructure::get_frame_size(), MayaFlux::Journal::Kakshya, MayaFlux::Kakshya::RegionProcessorBase::m_current_region_index, MayaFlux::Kakshya::RegionProcessorBase::m_is_processing, MayaFlux::Kakshya::RegionProcessorBase::m_organized_regions, MayaFlux::Kakshya::RegionProcessorBase::m_structure, process_organized_regions(), MayaFlux::Kakshya::PROCESSED, and MayaFlux::Journal::Runtime.
Referenced by MayaFlux::Kakshya::DynamicRegionProcessor::process().