MayaFlux: MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers_by_usage
get_graphics_buffers_by_usage()
std::vector< std::shared_ptr< VKBuffer > > MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers_by_usage (VKBuffer::Usage usage, ProcessingToken token) const
Gets graphics buffers filtered by usage type.
Parameters
usage VKBuffer::Usage type to filter by
token Processing domain
Returns
Vector of buffers matching the specified usage
Definition at line 309 of file BufferAccessControl.cpp.
{
    if (!m_unit_manager.has_graphics_unit(token)) {
        return {};
    }
    const auto& unit = m_unit_manager.get_graphics_unit(token);
    return unit.get_buffer()->get_buffers_by_usage(usage);
}
References MayaFlux::Buffers::RootGraphicsUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::get_graphics_unit(), MayaFlux::Buffers::TokenUnitManager::has_graphics_unit(), and m_unit_manager.