MayaFlux: MayaFlux::Nodes::Filters::Filter::build_input_history
build_input_history()
void MayaFlux::Nodes::Filters::Filter::build_input_history (double current_sample) protected
Builds input history from external context or internal accumulation.
Parameters
current_sample Current input sample being processed
Definition at line 72 of file Filter.cpp.
{
    if (m_use_external_input_context && !m_external_input_context.empty()) {
        size_t available = m_external_input_context.size();
        size_t lookback = std::min(available, m_input_history.size() - 1);
        m_input_history[0] = current_sample;
        for (size_t i = 0; i < lookback; ++i) {
            m_input_history[i + 1] = m_external_input_context[available - 1 - i];
        }
    } else {
        update_inputs(current_sample);
    }
}
References m_external_input_context, m_input_history, m_use_external_input_context, and update_inputs().
Referenced by MayaFlux::Nodes::Filters::FIR::process_sample(), and MayaFlux::Nodes::Filters::IIR::process_sample().