MayaFlux: MayaFlux::Kakshya::WindowContainer::lock
lock()
void MayaFlux::Kakshya::WindowContainer::lock () override virtual
Acquire a lock for thread-safe access.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 169 of file WindowContainer.cpp.
{ m_data_mutex.lock(); }
References m_data_mutex.
Referenced by add_region_group(), clear(), get_all_region_groups(), get_region_data(), get_region_group(), get_region_group_data(), get_segments_data(), has_data(), register_state_change_callback(), remove_region_group(), unregister_state_change_callback(), and update_processing_state().