MayaFlux: MayaFlux::IO::SoundFileReader::seek_internal
seek_internal()
bool MayaFlux::IO::SoundFileReader::seek_internal (const std::shared_ptr< FFmpegDemuxContext > & demux, const std::shared_ptr< AudioStreamContext > & audio, uint64_t frame_position) private
Seek the demuxer and flush the codec to the given frame position.
Parameters
ctx FFmpeg context.
frame_position Target frame position.
Returns
True if seek succeeded.
Caller must hold an exclusive lock on m_context_mutex.
Definition at line 339 of file SoundFileReader.cpp.
{
    if (frame_position > audio->total_frames)
        frame_position = audio->total_frames;
    if (audio->sample_rate == 0) {
        set_error("Invalid sample rate");
        return false;
    }
    AVStream* stream = demux->get_stream(audio->stream_index);
    if (!stream) {
        set_error("Invalid stream index");
        return false;
    }
    int64_t ts = av_rescale_q(
        static_cast<int64_t>(frame_position),
        AVRational { 1, static_cast<int>(audio->sample_rate) },
        stream->time_base);
    if (!demux->seek(audio->stream_index, ts)) {
        set_error(demux->last_error());
        return false;
    }
    audio->flush_codec();
    audio->drain_resampler_init();
    m_current_frame_position = frame_position;
    return true;
}
References m_current_frame_position, and set_error().
Referenced by read_frames(), and seek().