MayaFlux: MayaFlux::Nodes::NodeNetwork::set_output_mode
set_output_mode()
void MayaFlux::Nodes::NodeNetwork::set_output_mode (OutputMode mode) inline
Set the network's output routing mode.
Definition at line 162 of file NodeNetwork.hpp.
{ m_output_mode = mode; }
Referenced by MayaFlux::Nodes::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::ModalNetwork::ModalNetwork(), and MayaFlux::Nodes::ParticleNetwork::ParticleNetwork().