MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::has_cpu
has_cpu()
bool MayaFlux::Buffers::BufferTokenDistributor::has_cpu (ProcessingToken token) static private
Definition at line 71 of file BufferTokenDistributor.cpp.
{
    return token & ProcessingToken::CPU_PROCESS;
}
References MayaFlux::Buffers::CPU_PROCESS.
Referenced by can_transfer(), decide_audio_buffer(), decide_transfer(), is_valid_audio_token(), and is_valid_vk_token().