MayaFlux: Lila::Server::start
start()
bool Lila::Server::start () noexcept
Starts the server and begins accepting clients.
Returns
True if server started successfully, false otherwise
Definition at line 88 of file Server.cpp.
{
    if (m_running) {
        LILA_WARN(Emitter::SERVER, "Server already running");
        return false;
    }
    try {
#ifdef MAYAFLUX_PLATFORM_WINDOWS
        WSADATA wsaData;
        if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
            throw std::system_error(WSAGetLastError(), std::system_category(), "WSAStartup failed");
        }
#endif
        m_server_fd = socket(AF_INET, SOCK_STREAM, 0);
        if (m_server_fd < 0) {
            throw std::system_error(socket_errno(), std::system_category(), "socket creation failed");
        }
        int opt = 1;
        if (setsockopt(m_server_fd, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<char*>(&opt), sizeof(opt)) < 0) {
            throw std::system_error(socket_errno(), std::system_category(), "setsockopt failed");
        }
        if (set_nonblocking(m_server_fd) < 0) {
            throw std::system_error(socket_errno(), std::system_category(), "set non-blocking failed");
        }
        sockaddr_in address {};
        address.sin_family = AF_INET;
        address.sin_addr.s_addr = INADDR_ANY;
        address.sin_port = htons(m_port);
        if (bind(m_server_fd, reinterpret_cast<sockaddr*>(&address), sizeof(address)) < 0) {
            throw std::system_error(socket_errno(), std::system_category(), "bind failed");
        }
        if (listen(m_server_fd, 10) < 0) {
            throw std::system_error(socket_errno(), std::system_category(), "listen failed");
        }
        m_running = true;
        m_event_bus.publish(StreamEvent { EventType::ServerStart });
        if (m_start_handler) {
            m_start_handler();
        }
        m_server_thread = ServerThread([this](const auto& token) { server_loop(token); });
        LILA_INFO(Emitter::SERVER, "Server started on port " + std::to_string(m_port));
        m_event_bus.publish(StreamEvent { EventType::ServerStart });
        return true;
    } catch (const std::system_error& e) {
        LILA_ERROR(Emitter::SERVER, "Failed to start server: " + std::string(e.what()) + " (code: " + std::to_string(e.code().value()) + ")");
        if (m_server_fd >= 0) {
            socket_close(m_server_fd);
            m_server_fd = -1;
        }
#ifdef MAYAFLUX_PLATFORM_WINDOWS
        WSACleanup();
#endif
        return false;
    }
}
References LILA_ERROR, LILA_INFO, LILA_WARN, m_event_bus, m_port, m_running, m_server_fd, m_server_thread, m_start_handler, Lila::EventBus::publish(), server_loop(), Lila::set_nonblocking(), Lila::socket_close(), and Lila::socket_errno().