MayaFlux: MayaFlux::Kinesis::Stochastic::Stochastic::generate_memoryless
generate_memoryless()
double MayaFlux::Kinesis::Stochastic::Stochastic::generate_memoryless (double min, double max) private
Definition at line 103 of file Stochastic.cpp.
{
    if (min != m_cached_min || max != m_cached_max) {
        m_cached_min = min;
        m_cached_max = max;
        m_dist_dirty = true;
    }
    double raw_value = 0.0;
    switch (m_algorithm) {
    [[likely]] case Algorithm::UNIFORM:
        return min + fast_uniform() * (max - min);
    case Algorithm::NORMAL: {
        rebuild_distributions_if_needed(min, max);
        raw_value = m_normal_dist(m_engine);
        return std::clamp(raw_value, min, max);
    }
    case Algorithm::EXPONENTIAL: {
        rebuild_distributions_if_needed(min, max);
        raw_value = m_exponential_dist(m_engine);
        raw_value /= max;
        return min + raw_value * (max - min);
    }
    case Algorithm::POISSON: {
        std::poisson_distribution<int> dist(static_cast<int>(max - min));
        return static_cast<double>(dist(m_engine));
    }
    default:
        return min + fast_uniform() * (max - min);
    }
}
References MayaFlux::Kinesis::Stochastic::EXPONENTIAL, fast_uniform(), m_algorithm, m_cached_max, m_cached_min, m_dist_dirty, m_engine, m_exponential_dist, m_normal_dist, MayaFlux::Kinesis::Stochastic::NORMAL, MayaFlux::Kinesis::Stochastic::POISSON, rebuild_distributions_if_needed(), and MayaFlux::Kinesis::Stochastic::UNIFORM.
Referenced by operator()().