MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::process_default
process_default()
void MayaFlux::Kakshya::VideoStreamContainer::process_default () override virtual
Process the container's data using the default processor.
Executes the default processing chain, transforming raw data into a processable form. This is a convenience wrapper for standard workflows.
Implements MayaFlux::Kakshya::SignalSourceContainer.
Definition at line 551 of file VideoStreamContainer.cpp.
{
    if (m_default_processor && is_ready_for_processing()) {
        update_processing_state(ProcessingState::PROCESSING);
        m_default_processor->process(shared_from_this());
        update_processing_state(ProcessingState::PROCESSED);
    }
}
References is_ready_for_processing(), m_default_processor, MayaFlux::Kakshya::PROCESSED, MayaFlux::Kakshya::PROCESSING, and update_processing_state().
Referenced by MayaFlux::Kakshya::CameraContainer::process_default().