MayaFlux: MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer
remove_supplied_audio_buffer()
bool MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer (const std::shared_ptr< AudioBuffer > & buffer, ProcessingToken token, uint32_t channel)
Removes a previously supplied buffer from a token and channel.
Parameters
buffer Buffer to remove
token Processing domain
channel Channel index
Returns
True if the buffer was successfully removed, false otherwise
Cleans up the mixing relationship between the supplied buffer and the target channel.
Definition at line 63 of file BufferSupplyMixing.cpp.
{
    if (!buffer) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Invalid buffer for removal");
        return false;
    }
    if (!m_unit_manager.has_audio_unit(token) || channel >= m_unit_manager.get_audio_channel_count(token)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Token/channel combination out of range for removal (token: {}, channel: {})",
            static_cast<int>(token), channel);
        return false;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    auto root_buffer = unit.get_buffer(channel);
    auto processing_chain = unit.get_chain(channel);
    if (std::shared_ptr<MixProcessor> mix_processor = processing_chain->get_processor<MixProcessor>(root_buffer)) {
        return mix_processor->remove_source(buffer);
    }
    return false;
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::TokenUnitManager::get_audio_channel_count(), MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), m_unit_manager, and MF_ERROR.
Referenced by cleanup_completed_routing().