MayaFlux: MayaFlux::Buffers::RenderProcessor::cleanup
cleanup()
void MayaFlux::Buffers::RenderProcessor::cleanup () override protected virtual
Reimplemented from MayaFlux::Buffers::ShaderProcessor.
Definition at line 677 of file RenderProcessor.cpp.
{
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& flow = Portal::Graphics::get_render_flow();
    if (m_pipeline_id != Portal::Graphics::INVALID_RENDER_PIPELINE) {
        flow.destroy_pipeline(m_pipeline_id);
        m_pipeline_id = Portal::Graphics::INVALID_RENDER_PIPELINE;
    }
    if (m_geometry_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_geometry_shader_id);
        m_geometry_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    if (m_tess_control_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_tess_control_shader_id);
        m_tess_control_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    if (m_tess_eval_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_tess_eval_shader_id);
        m_tess_eval_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    if (m_fragment_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_fragment_shader_id);
        m_fragment_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    m_view_transform_ubo.reset();
    m_view_transform_descriptor_set_id = Portal::Graphics::INVALID_DESCRIPTOR_SET;
    m_view_transform_active = false;
    if (m_target_window) {
        flow.unregister_window(m_target_window);
        m_target_window.reset();
    }
    ShaderProcessor::cleanup();
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "RenderProcessor cleanup complete");
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::ShaderProcessor::cleanup(), MayaFlux::Portal::Graphics::get_render_flow(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_DESCRIPTOR_SET, MayaFlux::Portal::Graphics::INVALID_RENDER_PIPELINE, MayaFlux::Portal::Graphics::INVALID_SHADER, m_fragment_shader_id, m_geometry_shader_id, m_pipeline_id, m_target_window, m_tess_control_shader_id, m_tess_eval_shader_id, m_view_transform_active, m_view_transform_descriptor_set_id, m_view_transform_ubo, and MF_DEBUG.