MayaFlux: MayaFlux::Nodes::NodeGraphManager::get_root_node
get_root_node()
RootNode & MayaFlux::Nodes::NodeGraphManager::get_root_node (ProcessingToken token, unsigned int channel)
Gets or creates the root node for a specific token and channel.
Parameters
token Processing domain
channel Channel index
Returns
Reference to the root node for the given token and channel
If the root node does not exist, it is created and registered.
Definition at line 318 of file NodeGraphManager.cpp.
{
    ensure_root_exists(token, channel);
    return *m_token_roots[token][channel];
}
References ensure_root_exists(), and m_token_roots.
Referenced by add_to_root(), MayaFlux::Kriya::TemporalActivation::cleanup_current_operation(), print_summary(), process_channel(), process_sample(), and remove_from_root().