MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::create_2d
create_2d() [1/2]
std::shared_ptr< Core::VKImage > MayaFlux::Portal::Graphics::TextureLoom::create_2d (const Kakshya::DataVariant & variant, uint32_t width, uint32_t height, ImageFormat format = ImageFormat::RGBA32F)
Create a 2D texture from a DataVariant in one shot.
Parameters
variant Source data. Conversion and validation delegated to Kakshya::as_texture_access(): vec3 is promoted to vec4 with W=0 (warned); complex<double> and mat4 are rejected.
width Texture width in texels.
height Texture height in texels.
format Target image format (default: RGBA32F).
Returns
Initialised VKImage in shader-read layout, or nullptr on failure.
Validates byte count against width * height * bpp(format) before upload. Throws std::invalid_argument on mismatch.
Definition at line 334 of file TextureLoom.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "TextureLoom not initialized");
        return nullptr;
    }
    const auto access = Kakshya::as_texture_access(variant);
    if (!access) {
        return nullptr;
    }
    const size_t expected = calculate_image_size(width, height, 1, format);
    if (access->byte_count != expected) {
        error<std::invalid_argument>(
            Journal::Component::Portal,
            Journal::Context::ImageProcessing,
            std::source_location::current(),
            "create_2d: byte count mismatch — {} bytes supplied, "
            "{}x{} format {} requires {}",
            access->byte_count, width, height, static_cast<int>(format), expected);
    }
    return create_2d(width, height, format, access->data_ptr, 1);
}
References MayaFlux::Kakshya::as_texture_access(), calculate_image_size(), create_2d(), MayaFlux::Journal::ImageProcessing, is_initialized(), MF_ERROR, MayaFlux::Journal::Portal, and width.