MayaFlux: MayaFlux::Kakshya::WindowContainer::get_frames_typed
get_frames_typed()
void MayaFlux::Kakshya::WindowContainer::get_frames_typed (std::span< uint8_t > output, uint64_t start_frame, uint64_t num_frames) const private
Definition at line 739 of file WindowContainer.cpp.
{
    seqlock_read_void(m_data_lock, 8, [&] {
        const uint64_t h = m_structure.get_height();
        if (start_frame >= h || output.empty() || m_processed_data.empty()) {
            std::ranges::fill(output, uint8_t { 0 });
            return;
        }
        const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_processed_data[0]);
        if (!pixels || pixels->empty()) {
            std::ranges::fill(output, uint8_t { 0 });
            return;
        }
        const uint64_t row_elems = m_structure.get_width() * m_structure.get_channel_count();
        const uint64_t frames_to_copy = std::min(num_frames, h - start_frame);
        const uint64_t elems_to_copy = std::min(frames_to_copy * row_elems, static_cast<uint64_t>(output.size()));
        const uint64_t src_offset = start_frame * row_elems;
        std::copy_n(pixels->begin() + static_cast<std::ptrdiff_t>(src_offset),
            static_cast<std::ptrdiff_t>(elems_to_copy),
            output.begin());
        if (elems_to_copy < output.size())
            std::fill(output.begin() + static_cast<std::ptrdiff_t>(elems_to_copy), output.end(), uint8_t { 0 });
    });
}
References MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), h, m_data_lock, m_processed_data, m_structure, and pixels.
Referenced by get_frames_impl().