MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::free_all_command_buffers
free_all_command_buffers()
void MayaFlux::Portal::Graphics::ShaderFoundry::free_all_command_buffers ()
Free all allocated command buffers.
Definition at line 784 of file ShaderFoundry.cpp.
{
    if (!m_backend || !s_initialized) {
        return;
    }
    auto& cmd_manager = m_backend->get_command_manager();
    auto device = get_device();
    device.waitIdle();
    for (auto& [id, state] : m_command_buffers) {
        if (state.is_active) {
            cmd_manager.free_command_buffer(state.cmd);
        }
        if (state.timestamp_pool) {
            device.destroyQueryPool(state.timestamp_pool);
        }
    }
    m_command_buffers.clear();
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "Freed all command buffers");
}
References get_device(), m_backend, m_command_buffers, MF_INFO, MayaFlux::Journal::Portal, s_initialized, and MayaFlux::Journal::ShaderCompilation.
Referenced by shutdown(), and stop().