MayaFlux: MayaFlux::Nodes::GpuSync::PathGeneratorNode::regenerate_geometry
regenerate_geometry()
void MayaFlux::Nodes::GpuSync::PathGeneratorNode::regenerate_geometry () private
Definition at line 415 of file PathGeneratorNode.cpp.
{
    if (!m_geometry_dirty) {
        return;
    }
    if (m_dirty_segment_start != INVALID_SEGMENT && m_dirty_segment_end != INVALID_SEGMENT) {
        regenerate_segment_range(m_dirty_segment_start, m_dirty_segment_end);
        m_dirty_segment_start = INVALID_SEGMENT;
        m_dirty_segment_end = INVALID_SEGMENT;
    } else {
        generate_path_vertices();
    }
    m_geometry_dirty = false;
    m_vertex_data_dirty = true;
}
References generate_path_vertices(), INVALID_SEGMENT, m_dirty_segment_end, m_dirty_segment_start, m_geometry_dirty, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, and regenerate_segment_range().
Referenced by compute_frame().