MayaFlux: MayaFlux::IO::SoundFileWriter::worker_loop
worker_loop()
void MayaFlux::IO::SoundFileWriter::worker_loop (const std::string & filepath, uint32_t channels, uint32_t sample_rate, AVCodecID codec_id) private
Definition at line 176 of file SoundFileWriter.cpp.
{
    FFmpegMuxContext mux;
    AudioEncodeContext enc;
    auto fail = [&](std::string msg) {
        set_error(std::move(msg));
        m_open.store(false, std::memory_order_release);
        m_close_promise.set_value(false);
    };
    if (!mux.open(filepath)) {
        fail(mux.last_error());
        return;
    }
    if (!enc.open(mux, sample_rate, channels, codec_id)) {
        fail(enc.last_error());
        return;
    }
    if (!mux.write_header()) {
        fail(mux.last_error());
        return;
    }
    m_open.store(true, std::memory_order_release);
    bool ok = true;
    while (true) {
        auto item = m_queue->pop();
        if (!item) {
            std::this_thread::yield();
            continue;
        }
        if (std::holds_alternative<FrameChunk>(*item)) {
            auto& fc = std::get<FrameChunk>(*item);
            if (!enc.encode_frames(std::span<const double>(fc.samples), fc.num_frames, mux)) {
                set_error(enc.last_error());
                ok = false;
            }
        } else if (std::holds_alternative<PlanarChunk>(*item)) {
            auto& pc = std::get<PlanarChunk>(*item);
            const auto ch = static_cast<uint32_t>(pc.channels.size());
            std::vector<double> interleaved(static_cast<size_t>(pc.num_frames) * ch);
            for (uint32_t f = 0; f < pc.num_frames; ++f) {
                for (uint32_t c = 0; c < ch; ++c)
                    interleaved[(size_t)f * ch + c] = pc.channels[c][f];
            }
            if (!enc.encode_frames(interleaved, pc.num_frames, mux)) {
                set_error(enc.last_error());
                ok = false;
            }
        } else {
            if (ok && !enc.drain(mux)) {
                set_error(enc.last_error());
                ok = false;
            }
            mux.close();
            m_open.store(false, std::memory_order_release);
            m_close_promise.set_value(ok);
            return;
        }
    }
}
References MayaFlux::IO::FFmpegMuxContext::close(), MayaFlux::IO::AudioEncodeContext::drain(), MayaFlux::IO::AudioEncodeContext::encode_frames(), MayaFlux::IO::AudioEncodeContext::last_error(), MayaFlux::IO::FFmpegMuxContext::last_error(), m_close_promise, m_open, m_queue, MayaFlux::IO::FFmpegMuxContext::open(), MayaFlux::IO::AudioEncodeContext::open(), set_error(), and MayaFlux::IO::FFmpegMuxContext::write_header().
Referenced by open().