MayaFlux: MayaFlux::Buffers::BufferSupplyMixing::clone_audio_buffer_for_channels
clone_audio_buffer_for_channels()
std::vector< std::shared_ptr< AudioBuffer > > MayaFlux::Buffers::BufferSupplyMixing::clone_audio_buffer_for_channels (const std::shared_ptr< AudioBuffer > & buffer, const std::vector< uint32_t > & channels, ProcessingToken token)
Clones an audio buffer for each channel in the specified list.
Parameters
buffer Buffer to clone
channels Vector of channel indices to clone for
token Processing domain
Creates a new buffer for each specified channel, copying the structure but maintaining independent data. Useful for multi-channel processing where each channel needs its own processing chain.
Definition at line 145 of file BufferSupplyMixing.cpp.
{
    if (channels.empty()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: No channels specified for cloning");
        return {};
    }
    if (!buffer) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Invalid buffer for cloning");
        return {};
    }
    if (!m_unit_manager.has_audio_unit(token)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
            "BufferSupplyMixing: Token not found for cloning");
        return {};
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    std::vector<std::shared_ptr<AudioBuffer>> cloned_buffers {};
    for (const auto channel : channels) {
        if (channel >= unit.channel_count) {
            MF_ERROR(Journal::Component::Core, Journal::Context::BufferManagement,
                "BufferSupplyMixing: Channel {} out of range for cloning", channel);
            return cloned_buffers;
        }
        auto cloned_buffer = buffer->clone_to(channel);
        m_access_control.add_audio_buffer(cloned_buffer, token, channel);
        cloned_buffers.push_back(cloned_buffer);
    }
    return cloned_buffers;
}
References MayaFlux::Buffers::BufferAccessControl::add_audio_buffer(), MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), m_access_control, m_unit_manager, and MF_ERROR.