MayaFlux: MayaFlux::Kakshya::RegionProcessorBase::cache_region_if_needed
cache_region_if_needed()
void MayaFlux::Kakshya::RegionProcessorBase::cache_region_if_needed (const RegionSegment & segment, const std::shared_ptr< SignalSourceContainer > & container) protected virtual
Cache a region's data if beneficial and not already cached.
Uses heuristics (e.g., segment size vs. cache size) to decide.
Parameters
segment The region segment to consider for caching.
container The container providing the data.
Definition at line 35 of file RegionProcessorBase.cpp.
{
    if (!m_auto_caching || !m_cache_manager)
        return;
    if (m_cache_manager->get_cached_segment(segment)) {
        return;
    }
    uint64_t segment_size = segment.get_total_elements();
    if (segment_size <= m_max_cache_size / 10) { // Use max 10% of cache per segment
        try {
            RegionCache cache;
            cache.data = container->get_region_data(segment.source_region);
            cache.source_region = segment.source_region;
            cache.load_time = std::chrono::steady_clock::now();
            m_cache_manager->cache_region(cache);
        } catch (const std::exception& e) {
            MF_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
                "Failed to cache region segment: {}", e.what());
        }
    }
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Kakshya::RegionCache::data, MayaFlux::Kakshya::RegionSegment::get_total_elements(), MayaFlux::Journal::Kakshya, MayaFlux::Kakshya::RegionCache::load_time, m_auto_caching, m_cache_manager, m_max_cache_size, MF_WARN, MayaFlux::Kakshya::RegionCache::source_region, and MayaFlux::Kakshya::RegionSegment::source_region.
Referenced by MayaFlux::Kakshya::RegionOrganizationProcessor::add_segment_to_region(), and MayaFlux::Kakshya::RegionOrganizationProcessor::organize_group().