MayaFlux: MayaFlux::Core::VKDescriptorManager::grow_pools
grow_pools()
bool MayaFlux::Core::VKDescriptorManager::grow_pools (vk::Device device) private
Grow pool capacity by allocating new pool.
Parameters
device Logical device
Returns
true if new pool created successfully
Definition at line 233 of file VKDescriptorManager.cpp.
{
    auto new_pool = create_pool(device, m_pool_size);
    if (!new_pool) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to grow descriptor pool");
        return false;
    }
    m_pools.push_back(new_pool);
    m_pool_capacity += m_pool_size;
    m_current_pool_index = m_pools.size() - 1;
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Grew descriptor pools (new capacity: {} sets)", m_pool_capacity);
    return true;
}
References MayaFlux::Journal::Core, create_pool(), MayaFlux::Journal::GraphicsBackend, m_current_pool_index, m_pool_capacity, m_pool_size, m_pools, MF_ERROR, and MF_INFO.
Referenced by allocate_set(), and allocate_sets().