MayaFlux: Lila::Server::send_message
send_message()
bool Lila::Server::send_message (int client_fd, std::string_view message) private
Sends a message to a client.
Parameters
client_fd Client file descriptor
message Message to send
Returns
True if message sent successfully
Definition at line 400 of file Server.cpp.
{
    std::string msg_with_newline = std::string(message) + "\n";
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    int sent = send(static_cast<SOCKET>(client_fd), msg_with_newline.data(), static_cast<int>(msg_with_newline.size()), 0);
    return sent == static_cast<int>(msg_with_newline.size());
#else
    ssize_t sent = send(client_fd, msg_with_newline.data(), msg_with_newline.size(), 0);
    return sent == static_cast<ssize_t>(msg_with_newline.size());
#endif
}
Referenced by broadcast_event(), handle_client(), and process_control_message().