MayaFlux: MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_buffer
update_from_buffer()
void MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_buffer (DescriptorBinding & binding) private
Definition at line 581 of file DescriptorBindingsProcessor.cpp.
{
    if (binding.source_type == SourceType::AUDIO_BUFFER) {
        auto audio = std::dynamic_pointer_cast<AudioBuffer>(binding.buffer);
        const auto& samples = audio->get_data();
        size_t required = samples.size() * sizeof(float);
        ensure_buffer_capacity(binding, required);
        thread_local std::vector<float> conv;
        conv.resize(samples.size());
        std::ranges::transform(samples, conv.begin(),
            [](double d) { return static_cast<float>(d); });
        upload_to_gpu(conv.data(), required, binding.gpu_buffer, nullptr);
        return;
    }
    auto vk = std::dynamic_pointer_cast<VKBuffer>(binding.buffer);
    auto data = vk->get_data();
    if (data.empty()) {
        MF_RT_WARN(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Host VKBuffer binding '{}' returned no data", binding.descriptor_name);
        return;
    }
    auto& raw = std::get<std::vector<uint8_t>>(data[0]);
    ensure_buffer_capacity(binding, raw.size());
    upload_to_gpu(raw.data(), raw.size(), binding.gpu_buffer, nullptr);
}
References AUDIO_BUFFER, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::buffer, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::descriptor_name, ensure_buffer_capacity(), MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::gpu_buffer, MF_RT_WARN, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::source_type, and MayaFlux::Buffers::upload_to_gpu().
Referenced by update_descriptor_data().