MayaFlux: MayaFlux::Buffers::NodeTextureProcessor::initialize_gpu_resources
initialize_gpu_resources()
void MayaFlux::Buffers::NodeTextureProcessor::initialize_gpu_resources () private
Definition at line 165 of file NodeTextureProcessor.cpp.
{
    if (!m_attached_buffer || m_attached_buffer->m_vertex_bytes.empty()) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "NodeTextureProcessor: no attached buffer or empty vertex data");
        return;
    }
    upload_to_gpu(
        m_attached_buffer->m_vertex_bytes.data(),
        m_attached_buffer->m_vertex_bytes.size(),
        m_attached_buffer);
    auto& loom = Portal::Graphics::get_texture_manager();
    for (auto& [name, binding] : m_bindings) {
        auto pixels = binding.node->get_pixel_buffer();
        if (!pixels.empty()) {
            loom.upload_data(binding.gpu_texture, pixels.data(), pixels.size_bytes());
        }
    }
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "NodeTextureProcessor: uploaded {} bytes of vertex geometry",
        m_attached_buffer->m_vertex_bytes.size());
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_texture_manager(), m_attached_buffer, m_bindings, MF_DEBUG, MF_ERROR, pixels, and MayaFlux::Buffers::upload_to_gpu().
Referenced by on_attach().