MayaFlux: MayaFlux::Buffers::NetworkGeometryBuffer::add_chain_operator_rendering
add_chain_operator_rendering()
void MayaFlux::Buffers::NetworkGeometryBuffer::add_chain_operator_rendering (const RenderConfig & config)
Add a RenderProcessor for a specific operator chain index.
Parameters
config Rendering configuration
This allows rendering different subsets of the network geometry with different pipelines. Each chain index corresponds to a specific node/operator in the network.
Definition at line 192 of file NetworkGeometryBuffer.cpp.
{
    const auto resolved_config = resolve_config(config);
    auto self = std::dynamic_pointer_cast<VKBuffer>(shared_from_this());
    std::shared_ptr<RenderProcessor> render;
    apply_render_config(render, resolved_config, ShaderConfig { resolved_config.vertex_shader });
    get_processing_chain()->add_processor(render, shared_from_this());
    render->set_buffer_vertex_layout(self, Kakshya::VertexLayout::for_lines());
    render->set_vertex_range(0, 0);
    m_chain_render_processors.push_back({ .render_processor = render });
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::Init,
        "Added chain render processor #{} to NetworkGeometryBuffer",
        m_chain_render_processors.size());
}
References MayaFlux::Buffers::VKBuffer::apply_render_config(), MayaFlux::Journal::Buffers, MayaFlux::Kakshya::VertexLayout::for_lines(), MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Journal::Init, m_chain_render_processors, and MF_DEBUG.