MayaFlux: MayaFlux::Buffers::BufferProcessingControl::add_graphics_processor
add_graphics_processor() [2/2]
void MayaFlux::Buffers::BufferProcessingControl::add_graphics_processor (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token)
Adds a processor to the graphics processing chain.
Parameters
processor Processor to add
token Processing domain
Definition at line 338 of file BufferProcessingControl.cpp.
{
    auto chain = m_access_control.get_graphics_processing_chain(token);
    auto root_buffer = m_access_control.get_root_graphics_buffer(token);
    chain->add_processor(processor, root_buffer);
}
References MayaFlux::Buffers::BufferAccessControl::get_graphics_processing_chain(), MayaFlux::Buffers::BufferAccessControl::get_root_graphics_buffer(), m_access_control, and token.
Referenced by add_processor(), and add_processor().