MayaFlux: MayaFlux::Nodes::Filters::Filter::set_coefs
set_coefs()
void MayaFlux::Nodes::Filters::Filter::set_coefs (const std::vector< double > & new_coefs, coefficients type = coefficients::ALL)
Updates filter coefficients.
Parameters
new_coefs New coefficient values
type Which set of coefficients to update (input, output, or both)
Provides a flexible way to update filter coefficients, allowing dynamic modification of filter characteristics during processing.
Definition at line 60 of file Filter.cpp.
{
    if (type == coefficients::OUTPUT) {
        setACoefficients(new_coefs);
    } else if (type == coefficients::INPUT) {
        setBCoefficients(new_coefs);
    } else {
        setACoefficients(new_coefs);
        setBCoefficients(new_coefs);
    }
}
References MayaFlux::Nodes::Filters::INPUT, MayaFlux::Nodes::Filters::OUTPUT, setACoefficients(), and setBCoefficients().
Referenced by update_coef_from_input(), and update_coefs_from_node().