MayaFlux: MayaFlux::Core::MIDIBackend::refresh_devices
refresh_devices()
size_t MayaFlux::Core::MIDIBackend::refresh_devices () override virtual
Refresh the device list.
Returns
Number of devices found
Re-enumerates available devices. May trigger device callbacks for newly connected or disconnected devices.
Implements MayaFlux::Core::IInputBackend.
Definition at line 148 of file MIDIBackend.cpp.
{
    if (!m_initialized.load()) {
        return 0;
    }
    std::vector<InputDeviceInfo> newly_added_devices;
    try {
        RtMidiIn midi_in;
        unsigned int port_count = midi_in.getPortCount();
        {
            std::lock_guard lock(m_devices_mutex);
            for (unsigned int i = 0; i < port_count; ++i) {
                std::string port_name = midi_in.getPortName(i);
                if (!port_matches_filter(port_name)) {
                    continue;
                }
                uint32_t dev_id = find_or_assign_device_id(i);
                MIDIPortInfo info {};
                info.id = dev_id;
                info.name = port_name;
                info.backend_type = InputType::MIDI;
                info.is_connected = true;
                info.is_input = true;
                info.is_output = false;
                info.port_number = static_cast<uint8_t>(i);
                info.rtmidi_port_number = i;
                bool is_new = (m_enumerated_devices.find(dev_id) == m_enumerated_devices.end());
                m_enumerated_devices[dev_id] = info;
                if (is_new) {
                    newly_added_devices.push_back(info);
                }
            }
        }
        for (const auto& info : newly_added_devices) {
            MF_WARN(Journal::Component::Core, Journal::Context::InputBackend,
                "MIDI port found: {}", info.name);
            notify_device_change(info, true);
        }
        {
            std::lock_guard lock(m_devices_mutex);
            return m_enumerated_devices.size();
        }
    } catch (const RtMidiError& error) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputBackend,
            "Error enumerating MIDI ports: {}", error.getMessage());
        return 0;
    }
}
References MayaFlux::Journal::Core, find_or_assign_device_id(), MayaFlux::Core::InputDeviceInfo::id, MayaFlux::Journal::InputBackend, m_devices_mutex, m_enumerated_devices, m_initialized, MF_ERROR, MF_WARN, MayaFlux::Core::MIDI, notify_device_change(), and port_matches_filter().
Referenced by initialize().