MayaFlux: MayaFlux::Buffers::SDFPrepProcessor::rebuild_buffers
rebuild_buffers()
void MayaFlux::Buffers::SDFPrepProcessor::rebuild_buffers () private
Definition at line 39 of file SDFPrepProcessor.cpp.
{
    auto svc = Registry::BackendRegistry::instance()
                   .get_service<Registry::Service::BufferService>();
    m_grid_buf = std::make_shared<VKBuffer>(
        corner_count() * sizeof(float),
        VKBuffer::Usage::HOST_STORAGE,
        Kakshya::DataModality::UNKNOWN);
    svc->initialize_buffer(m_grid_buf);
    m_counter_buf = std::make_shared<VKBuffer>(
        sizeof(uint32_t),
        VKBuffer::Usage::HOST_STORAGE,
        Kakshya::DataModality::UNKNOWN);
    svc->initialize_buffer(m_counter_buf);
}
References corner_count(), MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Buffers::VKBuffer::HOST_STORAGE, MayaFlux::Registry::BackendRegistry::instance(), m_counter_buf, m_grid_buf, and MayaFlux::Kakshya::UNKNOWN.
Referenced by on_attach(), and set_resolution().