MayaFlux: MayaFlux::Yantra::GpuDispatchCore::dispatch_core_async
dispatch_core_async()
Portal::Graphics::FenceID MayaFlux::Yantra::GpuDispatchCore::dispatch_core_async (const std::vector< std::vector< double > > & channels, const DataStructureInfo & structure_info) protected
Non-blocking variant of dispatch_core.
Performs the full setup (on_before_gpu_dispatch, prepare_gpu_inputs, bind_descriptor) then calls GpuResourceManager::dispatch_async. Returns immediately with a FenceID. The caller must poll ShaderFoundry::is_fence_signaled on the returned ID, and once signaled call readback_primary / readback_aux to collect results.
Parameters
channels Extracted double channels from the input Datum.
structure_info Dimension/modality metadata from OperationHelper.
Returns
FenceID to poll. INVALID_FENCE if dispatch fails.
Definition at line 315 of file GpuDispatchCore.cpp.
{
    on_before_gpu_dispatch(channels, structure_info);
    prepare_gpu_inputs(channels, structure_info);
    for (size_t i = 0; i < m_bindings.size(); ++i) {
        const auto et = m_bindings[i].element_type;
        if (et != GpuBufferBinding::ElementType::IMAGE_STORAGE
            && et != GpuBufferBinding::ElementType::IMAGE_SAMPLED)
            m_resources.bind_descriptor(i, m_bindings[i]);
    }
    const size_t effective = m_staging_floats.empty()
        ? largest_binding_data_element_count()
        : m_staging_floats.size();
    const auto groups = calculate_dispatch_size(effective, structure_info);
    m_last_effective_element_count = effective;
    return m_resources.dispatch_async(
        groups, m_bindings,
        m_push_constants.empty() ? nullptr : m_push_constants.data(),
        m_push_constants.size());
}
References MayaFlux::Yantra::GpuResourceManager::bind_descriptor(), calculate_dispatch_size(), MayaFlux::Yantra::GpuResourceManager::dispatch_async(), MayaFlux::Yantra::GpuBufferBinding::IMAGE_SAMPLED, MayaFlux::Yantra::GpuBufferBinding::IMAGE_STORAGE, largest_binding_data_element_count(), m_bindings, m_last_effective_element_count, m_push_constants, m_resources, m_staging_floats, on_before_gpu_dispatch(), and prepare_gpu_inputs().
Referenced by MayaFlux::Yantra::ShaderExecutionContext< InputType, OutputType >::dispatch_async().