MayaFlux: MayaFlux::Kriya::BufferOperation::is_process_phase_operation
is_process_phase_operation()
bool MayaFlux::Kriya::BufferOperation::is_process_phase_operation (const BufferOperation & op) static
Definition at line 262 of file BufferOperation.cpp.
{
    if (op.get_execution_phase() == BufferOperation::ExecutionPhase::PROCESS) {
        return true;
    }
    if (op.get_execution_phase() == BufferOperation::ExecutionPhase::CAPTURE) {
        return false;
    }
    switch (op.get_type()) {
    case BufferOperation::OpType::MODIFY:
        return !op.is_streaming();
    case BufferOperation::OpType::TRANSFORM:
    case BufferOperation::OpType::ROUTE:
    case BufferOperation::OpType::LOAD:
    case BufferOperation::OpType::DISPATCH:
    case BufferOperation::OpType::FUSE:
        return true;
    case BufferOperation::OpType::CAPTURE:
    case BufferOperation::OpType::CONDITION:
    case BufferOperation::OpType::BRANCH:
    case BufferOperation::OpType::SYNC:
    default:
        return false;
    }
}
References BRANCH, CAPTURE, CONDITION, DISPATCH, FUSE, get_execution_phase(), get_type(), is_streaming(), LOAD, MODIFY, PROCESS, ROUTE, SYNC, and TRANSFORM.
Referenced by MayaFlux::Kriya::BufferPipeline::execute_phased(), and MayaFlux::Kriya::BufferPipeline::execute_streaming().