MayaFlux: MayaFlux::Nexus::Fabric::assign_id
assign_id()
uint32_t MayaFlux::Nexus::Fabric::assign_id (Member & m) private
Definition at line 225 of file Fabric.cpp.
{
    uint32_t id = m_next_id++;
    std::visit([id](const auto& ptr) {
        ptr->m_id = id;
    },
        m);
    return id;
}
References id, and m_next_id.
Referenced by wire(), wire(), and wire().