MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::invalidate_span_cache
invalidate_span_cache()
void MayaFlux::Kakshya::SoundStreamContainer::invalidate_span_cache () protected
Invalidate the span cache when data or layout changes.
Definition at line 868 of file SoundStreamContainer.cpp.
{
    m_span_cache_dirty.store(true, std::memory_order_release);
}
References m_span_cache_dirty.
Referenced by reorganize_data_layout(), set_region_data(), set_value_at(), and MayaFlux::Kakshya::DynamicSoundStream::write_frames().