MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::set_all_data
set_all_data() [1/2]
void MayaFlux::Kakshya::DynamicSoundStream::set_all_data (const DataVariant & new_data) private
Definition at line 363 of file DynamicSoundStream.cpp.
{
    set_all_data(std::vector<DataVariant> {data});
}
References set_all_data().
Referenced by expand_to(), and set_all_data().