MayaFlux: MayaFlux::Buffers::TextureProcessor::initialize_gpu_resources
initialize_gpu_resources()
void MayaFlux::Buffers::TextureProcessor::initialize_gpu_resources () private
Initialize all GPU resources:
VKImage for texture
Vertex buffer with quad geometry
Pixel upload
Definition at line 95 of file TextureProcessor.cpp.
{
    if (!m_texture_buffer) {
        return;
    }
    if (!m_texture_buffer->has_texture()) {
        m_texture_buffer->m_gpu_texture = create_gpu_texture();
    }
    upload_initial_geometry();
    upload_initial_pixels();
    m_texture_buffer->m_texture_dirty = false;
    m_texture_buffer->m_geometry_dirty = false;
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "TextureProcessor: GPU resources initialized");
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, create_gpu_texture(), m_texture_buffer, MF_DEBUG, upload_initial_geometry(), and upload_initial_pixels().
Referenced by on_attach().