MayaFlux: MayaFlux::Core::MIDIBackend::open_device
open_device()
bool MayaFlux::Core::MIDIBackend::open_device (uint32_t device_id) override virtual
Open a device for input.
Parameters
device_id Device identifier from get_devices()
Returns
true if device was opened successfully
Implements MayaFlux::Core::IInputBackend.
Definition at line 209 of file MIDIBackend.cpp.
{
    std::lock_guard lock(m_devices_mutex);
    if (m_open_devices.find(device_id) != m_open_devices.end()) {
        MF_WARN(Journal::Component::Core, Journal::Context::InputBackend,
            "MIDI port {} already open", device_id);
        return true;
    }
    auto it = m_enumerated_devices.find(device_id);
    if (it == m_enumerated_devices.end()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputBackend,
            "MIDI port {} not found", device_id);
        return false;
    }
    try {
        auto state = std::make_shared<MIDIPortState>();
        state->info = it->second;
        state->device_id = device_id;
        state->input_callback = m_input_callback;
        state->midi_in = std::make_unique<RtMidiIn>();
        state->midi_in->openPort(state->info.rtmidi_port_number, state->info.name);
        state->midi_in->setCallback(&MIDIBackend::rtmidi_callback, state.get());
        state->midi_in->ignoreTypes(false, false, false);
        state->active.store(true);
        m_open_devices.insert_or_assign(device_id, state);
        MF_INFO(Journal::Component::Core, Journal::Context::InputBackend,
            "Opened MIDI port {}: {}", device_id, state->info.name);
        return true;
    } catch (const RtMidiError& error) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputBackend,
            "Failed to open MIDI port {}: {}", it->second.name, error.getMessage());
        return false;
    }
}
References MayaFlux::Journal::Core, MayaFlux::Journal::InputBackend, m_devices_mutex, m_enumerated_devices, m_input_callback, m_open_devices, MF_ERROR, MF_INFO, MF_WARN, and rtmidi_callback().
Referenced by MayaFlux::Core::InputSubsystem::initialize_midi_backend(), and start().