MayaFlux: MayaFlux::IO::SoundFileReader::set_error
set_error()
void MayaFlux::IO::SoundFileReader::set_error (const std::string & error) const private
Set the last error message.
Parameters
error Error string.
Definition at line 712 of file SoundFileReader.cpp.
{
    std::lock_guard<std::mutex> lock(m_error_mutex);
    m_last_error = err;
    MF_ERROR(Journal::Component::IO, Journal::Context::FileIO, "SoundFileReader: {}", err);
}
References MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, m_error_mutex, m_last_error, and MF_ERROR.
Referenced by create_container(), decode_frames(), load_bounded(), load_into_container(), open(), open_from_demux(), read_all(), read_frames(), read_region(), seek(), and seek_internal().