MayaFlux: MayaFlux::Buffers::ShaderProcessor::cleanup
cleanup()
void MayaFlux::Buffers::ShaderProcessor::cleanup () protected virtual
Reimplemented in MayaFlux::Buffers::ComputeProcessor, and MayaFlux::Buffers::RenderProcessor.
Definition at line 405 of file ShaderProcessor.cpp.
{
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& compute_press = Portal::Graphics::get_compute_press();
    if (m_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_shader_id);
        m_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    m_descriptor_set_ids.clear();
    m_bound_buffers.clear();
    m_initialized = false;
}
References MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_SHADER, m_bound_buffers, m_descriptor_set_ids, m_initialized, and m_shader_id.
Referenced by MayaFlux::Buffers::RenderProcessor::cleanup(), and ~ShaderProcessor().