MayaFlux: MayaFlux::Portal::Text::GlyphAtlas::line_height
line_height()
uint32_t MayaFlux::Portal::Text::GlyphAtlas::line_height () const
Line advance in pixels for this atlas's pixel_size.
Derived from FT_Face metrics: (ascender - descender) in 26.6 fixed-point, shifted right by 6. Returns pixel_size as a safe fallback if the face has not yet been sized (i.e. before the first get_or_rasterize() call).
Definition at line 48 of file GlyphAtlas.cpp.
{
    FT_Face face = m_face.get_face();
    if (!face || face->size == nullptr) {
        return m_pixel_size;
    }
    const int32_t h = (face->size->metrics.ascender - face->size->metrics.descender) >> 6;
    return h > 0 ? static_cast<uint32_t>(h) : m_pixel_size;
}
References MayaFlux::Portal::Text::FontFace::get_face(), h, m_face, and m_pixel_size.
Referenced by MayaFlux::Portal::Text::impress(), MayaFlux::Portal::Text::lay_out(), MayaFlux::Portal::Text::press(), and MayaFlux::Portal::Text::repress().