MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::clear
clear()
void MayaFlux::Kakshya::VideoStreamContainer::clear () override virtual
Clear all data in the container.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 462 of file VideoStreamContainer.cpp.
{
    std::unique_lock lock(m_data_mutex);
    std::ranges::for_each(m_data, [](auto& v) {
        std::visit([](auto& vec) { vec.clear(); }, v);
    });
    m_num_frames = 0;
    m_read_position.store(0);
    setup_dimensions();
    update_processing_state(ProcessingState::IDLE);
}
References MayaFlux::Kakshya::IDLE, lock(), m_data, m_data_mutex, m_num_frames, m_read_position, setup_dimensions(), and update_processing_state().