MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::decide_vk_buffer
decide_vk_buffer()
DistributionDecision MayaFlux::Buffers::BufferTokenDistributor::decide_vk_buffer (const std::shared_ptr< VKBuffer > & vk, ProcessingToken token) static private
Definition at line 146 of file BufferTokenDistributor.cpp.
{
    if (!is_valid_vk_token(token)) {
        return DistributionDecision {
            .result = DistributionResult::REJECTED,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_BACKEND,
            .reason = "VKBuffer requires GPU_PPOCESS token without CPU_PROCESS"
        };
    }
    // Decision 1: GRAPHICS_BACKEND or FRAME_RATE GPU → DIRECT_ROOT (graphics domain)
    if (has_frame_rate(token) && has_gpu(token)) {
        return DistributionDecision {
            .result = DistributionResult::DIRECT_ROOT,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::GRAPHICS_BACKEND,
            .reason = "GPU buffer registered to graphics root"
        };
    }
    // Decision 2: AUDIO_PARALLEL (SAMPLE_RATE + GPU) → TRANSFER_ONLY
    if (has_sample_rate(token) && has_gpu(token)) {
        vk->force_internal_usage(true);
        return DistributionDecision {
            .result = DistributionResult::TRANSFER_ONLY,
            .transfer_processor = nullptr,
            .transfer_direction = ProcessingToken::AUDIO_PARALLEL,
            .reason = "GPU buffer at audio rate marked internal (awaiting transfer)"
        };
    }
    return DistributionDecision {
        .result = DistributionResult::REJECTED,
        .transfer_processor = nullptr,
        .transfer_direction = ProcessingToken::AUDIO_BACKEND,
        .reason = "VKBuffer token combination not handled"
    };
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Buffers::AUDIO_PARALLEL, MayaFlux::Buffers::DIRECT_ROOT, MayaFlux::Buffers::GRAPHICS_BACKEND, has_frame_rate(), has_gpu(), has_sample_rate(), is_valid_vk_token(), MayaFlux::Buffers::REJECTED, MayaFlux::Buffers::DistributionDecision::result, and MayaFlux::Buffers::TRANSFER_ONLY.
Referenced by distribute().