MayaFlux: MayaFlux::Portal::Forma::Context::register_handlers
register_handlers()
void MayaFlux::Portal::Forma::Context::register_handlers () private
Definition at line 75 of file Context.cpp.
{
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_moved(m_window,
                [this](double px, double py) { handle_move(px, py); })),
        m_name + "_move");
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_pressed(m_window, IO::MouseButtons::Left,
                [this](double px, double py) { handle_press(px, py, IO::MouseButtons::Left); })),
        m_name + "_press_left");
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_released(m_window, IO::MouseButtons::Left,
                [this](double px, double py) { handle_release(px, py, IO::MouseButtons::Left); })),
        m_name + "_release_left");
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_pressed(m_window, IO::MouseButtons::Right,
                [this](double px, double py) { handle_press(px, py, IO::MouseButtons::Right); })),
        m_name + "_press_right");
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_released(m_window, IO::MouseButtons::Right,
                [this](double px, double py) { handle_release(px, py, IO::MouseButtons::Right); })),
        m_name + "_release_right");
    m_event_manager.add_event(
        std::make_shared<Vruta::Event>(
            Kriya::mouse_scrolled(m_window,
                [this](double dx, double dy) { handle_scroll(dx, dy); })),
        m_name + "_scroll");
}
References MayaFlux::Vruta::EventManager::add_event(), handle_move(), handle_press(), handle_release(), handle_scroll(), MayaFlux::IO::Left, m_event_manager, m_name, m_window, MayaFlux::Kriya::mouse_moved(), MayaFlux::Kriya::mouse_pressed(), MayaFlux::Kriya::mouse_released(), MayaFlux::Kriya::mouse_scrolled(), and MayaFlux::IO::Right.
Referenced by Context().