MayaFlux: MayaFlux::Buffers::BufferDownloadProcessor::download_device_local
download_device_local()
void MayaFlux::Buffers::BufferDownloadProcessor::download_device_local (const std::shared_ptr< VKBuffer > & source) private
Definition at line 63 of file BufferDownloadProcessor.cpp.
{
    auto target_it = m_target_map.find(source);
    if (target_it == m_target_map.end() || !target_it->second) {
        return;
    }
    auto target = target_it->second;
    ensure_staging_buffer(source);
    auto staging_buffer = m_staging_buffers[source];
    Buffers::download_device_local(source, std::dynamic_pointer_cast<VKBuffer>(target), staging_buffer);
}
References MayaFlux::Buffers::download_device_local(), ensure_staging_buffer(), m_staging_buffers, and m_target_map.
Referenced by processing_function().