MayaFlux: MayaFlux::Buffers::GeometryBuffer::setup_rendering
setup_rendering()
void MayaFlux::Buffers::GeometryBuffer::setup_rendering (const RenderConfig & config)
Setup rendering with RenderProcessor.
Parameters
config Rendering configuration
Definition at line 62 of file GeometryBuffer.cpp.
{
    RenderConfig resolved_config = config;
    const bool textured = m_diffuse_texture != nullptr
        || !resolved_config.default_texture_binding.empty();
    if (resolved_config.topology == Portal::Graphics::PrimitiveTopology::POINT_LIST
        && m_geometry_node->get_primitive_topology()
            != Portal::Graphics::PrimitiveTopology::POINT_LIST) {
        resolved_config.topology = m_geometry_node->get_primitive_topology();
    }
    switch (resolved_config.topology) {
    case Portal::Graphics::PrimitiveTopology::POINT_LIST:
        if (config.vertex_shader.empty())
            resolved_config.vertex_shader = "point.vert.spv";
        if (config.fragment_shader.empty())
            resolved_config.fragment_shader = "point.frag.spv";
        break;
    case Portal::Graphics::PrimitiveTopology::LINE_LIST:
    case Portal::Graphics::PrimitiveTopology::LINE_STRIP:
        if (config.vertex_shader.empty())
            resolved_config.vertex_shader = "line.vert.spv";
        if (config.fragment_shader.empty())
            resolved_config.fragment_shader = "line.frag.spv";
#ifndef MAYAFLUX_PLATFORM_MACOS
        if (config.geometry_shader.empty())
            resolved_config.geometry_shader = "line.geom.spv";
#else
        resolved_config.topology = Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST;
#endif
        break;
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST:
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP:
        if (config.vertex_shader.empty())
            resolved_config.vertex_shader = "triangle.vert.spv";
        if (config.fragment_shader.empty()) {
            resolved_config.fragment_shader = textured
                ? "mesh_textured.frag.spv"
                : "triangle.frag.spv";
        }
        break;
    default:
        if (config.vertex_shader.empty())
            resolved_config.vertex_shader = "point.vert.spv";
        if (config.fragment_shader.empty())
            resolved_config.fragment_shader = "point.frag.spv";
    }
    const bool frag_samples_texture = !resolved_config.default_texture_binding.empty()
        || resolved_config.fragment_shader.find("textured") != std::string::npos;
    if (textured && !frag_samples_texture) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::Init,
            "GeometryBuffer::setup_rendering: texture supplied but fragment shader '{}' "
            "does not sample a texture — texture will be ignored",
            resolved_config.fragment_shader);
    }
    const bool apply_texture = textured && frag_samples_texture;
    ShaderConfig sc { resolved_config.vertex_shader };
    if (apply_texture) {
        const std::string slot = resolved_config.default_texture_binding.empty()
            ? m_diffuse_binding
            : resolved_config.default_texture_binding;
        sc.bindings[slot] = ShaderBinding(0, 1, vk::DescriptorType::eCombinedImageSampler);
    }
    apply_render_config(resolved_config, sc);
    get_processing_chain()->add_final_processor(m_render_processor, shared_from_this());
    if (apply_texture && m_diffuse_texture)
        set_texture(m_diffuse_texture, m_diffuse_binding);
    set_default_render_config(resolved_config);
}
References MayaFlux::Buffers::VKBuffer::apply_render_config(), MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::RenderConfig::default_texture_binding, MayaFlux::Portal::Graphics::RenderConfig::fragment_shader, MayaFlux::Portal::Graphics::RenderConfig::geometry_shader, MayaFlux::Buffers::VKBuffer::get_processing_chain(), MayaFlux::Journal::Init, MayaFlux::Portal::Graphics::LINE_LIST, MayaFlux::Portal::Graphics::LINE_STRIP, m_diffuse_binding, m_diffuse_texture, m_geometry_node, MayaFlux::Buffers::VKBuffer::m_render_processor, MF_WARN, MayaFlux::Portal::Graphics::POINT_LIST, MayaFlux::Buffers::VKBuffer::set_default_render_config(), set_texture(), MayaFlux::Portal::Graphics::RenderConfig::topology, MayaFlux::Portal::Graphics::TRIANGLE_LIST, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, and MayaFlux::Portal::Graphics::RenderConfig::vertex_shader.