MayaFlux: MayaFlux::Buffers::ShaderProcessor::initialize_pipeline
initialize_pipeline()
void MayaFlux::Buffers::ShaderProcessor::initialize_pipeline (const std::shared_ptr< Buffer > & buffer) protected virtual
Reimplemented in MayaFlux::Buffers::RenderProcessor.
Definition at line 411 of file ShaderProcessor.cpp.
{
    if (m_shader_id == Portal::Graphics::INVALID_SHADER) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot create pipeline without shader");
        return;
    }
    auto& compute_press = Portal::Graphics::get_compute_press();
    std::map<uint32_t, std::vector<std::pair<std::string, ShaderBinding>>> bindings_by_set;
    for (const auto& [name, binding] : m_config.bindings) {
        bindings_by_set[binding.set].emplace_back(name, binding);
    }
    std::vector<std::vector<Portal::Graphics::DescriptorBindingConfig>> descriptor_sets;
    for (const auto& [set_index, set_bindings] : bindings_by_set) {
        std::vector<Portal::Graphics::DescriptorBindingConfig> set_config;
        for (const auto& [name, binding] : set_bindings) {
            set_config.emplace_back(binding.set, binding.binding, binding.type);
        }
        descriptor_sets.push_back(set_config);
    }
    m_pipeline_id = compute_press.create_pipeline(
        m_shader_id,
        descriptor_sets,
        m_config.push_constant_size);
    if (m_pipeline_id == Portal::Graphics::INVALID_COMPUTE_PIPELINE) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Failed to create compute pipeline");
        return;
    }
    on_pipeline_created(m_pipeline_id);
    MF_INFO(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Compute pipeline created (ID: {}, {} descriptor sets, {} bytes push constants)",
        m_pipeline_id, descriptor_sets.size(), m_config.push_constant_size);
}
References MayaFlux::Buffers::ShaderProcessorConfig::bindings, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, MayaFlux::Portal::Graphics::INVALID_SHADER, m_config, m_pipeline_id, m_shader_id, MF_ERROR, MF_INFO, on_pipeline_created(), MayaFlux::Buffers::ShaderProcessorConfig::push_constant_size, and set_config().
Referenced by processing_function().