MayaFlux: MayaFlux::Core::NetworkSubsystem::initialize
initialize()
void MayaFlux::Core::NetworkSubsystem::initialize (SubsystemProcessingHandle & handle) override virtual
Initialize with a handle provided by SubsystemManager.
Parameters
handle Processing handle providing access to buffer and node operations
The handle is borrowed - subsystem doesn't own it but uses it throughout its lifetime. This is where subsystems configure their processing resources, create initial nodes, setup buffer configurations, and prepare for operation.
The handle provides token-scoped access to both buffer processing and node graph operations, ensuring the subsystem operates within its designated processing domain with proper thread safety and resource isolation.
Implements MayaFlux::Core::ISubsystem.
Definition at line 38 of file NetworkSubsystem.cpp.
{
    MF_INFO(Journal::Component::Core, Journal::Context::Init,
        "Initializing Network Subsystem...");
    m_handle = &handle;
    if (m_config.udp.enabled) {
        initialize_udp_backend();
    }
    if (m_config.tcp.enabled) {
        initialize_tcp_backend();
    }
    if (m_config.shared_memory.enabled) {
        initialize_shm_backend();
    }
    register_backend_service();
    Portal::Network::initialize(m_network_service.get());
    m_ready.store(true);
    MF_INFO(Journal::Component::Core, Journal::Context::Init,
        "Network Subsystem initialized with {} backend(s)", m_backends.size());
}
References MayaFlux::Journal::Core, MayaFlux::Core::UDPBackendInfo::enabled, MayaFlux::Core::TCPBackendInfo::enabled, MayaFlux::Core::SharedMemoryBackendInfo::enabled, MayaFlux::Journal::Init, MayaFlux::Portal::Network::initialize(), initialize_shm_backend(), initialize_tcp_backend(), initialize_udp_backend(), m_backends, m_config, m_handle, m_network_service, m_ready, MF_INFO, register_backend_service(), MayaFlux::Core::GlobalNetworkConfig::shared_memory, MayaFlux::Core::GlobalNetworkConfig::tcp, and MayaFlux::Core::GlobalNetworkConfig::udp.