MayaFlux: MayaFlux::Kakshya::DataAccess::gpu_buffer
gpu_buffer()
auto MayaFlux::Kakshya::DataAccess::gpu_buffer () const inline
Get raw buffer info for GPU upload.
Returns
Tuple of (void* data, size_t bytes, format_hint)
Definition at line 46 of file DataAccess.hpp.
    {
        return std::visit([&](auto& vec) {
            using T = typename std::decay_t<decltype(vec)>::value_type;
            return std::make_tuple(
                static_cast<const void*>(vec.data()),
                vec.size() * sizeof(T),
                get_format_hint<T>());
        },
            m_variant);
    }
Referenced by MayaFlux::Buffers::download_from_gpu(), MayaFlux::Buffers::VKBuffer::set_data(), MayaFlux::Buffers::upload_device_local(), and MayaFlux::Buffers::upload_host_visible().