MayaFlux: MayaFlux::Core::InputManager::setup_osc_bridge
setup_osc_bridge()
void MayaFlux::Core::InputManager::setup_osc_bridge (const OSCConfigInfo & osc_config)
Setup OSC bridge if enabled in config.
Definition at line 434 of file InputManager.cpp.
{
    if (!osc_config.enabled) {
        return;
    }
    if (!m_network_service) {
        m_network_service = Registry::BackendRegistry::instance()
                                .get_service<Registry::Service::NetworkService>();
    }
    if (!m_network_service) {
        MF_WARN(Journal::Component::Core, Journal::Context::InputManagement,
            "OSC bridge requested but NetworkService not available");
        return;
    }
    EndpointInfo ep;
    ep.transport = NetworkTransport::UDP;
    ep.role = EndpointRole::BIDIRECTIONAL;
    ep.local_port = osc_config.receive_port;
    ep.remote_address = osc_config.send_address;
    ep.remote_port = osc_config.send_port;
    ep.label = "osc_input";
    m_osc_endpoint_id = m_network_service->open_endpoint(ep);
    if (m_osc_endpoint_id == 0) {
        MF_ERROR(Journal::Component::Core, Journal::Context::InputManagement,
            "Failed to open UDP endpoint for OSC on port {}",
            osc_config.receive_port);
        return;
    }
    m_network_service->set_endpoint_receive_callback(m_osc_endpoint_id,
        [this](uint64_t, const uint8_t* data, size_t size, std::string_view) {
            auto parsed = OscParser::parse(data, size);
            if (parsed) {
                enqueue(*parsed);
            }
        });
    MF_INFO(Journal::Component::Core, Journal::Context::InputManagement,
        "OSC bridge active on port {}", osc_config.receive_port);
}
References MayaFlux::Core::BIDIRECTIONAL, MayaFlux::Journal::Core, MayaFlux::Core::OSCConfigInfo::enabled, enqueue(), MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Journal::InputManagement, MayaFlux::Registry::BackendRegistry::instance(), MayaFlux::Core::EndpointInfo::label, MayaFlux::Core::EndpointInfo::local_port, m_network_service, m_osc_endpoint_id, MF_ERROR, MF_INFO, MF_WARN, MayaFlux::Registry::Service::NetworkService::open_endpoint, MayaFlux::Core::OscParser::parse(), MayaFlux::Core::OSCConfigInfo::receive_port, MayaFlux::Core::EndpointInfo::remote_address, MayaFlux::Core::EndpointInfo::remote_port, MayaFlux::Core::EndpointInfo::role, MayaFlux::Core::OSCConfigInfo::send_address, MayaFlux::Core::OSCConfigInfo::send_port, MayaFlux::Registry::Service::NetworkService::set_endpoint_receive_callback, size, MayaFlux::Core::EndpointInfo::transport, and MayaFlux::Core::UDP.