MayaFlux: MayaFlux::Buffers::DataWriteProcessor::upload_primary
upload_primary()
void MayaFlux::Buffers::DataWriteProcessor::upload_primary (const std::shared_ptr< VKBuffer > & vk, std::vector< Kakshya::DataVariant > & slots) private
Definition at line 193 of file DataWriteProcessor.cpp.
{
    if (is_vertex_modality(m_modality)) {
        upload_vertex(vk, slots);
    } else if (is_texture_modality(m_modality)) {
        upload_texture(vk, slots[0]);
    } else {
        upload_raw(vk, slots[0]);
    }
}
References is_texture_modality(), is_vertex_modality(), m_modality, upload_raw(), upload_texture(), and upload_vertex().
Referenced by processing_function().