MayaFlux: MayaFlux::Core::InputSubsystem::initialize_midi_backend
initialize_midi_backend()
void MayaFlux::Core::InputSubsystem::initialize_midi_backend () private
Definition at line 320 of file InputSubsystem.cpp.
{
    MIDIBackend::Config midi_config;
    midi_config.input_port_filters = m_config.midi.input_port_filters;
    midi_config.output_port_filters = m_config.midi.output_port_filters;
    midi_config.auto_open_inputs = m_config.midi.auto_open_inputs;
    midi_config.auto_open_outputs = m_config.midi.auto_open_outputs;
    midi_config.enable_virtual_port = m_config.midi.enable_virtual_port;
    midi_config.virtual_port_name = m_config.midi.virtual_port_name;
    auto midi = std::make_unique<MIDIBackend>(midi_config);
    if (add_backend(std::move(midi))) {
        if (m_config.midi.auto_open_inputs) {
            auto* backend = dynamic_cast<MIDIBackend*>(get_backend(InputType::MIDI));
            for (const auto& dev : backend->get_devices()) {
                if (dev.is_input) {
                    backend->open_device(dev.id);
                }
            }
        }
    }
}
References add_backend(), MayaFlux::Core::MIDIBackend::Config::auto_open_inputs, MayaFlux::Core::MIDIBackendInfo::auto_open_inputs, MayaFlux::Core::MIDIBackend::Config::auto_open_outputs, MayaFlux::Core::MIDIBackendInfo::auto_open_outputs, MayaFlux::Core::MIDIBackend::Config::enable_virtual_port, MayaFlux::Core::MIDIBackendInfo::enable_virtual_port, get_backend(), MayaFlux::Core::MIDIBackend::Config::input_port_filters, MayaFlux::Core::MIDIBackendInfo::input_port_filters, m_config, MayaFlux::Core::GlobalInputConfig::midi, MayaFlux::Core::MIDI, MayaFlux::Core::MIDIBackend::open_device(), MayaFlux::Core::MIDIBackend::Config::output_port_filters, MayaFlux::Core::MIDIBackendInfo::output_port_filters, MayaFlux::Core::MIDIBackend::Config::virtual_port_name, and MayaFlux::Core::MIDIBackendInfo::virtual_port_name.
Referenced by initialize().