MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::lock
lock()
void MayaFlux::Kakshya::VideoStreamContainer::lock () inline override virtual
Acquire a lock for thread-safe access.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 87 of file VideoStreamContainer.hpp.
{ m_data_mutex.lock(); }
Referenced by add_region_group(), clear(), get_all_region_groups(), get_default_processor(), get_frame_pixels(), get_region_data(), get_region_group(), get_region_group_data(), get_segments_data(), has_data(), notify_state_change(), register_state_change_callback(), remove_region_group(), and unregister_state_change_callback().