MayaFlux: MayaFlux::Buffers::FormaProcessor::FormaProcessor
FormaProcessor()
MayaFlux::Buffers::FormaProcessor::FormaProcessor (Portal::Graphics::PrimitiveTopology topology) explicit
Definition at line 10 of file FormaProcessor.cpp.
    : m_topology(topology)
{
    m_processing_token = ProcessingToken::GRAPHICS_BACKEND;
    switch (topology) {
    case Portal::Graphics::PrimitiveTopology::POINT_LIST:
        m_stride = Kakshya::VertexLayout::for_points().stride_bytes;
        break;
    case Portal::Graphics::PrimitiveTopology::LINE_LIST:
    case Portal::Graphics::PrimitiveTopology::LINE_STRIP:
        m_stride = Kakshya::VertexLayout::for_lines().stride_bytes;
        break;
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST:
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP:
    default:
        m_stride = Kakshya::VertexLayout::for_meshes().stride_bytes;
        break;
    }
}
References MayaFlux::Kakshya::VertexLayout::for_lines(), MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Kakshya::VertexLayout::for_points(), MayaFlux::Buffers::GRAPHICS_BACKEND, MayaFlux::Portal::Graphics::LINE_LIST, MayaFlux::Portal::Graphics::LINE_STRIP, MayaFlux::Buffers::BufferProcessor::m_processing_token, m_stride, MayaFlux::Portal::Graphics::POINT_LIST, MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Portal::Graphics::TRIANGLE_LIST, and MayaFlux::Portal::Graphics::TRIANGLE_STRIP.