MayaFlux: MayaFlux::Core::InputSubsystem::shutdown
shutdown()
void MayaFlux::Core::InputSubsystem::shutdown () override virtual
Shutdown and cleanup subsystem resources.
Implements MayaFlux::Core::ISubsystem.
Definition at line 165 of file InputSubsystem.cpp.
{
    if (!m_ready.load())
        return;
    stop();
    {
        std::unique_lock lock(m_backends_mutex);
        for (auto& [type, backend] : m_backends) {
            backend->shutdown();
        }
        m_backends.clear();
    }
    m_handle->inputs.unregister();
    auto& registry = Registry::BackendRegistry::instance();
    registry.unregister_service<Registry::Service::InputService>();
    m_input_service.reset();
    m_ready.store(false);
    MF_INFO(Journal::Component::Core, Journal::Context::InputSubsystem,
        "Input Subsystem shutdown complete");
}
References MayaFlux::Journal::Core, MayaFlux::Core::SubsystemProcessingHandle::inputs, MayaFlux::Journal::InputSubsystem, MayaFlux::Registry::BackendRegistry::instance(), m_backends, m_backends_mutex, m_handle, m_input_service, m_ready, MF_INFO, stop(), and MayaFlux::Core::InputManagerHandle::unregister().
Referenced by ~InputSubsystem().