MayaFlux: MayaFlux::Portal::Forma::Context::on_held
on_held()
void MayaFlux::Portal::Forma::Context::on_held (uint32_t id, IO::Keys key, KeyFn fn)
Called repeatedly while a key is held and the element has focus.
Fires on initial press and continues on each repeat tick until the key is released. Useful for continuous adjustments (arrow key nudging, value increments) without requiring the user to repeatedly press.
Parameters
id Element id to bind to.
key The key to listen for.
fn Callback receiving element id, fired on press and each repeat.
Definition at line 100 of file Context.cpp.
{
    const int key_code = static_cast<int>(key);
    m_callbacks[id].key_held[key_code] = std::move(fn);
    if (!m_registered_keys[key_code].has_held) {
        const std::string key_name = std::to_string(key_code);
        m_event_manager.add_event(
            std::make_shared<Vruta::Event>(
                Kriya::key_held(m_window, key,
                    [this, key]() { handle_key_held(key); })),
            m_name + "_key_held_" + key_name);
        m_registered_keys[key_code].has_held = true;
    }
}
References MayaFlux::Vruta::EventManager::add_event(), handle_key_held(), MayaFlux::Kriya::key_held(), m_callbacks, m_event_manager, m_name, m_registered_keys, and m_window.
Referenced by key_step().