MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::apply_output_scale
apply_output_scale()
void MayaFlux::Nodes::Network::NodeNetwork::apply_output_scale () protected
Apply m_output_scale to m_last_audio_buffer.
Call at the end of each concrete process_batch() after all samples are written.
Definition at line 26 of file NodeNetwork.cpp.
{
    if (m_output_scale == 1.0)
        return;
    for (auto& s : m_last_audio_buffer)
        s *= m_output_scale;
}
References m_last_audio_buffer, and m_output_scale.
Referenced by MayaFlux::Nodes::Network::ModalNetwork::process_batch(), MayaFlux::Nodes::Network::ResonatorNetwork::process_batch(), and MayaFlux::Nodes::Network::WaveguideNetwork::process_batch().