MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::load_shader
load_shader()
ShaderID MayaFlux::Portal::Graphics::ShaderFoundry::load_shader (const std::string & filepath, std::optional< ShaderStage > stage = std::nullopt, const std::string & entry_point = "main")
Compile shader from file path.
Parameters
filepath Path to shader file (.comp, .vert, .frag, .spv, etc.)
stage Optional stage override (auto-detected from extension if omitted)
entry_point Entry point function name (default: "main")
Returns
ID of compiled shader module, or INVALID_SHADER on failure
Supports:
GLSL files: .comp, .vert, .frag, .geom, .tesc, .tese
SPIR-V files: .spv
Stage auto-detection: .comp → COMPUTE .vert → VERTEX .frag → FRAGMENT .geom → GEOMETRY .tesc → TESS_CONTROL .tese → TESS_EVALUATION
Caching: If the same file is compiled twice, returns cached version. Use invalidate_cache() or hot_reload() to force recompilation.
Definition at line 265 of file ShaderFoundry.cpp.
{
    auto cache_it = m_shader_filepath_cache.find(filepath);
    if (cache_it != m_shader_filepath_cache.end()) {
        MF_DEBUG(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Using cached shader ID for: {}", filepath);
        return cache_it->second;
    }
    auto shader_module = compile_from_file(filepath, stage, entry_point);
    if (!shader_module) {
        return INVALID_SHADER;
    }
    ShaderID id = m_next_shader_id++;
    ShaderState& state = m_shaders[id];
    state.module = shader_module;
    state.filepath = filepath;
    state.stage = stage.value_or(
        detect_stage_from_extension(filepath).value_or(ShaderStage::COMPUTE));
    state.entry_point = entry_point;
    m_shader_filepath_cache[filepath] = id;
    return id;
}
References compile_from_file(), MayaFlux::Portal::Graphics::COMPUTE, detect_stage_from_extension(), MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::entry_point, MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::filepath, MayaFlux::Portal::Graphics::INVALID_SHADER, m_next_shader_id, m_shader_filepath_cache, m_shaders, MF_DEBUG, MayaFlux::Journal::Portal, MayaFlux::Journal::ShaderCompilation, and MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::stage.
Referenced by reload_shader(), and MayaFlux::Buffers::RenderProcessor::RenderProcessor().