MayaFlux: MayaFlux::IO::AudioEncodeContext::encode_frames
encode_frames()
bool MayaFlux::IO::AudioEncodeContext::encode_frames (std::span< const double > interleaved, uint32_t num_frames, FFmpegMuxContext & mux)
Encode a block of interleaved double-precision PCM frames.
Converts input via SwrContext, writes converted samples into the FIFO, then drains the FIFO in encoder-frame-sized chunks. For encoders with frame_size == 0 (PCM, some raw formats) the entire FIFO content is submitted as one frame per call.
Non-blocking: returns false only on a hard encode error, not on FIFO underrun. Safe to call with any number of frames per call.
Parameters
interleaved Interleaved samples in double precision.
num_frames Number of PCM frames (samples / channels).
mux Mux context to receive encoded packets.
Returns
True on success.
Definition at line 228 of file AudioEncodeContext.cpp.
{
    if (!is_valid())
        return false;
    uint8_t** conv = nullptr;
    int linesize = 0;
    int alloc = av_samples_alloc_array_and_samples(
        &conv, &linesize,
        static_cast<int>(m_channels),
        static_cast<int>(num_frames),
        codec_context->sample_fmt, 0);
    if (alloc < 0 || !conv) {
        m_last_error = "av_samples_alloc_array_and_samples failed during encode";
        return false;
    }
    const auto* src = reinterpret_cast<const uint8_t*>(interleaved.data());
    int converted = swr_convert(
        swr_context,
        conv, static_cast<int>(num_frames),
        &src, static_cast<int>(num_frames));
    if (converted < 0) {
        av_freep(static_cast<void*>(&conv[0]));
        av_freep(static_cast<void*>(&conv));
        m_last_error = "swr_convert failed";
        return false;
    }
    int written = av_audio_fifo_write(fifo,
        reinterpret_cast<void**>(conv), converted);
    av_freep(static_cast<void*>(&conv[0]));
    av_freep(static_cast<void*>(&conv));
    if (written < converted) {
        m_last_error = "av_audio_fifo_write wrote fewer samples than expected";
        return false;
    }
    int frame_size = codec_context->frame_size > 0
        ? codec_context->frame_size
        : av_audio_fifo_size(fifo);
    while (av_audio_fifo_size(fifo) >= frame_size) {
        if (!send_fifo_frame(mux, false))
            return false;
    }
    return true;
}
References codec_context, fifo, is_valid(), m_channels, m_last_error, send_fifo_frame(), and swr_context.
Referenced by MayaFlux::IO::SoundFileWriter::worker_loop().