MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::get_device
get_device()
vk::Device MayaFlux::Portal::Graphics::ShaderFoundry::get_device () const
Get logical device handle.
Definition at line 1288 of file ShaderFoundry.cpp.
{
    return m_backend->get_context().get_device();
}
References m_backend.
Referenced by allocate_descriptor_set(), begin_timestamp(), cleanup_descriptor_resources(), MayaFlux::Portal::Graphics::ComputePress::cleanup_pipelines(), MayaFlux::Portal::Graphics::RenderFlow::cleanup_pipelines(), cleanup_shader_modules(), cleanup_sync_objects(), compile_from_file(), compile_from_source(), compile_from_spirv(), MayaFlux::Portal::Graphics::RenderFlow::create_pipeline(), MayaFlux::Portal::Graphics::ComputePress::create_pipeline(), MayaFlux::Portal::Graphics::ComputePress::destroy_pipeline(), MayaFlux::Portal::Graphics::RenderFlow::destroy_pipeline(), destroy_shader(), free_all_command_buffers(), get_timestamp_result(), MayaFlux::Portal::Graphics::ComputePress::initialize(), initialize(), is_fence_signaled(), MayaFlux::Portal::Graphics::ComputePress::shutdown(), MayaFlux::Portal::Graphics::RenderFlow::shutdown(), stop(), submit_async(), submit_with_signal(), update_descriptor_buffer(), update_descriptor_image(), update_descriptor_storage_image(), wait_for_fence(), and wait_for_fences().