MayaFlux: MayaFlux::Vruta::TaskScheduler::process_token
process_token()
void MayaFlux::Vruta::TaskScheduler::process_token (ProcessingToken token, uint64_t processing_units = 1)
Process all tasks for a specific processing domain.
Parameters
token Processing domain to advance
processing_units Number of units to process (samples/frames/etc.)
Advances the appropriate clock and processes all tasks that are ready to execute in the specified domain. This is the main entry point for backend-specific processing loops.
Definition at line 217 of file Scheduler.cpp.
{
    drain_pending_tasks();
    auto processor_it = m_token_processors.find(token);
    if (processor_it != m_token_processors.end()) {
        auto tasks = get_tasks_for_token(token);
        processor_it->second(tasks, processing_units);
    } else {
        process_default(token, processing_units);
    }
    if (token == ProcessingToken::SAMPLE_ACCURATE) {
        pump_cross(DelayContext::SAMPLE_BASED, ProcessingToken::SAMPLE_ACCURATE, processing_units);
    } else if (token == ProcessingToken::FRAME_ACCURATE) {
        pump_cross(DelayContext::FRAME_BASED, ProcessingToken::FRAME_ACCURATE, processing_units);
    }
    static uint64_t cleanup_counter = 0;
    if (++cleanup_counter % (static_cast<uint64_t>(m_cleanup_threshold * 2)) == 0) {
        cleanup_completed_tasks();
    }
}
References cleanup_completed_tasks(), drain_pending_tasks(), MayaFlux::Vruta::FRAME_ACCURATE, MayaFlux::Vruta::FRAME_BASED, get_tasks_for_token(), m_cleanup_threshold, m_token_processors, process_default(), pump_cross(), MayaFlux::Vruta::SAMPLE_ACCURATE, and MayaFlux::Vruta::SAMPLE_BASED.
Referenced by process_all_tokens().