MayaFlux: MayaFlux::Buffers::VKBuffer::set_data
set_data()
void MayaFlux::Buffers::VKBuffer::set_data (const std::vector< Kakshya::DataVariant > & data)
Write data into the buffer.
If the buffer is host-visible and mapped the provided data is copied into the mapped memory. For device-local buffers, a BufferUploadProcessor must be present in the processing chain to perform the staging/upload.
Parameters
data Vector of Kakshya::DataVariant containing the payload to copy.
Definition at line 49 of file VKBuffer.cpp.
{
    if (!is_initialized()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "Cannot set_data on uninitialized VKBuffer. Register with BufferManager first.");
        return;
    }
    if (data.empty()) {
        clear();
        return;
    }
    if (is_host_visible() && m_resources.mapped_ptr) {
        Kakshya::DataAccess accessor(
            const_cast<Kakshya::DataVariant&>(data[0]),
            {},
            m_modality);
        auto [ptr, bytes, format_hint] = accessor.gpu_buffer();
        if (bytes > m_size_bytes) {
            error<std::runtime_error>(
                Journal::Component::Buffers,
                Journal::Context::BufferManagement,
                std::source_location::current(),
                "Data size {} exceeds buffer capacity {}",
                bytes, m_size_bytes);
        }
        std::memcpy(m_resources.mapped_ptr, ptr, bytes);
        mark_dirty_range(0, m_size_bytes);
        infer_dimensions_from_data(bytes);
    } else {
        MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
            "set_data() on device-local buffer requires BufferUploadProcessor in chain");
    }
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, clear(), MayaFlux::Kakshya::DataAccess::gpu_buffer(), infer_dimensions_from_data(), is_host_visible(), is_initialized(), m_modality, m_resources, m_size_bytes, MayaFlux::Buffers::VKBufferResources::mapped_ptr, mark_dirty_range(), and MF_WARN.