MayaFlux: MayaFlux::Nodes::GpuSync::SDFNode::rebuild
rebuild()
void MayaFlux::Nodes::GpuSync::SDFNode::rebuild () private
Definition at line 63 of file SDFNode.cpp.
{
    auto data = Kinesis::generate_sdf_mesh(
        m_field, m_bounds_min, m_bounds_max,
        m_res_x, m_res_y, m_res_z, m_iso_level);
    if (!data.is_valid()) {
        MF_WARN(Journal::Component::Nodes, Journal::Context::NodeProcessing,
            "SDFNode: no isosurface crossings at iso_level={}", m_iso_level);
        clear_mesh();
        m_dirty = false;
        return;
    }
    set_mesh(data);
    MeshWriterNode::compute_frame();
    m_dirty = false;
}
References MayaFlux::Nodes::GpuSync::MeshWriterNode::clear_mesh(), MayaFlux::Nodes::GpuSync::MeshWriterNode::compute_frame(), MayaFlux::Kinesis::generate_sdf_mesh(), m_bounds_max, m_bounds_min, m_dirty, m_field, m_iso_level, m_res_x, m_res_y, m_res_z, MF_WARN, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, and MayaFlux::Nodes::GpuSync::MeshWriterNode::set_mesh().
Referenced by compute_frame(), and SDFNode().