MayaFlux: MayaFlux::Buffers::VKBuffer::is_initialized
is_initialized()
bool MayaFlux::Buffers::VKBuffer::is_initialized () const inline
Check whether Vulkan handles are present (buffer registered)
Definition at line 287 of file VKBuffer.hpp.
{ return m_resources.buffer != VK_NULL_HANDLE; }
Referenced by clear(), get_data(), get_device_address(), resize(), and set_data().