MayaFlux: MayaFlux::IO::VideoFileReader::stop_decode_thread
stop_decode_thread()
void MayaFlux::IO::VideoFileReader::stop_decode_thread () private
Definition at line 492 of file VideoFileReader.cpp.
{
    if (!m_decode_active.load())
        return;
    m_decode_stop.store(true);
    m_decode_cv.notify_all();
    if (m_decode_thread.joinable())
        m_decode_thread.join();
    m_decode_active.store(false);
}
References m_decode_active, m_decode_cv, m_decode_stop, and m_decode_thread.
Referenced by close(), seek(), and start_decode_thread().