MayaFlux: MayaFlux::Core::AudioSubsystem::register_backend_service
register_backend_service()
void MayaFlux::Core::AudioSubsystem::register_backend_service () private
Definition at line 220 of file AudioSubsystem.cpp.
{
    auto svc = std::make_shared<Registry::Service::AudioBackendService>();
    svc->get_output_snapshot = [this]() -> std::span<const double> {
        const double* ptr = m_snapshot_ptr.load(std::memory_order_acquire);
        uint32_t sz = m_snapshot_size.load(std::memory_order_acquire);
        if (!ptr || sz == 0)
            return {};
        return { ptr, sz };
    };
    svc->register_output_observer = [this](
                                        std::function<void(const double*, uint32_t)> cb) -> uint32_t {
        uint32_t id = m_next_observer_id.fetch_add(1, std::memory_order_relaxed);
#ifdef MAYAFLUX_PLATFORM_MACOS
        const ObserverMap* current = m_observers_ptr.load(std::memory_order_acquire);
        const ObserverMap* next;
        do {
            auto* copy = new ObserverMap(*current);
            (*copy)[id] = cb;
            next = copy;
        } while (!m_observers_ptr.compare_exchange_weak(
            current, next,
            std::memory_order_release, std::memory_order_acquire));
        retire_observers(current);
#else
        auto current = m_observers.load(std::memory_order_acquire);
        std::shared_ptr<ObserverMap> next;
        do {
            next = std::make_shared<ObserverMap>(*current);
            (*next)[id] = cb;
        } while (!m_observers.compare_exchange_weak(
            current, next,
            std::memory_order_release, std::memory_order_acquire));
#endif
        return id;
    };
    svc->unregister_output_observer = [this](uint32_t id) {
#ifdef MAYAFLUX_PLATFORM_MACOS
        const ObserverMap* current = m_observers_ptr.load(std::memory_order_acquire);
        const ObserverMap* next;
        do {
            auto* copy = new ObserverMap(*current);
            copy->erase(id);
            next = copy;
        } while (!m_observers_ptr.compare_exchange_weak(
            current, next,
            std::memory_order_release, std::memory_order_acquire));
        retire_observers(current);
#else
        auto current = m_observers.load(std::memory_order_acquire);
        std::shared_ptr<ObserverMap> next;
        do {
            next = std::make_shared<ObserverMap>(*current);
            next->erase(id);
        } while (!m_observers.compare_exchange_weak(
            current, next,
            std::memory_order_release, std::memory_order_acquire));
#endif
    };
    m_audio_backend_service = svc;
    Registry::BackendRegistry::instance()
        .register_service<Registry::Service::AudioBackendService>(
            [svc]() -> void* { return svc.get(); });
}
References id, MayaFlux::Registry::BackendRegistry::instance(), m_audio_backend_service, m_next_observer_id, m_observers, m_snapshot_ptr, m_snapshot_size, and MayaFlux::Registry::BackendRegistry::register_service().
Referenced by initialize().