MayaFlux: MayaFlux::Kakshya::PlotProcessor::process
process()
void MayaFlux::Kakshya::PlotProcessor::process (const std::shared_ptr< SignalSourceContainer > & container) override virtual
Acquire data from all bound sources and write into the container.
For each bound series: acquires from source, writes into container m_data, then copies m_data into processed_data. Unbound series are left unchanged. Called from the graphics thread by Forma before the geometry function runs.
Implements MayaFlux::Kakshya::DataProcessor.
Definition at line 146 of file PlotProcessor.cpp.
{
    auto plot = std::dynamic_pointer_cast<PlotContainer>(container);
    if (!plot) {
        MF_ERROR(C, X, "PlotProcessor::process: container is not a PlotContainer");
        return;
    }
    m_processing.store(true, std::memory_order_release);
    for (auto& [idx, b] : m_bindings) {
        if (idx >= plot->series_count())
            continue;
        thread_local std::vector<double> staging;
        staging.resize(plot->series_size(idx));
        {
            auto frame = plot->get_frame(idx).as<double>();
            if (frame.size() == staging.size()) {
                std::ranges::copy(frame, staging.begin());
            } else {
                std::ranges::fill(staging, 0.0);
            }
        }
        switch (b.source_type) {
        case SourceType::NODE:
            acquire_from_node(b, staging);
            break;
        case SourceType::AUDIO_BUFFER:
            acquire_from_audio_buffer(b, staging);
            break;
        case SourceType::NETWORK:
            acquire_from_network(b, staging);
            break;
        case SourceType::CALLABLE:
            acquire_from_callable(b, staging);
            break;
        case SourceType::RAW:
            acquire_from_raw(b, staging);
            break;
        }
        plot->write_series(idx, staging);
    }
    auto& src = plot->get_data();
    auto& dst = plot->get_processed_data();
    dst.resize(src.size());
    for (size_t i = 0; i < src.size(); ++i)
        dst[i] = src[i];
    m_processing.store(false, std::memory_order_release);
}
References acquire_from_audio_buffer(), acquire_from_callable(), acquire_from_network(), acquire_from_node(), acquire_from_raw(), AUDIO_BUFFER, b, CALLABLE, m_bindings, m_processing, MF_ERROR, NETWORK, NODE, and RAW.