MayaFlux: MayaFlux::Kriya::BufferPipeline::execute_for_cycles
execute_for_cycles()
void MayaFlux::Kriya::BufferPipeline::execute_for_cycles (uint64_t cycles = 0)
Execute the pipeline for a specified number of cycles.
Parameters
cycles Number of processing cycles to execute
Schedules the pipeline to run for the given number of cycles. Each cycle processes all operations once. Execution is asynchronous via the scheduler. The pipeline remains alive until all cycles complete.
Exceptions
std::runtime_error if pipeline has no scheduler
Note
Execution happens asynchronously - this function returns immediately.
Definition at line 122 of file BufferPipeline.cpp.
{
    if (!m_scheduler) {
        error<std::runtime_error>(Journal::Component::Kriya,
            Journal::Context::CoroutineScheduling,
            std::source_location::current(),
            "Pipeline requires scheduler for execution");
    }
    auto self = shared_from_this();
    if (cycles == 0) {
        cycles = UINT64_MAX;
        m_continuous_execution = true;
    }
    m_max_cycles = cycles;
    auto routine = std::make_shared<Vruta::SoundRoutine>(
        execute_internal(cycles, 0));
    m_scheduler->add_task(std::move(routine));
    m_active_self = self;
}
References MayaFlux::Vruta::TaskScheduler::add_task(), MayaFlux::Journal::CoroutineScheduling, execute_internal(), MayaFlux::Journal::Kriya, m_active_self, m_continuous_execution, m_max_cycles, and m_scheduler.
Referenced by execute_continuous().