MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::set_memory_layout
set_memory_layout()
void MayaFlux::Kakshya::SoundStreamContainer::set_memory_layout (MemoryLayout layout) override virtual
Set the memory layout for this container.
Parameters
layout New memory layout to use
Note
May trigger data reorganization if implementation supports both layouts
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 62 of file SoundStreamContainer.cpp.
{
    if (layout != m_structure.memory_layout) {
        std::unique_lock lock(m_data_mutex);
        reorganize_data_layout(layout);
        m_structure.memory_layout = layout;
        setup_dimensions();
    }
}
References lock(), m_data_mutex, m_structure, MayaFlux::Kakshya::ContainerDataStructure::memory_layout, reorganize_data_layout(), and setup_dimensions().