MayaFlux: Lila::ServerThread::request_stop
request_stop()
void Lila::ServerThread::request_stop () inline noexcept
Definition at line 191 of file ServerThread.hpp.
    {
        if (m_stop_flag) {
            m_stop_flag->store(true, std::memory_order_release);
        }
    }
References m_stop_flag.
Referenced by operator=(), Lila::Server::stop(), and ~ServerThread().