MayaFlux: MayaFlux::Core::OscParser::write_blob
write_blob()
void MayaFlux::Core::OscParser::write_blob (std::vector< uint8_t > & out, const std::vector< uint8_t > & blob) static private
Definition at line 147 of file OscParser.cpp.
{
    write_int32(out, static_cast<int32_t>(blob.size()));
    out.insert(out.end(), blob.begin(), blob.end());
    size_t padded = padded_size(blob.size());
    out.resize(out.size() + (padded - blob.size()), 0);
}
References padded_size(), and write_int32().
Referenced by serialize().