MayaFlux: Lila::Server::handle_client
handle_client()
void Lila::Server::handle_client (int client_fd) private
Handles communication with a single client.
Parameters
client_fd Client file descriptor
Definition at line 260 of file Server.cpp.
{
    int enable = 1;
    if (setsockopt(client_fd, IPPROTO_TCP, TCP_NODELAY, reinterpret_cast<char*>(&enable), sizeof(enable)) < 0) {
        LILA_WARN(Emitter::SERVER, "Failed to set TCP_NODELAY on client fd " + std::to_string(client_fd) + ": " + socket_error_string(socket_errno()));
    }
    ClientInfo client_info {
        .fd = client_fd,
        .session_id = "",
        .connected_at = std::chrono::system_clock::now()
    };
    {
        std::unique_lock lock(m_clients_mutex);
        m_connected_clients[client_fd] = client_info;
    }
    if (m_connect_handler) {
        m_connect_handler(client_info);
    }
    m_event_bus.publish(StreamEvent { EventType::ClientConnected, client_info });
    LILA_INFO(Emitter::SERVER, "Client connected fd: " + std::to_string(client_fd));
    while (m_running) {
        auto message = read_message(client_fd);
        if (!message) {
            if (message.error() != "timeout" && message.error() != "would_block") {
                break;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(8));
            continue;
        }
        if (message->empty())
            continue;
        if (message->starts_with('@')) {
            process_control_message(client_fd, message->substr(1));
            continue;
        }
        if (m_message_handler) {
            auto response = m_message_handler(*message);
            if (response) {
                if (!send_message(client_fd, *response)) {
                    LILA_WARN(Emitter::SERVER, "Failed to send response to client fd " + std::to_string(client_fd));
                    break;
                }
            } else {
                if (!send_message(client_fd, "{\"status\":\"error\",\"message\":\"" + response.error() + "\"}")) {
                    LILA_WARN(Emitter::SERVER, "Failed to send error response to client fd " + std::to_string(client_fd));
                    break;
                }
            }
        }
    }
    cleanup_client(client_fd);
}
References cleanup_client(), Lila::ClientInfo::fd, LILA_INFO, LILA_WARN, m_clients_mutex, m_connect_handler, m_connected_clients, m_event_bus, m_message_handler, m_running, process_control_message(), Lila::EventBus::publish(), read_message(), send_message(), Lila::socket_errno(), and Lila::socket_error_string().