MayaFlux: MayaFlux::Nodes::GpuSync::PathGeneratorNode::generate_curve_segment
generate_curve_segment()
void MayaFlux::Nodes::GpuSync::PathGeneratorNode::generate_curve_segment (const std::vector< LineVertex > & curve_verts, size_t start_idx, std::vector< LineVertex > & output) private
Definition at line 111 of file PathGeneratorNode.cpp.
{
    if (start_idx + 3 >= curve_verts.size()) {
        return;
    }
    Eigen::MatrixXd segment_controls(3, 4);
    for (Eigen::Index i = 0; i < 4; ++i) {
        const auto& pt = curve_verts[start_idx + i].position;
        segment_controls.col(i) << pt.x, pt.y, pt.z;
    }
    Eigen::MatrixXd interpolated = Kinesis::generate_interpolated_points(
        segment_controls,
        m_samples_per_segment,
        m_mode,
        m_tension);
    if (m_arc_length_parameterization) {
        interpolated = Kinesis::reparameterize_by_arc_length(
            interpolated,
            m_samples_per_segment);
    }
    for (Eigen::Index i = 0; i < interpolated.cols() - 1; ++i) {
        float t0 = static_cast<float>(i) / static_cast<float>(interpolated.cols() - 1);
        float t1 = static_cast<float>(i + 1) / static_cast<float>(interpolated.cols() - 1);
        size_t ctrl_idx0 = start_idx + std::min(static_cast<size_t>(t0 * 3), size_t(3));
        size_t ctrl_idx1 = start_idx + std::min(static_cast<size_t>(t1 * 3), size_t(3));
        glm::vec3 color0 = m_force_uniform_color ? m_current_color : curve_verts[ctrl_idx0].color;
        glm::vec3 color1 = m_force_uniform_color ? m_current_color : curve_verts[ctrl_idx1].color;
        float thick0 = m_force_uniform_thickness ? m_current_thickness : curve_verts[ctrl_idx0].thickness;
        float thick1 = m_force_uniform_thickness ? m_current_thickness : curve_verts[ctrl_idx1].thickness;
        glm::vec3 p0(interpolated(0, i), interpolated(1, i), interpolated(2, i));
        glm::vec3 p1(interpolated(0, i + 1), interpolated(1, i + 1), interpolated(2, i + 1));
        output.push_back({ p0, color0, thick0 });
        output.push_back({ p1, color1, thick1 });
    }
}
References MayaFlux::Kinesis::generate_interpolated_points(), m_arc_length_parameterization, m_current_color, m_current_thickness, m_force_uniform_color, m_force_uniform_thickness, m_mode, m_samples_per_segment, m_tension, and MayaFlux::Kinesis::reparameterize_by_arc_length().
Referenced by complete(), generate_interpolated_path(), and regenerate_segment_range().