MayaFlux: MayaFlux::Core::Engine::get_node_graph_manager
get_node_graph_manager()
std::shared_ptr< Nodes::NodeGraphManager > MayaFlux::Core::Engine::get_node_graph_manager () inline
Gets the node graph manager.
Returns
Shared pointer to the NodeGraphManager for node-based processing
The NodeGraphManager handles the computational graph of processing nodes. Access through Engine ensures proper initialization and lifetime management.
Definition at line 232 of file Engine.hpp.
{ return m_node_graph_manager; }
Referenced by MayaFlux::get_audio_channel_root(), MayaFlux::get_node_graph_manager(), MayaFlux::register_node(), MayaFlux::register_node_network(), and MayaFlux::unregister_node_network().