MayaFlux: MayaFlux::IO::IOManager::load_video
load_video() [2/2]
VideoLoadResult MayaFlux::IO::IOManager::load_video (const std::string & filepath, LoadConfig config)
Load a video file into a VideoFileContainer.
Performs can_read check, opens with metadata and region extraction, registers the reader (assigning a globally unique reader_id), calls setup_io_service(), loads into container, and configures the default FrameAccessProcessor with auto_advance enabled.
Passing VideoReadOptions::EXTRACT_AUDIO also extracts the embedded SoundFileContainer, configures its ContiguousAccessProcessor identically to load_audio_file() in Depot, and populates VideoLoadResult::audio.
Parameters
filepath Path to the video file.
config LoadConfig struct containing options and target dimensions.
Returns
VideoLoadResult containing video container and optional audio container.
Definition at line 109 of file IOManager.cpp.
{
    auto reader = std::make_shared<IO::VideoFileReader>();
    if (!reader->can_read(filepath)) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "Cannot read video file: {}", filepath);
        return {};
    }
    reader->set_video_options(config.video_options);
    reader->set_audio_options(config.audio_options);
    reader->set_target_dimensions(config.target_width, config.target_height);
    if ((config.video_options & VideoReadOptions::EXTRACT_AUDIO) == VideoReadOptions::EXTRACT_AUDIO) {
        reader->set_target_sample_rate(m_sample_rate);
    }
    if (!reader->open(filepath, config.file_options)) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "Failed to open video file: {}", reader->get_last_error());
        return {};
    }
    const uint64_t reader_id = register_video_reader(reader);
    reader->setup_io_service(reader_id);
    auto video_container = std::dynamic_pointer_cast<Kakshya::VideoFileContainer>(reader->create_container());
    if (!video_container) {
        MF_ERROR(Journal::Component::API, Journal::Context::Runtime,
            "Failed to create video container from: {}", filepath);
        release_video_reader(reader_id);
        return {};
    }
    if (!reader->load_into_container(video_container)) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "Failed to load video data: {}", reader->get_last_error());
        release_video_reader(reader_id);
        return {};
    }
    configure_frame_processor(video_container);
    VideoLoadResult result;
    result.video = video_container;
    if ((config.video_options & IO::VideoReadOptions::EXTRACT_AUDIO) == IO::VideoReadOptions::EXTRACT_AUDIO) {
        auto audio_container = reader->get_audio_container();
        if (audio_container) {
            configure_audio_processor(audio_container);
            result.audio = audio_container;
            m_extracted_audio[video_container] = audio_container;
        } else {
            MF_WARN(Journal::Component::API, Journal::Context::FileIO,
                "No audio track found in: {}", filepath);
        }
    }
    MF_INFO(Journal::Component::API, Journal::Context::FileIO,
        "Loaded video: {}", filepath);
    return result;
}
References MayaFlux::Journal::API, MayaFlux::IO::VideoLoadResult::audio, MayaFlux::IO::LoadConfig::audio_options, configure_audio_processor(), configure_frame_processor(), MayaFlux::IO::EXTRACT_AUDIO, MayaFlux::IO::LoadConfig::file_options, MayaFlux::Journal::FileIO, m_extracted_audio, m_sample_rate, MF_ERROR, MF_INFO, MF_WARN, register_video_reader(), release_video_reader(), MayaFlux::Journal::Runtime, MayaFlux::IO::LoadConfig::target_height, MayaFlux::IO::LoadConfig::target_width, MayaFlux::IO::VideoLoadResult::video, and MayaFlux::IO::LoadConfig::video_options.