MayaFlux: MayaFlux::Core::VKInstance::initialize
initialize()
bool MayaFlux::Core::VKInstance::initialize (bool enable_validation = true, const std::vector< const char * > & required_extensions = {})
Initialize Vulkan instance.
Parameters
enable_validation Enable validation layers (recommended for development)
required_extensions Extensions required (e.g., for GLFW surface)
Returns
true if initialization succeeded
Definition at line 41 of file VKInstance.cpp.
{
    m_validation_enabled = enable_validation;
    auto vkGetInstanceProcAddr = vk::detail::DynamicLoader().getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
    VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
    if (m_validation_enabled && !check_validation_layer_support(VALIDATION_LAYERS)) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend, "Vulkan validation layers requested, but not available!");
        return false;
    }
    vk::ApplicationInfo app_info {};
    app_info.pApplicationName = "MayaFlux";
    app_info.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
    app_info.pEngineName = "MayaFlux Engine";
    app_info.engineVersion = VK_MAKE_VERSION(1, 0, 0);
    app_info.apiVersion = VK_API_VERSION_1_3;
    vk::InstanceCreateInfo create_info {};
    create_info.pApplicationInfo = &app_info;
    std::vector<const char*> extensions = required_extensions;
#ifdef MAYAFLUX_PLATFORM_MACOS
    extensions.push_back(VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME);
    create_info.flags = vk::InstanceCreateFlagBits::eEnumeratePortabilityKHR;
#endif
    if (m_validation_enabled) {
        extensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
    }
    create_info.enabledExtensionCount = static_cast<uint32_t>(extensions.size());
    create_info.ppEnabledExtensionNames = extensions.data();
    vk::DebugUtilsMessengerCreateInfoEXT debug_create_info {};
    if (m_validation_enabled) {
        create_info.enabledLayerCount = static_cast<uint32_t>(VALIDATION_LAYERS.size());
        create_info.ppEnabledLayerNames = VALIDATION_LAYERS.data();
        debug_create_info.messageSeverity = vk::DebugUtilsMessageSeverityFlagBitsEXT::eVerbose
            | vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning | vk::DebugUtilsMessageSeverityFlagBitsEXT::eError;
        debug_create_info.messageType = vk::DebugUtilsMessageTypeFlagBitsEXT::eGeneral
            | vk::DebugUtilsMessageTypeFlagBitsEXT::eValidation
            | vk::DebugUtilsMessageTypeFlagBitsEXT::ePerformance;
        debug_create_info.pfnUserCallback = debug_callback;
        create_info.pNext = &debug_create_info;
    } else {
        create_info.enabledLayerCount = 0;
        create_info.pNext = nullptr;
    }
    try {
        m_instance = vk::createInstance(create_info);
        m_dynamic_dispatcher = vk::detail::DispatchLoaderDynamic(m_instance, vkGetInstanceProcAddr);
        VULKAN_HPP_DEFAULT_DISPATCHER.init(m_instance);
    } catch (const std::exception& e) {
        error_rethrow(Journal::Component::Core, Journal::Context::GraphicsBackend,
            std::source_location::current(),
            "Failed to create Vulkan instance: {}", e.what());
    }
    MF_PRINT(Journal::Component::Core, Journal::Context::GraphicsBackend, "Vulkan instance created.");
    if (m_validation_enabled && !setup_debug_messenger()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend, "Failed to set up debug messenger!");
        return false;
    }
    return true;
}
References check_validation_layer_support(), MayaFlux::Journal::Core, debug_callback(), MayaFlux::Journal::GraphicsBackend, m_dynamic_dispatcher, m_instance, m_validation_enabled, MF_ERROR, MF_PRINT, setup_debug_messenger(), and MayaFlux::Core::VALIDATION_LAYERS.
Referenced by MayaFlux::Core::VKContext::initialize().