MayaFlux: MayaFlux::IO::FFmpegDemuxContext::find_best_stream
find_best_stream()
int MayaFlux::IO::FFmpegDemuxContext::find_best_stream (int media_type, const void ** out_codec = nullptr) const
Find the best stream of the requested media type.
Parameters
media_type AVMediaType value (AVMEDIA_TYPE_AUDIO, AVMEDIA_TYPE_VIDEO, …)
out_codec Receives a pointer to the matched codec (may be nullptr if caller does not need it).
Returns
Stream index ≥ 0 on success, negative on failure.
Definition at line 100 of file FFmpegDemuxContext.cpp.
{
    if (!format_context)
        return -1;
    const AVCodec* codec = nullptr;
    int idx = av_find_best_stream(
        format_context,
        static_cast<AVMediaType>(media_type),
        -1, -1,
        &codec,
        0);
    if (out_codec)
        *out_codec = codec;
    return idx;
}
References format_context.
Referenced by MayaFlux::IO::SoundFileReader::can_read(), MayaFlux::IO::AudioStreamContext::open(), MayaFlux::IO::VideoStreamContext::open(), and MayaFlux::IO::VideoStreamContext::open_device().