MayaFlux: MayaFlux::Portal::Forma::Bridge::spawn_inbound
spawn_inbound()
void MayaFlux::Portal::Forma::Bridge::spawn_inbound (uint32_t id, std::function< float()> source) private
Definition at line 59 of file Bridge.cpp.
{
    auto it = m_records.find(id);
    if (it == m_records.end()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::Init,
            "Bridge::bind: unknown element id {}", id);
        return;
    }
    cancel_inbound(it->second);
    auto name = make_task_name(id, "inbound");
    it->second.inbound_task = name;
    auto& rec = it->second;
    auto writer = rec.writer;
    auto routine = [](Vruta::TaskScheduler&,
                       std::function<float()> src,
                       std::function<void(float)> write) -> Vruta::GraphicsRoutine {
        auto& p = co_await Kriya::GetGraphicsPromise {};
        while (!p.should_terminate) {
            write(src());
            co_await Kriya::FrameDelay { .frames_to_wait = 1 };
        }
    };
    m_scheduler.add_task(
        std::make_shared<Vruta::GraphicsRoutine>(
            routine(m_scheduler, std::move(source), std::move(writer))),
        name, false);
}
References MayaFlux::Vruta::TaskScheduler::add_task(), cancel_inbound(), MayaFlux::Kriya::FrameDelay::frames_to_wait, MayaFlux::Journal::Init, m_records, m_scheduler, make_task_name(), MF_ERROR, MayaFlux::Journal::Portal, and write().
Referenced by bind(), and bind().