MayaFlux: MayaFlux::Kakshya::ContiguousAccessProcessor::validate
validate()
void ContiguousAccessProcessor::validate () private
Validate the container's structure and output configuration.
Throws if configuration is invalid.
Definition at line 71 of file ContiguousAccessProcessor.cpp.
{
    if (m_total_elements == 0) {
        MF_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "ContiguousAccessProcessor validation: Container has no data elements");
    }
    if (m_output_shape.size() != 2) {
        error<std::runtime_error>(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "Audio output shape must be [frames, channels]");
    }
    uint64_t frames_requested = m_output_shape[0];
    uint64_t channels_requested = m_output_shape[1];
    uint64_t available_channels = m_structure.get_channel_count();
    if (frames_requested == 0 || channels_requested == 0) {
        error<std::runtime_error>(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "Frame and channel counts cannot be zero");
    }
    if (frames_requested > m_structure.get_samples_count_per_channel()) {
        error<std::runtime_error>(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "Requested {} frames exceeds available {} samples per channel",
            frames_requested,
            m_structure.get_samples_count_per_channel());
    }
    if (channels_requested > available_channels) {
        error<std::runtime_error>(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "Requested {} channels exceeds available {} channels",
            channels_requested,
            available_channels);
    }
    if (m_current_position.size() != available_channels) {
        MF_ERROR(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "Current position size {} doesn't match available channel count {}, resetting positions",
            m_current_position.size(),
            available_channels);
        m_current_position.resize(available_channels, 0);
    }
    MF_INFO(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
        "ContiguousAccessProcessor validated: memory layout {}, processing {}×{} blocks, current positions for {} channels",
        (m_structure.organization == OrganizationStrategy::INTERLEAVED ? "interleaved" : "planar"),
        frames_requested,
        channels_requested, m_current_position.size());
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_samples_count_per_channel(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Journal::Kakshya, m_current_position, m_output_shape, m_structure, m_total_elements, MF_ERROR, MF_INFO, MF_WARN, and MayaFlux::Kakshya::ContainerDataStructure::organization.
Referenced by on_attach(), and set_output_size().