MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::get_data_as_double
get_data_as_double()
std::span< const double > MayaFlux::Kakshya::SoundStreamContainer::get_data_as_double () const
Get the audio data as a specific type.
Returns
Span of double data for direct access
Definition at line 791 of file SoundStreamContainer.cpp.
{
    if (!m_double_extraction_dirty.load(std::memory_order_acquire)) {
        return { m_cached_ext_buffer };
    }
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        if (m_data.empty())
            return {};
        std::shared_lock data_lock(m_data_mutex);
        auto span = convert_variant<double>(m_data[0]);
        return { span.data(), span.size() };
    }
    const auto& spans = get_span_cache();
    auto channels = spans
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    m_cached_ext_buffer = interleave_channels(channels);
    m_double_extraction_dirty.store(false, std::memory_order_release);
    return { m_cached_ext_buffer };
}
References get_span_cache(), MayaFlux::Kakshya::interleave_channels(), MayaFlux::Kakshya::INTERLEAVED, m_cached_ext_buffer, m_data, m_data_mutex, m_double_extraction_dirty, m_structure, and MayaFlux::Kakshya::ContainerDataStructure::organization.
Referenced by get_frames(), get_raw_data(), and peek_sequential().