MayaFlux: MayaFlux::Kakshya::WindowContainer::get_frame
get_frame()
std::span< const double > MayaFlux::Kakshya::WindowContainer::get_frame (uint64_t frame_index) const override virtual
Get a single frame of data efficiently.
Parameters
frame_index Index of the frame (in the temporal dimension)
Returns
Span of data representing one complete frame
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 563 of file WindowContainer.cpp.
{
    std::shared_lock lock(m_data_mutex);
    const uint64_t h = m_structure.get_height();
    if (frame_index >= h || m_processed_data.empty())
        return {};
    const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_processed_data[0]);
    if (!pixels || pixels->empty())
        return {};
    const uint64_t w = m_structure.get_width();
    const uint64_t c = m_structure.get_channel_count();
    const uint64_t row_elems = w * c;
    const uint64_t offset = frame_index * row_elems;
    if (offset + row_elems > pixels->size())
        return {};
    auto& cache = m_frame_cache;
    cache.resize(row_elems);
    for (uint64_t i = 0; i < row_elems; ++i)
        cache[i] = static_cast<double>((*pixels)[offset + i]) / 255.0;
    return { cache.data(), cache.size() };
}
References MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), h, lock(), m_data_mutex, m_frame_cache, m_processed_data, m_structure, and pixels.