MayaFlux: MayaFlux::Buffers::FormaBindingsProcessor::make_descriptor_buffer
make_descriptor_buffer()
std::shared_ptr< VKBuffer > MayaFlux::Buffers::FormaBindingsProcessor::make_descriptor_buffer (Portal::Graphics::DescriptorRole role) static private
Definition at line 178 of file FormaBindingsProcessor.cpp.
{
    const VKBuffer::Usage usage = (role == Portal::Graphics::DescriptorRole::UNIFORM)
        ? VKBuffer::Usage::UNIFORM
        : VKBuffer::Usage::COMPUTE;
    auto buf = std::make_shared<VKBuffer>(
        sizeof(float),
        usage,
        Kakshya::DataModality::UNKNOWN);
    auto svc = Registry::BackendRegistry::instance()
                   .get_service<Registry::Service::BufferService>();
    if (!svc) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "FormaBindingsProcessor: no BufferService available");
    }
    svc->initialize_buffer(buf);
    return buf;
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::COMPUTE, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), MayaFlux::Buffers::VKBuffer::UNIFORM, MayaFlux::Portal::Graphics::UNIFORM, and MayaFlux::Kakshya::UNKNOWN.
Referenced by bind_descriptor().