MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::setup_dimensions
setup_dimensions()
void MayaFlux::Kakshya::VideoStreamContainer::setup_dimensions () protected
Definition at line 39 of file VideoStreamContainer.cpp.
{
    m_structure.dimensions = DataDimension::create_dimensions(
        DataModality::VIDEO_COLOR,
        { m_num_frames,
            static_cast<uint64_t>(m_height),
            static_cast<uint64_t>(m_width),
            static_cast<uint64_t>(m_channels) },
        MemoryLayout::ROW_MAJOR);
}
References MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Kakshya::ContainerDataStructure::dimensions, m_channels, m_height, m_num_frames, m_structure, m_width, MayaFlux::Kakshya::ROW_MAJOR, and MayaFlux::Kakshya::VIDEO_COLOR.
Referenced by MayaFlux::Kakshya::CameraContainer::CameraContainer(), clear(), setup_ring(), and VideoStreamContainer().