MayaFlux: MayaFlux::Portal::Graphics::SamplerForge::create_sampler
create_sampler()
vk::Sampler MayaFlux::Portal::Graphics::SamplerForge::create_sampler (const SamplerConfig & config) private
Definition at line 151 of file SamplerForge.cpp.
{
    auto device = m_backend->get_context().get_device();
    auto physical_device = m_backend->get_context().get_physical_device();
    vk::SamplerCreateInfo sampler_info {};
    sampler_info.magFilter = to_vk_filter(config.mag_filter);
    sampler_info.minFilter = to_vk_filter(config.min_filter);
    sampler_info.addressModeU = to_vk_address_mode(config.address_mode_u);
    sampler_info.addressModeV = to_vk_address_mode(config.address_mode_v);
    sampler_info.addressModeW = to_vk_address_mode(config.address_mode_w);
    if (config.max_anisotropy > 1.0F) {
        auto properties = physical_device.getProperties();
        sampler_info.anisotropyEnable = VK_TRUE;
        sampler_info.maxAnisotropy = std::min(
            config.max_anisotropy,
            properties.limits.maxSamplerAnisotropy);
    } else {
        sampler_info.anisotropyEnable = VK_FALSE;
        sampler_info.maxAnisotropy = 1.0F;
    }
    sampler_info.borderColor = vk::BorderColor::eIntOpaqueBlack;
    sampler_info.unnormalizedCoordinates = VK_FALSE;
    sampler_info.compareEnable = VK_FALSE;
    sampler_info.compareOp = vk::CompareOp::eAlways;
    if (config.enable_mipmaps) {
        sampler_info.mipmapMode = (config.min_filter == FilterMode::LINEAR)
            ? vk::SamplerMipmapMode::eLinear
            : vk::SamplerMipmapMode::eNearest;
        sampler_info.minLod = 0.0F;
        sampler_info.maxLod = VK_LOD_CLAMP_NONE;
        sampler_info.mipLodBias = 0.0F;
    } else {
        sampler_info.mipmapMode = vk::SamplerMipmapMode::eNearest;
        sampler_info.minLod = 0.0F;
        sampler_info.maxLod = 0.0F;
        sampler_info.mipLodBias = 0.0F;
    }
    try {
        vk::Sampler sampler = device.createSampler(sampler_info);
        MF_DEBUG(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "Created sampler: mag={}, min={}, aniso={}",
            vk::to_string(sampler_info.magFilter),
            vk::to_string(sampler_info.minFilter),
            sampler_info.maxAnisotropy);
        return sampler;
    } catch (const vk::SystemError& e) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "Failed to create sampler: {}", e.what());
        return nullptr;
    }
}
References MayaFlux::Portal::Graphics::SamplerConfig::address_mode_u, MayaFlux::Portal::Graphics::SamplerConfig::address_mode_v, MayaFlux::Portal::Graphics::SamplerConfig::address_mode_w, MayaFlux::Portal::Graphics::SamplerConfig::enable_mipmaps, MayaFlux::Journal::ImageProcessing, MayaFlux::Portal::Graphics::LINEAR, m_backend, MayaFlux::Portal::Graphics::SamplerConfig::mag_filter, MayaFlux::Portal::Graphics::SamplerConfig::max_anisotropy, MF_DEBUG, MF_ERROR, MayaFlux::Portal::Graphics::SamplerConfig::min_filter, MayaFlux::Journal::Portal, to_vk_address_mode(), and to_vk_filter().
Referenced by get_or_create().