MayaFlux: MayaFlux::Core::VKComputePipeline::dispatch
dispatch()
void MayaFlux::Core::VKComputePipeline::dispatch (vk::CommandBuffer cmd, uint32_t group_count_x, uint32_t group_count_y, uint32_t group_count_z) const
Dispatch compute workgroups.
Parameters
cmd Command buffer
group_count_x Number of workgroups in X dimension
group_count_y Number of workgroups in Y dimension
group_count_z Number of workgroups in Z dimension
Executes the compute shader with the specified number of workgroups. Total invocations = group_count * local_size (from shader).
Example: // Shader: layout(local_size_x = 256) in; // Process 1M elements: 1,000,000 / 256 = 3,907 workgroups pipeline.dispatch(cmd, 3907, 1, 1);
Must be called after bind() and bind_descriptor_sets().
Definition at line 261 of file VKComputePipeline.cpp.
{
    if (!m_pipeline) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot dispatch invalid compute pipeline");
        return;
    }
    if (group_count_x == 0 || group_count_y == 0 || group_count_z == 0) {
        MF_WARN(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Dispatching with zero workgroups ({}x{}x{})",
            group_count_x, group_count_y, group_count_z);
        return;
    }
    cmd.dispatch(group_count_x, group_count_y, group_count_z);
}
References MayaFlux::Journal::Core, MayaFlux::Journal::GraphicsBackend, m_pipeline, MF_ERROR, and MF_WARN.
Referenced by dispatch_1d(), dispatch_2d(), and dispatch_3d().