MayaFlux: MayaFlux::Nodes::Generator::Generator::create_context
create_context()
std::unique_ptr< NodeContext > MayaFlux::Nodes::Generator::Generator::create_context (double value) override virtual
Creates a context object for callbacks.
Parameters
value The current generated sample
Returns
A unique pointer to a GeneratorContext object
This method creates a specialized context object containing the current sample value and all oscillator parameters, providing callbacks with rich information about the oscillator's state.
Implements MayaFlux::Nodes::Node.
Reimplemented in MayaFlux::Nodes::Generator::Logic, MayaFlux::Nodes::Generator::Polynomial, and MayaFlux::Nodes::Generator::Stochastics::Random.
Definition at line 19 of file Generator.cpp.
{
    if (m_gpu_compatible) {
        return std::make_unique<GeneratorContextGpu>(
            value,
            m_frequency,
            m_amplitude,
            m_phase,
            get_gpu_data_buffer());
    }
    return std::make_unique<GeneratorContext>(value, m_frequency, m_amplitude, m_phase);
}
References MayaFlux::Nodes::Node::get_gpu_data_buffer(), m_amplitude, m_frequency, MayaFlux::Nodes::Node::m_gpu_compatible, and m_phase.
Referenced by MayaFlux::Nodes::Generator::Impulse::notify_tick(), MayaFlux::Nodes::Generator::Phasor::notify_tick(), MayaFlux::Nodes::Generator::Sine::notify_tick(), and MayaFlux::Nodes::Generator::Sine::Sine().