MayaFlux: MayaFlux::Kakshya::EigenAccess::to_matrix
to_matrix()
Eigen::MatrixXd MayaFlux::Kakshya::EigenAccess::to_matrix () const
Convert DataVariant to Eigen matrix.
Returns
Matrix representation
Scalar types: 1xN matrix (single row)
Complex types: 2xN matrix (row 0 = real, row 1 = imag)
GLM vec2: 2xN matrix
GLM vec3: 3xN matrix
GLM vec4: 4xN matrix
GLM mat4: 16xN matrix (flattened)
Definition at line 37 of file EigenAccess.cpp.
{
    return std::visit([this](const auto& vec) -> Eigen::MatrixXd {
        using T = typename std::decay_t<decltype(vec)>::value_type;
        if constexpr (std::is_arithmetic_v<T>) {
            return scalar_to_matrix(vec);
        } else if constexpr (std::is_same_v<T, std::complex<float>> || std::is_same_v<T, std::complex<double>>) {
            return complex_to_matrix(vec);
        } else if constexpr (GlmType<T>) {
            return glm_to_matrix(vec);
        } else {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "Unsupported type for Eigen conversion: {}",
                typeid(T).name());
        }
    },
        m_variant);
}
References complex_to_matrix(), glm_to_matrix(), MayaFlux::Journal::Kakshya, m_variant, MayaFlux::Journal::Runtime, and scalar_to_matrix().
Referenced by MayaFlux::Kakshya::to_eigen_matrix().