MayaFlux: MayaFlux::IO::VideoFileReader::close
close()
void MayaFlux::IO::VideoFileReader::close () override virtual
Close the currently open file.
Implements MayaFlux::IO::FileReader.
Definition at line 118 of file VideoFileReader.cpp.
{
    stop_decode_thread();
    m_container_ref.reset();
    std::unique_lock ctx_lock(m_context_mutex);
    if (m_audio) {
        m_audio->close();
        m_audio.reset();
    }
    if (m_video) {
        m_video->close();
        m_video.reset();
    }
    if (m_demux) {
        m_demux->close();
        m_demux.reset();
    }
    m_audio_container.reset();
    m_sws_buf.clear();
    m_sws_buf.shrink_to_fit();
    {
        std::lock_guard lock(m_metadata_mutex);
        m_cached_metadata.reset();
        m_cached_regions.clear();
    }
    m_decode_head.store(0);
    clear_error();
    if (m_owns_io_service) {
        Registry::BackendRegistry::instance()
            .unregister_service<Registry::Service::IOService>();
        m_io_service.reset();
        m_owns_io_service = false;
    }
}
References clear_error(), MayaFlux::Registry::BackendRegistry::instance(), m_audio, m_audio_container, m_cached_metadata, m_cached_regions, m_container_ref, m_context_mutex, m_decode_head, m_demux, m_io_service, m_metadata_mutex, m_owns_io_service, m_sws_buf, m_video, stop_decode_thread(), and MayaFlux::Registry::BackendRegistry::unregister_service().
Referenced by open(), and ~VideoFileReader().