MayaFlux: MayaFlux::Core::UDPBackend::open_endpoint
open_endpoint()
uint64_t MayaFlux::Core::UDPBackend::open_endpoint (const EndpointInfo & info) override virtual
Open a new endpoint.
Parameters
info Endpoint configuration with id pre-assigned by subsystem.
Returns
The endpoint id on success, or 0 on failure.
The subsystem assigns the id before calling this. The backend stores and uses it for subsequent operations.
For UDP: binds a local port and/or stores a default remote target. For TCP: connects to a remote host, or begins listening on a port. Outbound connect may block. Use co_open_endpoint on the service for non-blocking connect. For SHM: opens or creates a named shared memory segment.
Implements MayaFlux::Core::INetworkBackend.
Definition at line 91 of file UDPBackend.cpp.
{
    uint16_t local_port = info.local_port;
    if (local_port == 0 && info.role == EndpointRole::SEND) {
        local_port = 0;
    } else if (local_port == 0) {
        local_port = m_config.default_receive_port;
    }
    auto* sock = acquire_socket(local_port);
    if (!sock) {
        return 0;
    }
    EndpointRecord record;
    record.info = info;
    record.socket_state = sock;
    if (!info.remote_address.empty() && info.remote_port > 0) {
        asio::error_code ec;
        auto addr = asio::ip::make_address(info.remote_address, ec);
        if (ec) {
            MF_ERROR(Journal::Component::Core, Journal::Context::NetworkBackend,
                "Invalid remote address '{}': {}", info.remote_address, ec.message());
            release_socket(local_port);
            return 0;
        }
        record.default_remote = asio::ip::udp::endpoint(addr, info.remote_port);
        record.has_default_remote = true;
    }
    record.info.state = EndpointState::OPEN;
    {
        std::unique_lock lock(m_endpoints_mutex);
        m_endpoints[info.id] = std::move(record);
    }
    transition_state(m_endpoints[info.id], EndpointState::OPEN);
    MF_INFO(Journal::Component::Core, Journal::Context::NetworkBackend,
        "UDP endpoint {} opened (local:{}, remote:{}:{})",
        info.id, local_port, info.remote_address, info.remote_port);
    return info.id;
}
References acquire_socket(), MayaFlux::Journal::Core, MayaFlux::Core::UDPBackendInfo::default_receive_port, MayaFlux::Core::UDPBackend::EndpointRecord::default_remote, MayaFlux::Core::UDPBackend::EndpointRecord::has_default_remote, MayaFlux::Core::EndpointInfo::id, MayaFlux::Core::UDPBackend::EndpointRecord::info, MayaFlux::Core::EndpointInfo::local_port, m_config, m_endpoints, m_endpoints_mutex, MF_ERROR, MF_INFO, MayaFlux::Journal::NetworkBackend, MayaFlux::Core::OPEN, release_socket(), MayaFlux::Core::EndpointInfo::remote_address, MayaFlux::Core::EndpointInfo::remote_port, MayaFlux::Core::EndpointInfo::role, MayaFlux::Core::SEND, MayaFlux::Core::UDPBackend::EndpointRecord::socket_state, MayaFlux::Core::EndpointInfo::state, and transition_state().