MayaFlux: MayaFlux::Nodes::Generator::Counter::notify_tick
notify_tick()
void MayaFlux::Nodes::Generator::Counter::notify_tick (double value) override protected virtual
Notifies all registered callbacks with the current context.
Parameters
value The current sample value
This method is called by the node implementation when a new output value is produced. It creates a context object using create_context(), then calls all registered callbacks with that context.
For unconditional callbacks (registered with on_tick()), the callback is always called. For conditional callbacks (registered with on_tick_if()), the callback is called only if its condition returns true.
Node implementations should call this method at appropriate points in their processing flow to trigger callbacks.
Implements MayaFlux::Nodes::Node.
Definition at line 121 of file Counter.cpp.
{
    update_context(value);
    auto& ctx = get_last_context();
    auto& gc = dynamic_cast<GeneratorContext&>(ctx);
    for (auto& cb : m_callbacks) {
        cb(ctx);
    }
    for (auto& [cb, cond] : m_conditional_callbacks) {
        if (cond(ctx)) {
            cb(ctx);
        }
    }
    for (auto& cb : m_increment_callbacks) {
        cb(gc);
    }
    if (m_wrapped) {
        for (auto& cb : m_wrap_callbacks) {
            cb(gc);
        }
    }
    for (auto& [target, cb] : m_count_callbacks) {
        if (m_count == target) {
            cb(gc);
        }
    }
}
References MayaFlux::Nodes::Generator::Generator::get_last_context(), MayaFlux::Nodes::Node::m_callbacks, MayaFlux::Nodes::Node::m_conditional_callbacks, m_count, m_count_callbacks, m_increment_callbacks, m_wrap_callbacks, m_wrapped, and update_context().
Referenced by process_sample().