MayaFlux: MayaFlux::IO::CameraReader::setup_io_service
setup_io_service()
void MayaFlux::IO::CameraReader::setup_io_service (uint64_t reader_id)
Setup an IOService for this reader with the given reader_id.
Parameters
reader_id Globally unique ID assigned to this reader.
This is method is called when working outside of IOManager for self registration. IOManager::open_camera() handles this automatically for managed readers.
Definition at line 30 of file CameraReader.cpp.
{
    m_standalone_reader_id = reader_id;
    if (!Registry::BackendRegistry::instance()
            .get_service<Registry::Service::IOService>()) {
        m_standalone_service = std::make_shared<Registry::Service::IOService>();
        m_standalone_service->request_frame = [this](uint64_t reader_id) {
            if (reader_id == m_standalone_reader_id)
                pull_frame_all();
        };
        Registry::BackendRegistry::instance()
            .register_service<Registry::Service::IOService>(
                [this]() -> void* { return m_standalone_service.get(); });
        m_owns_service = true;
    }
}
References MayaFlux::Registry::BackendRegistry::instance(), m_owns_service, m_standalone_reader_id, m_standalone_service, pull_frame_all(), and MayaFlux::Registry::BackendRegistry::register_service().