MayaFlux: MayaFlux::IO::VideoFileReader::seek
seek()
bool MayaFlux::IO::VideoFileReader::seek (const std::vector< uint64_t > & position) override virtual
Seek to a specific position in the file.
Parameters
position Target position in N-dimensional space.
Returns
true if seek was successful.
Implements MayaFlux::IO::FileReader.
Definition at line 572 of file VideoFileReader.cpp.
{
    if (position.empty())
        return false;
    const uint64_t target_frame = position[0];
    stop_decode_thread();
    std::shared_ptr<VideoStreamContext> video;
    std::shared_ptr<FFmpegDemuxContext> demux;
    {
        std::shared_lock lock(m_context_mutex);
        if (!m_demux || !m_video || !m_video->is_valid()) {
            set_error("Cannot seek: reader not open");
            return false;
        }
        video = m_video;
        demux = m_demux;
    }
    if (!seek_internal(demux, video, target_frame))
        return false;
    m_decode_head.store(target_frame);
    auto vc = m_container_ref.lock();
    if (!vc)
        return true;
    vc->invalidate_ring();
    vc->set_read_position({ target_frame });
    const uint64_t total = vc->get_total_source_frames();
    const uint64_t batch = std::min(
        static_cast<uint64_t>(m_decode_batch_size),
        total > target_frame ? total - target_frame : 0UL);
    decode_batch(*vc, batch);
    if (m_decode_head.load() < total)
        start_decode_thread();
    return true;
}
References decode_batch(), m_container_ref, m_context_mutex, m_decode_batch_size, m_decode_head, m_demux, m_video, position, seek_internal(), set_error(), start_decode_thread(), and stop_decode_thread().