MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::get_metadata
get_metadata()
std::unordered_map< std::string, std::string > MayaFlux::Nodes::Network::NodeNetwork::get_metadata () const virtual
Get network metadata for debugging/visualization.
Returns
Map of property names to string representations
Subclasses can override to expose internal state:
Particle count, average velocity
Modal frequencies, decay times
Waveguide delay lengths etc.
Reimplemented in MayaFlux::Nodes::Network::ModalNetwork, MayaFlux::Nodes::Network::ParticleNetwork, MayaFlux::Nodes::Network::PointCloudNetwork, MayaFlux::Nodes::Network::ResonatorNetwork, and MayaFlux::Nodes::Network::WaveguideNetwork.
Definition at line 36 of file NodeNetwork.cpp.
{
    return { { "topology", topology_to_string(m_topology) },
        { "output_mode", output_mode_to_string(m_output_mode) },
        { "node_count", std::to_string(get_node_count()) },
        { "enabled", m_enabled ? "true" : "false" } };
}
References get_node_count(), m_enabled, m_output_mode, m_topology, output_mode_to_string(), and topology_to_string().
Referenced by MayaFlux::Nodes::Network::ModalNetwork::get_metadata(), MayaFlux::Nodes::Network::ParticleNetwork::get_metadata(), MayaFlux::Nodes::Network::PointCloudNetwork::get_metadata(), MayaFlux::Nodes::Network::ResonatorNetwork::get_metadata(), and MayaFlux::Nodes::Network::WaveguideNetwork::get_metadata().