MayaFlux: MayaFlux::Nodes::NodeGraphManager::get_all_channels
get_all_channels()
std::vector< unsigned int > MayaFlux::Nodes::NodeGraphManager::get_all_channels (ProcessingToken token) const
Gets all channel indices for a given processing token.
Parameters
token Processing domain
Returns
Vector of channel indices that have root nodes for this token
Definition at line 375 of file NodeGraphManager.cpp.
{
    std::vector<unsigned int> channels;
    auto it = m_token_roots.find(token);
    if (it != m_token_roots.end()) {
        for (const auto& [channel, root] : it->second) {
            channels.push_back(channel);
        }
    }
    return channels;
}
References m_token_roots.
Referenced by get_channel_count(), print_summary(), and process_token_with_channel_data().