MayaFlux: MayaFlux::Buffers::ShaderProcessor::resolve_ds_index
resolve_ds_index()
std::optional< uint32_t > MayaFlux::Buffers::ShaderProcessor::resolve_ds_index (uint32_t set) const protected
Resolve logical descriptor set index to actual index.
Parameters
set Logical set index from ShaderBinding
Returns
Resolved set index, or std::nullopt if invalid
Handles cases where the engine reserves set 0 for global resources. If m_engine_owns_set_zero is true, logical set 0 maps to no descriptor, and logical sets are offset by +1 in the actual descriptor sets.
Definition at line 353 of file ShaderProcessor.cpp.
{
    if (m_engine_owns_set_zero) {
        if (set == 0)
            return std::nullopt;
        const uint32_t idx = set - 1;
        if (idx >= m_descriptor_set_ids.size())
            return std::nullopt;
        return idx;
    }
    if (set >= m_descriptor_set_ids.size())
        return std::nullopt;
    return set;
}
References m_descriptor_set_ids, and m_engine_owns_set_zero.
Referenced by MayaFlux::Buffers::RenderProcessor::bind_texture(), MayaFlux::Buffers::RenderProcessor::execute_shader(), MayaFlux::Buffers::RenderProcessor::initialize_descriptors(), and update_descriptors().