MayaFlux: MayaFlux::Kinesis::Vision::VisionExecutor::reset
reset()
void MayaFlux::Kinesis::Vision::VisionExecutor::reset ()
Clear stored inter-frame state.
Call when the pixel source changes (camera switch, video seek) so the next track_keypoints step starts clean. Does not release scratch storage.
Definition at line 86 of file VisionExecutor.cpp.
{
    std::get<std::vector<float>>(m_prev_gray).clear();
    m_curr_gray_cache.clear();
    m_prev_keypoints.clear();
}
References m_curr_gray_cache, m_prev_gray, and m_prev_keypoints.
Referenced by MayaFlux::Buffers::ImageCVProcessor< T >::on_attach(), MayaFlux::Kakshya::VisionProcessor::on_attach(), MayaFlux::Buffers::ImageCVProcessor< T >::on_detach(), MayaFlux::Kakshya::VisionProcessor::on_detach(), MayaFlux::Yantra::VisionAnalyzer< InputType, OutputType >::reset(), MayaFlux::Buffers::ImageCVProcessor< T >::set_sequence(), MayaFlux::Kakshya::VisionProcessor::set_sequence(), and MayaFlux::Yantra::VisionAnalyzer< InputType, OutputType >::set_sequence().