MayaFlux: MayaFlux::Kriya::BufferPipeline::execute_internal
execute_internal()
Vruta::SoundRoutine MayaFlux::Kriya::BufferPipeline::execute_internal (uint64_t max_cycles, uint64_t samples_per_operation) private
Definition at line 710 of file BufferPipeline.cpp.
{
    switch (m_execution_strategy) {
    case ExecutionStrategy::PHASED:
        return execute_phased(max_cycles, samples_per_operation);
    case ExecutionStrategy::STREAMING:
        return execute_streaming(max_cycles, samples_per_operation);
    case ExecutionStrategy::PARALLEL:
        return execute_parallel(max_cycles, samples_per_operation);
    case ExecutionStrategy::REACTIVE:
        return execute_reactive(max_cycles, samples_per_operation);
    default:
        error<std::runtime_error>(Journal::Component::Kriya,
            Journal::Context::CoroutineScheduling,
            std::source_location::current(),
            "Unknown execution strategy in BufferPipeline");
    }
}
References MayaFlux::Journal::CoroutineScheduling, execute_parallel(), execute_phased(), execute_reactive(), execute_streaming(), MayaFlux::Journal::Kriya, m_execution_strategy, MayaFlux::Kriya::PARALLEL, MayaFlux::Kriya::PHASED, MayaFlux::Kriya::REACTIVE, and MayaFlux::Kriya::STREAMING.
Referenced by execute_buffer_rate(), execute_for_cycles(), execute_once(), and execute_scheduled().