MayaFlux: MayaFlux::Core::Engine::get_stream_info
get_stream_info()
GlobalStreamInfo & MayaFlux::Core::Engine::get_stream_info () inline
Gets the current stream configuration.
Returns
Reference to the GlobalStreamInfo struct
Definition at line 207 of file Engine.hpp.
{ return m_stream_info; }
Referenced by MayaFlux::Config::get_buffer_size(), MayaFlux::Config::get_global_stream_info(), MayaFlux::Config::get_num_out_channels(), MayaFlux::Config::get_sample_rate(), MayaFlux::samples_to_blocks(), MayaFlux::seconds_to_blocks(), and MayaFlux::seconds_to_samples().