MayaFlux: MayaFlux::Nodes::Network::ModalNetwork::update_mapped_parameters
update_mapped_parameters()
void MayaFlux::Nodes::Network::ModalNetwork::update_mapped_parameters () private
Update mapped parameters before processing.
Definition at line 342 of file ModalNetwork.cpp.
{
    for (const auto& mapping : m_parameter_mappings) {
        if (mapping.mode == MappingMode::BROADCAST && mapping.broadcast_source) {
            double value = mapping.broadcast_source->get_last_output();
            apply_broadcast_parameter(mapping.param_name, value);
        } else if (mapping.mode == MappingMode::ONE_TO_ONE && mapping.network_source) {
            apply_one_to_one_parameter(mapping.param_name, mapping.network_source);
        }
    }
}
References apply_broadcast_parameter(), apply_one_to_one_parameter(), MayaFlux::Nodes::Network::BROADCAST, MayaFlux::Nodes::Network::NodeNetwork::m_parameter_mappings, and MayaFlux::Nodes::Network::ONE_TO_ONE.
Referenced by process_batch().