MayaFlux: MayaFlux::Buffers::VKBuffer::set_vertex_layout
set_vertex_layout()
void MayaFlux::Buffers::VKBuffer::set_vertex_layout (const Kakshya::VertexLayout & layout)
Set vertex layout for this buffer.
Required before using buffer with graphics rendering. Describes how to interpret buffer data as vertices.
Parameters
layout VertexLayout describing vertex structure
Definition at line 361 of file VKBuffer.cpp.
{
    auto computed_layout = layout;
    computed_layout.compute_stride();
    m_vertex_layout = computed_layout;
}
References MayaFlux::Kakshya::VertexLayout::compute_stride(), and m_vertex_layout.
Referenced by MayaFlux::Buffers::TextureBuffer::generate_default_quad(), and MayaFlux::Buffers::NodeTextureBuffer::generate_fullscreen_quad().