MayaFlux: MayaFlux::Core::NetworkSubsystem::shutdown
shutdown()
void MayaFlux::Core::NetworkSubsystem::shutdown () override virtual
Shutdown and cleanup subsystem resources.
Implements MayaFlux::Core::ISubsystem.
Definition at line 169 of file NetworkSubsystem.cpp.
{
    stop();
    {
        std::unique_lock lock(m_routing_mutex);
        m_endpoint_routing.clear();
    }
    {
        std::unique_lock lock(m_callbacks_mutex);
        m_endpoint_callbacks.clear();
    }
    {
        std::unique_lock lock(m_backends_mutex);
        for (auto& [transport, backend] : m_backends) {
            backend->shutdown();
        }
        m_backends.clear();
    }
    if (m_network_service) {
        Registry::BackendRegistry::instance()
            .unregister_service<Registry::Service::NetworkService>();
        m_network_service.reset();
    }
    m_ready.store(false);
    MF_INFO(Journal::Component::Core, Journal::Context::Init,
        "Network Subsystem shutdown complete");
}
References MayaFlux::Journal::Core, MayaFlux::Journal::Init, MayaFlux::Registry::BackendRegistry::instance(), MF_INFO, and MayaFlux::Registry::BackendRegistry::unregister_service().
Referenced by ~NetworkSubsystem().