MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_audio_unit
get_audio_unit()
const RootAudioUnit & MayaFlux::Buffers::TokenUnitManager::get_audio_unit (ProcessingToken token) const
Gets an existing audio unit without creating if missing.
Parameters
token Processing domain
Returns
Const reference to the audio unit
Exceptions
std::out_of_range if token not found
This is a query-only operation; will not create a unit if missing.
Definition at line 82 of file TokenUnitManager.cpp.
{
    auto it = m_audio_units.find(token);
    if (it == m_audio_units.end()) {
        error<std::out_of_range>(
            Journal::Component::Core,
            Journal::Context::BufferManagement,
            std::source_location::current(),
            "Audio unit not found for token {}",
            static_cast<int>(token));
    }
    return it->second;
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, and m_audio_units.
Referenced by MayaFlux::Buffers::BufferProcessingControl::add_audio_processor(), MayaFlux::Buffers::BufferSupplyMixing::fill_audio_interleaved(), MayaFlux::Buffers::BufferAccessControl::get_audio_buffers(), MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer(), and MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor().