MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::expand_to
expand_to()
void MayaFlux::Kakshya::DynamicSoundStream::expand_to (uint64_t target_frames) private
Definition at line 368 of file DynamicSoundStream.cpp.
{
    uint64_t current_frames = get_total_elements() / get_num_channels();
    uint64_t new_capacity = std::max(target_frames, current_frames * 2);
    std::vector<DataVariant> new_data = create_expanded_data(new_capacity);
    set_all_data(new_data);
}
References create_expanded_data(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::SoundStreamContainer::get_total_elements(), and set_all_data().
Referenced by ensure_capacity(), validate(), validate_single_channel(), and write_frames().