MayaFlux: MayaFlux::Nodes::Network::PointCloudNetwork::generate_initial_positions
generate_initial_positions()
std::vector< LineVertex > MayaFlux::Nodes::Network::PointCloudNetwork::generate_initial_positions () private
Definition at line 359 of file PointCloudNetwork.cpp.
{
    std::vector<LineVertex> vertices;
    vertices.reserve(m_num_points);
    const glm::vec3 range = m_bounds_max - m_bounds_min;
    switch (m_init_mode) {
    case InitializationMode::UNIFORM_GRID: {
        const auto points_per_axis = static_cast<size_t>(std::cbrt(static_cast<double>(m_num_points)));
        const glm::vec3 step = range / static_cast<float>(points_per_axis - 1);
        for (size_t x = 0; x < points_per_axis; ++x) {
            for (size_t y = 0; y < points_per_axis; ++y) {
                for (size_t z = 0; z < points_per_axis; ++z) {
                    if (vertices.size() >= m_num_points)
                        break;
                    glm::vec3 pos = m_bounds_min + glm::vec3(static_cast<float>(x) * step.x, static_cast<float>(y) * step.y, static_cast<float>(z) * step.z);
                    glm::vec3 color = glm::vec3(
                        static_cast<float>(x) / static_cast<float>(points_per_axis - 1),
                        static_cast<float>(y) / static_cast<float>(points_per_axis - 1),
                        static_cast<float>(z) / static_cast<float>(points_per_axis - 1));
                    glm::vec3 center = (m_bounds_min + m_bounds_max) * 0.5F;
                    float thickness = 1.0F + glm::length(pos - center) / glm::length(range) * 2.0F;
                    vertices.emplace_back(LineVertex {
                        .position = pos,
                        .color = color,
                        .thickness = thickness });
                }
            }
        }
        break;
    }
    case InitializationMode::RANDOM_SPHERE: {
        glm::vec3 center = (m_bounds_min + m_bounds_max) * 0.5F;
        float max_radius = glm::length(range) * 0.5F;
        for (size_t i = 0; i < m_num_points; ++i) {
            auto theta = static_cast<float>(m_random_gen(0.0F, M_PI * 2.0F));
            auto phi = static_cast<float>(std::acos(m_random_gen(-1.0F, 1.0F)));
            auto radius = static_cast<float>(std::cbrt(m_random_gen(0.0F, 1.0F)));
            glm::vec3 pos = center + max_radius * radius * glm::vec3(std::sin(phi) * std::cos(theta), std::sin(phi) * std::sin(theta), std::cos(phi));
            glm::vec3 color = glm::vec3(
                radius,
                theta / glm::two_pi<float>(),
                phi / glm::pi<float>());
            float thickness = 1.0F + radius * 2.0F;
            vertices.emplace_back(LineVertex {
                .position = pos,
                .color = color,
                .thickness = thickness });
        }
        break;
    }
    case InitializationMode::RANDOM_CUBE:
    default: {
        for (size_t i = 0; i < m_num_points; ++i) {
            glm::vec3 pos = glm::vec3(
                m_random_gen(m_bounds_min.x, m_bounds_max.x),
                m_random_gen(m_bounds_min.y, m_bounds_max.y),
                m_random_gen(m_bounds_min.z, m_bounds_max.z));
            glm::vec3 color = (pos - m_bounds_min) / range;
            float thickness = m_random_gen(1.0F, 3.0F);
            vertices.emplace_back(LineVertex {
                .position = pos,
                .color = color,
                .thickness = thickness });
        }
        break;
    }
    case InitializationMode::PROCEDURAL:
    case InitializationMode::EMPTY:
        break;
    }
    return vertices;
}
References EMPTY, m_bounds_max, m_bounds_min, m_init_mode, m_num_points, m_random_gen, MayaFlux::Nodes::LineVertex::position, PROCEDURAL, RANDOM_CUBE, RANDOM_SPHERE, and UNIFORM_GRID.
Referenced by initialize(), reset(), and set_operator().