MayaFlux: MayaFlux::Core::VKContext::get_graphics_queue
get_graphics_queue()
vk::Queue MayaFlux::Core::VKContext::get_graphics_queue () const inline
Get graphics queue.
Definition at line 54 of file VKContext.hpp.
{ return m_device.get_graphics_queue(); }
References MayaFlux::Core::VKDevice::get_graphics_queue(), and m_device.
Referenced by MayaFlux::Core::BackendResourceManager::execute_immediate_commands(), and MayaFlux::Core::VKSwapchain::present().