MayaFlux: MayaFlux::IO::FFmpegMuxContext::close
close()
void MayaFlux::IO::FFmpegMuxContext::close ()
Write the container trailer, flush avio, and release all resources.
av_write_trailer is called only if write_header() previously succeeded. Safe to call multiple times or on a context that was never successfully opened.
Definition at line 63 of file FFmpegMuxContext.cpp.
{
    if (!format_context)
        return;
    if (m_header_written) {
        av_write_trailer(format_context);
        m_header_written = false;
    }
    if (format_context->pb && !(format_context->oformat->flags & AVFMT_NOFILE))
        avio_closep(&format_context->pb);
    avformat_free_context(format_context);
    format_context = nullptr;
    m_last_error.clear();
}
References format_context, m_header_written, and m_last_error.
Referenced by open(), MayaFlux::IO::SoundFileWriter::worker_loop(), MayaFlux::IO::VideoFileWriter::worker_loop(), and ~FFmpegMuxContext().