MayaFlux: MayaFlux::Buffers::VKBuffer::set_default_processor
set_default_processor()
void MayaFlux::Buffers::VKBuffer::set_default_processor (const std::shared_ptr< BufferProcessor > & processor) override virtual
Set the buffer's default processor.
Attaches a processor that will be invoked by process_default(). The previous default processor (if any) is detached first.
Parameters
processor Shared pointer to a BufferProcessor or nullptr to clear.
Implements MayaFlux::Buffers::Buffer.
Definition at line 258 of file VKBuffer.cpp.
{
    if (m_default_processor) {
        m_default_processor->on_detach(shared_from_this());
    }
    if (processor) {
        processor->on_attach(shared_from_this());
    }
    m_default_processor = processor;
}
References m_default_processor.
Referenced by MayaFlux::Buffers::RootGraphicsBuffer::initialize(), MayaFlux::Buffers::CompositeGeometryBuffer::setup_processors(), MayaFlux::Buffers::GeometryBuffer::setup_processors(), MayaFlux::Buffers::NetworkGeometryBuffer::setup_processors(), MayaFlux::Buffers::NodeTextureBuffer::setup_processors(), and MayaFlux::Buffers::TextureBuffer::setup_processors().