MayaFlux: MayaFlux::Portal::Graphics::ComputePress::initialize
initialize()
bool MayaFlux::Portal::Graphics::ComputePress::initialize ()
Definition at line 11 of file ComputePress.cpp.
{
    if (s_initialized) {
        MF_WARN(Journal::Component::Portal, Journal::Context::GPUCompute,
            "ComputePress already initialized (static flag)");
        return true;
    }
    m_shader_foundry = &get_shader_foundry();
    if (!m_shader_foundry->is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::GPUCompute,
            "Cannot initialize ComputePress: ShaderFoundry not initialized");
        return false;
    }
    m_descriptor_manager = std::make_shared<Core::VKDescriptorManager>();
    m_descriptor_manager->initialize(m_shader_foundry->get_device(), 1024);
    s_initialized = true;
    MF_INFO(Journal::Component::Portal, Journal::Context::GPUCompute,
        "ComputePress initialized");
    return true;
}
References MayaFlux::Portal::Graphics::ShaderFoundry::get_device(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Journal::GPUCompute, MayaFlux::Portal::Graphics::ShaderFoundry::is_initialized(), m_descriptor_manager, m_shader_foundry, MF_ERROR, MF_INFO, MF_WARN, MayaFlux::Journal::Portal, and s_initialized.