MayaFlux: MayaFlux::Buffers::AudioBuffer::set_default_processor
set_default_processor()
void MayaFlux::Buffers::AudioBuffer::set_default_processor (std::shared_ptr< BufferProcessor > processor) override virtual
Sets the default audio transformation processor for this buffer.
Parameters
processor Audio processor to use as default transformation
Configures the default audio processor that will be used when process_default() is called. The processor should be compatible with double-precision audio data processing.
Implements MayaFlux::Buffers::Buffer.
Definition at line 62 of file AudioBuffer.cpp.
{
    try {
        if (m_default_processor) {
            m_default_processor->on_detach(shared_from_this());
        }
        if (processor) {
            processor->on_attach(shared_from_this());
        }
        m_default_processor = processor;
    } catch (const std::exception& e) {
        std::cout << "Exception in set_default_processor: " << e.what() << std::endl;
        throw;
    }
}
References m_default_processor.
Referenced by MayaFlux::Buffers::ContainerBuffer::initialize(), MayaFlux::Buffers::RootAudioBuffer::initialize(), and MayaFlux::Buffers::FileBridgeBuffer::setup_chain_and_processor().