MayaFlux: MayaFlux::Nodes::Network::PointCloudNetwork::set_topology
set_topology()
void MayaFlux::Nodes::Network::PointCloudNetwork::set_topology (Topology topology) override virtual
Set the network's topology.
Reimplemented from MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 149 of file PointCloudNetwork.cpp.
{
    NodeNetwork::set_topology(topology);
}
References MayaFlux::Nodes::Network::NodeNetwork::set_topology().
Referenced by PointCloudNetwork(), and PointCloudNetwork().