MayaFlux: MayaFlux::Core::RtAudioStream::is_running
is_running()
bool MayaFlux::Core::RtAudioStream::is_running () const override virtual
Checks if the stream is actively processing audio data.
Returns
True if the stream is currently active, false otherwise
Implements MayaFlux::Core::AudioStream.
Definition at line 360 of file RtAudioBackend.cpp.
{
    return m_isRunning && m_context->isStreamRunning();
}
References m_context, and m_isRunning.
Referenced by close(), start(), stop(), and ~RtAudioStream().