MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::get_total_elements
get_total_elements()
uint64_t MayaFlux::Kakshya::SoundStreamContainer::get_total_elements () const override virtual
Get the total number of elements in the container.
Returns
Product of all dimension sizes
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 57 of file SoundStreamContainer.cpp.
{
    return m_structure.get_total_elements();
}
References MayaFlux::Kakshya::ContainerDataStructure::get_total_elements(), and m_structure.
Referenced by MayaFlux::Kakshya::DynamicSoundStream::ensure_capacity(), and MayaFlux::Kakshya::DynamicSoundStream::expand_to().