MayaFlux: MayaFlux::Buffers::SDFMeshProcessor::rebuild_lookup_buffers
rebuild_lookup_buffers()
void MayaFlux::Buffers::SDFMeshProcessor::rebuild_lookup_buffers () private
Definition at line 274 of file SDFMeshProcessor.cpp.
{
    auto svc = Registry::BackendRegistry::instance()
                   .get_service<Registry::Service::BufferService>();
    m_edge_buf = std::make_shared<VKBuffer>(
        256 * sizeof(uint32_t),
        VKBuffer::Usage::HOST_STORAGE,
        Kakshya::DataModality::UNKNOWN);
    svc->initialize_buffer(m_edge_buf);
    m_tri_buf = std::make_shared<VKBuffer>(
        static_cast<long>(256) * 16 * sizeof(int32_t),
        VKBuffer::Usage::HOST_STORAGE,
        Kakshya::DataModality::UNKNOWN);
    svc->initialize_buffer(m_tri_buf);
}
References MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Buffers::VKBuffer::HOST_STORAGE, MayaFlux::Registry::BackendRegistry::instance(), m_edge_buf, m_tri_buf, and MayaFlux::Kakshya::UNKNOWN.
Referenced by SDFMeshProcessor().