MayaFlux: MayaFlux::Buffers::BufferTokenDistributor::is_valid_vk_token
is_valid_vk_token()
bool MayaFlux::Buffers::BufferTokenDistributor::is_valid_vk_token (ProcessingToken token) static private
Definition at line 94 of file BufferTokenDistributor.cpp.
{
    return has_gpu(token) && !has_cpu(token);
}
References has_cpu(), and has_gpu().
Referenced by decide_vk_buffer().