MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::validate_single_channel
validate_single_channel()
uint64_t MayaFlux::Kakshya::DynamicSoundStream::validate_single_channel (std::span< const double > data, uint64_t start_frame = 0, uint32_t channel = 0) private
Definition at line 64 of file DynamicSoundStream.cpp.
{
    if (data.empty()) {
        return 0;
    }
    if (channel >= get_num_channels()) {
        std::cerr << "Channel index " << channel << " exceeds available channels (" << get_num_channels() << ")" << '\n';
        return 0;
    }
    uint64_t num_frames = data.size();
    uint64_t required_end_frame = start_frame + num_frames;
    if (m_auto_resize) {
        if (required_end_frame > get_num_frames()) {
            expand_to(required_end_frame);
        }
    } else {
        uint64_t available_frames = (start_frame < get_num_frames()) ? (get_num_frames() - start_frame) : 0;
        if (available_frames == 0) {
            return 0;
        }
        if (num_frames > available_frames) {
            num_frames = available_frames;
        }
        if (required_end_frame > m_num_frames) {
            m_num_frames = required_end_frame;
            setup_dimensions();
        }
    }
    return num_frames;
}
References channel, expand_to(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::SoundStreamContainer::get_num_frames(), m_auto_resize, MayaFlux::Kakshya::SoundStreamContainer::m_num_frames, and MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions().
Referenced by write_frames().