MayaFlux: MayaFlux::Core::VKShaderModule::create_from_glsl_file
create_from_glsl_file()
bool MayaFlux::Core::VKShaderModule::create_from_glsl_file (vk::Device device, const std::string & glsl_path, std::optional< vk::ShaderStageFlagBits > stage = std::nullopt, const std::string & entry_point = "main", bool enable_reflection = true, const std::vector< std::string > & include_directories = {}, const std::unordered_map< std::string, std::string > & defines = {})
Create shader module from GLSL file.
Parameters
device Logical device
glsl_path Path to .comp/.vert/.frag/.geom file
stage Shader stage (auto-detected from extension if not specified)
entry_point Entry point function name
enable_reflection Extract metadata
include_directories Paths for #include resolution
defines Preprocessor definitions
Returns
true if creation succeeded
Reads file, compiles GLSL → SPIR-V, calls create_from_spirv(). Stage auto-detection: .comp → Compute .vert → Vertex .frag → Fragment .geom → Geometry .tesc → Tessellation Control .tese → Tessellation Evaluation
Definition at line 257 of file VKShaderModule.cpp.
{
    std::string resolved_path = resolve_shader_path(glsl_path);
    if (!stage.has_value()) {
        stage = detect_stage_from_extension(glsl_path);
        if (!stage.has_value()) {
            MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Cannot auto-detect shader stage from file extension: '{}'", glsl_path);
            return false;
        }
        MF_DEBUG(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Auto-detected {} stage from file extension", vk::to_string(*stage));
    }
    auto glsl_source = read_text_file(resolved_path);
    if (glsl_source.empty()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to read GLSL file: '{}'", glsl_path);
        return false;
    }
    MF_DEBUG(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Loaded GLSL from file: '{}' ({} bytes)", glsl_path, glsl_source.size());
    return create_from_glsl(device, glsl_source, *stage, entry_point,
        enable_reflection, include_directories, defines);
}
References MayaFlux::Journal::Core, create_from_glsl(), detect_stage_from_extension(), MayaFlux::Journal::GraphicsBackend, MF_DEBUG, MF_ERROR, and read_text_file().