MayaFlux: MayaFlux::Nodes::GpuSync::GlyphGeometryNode::rebuild_outlines
rebuild_outlines()
void MayaFlux::Nodes::GpuSync::GlyphGeometryNode::rebuild_outlines ()
Rebuild outline geometry from the current text and pen settings.
Called automatically by set_text(). Call directly after mutating pen, color, or thickness without changing text.
Definition at line 79 of file GlyphGeometryNode.cpp.
{
    m_outlines.clear();
    m_pen_offsets.clear();
    if (m_text.empty()) {
        resize_vertex_buffer(0, false);
        m_vertex_data_dirty = true;
        return;
    }
    float cursor_x = m_pen_x;
    float cursor_y = m_pen_y;
    const auto* bytes = reinterpret_cast<const utf8proc_uint8_t*>(m_text.data());
    auto remaining = static_cast<utf8proc_ssize_t>(m_text.size());
    utf8proc_ssize_t offset = 0;
    while (offset < remaining) {
        utf8proc_int32_t cp = 0;
        const utf8proc_ssize_t n = utf8proc_iterate(bytes + offset, remaining - offset, &cp);
        if (n <= 0) {
            offset += 1;
            continue;
        }
        offset += n;
        if (cp < 0)
            continue;
        if (cp == '\n') {
            const uint32_t px = m_face
                ? m_pixel_size
                : (Portal::Text::TypeFaceFoundry::instance().get_default_glyph_atlas()
                          ? Portal::Text::TypeFaceFoundry::instance().get_default_glyph_atlas()->pixel_size()
                          : 0);
            cursor_x = m_pen_x;
            cursor_y += static_cast<float>(px);
            continue;
        }
        if (cp == '\r')
            continue;
        Portal::Text::GlyphOutline outline = m_face
            ? Portal::Text::decompose_glyph(*m_face, static_cast<uint32_t>(cp), m_pixel_size, m_tolerance)
            : Portal::Text::decompose_glyph(static_cast<uint32_t>(cp), m_tolerance);
        m_pen_offsets.emplace_back(cursor_x, cursor_y);
        m_outlines.push_back(std::move(outline));
        cursor_x += static_cast<float>(m_outlines.back().advance_x);
    }
    write_vertices();
}
References cursor_x, cursor_y, MayaFlux::Portal::Text::decompose_glyph(), MayaFlux::Portal::Text::TypeFaceFoundry::get_default_glyph_atlas(), MayaFlux::Portal::Text::TypeFaceFoundry::instance(), m_face, m_outlines, m_pen_offsets, m_pen_x, m_pen_y, m_pixel_size, m_text, m_tolerance, MayaFlux::Nodes::GpuSync::GeometryWriterNode::m_vertex_data_dirty, MayaFlux::Portal::Text::GlyphAtlas::pixel_size(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer(), and write_vertices().
Referenced by GlyphGeometryNode(), GlyphGeometryNode(), and set_text().