MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::set_looping
set_looping()
void MayaFlux::Kakshya::SoundStreamContainer::set_looping (bool enable) override virtual
Enable or disable looping behavior for the stream.
Parameters
enable true to enable looping
When enabled, advancing past the end of the loop region wraps to the start.
Implements MayaFlux::Kakshya::StreamContainer.
Definition at line 484 of file SoundStreamContainer.cpp.
{
    m_looping_enabled = enable;
    if (enable && m_loop_region.start_coordinates.empty()) {
        m_loop_region = Region::time_span(0, m_num_frames - 1);
    }
}
References m_loop_region, m_looping_enabled, m_num_frames, MayaFlux::Kakshya::Region::start_coordinates, and MayaFlux::Kakshya::Region::time_span().
Referenced by MayaFlux::Kakshya::DynamicSoundStream::disable_circular_buffer(), and MayaFlux::Kakshya::DynamicSoundStream::enable_circular_buffer().