MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions
setup_dimensions()
void MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions () protected
Definition at line 29 of file SoundStreamContainer.cpp.
{
    DataModality modality = (m_num_channels > 1)
        ? DataModality::AUDIO_MULTICHANNEL
        : DataModality::AUDIO_1D;
    std::vector<uint64_t> shape;
    if (modality == DataModality::AUDIO_1D) {
        shape = { m_num_frames };
    } else {
        shape = { m_num_frames, m_num_channels };
    }
    auto layout = m_structure.memory_layout;
    OrganizationStrategy org = m_structure.organization;
    m_structure = ContainerDataStructure(modality, org, layout);
    m_structure.dimensions = DataDimension::create_dimensions(modality, shape, layout);
    m_structure.time_dims = m_num_frames;
    m_structure.channel_dims = m_num_channels;
}
References MayaFlux::Kakshya::AUDIO_1D, MayaFlux::Kakshya::AUDIO_MULTICHANNEL, MayaFlux::Kakshya::ContainerDataStructure::channel_dims, MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Kakshya::ContainerDataStructure::dimensions, m_num_channels, m_num_frames, m_structure, MayaFlux::Kakshya::ContainerDataStructure::memory_layout, MayaFlux::Kakshya::ContainerDataStructure::organization, and MayaFlux::Kakshya::ContainerDataStructure::time_dims.
Referenced by clear(), reorganize_data_layout(), MayaFlux::Kakshya::DynamicSoundStream::set_all_data(), set_memory_layout(), MayaFlux::Kakshya::SoundFileContainer::set_raw_data(), MayaFlux::Kakshya::SoundFileContainer::setup(), SoundStreamContainer(), MayaFlux::Kakshya::DynamicSoundStream::validate(), and MayaFlux::Kakshya::DynamicSoundStream::validate_single_channel().