MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::create_expanded_data
create_expanded_data()
std::vector< DataVariant > MayaFlux::Kakshya::DynamicSoundStream::create_expanded_data (uint64_t new_frame_count) private
Definition at line 377 of file DynamicSoundStream.cpp.
{
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        std::vector<DataVariant> expanded_data(1);
        if (m_data.empty()) {
            expanded_data[0] = DataVariant(std::vector<double>(new_frame_count * get_num_channels(), 0.0));
        } else {
            std::vector<double> current_data;
            extract_from_variant(m_data[0], current_data);
            std::vector<double> expanded_buffer(new_frame_count * get_num_channels(), 0.0);
            std::ranges::copy_n(current_data.begin(),
                std::min<size_t>(current_data.size(), expanded_buffer.size()),
                expanded_buffer.begin());
            expanded_data[0] = DataVariant(std::move(expanded_buffer));
        }
        return expanded_data;
    }
    return std::views::iota(0U, get_num_channels())
        | std::views::transform([this, new_frame_count](uint32_t ch) -> DataVariant {
              if (ch < m_data.size()) {
                  std::vector<double> current_channel_data;
                  extract_from_variant(m_data[ch], current_channel_data);
                  std::vector<double> expanded_channel(new_frame_count, 0.0);
                  std::ranges::copy_n(current_channel_data.begin(),
                      std::min<size_t>(current_channel_data.size(), expanded_channel.size()),
                      expanded_channel.begin());
                  return { std::move(expanded_channel) };
              }
              return { std::vector<double>(new_frame_count, 0.0) };
          })
        | std::ranges::to<std::vector>();
}
References MayaFlux::Kakshya::extract_from_variant(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Kakshya::SoundStreamContainer::m_data, MayaFlux::Kakshya::SoundStreamContainer::m_structure, and MayaFlux::Kakshya::ContainerDataStructure::organization.
Referenced by expand_to().