MayaFlux: MayaFlux::Kakshya::ContiguousAccessProcessor::on_attach
on_attach()
void ContiguousAccessProcessor::on_attach (const std::shared_ptr< SignalSourceContainer > & container) override virtual
Attach the processor to a signal source container.
Initializes dimension metadata, memory layout, and prepares for processing.
Parameters
container The SignalSourceContainer to attach to.
Implements MayaFlux::Kakshya::DataProcessor.
Definition at line 10 of file ContiguousAccessProcessor.cpp.
{
    if (!container) {
        return;
    }
    m_source_container_weak = container;
    try {
        store_metadata(container);
        validate();
        m_prepared = true;
        container->mark_ready_for_processing(true);
        MF_INFO(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "ContiguousAccessProcessor attached: {} layout, {} total elements, {} channels",
            (m_structure.organization == OrganizationStrategy::INTERLEAVED ? "interleaved" : "planar"),
            m_total_elements,
            m_structure.get_channel_count());
    } catch (const std::exception& e) {
        m_prepared = false;
        error_rethrow(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "Failed to attach ContiguousAccessProcessor: {}",
            e.what());
    }
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Journal::Kakshya, m_prepared, m_source_container_weak, m_structure, m_total_elements, MF_INFO, MayaFlux::Kakshya::ContainerDataStructure::organization, store_metadata(), and validate().