MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode
TopologyGeneratorNode() [1/2]
MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode (Kinesis::ProximityMode mode = Kinesis::ProximityMode::SEQUENTIAL, bool auto_connect = true, size_t max_points = 256) explicit
Create topology generator.
Parameters
mode Connection generation rule
auto_connect If true, regenerate topology on every point addition
max_points Maximum point capacity
Definition at line 15 of file TopologyGeneratorNode.cpp.
    : GeometryWriterNode(static_cast<uint32_t>(max_points * max_points))
    , m_mode(mode)
    , m_points(max_points)
    , m_auto_connect(auto_connect)
{
    const auto& stride = sizeof(LineVertex);
    set_vertex_stride(stride);
    auto layout = Kakshya::VertexLayout::for_lines(stride);
    layout.vertex_count = 0;
    set_vertex_layout(layout);
    m_vertices.reserve(max_points * max_points);
    m_connections.reserve(max_points * max_points);
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "Created TopologyGeneratorNode with mode {}, auto_connect={}, capacity={}",
        static_cast<int>(mode), auto_connect, max_points);
}
References MayaFlux::Kakshya::VertexLayout::for_lines(), m_connections, m_vertices, MF_DEBUG, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride().