MayaFlux: Lila::Server::stop
stop()
void Lila::Server::stop () noexcept
Stops the server and disconnects all clients.
Definition at line 157 of file Server.cpp.
{
    if (!m_running)
        return;
    m_running = false;
    if (m_server_thread.joinable()) {
        m_server_thread.request_stop();
        m_server_thread.join();
    }
    if (m_server_fd >= 0) {
        socket_close(m_server_fd);
        m_server_fd = -1;
    }
    {
        std::unique_lock lock(m_clients_mutex);
        for (const auto& [fd, client] : m_connected_clients) {
            socket_close(fd);
        }
        m_connected_clients.clear();
    }
    m_event_bus.publish(StreamEvent { EventType::ServerStop });
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    WSACleanup();
#endif
    LILA_INFO(Emitter::SERVER, "Server stopped");
}
References Lila::ServerThread::join(), Lila::ServerThread::joinable(), LILA_INFO, m_clients_mutex, m_connected_clients, m_event_bus, m_running, m_server_fd, m_server_thread, Lila::EventBus::publish(), Lila::ServerThread::request_stop(), and Lila::socket_close().
Referenced by ~Server().