MayaFlux: Lila::Server::read_message
read_message()
std::expected< std::string, std::string > Lila::Server::read_message (int client_fd) private
Reads a message from a client.
Parameters
client_fd Client file descriptor
Returns
Expected message string or error string
Definition at line 351 of file Server.cpp.
{
    constexpr size_t BUFFER_SIZE = 4096;
    std::string result;
    result.reserve(BUFFER_SIZE);
    std::array<char, BUFFER_SIZE> buffer {};
    while (true) {
        ssize_t bytes_read = socket_read(client_fd, buffer.data(), buffer.size() - 1);
        if (bytes_read < 0) {
#ifdef MAYAFLUX_PLATFORM_WINDOWS
            int code = socket_errno();
            if (code == WSAEWOULDBLOCK) {
                return std::unexpected("would_block");
            }
            return std::unexpected("read error: " + socket_error_string(code));
#else
            if (errno == EAGAIN || errno == EWOULDBLOCK) {
                return std::unexpected("would_block");
            }
            return std::unexpected("read error: " + std::string(strerror(errno)));
#endif
        }
        if (bytes_read == 0) {
            return std::unexpected("client_disconnected");
        }
        buffer[bytes_read] = '\0';
        result.append(buffer.data());
        if (!result.empty() && result.back() == '\n') {
            result.pop_back();
            if (!result.empty() && result.back() == '\r') {
                result.pop_back();
            }
            break;
        }
        if (result.size() > static_cast<size_t>(1024 * 1024)) {
            return std::unexpected("message_too_large");
        }
    }
    return result;
}
References Lila::socket_errno(), Lila::socket_error_string(), and Lila::socket_read().
Referenced by handle_client().