MayaFlux: MayaFlux::Kriya::TemporalActivation::cancel
cancel()
void MayaFlux::Kriya::TemporalActivation::cancel ()
Cancels any currently active node.
This method deactivates any currently active node, nodenetowrk or buffer, disconnecting it from the output channel. If no node is active, this method has no effect.
Definition at line 193 of file Timers.cpp.
{
    if (m_timer.is_active()) {
        cleanup_current_operation();
    }
    m_timer.cancel();
}
References MayaFlux::Kriya::Timer::cancel(), cleanup_current_operation(), MayaFlux::Kriya::Timer::is_active(), and m_timer.
Referenced by activate_buffer(), activate_network(), and activate_node().