MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::set_output_mode
set_output_mode()
void MayaFlux::Nodes::Network::NodeNetwork::set_output_mode (OutputMode mode) inline
Set the network's output routing mode.
Definition at line 176 of file NodeNetwork.hpp.
{ m_output_mode = mode; }
Referenced by MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::Network::ParticleNetwork::ParticleNetwork(), MayaFlux::Nodes::Network::PointCloudNetwork::PointCloudNetwork(), MayaFlux::Nodes::Network::PointCloudNetwork::PointCloudNetwork(), and MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideNetwork().