MayaFlux: MayaFlux::Nodes::NodeGraphManager::process_token
process_token()
void MayaFlux::Nodes::NodeGraphManager::process_token (ProcessingToken token, unsigned int num_samples = 1)
Process all nodes in a specific token domain Calls registered processor if available, otherwise calls process() on each root.
Parameters
token Processing domain to process
num_samples Number of samples/frames to process
Processes all root nodes for the specified processing domain (token). If a custom processor is registered for the token, it is called with all root nodes. Otherwise, process() is called on each root node individually.
Definition at line 109 of file NodeGraphManager.cpp.
{
    if (m_terminate_requested.load())
        return;
    auto roots = get_all_root_nodes(token);
    if (auto it = m_token_processors.find(token); it != m_token_processors.end()) {
        it->second(std::span<RootNode*>(roots.data(), roots.size()));
        return;
    }
    if (!preprocess_networks(token)) {
        return;
    }
    auto it = m_token_networks.find(token);
    if (it != m_token_networks.end()) {
        for (auto& network : it->second) {
            if (!network || !network->is_enabled()) {
                continue;
            }
            if (!network->is_processed_this_cycle()) {
                network->mark_processing(true);
                network->process_batch(num_samples);
                network->mark_processing(false);
                network->mark_processed(true);
            }
        }
    }
    postprocess_networks(token, std::nullopt);
    if (token == ProcessingToken::AUDIO_RATE) {
        for (auto* root : roots) {
            root->process_batch(num_samples);
        }
    } else if (token == ProcessingToken::VISUAL_RATE) {
        for (auto* root : roots) {
            root->process_batch_frame(num_samples);
        }
    }
}
References MayaFlux::Nodes::AUDIO_RATE, get_all_root_nodes(), m_terminate_requested, m_token_networks, m_token_processors, network, postprocess_networks(), preprocess_networks(), and MayaFlux::Nodes::VISUAL_RATE.
Referenced by process_all_tokens().