MayaFlux: MayaFlux::Buffers::BufferProcessingControl::add_audio_processor
add_audio_processor()
void MayaFlux::Buffers::BufferProcessingControl::add_audio_processor (const std::shared_ptr< BufferProcessor > & processor, const std::shared_ptr< AudioBuffer > & buffer)
Adds a processor to a specific audio buffer.
Parameters
processor Processor to add
buffer Target audio buffer
Routes the processor to the appropriate processing chain based on the buffer's channel ID.
Definition at line 110 of file BufferProcessingControl.cpp.
{
    uint32_t channel_id = buffer->get_channel_id();
    for (const auto& token : m_unit_manager.get_active_audio_tokens()) {
        const auto& unit = m_unit_manager.get_audio_unit(token);
        if (channel_id < unit.channel_count) {
            auto processing_chain = unit.get_chain(channel_id);
            processing_chain->add_processor(processor, buffer);
            buffer->set_processing_chain(processing_chain);
            return;
        }
    }
    // Fallback: use global processing chain if no token matches
    // This requires BufferManager to provide access to global chain
    // For now, we log a warning
    MF_WARN(Journal::Component::Core, Journal::Context::BufferManagement,
        "Could not find matching token for audio buffer with channel ID {}", channel_id);
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Buffers::TokenUnitManager::get_active_audio_tokens(), MayaFlux::Buffers::TokenUnitManager::get_audio_unit(), MayaFlux::Buffers::RootAudioUnit::get_chain(), m_unit_manager, and MF_WARN.
Referenced by add_processor(), and connect_node_to_audio_buffer().