MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::clear
clear()
void MayaFlux::Kakshya::SoundStreamContainer::clear () override virtual
Clear all data in the container.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 311 of file SoundStreamContainer.cpp.
{
    std::unique_lock lock(m_data_mutex);
    std::ranges::for_each(m_data, [](auto& vec) {
        std::visit([](auto& v) { v.clear(); }, vec);
    });
    std::ranges::for_each(m_processed_data, [](auto& vec) {
        std::visit([](auto& v) { v.clear(); }, vec);
    });
    m_num_frames = 0;
    m_circular_write_position = 0;
    m_read_position = std::vector<std::atomic<uint64_t>>(m_num_channels);
    for (auto& pos : m_read_position) {
        pos.store(0);
    }
    setup_dimensions();
    update_processing_state(ProcessingState::IDLE);
}
References MayaFlux::Kakshya::IDLE, lock(), m_circular_write_position, m_data, m_data_mutex, m_num_channels, m_num_frames, m_processed_data, m_read_position, setup_dimensions(), and update_processing_state().