MayaFlux: MayaFlux::Kakshya::WindowContainer::setup_dimensions
setup_dimensions()
void MayaFlux::Kakshya::WindowContainer::setup_dimensions () private
Definition at line 78 of file WindowContainer.cpp.
{
    const auto& fmt = m_window->get_create_info().container_format;
    const uint32_t w = m_window->get_create_info().width;
    const uint32_t h = m_window->get_create_info().height;
    const uint32_t c = fmt.color_channels;
    m_structure = ContainerDataStructure::image_interleaved();
    m_structure.dimensions = DataDimension::create_dimensions(
        DataModality::IMAGE_COLOR,
        { static_cast<uint64_t>(h), static_cast<uint64_t>(w), static_cast<uint64_t>(c) },
        MemoryLayout::ROW_MAJOR);
    const size_t sz = static_cast<size_t>(w) * h * c;
    m_processed_data.resize(1);
    m_processed_data[0] = std::vector<uint8_t>(sz, 0U);
}
References MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Kakshya::ContainerDataStructure::dimensions, h, MayaFlux::Kakshya::IMAGE_COLOR, MayaFlux::Kakshya::ContainerDataStructure::image_interleaved(), m_processed_data, m_structure, m_window, and MayaFlux::Kakshya::ROW_MAJOR.
Referenced by WindowContainer().