MayaFlux: MayaFlux::Kriya::BufferPipeline::dispatch_branch_async
dispatch_branch_async()
std::shared_ptr< Vruta::SoundRoutine > MayaFlux::Kriya::BufferPipeline::dispatch_branch_async (BranchInfo & branch, uint64_t cycle) private
Definition at line 645 of file BufferPipeline.cpp.
{
    if (!m_scheduler)
        return nullptr;
    if (!m_coordinator) {
        m_coordinator = std::make_unique<CycleCoordinator>(*m_scheduler);
    }
    branch.pipeline->m_active_self = branch.pipeline;
    auto branch_routine = branch.pipeline->execute_internal(1, branch.samples_per_operation);
    auto task = std::make_shared<Vruta::SoundRoutine>(std::move(branch_routine));
    m_scheduler->add_task(task);
    m_branch_tasks.push_back(task);
    return task;
}
References MayaFlux::Vruta::TaskScheduler::add_task(), m_branch_tasks, m_coordinator, m_scheduler, MayaFlux::Kriya::BufferPipeline::BranchInfo::pipeline, and MayaFlux::Kriya::BufferPipeline::BranchInfo::samples_per_operation.
Referenced by execute_phased(), and execute_streaming().