MayaFlux: MayaFlux::Buffers::TokenUnitManager::has_graphics_unit
has_graphics_unit()
bool MayaFlux::Buffers::TokenUnitManager::has_graphics_unit (ProcessingToken token) const
Checks if a graphics unit exists for the given token.
Parameters
token Processing domain
Returns
True if the unit exists, false otherwise
Definition at line 169 of file TokenUnitManager.cpp.
{
    return m_graphics_units.find(token) != m_graphics_units.end();
}
References m_graphics_units.
Referenced by MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers_by_usage(), MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer(), and MayaFlux::Buffers::BufferProcessingControl::remove_graphics_processor().