MayaFlux: MayaFlux::Buffers::GeometryBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::GeometryBuffer::setup_processors (ProcessingToken token) override virtual
Initialize the buffer and its processors.
Reimplemented from MayaFlux::Buffers::VKBuffer.
Definition at line 37 of file GeometryBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<GeometryBuffer>(shared_from_this());
    m_bindings_processor = std::make_shared<GeometryBindingsProcessor>();
    m_bindings_processor->set_processing_token(token);
    m_bindings_processor->bind_geometry_node(
        m_binding_name,
        m_geometry_node,
        self);
    set_default_processor(m_bindings_processor);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
}
References MayaFlux::Buffers::VKBuffer::get_processing_chain(), m_binding_name, m_bindings_processor, m_geometry_node, MayaFlux::Buffers::VKBuffer::set_default_processor(), and MayaFlux::Buffers::VKBuffer::set_processing_chain().