MayaFlux: MayaFlux::Kakshya::WindowAccessProcessor::on_attach
on_attach()
void MayaFlux::Kakshya::WindowAccessProcessor::on_attach (const std::shared_ptr< SignalSourceContainer > & container) override virtual
Attach to a WindowContainer.
Queries the live swapchain format and caches surface traits. Throws std::invalid_argument if container is not a WindowContainer.
Implements MayaFlux::Kakshya::DataProcessor.
Definition at line 13 of file WindowAccessProcessor.cpp.
{
    auto wc = std::dynamic_pointer_cast<WindowContainer>(container);
    if (!wc) {
        error<std::invalid_argument>(
            Journal::Component::Kakshya,
            Journal::Context::ContainerProcessing,
            std::source_location::current(),
            "WindowAccessProcessor requires a WindowContainer");
    }
    const auto& s = wc->get_structure();
    m_width = static_cast<uint32_t>(s.get_width());
    m_height = static_cast<uint32_t>(s.get_height());
    m_surface_format = query_surface_format(wc->get_window());
    const uint32_t bpp = Core::vk_format_bytes_per_pixel(
        Core::to_vk_format(m_surface_format));
    container->mark_ready_for_processing(true);
    MF_INFO(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
        "WindowAccessProcessor attached: {}x{} format={} bpp={}",
        m_width, m_height,
        static_cast<uint32_t>(m_surface_format),
        bpp);
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Journal::Kakshya, m_height, m_surface_format, m_width, MF_INFO, MayaFlux::Kakshya::query_surface_format(), MayaFlux::Core::to_vk_format(), and MayaFlux::Core::vk_format_bytes_per_pixel().