MayaFlux: MayaFlux::TemporalWrapper::entity
entity()
template<typename T > std::shared_ptr< T > MayaFlux::TemporalWrapper< T >::entity () const inline
Definition at line 99 of file Temporal.hpp.
{ return m_entity; }
References MayaFlux::TemporalWrapper< T >::m_entity.
Referenced by MayaFlux::operator|(), MayaFlux::operator|(), and MayaFlux::operator|().