MayaFlux: MayaFlux::Kakshya::WindowContainer::image_at
image_at() [1/2]
std::shared_ptr< Core::VKImage > MayaFlux::Kakshya::WindowContainer::image_at (uint32_t frame_index) const
Upload m_data[frame_index] to a new VKImage.
Parameters
frame_index Index into m_data in [0, frame_capacity).
Definition at line 247 of file WindowContainer.cpp.
{
    if (frame_index >= m_data.size()) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::to_image({}) : out of range (capacity={})",
            frame_index, m_frame_capacity);
        return nullptr;
    }
    const uint64_t written = m_frames_written.load(std::memory_order_acquire);
    const uint32_t head = m_write_head.load(std::memory_order_acquire);
    const bool ring_full = written >= m_frame_capacity;
    if (!ring_full && frame_index >= head) {
        MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
            "WindowContainer::image_at({}) : frame index is ahead of write head ({}), data may be stale or uninitialized",
            frame_index, head);
        return nullptr;
    }
    std::shared_ptr<Core::VKImage> img;
    seqlock_read_void(m_data_lock, 8, [&] {
        const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_data[frame_index]);
        if (!pixels || pixels->empty()) {
            MF_RT_WARN(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
                "WindowContainer::image_at({}) : slot is empty", frame_index);
            return;
        }
        const auto img_fmt = surface_format_to_image_format(query_surface_format(m_window));
        img = Portal::Graphics::TextureLoom::instance().create_2d(
            m_structure.get_width(), m_structure.get_height(), img_fmt, pixels->data());
        if (!img) {
            MF_RT_ERROR(Journal::Component::Kakshya, Journal::Context::ContainerProcessing,
                "WindowContainer::image_at({}) : TextureLoom::create_2d failed", frame_index);
        }
    });
    return img;
}
References MayaFlux::Journal::ContainerProcessing, MayaFlux::Portal::Graphics::TextureLoom::create_2d(), MayaFlux::Kakshya::ContainerDataStructure::get_height(), MayaFlux::Kakshya::ContainerDataStructure::get_width(), MayaFlux::Portal::Graphics::TextureLoom::instance(), MayaFlux::Journal::Kakshya, m_data, m_data_lock, m_frame_capacity, m_frames_written, m_structure, m_window, m_write_head, MF_RT_ERROR, MF_RT_WARN, pixels, and MayaFlux::Kakshya::query_surface_format().