MayaFlux: MayaFlux::Kakshya::RegionOrganizationProcessor::process_organized_regions
process_organized_regions()
void MayaFlux::Kakshya::RegionOrganizationProcessor::process_organized_regions (const std::shared_ptr< SignalSourceContainer > & container, std::vector< DataVariant > & output_data) protected virtual
Process regions according to their selection pattern.
Parameters
container The signal container to process.
output_data Output data variant to fill.
Definition at line 188 of file RegionProcessors.cpp.
{
    if (m_organized_regions.empty())
        return;
    auto& current_region = m_organized_regions[m_current_region_index];
    current_region.state = RegionState::ACTIVE;
    size_t selected_segment = select_next_segment(current_region);
    bool segment_changed = (selected_segment != current_region.active_segment_index);
    bool segment_completed = is_segment_complete(current_region, selected_segment);
    bool region_completed = (segment_completed && selected_segment == current_region.segments.size() - 1);
    if (region_completed && m_current_region_index < m_organized_regions.size() - 1) {
        auto& next_region = m_organized_regions[m_current_region_index + 1];
        bool should_transition = false;
        switch (current_region.transition_type) {
        case RegionTransition::IMMEDIATE:
            should_transition = false;
            break;
        case RegionTransition::CROSSFADE:
        case RegionTransition::OVERLAP:
            should_transition = (current_region.transition_duration_ms > 0);
            break;
        default:
            should_transition = false;
            break;
        }
        if (should_transition) {
            apply_region_transition(current_region, next_region, container, output_data);
        } else {
            process_region_segment(current_region, current_region.segments[selected_segment],
                container, output_data);
        }
        m_current_region_index++;
        auto& new_current = m_organized_regions[m_current_region_index];
        new_current.state = RegionState::READY;
        new_current.active_segment_index = 0;
    } else {
        process_region_segment(current_region, current_region.segments[selected_segment],
            container, output_data);
        current_region.active_segment_index = selected_segment;
    }
}
References MayaFlux::Kakshya::ACTIVE, apply_region_transition(), MayaFlux::Kakshya::CROSSFADE, MayaFlux::Kakshya::IMMEDIATE, MayaFlux::Kakshya::is_segment_complete(), MayaFlux::Kakshya::RegionProcessorBase::m_current_region_index, MayaFlux::Kakshya::RegionProcessorBase::m_organized_regions, MayaFlux::Kakshya::OVERLAP, process_region_segment(), MayaFlux::Kakshya::READY, and select_next_segment().
Referenced by process().