MayaFlux: MayaFlux::Yantra::GpuResourceManager::cleanup
cleanup()
void MayaFlux::Yantra::GpuResourceManager::cleanup ()
Definition at line 155 of file GpuResourceManager.cpp.
{
    if (!m_ready) {
        return;
    }
    auto& foundry = Portal::Graphics::get_shader_foundry();
    auto& compute_press = Portal::Graphics::get_compute_press();
    auto device = foundry.get_device();
    if (m_impl) {
        for (auto& slot : m_impl->buffers) {
            free_slot(device, slot);
        }
    }
    m_impl.reset();
    m_slots.clear();
    if (m_pipeline_id != Portal::Graphics::INVALID_COMPUTE_PIPELINE) {
        compute_press.destroy_pipeline(m_pipeline_id);
        m_pipeline_id = Portal::Graphics::INVALID_COMPUTE_PIPELINE;
    }
    if (m_shader_id != Portal::Graphics::INVALID_SHADER) {
        foundry.destroy_shader(m_shader_id);
        m_shader_id = Portal::Graphics::INVALID_SHADER;
    }
    m_descriptor_set_ids.clear();
    m_ready = false;
}
References MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, MayaFlux::Portal::Graphics::INVALID_SHADER, m_descriptor_set_ids, m_impl, m_pipeline_id, m_ready, m_shader_id, and m_slots.
Referenced by ~GpuResourceManager().