MayaFlux: Lila::Server::server_loop
server_loop()
void Lila::Server::server_loop (const ServerThread::StopToken & stop_token) private
Main server loop; accepts and manages clients.
Parameters
stop_token Token to signal server shutdown
Definition at line 194 of file Server.cpp.
{
    while (!stop_token.stop_requested() && m_running) {
        fd_set readfds;
        FD_ZERO(&readfds);
        FD_SET(m_server_fd, &readfds);
        timeval timeout { .tv_sec = 1, .tv_usec = 0 };
#ifdef MAYAFLUX_PLATFORM_WINDOWS
        int activity = select(0, &readfds, nullptr, nullptr, &timeout); // nfds ignored on Windows
#else
        int activity = select(m_server_fd + 1, &readfds, nullptr, nullptr, &timeout);
#endif
        if (activity < 0) {
            int code = socket_errno();
#ifndef MAYAFLUX_PLATFORM_WINDOWS
            if (code == EINTR)
                continue;
#endif
            if (m_running) {
                LILA_ERROR(Emitter::SERVER, "Select error: " + socket_error_string(code));
            }
            break;
        }
        if (activity == 0)
            continue;
        sockaddr_in client_addr {};
        socklen_t client_len = sizeof(client_addr);
#ifdef MAYAFLUX_PLATFORM_WINDOWS
        SOCKET client_socket = accept(static_cast<SOCKET>(m_server_fd), reinterpret_cast<sockaddr*>(&client_addr), &client_len);
        int client_fd = static_cast<int>(client_socket);
        if (client_socket == INVALID_SOCKET) {
            int code = socket_errno();
            if (code == WSAEWOULDBLOCK)
                continue;
            if (m_running) {
                LILA_ERROR(Emitter::SERVER, "Accept failed: " + socket_error_string(code));
            }
            continue;
        }
#else
        int client_fd = accept(m_server_fd, reinterpret_cast<sockaddr*>(&client_addr), &client_len);
        if (client_fd < 0) {
            if (errno == EAGAIN || errno == EWOULDBLOCK)
                continue;
            if (m_running) {
                LILA_ERROR(Emitter::SERVER, "Accept failed: " + std::string(strerror(errno)));
            }
            continue;
        }
#endif
        if (set_nonblocking(client_fd) < 0) {
            LILA_WARN(Emitter::SERVER, "Failed to set non-blocking on client fd " + std::to_string(client_fd));
        }
        handle_client(client_fd);
    }
}
References LILA_ERROR, LILA_WARN, Lila::set_nonblocking(), Lila::socket_errno(), Lila::socket_error_string(), and Lila::ServerThread::StopToken::stop_requested().
Referenced by start().