MayaFlux: MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer
remove_graphics_buffer()
void MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer (const std::shared_ptr< Buffer > & buffer, ProcessingToken token)
Removes a graphics buffer from a token.
Parameters
buffer Graphics buffer to remove
token Processing domain
Definition at line 255 of file BufferAccessControl.cpp.
{
    if (!buffer) {
        MF_WARN(Journal::Component::Core, Journal::Context::BufferManagement,
            "Attempted to remove null graphics buffer from token {}",
            static_cast<int>(token));
        return;
    }
    if (auto vk_buffer = std::dynamic_pointer_cast<VKBuffer>(buffer)) {
        if (!m_unit_manager.has_graphics_unit(token)) {
            MF_WARN(Journal::Component::Core, Journal::Context::BufferManagement,
                "Token {} not found when removing graphics buffer",
                static_cast<int>(token));
            return;
        }
        auto& unit = m_unit_manager.get_graphics_unit_mutable(token);
        unit.get_buffer()->remove_child_buffer(vk_buffer);
        try {
            auto buffer_service = Registry::BackendRegistry::instance()
                                      .get_service<Registry::Service::BufferService>();
            if (vk_buffer->is_initialized()) {
                buffer_service->destroy_buffer(vk_buffer);
            }
        } catch (const std::exception& e) {
            error_rethrow(Journal::Component::Core, Journal::Context::BufferManagement,
                std::source_location::current(),
                "Failed to cleanup graphics buffer for token {}: {}",
                static_cast<int>(token), e.what());
        }
        MF_INFO(Journal::Component::Core, Journal::Context::BufferManagement,
            "Removed graphics buffer from token {} (remaining: {})",
            static_cast<int>(token),
            unit.get_buffer()->get_buffer_count());
    } else {
        error<std::invalid_argument>(Journal::Component::Core, Journal::Context::BufferManagement,
            std::source_location::current(),
            "Unsupported graphics buffer type for token {}",
            static_cast<int>(token));
    }
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Core, MayaFlux::Registry::Service::BufferService::destroy_buffer, MayaFlux::Buffers::RootGraphicsUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::get_graphics_unit_mutable(), MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Buffers::TokenUnitManager::has_graphics_unit(), MayaFlux::Registry::BackendRegistry::instance(), m_unit_manager, MF_INFO, and MF_WARN.
Referenced by remove_buffer(), and terminate_active_buffers().