MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::build_interpolated_path
build_interpolated_path()
void MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::build_interpolated_path (std::span< LineVertex > points, size_t num_points) private
Definition at line 293 of file TopologyGeneratorNode.cpp.
{
    Eigen::MatrixXd control_points(3, num_points);
    for (Eigen::Index i = 0; i < num_points; ++i) {
        control_points.col(i) << points[i].position.x,
            points[i].position.y,
            points[i].position.z;
    }
    size_t num_segments = num_points - 1;
    Eigen::Index total_samples = 1 + (Eigen::Index)num_segments * ((Eigen::Index)m_samples_per_segment - 1);
    Eigen::MatrixXd dense_points = Kinesis::generate_interpolated_points(
        control_points,
        total_samples,
        m_path_interpolation_mode,
        0.5);
    if (m_use_arc_length_reparameterization) {
        dense_points = Kinesis::reparameterize_by_arc_length(
            dense_points, total_samples);
    }
    m_vertices.clear();
    m_vertices.reserve((dense_points.cols() - 1) * 2);
    for (Eigen::Index i = 0; i < dense_points.cols() - 1; ++i) {
        float t0 = float(i) / float(total_samples - 1);
        float t1 = float(i + 1) / float(total_samples - 1);
        auto segment_idx0 = std::min<size_t>(size_t(t0 * float(num_segments)), num_segments - 1);
        auto segment_idx1 = std::min<size_t>(size_t(t1 * float(num_segments)), num_segments - 1);
        glm::vec3 color0 = m_force_uniform_color ? m_line_color : points[segment_idx0].color;
        glm::vec3 color1 = m_force_uniform_color ? m_line_color : points[segment_idx1].color;
        float thick0 = m_force_uniform_thickness ? m_line_thickness : points[segment_idx0].thickness;
        float thick1 = m_force_uniform_thickness ? m_line_thickness : points[segment_idx1].thickness;
        m_vertices.emplace_back(LineVertex {
            .position = glm::vec3(dense_points(0, i), dense_points(1, i), dense_points(2, i)),
            .color = color0,
            .thickness = thick0 });
        m_vertices.emplace_back(LineVertex {
            .position = glm::vec3(dense_points(0, i + 1), dense_points(1, i + 1), dense_points(2, i + 1)),
            .color = color1,
            .thickness = thick1 });
    }
}
References MayaFlux::Kinesis::generate_interpolated_points(), m_force_uniform_color, m_force_uniform_thickness, m_line_color, m_line_thickness, m_path_interpolation_mode, m_samples_per_segment, m_use_arc_length_reparameterization, m_vertices, MayaFlux::Nodes::LineVertex::position, and MayaFlux::Kinesis::reparameterize_by_arc_length().
Referenced by build_vertex_buffer().