MayaFlux: MayaFlux::Kakshya::EigenAccess::is_complex
is_complex()
bool MayaFlux::Kakshya::EigenAccess::is_complex () const
Check if data contains complex numbers.
Returns
true if complex data
Definition at line 191 of file EigenAccess.cpp.
{
    return std::visit([](const auto& vec) -> bool {
        using T = typename std::decay_t<decltype(vec)>::value_type;
        return std::is_same_v<T, std::complex<float>> || std::is_same_v<T, std::complex<double>>;
    },
        m_variant);
}
References m_variant.
Referenced by MayaFlux::Kinesis::interpolate_nddata(), to_complex_vector(), to_magnitude_vector(), and to_phase_vector().