MayaFlux: MayaFlux::Kriya::EventChain::cancel
cancel()
void MayaFlux::Kriya::EventChain::cancel ()
Cancels the event chain if it's currently executing.
Terminates the underlying coroutine, preventing any remaining events from executing. Safe to call even if chain has completed.
Definition at line 121 of file Chain.cpp.
{
    if (is_active()) {
        m_Scheduler.cancel_task(m_routine);
        m_routine = nullptr;
        fire_on_complete();
    }
}
References MayaFlux::Vruta::TaskScheduler::cancel_task(), fire_on_complete(), is_active(), m_routine, and m_Scheduler.