MayaFlux: MayaFlux::Nodes::Network::FieldOperator::store_reference
store_reference()
void MayaFlux::Nodes::Network::FieldOperator::store_reference (const void * data, size_t count) private
Definition at line 17 of file FieldOperator.cpp.
{
    m_count = count;
    size_t total = count * k_stride;
    m_reference_data.resize(total);
    m_vertex_data.resize(total);
    std::memcpy(m_reference_data.data(), data, total);
    std::memcpy(m_vertex_data.data(), data, total);
    m_dirty = true;
}
References count, k_stride, m_count, m_dirty, m_reference_data, and m_vertex_data.
Referenced by initialize(), initialize(), and initialize().