MayaFlux: MayaFlux::Core::AudioSubsystem::process_audio
process_audio()
int MayaFlux::Core::AudioSubsystem::process_audio (double * input_buffer, double * output_buffer, unsigned int num_frames)
Processes both input and output data in full-duplex mode.
Parameters
input_buffer Pointer to input data buffer
output_buffer Pointer to output data buffer
num_frames Number of frames to process
Returns
Status code (0 for success)
Handles full-duplex audio processing, processing input and generating output simultaneously. Used for real-time effects and monitoring scenarios.
Definition at line 188 of file AudioSubsystem.cpp.
{
    for (const auto& [name, hook] : m_handle->pre_process_hooks) {
        hook(num_frames);
    }
    process_input(input_buffer, num_frames);
    process_output(output_buffer, num_frames);
    for (const auto& [name, hook] : m_handle->post_process_hooks) {
        hook(num_frames);
    }
    return 0;
}
References m_handle, MayaFlux::Core::SubsystemProcessingHandle::post_process_hooks, MayaFlux::Core::SubsystemProcessingHandle::pre_process_hooks, process_input(), and process_output().
Referenced by register_callbacks().