MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::write_frames
write_frames() [2/2]
uint64_t MayaFlux::Kakshya::DynamicSoundStream::write_frames (std::vector< std::span< const double > > data, uint64_t start_frame = 0)
Definition at line 102 of file DynamicSoundStream.cpp.
{
    auto num_frames = validate(data, start_frame);
    if (!num_frames)
        return 0;
    if (m_is_circular && start_frame + num_frames > m_circular_capacity) {
        uint64_t frames_to_end = m_circular_capacity - start_frame;
        uint64_t frames_from_start = num_frames - frames_to_end;
        if (frames_to_end > 0) {
            std::vector<std::span<const double>> first_part;
            first_part.reserve(data.size());
            for (const auto& span : data) {
                first_part.emplace_back(span.subspan(0, frames_to_end));
            }
            write_frames(first_part, start_frame);
        }
        if (frames_from_start > 0) {
            std::vector<std::span<const double>> second_part;
            second_part.reserve(data.size());
            for (const auto& span : data) {
                second_part.emplace_back(span.subspan(frames_to_end, frames_from_start));
            }
            write_frames(second_part, 0);
        }
        return num_frames;
    }
    Region write_region {
        { start_frame, 0 },
        { start_frame + num_frames - 1, get_num_channels() - 1 }
    };
    std::vector<DataVariant> data_variants;
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        uint64_t samples_to_write = num_frames * get_num_channels();
        data_variants.emplace_back(
            std::vector<double>(data[0].begin(), data[0].begin() + samples_to_write));
    } else {
        data_variants = data
            | std::views::take(get_num_channels())
            | std::views::transform([num_frames](const auto& span) -> DataVariant {
                  return DataVariant(std::vector<double>(span.begin(), span.begin() + num_frames));
              })
            | std::ranges::to<std::vector>();
    }
    set_region_data(write_region, data_variants);
    if (m_is_circular) {
        m_num_frames = std::min(m_circular_capacity, m_num_frames);
    }
    return num_frames;
}
References MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::INTERLEAVED, m_circular_capacity, m_is_circular, MayaFlux::Kakshya::SoundStreamContainer::m_num_frames, MayaFlux::Kakshya::SoundStreamContainer::m_structure, MayaFlux::Kakshya::ContainerDataStructure::organization, MayaFlux::Kakshya::SoundStreamContainer::set_region_data(), validate(), and write_frames().