MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::get_command_buffer
get_command_buffer()
vk::CommandBuffer MayaFlux::Portal::Graphics::ShaderFoundry::get_command_buffer (CommandBufferID cmd_id)
Get Vulkan command buffer handle from CommandBufferID.
Parameters
cmd_id Command buffer ID
Definition at line 763 of file ShaderFoundry.cpp.
{
    auto it = m_command_buffers.find(cmd_id);
    if (it != m_command_buffers.end()) {
        return it->second.cmd;
    }
    return nullptr;
}
References m_command_buffers.
Referenced by MayaFlux::Portal::Graphics::RenderFlow::begin_rendering(), MayaFlux::Portal::Graphics::ComputePress::bind_descriptor_sets(), MayaFlux::Portal::Graphics::RenderFlow::bind_descriptor_sets(), MayaFlux::Portal::Graphics::RenderFlow::bind_index_buffer(), MayaFlux::Portal::Graphics::ComputePress::bind_pipeline(), MayaFlux::Portal::Graphics::RenderFlow::bind_pipeline(), MayaFlux::Portal::Graphics::RenderFlow::bind_vertex_buffers(), MayaFlux::Portal::Graphics::ComputePress::dispatch(), MayaFlux::Portal::Graphics::ComputePress::dispatch_indirect(), MayaFlux::Portal::Graphics::RenderFlow::draw(), MayaFlux::Portal::Graphics::RenderFlow::draw_indexed(), MayaFlux::Portal::Graphics::RenderFlow::draw_mesh_tasks(), MayaFlux::Portal::Graphics::RenderFlow::draw_mesh_tasks_indirect(), MayaFlux::Portal::Graphics::RenderFlow::end_rendering(), MayaFlux::Portal::Graphics::ComputePress::push_constants(), and MayaFlux::Portal::Graphics::RenderFlow::push_constants().