MayaFlux: MayaFlux::Kinesis::Stochastic::Stochastic::reset_state
reset_state()
void MayaFlux::Kinesis::Stochastic::Stochastic::reset_state ()
Resets internal state for stateful algorithms.
Memoryless distributions unaffected. Stateful processes return to initial state.
Definition at line 98 of file Stochastic.cpp.
{
    m_state.reset();
}
References m_state, and MayaFlux::Kinesis::Stochastic::GeneratorState::reset().
Referenced by seed(), and set_algorithm().