MayaFlux: MayaFlux::Core::WindowManager::process
process()
bool MayaFlux::Core::WindowManager::process ()
Process windows for one frame.
This is the main per-frame operation that should be called from the application's main loop. It:
Polls GLFW events (triggers EventSource)
Cleans up closed windows
Optionally runs per-frame hooks
Returns
True if processing should continue, false if all windows closed
Definition at line 189 of file WindowManager.cpp.
{
    Parallel::dispatch_main_sync([]() {
        glfwPollEvents();
    });
    {
        std::lock_guard<std::mutex> lock(m_hooks_mutex);
        for (const auto& [name, hook] : m_frame_hooks) {
            hook();
        }
    }
    destroy_closed_windows();
    return window_count() > 0;
}
References destroy_closed_windows(), MayaFlux::Parallel::dispatch_main_sync(), m_frame_hooks, m_hooks_mutex, and window_count().