MayaFlux: MayaFlux::Nodes::NodeGraphManager::add_network
add_network()
void MayaFlux::Nodes::NodeGraphManager::add_network (const std::shared_ptr< Network::NodeNetwork > & network, ProcessingToken token)
Add a network to a processing token.
Parameters
network Network to add
token Processing domain (AUDIO_RATE, VISUAL_RATE, etc.)
Networks are processed parallel to RootNodes, managing their own internal node coordination and processing.
Definition at line 467 of file NodeGraphManager.cpp.
{
    if (!network) {
        return;
    }
    register_network_global(network);
    network->set_enabled(true);
    if (network->get_output_mode() == Network::OutputMode::AUDIO_SINK
        || network->get_output_mode() == Network::OutputMode::AUDIO_COMPUTE) {
        uint32_t channel_mask = network->get_channel_mask();
        if (channel_mask == 0) {
            channel_mask = 1;
            network->add_channel_usage(0);
        }
        auto channels = network->get_registered_channels();
        m_audio_networks[token].push_back(network);
        for (auto ch : channels) {
            ensure_root_exists(token, ch);
            MF_INFO(Journal::Component::Nodes,
                Journal::Context::NodeProcessing,
                "Added audio network to token {} channel {}: {} nodes",
                static_cast<int>(token), ch, network->get_node_count());
        }
    } else {
        m_token_networks[token].push_back(network);
        MF_INFO(Journal::Component::Nodes,
            Journal::Context::NodeProcessing,
            "Added network to token {}: {} nodes, mode={}",
            static_cast<int>(token),
            network->get_node_count(),
            static_cast<int>(network->get_output_mode()));
    }
}
References MayaFlux::Nodes::Network::AUDIO_COMPUTE, MayaFlux::Nodes::Network::AUDIO_SINK, ensure_root_exists(), m_audio_networks, m_token_networks, MF_INFO, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, and register_network_global().
Referenced by MayaFlux::Kriya::TemporalActivation::activate_network().