MayaFlux: MayaFlux::Kriya::Timer::cancel
cancel()
void MayaFlux::Kriya::Timer::cancel ()
Cancels any scheduled callback.
This method cancels any currently scheduled callback, preventing it from executing. If no callback is scheduled, this method has no effect.
Definition at line 45 of file Timers.cpp.
{
    if (m_active && m_routine) {
        m_Scheduler.cancel_task(m_routine);
        m_routine = nullptr;
        m_active = false;
    }
}
References MayaFlux::Vruta::TaskScheduler::cancel_task(), m_active, m_routine, and m_Scheduler.
Referenced by MayaFlux::Kriya::TimedAction::cancel(), MayaFlux::Kriya::TemporalActivation::cancel(), and schedule().