MayaFlux: MayaFlux::Core::WindowManager::destroy_window
destroy_window()
void MayaFlux::Core::WindowManager::destroy_window (const std::shared_ptr< Window > & window, bool cleanup_backend = false)
Destroys a window by pointer.
Parameters
window Pointer to window to destroy
cleanup_backend If true, also cleans up backend resources
Definition at line 58 of file WindowManager.cpp.
{
    if (!window)
        return;
    auto pr_it = std::ranges::find(m_processing_windows, window);
    if (pr_it != m_processing_windows.end()) {
        m_processing_windows.erase(pr_it);
    }
    const std::string title = window->get_create_info().title;
    remove_from_lookup(window);
    auto it = std::ranges::find(m_windows, window);
    if (it != m_windows.end()) {
        m_windows.erase(it);
        MF_INFO(Journal::Component::Core, Journal::Context::WindowingSubsystem,
            "Destroyed window '{}' - remaining: {}", title, m_windows.size());
    }
    if (!cleanup_backend) {
        return;
    }
    if (m_terminate.load()) {
        window->destroy();
    } else {
        Parallel::dispatch_main_sync([&]() {
            window->destroy();
        });
    }
    MF_DEBUG(Journal::Component::Core, Journal::Context::WindowingSubsystem,
        "Backend resources for window '{}' cleaned up", title);
}
References MayaFlux::Journal::Core, MayaFlux::Parallel::dispatch_main_sync(), m_processing_windows, m_terminate, m_windows, MF_DEBUG, MF_INFO, remove_from_lookup(), and MayaFlux::Journal::WindowingSubsystem.
Referenced by destroy_closed_windows(), and destroy_window_by_title().