MayaFlux: MayaFlux::Creator::read_input
read_input()
std::shared_ptr< Nodes::Input::InputNode > MayaFlux::Creator::read_input (const Nodes::Input::InputConfig & config, const Core::InputBinding & binding)
Create and register generic input node.
Parameters
config Generic input configuration.
binding Generic input binding.
Returns
Shared pointer to InputNode (already registered).
Definition at line 172 of file Creator.cpp.
{
    switch (binding.backend) {
    case Core::InputType::HID:
        return read_hid(static_cast<const Nodes::Input::HIDConfig&>(config), binding);
    case Core::InputType::MIDI:
        return read_midi(static_cast<const Nodes::Input::MIDIConfig&>(config), binding);
    case Core::InputType::OSC:
        return read_osc(static_cast<const Nodes::Input::OSCConfig&>(config), binding);
    default:
        MF_ERROR(Journal::Component::API, Journal::Context::Init,
            "Input type {} not yet implemented",
            static_cast<int>(binding.backend));
        return nullptr;
    }
}
References MayaFlux::Journal::API, MayaFlux::Core::InputBinding::backend, MayaFlux::Core::HID, MayaFlux::Journal::Init, MF_ERROR, MayaFlux::Core::MIDI, MayaFlux::Core::OSC, read_hid(), read_midi(), and read_osc().