MayaFlux: MayaFlux::Kriya::SamplingPipeline::rebuild_for
rebuild_for()
void MayaFlux::Kriya::SamplingPipeline::rebuild_for (uint64_t milliseconds)
Stop and restart pipeline execution for a bounded duration.
Stops any running pipeline execution, resets the cycle counter, and restarts for the given duration. Hard-cuts all active voices at the point of restart. Document as a destructive operation.
Parameters
milliseconds Duration in milliseconds.
Definition at line 96 of file SamplingPipeline.cpp.
{
    if (!m_built) {
        MF_WARN(Journal::Component::Kriya, Journal::Context::Configuration,
            "SamplingPipeline::rebuild_for called before build. Use build_for instead to avoid redundant setup.");
        return;
    }
    m_pipeline->stop_continuous();
    const double seconds = static_cast<double>(milliseconds) / 1000.0;
    const uint64_t cycles = Vruta::seconds_to_blocks(
        seconds, m_mgr.get_sample_rate(), m_mgr.get_buffer_size(Buffers::ProcessingToken::AUDIO_BACKEND));
    m_pipeline->on_complete([this] {
        std::ranges::fill(m_buffer->get_data(), 0.0);
    });
    m_pipeline->execute_buffer_rate(cycles);
}
References MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Journal::Configuration, MayaFlux::Buffers::BufferManager::get_buffer_size(), MayaFlux::Buffers::BufferManager::get_sample_rate(), MayaFlux::Journal::Kriya, m_buffer, m_built, m_mgr, m_pipeline, MF_WARN, and MayaFlux::Vruta::seconds_to_blocks().