MayaFlux: MayaFlux::Journal::Archivist::scribe
scribe()
void MayaFlux::Journal::Archivist::scribe (Severity severity, Component component, Context context, std::string_view message, std::source_location location = std::source_location::current())
Log a message with the specified severity, component, and context.
This method captures the source location automatically.
Parameters
severity The severity level of the log message.
component The component generating the log message.
context The execution context of the log message.
message The log message content.
location The source location (file, line, function) of the log call.
Definition at line 371 of file Archivist.cpp.
{
    JournalEntry entry(severity, component, context, message, location);
    m_impl->scribe(entry);
}
References m_impl.
Referenced by MayaFlux::Journal::error(), MayaFlux::Journal::error(), MayaFlux::Journal::error_rethrow(), MayaFlux::Journal::fatal(), MayaFlux::Journal::fatal(), MayaFlux::Journal::scribe(), and MayaFlux::Journal::scribe().