MayaFlux: MayaFlux::Nodes::Network::ParticleNetwork::generate_initial_vertices
generate_initial_vertices()
std::vector< PointVertex > MayaFlux::Nodes::Network::ParticleNetwork::generate_initial_vertices () private
Definition at line 256 of file ParticleNetwork.cpp.
{
    std::vector<PointVertex> vertices;
    vertices.reserve(m_num_points);
    for (size_t i = 0; i < m_num_points; ++i) {
        vertices.push_back(generate_single_vertex(m_init_mode, i, m_num_points));
    }
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "Generated {} initial vertices with mode {}",
        m_num_points, static_cast<int>(m_init_mode));
    return vertices;
}
References generate_single_vertex(), m_init_mode, m_num_points, MF_DEBUG, MayaFlux::Journal::NodeProcessing, and MayaFlux::Journal::Nodes.
Referenced by initialize(), reset(), and set_operator().