MayaFlux: MayaFlux::Buffers::DataWriteProcessor::upload_texture
upload_texture()
void MayaFlux::Buffers::DataWriteProcessor::upload_texture (const std::shared_ptr< VKBuffer > & vk, Kakshya::DataVariant & slot) private
Definition at line 241 of file DataWriteProcessor.cpp.
{
    auto access = Kakshya::as_texture_access(slot);
    if (!access) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "DataWriteProcessor: as_texture_access failed for modality {}",
            Kakshya::modality_to_string(m_modality));
        return;
    }
    m_last_texture_format = access->format;
    if (m_tex_width == 0 || m_tex_height == 0) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "DataWriteProcessor: setup_pixel_target() not called before texture upload");
        return;
    }
    auto& loom = Portal::Graphics::get_texture_manager();
    if (!m_gpu_texture) {
        m_gpu_texture = loom.create_2d(m_tex_width, m_tex_height, m_tex_format, nullptr, 1);
        if (!m_gpu_texture) {
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "DataWriteProcessor: failed to create GPU texture {}x{}",
                m_tex_width, m_tex_height);
            return;
        }
        m_image_staging = create_image_staging_buffer(m_gpu_texture->get_size_bytes());
        if (auto rp = vk->get_render_processor()) {
            rp->bind_texture(m_tex_binding, m_gpu_texture);
        }
    }
    loom.upload_data(m_gpu_texture, access->data_ptr, access->byte_count, m_image_staging);
}
References MayaFlux::Kakshya::as_texture_access(), MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Portal::Graphics::get_texture_manager(), m_gpu_texture, m_image_staging, m_last_texture_format, m_modality, m_tex_binding, m_tex_format, m_tex_height, m_tex_width, MF_RT_ERROR, and MayaFlux::Kakshya::modality_to_string().
Referenced by processing_function(), and upload_primary().