MayaFlux: MayaFlux::Vruta::TaskScheduler::get_rate
get_rate()
unsigned int MayaFlux::Vruta::TaskScheduler::get_rate (ProcessingToken token = ProcessingToken::SAMPLE_ACCURATE) const
Get processing rate for a domain.
Parameters
token Processing domain
Returns
Processing rate (sample rate, frame rate, etc.)
Definition at line 167 of file Scheduler.cpp.
{
    auto clock_it = m_token_clocks.find(token);
    if (clock_it != m_token_clocks.end()) {
        return clock_it->second->rate();
    }
    return get_default_rate(token);
}
References get_default_rate(), m_token_clocks, and token.
Referenced by MayaFlux::Kriya::line(), seconds_to_samples(), and seconds_to_units().