MayaFlux: MayaFlux::Vruta::TaskScheduler::cancel_task
cancel_task() [1/2]
bool MayaFlux::Vruta::TaskScheduler::cancel_task (const std::shared_ptr< Routine > & routine)
Cancels and removes a task from the scheduler.
Parameters
routine Shared pointer to the task to cancel
Returns
True if the task was found and cancelled, false otherwise
This method removes a task from the scheduler, preventing it from executing further. It's used to stop tasks that are no longer needed or to clean up before shutting down the engine.
Definition at line 101 of file Scheduler.cpp.
{
    if (!routine)
        return false;
    if (routine && routine->get_processing_token() == ProcessingToken::CONDITIONAL) {
        auto it = std::ranges::find_if(m_conditional_tasks,
            [&routine](const TaskEntry& e) { return e.routine == routine; });
        const std::string name = (it != m_conditional_tasks.end()) ? it->name : "";
        return cancel_task(name);
    }
    auto it = find_task_by_routine(routine);
    const std::string name = (it != m_tasks.end()) ? it->name : "";
    for (auto& op : m_pending_ops) {
        bool expected = false;
        if (op.active.compare_exchange_strong(expected, true,
                std::memory_order_acquire, std::memory_order_relaxed)) {
            op.entry = { routine, name };
            op.is_addition = false;
            m_pending_count.fetch_add(1, std::memory_order_relaxed);
            return true;
        }
    }
    MF_ERROR(Journal::Component::Vruta, Journal::Context::CoroutineScheduling,
        "Pending task queue full, could not cancel task '{}'", name);
    return false;
}
References cancel_task(), MayaFlux::Vruta::CONDITIONAL, MayaFlux::Journal::CoroutineScheduling, find_task_by_routine(), m_conditional_tasks, m_pending_count, m_pending_ops, m_tasks, MF_ERROR, MayaFlux::Vruta::TaskEntry::routine, and MayaFlux::Journal::Vruta.
Referenced by MayaFlux::Kriya::EventChain::cancel(), MayaFlux::Kriya::Timer::cancel(), MayaFlux::Portal::Forma::Bridge::cancel_inbound(), MayaFlux::Portal::Forma::Bridge::cancel_outbound(), cancel_task(), MayaFlux::Nexus::Fabric::remove(), and MayaFlux::Nexus::Fabric::~Fabric().