MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames
get_channel_frames() [2/2]
std::span< const double > MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames (uint32_t channel, uint64_t start_frame, uint64_t num_frames) const
Get the fixed capacity of the circular buffer if enabled.
Returns
Capacity in frames if circular mode is active, 0 otherwise
Definition at line 231 of file DynamicSoundStream.cpp.
{
    if (channel >= get_num_channels()) {
        return {};
    }
    if (m_structure.organization == OrganizationStrategy::INTERLEAVED) {
        std::cerr << "Direct span access not supported for interleaved data. Use get_frames() or Kakshya::extract_channel_data() instead." << '\n';
        return {};
    }
    std::shared_lock lock(m_data_mutex);
    if (channel >= m_data.size()) {
        return {};
    }
    const auto& channel_data = std::get<std::vector<double>>(m_data[channel]);
    if (start_frame >= channel_data.size()) {
        return {};
    }
    uint64_t available_frames = channel_data.size() - start_frame;
    uint64_t actual_frames = std::min(num_frames, available_frames);
    return { channel_data.data() + start_frame, actual_frames };
}
References MayaFlux::Kakshya::SoundStreamContainer::channel_data(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), MayaFlux::Kakshya::INTERLEAVED, MayaFlux::Kakshya::SoundStreamContainer::lock(), MayaFlux::Kakshya::SoundStreamContainer::m_data, MayaFlux::Kakshya::SoundStreamContainer::m_data_mutex, MayaFlux::Kakshya::SoundStreamContainer::m_structure, and MayaFlux::Kakshya::ContainerDataStructure::organization.