MayaFlux: MayaFlux::IO::SoundFileReader::build_regions
build_regions()
void MayaFlux::IO::SoundFileReader::build_regions (const std::shared_ptr< FFmpegDemuxContext > & demux, const std::shared_ptr< AudioStreamContext > & audio) const private
Build and cache FileRegion list from both contexts.
Definition at line 245 of file SoundFileReader.cpp.
{
    auto chapters = demux->extract_chapter_regions();
    auto cues = audio->extract_cue_regions(*demux);
    std::vector<FileRegion> all;
    all.reserve(chapters.size() + cues.size());
    all.insert(all.end(), chapters.begin(), chapters.end());
    all.insert(all.end(), cues.begin(), cues.end());
    std::lock_guard<std::mutex> ml(m_metadata_mutex);
    m_cached_regions = std::move(all);
}
References m_cached_regions, and m_metadata_mutex.
Referenced by get_regions(), open(), and open_from_demux().