MayaFlux: MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode
TopologyGeneratorNode() [2/2]
MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode (CustomConnectionFunction custom_func, bool auto_connect = true, size_t max_points = 256)
Create with custom connection function.
Parameters
custom_func User-provided topology generation
auto_connect Auto-regenerate flag
max_points Maximum capacity
Definition at line 39 of file TopologyGeneratorNode.cpp.
    : GeometryWriterNode(static_cast<uint32_t>(max_points * max_points))
    , m_mode(Kinesis::ProximityMode::CUSTOM)
    , m_custom_func(std::move(custom_func))
    , m_points(max_points)
    , m_auto_connect(auto_connect)
{
    const auto& stride = sizeof(LineVertex);
    set_vertex_stride(stride);
    auto layout = Kakshya::VertexLayout::for_lines(stride);
    layout.vertex_count = 0;
    set_vertex_layout(layout);
    m_vertices.reserve(max_points * max_points);
    m_connections.reserve(max_points * max_points);
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "Created TopologyGeneratorNode with custom function");
}
References MayaFlux::Kakshya::VertexLayout::for_lines(), m_connections, m_vertices, MF_DEBUG, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride().