MayaFlux: MayaFlux::IO::VideoStreamContext::open_device
open_device()
bool MayaFlux::IO::VideoStreamContext::open_device (const FFmpegDemuxContext & demux, uint32_t target_width = 0, uint32_t target_height = 0, int target_format = -1)
Open codec only, without initialising the SwsContext scaler.
Intended for live capture devices (dshow, v4l2, avfoundation) where pix_fmt is AV_PIX_FMT_NONE until the first decoded frame arrives and sws_getContext therefore cannot be called at open time.
After this call is_codec_valid() returns true; is_valid() returns false until rebuild_scaler_from_frame() has been called successfully.
Parameters
demux Open demux context (must outlive this object).
target_width Desired output width (0 = use frame width).
target_height Desired output height (0 = use frame height).
target_format Desired AVPixelFormat (negative = AV_PIX_FMT_RGBA).
Returns
True if codec was opened successfully.
Definition at line 208 of file VideoStreamContext.cpp.
{
    close();
    FFmpegDemuxContext::init_ffmpeg();
    if (!demux.is_open()) {
        m_last_error = "Demux context is not open";
        return false;
    }
    const AVCodec* codec = nullptr;
    stream_index = demux.find_best_stream(AVMEDIA_TYPE_VIDEO,
        reinterpret_cast<const void**>(&codec));
    if (stream_index < 0 || !codec) {
        m_last_error = "No video stream found";
        return false;
    }
    codec_context = avcodec_alloc_context3(codec);
    if (!codec_context) {
        m_last_error = "avcodec_alloc_context3 failed";
        return false;
    }
    AVStream* stream = demux.get_stream(stream_index);
    if (avcodec_parameters_to_context(codec_context, stream->codecpar) < 0) {
        m_last_error = "avcodec_parameters_to_context failed";
        close();
        return false;
    }
    if (avcodec_open2(codec_context, codec, nullptr) < 0) {
        m_last_error = "avcodec_open2 failed";
        close();
        return false;
    }
    target_width = tw;
    target_height = th;
    target_format = tf;
    src_pixel_format = codec_context->pix_fmt;
    width = static_cast<uint32_t>(codec_context->width);
    height = static_cast<uint32_t>(codec_context->height);
    if (width == 0 || height == 0) {
        AVStream* s = demux.get_stream(stream_index);
        width = static_cast<uint32_t>(s->codecpar->width);
        height = static_cast<uint32_t>(s->codecpar->height);
    }
    if (width == 0 || height == 0) {
        width = target_width;
        height = target_height;
    }
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    if (target_width > 0 && target_height > 0
        && width == target_height && height == target_width) {
        std::swap(width, height);
    }
#endif
    out_width = target_width > 0 ? target_width : width;
    out_height = target_height > 0 ? target_height : height;
    if (stream->avg_frame_rate.den > 0 && stream->avg_frame_rate.num > 0)
        frame_rate = av_q2d(stream->avg_frame_rate);
    else if (stream->r_frame_rate.den > 0 && stream->r_frame_rate.num > 0)
        frame_rate = av_q2d(stream->r_frame_rate);
    auto fmt = av_get_pix_fmt_name(static_cast<AVPixelFormat>(src_pixel_format));
    MF_INFO(Journal::Component::IO, Journal::Context::FileIO,
        "[VideoStreamContext] open_device: stream #{} | {}x{} | pix_fmt={}",
        stream_index, width, height, fmt ? fmt : "none");
    return true;
}
References close(), codec_context, MayaFlux::Journal::FileIO, MayaFlux::IO::FFmpegDemuxContext::find_best_stream(), frame_rate, MayaFlux::IO::FFmpegDemuxContext::get_stream(), height, MayaFlux::IO::FFmpegDemuxContext::init_ffmpeg(), MayaFlux::Journal::IO, MayaFlux::IO::FFmpegDemuxContext::is_open(), m_last_error, MF_INFO, out_height, out_width, src_pixel_format, stream_index, target_format, target_height, target_width, and width.