MayaFlux: MayaFlux::Buffers::MeshProcessor::upload_indices
upload_indices()
void MayaFlux::Buffers::MeshProcessor::upload_indices (const std::shared_ptr< MeshBuffer > & buf) private
Definition at line 159 of file MeshProcessor.cpp.
{
    const auto* ib = std::get_if<std::vector<uint32_t>>(
        &buf->m_mesh_data.index_variant);
    if (!ib || ib->empty() || !m_gpu_index_buffer) {
        return;
    }
    upload_resizing(
        ib->data(),
        ib->size() * sizeof(uint32_t),
        m_gpu_index_buffer,
        m_index_staging);
}
References m_gpu_index_buffer, m_index_staging, and MayaFlux::Buffers::upload_resizing().
Referenced by on_attach(), and processing_function().