MayaFlux: MayaFlux::Nodes::CompositeOpNode::process_sample
process_sample()
template<size_t N = 0> double MayaFlux::Nodes::CompositeOpNode< N >::process_sample (double input = 0.) inline override virtual
Processes a single data sample.
Parameters
input The input sample value
Returns
The processed output sample value
This is the core processing method that all nodes must implement. It takes a single input value, applies the node's transformation algorithm, and returns the resulting output value.
For generator nodes that don't require input (like oscillators or stochastic generators), the input parameter may be ignored. Note: This method does NOT mark the node as processed. That responsibility belongs to the caller, typically a chained parent node or the root node.
Implements MayaFlux::Nodes::Node.
Definition at line 419 of file NodeCombine.hpp.
    {
        if (!is_initialized())
            initialize();
        for (auto& node : m_inputs) {
            atomic_inc_modulator_count(node->m_modulator_count, 1);
        }
        for (size_t i = 0; i < m_inputs.size(); ++i) {
            uint32_t state = m_inputs[i]->m_state.load();
            if (state & NodeState::PROCESSED) {
                m_input_values[i] = input + m_inputs[i]->get_last_output();
            } else {
                m_input_values[i] = m_inputs[i]->process_sample(input);
                atomic_add_flag(m_inputs[i]->m_state, NodeState::PROCESSED);
            }
        }
        m_last_output = m_func(std::span<const double>(m_input_values));
        if (!m_state_saved || (m_state_saved && m_fire_events_during_snapshot))
            notify_tick(m_last_output);
        for (auto& node : m_inputs) {
            atomic_dec_modulator_count(node->m_modulator_count, 1);
        }
        for (auto& node : m_inputs) {
            try_reset_processed_state(node);
        }
        return m_last_output;
    }
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), initialize(), MayaFlux::is_initialized(), and MayaFlux::Nodes::try_reset_processed_state().