MayaFlux: MayaFlux::Vruta::GraphicsRoutine::is_active
is_active()
bool MayaFlux::Vruta::GraphicsRoutine::is_active () const override virtual
Checks if the coroutine is still active.
Returns
True if the coroutine is active, false if it's completed or invalid
An active coroutine has not yet completed its execution and can be resumed. Inactive coroutines have either completed or were never properly initialized.
Implements MayaFlux::Vruta::Routine.
Definition at line 269 of file Routine.cpp.
{
    return m_handle && !m_handle.done();
}
References m_handle.
Referenced by initialize_state(), restart(), and try_resume_with_context().