MayaFlux: MayaFlux::Kriya::NetworkAwaiter::await_suspend
await_suspend()
void MayaFlux::Kriya::NetworkAwaiter::await_suspend (std::coroutine_handle<> handle)
Suspend the coroutine and register with the source.
Parameters
handle Type-erased coroutine handle
Definition at line 22 of file NetworkAwaiter.cpp.
{
    m_handle = handle;
    m_is_suspended = true;
    m_source.register_waiter(this);
    if (auto msg = m_source.pop_message()) {
        m_source.unregister_waiter(this);
        m_result = std::move(*msg);
        m_is_suspended = false;
        m_handle.resume();
    }
}
References m_handle, m_is_suspended, m_result, m_source, MayaFlux::Vruta::NetworkSource::pop_message(), MayaFlux::Vruta::NetworkSource::register_waiter(), and MayaFlux::Vruta::NetworkSource::unregister_waiter().