MayaFlux: MayaFlux::Nodes::Generator::Phasor::notify_tick
notify_tick()
void MayaFlux::Nodes::Generator::Phasor::notify_tick (double value) override protected virtual
Notifies all registered callbacks about a new sample.
Parameters
value The newly generated sample
This method is called internally whenever a new sample is generated, creating the appropriate context and invoking all registered callbacks that should receive notification about this sample.
Implements MayaFlux::Nodes::Node.
Definition at line 201 of file Phasor.cpp.
{
    update_context(value);
    auto& ctx = get_last_context();
    for (auto& callback : m_callbacks) {
        callback(ctx);
    }
    if (m_phase_wrapped) {
        for (auto& callback : m_phase_wrap_callbacks) {
            callback(ctx);
        }
    }
    for (auto& [callback, condition] : m_conditional_callbacks) {
        if (condition(ctx)) {
            callback(ctx);
        }
    }
    for (auto& [callback, threshold] : m_threshold_callbacks) {
        if (value >= threshold && !m_threshold_crossed) {
            callback(ctx);
            m_threshold_crossed = true;
        } else if (value < threshold) {
            m_threshold_crossed = false;
        }
    }
}
References MayaFlux::Nodes::Generator::Generator::get_last_context(), MayaFlux::Nodes::Node::m_callbacks, MayaFlux::Nodes::Node::m_conditional_callbacks, m_phase_wrap_callbacks, m_phase_wrapped, m_threshold_callbacks, m_threshold_crossed, and MayaFlux::Nodes::Generator::Generator::update_context().
Referenced by process_sample().