MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::lock
lock()
void MayaFlux::Kakshya::SoundStreamContainer::lock () inline override virtual
Acquire a lock for thread-safe access.
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 67 of file SoundStreamContainer.hpp.
{ m_data_mutex.lock(); }
Referenced by add_region_group(), all_dimensions_consumed(), clear(), clear_all_consumption(), get_all_region_groups(), MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames(), MayaFlux::Kakshya::DynamicSoundStream::get_channel_frames(), get_default_processor(), get_region_group(), has_active_readers(), has_data(), notify_state_change(), register_dimension_reader(), remove_region_group(), MayaFlux::Kakshya::DynamicSoundStream::set_all_data(), set_memory_layout(), MayaFlux::Kakshya::SoundFileContainer::set_raw_data(), set_region_data(), MayaFlux::Kakshya::SoundFileContainer::setup(), unregister_dimension_reader(), update_processing_state(), and MayaFlux::Kakshya::DynamicSoundStream::write_frames().