MayaFlux: MayaFlux::Buffers::VKBuffer::get_size_bytes
get_size_bytes()
vk::DeviceSize MayaFlux::Buffers::VKBuffer::get_size_bytes () const inline
Definition at line 235 of file VKBuffer.hpp.
{ return m_size_bytes; }
Referenced by MayaFlux::Buffers::GeometryBuffer::GeometryBuffer(), MayaFlux::Buffers::NetworkGeometryBuffer::NetworkGeometryBuffer(), MayaFlux::Buffers::NodeTextureBuffer::NodeTextureBuffer(), and MayaFlux::Buffers::NodeTextureBuffer::setup_processors().