MayaFlux: MayaFlux::Buffers::DescriptorBindingsProcessor::update_descriptor_data
update_descriptor_data()
void MayaFlux::Buffers::DescriptorBindingsProcessor::update_descriptor_data (DescriptorBinding & binding) private
Update descriptor from binding source (node, audio buffer, etc.)
Definition at line 494 of file DescriptorBindingsProcessor.cpp.
{
    switch (binding.source_type) {
    case SourceType::NODE:
        update_from_node(binding);
        break;
    case SourceType::AUDIO_BUFFER:
    case SourceType::HOST_VK_BUFFER:
        update_from_buffer(binding);
        break;
    case SourceType::NETWORK_AUDIO:
    case SourceType::NETWORK_GPU:
        update_from_network(binding);
        break;
    }
}
References AUDIO_BUFFER, HOST_VK_BUFFER, NETWORK_AUDIO, NETWORK_GPU, NODE, MayaFlux::Buffers::DescriptorBindingsProcessor::DescriptorBinding::source_type, update_from_buffer(), update_from_network(), and update_from_node().
Referenced by execute_shader().