MayaFlux: MayaFlux::IO::ModelReader::extract_meshes
extract_meshes()
std::vector< Kakshya::MeshData > MayaFlux::IO::ModelReader::extract_meshes () const
Load all meshes after open() has already been called.
Extracts from the currently imported scene. Returns empty if no scene is loaded. Does not call close().
Returns
One MeshData per aiMesh in the scene.
Definition at line 73 of file ModelReader.cpp.
{
    if (!m_impl->scene) {
        set_error("No scene loaded");
        return {};
    }
    const aiScene* s = m_impl->scene;
    std::vector<Kakshya::MeshData> result;
    result.reserve(s->mNumMeshes);
    for (unsigned int i = 0; i < s->mNumMeshes; ++i) {
        const aiMesh* mesh = s->mMeshes[i];
        std::string mesh_name(mesh->mName.C_Str());
        std::string mat_name;
        if (s->mNumMaterials > 0 && mesh->mMaterialIndex < s->mNumMaterials) {
            aiString ai_mat;
            s->mMaterials[mesh->mMaterialIndex]->Get(AI_MATKEY_NAME, ai_mat);
            mat_name = ai_mat.C_Str();
        }
        auto mesh_data = extract_single_mesh(mesh, s, mesh_name, mat_name);
        if (mesh_data.is_valid()) {
            result.push_back(std::move(mesh_data));
        } else {
            MF_WARN(Journal::Component::IO, Journal::Context::FileIO,
                "ModelReader: mesh '{}' produced invalid MeshData, skipped",
                mesh_name.empty() ? "<unnamed>" : mesh_name);
        }
    }
    MF_INFO(Journal::Component::IO, Journal::Context::FileIO,
        "ModelReader: extracted {}/{} meshes",
        result.size(), s->mNumMeshes);
    return result;
}
References extract_single_mesh(), MayaFlux::Journal::FileIO, MayaFlux::Journal::IO, m_impl, MF_INFO, MF_WARN, and set_error().
Referenced by create_mesh_buffers(), and load().