MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::instance
instance()
static TextureLoom & MayaFlux::Portal::Graphics::TextureLoom::instance () inline static
Definition at line 119 of file TextureLoom.hpp.
    {
        static TextureLoom manager;
        return manager;
    }
Referenced by MayaFlux::Portal::Graphics::get_texture_manager(), MayaFlux::Portal::Graphics::initialize(), and MayaFlux::Portal::Graphics::shutdown().