MayaFlux: MayaFlux::Platform::SystemConfig::get_clang_resource_dir
get_clang_resource_dir()
const std::string & MayaFlux::Platform::SystemConfig::get_clang_resource_dir () static
Definition at line 31 of file HostEnvironment.cpp.
{
    static std::string cached_resource_dir;
    if (cached_resource_dir.empty()) {
        const char* cmd = "clang -print-resource-dir";
        auto result = exec_command(cmd);
        trim_output(result);
        if (!result.empty()
            && (result.find("error:") == std::string::npos)
            && (result.find("clang") != std::string::npos
                || result.find("lib") != std::string::npos
                || fs::exists(result))) {
            {
                cached_resource_dir = std::move(result);
            }
        }
    }
    return cached_resource_dir;
}
References exec_command(), and trim_output().
Referenced by Lila::ClangInterpreter::initialize().