MayaFlux: MayaFlux::IO::VideoEncodeContext::drain_packets
drain_packets()
bool MayaFlux::IO::VideoEncodeContext::drain_packets (FFmpegMuxContext & mux) private
Definition at line 343 of file VideoEncodeContext.cpp.
{
    AVPacket* pkt = av_packet_alloc();
    if (!pkt) {
        m_last_error = "av_packet_alloc failed";
        return false;
    }
    bool ok = true;
    while (true) {
        int ret = avcodec_receive_packet(codec_context, pkt);
        if (ret == AVERROR(EAGAIN) || ret == AVERROR_EOF)
            break;
        if (ret < 0) {
            char errbuf[AV_ERROR_MAX_STRING_SIZE];
            av_strerror(ret, errbuf, sizeof(errbuf));
            m_last_error = std::string("avcodec_receive_packet failed: ") + errbuf;
            ok = false;
            break;
        }
        pkt->stream_index = m_stream_index;
        av_packet_rescale_ts(pkt,
            codec_context->time_base,
            m_stream->time_base);
        if (!mux.write_packet(pkt)) {
            m_last_error = mux.last_error();
            ok = false;
            break;
        }
        av_packet_unref(pkt);
    }
    av_packet_free(&pkt);
    return ok;
}
References codec_context, MayaFlux::IO::FFmpegMuxContext::last_error(), m_last_error, m_stream, m_stream_index, and MayaFlux::IO::FFmpegMuxContext::write_packet().
Referenced by drain(), and encode_frame().