MayaFlux: MayaFlux::Core::BackendPipelineManager::setup_backend_service
setup_backend_service()
void MayaFlux::Core::BackendPipelineManager::setup_backend_service (const std::shared_ptr< Registry::Service::ComputeService > & compute_service)
Definition at line 19 of file BackendPipelineManager.cpp.
{
    compute_service->create_shader_module = [this](const std::string& path, uint32_t stage) -> std::shared_ptr<void> {
        return std::static_pointer_cast<void>(this->create_shader_module(path, stage));
    };
    compute_service->create_descriptor_manager = [this](uint32_t pool_size) -> std::shared_ptr<void> {
        return std::static_pointer_cast<void>(this->create_descriptor_manager(pool_size));
    };
    compute_service->create_descriptor_layout = [this](const std::shared_ptr<void>& mgr,
                                                    const std::vector<std::pair<uint32_t, uint32_t>>& bindings) -> void* {
        auto manager = std::static_pointer_cast<VKDescriptorManager>(mgr);
        vk::DescriptorSetLayout layout = this->create_descriptor_layout(manager, bindings);
        return reinterpret_cast<void*>(static_cast<VkDescriptorSetLayout>(layout));
    };
    compute_service->create_compute_pipeline = [this](const std::shared_ptr<void>& shdr,
                                                   const std::vector<void*>& layouts,
                                                   uint32_t push_size) -> std::shared_ptr<void> {
        auto shader = std::static_pointer_cast<VKShaderModule>(shdr);
        std::vector<vk::DescriptorSetLayout> vk_layouts;
        vk_layouts.reserve(layouts.size());
        for (auto* ptr : layouts) {
            vk_layouts.emplace_back(reinterpret_cast<VkDescriptorSetLayout>(ptr));
        }
        return std::static_pointer_cast<void>(this->create_compute_pipeline(shader, vk_layouts, push_size));
    };
    compute_service->cleanup_resource = [this](const std::shared_ptr<void>& res) {
        this->cleanup_compute_resource(res.get());
    };
}
References cleanup_compute_resource(), create_compute_pipeline(), create_descriptor_layout(), create_descriptor_manager(), and create_shader_module().