MayaFlux: MayaFlux::Portal::Graphics::TextureLoom::upload_data
upload_data() [1/2]
void MayaFlux::Portal::Graphics::TextureLoom::upload_data (const std::shared_ptr< Core::VKImage > & image, const void * data, size_t size)
Upload pixel data to an existing texture.
Parameters
image Target image
data Pixel data pointer
size Data size in bytes
Handles staging buffer, layout transitions, and cleanup. Blocks until upload completes.
Definition at line 369 of file TextureLoom.cpp.
{
    if (!is_initialized() || !image || !data) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ImageProcessing,
            "Invalid parameters for upload_data");
        return;
    }
    m_resource_manager->upload_image_data(image, data, size);
}
References image, MayaFlux::Journal::ImageProcessing, is_initialized(), m_resource_manager, MF_ERROR, MayaFlux::Journal::Portal, size, and MayaFlux::Core::BackendResourceManager::upload_image_data().
Referenced by create_2d(), create_3d(), and create_cubemap().