MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::slot_for
slot_for()
uint32_t MayaFlux::Kakshya::VideoStreamContainer::slot_for (uint64_t frame_index) const inline protected
Definition at line 380 of file VideoStreamContainer.hpp.
    {
        return static_cast<uint32_t>(frame_index % m_ring_capacity);
    }
Referenced by commit_frame(), get_frame_pixels(), is_frame_available(), and mutable_slot_ptr().