MayaFlux: MayaFlux::Kriya::BufferOperation::get_type
get_type()
OpType MayaFlux::Kriya::BufferOperation::get_type () const inline
Getters for internal state (read-only)
Definition at line 359 of file BufferOperation.hpp.
{ return m_type; }
Referenced by is_capture_phase_operation(), is_process_phase_operation(), and MayaFlux::Kriya::BufferPipeline::process_operation().