MayaFlux: MayaFlux::Nodes::ModalNetwork::initialize_modes
initialize_modes()
void MayaFlux::Nodes::ModalNetwork::initialize_modes (const std::vector< double > & ratios, double base_decay) private
Initialize modes with given frequency ratios.
Definition at line 92 of file ModalNetwork.cpp.
{
    m_modes.clear();
    m_modes.reserve(ratios.size());
    for (size_t i = 0; i < ratios.size(); ++i) {
        ModalNode mode;
        mode.index = i;
        mode.frequency_ratio = ratios[i];
        mode.base_frequency = m_fundamental * ratios[i];
        mode.current_frequency = mode.base_frequency;
        mode.decay_time = base_decay / ratios[i];
        // Initial amplitude decreases with mode number (1/n falloff)
        mode.initial_amplitude = 1.0 / (i + 1);
        mode.amplitude = 0.0;
        mode.oscillator = std::make_shared<Generator::Sine>(mode.current_frequency);
        mode.decay_coefficient = std::exp(-1.0 / (base_decay * Config::get_sample_rate()));
        m_modes.push_back(std::move(mode));
    }
}
References MayaFlux::Nodes::ModalNetwork::ModalNode::amplitude, MayaFlux::Nodes::ModalNetwork::ModalNode::base_frequency, MayaFlux::Nodes::ModalNetwork::ModalNode::current_frequency, MayaFlux::Nodes::ModalNetwork::ModalNode::decay_coefficient, MayaFlux::Nodes::ModalNetwork::ModalNode::decay_time, MayaFlux::Nodes::ModalNetwork::ModalNode::frequency_ratio, MayaFlux::Config::get_sample_rate(), MayaFlux::Nodes::ModalNetwork::ModalNode::index, MayaFlux::Nodes::ModalNetwork::ModalNode::initial_amplitude, m_fundamental, m_modes, and MayaFlux::Nodes::ModalNetwork::ModalNode::oscillator.
Referenced by ModalNetwork(), and ModalNetwork().