MayaFlux: MayaFlux::Journal::Archivist::Impl::scribe
scribe()
void MayaFlux::Journal::Archivist::Impl::scribe (const JournalEntry & entry) inline
Definition at line 76 of file Archivist.cpp.
    {
        if (!should_log(entry.severity, entry.component, entry.context)) {
            return;
        }
        std::lock_guard lock(m_mutex);
        if (m_sinks.empty()) {
            write_to_console(entry);
        } else {
            write_to_sinks(entry);
        }
    }
References MayaFlux::Journal::JournalEntry::component, MayaFlux::Journal::JournalEntry::context, m_mutex, m_sinks, MayaFlux::Journal::JournalEntry::severity, should_log(), write_to_console(), and write_to_sinks().