MayaFlux: MayaFlux::Buffers::ComputeProcessor::initialize_descriptors
initialize_descriptors()
void MayaFlux::Buffers::ComputeProcessor::initialize_descriptors (const std::shared_ptr< VKBuffer > & buffer) override protected virtual
Implements MayaFlux::Buffers::ShaderProcessor.
Definition at line 87 of file ComputeProcessor.cpp.
{
    if (m_pipeline_id == Portal::Graphics::INVALID_COMPUTE_PIPELINE) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Cannot allocate descriptor sets without pipeline");
        return;
    }
    on_before_descriptors_create();
    auto& compute_press = Portal::Graphics::get_compute_press();
    m_descriptor_set_ids = compute_press.allocate_pipeline_descriptors(m_pipeline_id);
    if (m_descriptor_set_ids.empty()) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "Failed to allocate descriptor sets");
        return;
    }
    update_descriptors(buffer);
    on_descriptors_created();
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Descriptor sets initialized: {} sets", m_descriptor_set_ids.size());
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::INVALID_COMPUTE_PIPELINE, MayaFlux::Buffers::ShaderProcessor::m_descriptor_set_ids, m_pipeline_id, MF_DEBUG, MF_ERROR, MayaFlux::Buffers::ShaderProcessor::on_before_descriptors_create(), MayaFlux::Buffers::ShaderProcessor::on_descriptors_created(), and MayaFlux::Buffers::ShaderProcessor::update_descriptors().