MayaFlux: MayaFlux::Buffers::BufferProcessingChain::add_processor_direct
add_processor_direct()
bool MayaFlux::Buffers::BufferProcessingChain::add_processor_direct (const std::shared_ptr< BufferProcessor > & processor, const std::shared_ptr< Buffer > & buffer, std::string * rejection_reason = nullptr) protected
Definition at line 18 of file BufferProcessingChain.cpp.
{
    auto processor_token = processor->get_processing_token();
    switch (m_enforcement_strategy) {
    case TokenEnforcementStrategy::STRICT:
        if (processor_token != m_token_filter_mask) {
            if (rejection_reason) {
                *rejection_reason = "Processor token (" + std::to_string(static_cast<uint32_t>(processor_token)) + ") does not exactly match chain's preferred token (" + std::to_string(static_cast<uint32_t>(m_token_filter_mask)) + ") in STRICT mode";
            }
            return false;
        }
        break;
    case TokenEnforcementStrategy::FILTERED:
        if (!are_tokens_compatible(m_token_filter_mask, processor_token)) {
            if (rejection_reason) {
                *rejection_reason = "Processor token (" + std::to_string(static_cast<uint32_t>(processor_token)) + ") is not compatible with chain's preferred token (" + std::to_string(static_cast<uint32_t>(m_token_filter_mask)) + ") in FILTERED mode";
            }
            return false;
        }
        break;
    case TokenEnforcementStrategy::OVERRIDE_SKIP:
        if (!are_tokens_compatible(m_token_filter_mask, processor_token)) {
            m_conditional_processors[buffer].insert(processor);
        }
        break;
    case TokenEnforcementStrategy::OVERRIDE_REJECT:
        if (!are_tokens_compatible(m_token_filter_mask, processor_token)) {
            m_pending_removal[buffer].insert(processor);
        }
        break;
    case TokenEnforcementStrategy::IGNORE:
        break;
    }
    auto& processors = m_buffer_processors[buffer];
    auto it = std::ranges::find(processors, processor);
    if (it != processors.end()) {
        if (rejection_reason) {
            *rejection_reason = "Processor already exists in chain for this buffer";
        }
        return false;
    }
    processors.push_back(processor);
    processor->on_attach(buffer);
    return true;
}
References MayaFlux::Buffers::are_tokens_compatible(), MayaFlux::Buffers::FILTERED, MayaFlux::Buffers::IGNORE, m_buffer_processors, m_conditional_processors, m_enforcement_strategy, m_pending_removal, m_token_filter_mask, MayaFlux::Buffers::OVERRIDE_REJECT, MayaFlux::Buffers::OVERRIDE_SKIP, and MayaFlux::Buffers::STRICT.
Referenced by add_processor(), and process_pending_processor_operations().