MayaFlux: MayaFlux::Core::VKShaderModule::create_from_spirv
create_from_spirv()
bool MayaFlux::Core::VKShaderModule::create_from_spirv (vk::Device device, const std::vector< uint32_t > & spirv_code, vk::ShaderStageFlagBits stage, const std::string & entry_point = "main", bool enable_reflection = true)
Create shader module from SPIR-V binary.
Parameters
device Logical device
spirv_code SPIR-V bytecode (must be aligned to uint32_t)
stage Shader stage (compute, vertex, fragment, etc.)
entry_point Entry point function name (default: "main")
enable_reflection Extract descriptor bindings and resources
Returns
true if creation succeeded
This is the lowest-level creation method. All other create methods eventually funnel through this one.
Definition at line 155 of file VKShaderModule.cpp.
{
    if (spirv_code.empty()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot create shader module from empty SPIR-V code");
        return false;
    }
    if (spirv_code[0] != 0x07230203) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Invalid SPIR-V magic number: 0x{:08X} (expected 0x07230203)",
            spirv_code[0]);
        return false;
    }
    vk::ShaderModuleCreateInfo create_info;
    create_info.codeSize = spirv_code.size() * sizeof(uint32_t);
    create_info.pCode = spirv_code.data();
    try {
        m_module = device.createShaderModule(create_info);
    } catch (const vk::SystemError& e) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to create shader module: {}", e.what());
        return false;
    }
    m_stage = stage;
    m_entry_point = entry_point;
    if (m_preserve_spirv) {
        m_spirv_code = spirv_code;
    }
    if (enable_reflection) {
        if (!reflect_spirv(spirv_code)) {
            MF_WARN(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Shader reflection failed - descriptor layouts must be manually specified");
        }
    }
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Shader module created ({} stage, {} bytes SPIR-V, entry='{}')",
        vk::to_string(stage), spirv_code.size() * 4, entry_point);
    return true;
}
References MayaFlux::Journal::Core, MayaFlux::Journal::GraphicsBackend, m_entry_point, m_module, m_preserve_spirv, m_spirv_code, m_stage, MF_ERROR, MF_INFO, MF_WARN, and reflect_spirv().
Referenced by create_from_glsl(), and create_from_spirv_file().