MayaFlux: MayaFlux::IO::SoundFileReader::build_metadata
build_metadata()
void MayaFlux::IO::SoundFileReader::build_metadata (const std::shared_ptr< FFmpegDemuxContext > & demux, const std::shared_ptr< AudioStreamContext > & audio) const private
Build and cache FileMetadata from both contexts.
Definition at line 229 of file SoundFileReader.cpp.
{
    FileMetadata meta;
    demux->extract_container_metadata(meta);
    audio->extract_stream_metadata(*demux, meta);
    meta.file_size = std::filesystem::file_size(m_filepath);
    auto ftime = std::filesystem::last_write_time(m_filepath);
    meta.modification_time = std::chrono::system_clock::time_point(
        std::chrono::seconds(
            std::chrono::duration_cast<std::chrono::seconds>(ftime.time_since_epoch())));
    std::lock_guard<std::mutex> ml(m_metadata_mutex);
    m_cached_metadata = std::move(meta);
}
References MayaFlux::IO::FileMetadata::file_size, m_cached_metadata, m_filepath, m_metadata_mutex, and MayaFlux::IO::FileMetadata::modification_time.
Referenced by get_metadata(), open(), and open_from_demux().