MayaFlux: MayaFlux::Kakshya::SoundStreamContainer::has_data
has_data()
bool MayaFlux::Kakshya::SoundStreamContainer::has_data () const override virtual
Check if the container currently holds any data.
Returns
true if data is present, false otherwise
Implements MayaFlux::Kakshya::NDDataContainer.
Definition at line 341 of file SoundStreamContainer.cpp.
{
    std::shared_lock lock(m_data_mutex);
    return std::ranges::any_of(m_data, [](const auto& variant) {
        return std::visit([](const auto& vec) { return !vec.empty(); }, variant);
    });
}
References lock(), m_data, and m_data_mutex.
Referenced by get_value_at(), is_ready(), is_ready_for_processing(), and mark_ready_for_processing().