MayaFlux: MayaFlux::Kakshya::VideoStreamContainer::get_frame_pixels
get_frame_pixels()
std::span< const uint8_t > MayaFlux::Kakshya::VideoStreamContainer::get_frame_pixels (uint64_t frame_index) const
Get raw pixel data for a single frame as uint8_t span.
Parameters
frame_index Zero-based frame index.
Returns
Span of pixel bytes for the frame, empty if out of range.
Definition at line 186 of file VideoStreamContainer.cpp.
{
    const size_t frame_bytes = get_frame_byte_size();
    if (frame_bytes == 0 || frame_index >= m_num_frames)
        return {};
    if (m_ring_capacity == 0) {
        std::span<const uint8_t> result;
        seqlock_read_void(m_data_lock, 8, [&] {
            if (m_data.empty())
                return;
            const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_data[0]);
            if (!pixels)
                return;
            const size_t offset = frame_index * frame_bytes;
            if (offset + frame_bytes > pixels->size())
                return;
            result = { pixels->data() + offset, frame_bytes };
        });
        return result;
    }
    const uint32_t slot = slot_for(frame_index);
    if (m_slot_frame[slot].load(std::memory_order_acquire) == frame_index) {
        const auto* pixels = std::get_if<std::vector<uint8_t>>(&m_data[0]);
        if (!pixels)
            return {};
        return { pixels->data() + slot * frame_bytes, frame_bytes };
    }
    return {};
}
References get_frame_byte_size(), m_data, m_data_lock, m_num_frames, m_ring_capacity, m_slot_frame, pixels, and slot_for().
Referenced by get_value_impl().