MayaFlux: MayaFlux::Nodes::NodeGraphManager::process_channel
process_channel()
std::vector< double > MayaFlux::Nodes::NodeGraphManager::process_channel (ProcessingToken token, unsigned int channel, unsigned int num_samples)
Process a specific channel within a token domain.
Parameters
token Processing domain
channel Channel index within that domain
num_samples Number of samples/frames to process
Returns
Processed data from the channel's root node
Processes a single channel's root node and returns the processed data. If a custom per-channel processor is registered, it is used; otherwise, the default root node processing is performed.
Definition at line 214 of file NodeGraphManager.cpp.
{
    if (channel == 0) {
        reset_audio_network_state(token);
    }
    auto& root = get_root_node(token, channel);
    if (auto it = m_token_channel_processors.find(token); it != m_token_channel_processors.end()) {
        return it->second(&root, num_samples);
    }
    std::vector<double> samples = root.process_batch(num_samples);
    uint32_t normalize_coef = root.get_node_size();
    for (double& sample : samples) {
        normalize_sample(sample, normalize_coef);
    }
    return samples;
}
References get_root_node(), m_token_channel_processors, normalize_sample(), and reset_audio_network_state().
Referenced by process_token_with_channel_data().