MayaFlux: MayaFlux::Portal::Forma::Inspector::scheduler
scheduler()
InspectResult & MayaFlux::Portal::Forma::Inspector::scheduler (Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F)
Inspect the full TaskScheduler state.
Header shows total task count. Each task is a collapsible whose header is the routine's dynamic type name, with name, token, active, and delay context as sub-fields.
Persistent: the first call builds the result against surface and cursor and stores it statically. Subsequent calls return the same result regardless of the supplied surface and cursor; the original window remains the render target. To display on a different surface, the process must be restarted.
Definition at line 59 of file SchedulerQuery.cpp.
{
    if (s_scheduler_result) {
        return *s_scheduler_result;
    }
    const std::vector<ValueSpec> root_values {
        ValueSpec {
            .label = "tasks",
            .reader = [&m_sched = m_sched] {
                return std::to_string(m_sched.get_all_tasks().size());
            },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), "TaskScheduler", dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(root_values.size());
    for (const auto& spec : root_values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto root_group = make_value_group(root_values, std::move(hbuf), rbufs,
        surface, cursor, x_min, x_max, row_h, true);
    InspectResult& result = s_scheduler_result.emplace();
    result.group = std::move(root_group);
    const auto tasks = m_sched.get_all_tasks();
    for (const auto& entry : tasks) {
        if (!entry.routine)
            continue;
        auto task_result = inspect_task(
            entry, surface, cursor,
            x_min, x_max, row_h);
        result.group.header.attach(surface.layer(), task_result.group.header.header_id);
        result.children.push_back(std::move(task_result));
    }
    return result;
}
References MayaFlux::Portal::Forma::Collapsible::attach(), MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Vruta::TaskScheduler::get_all_tasks(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, inspect_task(), MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Portal::Forma::Surface::layer(), m_sched, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::row_pixel_dims(), s_scheduler_result, tasks(), and MayaFlux::Portal::Forma::Surface::window().