MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::process_bidirectional
process_bidirectional()
void MayaFlux::Nodes::Network::WaveguideNetwork::process_bidirectional (WaveguideSegment & seg, unsigned int num_samples, std::vector< double > & out) private
Definition at line 187 of file WaveguideNetwork.cpp.
{
    const double continuous_gain = (m_exciter_type == ExciterType::CONTINUOUS && m_exciter_node)
        ? 1.0 / seg.loss_factor
        : 1.0;
    for (unsigned int i = 0; i < num_samples; ++i) {
        const double exciter = generate_exciter_sample();
        const double plus_end = read_with_interpolation(
            seg.p_plus, m_delay_length_integer, m_delay_length_fraction);
        const double minus_end = read_with_interpolation(
            seg.p_minus, m_delay_length_integer, m_delay_length_fraction);
        auto* filt_open = seg.loop_filter_open ? seg.loop_filter_open.get()
                                               : seg.loop_filter.get();
        auto* filt_closed = seg.loop_filter_closed ? seg.loop_filter_closed.get()
                                                   : seg.loop_filter.get();
        const double filtered_plus = (m_exciter_type != ExciterType::CONTINUOUS && filt_open)
            ? filt_open->process_sample(plus_end)
            : plus_end;
        const double filtered_minus = (m_exciter_type != ExciterType::CONTINUOUS && filt_closed)
            ? filt_closed->process_sample(minus_end)
            : minus_end;
        seg.p_minus.push(filtered_plus * seg.loss_factor * seg.reflection_open * continuous_gain);
        seg.p_plus.push(exciter + filtered_minus * seg.loss_factor * seg.reflection_closed * continuous_gain);
        out[i] = observe_sample(seg);
    }
}
References CONTINUOUS, generate_exciter_sample(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loop_filter, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loop_filter_closed, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loop_filter_open, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::loss_factor, m_delay_length_fraction, m_delay_length_integer, m_exciter_node, m_exciter_type, observe_sample(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::p_minus, MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::p_plus, MayaFlux::Memory::HistoryBuffer< T >::push(), read_with_interpolation(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::reflection_closed, and MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::reflection_open.
Referenced by process_batch().