MayaFlux: MayaFlux::Portal::Forma::Plot::Series::resolved_tick_labels
resolved_tick_labels()
std::vector< TickLabelsSpec > MayaFlux::Portal::Forma::Plot::Series::resolved_tick_labels () const
Resolve pending fluent tick requests into concrete tick label specs.
Definition at line 128 of file SeriesBuilder.cpp.
{
    std::vector<TickLabelsSpec> resolved;
    if (!m_plot_bounds)
        return resolved;
    resolved.reserve(m_ticks.size());
    for (const auto& req : m_ticks) {
        AxisRange range {};
        if (req.range) {
            range = *req.range;
        } else {
            switch (req.axis) {
            case TickAxis::X:
                range = merge_axis_const(m_x);
                break;
            case TickAxis::Y:
                range = merge_axis_const(m_y);
                break;
            case TickAxis::Explicit:
            default:
                range = {};
                break;
            }
        }
        resolved.push_back(TickLabelsSpec {
            .plot_bounds = *m_plot_bounds,
            .range = std::move(range),
            .count = req.count,
            .edge = req.edge,
            .color = req.color,
            .decimal_places = req.decimal_places,
            .label_h = req.label_h,
            .label_w = req.label_w,
            .name_prefix = req.name_prefix,
        });
    }
    return resolved;
}
References Explicit, m_plot_bounds, m_ticks, m_x, m_y, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::plot_bounds, X, and Y.
Referenced by MayaFlux::Portal::Forma::Plot::WaveformBuilder::done(), MayaFlux::Portal::Forma::Plot::ScatterBuilder::done(), MayaFlux::Portal::Forma::Plot::BarsBuilder::done(), and MayaFlux::Portal::Forma::Plot::FilledWaveformBuilder::done().