MayaFlux: MayaFlux::Buffers::TokenUnitManager::get_graphics_unit
get_graphics_unit()
const RootGraphicsUnit & MayaFlux::Buffers::TokenUnitManager::get_graphics_unit (ProcessingToken token) const
Gets an existing graphics unit without creating if missing.
Parameters
token Processing domain
Returns
Const reference to the graphics unit
Exceptions
std::out_of_range if token not found
This is a query-only operation; will not create a unit if missing.
Definition at line 151 of file TokenUnitManager.cpp.
{
    auto it = m_graphics_units.find(token);
    if (it == m_graphics_units.end()) {
        throw std::out_of_range("Graphics unit not found for token");
    }
    return it->second;
}
References m_graphics_units.
Referenced by MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers(), MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers_by_usage(), and MayaFlux::Buffers::BufferAccessControl::get_root_graphics_buffer().