MayaFlux: MayaFlux::Core::VKShaderModule::create_from_glsl
create_from_glsl()
bool MayaFlux::Core::VKShaderModule::create_from_glsl (vk::Device device, const std::string & glsl_source, vk::ShaderStageFlagBits stage, const std::string & entry_point = "main", bool enable_reflection = true, const std::vector< std::string > & include_directories = {}, const std::unordered_map< std::string, std::string > & defines = {})
Create shader module from GLSL source string.
Parameters
device Logical device
glsl_source GLSL source code
stage Shader stage (determines compiler mode)
entry_point Entry point function name
enable_reflection Extract metadata
include_directories Paths for #include resolution
defines Preprocessor definitions (e.g., {"DEBUG", "MAX_LIGHTS=4"})
Returns
true if creation succeeded
Compiles GLSL → SPIR-V using shaderc, then calls create_from_spirv(). Requires shaderc library to be available.
Definition at line 234 of file VKShaderModule.cpp.
{
    auto spirv_code = compile_glsl_to_spirv(glsl_source, stage, include_directories, defines);
    if (spirv_code.empty()) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to compile GLSL to SPIR-V ({} stage)", vk::to_string(stage));
        return false;
    }
    MF_DEBUG(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Compiled GLSL to SPIR-V ({} stage, {} bytes)",
        vk::to_string(stage), spirv_code.size() * 4);
    return create_from_spirv(device, spirv_code, stage, entry_point, enable_reflection);
}
References compile_glsl_to_spirv(), MayaFlux::Journal::Core, create_from_spirv(), MayaFlux::Journal::GraphicsBackend, MF_DEBUG, and MF_ERROR.
Referenced by create_from_glsl_file().