MayaFlux: MayaFlux::Vruta::TaskScheduler::get_tasks_for_token
get_tasks_for_token()
std::vector< std::shared_ptr< Routine > > MayaFlux::Vruta::TaskScheduler::get_tasks_for_token (ProcessingToken token) const
Get all tasks for a specific processing domain.
Parameters
token Processing domain
Returns
Vector of tasks in the domain
Definition at line 92 of file Scheduler.cpp.
{
    std::vector<std::shared_ptr<Routine>> result;
    for (const auto& entry : m_tasks) {
        if (entry.routine && entry.routine->get_processing_token() == token) {
            result.push_back(entry.routine);
        }
    }
    return result;
}
References m_tasks.
Referenced by process_buffer_cycle_tasks(), process_default(), and process_token().