MayaFlux: MayaFlux::Core::OscParser::serialize
serialize()
std::vector< uint8_t > MayaFlux::Core::OscParser::serialize (const std::string & address, const std::vector< InputValue::OSCArg > & args) static
Serialize an OSC message to wire format.
Parameters
address OSC address string (must start with '/').
args Typed arguments.
Returns
Serialized bytes, or empty on error.
Definition at line 66 of file OscParser.cpp.
{
    if (address.empty() || address[0] != '/') {
        return {};
    }
    std::vector<uint8_t> out;
    out.reserve(256);
    Transitive::Protocol::write_string(out, address);
    std::string type_tags = ",";
    for (const auto& arg : args) {
        std::visit([&type_tags](const auto& val) {
            using T = std::decay_t<decltype(val)>;
            if constexpr (std::is_same_v<T, int32_t>) {
                type_tags += 'i';
            } else if constexpr (std::is_same_v<T, float>) {
                type_tags += 'f';
            } else if constexpr (std::is_same_v<T, std::string>) {
                type_tags += 's';
            } else if constexpr (std::is_same_v<T, std::vector<uint8_t>>) {
                type_tags += 'b';
            }
        },
            arg);
    }
    Transitive::Protocol::write_string(out, type_tags);
    for (const auto& arg : args) {
        std::visit([&out](const auto& val) {
            using T = std::decay_t<decltype(val)>;
            if constexpr (std::is_same_v<T, int32_t>) {
                Transitive::Protocol::write_int32(out, val);
            } else if constexpr (std::is_same_v<T, float>) {
                Transitive::Protocol::write_float(out, val);
            } else if constexpr (std::is_same_v<T, std::string>) {
                Transitive::Protocol::write_string(out, val);
            } else if constexpr (std::is_same_v<T, std::vector<uint8_t>>) {
                Transitive::Protocol::write_blob(out, val);
            }
        },
            arg);
    }
    return out;
}
References MayaFlux::Transitive::Protocol::write_blob(), MayaFlux::Transitive::Protocol::write_float(), MayaFlux::Transitive::Protocol::write_int32(), and MayaFlux::Transitive::Protocol::write_string().
Referenced by MayaFlux::Portal::Network::serialize_osc().