MayaFlux: MayaFlux::Kakshya::RegionProcessorBase::on_attach
on_attach()
void MayaFlux::Kakshya::RegionProcessorBase::on_attach (const std::shared_ptr< SignalSourceContainer > & container) override virtual
Attach this processor to a signal source container.
Initializes region organization, caching, and dimension metadata.
Parameters
container The SignalSourceContainer to attach to.
Implements MayaFlux::Kakshya::DataProcessor.
Reimplemented in MayaFlux::Kakshya::SpatialRegionProcessor.
Definition at line 8 of file RegionProcessorBase.cpp.
{
    if (!container) {
        throw std::invalid_argument("Container cannot be null");
    }
    m_container_weak = container;
    m_structure = container->get_structure();
    m_cache_manager = std::make_unique<RegionCacheManager>(m_max_cache_size);
    m_cache_manager->initialize();
    m_current_position.resize(m_structure.get_frame_size());
    organize_container_data(container);
    container->mark_ready_for_processing(true);
}
References MayaFlux::Kakshya::ContainerDataStructure::get_frame_size(), m_cache_manager, m_container_weak, m_current_position, m_max_cache_size, m_structure, and organize_container_data().
Referenced by MayaFlux::Kakshya::SpatialRegionProcessor::on_attach(), and MayaFlux::Kakshya::RegionOrganizationProcessor::RegionOrganizationProcessor().