MayaFlux: MayaFlux::Nodes::Generator::Generator::update_context
update_context()
void MayaFlux::Nodes::Generator::Generator::update_context (double value) override virtual
Updates the context object for callbacks.
Parameters
value The current generated sample
This method creates a specialized context object containing the current sample value and all oscillator parameters, providing callbacks with rich information about the oscillator's state.
Implements MayaFlux::Nodes::Node.
Reimplemented in MayaFlux::Nodes::Generator::Logic, MayaFlux::Nodes::Generator::Polynomial, and MayaFlux::Nodes::Generator::Random.
Definition at line 19 of file Generator.cpp.
{
    if (m_gpu_compatible) {
        m_context_gpu.value = value;
        m_context_gpu.frequency = m_frequency;
        m_context_gpu.amplitude = m_amplitude;
        m_context_gpu.phase = m_phase;
    } else {
        m_context.value = value;
        m_context.frequency = m_frequency;
        m_context.amplitude = m_amplitude;
        m_context.phase = m_phase;
    }
}
References MayaFlux::Nodes::Generator::GeneratorContext::amplitude, MayaFlux::Nodes::Generator::GeneratorContext::frequency, m_amplitude, m_context, m_context_gpu, m_frequency, MayaFlux::Nodes::Node::m_gpu_compatible, m_phase, MayaFlux::Nodes::Generator::GeneratorContext::phase, and MayaFlux::Nodes::NodeContext::value.
Referenced by MayaFlux::Nodes::Generator::Impulse::notify_tick(), MayaFlux::Nodes::Generator::Phasor::notify_tick(), and MayaFlux::Nodes::Generator::Sine::notify_tick().