MayaFlux: MayaFlux::Buffers::DataWriteProcessor::ensure_capacity
ensure_capacity()
void MayaFlux::Buffers::DataWriteProcessor::ensure_capacity (const std::shared_ptr< VKBuffer > & vk, size_t required) private
Definition at line 287 of file DataWriteProcessor.cpp.
{
    if (required <= vk->get_size_bytes()) {
        return;
    }
    vk->resize(static_cast<size_t>(static_cast<float>(required) * 1.5F), false);
    if (m_staging) {
        m_staging = create_staging_buffer(vk->get_size_bytes());
    }
}
References MayaFlux::Buffers::create_staging_buffer(), and m_staging.
Referenced by upload_raw(), upload_secondary(), and upload_vertex().