MayaFlux: MayaFlux::Nodes::Generator::Sine::update_phase_increment
update_phase_increment()
void MayaFlux::Nodes::Generator::Sine::update_phase_increment (double frequency) private
Updates the phase increment based on a new frequency.
Parameters
frequency New frequency in Hz
This method calculates the phase increment needed to produce the specified frequency at the current sample rate.
Definition at line 52 of file Sine.cpp.
{
    uint64_t s_rate = 48000U;
    if (MayaFlux::is_engine_initialized()) {
        s_rate = Config::get_sample_rate();
    }
    m_phase_inc = (2 * M_PI * frequency) / (double)s_rate;
}
References MayaFlux::Config::get_sample_rate(), MayaFlux::is_engine_initialized(), and m_phase_inc.
Referenced by process_sample(), reset(), set_frequency(), Sine(), Sine(), Sine(), and Sine().