MayaFlux: MayaFlux::Core::BackendResourceManager::execute_immediate_commands
execute_immediate_commands()
void MayaFlux::Core::BackendResourceManager::execute_immediate_commands (const std::function< void(vk::CommandBuffer)> & recorder)
Execute immediate command recording for buffer operations.
Parameters
recorder Command recording function
Definition at line 979 of file BackendResoureManager.cpp.
{
    vk::CommandBuffer cmd = m_command_manager.begin_single_time_commands();
    recorder(cmd);
    m_command_manager.end_single_time_commands(cmd, m_context.get_graphics_queue());
}
References MayaFlux::Core::VKCommandManager::begin_single_time_commands(), cmd, MayaFlux::Core::VKCommandManager::end_single_time_commands(), MayaFlux::Core::VKContext::get_graphics_queue(), m_command_manager, and m_context.
Referenced by download_image_data(), record_deferred_commands(), setup_backend_service(), transition_image_layout(), upload_image_data(), and upload_image_data_with_staging().