MayaFlux: MayaFlux::Buffers::StreamSliceProcessor::load
load()
void MayaFlux::Buffers::StreamSliceProcessor::load (size_t index, Kakshya::StreamSlice slice)
Assign a StreamSlice to a slot.
Must be called after the processor is attached to a buffer, as the buffer's frame count is required to configure the CursorAccessProcessor. Calling load() before attachment is a no-op with an error log.
Constructs a CursorAccessProcessor owned by this slot, attaches it to the slice's stream, and configures the loop region from the slice's Region. Any previously loaded slot processor is detached first. The slot is left inactive; call bind() to start playback. Grows the slot pool if index exceeds the current size.
Parameters
index The slot is left inactive; call bind() to start playback.
slice StreamSlice describing the stream and region.
Definition at line 40 of file StreamSliceProcessor.cpp.
{
    if (m_frames_per_block == 0) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "StreamSliceProcessor::load called before attachment to a buffer -- attach first");
        return;
    }
    if (!slice.stream)
        return;
    if (index > m_slots.size()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::Configuration,
            "StreamSliceProcessor::load index {} exceeds slot count {}; use {} for next available",
            index, m_slots.size(), m_slots.size());
    }
    if (index >= m_slots.size())
        m_slots.resize(index + 1);
    detach_slot(index);
    slice.active = false;
    slice.index = static_cast<uint8_t>(index);
    auto proc = std::make_shared<Kakshya::CursorAccessProcessor>(m_frames_per_block);
    proc->set_loop_region(slice.start_frame(), slice.end_frame());
    proc->set_looping(slice.looping);
    proc->set_loop_count(slice.loop_count);
    if (slice.speed != 1.0)
        proc->set_speed(slice.speed);
    proc->set_on_end([this, index] {
        m_slots[index].slice.active = false;
        if (m_on_end)
            m_on_end(index);
    });
    proc->on_attach(slice.stream);
    m_slots[index].slice = std::move(slice);
    m_slots[index].proc = std::move(proc);
}
References MayaFlux::Kakshya::StreamSlice::active, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Journal::Configuration, detach_slot(), MayaFlux::Kakshya::StreamSlice::end_frame(), MayaFlux::Kakshya::StreamSlice::index, MayaFlux::Kakshya::StreamSlice::loop_count, MayaFlux::Kakshya::StreamSlice::looping, m_frames_per_block, m_on_end, m_slots, MF_ERROR, MF_WARN, slice(), MayaFlux::Kakshya::StreamSlice::speed, MayaFlux::Kakshya::StreamSlice::start_frame(), and MayaFlux::Kakshya::StreamSlice::stream.