MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::set_topology
set_topology()
void MayaFlux::Nodes::Network::NodeNetwork::set_topology (Topology topology) inline
Set the network's topology.
Definition at line 172 of file NodeNetwork.hpp.
{ m_topology = topology; }
Referenced by MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), MayaFlux::Nodes::Network::ModalNetwork::ModalNetwork(), and MayaFlux::Nodes::Network::ParticleNetwork::ParticleNetwork().