MayaFlux: MayaFlux::Kriya::SamplingPipeline::build
build()
void MayaFlux::Kriya::SamplingPipeline::build ()
Finalize configuration and start processing.
Supplies the buffer to the output channel, chains the capture operation into the pipeline, and starts execution at buffer rate. Must be called before play(). Calling build() more than once has no effect.
Definition at line 58 of file SamplingPipeline.cpp.
{
    if (m_built)
        return;
    m_mgr.supply_buffer_to(m_buffer,
        Buffers::ProcessingToken::AUDIO_BACKEND, m_channel, 1.0, true);
    m_pipeline >> static_cast<BufferOperation>(m_capture);
    m_pipeline->execute_buffer_rate(0);
    m_built = true;
}
References MayaFlux::Buffers::AUDIO_BACKEND, m_buffer, m_built, m_capture, m_channel, m_mgr, m_pipeline, and MayaFlux::Buffers::BufferManager::supply_buffer_to().
Referenced by play(), and play_continuous().