MayaFlux: MayaFlux::Nodes::Input::HIDNode::parse_axis
parse_axis()
double MayaFlux::Nodes::Input::HIDNode::parse_axis (std::span< const uint8_t > bytes) const private
Parse axis value from HID report bytes.
Parameters
bytes HID report bytes
Returns
Normalized axis value (0.0 to 1.0)
Definition at line 39 of file HIDNode.cpp.
{
    if (bytes.size() <= m_config.byte_offset) {
        return m_config.default_value;
    }
    double raw = 0.0;
    if (m_config.byte_size == 1) {
        uint8_t b = bytes[m_config.byte_offset];
        raw = m_config.is_signed
            ? static_cast<double>(static_cast<int8_t>(b))
            : static_cast<double>(b);
    } else if (m_config.byte_size == 2 && bytes.size() > m_config.byte_offset + 1) {
        uint16_t w = bytes[m_config.byte_offset] | (bytes[m_config.byte_offset + 1] << 8);
        raw = m_config.is_signed
            ? static_cast<double>(static_cast<int16_t>(w))
            : static_cast<double>(w);
    }
    // Normalize to 0-1
    double normalized = (raw - m_config.min_raw) / (m_config.max_raw - m_config.min_raw);
    normalized = std::clamp(normalized, 0.0, 1.0);
    // Apply deadzone if configured
    if (m_config.deadzone > 0.0) {
        normalized = apply_deadzone(normalized);
    }
    return normalized;
}
References apply_deadzone(), b, MayaFlux::Nodes::Input::HIDConfig::byte_offset, MayaFlux::Nodes::Input::HIDConfig::byte_size, MayaFlux::Nodes::Input::HIDConfig::deadzone, MayaFlux::Nodes::Input::InputConfig::default_value, MayaFlux::Nodes::Input::HIDConfig::is_signed, m_config, MayaFlux::Nodes::Input::HIDConfig::max_raw, MayaFlux::Nodes::Input::HIDConfig::min_raw, and MayaFlux::normalized().
Referenced by extract_value().