MayaFlux: MayaFlux::Kriya::TemporalActivation::activate_node
activate_node()
void MayaFlux::Kriya::TemporalActivation::activate_node (const std::shared_ptr< Nodes::Node > & node, double duration_seconds, Nodes::ProcessingToken token = Nodes::ProcessingToken::AUDIO_RATE, const std::vector< uint32_t > & channels = {})
Activates a node for a specified duration.
Parameters
node The node to activate
token The processing token associated with the node
duration_seconds The duration to keep the node active (in seconds)
channels Optional list of output channels to connect the node to (default is all channels)
This method activates the specified node by connecting it to the output channels or graphics sync, and starts a timer for the specified duration. When the timer expires, the node is automatically disconnected from the output channels, effectively deactivating it.
If another node, network, or buffer is already active, it will be cancelled before activating the new one.
Definition at line 87 of file Timers.cpp.
{
    cancel();
    m_current_node = node;
    m_node_token = token;
    m_channels = channels;
    m_active_type = ActiveType::NODE;
    for (auto channel : channels) {
        m_node_graph_manager.add_to_root(node, token, channel);
    }
    m_timer.schedule(duration_seconds, [this]() {
        cleanup_current_operation();
    });
}
References MayaFlux::Nodes::NodeGraphManager::add_to_root(), cancel(), channel, cleanup_current_operation(), m_active_type, m_channels, m_current_node, m_node_graph_manager, m_node_token, m_timer, NODE, and MayaFlux::Kriya::Timer::schedule().