MayaFlux: MayaFlux::Nodes::Generator::Phasor::update_phase_increment
update_phase_increment()
void MayaFlux::Nodes::Generator::Phasor::update_phase_increment (double frequency) private
Updates the phase increment based on a new frequency.
Parameters
frequency New frequency in Hz
This method calculates the phase increment needed to produce a complete cycle at the specified frequency at the current sample rate.
Definition at line 60 of file Phasor.cpp.
{
    uint64_t s_rate = 48000U;
    if (MayaFlux::is_engine_initialized()) {
        s_rate = Config::get_sample_rate();
    }
    m_phase_inc = frequency / (double)s_rate;
}
References MayaFlux::Config::get_sample_rate(), MayaFlux::is_engine_initialized(), and m_phase_inc.
Referenced by Phasor(), Phasor(), Phasor(), Phasor(), process_sample(), reset(), and set_frequency().