MayaFlux: MayaFlux::Core::BackendResourceManager::transition_image_layout
transition_image_layout()
void MayaFlux::Core::BackendResourceManager::transition_image_layout (vk::Image image, vk::ImageLayout old_layout, vk::ImageLayout new_layout, uint32_t mip_levels = 1, uint32_t array_layers = 1, vk::ImageAspectFlags aspect_flags = vk::ImageAspectFlagBits::eColor)
Transition image layout using a pipeline barrier.
Parameters
image VkImage handle
old_layout Current layout
new_layout Target layout
mip_levels Number of mip levels to transition
array_layers Number of array layers to transition
Executes immediately on graphics queue. Use for initial setup and one-off transitions. For rendering, prefer manual barriers.
Definition at line 530 of file BackendResoureManager.cpp.
{
    execute_immediate_commands([&](vk::CommandBuffer cmd) {
        vk::ImageMemoryBarrier barrier {};
        barrier.oldLayout = old_layout;
        barrier.newLayout = new_layout;
        barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.image = image;
        barrier.subresourceRange.aspectMask = aspect_flags;
        barrier.subresourceRange.baseMipLevel = 0;
        barrier.subresourceRange.levelCount = mip_levels;
        barrier.subresourceRange.baseArrayLayer = 0;
        barrier.subresourceRange.layerCount = array_layers;
        vk::PipelineStageFlags src_stage;
        vk::PipelineStageFlags dst_stage;
        if (old_layout == vk::ImageLayout::eUndefined && new_layout == vk::ImageLayout::eTransferDstOptimal) {
            barrier.srcAccessMask = vk::AccessFlags {};
            barrier.dstAccessMask = vk::AccessFlagBits::eTransferWrite;
            src_stage = vk::PipelineStageFlagBits::eTopOfPipe;
            dst_stage = vk::PipelineStageFlagBits::eTransfer;
        } else if (old_layout == vk::ImageLayout::eTransferDstOptimal && new_layout == vk::ImageLayout::eShaderReadOnlyOptimal) {
            barrier.srcAccessMask = vk::AccessFlagBits::eTransferWrite;
            barrier.dstAccessMask = vk::AccessFlagBits::eShaderRead;
            src_stage = vk::PipelineStageFlagBits::eTransfer;
            dst_stage = vk::PipelineStageFlagBits::eFragmentShader;
        } else if (old_layout == vk::ImageLayout::eUndefined && new_layout == vk::ImageLayout::eShaderReadOnlyOptimal) {
            barrier.srcAccessMask = vk::AccessFlags {};
            barrier.dstAccessMask = vk::AccessFlagBits::eShaderRead;
            src_stage = vk::PipelineStageFlagBits::eTopOfPipe;
            dst_stage = vk::PipelineStageFlagBits::eFragmentShader;
        } else if (old_layout == vk::ImageLayout::eUndefined && new_layout == vk::ImageLayout::eColorAttachmentOptimal) {
            barrier.srcAccessMask = vk::AccessFlags {};
            barrier.dstAccessMask = vk::AccessFlagBits::eColorAttachmentWrite;
            src_stage = vk::PipelineStageFlagBits::eTopOfPipe;
            dst_stage = vk::PipelineStageFlagBits::eColorAttachmentOutput;
        } else if (old_layout == vk::ImageLayout::eUndefined && new_layout == vk::ImageLayout::eDepthStencilAttachmentOptimal) {
            barrier.srcAccessMask = vk::AccessFlags {};
            barrier.dstAccessMask = vk::AccessFlagBits::eDepthStencilAttachmentRead | vk::AccessFlagBits::eDepthStencilAttachmentWrite;
            src_stage = vk::PipelineStageFlagBits::eTopOfPipe;
            dst_stage = vk::PipelineStageFlagBits::eEarlyFragmentTests;
        } else if (old_layout == vk::ImageLayout::eUndefined && new_layout == vk::ImageLayout::eGeneral) {
            barrier.srcAccessMask = vk::AccessFlags {};
            barrier.dstAccessMask = vk::AccessFlagBits::eShaderRead | vk::AccessFlagBits::eShaderWrite;
            src_stage = vk::PipelineStageFlagBits::eTopOfPipe;
            dst_stage = vk::PipelineStageFlagBits::eComputeShader;
        } else {
            barrier.srcAccessMask = vk::AccessFlagBits::eMemoryRead | vk::AccessFlagBits::eMemoryWrite;
            barrier.dstAccessMask = vk::AccessFlagBits::eMemoryRead | vk::AccessFlagBits::eMemoryWrite;
            src_stage = vk::PipelineStageFlagBits::eAllCommands;
            dst_stage = vk::PipelineStageFlagBits::eAllCommands;
            MF_WARN(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Using generic image layout transition");
        }
        cmd.pipelineBarrier(
            src_stage, dst_stage,
            vk::DependencyFlags {},
            0, nullptr, // Memory barriers
            0, nullptr, // Buffer barriers
            1, &barrier // Image barriers
        );
    });
    MF_DEBUG(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Image layout transitioned: {} -> {}",
        vk::to_string(old_layout), vk::to_string(new_layout));
}
References cmd, MayaFlux::Journal::Core, execute_immediate_commands(), MayaFlux::Journal::GraphicsBackend, image, MF_DEBUG, and MF_WARN.
Referenced by MayaFlux::Portal::Graphics::TextureLoom::create_2d(), MayaFlux::Portal::Graphics::TextureLoom::create_3d(), MayaFlux::Portal::Graphics::TextureLoom::create_cubemap(), MayaFlux::Portal::Graphics::TextureLoom::create_depth_buffer(), MayaFlux::Portal::Graphics::TextureLoom::create_render_target(), MayaFlux::Portal::Graphics::TextureLoom::create_storage_image(), and MayaFlux::Portal::Graphics::TextureLoom::transition_layout().