MayaFlux: MayaFlux::Core::GraphicsSubsystem::shutdown
shutdown()
void MayaFlux::Core::GraphicsSubsystem::shutdown () override virtual
Shutdown and cleanup subsystem resources.
Implements MayaFlux::Core::ISubsystem.
Definition at line 385 of file GraphicsSubsystem.cpp.
{
    stop();
    teardown_windows();
    Portal::Text::shutdown();
    Portal::Graphics::shutdown();
    m_backend->cleanup();
    m_is_ready = false;
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsSubsystem,
        "Graphics Subsystem shutdown complete.");
}
References MayaFlux::Journal::Core, MayaFlux::Journal::GraphicsSubsystem, m_backend, m_is_ready, MF_INFO, MayaFlux::Portal::Graphics::shutdown(), MayaFlux::Portal::Text::shutdown(), stop(), and teardown_windows().