MayaFlux: MayaFlux::Nodes::Network::WaveguideNetwork::process_batch
process_batch()
void MayaFlux::Nodes::Network::WaveguideNetwork::process_batch (unsigned int num_samples) override virtual
Process the network for the given number of samples.
Parameters
num_samples Number of samples/frames to process
Subclasses implement their specific processing logic:
Update internal state (physics, relationships, etc.)
Process individual nodes
Apply inter-node interactions
Aggregate outputs if needed
Called by NodeGraphManager during token processing.
Implements MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 122 of file WaveguideNetwork.cpp.
{
    ensure_initialized();
    if (!is_enabled() || m_segments.empty()) {
        while (m_audio_buffer_lock.test_and_set(std::memory_order_acquire))
            std::this_thread::yield();
        m_last_audio_buffer.assign(num_samples, 0.0);
        m_last_output = 0.0;
        m_audio_buffer_lock.clear(std::memory_order_release);
        return;
    }
    update_mapped_parameters();
    thread_local std::vector<double> scratch;
    scratch.assign(num_samples, 0.0);
    auto& seg = m_segments[0];
    if (m_exciter_node && m_exciter_type == ExciterType::CONTINUOUS) {
        extract_node_samples(m_exciter_node, m_exciter_node_buffer,
            m_exciter_node_buffer_pos, num_samples);
    }
    if (seg.mode == WaveguideSegment::PropagationMode::UNIDIRECTIONAL) {
        process_unidirectional(seg, num_samples, scratch);
    } else {
        process_bidirectional(seg, num_samples, scratch);
    }
    while (m_audio_buffer_lock.test_and_set(std::memory_order_acquire))
        std::this_thread::yield();
    m_last_audio_buffer.assign(scratch.begin(), scratch.end());
    apply_output_scale();
    m_last_output = m_last_audio_buffer.back();
    m_audio_buffer_lock.clear(std::memory_order_release);
}
References MayaFlux::Nodes::Network::NodeNetwork::apply_output_scale(), CONTINUOUS, MayaFlux::Nodes::Network::NodeNetwork::ensure_initialized(), MayaFlux::Nodes::Network::NodeNetwork::extract_node_samples(), MayaFlux::Nodes::Network::NodeNetwork::is_enabled(), MayaFlux::Nodes::Network::NodeNetwork::m_audio_buffer_lock, m_exciter_node, m_exciter_node_buffer, m_exciter_node_buffer_pos, m_exciter_type, MayaFlux::Nodes::Network::NodeNetwork::m_last_audio_buffer, m_last_output, m_segments, process_bidirectional(), process_unidirectional(), MayaFlux::Nodes::Network::WaveguideNetwork::WaveguideSegment::UNIDIRECTIONAL, and update_mapped_parameters().