MayaFlux: MayaFlux::Nodes::BinaryOpNode::initialize
initialize()
void MayaFlux::Nodes::BinaryOpNode::initialize ()
Initializes the binary operation node.
This method performs any necessary setup for the binary operation node, such as ensuring both input nodes are properly initialized and registered. It should be called before the node is used for processing to ensure correct operation.
Definition at line 63 of file NodeCombine.cpp.
{
    if (!m_is_initialized) {
        if (m_manager) {
            auto self = shared_from_this();
            uint32_t lhs_mask = m_lhs ? m_lhs->get_channel_mask().load() : 0;
            uint32_t rhs_mask = m_rhs ? m_rhs->get_channel_mask().load() : 0;
            uint32_t combined_mask = lhs_mask | rhs_mask;
            if (combined_mask != 0) {
                for (auto& channel : get_active_channels(combined_mask, 0)) {
                    m_manager->add_to_root(self, m_token, channel);
                }
            } else {
                m_manager->add_to_root(self, m_token, 0);
            }
            m_is_initialized = true;
        }
    }
    if (m_manager) {
        auto semantics = m_manager->get_node_config().binary_op_semantics;
        switch (semantics) {
        case NodeBinaryOpSemantics::REPLACE:
            if (m_lhs) {
                for (auto& channel : get_active_channels(m_lhs, 0)) {
                    m_manager->remove_from_root(m_lhs, m_token, channel);
                }
            }
            if (m_rhs) {
                for (auto& channel : get_active_channels(m_rhs, 0)) {
                    m_manager->remove_from_root(m_rhs, m_token, channel);
                }
            }
            break;
        case NodeBinaryOpSemantics::KEEP:
        default:
            break;
        }
    }
}
References MayaFlux::Nodes::NodeGraphManager::add_to_root(), MayaFlux::Nodes::NodeConfig::binary_op_semantics, channel, MayaFlux::Nodes::get_active_channels(), MayaFlux::Nodes::NodeGraphManager::get_node_config(), MayaFlux::Nodes::KEEP, m_is_initialized, m_lhs, m_manager, m_rhs, m_token, MayaFlux::Nodes::NodeGraphManager::remove_from_root(), and MayaFlux::Nodes::REPLACE.
Referenced by process_sample().