MayaFlux: MayaFlux::Core::OscParser::read_blob
read_blob()
std::vector< uint8_t > MayaFlux::Core::OscParser::read_blob (const uint8_t * data, size_t max_len, size_t & offset) static private
Definition at line 45 of file OscParser.cpp.
{
    int32_t blob_size = read_int32(data, offset);
    if (blob_size < 0 || offset + static_cast<size_t>(blob_size) > max_len) {
        return {};
    }
    std::vector<uint8_t> result(data + offset, data + offset + blob_size);
    offset += padded_size(static_cast<size_t>(blob_size));
    return result;
}
References padded_size(), and read_int32().
Referenced by parse().