MayaFlux: MayaFlux::Nodes::GpuSync::PointNode::PointNode
PointNode() [2/3]
MayaFlux::Nodes::GpuSync::PointNode::PointNode (const PointVertex & point) explicit
Create point from PointVertex.
Parameters
point Initial point data
Definition at line 16 of file PointNode.cpp.
    : GeometryWriterNode(0)
    , m_point_vertex(point)
{
    set_vertex_stride(sizeof(PointVertex));
    Kakshya::VertexLayout layout;
    layout.vertex_count = 1;
    layout.stride_bytes = sizeof(PointVertex);
    // Location 0: position
    layout.attributes.push_back(Kakshya::VertexAttributeLayout {
        .component_modality = Kakshya::DataModality::VERTEX_POSITIONS_3D,
        .offset_in_vertex = 0,
        .name = "position" });
    // Location 1: color
    layout.attributes.push_back(Kakshya::VertexAttributeLayout {
        .component_modality = Kakshya::DataModality::VERTEX_COLORS_RGB,
        .offset_in_vertex = sizeof(glm::vec3),
        .name = "color" });
    // Location 2: size
    layout.attributes.push_back(Kakshya::VertexAttributeLayout {
        .component_modality = Kakshya::DataModality::UNKNOWN,
        .offset_in_vertex = sizeof(glm::vec3) + sizeof(glm::vec3),
        .name = "size" });
    set_vertex_layout(layout);
    resize_vertex_buffer(1, false);
    MF_DEBUG(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "Created PointNode at position ({}, {}, {}), color ({}, {}, {}), size {}",
        m_point_vertex.position.x, m_point_vertex.position.y, m_point_vertex.position.z,
        m_point_vertex.color.x, m_point_vertex.color.y, m_point_vertex.color.z, m_point_vertex.size);
}
References MayaFlux::Kakshya::VertexLayout::attributes, MayaFlux::Nodes::GpuSync::PointVertex::color, MayaFlux::Kakshya::VertexAttributeLayout::component_modality, m_point_vertex, MF_DEBUG, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, MayaFlux::Nodes::GpuSync::PointVertex::position, MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_stride(), MayaFlux::Nodes::GpuSync::PointVertex::size, MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Kakshya::UNKNOWN, MayaFlux::Kakshya::VERTEX_COLORS_RGB, MayaFlux::Kakshya::VertexLayout::vertex_count, and MayaFlux::Kakshya::VERTEX_POSITIONS_3D.