MayaFlux: MayaFlux::Nodes::GpuSync::MeshWriterNode::compute_frame
compute_frame()
void MayaFlux::Nodes::GpuSync::MeshWriterNode::compute_frame () override virtual
Compute GPU data for this frame.
Called once per VISUAL_RATE tick. Subclasses populate their respective buffers (pixel_buffer, vertex_buffer, readback_data).
Implements MayaFlux::Nodes::GpuSync::GpuSync.
Definition at line 57 of file MeshWriterNode.cpp.
{
    if (m_vertices.empty()) {
        resize_vertex_buffer(0, false);
        return;
    }
    set_vertices<MeshVertex>(std::span { m_vertices.data(), m_vertices.size() });
    set_indices(std::span { m_indices.data(), m_indices.size() });
    auto layout = Kakshya::VertexLayout::for_meshes(sizeof(MeshVertex));
    layout.vertex_count = static_cast<uint32_t>(m_vertices.size());
    set_vertex_layout(layout);
    MF_TRACE(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "MeshWriterNode: uploaded {} vertices, {} indices ({} faces)",
        m_vertices.size(), m_indices.size(), m_indices.size() / 3);
}
References MayaFlux::Kakshya::VertexLayout::for_meshes(), m_indices, m_vertices, MF_TRACE, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, MayaFlux::Nodes::GpuSync::GeometryWriterNode::resize_vertex_buffer(), MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_indices(), and MayaFlux::Nodes::GpuSync::GeometryWriterNode::set_vertex_layout().