MayaFlux: MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_channel
remove_audio_processor_from_channel()
void MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_channel (const std::shared_ptr< BufferProcessor > & processor, ProcessingToken token, uint32_t channel)
Removes a processor from a specific audio token and channel.
Parameters
processor Processor to remove
token Processing domain
channel Channel index
Definition at line 174 of file BufferProcessingControl.cpp.
{
    if (!m_unit_manager.has_audio_unit(token)) {
        return;
    }
    auto& unit = m_unit_manager.get_audio_unit_mutable(token);
    if (channel >= unit.channel_count) {
        return;
    }
    auto chain = unit.get_chain(channel);
    auto root_buffer = unit.get_buffer(channel);
    chain->remove_processor(processor, root_buffer);
}
References MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootAudioUnit::get_chain(), MayaFlux::Buffers::TokenUnitManager::has_audio_unit(), and m_unit_manager.
Referenced by remove_processor_from_token().