MayaFlux: MayaFlux::Buffers::TextureBindBuffer::setup_processors
setup_processors()
void MayaFlux::Buffers::TextureBindBuffer::setup_processors (Buffers::ProcessingToken token) override virtual
Initialize the buffer and its processors.
Reimplemented from MayaFlux::Buffers::VKBuffer.
Definition at line 35 of file TextureBindBuffer.cpp.
{
    auto self = std::dynamic_pointer_cast<TextureBindBuffer>(shared_from_this());
    m_bindings_processor = std::make_shared<TextureBindingsProcessor>();
    m_bindings_processor->bind_texture_node(
        m_binding_name,
        m_texture_node,
        self);
    set_default_processor(m_bindings_processor);
    auto chain = get_processing_chain();
    if (!chain) {
        chain = std::make_shared<BufferProcessingChain>();
        set_processing_chain(chain);
    }
    chain->set_preferred_token(token);
}
References MayaFlux::Buffers::VKBuffer::get_processing_chain(), m_binding_name, m_bindings_processor, m_texture_node, MayaFlux::Buffers::VKBuffer::set_default_processor(), MayaFlux::Buffers::VKBuffer::set_processing_chain(), and token.