MayaFlux: MayaFlux::Buffers::BufferUploadProcessor::upload_device_local
upload_device_local()
void MayaFlux::Buffers::BufferUploadProcessor::upload_device_local (const std::shared_ptr< VKBuffer > & target, const Kakshya::DataVariant & data) private
Definition at line 60 of file BufferUploadProcessor.cpp.
{
    ensure_staging_buffer(target);
    auto staging_buffer = m_staging_buffers[target];
    Buffers::upload_device_local(target, staging_buffer, data);
}
References ensure_staging_buffer(), m_staging_buffers, and MayaFlux::Buffers::upload_device_local().
Referenced by processing_function().