MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::ensure_initialized
ensure_initialized()
void MayaFlux::Nodes::Network::NodeNetwork::ensure_initialized () protected
Ensure initialize() is called exactly once.
Definition at line 7 of file NodeNetwork.cpp.
{
    if (!m_initialized) {
        initialize();
        m_initialized = true;
    }
}
References initialize(), and m_initialized.
Referenced by MayaFlux::Nodes::Network::ModalNetwork::process_batch(), and MayaFlux::Nodes::Network::WaveguideNetwork::process_batch().