MayaFlux: MayaFlux::Nodes::Network::NodeNetwork::is_enabled
is_enabled()
bool MayaFlux::Nodes::Network::NodeNetwork::is_enabled () const inline
Check if network is enabled.
Definition at line 203 of file NodeNetwork.hpp.
{ return m_enabled; }
Referenced by MayaFlux::Nodes::Network::ModalNetwork::process_batch(), MayaFlux::Nodes::Network::ParticleNetwork::process_batch(), MayaFlux::Nodes::Network::PointCloudNetwork::process_batch(), and MayaFlux::Nodes::Network::WaveguideNetwork::process_batch().