MayaFlux: MayaFlux::Core::HIDBackend::poll_device
poll_device()
void MayaFlux::Core::HIDBackend::poll_device (uint32_t device_id, HIDDeviceState & state) private
Definition at line 410 of file HIDBackend.cpp.
{
    int bytes_read = hid_read_timeout(
        state.handle, state.read_buffer.data(),
        state.read_buffer.size(), m_config.poll_timeout_ms);
    if (bytes_read > 0) {
        std::span<const uint8_t> report(state.read_buffer.data(), bytes_read);
        InputValue value = parse_hid_report(device_id, report);
        notify_input(value);
    } else if (bytes_read < 0) {
        MF_WARN(Journal::Component::Core, Journal::Context::InputBackend,
            "HID read error on device {}", device_id);
        state.active.store(false);
    }
    // bytes_read == 0 means timeout (no data), which is normal
}
References MayaFlux::Core::HIDDeviceState::active, MayaFlux::Journal::Core, MayaFlux::Core::HIDDeviceState::handle, MayaFlux::Journal::InputBackend, m_config, MF_WARN, notify_input(), parse_hid_report(), MayaFlux::Core::HIDBackend::Config::poll_timeout_ms, and MayaFlux::Core::HIDDeviceState::read_buffer.
Referenced by poll_thread_func().