MayaFlux: MayaFlux::Buffers::VKBuffer::get_processing_chain
get_processing_chain()
std::shared_ptr< Buffers::BufferProcessingChain > MayaFlux::Buffers::VKBuffer::get_processing_chain () override virtual
Access the buffer's processing chain.
Returns
Shared pointer to the BufferProcessingChain used for this buffer.
Implements MayaFlux::Buffers::Buffer.
Definition at line 274 of file VKBuffer.cpp.
{
    return m_processing_chain;
}
References m_processing_chain.
Referenced by MayaFlux::Buffers::CompositeGeometryBuffer::add_geometry(), clone_to(), MayaFlux::Buffers::VideoContainerBuffer::setup_processors(), MayaFlux::Buffers::CompositeGeometryBuffer::setup_processors(), MayaFlux::Buffers::GeometryBuffer::setup_processors(), MayaFlux::Buffers::NetworkGeometryBuffer::setup_processors(), MayaFlux::Buffers::NodeTextureBuffer::setup_processors(), MayaFlux::Buffers::TextureBuffer::setup_processors(), MayaFlux::Buffers::GeometryBuffer::setup_rendering(), MayaFlux::Buffers::NetworkGeometryBuffer::setup_rendering(), MayaFlux::Buffers::NodeTextureBuffer::setup_rendering(), and MayaFlux::Buffers::TextureBuffer::setup_rendering().