MayaFlux: MayaFlux::Nodes::Network::ParticleNetwork::process_batch
process_batch()
void MayaFlux::Nodes::Network::ParticleNetwork::process_batch (unsigned int num_samples) override virtual
Process the network for the given number of samples.
Parameters
num_samples Number of samples/frames to process
Subclasses implement their specific processing logic:
Update internal state (physics, relationships, etc.)
Process individual nodes
Apply inter-node interactions
Aggregate outputs if needed
Called by NodeGraphManager during token processing.
Implements MayaFlux::Nodes::Network::NodeNetwork.
Definition at line 85 of file ParticleNetwork.cpp.
{
    ensure_initialized();
    if (!is_enabled()) {
        return;
    }
    update_mapped_parameters();
    for (unsigned int frame = 0; frame < num_samples; ++frame) {
        clear_forces();
        apply_gravity();
        apply_drag();
        if (m_has_attraction_point) {
            apply_attraction_force();
        }
        if (m_topology != Topology::INDEPENDENT) {
            apply_interaction_forces();
        }
        integrate(m_timestep);
        handle_bounds();
    }
    update_point_nodes();
    MF_TRACE(Journal::Component::Nodes, Journal::Context::NodeProcessing,
        "ParticleNetwork processed {} frames, {} particles",
        num_samples, m_particles.size());
}
References apply_attraction_force(), apply_drag(), apply_gravity(), apply_interaction_forces(), clear_forces(), MayaFlux::Nodes::Network::NodeNetwork::ensure_initialized(), handle_bounds(), MayaFlux::Nodes::Network::NodeNetwork::INDEPENDENT, integrate(), MayaFlux::Nodes::Network::NodeNetwork::is_enabled(), m_has_attraction_point, m_particles, m_timestep, MayaFlux::Nodes::Network::NodeNetwork::m_topology, MF_TRACE, MayaFlux::Journal::NodeProcessing, MayaFlux::Journal::Nodes, update_mapped_parameters(), and update_point_nodes().