MayaFlux: MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout
get_vertex_layout()
std::optional< Kakshya::VertexLayout > MayaFlux::Nodes::GpuSync::GeometryWriterNode::get_vertex_layout () const inline
Get cached vertex layout.
Returns
Optional containing layout if set
Definition at line 257 of file GeometryWriterNode.hpp.
{ return m_vertex_layout; }
Referenced by MayaFlux::Nodes::GpuSync::PathGeneratorNode::compute_frame(), MayaFlux::Nodes::GpuSync::PointCollectionNode::compute_frame(), and MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::compute_frame().