MayaFlux: MayaFlux::Core::InputManager::matches_binding
matches_binding()
bool MayaFlux::Core::InputManager::matches_binding (const InputValue & value, const InputBinding & binding) const private
Definition at line 368 of file InputManager.cpp.
{
    if (binding.backend != value.source_type) {
        return false;
    }
    if (binding.device_id != 0 && binding.device_id != value.device_id) {
        return false;
    }
    switch (binding.backend) {
    case InputType::MIDI:
        if (value.type == InputValue::Type::MIDI) {
            const auto& midi = value.as_midi();
            if (binding.midi_channel && *binding.midi_channel != midi.channel()) {
                return false;
            }
            if (binding.midi_message_type && *binding.midi_message_type != midi.type()) {
                return false;
            }
            if (binding.midi_cc_number && midi.type() == 0xB0) {
                if (*binding.midi_cc_number != midi.data1) {
                    return false;
                }
            }
        }
        break;
    case InputType::OSC:
        if (value.type == InputValue::Type::OSC && binding.osc_address_pattern) {
            const auto& osc = value.as_osc();
            if (!osc.address.starts_with(*binding.osc_address_pattern)) {
                return false;
            }
        }
        break;
    default:
        // HID, Serial: no additional filters beyond device_id
        break;
    }
    return true;
}
References MayaFlux::Core::InputValue::as_midi(), MayaFlux::Core::InputValue::as_osc(), MayaFlux::Core::InputBinding::backend, MayaFlux::Core::InputBinding::device_id, MayaFlux::Core::InputValue::device_id, MayaFlux::Core::MIDI, MayaFlux::Core::InputValue::MIDI, MayaFlux::Core::InputBinding::midi_cc_number, MayaFlux::Core::InputBinding::midi_channel, MayaFlux::Core::InputBinding::midi_message_type, MayaFlux::Core::OSC, MayaFlux::Core::InputValue::OSC, MayaFlux::Core::InputBinding::osc_address_pattern, MayaFlux::Core::InputValue::source_type, and MayaFlux::Core::InputValue::type.
Referenced by dispatch_to_nodes().