MayaFlux: MayaFlux::Buffers::ShaderProcessor::update_descriptors
update_descriptors()
void MayaFlux::Buffers::ShaderProcessor::update_descriptors () private
Definition at line 480 of file ShaderProcessor.cpp.
{
    if (m_descriptor_set_ids.empty()) {
        return;
    }
    auto& foundry = Portal::Graphics::get_shader_foundry();
    for (const auto& [descriptor_name, buffer] : m_bound_buffers) {
        auto binding_it = m_config.bindings.find(descriptor_name);
        if (binding_it == m_config.bindings.end()) {
            continue;
        }
        const auto& binding = binding_it->second;
        if (binding.set >= m_descriptor_set_ids.size()) {
            MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Invalid descriptor set index {} for binding '{}'",
                binding.set, descriptor_name);
            continue;
        }
        foundry.update_descriptor_buffer(
            m_descriptor_set_ids[binding.set],
            binding.binding,
            binding.type,
            buffer->get_buffer(),
            0,
            buffer->get_size_bytes());
    }
}
References MayaFlux::Buffers::ShaderProcessorConfig::bindings, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_shader_foundry(), m_bound_buffers, m_config, m_descriptor_set_ids, and MF_ERROR.
Referenced by initialize_descriptors(), and processing_function().