MayaFlux: MayaFlux::Portal::Forma::Inspector::tasks
tasks()
InspectResult MayaFlux::Portal::Forma::Inspector::tasks (Vruta::ProcessingToken token, Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F)
Inspect tasks for a specific processing token.
Same per-task layout as scheduler() but filtered to one token.
Definition at line 105 of file SchedulerQuery.cpp.
{
    const std::string header_label = "TaskScheduler ["
        + std::string(Reflect::enum_to_string(token)) + "]";
    const auto dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), header_label, dims);
    auto root_group = make_value_group({}, std::move(hbuf), {},
        surface, cursor, x_min, x_max, row_h, true);
    InspectResult result;
    result.group = std::move(root_group);
    const auto all = m_sched.get_all_tasks();
    for (const auto& entry : all) {
        if (!entry.routine)
            continue;
        if (entry.routine->get_processing_token() != token)
            continue;
        auto task_result = inspect_task(
            entry, surface, cursor,
            x_min, x_max, row_h);
        result.group.header.attach(surface.layer(), task_result.group.header.header_id);
        result.children.push_back(std::move(task_result));
    }
    return result;
}
References MayaFlux::Reflect::enum_to_string(), MayaFlux::Vruta::TaskScheduler::get_all_tasks(), MayaFlux::Portal::Forma::InspectResult::group, inspect_task(), MayaFlux::Portal::Forma::Surface::layer(), m_sched, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::row_pixel_dims(), and MayaFlux::Portal::Forma::Surface::window().
Referenced by scheduler().