MayaFlux: MayaFlux::Nodes::Network::ResonatorNetwork::update_mapped_parameters
update_mapped_parameters()
void MayaFlux::Nodes::Network::ResonatorNetwork::update_mapped_parameters () private
Apply all registered parameter mappings for the current cycle.
Definition at line 309 of file ResonatorNetwork.cpp.
{
    for (const auto& mapping : m_parameter_mappings) {
        if (mapping.mode == MappingMode::BROADCAST && mapping.broadcast_source) {
            apply_broadcast_parameter(
                mapping.param_name,
                mapping.broadcast_source->get_last_output());
        } else if (mapping.mode == MappingMode::ONE_TO_ONE && mapping.network_source) {
            apply_one_to_one_parameter(mapping.param_name, mapping.network_source);
        }
    }
}
References apply_broadcast_parameter(), apply_one_to_one_parameter(), MayaFlux::Nodes::Network::BROADCAST, m_parameter_mappings, and MayaFlux::Nodes::Network::ONE_TO_ONE.
Referenced by process_batch().