MayaFlux: MayaFlux::Kinesis::SpatialIndex::query_grid
query_grid()
template<typename PointT > void MayaFlux::Kinesis::SpatialIndex< PointT >::query_grid (const SpatialSnapshot< PointT > & snap, const PointT & center, float radius_sq, std::vector< QueryResult > & out) const private
Definition at line 397 of file SpatialIndex.cpp.
{
    auto extent = static_cast<int32_t>(std::ceil(std::sqrt(radius_sq) * m_inv_cell));
    auto check_cell = [&](uint64_t h) {
        auto it = snap.cells.find(h);
        if (it == snap.cells.end()) {
            return;
        }
        for (uint32_t slot : it->second) {
            float d_sq = m_distance_fn(center, snap.positions[slot]);
            if (d_sq <= radius_sq) {
                out.push_back({ snap.slot_to_id[slot], d_sq });
            }
        }
    };
    if constexpr (std::is_same_v<PointT, glm::vec3>) {
        auto [cx, cy, cz] = detail::cell_coords_3d(center, m_inv_cell);
        for (int32_t dx = -extent; dx <= extent; ++dx) {
            for (int32_t dy = -extent; dy <= extent; ++dy) {
                for (int32_t dz = -extent; dz <= extent; ++dz) {
                    check_cell(detail::hash_cell_3d(cx + dx, cy + dy, cz + dz));
                }
            }
        }
    } else {
        uint32_t dims = snap.dimensions;
        std::vector<int32_t> base_cell(dims);
        for (uint32_t d = 0; d < dims; ++d) {
            base_cell[d] = static_cast<int32_t>(std::floor(center(d) * m_inv_cell));
        }
        std::vector<int32_t> offsets(dims, -extent);
        auto advance = [&]() -> bool {
            for (uint32_t d = 0; d < dims; ++d) {
                if (++offsets[d] <= extent) {
                    return true;
                }
                offsets[d] = -extent;
            }
            return false;
        };
        do {
            Eigen::VectorXd probe(dims);
            for (uint32_t d = 0; d < dims; ++d) {
                probe(d) = static_cast<double>(base_cell[d] + offsets[d]) + 0.5;
            }
            check_cell(detail::hash_cell_nd(probe, m_inv_cell));
        } while (advance());
    }
}
References MayaFlux::Kinesis::detail::cell_coords_3d(), MayaFlux::Kinesis::SpatialSnapshot< PointT >::cells, MayaFlux::Kinesis::SpatialSnapshot< PointT >::dimensions, h, MayaFlux::Kinesis::detail::hash_cell_3d(), MayaFlux::Kinesis::detail::hash_cell_nd(), MayaFlux::Kinesis::SpatialSnapshot< PointT >::positions, and MayaFlux::Kinesis::SpatialSnapshot< PointT >::slot_to_id.