MayaFlux: MayaFlux::Buffers::TextBuffer::setup_rendering
setup_rendering()
void MayaFlux::Buffers::TextBuffer::setup_rendering (const RenderConfig & config) override virtual
Delegates to TextureBuffer::setup_rendering, then enables streaming mode on the TextureProcessor and alpha blending on the RenderProcessor.
Parameters
config Same as TextureBuffer::setup_rendering.
Reimplemented from MayaFlux::Buffers::TextureBuffer.
Definition at line 10 of file TextBuffer.cpp.
{
    TextureBuffer::setup_rendering(config);
    if (auto tex_proc = get_texture_processor()) {
        tex_proc->set_streaming_mode(true);
    } else {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::Configuration,
            "TextBuffer missing TextureProcessor during setup_rendering. Ensure the buffer is registered prior to calling setup rendering");
        return;
    }
    get_render_processor()->enable_alpha_blending();
}
References MayaFlux::Journal::Buffers, MayaFlux::Journal::Configuration, MayaFlux::Buffers::TextureBuffer::get_render_processor(), MayaFlux::Buffers::TextureBuffer::get_texture_processor(), MF_RT_ERROR, and MayaFlux::Buffers::TextureBuffer::setup_rendering().