MayaFlux: MayaFlux::Buffers::VKBuffer::infer_dimensions_from_data
infer_dimensions_from_data()
void MayaFlux::Buffers::VKBuffer::infer_dimensions_from_data (size_t byte_count) private
Infer Kakshya::DataDimension entries from a given byte count.
Uses the current modality and provided byte count to populate m_dimensions so processors and UI code can reason about the buffer's layout.
Parameters
byte_count Number of bytes of data to infer dimensions from.
Definition at line 300 of file VKBuffer.cpp.
{
    using namespace Kakshya;
    m_dimensions.clear();
    switch (m_modality) {
    case DataModality::VERTICES_3D: {
        const uint64_t count = byte_count / sizeof(Kakshya::Vertex);
        m_dimensions.push_back(DataDimension::vertex_positions(count));
        m_dimensions.push_back(DataDimension::vertex_colors(count));
        m_dimensions.push_back(DataDimension::grouped("scalar", count, 1, DataDimension::Role::CUSTOM));
        m_dimensions.push_back(DataDimension::texture_coords(count));
        m_dimensions.push_back(DataDimension::vertex_normals(count));
        m_dimensions.push_back(DataDimension::grouped("tangents", count, 3, DataDimension::Role::CUSTOM));
        break;
    }
    case DataModality::VERTEX_POSITIONS_3D: {
        uint64_t count = byte_count / sizeof(glm::vec3);
        m_dimensions.push_back(DataDimension::vertex_positions(count));
        break;
    }
    case DataModality::VERTEX_NORMALS_3D: {
        uint64_t count = byte_count / sizeof(glm::vec3);
        m_dimensions.push_back(DataDimension::vertex_normals(count));
        break;
    }
    case DataModality::TEXTURE_COORDS_2D: {
        uint64_t count = byte_count / sizeof(glm::vec2);
        m_dimensions.push_back(DataDimension::texture_coords(count));
        break;
    }
    case DataModality::VERTEX_COLORS_RGB: {
        uint64_t count = byte_count / sizeof(glm::vec3);
        m_dimensions.push_back(DataDimension::vertex_colors(count, false));
        break;
    }
    case DataModality::VERTEX_COLORS_RGBA: {
        uint64_t count = byte_count / sizeof(glm::vec4);
        m_dimensions.push_back(DataDimension::vertex_colors(count, true));
        break;
    }
    case DataModality::AUDIO_1D: {
        uint64_t samples = byte_count / sizeof(double);
        m_dimensions.push_back(DataDimension::time(samples));
        break;
    }
    default:
        m_dimensions.emplace_back("data", byte_count, 1, DataDimension::Role::CUSTOM);
        break;
    }
}
References count, m_dimensions, and m_modality.
Referenced by resize(), set_data(), set_modality(), and VKBuffer().