MayaFlux: MayaFlux::Portal::Forma::Inspector::event_manager
event_manager()
InspectResult & MayaFlux::Portal::Forma::Inspector::event_manager (Surface & surface, LayoutCursor & cursor, float x_min = -0.95F, float x_max = 0.95F, float row_h = 0.05F)
Inspect the full EventManager state.
Header shows total event count. Each event is a collapsible whose header is the event's registered name, or "(unnamed)" for events added without a name. Body rows expose active state.
Persistent: the first call builds the result against surface and cursor and stores it statically. Subsequent calls return the same result regardless of the supplied surface and cursor; the original window remains the render target. To display on a different surface, the process must be restarted.
Definition at line 47 of file EventQuery.cpp.
{
    const std::vector<ValueSpec> root_values {
        ValueSpec {
            .label = "events",
            .reader = [&m_event_mgr = m_event_mgr] {
                return std::to_string(m_event_mgr.get_all_events().size());
            },
        },
    };
    const auto dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
    auto hbuf = make_row_buffer(surface.window(), "EventManager", dims);
    std::vector<RowBuffer> rbufs;
    rbufs.reserve(root_values.size());
    for (const auto& spec : root_values)
        rbufs.push_back(make_row_buffer(surface.window(), spec.label, dims));
    auto root_group = make_value_group(root_values, std::move(hbuf), rbufs,
        surface, cursor, x_min, x_max, row_h, true);
    InspectResult& result = s_event_result.emplace();
    result.group = std::move(root_group);
    const auto names = m_event_mgr.get_event_names();
    for (const auto& ev : m_event_mgr.get_all_events()) {
        if (!ev)
            continue;
        std::string header_label = "(unnamed)";
        for (const auto& n : names) {
            if (m_event_mgr.get_event(n) == ev) {
                header_label = n;
                break;
            }
        }
        std::vector<ValueSpec> values {
            ValueSpec {
                .label = "active",
                .reader = [ev] { return ev->is_active() ? "true" : "false"; },
            },
        };
        const auto ev_dims = row_pixel_dims(surface.window(), x_min, x_max, row_h);
        auto ev_hbuf = make_row_buffer(surface.window(), header_label, ev_dims);
        std::vector<RowBuffer> ev_rbufs;
        ev_rbufs.reserve(values.size());
        for (const auto& spec : values)
            ev_rbufs.push_back(make_row_buffer(surface.window(), spec.label, ev_dims));
        auto ev_group = make_value_group(values, std::move(ev_hbuf), ev_rbufs,
            surface, cursor, x_min, x_max, row_h, false);
        InspectResult ev_result;
        ev_result.group = std::move(ev_group);
        result.group.header.attach(surface.layer(), ev_result.group.header.header_id);
        result.children.push_back(std::move(ev_result));
    }
    return result;
}
References MayaFlux::Portal::Forma::Collapsible::attach(), MayaFlux::Portal::Forma::InspectResult::children, MayaFlux::Vruta::EventManager::get_all_events(), MayaFlux::Vruta::EventManager::get_event(), MayaFlux::Vruta::EventManager::get_event_names(), MayaFlux::Portal::Forma::InspectResult::group, MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Portal::Forma::Surface::layer(), m_event_mgr, make_row_buffer(), MayaFlux::Portal::Forma::make_value_group(), MayaFlux::Portal::Forma::row_pixel_dims(), s_event_result, and MayaFlux::Portal::Forma::Surface::window().