MayaFlux: MayaFlux::Portal::Graphics::ShaderFoundry::load_shader
load_shader() [2/2]
ShaderID MayaFlux::Portal::Graphics::ShaderFoundry::load_shader (const std::string & content, std::optional< ShaderStage > stage = std::nullopt, const std::string & entry_point = "main")
Universal shader loader - auto-detects source type.
Parameters
content File path, GLSL source string, or SPIR-V path
stage Optional stage override (auto-detected if omitted)
entry_point Entry point function name (default: "main")
Returns
ShaderID, or INVALID_SHADER on failure
Supports:
GLSL files: .comp, .vert, .frag, .geom, .tesc, .tese
SPIR-V files: .spv
Stage auto-detection: .comp → COMPUTE .vert → VERTEX .frag → FRAGMENT .geom → GEOMETRY .tesc → TESS_CONTROL .tese → TESS_EVALUATION .mesh → MESH .task → TASK
Examples: load_shader("shaders/kernel.comp"); // File load_shader("shaders/kernel.spv", COMPUTE); // SPIR-V load_shader("#version 450\nvoid main(){}", COMPUTE); // Source
Definition at line 265 of file ShaderFoundry.cpp.
{
    if (!is_initialized()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "ShaderFoundry not initialized");
        return INVALID_SHADER;
    }
    DetectedSourceType source_type = detect_source_type(content);
    std::string cache_key;
    if (source_type == DetectedSourceType::FILE_GLSL || source_type == DetectedSourceType::FILE_SPIRV) {
        cache_key = content;
    } else {
        cache_key = generate_source_cache_key(content, stage.value_or(ShaderStage::COMPUTE));
    }
    auto id_it = m_shader_filepath_cache.find(cache_key);
    if (id_it != m_shader_filepath_cache.end()) {
        MF_DEBUG(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Using cached shader ID for: {}", cache_key);
        return id_it->second;
    }
    if (!stage.has_value()) {
        if (source_type == DetectedSourceType::FILE_GLSL || source_type == DetectedSourceType::FILE_SPIRV) {
            if (source_type == DetectedSourceType::FILE_SPIRV) {
                std::filesystem::path p(content);
                std::string stem = p.stem().string();
                stage = detect_stage_from_extension(stem);
            } else {
                stage = detect_stage_from_extension(content);
            }
        }
        if (!stage.has_value()) {
            MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
                "Cannot auto-detect shader stage from '{}' - must specify explicitly",
                content);
            return INVALID_SHADER;
        }
    }
    std::shared_ptr<Core::VKShaderModule> shader_module;
    switch (source_type) {
    case DetectedSourceType::FILE_GLSL:
        shader_module = compile_from_file(content, stage, entry_point);
        break;
    case DetectedSourceType::FILE_SPIRV:
        shader_module = compile_from_spirv(content, *stage, entry_point);
        break;
    case DetectedSourceType::SOURCE_STRING:
        shader_module = compile_from_source(content, *stage, entry_point);
        break;
    default:
        MF_ERROR(Journal::Component::Portal, Journal::Context::ShaderCompilation,
            "Cannot determine shader source type");
        return INVALID_SHADER;
    }
    if (!shader_module) {
        return INVALID_SHADER;
    }
    ShaderID id = m_next_shader_id++;
    ShaderState& state = m_shaders[id];
    state.module = shader_module;
    state.filepath = cache_key;
    state.stage = *stage;
    state.entry_point = entry_point;
    m_shader_filepath_cache[cache_key] = id;
    MF_INFO(Journal::Component::Portal, Journal::Context::ShaderCompilation,
        "Shader loaded: {} (ID: {}, stage: {})",
        cache_key, id, static_cast<int>(*stage));
    return id;
}
References compile_from_file(), compile_from_source(), compile_from_spirv(), MayaFlux::Portal::Graphics::COMPUTE, detect_source_type(), detect_stage_from_extension(), MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::entry_point, FILE_GLSL, FILE_SPIRV, MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::filepath, generate_source_cache_key(), MayaFlux::Portal::Graphics::INVALID_SHADER, is_initialized(), m_next_shader_id, m_shader_filepath_cache, m_shaders, MF_DEBUG, MF_ERROR, MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Journal::ShaderCompilation, SOURCE_STRING, and MayaFlux::Portal::Graphics::ShaderFoundry::ShaderState::stage.
Referenced by load_shader(), reload_shader(), and MayaFlux::Buffers::RenderProcessor::RenderProcessor().