MayaFlux: MayaFlux::Nodes::Generator::Impulse::notify_tick
notify_tick()
void MayaFlux::Nodes::Generator::Impulse::notify_tick (double value) override protected virtual
Notifies all registered callbacks about a new sample.
Parameters
value The newly generated sample
This method is called internally whenever a new sample is generated, creating the appropriate context and invoking all registered callbacks that should receive notification about this sample.
Implements MayaFlux::Nodes::Node.
Definition at line 179 of file Impulse.cpp.
{
    update_context(value);
    auto& ctx = get_last_context();
    for (auto& callback : m_callbacks) {
        callback(ctx);
    }
    for (auto& [callback, condition] : m_conditional_callbacks) {
        if (condition(ctx)) {
            callback(ctx);
        }
    }
    if (m_impulse_occurred) {
        for (auto& callback : m_impulse_callbacks) {
            callback(ctx);
        }
    }
}
References MayaFlux::Nodes::Generator::Generator::get_last_context(), MayaFlux::Nodes::Node::m_callbacks, MayaFlux::Nodes::Node::m_conditional_callbacks, m_impulse_callbacks, m_impulse_occurred, and MayaFlux::Nodes::Generator::Generator::update_context().
Referenced by process_sample().