MayaFlux: MayaFlux::Buffers::VKBuffer::clone_to
clone_to() [2/2]
std::shared_ptr< Buffers::VKBuffer > MayaFlux::Buffers::VKBuffer::clone_to (Usage usage)
Create a clone of this buffer with the same data and properties.
Parameters
usage Usage enum for the cloned buffer
Returns
Shared pointer to the cloned VKBuffer
The cloned buffer will have the same size, modality, dimensions, processing chain and default processor as the original. Changes to one buffer after cloning do not affect the other.
Definition at line 368 of file VKBuffer.cpp.
{
    auto buffer = std::make_shared<VKBuffer>(m_size_bytes, usage, m_modality);
    if (auto layout = get_vertex_layout(); layout.has_value()) {
        buffer->set_vertex_layout(layout.value());
    }
    buffer->set_processing_chain(get_processing_chain());
    buffer->set_default_processor(get_default_processor());
    if (is_host_visible()) {
        if (buffer->is_host_visible()) {
            auto src_ptr = static_cast<uint8_t*>(m_resources.mapped_ptr);
            buffer->set_data({ std::vector<uint8_t>(src_ptr, src_ptr + m_size_bytes) });
        } else {
            download_device_local(
                std::dynamic_pointer_cast<VKBuffer>(shared_from_this()),
                buffer,
                nullptr);
        }
    } else {
        if (buffer->is_host_visible()) {
            upload_device_local(
                buffer,
                std::dynamic_pointer_cast<VKBuffer>(shared_from_this()),
                get_data()[0]);
        } else {
            MF_WARN(Journal::Component::Buffers, Journal::Context::BufferManagement,
                "Cloning device-local VKBuffer to another device-local VKBuffer requires external data transfer");
        }
    }
    return buffer;
}
References MayaFlux::Journal::BufferManagement, MayaFlux::Journal::Buffers, MayaFlux::Buffers::download_device_local(), get_data(), get_default_processor(), get_processing_chain(), get_vertex_layout(), is_host_visible(), m_modality, m_resources, m_size_bytes, MayaFlux::Buffers::VKBufferResources::mapped_ptr, MF_WARN, and MayaFlux::Buffers::upload_device_local().