MayaFlux: MayaFlux::Core::VKContext::destroy_surface
destroy_surface()
void MayaFlux::Core::VKContext::destroy_surface (vk::SurfaceKHR surface)
Destroy a specific surface Called when window is unregistered.
Definition at line 104 of file VKContext.cpp.
{
    if (!surface)
        return;
    auto it = std::ranges::find(m_surfaces, surface);
    if (it != m_surfaces.end()) {
        m_instance.get_instance().destroySurfaceKHR(*it);
        m_surfaces.erase(it);
    }
}
References MayaFlux::Core::VKInstance::get_instance(), m_instance, and m_surfaces.
Referenced by MayaFlux::Core::WindowRenderContext::cleanup(), and MayaFlux::Core::BackendWindowHandler::register_window().