MayaFlux: MayaFlux::Buffers::InstanceSSBOProcessor::processing_function
processing_function()
void MayaFlux::Buffers::InstanceSSBOProcessor::processing_function (const std::shared_ptr< Buffer > & buffer) override protected virtual
The core processing function that must be implemented by derived classes.
Parameters
buffer Buffer to process
This method is where the actual transformation logic is implemented. It should contain the algorithmic details of how the buffer's data is transformed, analyzed, or processed. The implementation can utilize any backend capabilities available to the processor, including:
Parallel Processing: Using multi-threading or GPU compute for large datasets
Data Transformations: Applying mathematical operations, filters, or effects
Feature Extraction: Analyzing data characteristics for further processing
Derived classes must override this method to provide specific processing behavior.
Implements MayaFlux::Buffers::BufferProcessor.
Definition at line 66 of file InstanceSSBOProcessor.cpp.
{
    auto vk_buf = std::dynamic_pointer_cast<VKBuffer>(buffer);
    if (!vk_buf || m_network->slot_count() == 0)
        return;
    const auto& slots = m_network->slots();
    if (slots[0].node && slots[0].node->needs_gpu_update())
        upload_template(vk_buf);
    if (any_slot_dirty()) {
        upload_transforms(vk_buf);
        clear_dirty_flags();
    }
    push_ssbo_binding(vk_buf);
}
References any_slot_dirty(), clear_dirty_flags(), m_network, push_ssbo_binding(), upload_template(), and upload_transforms().