MayaFlux: MayaFlux::Buffers::TextureProcessor::create_gpu_texture
create_gpu_texture()
std::shared_ptr< Core::VKImage > MayaFlux::Buffers::TextureProcessor::create_gpu_texture () private
Create VKImage for texture storage.
Definition at line 203 of file TextureProcessor.cpp.
{
    if (!m_texture_buffer) {
        return nullptr;
    }
    auto& loom = Portal::Graphics::get_texture_manager();
    auto texture = loom.create_2d(
        m_texture_buffer->get_width(),
        m_texture_buffer->get_height(),
        m_texture_buffer->get_format(),
        nullptr,
        1);
    if (!texture) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Failed to create GPU texture via TextureLoom");
    }
    MF_INFO(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "TextureProcessor: created GPU VKImage {}x{}",
        m_texture_buffer->get_width(), m_texture_buffer->get_height());
    return texture;
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::get_texture_manager(), m_texture_buffer, and MF_INFO.
Referenced by initialize_gpu_resources(), and update_pixels_if_dirty().