MayaFlux: MayaFlux::Nodes::ChainNode::process_sample
process_sample()
double MayaFlux::Nodes::ChainNode::process_sample (double input = 0.) override virtual
Processes a single sample through the chain.
Parameters
input The input sample
Returns
The output after processing through both nodes
The input is first processed by the source node, and the result is then processed by the target node.
Implements MayaFlux::Nodes::Node.
Definition at line 64 of file NodeStructure.cpp.
{
    if (!m_Source || !m_Target) {
        return input;
    }
    if (!is_initialized())
        initialize();
    atomic_inc_modulator_count(m_Source->m_modulator_count, 1);
    atomic_inc_modulator_count(m_Target->m_modulator_count, 1);
    m_last_output = input;
    uint32_t sstate = m_Source->m_state.load();
    if (sstate & NodeState::PROCESSED) {
        m_last_output = input + m_Source->get_last_output();
    } else {
        m_last_output = m_Source->process_sample(input);
        atomic_add_flag(m_Source->m_state, NodeState::PROCESSED);
    }
    uint32_t tstate = m_Target->m_state.load();
    if (tstate & NodeState::PROCESSED) {
        m_last_output += m_Target->get_last_output();
    } else {
        m_last_output = m_Target->process_sample(m_last_output);
        tstate = tstate | NodeState::PROCESSED;
        atomic_add_flag(m_Target->m_state, NodeState::PROCESSED);
    }
    atomic_dec_modulator_count(m_Source->m_modulator_count, 1);
    atomic_dec_modulator_count(m_Target->m_modulator_count, 1);
    try_reset_processed_state(m_Source);
    try_reset_processed_state(m_Target);
    return m_last_output;
}
References MayaFlux::Nodes::atomic_add_flag(), MayaFlux::Nodes::atomic_dec_modulator_count(), MayaFlux::Nodes::atomic_inc_modulator_count(), initialize(), is_initialized(), MayaFlux::Nodes::Node::m_last_output, m_Source, m_Target, MayaFlux::Nodes::PROCESSED, and MayaFlux::Nodes::try_reset_processed_state().
Referenced by process_batch().