MayaFlux: MayaFlux::Core::VKContext::create_surface
create_surface()
vk::SurfaceKHR MayaFlux::Core::VKContext::create_surface (std::shared_ptr< Window > window)
Create surface from window's native handles.
Parameters
window Window to create surface for
Returns
Surface handle, or null on failure
Definition at line 73 of file VKContext.cpp.
{
    if (!window) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot create surface: null window");
        return nullptr;
    }
#if defined(GLFW_BACKEND)
    auto* glfw_window = dynamic_cast<GlfwWindow*>(window.get());
    if (!glfw_window) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot create surface: window is not a GlfwWindow");
        return nullptr;
    }
    GLFWwindow* glfw_handle = glfw_window->get_glfw_handle();
    if (!glfw_handle) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Cannot create surface: null GLFW handle");
        return nullptr;
    }
    VkSurfaceKHR c_surface {};
    VkResult result = Parallel::dispatch_main_sync([&]() {
        return glfwCreateWindowSurface(
            static_cast<VkInstance>(m_instance.get_instance()),
            glfw_handle,
            nullptr,
            &c_surface);
    });
    if (result != VK_SUCCESS) {
        MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Failed to create GLFW window surface for window '{}'",
            window->get_create_info().title);
        return nullptr;
    }
    vk::SurfaceKHR surface(c_surface);
    m_surfaces.push_back(surface);
    MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "Surface created for window '{}'", window->get_create_info().title);
    return surface;
#elif defined(WIN32_BACKEND)
    if (m_graphics_config.windowing_backend == GlobalGraphicsConfig::WindowingBackend::WINDOWS) {
        auto hwnd = static_cast<HWND>(window->get_native_handle());
        if (!hwnd) {
            MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Cannot create surface: null HWND");
            return nullptr;
        }
        VkWin32SurfaceCreateInfoKHR info {};
        info.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
        info.hinstance = GetModuleHandleW(nullptr);
        info.hwnd = hwnd;
        VkSurfaceKHR c_surface {};
        if (vkCreateWin32SurfaceKHR(
                static_cast<VkInstance>(m_instance.get_instance()),
                &info, nullptr, &c_surface)
            != VK_SUCCESS) {
            MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Failed to create Win32 Vulkan surface for window '{}'",
                window->get_create_info().title);
            return nullptr;
        }
        vk::SurfaceKHR surface(c_surface);
        m_surfaces.push_back(surface);
        MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Win32 surface created for window '{}'", window->get_create_info().title);
        return surface;
    }
#elif defined(WAYLAND_BACKEND)
    {
        auto* wl_display = static_cast<struct wl_display*>(window->get_native_display());
        auto* wl_surface = static_cast<struct wl_surface*>(window->get_native_handle());
        if (!wl_display || !wl_surface) {
            MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Cannot create surface: null Wayland display or surface handle");
            return nullptr;
        }
        VkWaylandSurfaceCreateInfoKHR info {};
        info.sType = VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR;
        info.display = wl_display;
        info.surface = wl_surface;
        VkSurfaceKHR c_surface {};
        if (vkCreateWaylandSurfaceKHR(
                static_cast<VkInstance>(m_instance.get_instance()),
                &info, nullptr, &c_surface)
            != VK_SUCCESS) {
            MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
                "Failed to create Wayland Vulkan surface for window '{}'",
                window->get_create_info().title);
            return nullptr;
        }
        vk::SurfaceKHR surface(c_surface);
        m_surfaces.push_back(surface);
        MF_INFO(Journal::Component::Core, Journal::Context::GraphicsBackend,
            "Wayland surface created for window '{}'", window->get_create_info().title);
        return surface;
    }
#endif
    MF_ERROR(Journal::Component::Core, Journal::Context::GraphicsBackend,
        "No windowing backend available for surface creation");
    return nullptr;
}
References MayaFlux::Journal::Core, MayaFlux::Parallel::dispatch_main_sync(), MayaFlux::Core::VKInstance::get_instance(), MayaFlux::Journal::GraphicsBackend, m_graphics_config, m_instance, m_surfaces, MF_ERROR, MF_INFO, MayaFlux::Core::GlobalGraphicsConfig::windowing_backend, and MayaFlux::Core::GlobalGraphicsConfig::WINDOWS.
Referenced by MayaFlux::Core::BackendWindowHandler::register_window().