MayaFlux: MayaFlux::Portal::Graphics::ComputePress::instance
instance()
static ComputePress & MayaFlux::Portal::Graphics::ComputePress::instance () inline static
Definition at line 26 of file ComputePress.hpp.
    {
        static ComputePress press;
        return press;
    }
Referenced by MayaFlux::Portal::Graphics::get_compute_press(), MayaFlux::Portal::Graphics::initialize(), MayaFlux::Portal::Graphics::shutdown(), and MayaFlux::Portal::Graphics::stop().