MayaFlux: MayaFlux::Nodes::NodeGraphManager::cleanup_completed_routing
cleanup_completed_routing()
void MayaFlux::Nodes::NodeGraphManager::cleanup_completed_routing (ProcessingToken token)
Cleans up completed routing transitions for a given token.
Parameters
token Processing domain to clean up routing for
This method should be called after routing states have been updated to remove any nodes or networks that have completed their fade-out transitions and are no longer contributing to the output of their previous channels.
Definition at line 776 of file NodeGraphManager.cpp.
{
    std::vector<std::pair<std::shared_ptr<Node>, uint32_t>> nodes_to_remove;
    for (const auto& [id, node] : m_Node_registry) {
        if (!node->needs_channel_routing())
            continue;
        auto& state = node->get_routing_state();
        if (state.phase == RoutingState::COMPLETED) {
            for (uint32_t ch = 0; ch < 32; ch++) {
                if ((state.from_channels & (1 << ch)) && !(state.to_channels & (1 << ch))) {
                    nodes_to_remove.emplace_back(node, ch);
                }
            }
            state = RoutingState {};
        }
    }
    for (auto& [node, channel] : nodes_to_remove) {
        remove_from_root(node, token, channel);
    }
    std::vector<std::pair<std::shared_ptr<Network::NodeNetwork>, uint32_t>> networks_to_cleanup;
    for (const auto& network : get_all_networks(token)) {
        if (!network || !network->needs_channel_routing())
            continue;
        auto& state = network->get_routing_state();
        if (state.phase == RoutingState::COMPLETED) {
            network->set_channel_mask(state.to_channels);
            for (uint32_t ch = 0; ch < 32; ch++) {
                if ((state.from_channels & (1 << ch)) && !(state.to_channels & (1 << ch))) {
                    networks_to_cleanup.emplace_back(network, ch);
                }
            }
            state = RoutingState {};
        }
    }
    for (auto& [network, channel] : networks_to_cleanup) {
        network->remove_channel_usage(channel);
        if (network->get_channel_mask() == 0) {
            auto& networks = m_audio_networks[token];
            std::erase_if(networks, [&](const auto& n) { return n == network; });
            unregister_network_global(network);
        }
    }
}
References channel, MayaFlux::Nodes::RoutingState::COMPLETED, get_all_networks(), m_audio_networks, m_Node_registry, remove_from_root(), and unregister_network_global().