MayaFlux: MayaFlux::Buffers::DataWriteProcessor::upload_vertex
upload_vertex()
void MayaFlux::Buffers::DataWriteProcessor::upload_vertex (const std::shared_ptr< VKBuffer > & vk, std::vector< Kakshya::DataVariant > & slots) private
Definition at line 211 of file DataWriteProcessor.cpp.
{
    std::optional<Kakshya::VertexAccess> access;
    switch (m_topology) {
    case Portal::Graphics::PrimitiveTopology::LINE_LIST:
    case Portal::Graphics::PrimitiveTopology::LINE_STRIP:
        access = Kakshya::as_line_vertex_access(slots);
        break;
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST:
    case Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP:
        access = Kakshya::as_mesh_vertex_access(slots);
        break;
    default:
        access = Kakshya::as_point_vertex_access(slots);
        break;
    }
    if (!access) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "DataWriteProcessor: vertex access failed for modality {}",
            Kakshya::modality_to_string(m_modality));
        return;
    }
    ensure_capacity(vk, access->byte_count);
    upload_to_gpu(access->data_ptr, access->byte_count, vk, m_staging);
    vk->set_vertex_layout(access->layout);
}
References MayaFlux::Kakshya::as_line_vertex_access(), MayaFlux::Kakshya::as_mesh_vertex_access(), MayaFlux::Kakshya::as_point_vertex_access(), MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, ensure_capacity(), MayaFlux::Portal::Graphics::LINE_LIST, MayaFlux::Portal::Graphics::LINE_STRIP, m_modality, m_staging, m_topology, MF_RT_ERROR, MayaFlux::Kakshya::modality_to_string(), MayaFlux::Portal::Graphics::TRIANGLE_LIST, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, and MayaFlux::Buffers::upload_to_gpu().
Referenced by upload_primary().