MayaFlux: MayaFlux::Kakshya::DynamicSoundStream::ensure_capacity
ensure_capacity()
void MayaFlux::Kakshya::DynamicSoundStream::ensure_capacity (uint64_t required_frames)
Pre-allocate capacity for the specified number of frames.
Essential for real-time scenarios where allocation delays are unacceptable.
Parameters
required_frames Minimum number of frames the container should hold
Definition at line 308 of file DynamicSoundStream.cpp.
{
    if (uint64_t current_frames = get_total_elements() / get_num_channels();
        required_frames > current_frames) {
        expand_to(required_frames);
    }
}
References expand_to(), MayaFlux::Kakshya::SoundStreamContainer::get_num_channels(), and MayaFlux::Kakshya::SoundStreamContainer::get_total_elements().
Referenced by enable_circular_buffer().