MayaFlux: MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers
terminate_active_buffers()
void MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers ()
Terminates all active Audio and VK buffers.
Definition at line 347 of file BufferAccessControl.cpp.
{
    for (const auto& token : m_unit_manager.get_active_audio_tokens()) {
        auto& unit = m_unit_manager.get_audio_unit_mutable(token);
        for (uint32_t channel = 0; channel < unit.channel_count; ++channel) {
            auto root_buffer = unit.get_buffer(channel);
            root_buffer->clear();
            for (auto& child : root_buffer->get_child_buffers()) {
                if (child)
                    child->clear();
            }
            unit.root_buffers[channel].reset();
        }
    }
    for (const auto& token : m_unit_manager.get_active_graphics_tokens()) {
        auto& unit = m_unit_manager.get_graphics_unit_mutable(token);
        auto root_buffer = unit.get_buffer();
        root_buffer->clear();
        for (auto& child : root_buffer->get_child_buffers()) {
            if (child) {
                remove_graphics_buffer(child, token);
                child->clear();
            }
        }
        unit.root_buffer.reset();
    }
}
References MayaFlux::Buffers::TokenUnitManager::get_active_audio_tokens(), MayaFlux::Buffers::TokenUnitManager::get_active_graphics_tokens(), MayaFlux::Buffers::TokenUnitManager::get_audio_unit_mutable(), MayaFlux::Buffers::RootGraphicsUnit::get_buffer(), MayaFlux::Buffers::RootAudioUnit::get_buffer(), MayaFlux::Buffers::TokenUnitManager::get_graphics_unit_mutable(), m_unit_manager, and remove_graphics_buffer().