MayaFlux: MayaFlux::IO::SoundFileReader::open_from_demux
open_from_demux()
bool MayaFlux::IO::SoundFileReader::open_from_demux (std::shared_ptr< FFmpegDemuxContext > demux, std::shared_ptr< AudioStreamContext > audio, const std::string & filepath, FileReadOptions options = FileReadOptions::ALL)
Open an audio stream from an already-constructed demux and stream context.
Secondary open path for callers that have already probed the demuxer and opened an AudioStreamContext (e.g. VideoFileReader sharing its m_demux and m_audio). No avformat_open_input or AudioStreamContext::open is performed — both contexts are adopted as-is.
The filepath is required only for filesystem-level metadata (file_size, modification_time) populated during build_metadata. It must point to the same file already open in the demux context. Pass an empty string only if FileReadOptions::EXTRACT_METADATA is not set.
All subsequent SoundFileReader operations — metadata, regions, read_all, load_into_container — behave identically to the filepath-based open().
Both contexts must remain valid for the lifetime of this reader.
Parameters
demux Shared, already-open demux context.
audio Shared, already-open and valid audio stream context.
filepath Path to the source file (used for filesystem metadata only).
options File read options (metadata, regions, etc.).
Returns
True if both contexts are valid and setup succeeded.
Definition at line 126 of file SoundFileReader.cpp.
{
    std::unique_lock<std::shared_mutex> lock(m_context_mutex);
    m_demux.reset();
    m_audio.reset();
    m_current_frame_position = 0;
    {
        std::lock_guard<std::mutex> ml(m_metadata_mutex);
        m_cached_metadata.reset();
        m_cached_regions.clear();
    }
    clear_error();
    if (!demux || !demux->is_open()) {
        set_error("open_from_demux: demux context is null or not open");
        return false;
    }
    if (!audio || !audio->is_valid()) {
        set_error("open_from_demux: audio stream context is null or not valid");
        return false;
    }
    m_filepath = filepath;
    m_demux = std::move(demux);
    m_audio = std::move(audio);
    if ((options & FileReadOptions::EXTRACT_METADATA) != FileReadOptions::NONE)
        build_metadata(m_demux, m_audio);
    if ((options & FileReadOptions::EXTRACT_REGIONS) != FileReadOptions::NONE)
        build_regions(m_demux, m_audio);
    return true;
}
References build_metadata(), build_regions(), clear_error(), MayaFlux::IO::EXTRACT_METADATA, MayaFlux::IO::EXTRACT_REGIONS, m_audio, m_cached_metadata, m_cached_regions, m_context_mutex, m_current_frame_position, m_demux, m_filepath, m_metadata_mutex, MayaFlux::IO::NONE, and set_error().
Referenced by MayaFlux::IO::VideoFileReader::load_into_container().