MayaFlux: MayaFlux::Buffers::DescriptorBindingsProcessor::create_descriptor_buffer
create_descriptor_buffer()
std::shared_ptr< VKBuffer > MayaFlux::Buffers::DescriptorBindingsProcessor::create_descriptor_buffer (size_t size, Portal::Graphics::DescriptorRole role) private
Create GPU buffer for a descriptor binding.
Definition at line 672 of file DescriptorBindingsProcessor.cpp.
{
    VKBuffer::Usage usage {};
    if (role == Portal::Graphics::DescriptorRole::UNIFORM) {
        usage = VKBuffer::Usage::UNIFORM;
    } else { // SSBO
        usage = VKBuffer::Usage::COMPUTE;
    }
    auto buffer = std::make_shared<VKBuffer>(
        size,
        usage,
        Kakshya::DataModality::UNKNOWN);
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "create_descriptor_buffer requires a valid BufferService");
    }
    buffer_service->initialize_buffer(buffer);
    return buffer;
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Buffers::VKBuffer::COMPUTE, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), size, MayaFlux::Buffers::VKBuffer::UNIFORM, MayaFlux::Portal::Graphics::UNIFORM, and MayaFlux::Kakshya::UNKNOWN.
Referenced by bind_audio_buffer(), bind_host_vk_buffer(), bind_matrix_node(), bind_network(), bind_scalar_node(), bind_structured_node(), and bind_vector_node().