MayaFlux: main
main()
int main (int argc, char ** argv)
Main entry point for the Lila server binary.
Parameters
argc Argument count
argv Argument vector
Returns
Exit code
Definition at line 95 of file lila_server.cpp.
{
    int port = 9090;
    bool verbose = false;
    Lila::LogLevel log_level = Lila::LogLevel::INFO;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") {
            print_usage(argv[0]);
            return 0;
        }
        if (arg == "-p" || arg == "--port") {
            if (i + 1 < argc) {
                port = std::atoi(argv[++i]);
                if (port <= 0 || port > 65535) {
                    std::cerr << "Error: Invalid port number\n";
                    return 1;
                }
            } else {
                std::cerr << "Error: --port requires an argument\n";
                return 1;
            }
        } else if (arg == "-v" || arg == "--verbose") {
            verbose = true;
        } else if (arg == "-l" || arg == "--level") {
            if (i + 1 < argc) {
                log_level = parse_log_level(argv[++i]);
            } else {
                std::cerr << "Error: --level requires an argument\n";
                return 1;
            }
        } else {
            std::cerr << "Error: Unknown option '" << arg << "'\n";
            print_usage(argv[0]);
            return 1;
        }
    }
    auto& logger = Lila::Commentator::instance();
    logger.set_level(log_level);
    logger.set_verbose(verbose);
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);
    LILA_INFO(Lila::Emitter::SYSTEM, "Starting Lila live coding server");
    LILA_INFO(Lila::Emitter::SYSTEM, std::string("Port: ") + std::to_string(port));
    std::string level_str;
    switch (log_level) {
    case Lila::LogLevel::TRACE:
        level_str = "TRACE";
        break;
    case Lila::LogLevel::DEBUG:
        level_str = "DEBUG";
        break;
    case Lila::LogLevel::INFO:
        level_str = "INFO";
        break;
    case Lila::LogLevel::WARN:
        level_str = "WARN";
        break;
    case Lila::LogLevel::ERROR:
        level_str = "ERROR";
        break;
    case Lila::LogLevel::FATAL:
        level_str = "FATAL";
        break;
    default:
        level_str = "UNKNOWN";
        break;
    }
    LILA_INFO(Lila::Emitter::SYSTEM, std::string("Log level: ") + level_str);
    if (verbose) {
        LILA_INFO(Lila::Emitter::SYSTEM, "Verbose mode enabled");
    }
    Lila::Lila playground;
    if (!playground.initialize(Lila::OperationMode::Server, port)) {
        LILA_FATAL(Lila::Emitter::SYSTEM,
            std::string("Failed to initialize: ") + playground.get_last_error());
        return 1;
    }
    playground.on_server_started([]() {
        std::cout << "LILA_SERVER_READY\n"
                  << std::flush;
        LILA_INFO(Lila::Emitter::SYSTEM, "Server is ready to accept connections");
    });
    playground.on_success([]() {
        LILA_INFO(Lila::Emitter::GENERAL, "Code evaluation succeeded");
    });
    /*
    playground.on_error([](const std::string& error) {
        LILA_ERROR(Lila::Emitter::GENERAL,
            std::string("Evaluation error: ") + error);
    });
    */
    playground.on_server_client_connected([](const Lila::ClientInfo& client) {
        LILA_INFO(Lila::Emitter::SERVER,
            std::string("New client connection (fd: ") + std::to_string(client.fd) + ", session: " + (client.session_id.empty() ? "none" : client.session_id) + ")");
    });
    playground.on_server_client_disconnected([](const Lila::ClientInfo& client) {
        LILA_INFO(Lila::Emitter::SERVER,
            std::string("Client disconnected (fd: ") + std::to_string(client.fd) + ", session: " + (client.session_id.empty() ? "none" : client.session_id) + ")");
    });
    LILA_INFO(Lila::Emitter::SYSTEM, "Server running. Press Ctrl+C to stop.");
    playground.await_shutdown(&g_running);
    LILA_INFO(Lila::Emitter::SYSTEM, "Shutting down...");
    playground.stop_server();
    LILA_INFO(Lila::Emitter::SYSTEM, "Goodbye!");
    return 0;
}
References Lila::Lila::await_shutdown(), Lila::ClientInfo::fd, g_running, Lila::Lila::get_last_error(), Lila::Lila::initialize(), Lila::Commentator::instance(), LILA_FATAL, LILA_INFO, Lila::Lila::on_server_client_connected(), Lila::Lila::on_server_client_disconnected(), Lila::Lila::on_server_started(), Lila::Lila::on_success(), parse_log_level(), print_usage(), Lila::ClientInfo::session_id, signal_handler(), and Lila::Lila::stop_server().