MayaFlux: initialize
initialize()
void initialize ()
Definition at line 11 of file main.cpp.
{
#ifdef HAS_USER_PROJECT
    try {
        settings();
    } catch (const std::exception& e) {
        MF_ERROR(MayaFlux::Journal::Component::USER, MayaFlux::Journal::Context::Init, "Error during user initialization: {}", e.what());
    }
#endif
}
References MayaFlux::Journal::Init, MF_ERROR, and MayaFlux::Journal::USER.
Referenced by MayaFlux::Vruta::TaskScheduler::add_task(), MayaFlux::Portal::Graphics::initialize(), main(), and MayaFlux::schedule_task().