MayaFlux: main
main()
int main ()
Definition at line 33 of file main.cpp.
{
    try {
        MF_PRINT(MayaFlux::Journal::Component::USER, MayaFlux::Journal::Context::Init, "=== MayaFlux Creative Coding Framework ===");
        MF_PRINT(MayaFlux::Journal::Component::USER, MayaFlux::Journal::Context::Init,
            "Version: {}.{}.{}", MAYAFLUX_VERSION_MAJOR, MAYAFLUX_VERSION_MINOR, MAYAFLUX_VERSION_PATCH);
        MF_PRINT(MayaFlux::Journal::Component::USER, MayaFlux::Journal::Context::Init, "");
        initialize();
        MayaFlux::Init();
        MayaFlux::Start();
        MF_PRINT(Journal::Component::USER, Journal::Context::Init, "=== AudioVisual Processing Active ===");
        run();
        std::cout << "Press Enter [Return] to stop...\n";
        MayaFlux::Await();
        MayaFlux::End();
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::flush;
        return 1;
    }
    return 0;
}
References MayaFlux::Await(), MayaFlux::End(), MayaFlux::Init(), MayaFlux::Journal::Init, initialize(), MF_PRINT, run(), MayaFlux::Start(), and MayaFlux::Journal::USER.