MayaFlux: MayaFlux::Kakshya::safe_copy_data_variant
safe_copy_data_variant()
void MayaFlux::Kakshya::safe_copy_data_variant (const DataVariant & input, DataVariant & output)
Safely copy data from a DataVariant to another DataVariant, handling type conversion.
Parameters
input Source DataVariant.
output Destination DataVariant.
Definition at line 34 of file DataUtils.cpp.
{
    std::visit([&](const auto& input_vec, auto& output_vec) {
        using InputType = typename std::decay_t<decltype(input_vec)>::value_type;
        using OutputType = typename std::decay_t<decltype(output_vec)>::value_type;
        if constexpr (ProcessableData<InputType> && ProcessableData<OutputType>) {
            std::vector<OutputType> temp_storage;
            auto input_span = extract_from_variant<OutputType>(input, temp_storage);
            output_vec.resize(input_span.size());
            std::copy(input_span.begin(), input_span.end(), output_vec.begin());
        } else {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "Unsupported type conversion from {} to {}",
                typeid(InputType).name(),
                typeid(OutputType).name());
        }
    },
        input, output);
}
References MayaFlux::Journal::Kakshya, and MayaFlux::Journal::Runtime.
Referenced by MayaFlux::Kakshya::ContiguousAccessProcessor::process(), MayaFlux::Kakshya::RegionOrganizationProcessor::process_region_segment(), and MayaFlux::Kakshya::DynamicSoundStream::set_all_data().