MayaFlux: MayaFlux::Yantra::infer_from_container
infer_from_container()
std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_from_container (const std::shared_ptr< Kakshya::SignalSourceContainer > & container)
Infer structure from SignalSourceContainer.
Definition at line 29 of file StructureIntrospection.cpp.
{
    if (!container) {
        throw std::invalid_argument("Cannot infer structure from null container");
    }
    const auto& structure = container->get_structure();
    auto dimensions = structure.dimensions;
    auto modality = structure.modality;
    if (modality == Kakshya::DataModality::UNKNOWN) {
        modality = Kakshya::detect_data_modality(dimensions);
    }
    if (dimensions.empty()) {
        auto total_elements = structure.get_total_elements();
        if (total_elements > 0) {
            dimensions.emplace_back(Kakshya::DataDimension::time(total_elements));
            modality = Kakshya::DataModality::AUDIO_1D;
        }
    }
    return std::make_pair(std::move(dimensions), modality);
}
References MayaFlux::Kakshya::AUDIO_1D, MayaFlux::Kakshya::detect_data_modality(), MayaFlux::Kakshya::DataDimension::time(), and MayaFlux::Kakshya::UNKNOWN.
Referenced by infer_from_region(), and infer_structure().