MayaFlux: MayaFlux::Portal::Graphics::shutdown
shutdown()
MAYAFLUX_API void MayaFlux::Portal::Graphics::shutdown ()
Shutdown Portal::Graphics subsystem.
Destroys all pipelines, shaders, and resources. Must be called AFTER stop().
Definition at line 87 of file Graphics.cpp.
{
    if (!g_initialized) {
        return;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Shutting down Portal::Graphics...");
    RenderFlow::instance().shutdown();
    ComputePress::instance().shutdown();
    ShaderFoundry::instance().shutdown();
    SamplerForge::instance().shutdown();
    TextureLoom::instance().shutdown();
    g_initialized = false;
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Portal::Graphics shutdown complete");
}
References MayaFlux::Journal::API, MayaFlux::Portal::Graphics::ComputePress::instance(), MayaFlux::Portal::Graphics::RenderFlow::instance(), MayaFlux::Portal::Graphics::SamplerForge::instance(), MayaFlux::Portal::Graphics::ShaderFoundry::instance(), MayaFlux::Portal::Graphics::TextureLoom::instance(), MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Portal::Graphics::ComputePress::shutdown(), MayaFlux::Portal::Graphics::RenderFlow::shutdown(), MayaFlux::Portal::Graphics::SamplerForge::shutdown(), MayaFlux::Portal::Graphics::ShaderFoundry::shutdown(), and MayaFlux::Portal::Graphics::TextureLoom::shutdown().
Referenced by MayaFlux::Portal::Graphics::SamplerForge::operator=(), MayaFlux::Core::GraphicsSubsystem::shutdown(), MayaFlux::Portal::Graphics::ComputePress::~ComputePress(), MayaFlux::Portal::Graphics::RenderFlow::~RenderFlow(), MayaFlux::Portal::Graphics::SamplerForge::~SamplerForge(), MayaFlux::Portal::Graphics::ShaderFoundry::~ShaderFoundry(), and MayaFlux::Portal::Graphics::TextureLoom::~TextureLoom().