MayaFlux: MayaFlux::Portal::Graphics::get_compute_press
get_compute_press()
MAYAFLUX_API ComputePress & MayaFlux::Portal::Graphics::get_compute_press () inline
Definition at line 144 of file ComputePress.hpp.
{
    return ComputePress::instance();
}
References MayaFlux::Portal::Graphics::ComputePress::instance().
Referenced by MayaFlux::Buffers::ShaderProcessor::cleanup(), MayaFlux::Yantra::GpuResourceManager::cleanup(), MayaFlux::Buffers::ComputeProcessor::cleanup(), MayaFlux::Yantra::GpuResourceManager::dispatch(), MayaFlux::Yantra::GpuResourceManager::dispatch_batched(), MayaFlux::Buffers::ComputeProcessor::execute_shader(), MayaFlux::Yantra::GpuResourceManager::initialise(), MayaFlux::Buffers::ComputeProcessor::initialize_descriptors(), and MayaFlux::Buffers::ComputeProcessor::initialize_pipeline().