MayaFlux: MayaFlux::Kinesis::generate_proximity_graph
generate_proximity_graph()
EdgeList MayaFlux::Kinesis::generate_proximity_graph (const Eigen::MatrixXd & points, const ProximityConfig & config)
Generate proximity graph using specified mode.
Parameters
points DxN matrix where each column is a point
config Configuration specifying mode and parameters
Returns
Edge list
Definition at line 308 of file ProximityGraphs.cpp.
{
    switch (config.mode) {
    case ProximityMode::SEQUENTIAL:
        return sequential_chain(points);
    case ProximityMode::K_NEAREST:
        return k_nearest_neighbors(points, config.k_neighbors);
    case ProximityMode::RADIUS_THRESHOLD:
        return radius_threshold_graph(points, config.radius);
    case ProximityMode::MINIMUM_SPANNING_TREE:
        return minimum_spanning_tree(points);
    case ProximityMode::GABRIEL_GRAPH:
        return gabriel_graph(points);
    case ProximityMode::NEAREST_NEIGHBOR:
        return nearest_neighbor_graph(points);
    case ProximityMode::RELATIVE_NEIGHBORHOOD_GRAPH:
        return relative_neighborhood_graph(points);
    case ProximityMode::CUSTOM:
        return custom_proximity_graph(points, config.custom_function);
    default:
        return {};
    }
}
References CUSTOM, MayaFlux::Kinesis::ProximityConfig::custom_function, custom_proximity_graph(), gabriel_graph(), GABRIEL_GRAPH, K_NEAREST, k_nearest_neighbors(), MayaFlux::Kinesis::ProximityConfig::k_neighbors, minimum_spanning_tree(), MINIMUM_SPANNING_TREE, MayaFlux::Kinesis::ProximityConfig::mode, NEAREST_NEIGHBOR, nearest_neighbor_graph(), MayaFlux::Kinesis::ProximityConfig::radius, RADIUS_THRESHOLD, radius_threshold_graph(), relative_neighborhood_graph(), RELATIVE_NEIGHBORHOOD_GRAPH, SEQUENTIAL, and sequential_chain().
Referenced by MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::regenerate_topology().