MayaFlux: MayaFlux::Yantra::Granular::make_granular_context
make_granular_context() [1/3]
ExecutionContext MayaFlux::Yantra::Granular::make_granular_context (const GranularConfig & config, AnalysisType analysis_type, const std::string & qualifier = {}) inline
Construct an ExecutionContext for the granular pipeline using a built-in AnalysisType.
Parameters
config Pipeline scalar parameters.
analysis_type Attribution category. Supported: FEATURE, STATISTICAL.
qualifier Scalar to extract. Empty uses type default.
Returns
Populated ExecutionContext.
Definition at line 309 of file GranularWorkflow.hpp.
                                 {})
{
    ExecutionContext ctx;
    ctx.execution_metadata["grain_size"] = config.grain_size;
    ctx.execution_metadata["hop_size"] = config.hop_size;
    ctx.execution_metadata["channel"] = config.channel;
    ctx.execution_metadata["feature_key"] = config.feature_key;
    ctx.execution_metadata["ascending"] = config.ascending;
    ctx.execution_metadata["gpu_sort_threshold"] = config.gpu_sort_threshold;
    ctx.execution_metadata["analysis_type"] = analysis_type;
    ctx.execution_metadata["analyzer_qualifier"] = qualifier;
    return ctx;
}
Referenced by process(), process(), process_to_container(), process_to_container(), process_to_stream(), and process_to_stream().