MayaFlux: MayaFlux::Kinesis::Discrete::sort_channels
sort_channels()
void MayaFlux::Kinesis::Discrete::sort_channels (std::vector< std::span< double > > & channels, SortingDirection direction, SortingAlgorithm algorithm = SortingAlgorithm::STANDARD)
Sort all channels in-place.
Parameters
channels Vector of mutable spans, one per channel
direction Sort direction
algorithm Algorithm to use
Definition at line 19 of file Sort.cpp.
{
    for (auto& ch : channels)
        sort_span(ch, direction, algorithm);
}
References sort_span().
Referenced by MayaFlux::Yantra::sort_compute_data_extract(), MayaFlux::Yantra::sort_compute_data_extract(), and MayaFlux::Yantra::sort_compute_data_inplace().