MayaFlux: MayaFlux::Yantra::Granular::process
process() [2/2]
MAYAFLUX_API GranularDatum MayaFlux::Yantra::Granular::process (const std::shared_ptr< Kakshya::SignalSourceContainer > & container, AttributeExecutor executor, const GranularConfig & config = {})
Run segment -> attribute -> sort using a span-level attribution lambda.
Parameters
container Source signal data.
executor Lambda receiving grain samples and context, returning a scalar.
config Pipeline scalar parameters.
Returns
GranularDatum containing the attributed, sorted RegionGroup.
Definition at line 850 of file GranularWorkflow.cpp.
{
    auto matrix = make_granular_matrix(config.attribution_context);
    auto ctx = make_granular_context(config, std::move(executor));
    auto seg_op = matrix->get_operation<SegmentOp>("segment");
    auto attr_op = matrix->get_operation<AttributeOp>("attribute");
    auto sort_op = matrix->get_operation<SortOp>("sort");
    apply_context_parameters(seg_op, ctx);
    apply_context_parameters(attr_op, ctx);
    apply_context_parameters(sort_op, ctx);
    return matrix->with(make_granular_input(container))
        .template then<SegmentOp>("segment")
        .template then<AttributeOp>("attribute")
        .template then<SortOp>("sort")
        .to_io();
}
References MayaFlux::Yantra::apply_context_parameters(), MayaFlux::Yantra::Granular::GranularConfig::attribution_context, make_granular_context(), make_granular_input(), and make_granular_matrix().