MayaFlux: MayaFlux::Yantra::sort_compute_data_inplace
sort_compute_data_inplace()
template<ComputeData T> void MayaFlux::Yantra::sort_compute_data_inplace (Datum< T > & data, SortingDirection direction, SortingAlgorithm algorithm)
Universal sort function - handles extraction/conversion internally.
Template Parameters
T ComputeData type
Parameters
data Data to sort (modified in-place)
direction Sort direction
algorithm Sort algorithm
Definition at line 40 of file SortingHelper.hpp.
{
    if constexpr (RequiresContainer<T>) {
        if (!data.has_container()) {
            error<std::runtime_error>(Journal::Component::Yantra, Journal::Context::ComputeMatrix, std::source_location::current(), "Region-like types require container - use UniversalSorter instead");
        }
        auto channels = OperationHelper::extract_numeric_data(data.data, data.container.value());
        Kinesis::Discrete::sort_channels(channels, direction, algorithm);
        return;
    }
    auto channels = OperationHelper::extract_numeric_data(data.data, data.needs_processig());
    Kinesis::Discrete::sort_channels(channels, direction, algorithm);
}
References MayaFlux::Journal::ComputeMatrix, MayaFlux::Yantra::Datum< T >::container, MayaFlux::Yantra::Datum< T >::data, MayaFlux::Yantra::OperationHelper::extract_numeric_data(), MayaFlux::Yantra::Datum< T >::has_container(), MayaFlux::Yantra::Datum< T >::needs_processig(), MayaFlux::Kinesis::Discrete::sort_channels(), and MayaFlux::Journal::Yantra.
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::sort_data_in_place().