MayaFlux: MayaFlux::Buffers::upload_to_gpu
upload_to_gpu() [2/3]
MAYAFLUX_API void MayaFlux::Buffers::upload_to_gpu (const void * data, size_t size, const std::shared_ptr< VKBuffer > & target, const std::shared_ptr< VKBuffer > & staging = nullptr)
Upload raw data to GPU buffer (auto-detects host-visible vs device-local)
Parameters
data Source data pointer
size Size in bytes
target Target GPU buffer
staging Optional staging buffer (created if needed for device-local)
Convenience wrapper over StagingUtils that:
Converts raw pointer → DataVariant
Auto-detects if buffer is host-visible or device-local
Handles staging buffer creation if needed
Definition at line 272 of file StagingUtils.cpp.
{
    if (!target) {
        error<std::invalid_argument>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "upload_to_gpu: target buffer is null");
    }
    if (size == 0) {
        return;
    }
    std::vector<uint8_t> raw_bytes(size);
    std::memcpy(raw_bytes.data(), data, size);
    Kakshya::DataVariant data_variant(raw_bytes);
    if (target->is_host_visible()) {
        upload_host_visible(target, data_variant);
    } else {
        std::shared_ptr<VKBuffer> staging_buf = staging;
        if (!staging_buf) {
            staging_buf = create_staging_buffer(size);
        }
        upload_device_local(target, staging_buf, data_variant);
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, create_staging_buffer(), upload_device_local(), and upload_host_visible().
Referenced by MayaFlux::Buffers::NodeTextureProcessor::initialize_gpu_resources(), MayaFlux::IO::ImageReader::load_into_buffer(), MayaFlux::Buffers::CompositeGeometryProcessor::processing_function(), MayaFlux::Buffers::GeometryBindingsProcessor::processing_function(), MayaFlux::Buffers::NetworkGeometryProcessor::processing_function(), MayaFlux::Buffers::AggregateBindingsProcessor::processing_function(), MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_buffer(), MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_network(), MayaFlux::Buffers::DescriptorBindingsProcessor::update_from_node(), MayaFlux::Buffers::TextureProcessor::update_geometry_if_dirty(), upload_audio_to_gpu(), upload_from_view(), MayaFlux::Buffers::TextureProcessor::upload_initial_geometry(), upload_structured_view(), upload_to_gpu(), and upload_to_gpu().