MayaFlux: MayaFlux::create_pattern
create_pattern()
MAYAFLUX_API Vruta::SoundRoutine MayaFlux::create_pattern (std::function< std::any(uint64_t)> pattern_func, std::function< void(std::any)> callback, double interval_seconds)
Schedules a pattern generator that produces values based on a pattern function.
Parameters
pattern_func Function that generates pattern values based on step index
callback Function to call with each pattern value
interval_seconds Time between pattern steps
Returns
SoundRoutine object representing the scheduled task
Uses the task scheduler from the default engine.
Definition at line 72 of file Chronie.cpp.
{
    return Kriya::pattern(*get_scheduler(), std::move(pattern_func), std::move(callback), interval_seconds);
}
References get_scheduler(), and MayaFlux::Kriya::pattern().
Referenced by schedule_pattern().