MayaFlux: MayaFlux::Kinesis::to_window
to_window()
glm::vec2 MayaFlux::Kinesis::to_window (const glm::vec3 & ndc, uint32_t width, uint32_t height) inline
Convert NDC to window pixel coordinates.
Parameters
ndc NDC position (z ignored)
width Window width in pixels
height Window height in pixels
Returns
Window coordinates (top-left origin, +Y down)
Definition at line 153 of file ViewTransform.hpp.
{
    return {
        (ndc.x + 1.0F) * 0.5F * static_cast<float>(width),
        (1.0F - ndc.y) * 0.5F * static_cast<float>(height)
    };
}
References width.
Referenced by MayaFlux::window_coords(), MayaFlux::window_coords(), MayaFlux::window_coords(), and MayaFlux::window_coords().