MayaFlux: MayaFlux::Reflect::member
member()
template<typename Class , typename T > constexpr auto MayaFlux::Reflect::member (std::string_view key, T Class::* ptr) constexpr
Definition at line 37 of file Mirror.hpp.
{
    return Property<Class, T> { key, ptr };
}
References ptr.
Referenced by MayaFlux::Core::KeyRepeatConfig::describe(), MayaFlux::Core::TextConfig::describe(), MayaFlux::Core::GlobalStreamInfo::ChannelConfig::describe(), MayaFlux::Core::GlobalStreamInfo::describe(), MayaFlux::Nexus::State::Range::describe(), MayaFlux::Nexus::State::RangeSet::describe(), MayaFlux::Nexus::State::WiringStep::describe(), MayaFlux::Nexus::State::WiringRecord::describe(), MayaFlux::Nexus::State::AudioSinkRecord::describe(), MayaFlux::Nexus::State::RenderSinkRecord::describe(), MayaFlux::Nexus::State::LocusNavRecord::describe(), MayaFlux::Nexus::State::EntityRecord::describe(), MayaFlux::Nexus::State::ExpanseRecord::describe(), MayaFlux::Nexus::State::FabricSchema::describe(), MayaFlux::Nexus::State::FabricRef::describe(), MayaFlux::Nexus::State::TapestryExpanseRecord::describe(), and MayaFlux::Nexus::State::TapestrySchema::describe().