MayaFlux: MayaFlux::bind_pan_zoom_preset
bind_pan_zoom_preset() [2/2]
MAYAFLUX_API void MayaFlux::bind_pan_zoom_preset (const std::shared_ptr< Core::Window > & window, const std::shared_ptr< Buffers::RenderProcessor > & processor, const Kinesis::PanZoom2DConfig & config = {}, const Kinesis::PanZoom2DKeyMap & key_map = {}, const std::string & name = "default")
Bind the 2D pan/zoom controller to a window and render processor.
Drag pans the view; scroll zooms by scaling the orthographic half-height. View matrix is always identity; only the orthographic projection changes.
Parameters
window Window supplying input events
processor RenderProcessor that receives the ViewTransform source
config Pan/zoom tuning parameters
key_map Input assignments; defaults to MMB drag
name Unique prefix for registered events; must be unique per window
Definition at line 244 of file ViewportPreset.cpp.
{
    auto& record = s_registry[make_key(window, name)];
    record.saved_config = window->get_input_config();
    record.registered_events.clear();
    auto st = std::make_shared<Kinesis::PanZoom2DState>(Kinesis::make_pan_zoom_state(config));
    on_mouse_pressed(window, key_map.drag_button, [st](double /*x*/, double /*y*/) {
        st->drag_held    = true;
        st->first_mouse  = true; }, event_name(name, "drag_dn"));
    on_mouse_released(window, key_map.drag_button, [st](double /*x*/, double /*y*/) { st->drag_held = false; }, event_name(name, "drag_up"));
    on_mouse_move(window, [st, window_weak = std::weak_ptr<Core::Window>(window)](double x, double y) {
        if (!st->drag_held) {
            st->first_mouse = true;
            return;
        }
        if (st->first_mouse) {
            st->last_x      = x;
            st->last_y      = y;
            st->first_mouse = false;
            return;
        }
        const auto  dx = static_cast<float>(x - st->last_x);
        const auto  dy = static_cast<float>(y - st->last_y);
        st->last_x = x;
        st->last_y = y;
        auto win = window_weak.lock();
        if (!win)
            return;
        const auto& ws = win->get_state();
        if (ws.current_width > 0 && ws.current_height > 0) {
            Kinesis::apply_pan_zoom_pan(*st, dx, dy,
                static_cast<float>(ws.current_width),
                static_cast<float>(ws.current_height));
        } }, event_name(name, "mouse"));
    on_scroll(window, [st](double /*dx*/, double dy) { Kinesis::apply_pan_zoom_scroll(*st, static_cast<float>(dy)); }, event_name(name, "scroll"));
    processor->set_view_transform_source(
        [st, window_weak = std::weak_ptr<Core::Window>(window)]() -> Kinesis::ViewTransform {
            auto win = window_weak.lock();
            if (!win)
                return {};
            const auto& ws = win->get_state();
            const float aspect = (ws.current_height > 0)
                ? static_cast<float>(ws.current_width) / static_cast<float>(ws.current_height)
                : 1.0F;
            return Kinesis::compute_pan_zoom_view_transform(*st, aspect);
        });
}
References MayaFlux::Kinesis::apply_pan_zoom_pan(), MayaFlux::Kinesis::apply_pan_zoom_scroll(), MayaFlux::Kinesis::compute_pan_zoom_view_transform(), MayaFlux::Kinesis::PanZoom2DKeyMap::drag_button, MayaFlux::Kinesis::make_pan_zoom_state(), on_mouse_move(), on_mouse_pressed(), on_mouse_released(), and on_scroll().
Referenced by bind_pan_zoom_preset(), and bind_viewport_preset().