MayaFlux: MayaFlux::Portal::Forma::plot
plot()
MAYAFLUX_API std::pair< Mapped< std::shared_ptr< Kakshya::PlotContainer > >, Surface > MayaFlux::Portal::Forma::plot (std::string title, uint32_t width, uint32_t height, std::shared_ptr< Kakshya::PlotContainer > container, Plot::SeriesSpec spec)
Create a live plot in a new window.
Creates the window, shows it, constructs the Surface, builds the FormaBuffer from the spec capacity and topology, and calls Plot::place. Returns the Mapped<shared_ptr<PlotContainer>> from Plot::place, plus the Surface owning the window and layer.
Parameters
title Window title.
width Window width in pixels.
height Window height in pixels.
container Ready PlotContainer from Plot::source().build().
spec SeriesSpec from Plot::series()...done().
Returns
Pair of { Mapped<shared_ptr<PlotContainer>>, Surface } for the created plot.
Definition at line 247 of file Forma.cpp.
{
    const uint64_t N = container->series_count() > 0
        ? container->series_size(0)
        : 0;
    auto window = g_window_manager->create_window(
        Core::WindowCreateInfo { .title = std::move(title), .width = width, .height = height });
    window->show();
    auto surface = create_surface(window, window->get_create_info().title);
    if (spec.background_fn) {
        auto bg = create_element<float>(
            surface.layer(), window,
            *spec.background_fn,
            0.F,
            Graphics::PrimitiveTopology::TRIANGLE_STRIP,
            static_cast<size_t>(4) * Kakshya::VertexLayout::for_meshes().stride_bytes);
        const auto bg_id = bg.element.id;
        auto buf = internal::create_buffer_impl(window, spec.capacity_for(N), spec.topology);
        auto mapped = Plot::place(surface, std::move(buf), spec, std::move(container));
        surface.layer().relate(mapped.element.id, bg_id);
        surface.layer().send_to_back(bg_id);
        place_plot_adornments(surface, spec, mapped.element.id);
        return { std::move(mapped), std::move(surface) };
    }
    auto buf = internal::create_buffer_impl(window, spec.capacity_for(N), spec.topology);
    auto mapped = Plot::place(surface, std::move(buf), spec, std::move(container));
    place_plot_adornments(surface, spec, mapped.element.id);
    return { std::move(mapped), std::move(surface) };
}
References MayaFlux::Portal::Forma::Plot::SeriesSpec::background_fn, MayaFlux::Portal::Forma::Plot::SeriesSpec::capacity_for, MayaFlux::Portal::Forma::internal::create_buffer_impl(), create_surface(), MayaFlux::Kakshya::VertexLayout::for_meshes(), N, MayaFlux::Portal::Forma::Plot::place(), MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Core::WindowCreateInfo::title, MayaFlux::Portal::Forma::Plot::SeriesSpec::topology, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, and width.