MayaFlux: MayaFlux::Kinesis::Discrete::coefficient_of_variation
coefficient_of_variation()
std::vector< double > MayaFlux::Kinesis::Discrete::coefficient_of_variation (std::span< const double > data, size_t n_windows, uint32_t hop_size, uint32_t window_size, bool sample_variance = true)
Coefficient of variation (std_dev / mean) per window.
Returns 0 when |mean| < 1e-15.
Parameters
sample_variance If true, uses sample variance (N-1)
Definition at line 545 of file Analysis.cpp.
{
    auto m = mean(data, n_windows, hop_size, window_size);
    auto s = std_dev(data, n_windows, hop_size, window_size, sample_variance);
    std::vector<double> out(n_windows);
    Parallel::transform(Parallel::par_unseq, m.begin(), m.end(), s.begin(), out.begin(),
        [](double mv, double sv) {
            return (std::abs(mv) > 1e-15) ? sv / mv : 0.0;
        });
    return out;
}
References coefficient_of_variation(), MayaFlux::mean(), and MayaFlux::std_dev().
Referenced by coefficient_of_variation().