MayaFlux: MayaFlux::Nexus::add_render_sink
add_render_sink()
void MayaFlux::Nexus::add_render_sink (std::vector< RenderSink > & sinks, Buffers::BufferManager & mgr, const Portal::Graphics::RenderConfig & config, RenderFn fn = {}, std::string fn_name = {}, const std::optional< glm::vec3 > & initial_position = {})
Create and register a render sink targeting window.
Allocates a VKBuffer (VERTEX, POINT_LIST), attaches a GeometryWriteProcessor and a RenderProcessor with point.vert.spv / point.frag.spv defaults, and registers the buffer with mgr.
Parameters
sinks Sink vector owned by the calling Emitter or Agent.
mgr BufferManager to register the VKBuffer with.
window Target window for presentation.
fn Optional producer called each dispatch with InfluenceContext. Leave empty when geometry is supplied via push_geometry().
fn_name Optional identifier for state encoding, empty if anonymous.
initial_position Optional initial position to write if no producer fn is set.
Definition at line 95 of file Sinks.cpp.
{
    constexpr size_t k_initial_bytes = 4096;
    auto buf = std::make_shared<Buffers::VKBuffer>(
        k_initial_bytes,
        Buffers::VKBuffer::Usage::VERTEX,
        Kakshya::DataModality::VERTEX_POSITIONS_3D);
    auto writer = std::make_shared<Buffers::GeometryWriteProcessor>();
    const bool is_line = config.topology == Portal::Graphics::PrimitiveTopology::LINE_LIST
        || config.topology == Portal::Graphics::PrimitiveTopology::LINE_STRIP;
    const bool is_mesh = config.topology == Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST
        || config.topology == Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP;
    if (is_line) {
        writer->set_mode(Buffers::GeometryWriteMode::LINE);
    } else if (is_mesh) {
        writer->set_mode(Buffers::GeometryWriteMode::MESH);
    } else {
        writer->set_mode(Buffers::GeometryWriteMode::POINT);
    }
    buf->set_default_processor(writer);
    mgr.add_buffer(buf, Buffers::ProcessingToken::GRAPHICS_BACKEND);
    std::string vert = config.vertex_shader;
    std::string frag = config.fragment_shader;
    std::string geom = config.geometry_shader;
    if (vert.empty() || frag.empty()) {
        switch (config.topology) {
        case Portal::Graphics::PrimitiveTopology::LINE_LIST:
        case Portal::Graphics::PrimitiveTopology::LINE_STRIP:
            if (frag.empty())
                frag = "line.frag.spv";
#ifndef MAYAFLUX_PLATFORM_MACOS
            if (vert.empty())
                vert = "line.vert.spv";
            if (geom.empty())
                geom = "line.geom.spv";
#else
            if (vert.empty())
                vert = "line_fallback.vert.spv";
#endif
            break;
        case Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST:
        case Portal::Graphics::PrimitiveTopology::TRIANGLE_STRIP:
            if (vert.empty())
                vert = "triangle.vert.spv";
            if (frag.empty())
                frag = "triangle.frag.spv";
            break;
        default:
            if (vert.empty())
                vert = "point.vert.spv";
            if (frag.empty())
                frag = "point.frag.spv";
            break;
        }
    }
    auto renderer = std::make_shared<Buffers::RenderProcessor>(Buffers::ShaderConfig { vert });
    renderer->set_fragment_shader(frag);
    if (!geom.empty())
        renderer->set_geometry_shader(geom);
    renderer->set_primitive_topology(config.topology);
    renderer->set_polygon_mode(config.polygon_mode);
    renderer->set_cull_mode(config.cull_mode);
    renderer->set_target_window(config.target_window, buf);
    buf->get_processing_chain()->add_final_processor(renderer, buf);
    auto& sink = sinks.emplace_back(RenderSink {
        .buf = buf,
        .writer = std::move(writer),
        .renderer = std::move(renderer),
        .fn = std::move(fn),
        .fn_name = std::move(fn_name),
        .window = config.target_window,
    });
    if (!sink.fn && initial_position.has_value()) {
        sink.writer->set_data(
            Kakshya::DataVariant { std::vector<glm::vec3> { *initial_position } });
    }
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::Init,
        "Nexus: render sink added");
}
References MayaFlux::Buffers::BufferManager::add_buffer(), MayaFlux::Nexus::RenderSink::buf, MayaFlux::Journal::Buffers, MayaFlux::Portal::Graphics::RenderConfig::cull_mode, fn_name, MayaFlux::Portal::Graphics::RenderConfig::fragment_shader, MayaFlux::Portal::Graphics::RenderConfig::geometry_shader, MayaFlux::Buffers::GRAPHICS_BACKEND, MayaFlux::Journal::Init, MayaFlux::Buffers::LINE, MayaFlux::Portal::Graphics::LINE_LIST, MayaFlux::Portal::Graphics::LINE_STRIP, MayaFlux::Buffers::MESH, MF_DEBUG, MayaFlux::Buffers::POINT, MayaFlux::Portal::Graphics::RenderConfig::polygon_mode, MayaFlux::Portal::Graphics::RenderConfig::target_window, MayaFlux::Portal::Graphics::RenderConfig::topology, MayaFlux::Portal::Graphics::TRIANGLE_LIST, MayaFlux::Portal::Graphics::TRIANGLE_STRIP, MayaFlux::Buffers::VKBuffer::VERTEX, MayaFlux::Kakshya::VERTEX_POSITIONS_3D, and MayaFlux::Portal::Graphics::RenderConfig::vertex_shader.
Referenced by MayaFlux::Nexus::Agent::render(), MayaFlux::Nexus::Emitter::render(), MayaFlux::Nexus::Agent::render(), and MayaFlux::Nexus::Emitter::render().