MayaFlux: MayaFlux::Portal::Forma::Geometry::level_meter
level_meter()
MAYAFLUX_API GeometryFn< float > MayaFlux::Portal::Forma::Geometry::level_meter (Kinesis::AABB2D bounds, bool horizontal = true, glm::vec3 fill_color = glm::vec3(0.2F, 0.7F, 0.3F), glm::vec3 track_color = glm::vec3(0.15F))
Geometry function for a level meter in NDC space.
No interaction. Drive from a node via bridge().at(el.state).bind(node).
Parameters
bounds Full extent of the meter in NDC.
horizontal True for left-to-right fill, false for bottom-to-top.
fill_color Color of the active (filled) portion.
track_color Color of the inactive remainder.
Definition at line 234 of file Geometry.cpp.
{
    return [bounds, horizontal, fill_color, track_color](
               float v, std::vector<uint8_t>& out, Element& el) {
        const float t = std::clamp(v, 0.F, 1.F);
        Kinesis::AABB2D fill {}, remainder {};
        if (horizontal) {
            const float split = bounds.min.x + t * bounds.width();
            fill = { .min = bounds.min, .max = { split, bounds.max.y } };
            remainder = { .min = { split, bounds.min.y }, .max = bounds.max };
        } else {
            const float split = bounds.min.y + t * bounds.height();
            fill = { .min = bounds.min, .max = { bounds.max.x, split } };
            remainder = { .min = { bounds.min.x, split }, .max = bounds.max };
        }
        auto verts = Kakshya::to_mesh_vertices(Kinesis::filled_rect(fill, fill_color));
        auto rest = Kakshya::to_mesh_vertices(Kinesis::filled_rect(remainder, track_color));
        verts.insert(verts.end(), rest.begin(), rest.end());
        write_verts(out, verts);
        el.bounds_hint = bounds;
        el.contains = {};
    };
}
References MayaFlux::Kinesis::AABB2D::contains(), MayaFlux::Kinesis::filled_rect(), MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kakshya::to_mesh_vertices(), MayaFlux::Kinesis::AABB2D::width(), and write_verts().