MayaFlux: MayaFlux::Yantra::compute_zero_crossing_energy
compute_zero_crossing_energy()
std::vector< double > MayaFlux::Yantra::compute_zero_crossing_energy (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute zero-crossing energy using zero-copy processing.
This function computes the zero-crossing rate for a given data span. It counts the number of zero crossings in each window and normalizes it.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
Returns
Vector of zero-crossing energy values
Definition at line 39 of file AnalysisHelper.cpp.
{
    std::vector<double> zcr_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            int zero_crossings = 0;
            for (size_t j = 1; j < window.size(); ++j) {
                if ((window[j] >= 0.0) != (window[j - 1] >= 0.0)) {
                    zero_crossings++;
                }
            }
            zcr_values[i] = static_cast<double>(zero_crossings) / static_cast<double>(window.size() - 1);
        });
    return zcr_values;
}
References compute_zero_crossing_energy(), and MayaFlux::zero_crossings().
Referenced by MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::compute_energy_values(), and compute_zero_crossing_energy().