MayaFlux: MayaFlux::samples_to_blocks
samples_to_blocks()
MAYAFLUX_API uint64_t MayaFlux::samples_to_blocks (uint64_t samples)
Converts samples to blocks based on current block size.
Parameters
samples Number of samples
Returns
Number of blocks
Definition at line 266 of file Chronie.cpp.
{
    uint32_t block_size = 512;
    if (get_context().is_running()) {
        block_size = get_context().get_stream_info().buffer_size;
    }
    return Vruta::samples_to_blocks(samples, block_size);
}
References MayaFlux::Core::GlobalStreamInfo::buffer_size, get_context(), MayaFlux::Core::Engine::get_stream_info(), and MayaFlux::Vruta::samples_to_blocks().