MayaFlux: MayaFlux::Yantra::compute_kurtosis_statistic
compute_kurtosis_statistic()
std::vector< double > MayaFlux::Yantra::compute_kurtosis_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute kurtosis statistic using zero-copy processing.
This function computes the kurtosis (fourth moment) for a given data span. It measures the tail heaviness of the distribution in each window.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
Returns
Vector of kurtosis values (excess kurtosis, normal = 0)
Definition at line 456 of file AnalysisHelper.cpp.
{
    std::vector<double> kurtosis_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.size() < 2) {
                kurtosis_values[i] = 0.0;
                return;
            }
            double sum = 0.0;
            for (double sample : window) {
                sum += sample;
            }
            double mean = sum / static_cast<double>(window.size());
            double sum_sq_diff = 0.0;
            double sum_fourth_diff = 0.0;
            for (double sample : window) {
                double diff = sample - mean;
                double sq_diff = diff * diff;
                sum_sq_diff += sq_diff;
                sum_fourth_diff += sq_diff * sq_diff;
            }
            double variance = sum_sq_diff / static_cast<double>(window.size());
            if (variance <= 0.0) {
                kurtosis_values[i] = 0.0;
                return;
            }
            double fourth_moment = sum_fourth_diff / static_cast<double>(window.size());
            kurtosis_values[i] = (fourth_moment / (variance * variance)) - 3.0;
        });
    return kurtosis_values;
}
References compute_kurtosis_statistic(), and MayaFlux::mean().
Referenced by compute_kurtosis_statistic(), MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::create_analysis_result().