MayaFlux: MayaFlux::Utils::enum_to_string
enum_to_string()
template<typename EnumType > constexpr std::string_view MayaFlux::Utils::enum_to_string (EnumType value) constexpr noexcept
Universal enum to string converter using magic_enum (original case)
Template Parameters
EnumType Any enum type
Parameters
value Enum value to convert
Returns
String representation of the enum
Definition at line 57 of file EnumUtils.hpp.
{
    return magic_enum::enum_name(value);
}
Referenced by MayaFlux::Kakshya::modality_to_string(), MayaFlux::Kriya::BufferPipeline::process_operation(), MayaFlux::IO::to_string(), MayaFlux::Journal::Archivist::Impl::write_to_console(), and MayaFlux::Journal::Archivist::Impl::write_to_console().