MayaFlux: MayaFlux::Yantra::transform_window
transform_window() [1/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_window (DataType & input, Nodes::Generator::WindowType window_type, uint32_t window_size, std::vector< std::vector< double > > & working_buffer)
Windowing transformation using C++20 ranges (OUT-OF-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - will NOT be modified
window_type Type of window to apply
window_size Size of window (0 = full data size)
working_buffer Buffer for operations (will be resized if needed)
Returns
Windowed data
Definition at line 138 of file SpectralHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::setup_operation_buffer(input, working_buffer);
    uint32_t size = window_size > 0 ? window_size : smallest_size(working_buffer);
    auto window = Nodes::Generator::generate_window(size, window_type);
    working_buffer.resize(target_data.size());
    for (size_t i = 0; i < target_data.size(); ++i) {
        auto& span = target_data[i];
        auto& buffer = working_buffer[i];
        buffer.resize(span.size());
        auto data_view = span | std::views::take(std::min(size, static_cast<uint32_t>(span.size())));
        auto window_view = window | std::views::take(data_view.size());
        std::ranges::transform(data_view, window_view, buffer.begin(),
            [](double sample, double win) { return sample * win; });
        if (span.size() > size) {
            std::copy(span.begin() + size, span.end(), buffer.begin() + size);
        }
    }
    return OperationHelper::reconstruct_from_double<DataType>(working_buffer, structure_info);
}
References MayaFlux::Nodes::Generator::generate_window(), MayaFlux::Yantra::OperationHelper::setup_operation_buffer(), and smallest_size().