MayaFlux: MayaFlux::Yantra::sort_channels_inplace
sort_channels_inplace()
void MayaFlux::Yantra::sort_channels_inplace (std::vector< std::span< double > > & channels, SortingDirection direction, SortingAlgorithm algorithm)
Sort multiple channels (spans) in-place.
Parameters
channels Vector of spans, each representing a channel
direction Sort direction
algorithm Sort algorithm
Definition at line 30 of file SortingHelper.cpp.
{
    for (auto& channel : channels) {
        sort_span_inplace(channel, direction, algorithm);
    }
}
References sort_span_inplace().
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::convert_and_sort(), sort_compute_data_extract(), sort_compute_data_extract(), sort_compute_data_inplace(), and MayaFlux::Yantra::StandardSorter< InputType, OutputType >::sort_copy().