MayaFlux: MayaFlux::Portal::Forma::Geometry::drawable_canvas
drawable_canvas()
MAYAFLUX_API GeometryFn< std::vector< float > > MayaFlux::Portal::Forma::Geometry::drawable_canvas (Kinesis::AABB2D bounds, glm::vec3 color = glm::vec3(0.8F), float thickness = 1.5F)
Geometry function for a drawable curve canvas in NDC space.
Renders the sample vector as a LINE_LIST polyline. Each adjacent sample pair becomes one segment. The hit region covers the full canvas bounds.
Parameters
bounds Canvas extent in NDC.
color Line color.
thickness LineVertex thickness value.
Definition at line 287 of file Geometry.cpp.
{
    return [bounds, color, thickness](
               const std::vector<float>& v, std::vector<uint8_t>& out, Element& el) {
        if (v.size() < 2) {
            out.clear();
            el.bounds_hint = bounds;
            el.contains = Kinesis::polygon_bounds(std::span<const glm::vec2> {
                std::array<glm::vec2, 4> {
                    bounds.min,
                    glm::vec2(bounds.max.x, bounds.min.y),
                    bounds.max,
                    glm::vec2(bounds.min.x, bounds.max.y) } });
            return;
        }
        const auto n = v.size();
        const float x_step = bounds.width() / static_cast<float>(n - 1);
        std::vector<Kakshya::LineVertex> verts;
        verts.reserve((n - 1) * 2);
        for (size_t i = 0; i + 1 < n; ++i) {
            const float xa = bounds.min.x + static_cast<float>(i) * x_step;
            const float xb = bounds.min.x + static_cast<float>(i + 1) * x_step;
            const float ya = bounds.min.y + std::clamp(v[i], 0.F, 1.F) * bounds.height();
            const float yb = bounds.min.y + std::clamp(v[i + 1], 0.F, 1.F) * bounds.height();
            verts.push_back({ .position = { xa, ya, 0.F }, .color = color, .thickness = thickness });
            verts.push_back({ .position = { xb, yb, 0.F }, .color = color, .thickness = thickness });
        }
        write_verts(out, verts);
        el.bounds_hint = bounds;
        el.contains = Kinesis::polygon_bounds(std::span<const glm::vec2> {
            std::array<glm::vec2, 4> {
                bounds.min,
                glm::vec2(bounds.max.x, bounds.min.y),
                bounds.max,
                glm::vec2(bounds.min.x, bounds.max.y) } });
    };
}
References MayaFlux::Kinesis::AABB2D::contains(), MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kinesis::polygon_bounds(), MayaFlux::Kinesis::AABB2D::width(), and write_verts().