MayaFlux: MayaFlux::apply_window
apply_window() [2/2]
MAYAFLUX_API void MayaFlux::apply_window (std::vector< double > & data, const std::string & window_type = "hann")
Apply window function to single-channel data (in-place)
Parameters
data Input data (modified in-place)
window_type "hann", "hamming", "blackman", "rectangular" (default: "hann")
Definition at line 864 of file Yantra.cpp.
{
    Nodes::Generator::WindowType win_type;
    if (window_type == "hann" || window_type == "hanning") {
        win_type = Nodes::Generator::WindowType::HANNING;
    } else if (window_type == "hamming") {
        win_type = Nodes::Generator::WindowType::HAMMING;
    } else if (window_type == "blackman") {
        win_type = Nodes::Generator::WindowType::BLACKMAN;
    } else if (window_type == "rectangular" || window_type == "rect") {
        win_type = Nodes::Generator::WindowType::RECTANGULAR;
    } else {
        win_type = Nodes::Generator::WindowType::HANNING;
    }
    auto window = Nodes::Generator::generate_window(data.size(), win_type);
    for (size_t i = 0; i < data.size() && i < window.size(); ++i) {
        data[i] *= window[i];
    }
}
References MayaFlux::Nodes::Generator::BLACKMAN, MayaFlux::Nodes::Generator::generate_window(), MayaFlux::Nodes::Generator::HAMMING, MayaFlux::Nodes::Generator::HANNING, and MayaFlux::Nodes::Generator::RECTANGULAR.
Referenced by apply_window(), and apply_window_channels().