MayaFlux: MayaFlux::Kinesis::Discrete::slice_intervals
slice_intervals()
std::vector< double > MayaFlux::Kinesis::Discrete::slice_intervals (std::span< const double > data, const std::vector< std::pair< size_t, size_t > > & intervals)
Copy data from a set of half-open intervals into a flat vector.
Parameters
data Source span
intervals Sorted, non-overlapping [start, end) pairs
Returns
Concatenated data from all intervals
Definition at line 39 of file Extract.cpp.
{
    std::vector<double> out;
    for (const auto& [s, e] : intervals) {
        if (s < data.size() && e <= data.size() && s < e) {
            out.insert(out.end(), data.begin() + s, data.begin() + e);
        }
    }
    return out;
}
Referenced by MayaFlux::Yantra::extract_above_mean(), MayaFlux::Yantra::extract_high_energy(), MayaFlux::Yantra::extract_high_spectral(), MayaFlux::Yantra::extract_onsets(), MayaFlux::Yantra::extract_outliers(), MayaFlux::Yantra::extract_peaks(), MayaFlux::Yantra::extract_silence(), and MayaFlux::Yantra::extract_zero_crossings().