MayaFlux: MayaFlux::Yantra::extract_zero_crossings
extract_zero_crossings()
std::vector< std::vector< double > > MayaFlux::Yantra::extract_zero_crossings (const std::vector< std::span< const double > > & channels, double threshold, double min_distance, uint32_t region_size)
Definition at line 194 of file ExtractionHelper.cpp.
{
    std::vector<std::vector<double>> result;
    result.reserve(channels.size());
    for (const auto& ch : channels) {
        if (ch.empty() || region_size == 0) {
            result.emplace_back();
            continue;
        }
        auto all = D::zero_crossing_positions(ch, threshold);
        std::vector<size_t> filtered;
        size_t last = 0;
        for (size_t p : all) {
            if (filtered.empty() || (p - last) >= static_cast<size_t>(min_distance)) {
                filtered.push_back(p);
                last = p;
            }
        }
        result.push_back(D::slice_intervals(ch,
            D::merge_intervals(D::regions_around_positions(filtered, region_size / 2, ch.size()))));
    }
    return result;
}
References MayaFlux::Kinesis::Discrete::merge_intervals(), MayaFlux::Kinesis::Discrete::regions_around_positions(), MayaFlux::Kinesis::Discrete::slice_intervals(), and MayaFlux::Kinesis::Discrete::zero_crossing_positions().
Referenced by MayaFlux::Yantra::FeatureExtractor< InputType, OutputType >::extract_implementation().