MayaFlux: MayaFlux::Portal::Text::set_default_font
set_default_font() [2/2]
MAYAFLUX_API bool MayaFlux::Portal::Text::set_default_font (std::string_view family, std::string_view style, uint32_t pixel_size, uint32_t atlas_size = 512)
Locate a system font by family and style, then load it as the default.
Delegates font path resolution to find_font, then calls the path-based overload. Returns false and logs if the family cannot be located on the current platform.
Parameters
family Font family name, e.g. "JetBrains Mono".
style Style hint, e.g. "Medium", "Bold".
pixel_size Glyph height in pixels.
atlas_size Atlas texture dimension (power of two, default 512).
Returns
true on success.
Definition at line 82 of file Text.cpp.
{
    const auto path = find_font(family, style);
    if (!path) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "set_default_font: could not locate '{}{}{}' on this system",
            family,
            style.empty() ? "" : " ",
            style);
        return false;
    }
    return set_default_font(*path, pixel_size, atlas_size);
}
References MayaFlux::Journal::API, find_font(), MF_ERROR, MayaFlux::Journal::Portal, and set_default_font().
Referenced by initialize(), and set_default_font().