MayaFlux: MayaFlux::Portal::Graphics::get_texture_manager
get_texture_manager()
MAYAFLUX_API TextureLoom & MayaFlux::Portal::Graphics::get_texture_manager () inline
Get the global texture manager instance.
Returns
Reference to singleton texture manager
Must call initialize() before first use. Thread-safe after initialization.
Definition at line 302 of file TextureLoom.hpp.
{
    return TextureLoom::instance();
}
References MayaFlux::Portal::Graphics::TextureLoom::instance().
Referenced by MayaFlux::Buffers::RenderProcessor::bind_texture(), MayaFlux::Buffers::TextureProcessor::create_gpu_texture(), MayaFlux::Buffers::NodeTextureProcessor::initialize_gpu_resources(), MayaFlux::IO::ImageReader::load_texture(), MayaFlux::Buffers::NodeTextureProcessor::processing_function(), MayaFlux::Buffers::NodeTextureBuffer::setup_processors(), MayaFlux::Buffers::TextureProcessor::update_pixels_if_dirty(), and MayaFlux::Buffers::TextureProcessor::upload_initial_pixels().