MayaFlux: MayaFlux::Kinesis::Discrete::cross_correlate
cross_correlate()
std::vector< double > MayaFlux::Kinesis::Discrete::cross_correlate (std::span< const double > src, std::span< const double > tmpl, bool normalize = true)
Cross-correlation via FFT.
Parameters
src Input signal
tmpl Template signal
normalize Normalise result to peak absolute value
Returns
Cross-correlation, same length as src
Definition at line 90 of file Convolution.cpp.
{
    std::vector<double> reversed(tmpl.rbegin(), tmpl.rend());
    auto out = apply_convolution(src, reversed,
        [](const auto& s, const auto& k, auto& r) {
            P::transform(P::par_unseq, s.begin(), s.end(), k.begin(), r.begin(),
                [](const std::complex<double>& a, const std::complex<double>& b) {
                    return a * std::conj(b);
                });
        });
    if (normalize && !out.empty()) {
        const auto [mn, mx] = std::ranges::minmax_element(out);
        const double peak = std::max(std::abs(*mn), std::abs(*mx));
        if (peak > 0.0) {
            P::transform(P::par_unseq, out.begin(), out.end(), out.begin(),
                [peak](double v) { return v / peak; });
        }
    }
    return out;
}
References a, apply_convolution(), b, normalize(), peak(), and MayaFlux::reversed().
Referenced by matched_filter().