MayaFlux: MayaFlux::Kakshya::extract_region_data
extract_region_data() [2/3]
template<typename T > std::vector< std::vector< T > > MayaFlux::Kakshya::extract_region_data (const std::vector< std::span< const T > > & source_data, const Region & region, const std::vector< DataDimension > & dimensions, bool flatten = false)
Extract region data from planar storage (separate per channel/variant)
Template Parameters
T Data type
Parameters
source_variants Vector of data spans (one per channel/variant)
region Region to extract
dimensions Dimension descriptors
flatten If true, return single flattened vector; if false, return per-channel vectors
Returns
Vector of vectors (per-channel) or single flattened vector
Definition at line 115 of file RegionUtils.hpp.
{
    std::vector<std::vector<T>> results;
    for (size_t idx = 0; idx < source_data.size(); ++idx) {
        Region channel_region = remove_channel_dimension(region, dimensions);
        auto channel_data = extract_region_data(
            source_data[idx],
            channel_region,
            get_non_channel_dimensions(dimensions));
        results.push_back(std::move(channel_data));
    }
    if (flatten) {
        return { flatten_channels(results) };
    }
    return results;
}
References extract_region_data(), flatten_channels(), get_non_channel_dimensions(), and remove_channel_dimension().