MayaFlux: MayaFlux::Nodes::Generator::generate_window
generate_window()
std::vector< double > MayaFlux::Nodes::Generator::generate_window (uint32_t size, WindowType window_type)
Generate window coefficients using C++20 ranges.
Parameters
size Window size
window_type Type of window function
Returns
Window coefficients
Definition at line 67 of file WindowGenerator.cpp.
{
    switch (window_type) {
    case WindowType::HAMMING:
        return HammingWindow(size);
    case WindowType::BLACKMAN:
        return BlackmanWindow(size);
    case WindowType::HANNING:
    default:
        return HannWindow(size);
    }
}
References BLACKMAN, BlackmanWindow(), HAMMING, HammingWindow(), HANNING, and HannWindow().
Referenced by MayaFlux::apply_window(), MayaFlux::Yantra::process_spectral_windows(), MayaFlux::Yantra::transform_window(), and MayaFlux::Yantra::transform_window().