MayaFlux: MayaFlux::Portal::Text::repress
repress() [2/2]
MAYAFLUX_API bool MayaFlux::Portal::Text::repress (std::shared_ptr< Core::VKImage > & target, std::string_view text, const PressParams & params = {}, const std::shared_ptr< Buffers::VKBuffer > & staging = nullptr)
Re-composite a UTF-8 string into an existing GPU texture.
Uploads in-place when content fits within the existing image dimensions. Reallocates and updates target when content height exceeds image height.
Parameters
target VKImage to update. May be replaced on reallocation.
text UTF-8 string to composite.
params render_bounds, atlas, color.
staging Optional staging buffer for GPU upload.
Returns
True on success.
Definition at line 386 of file InkPress.cpp.
{
    if (!target) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "repress(VKImage): target is null");
        return false;
    }
    GlyphAtlas* atlas = resolve_atlas(params.atlas);
    if (!atlas)
        return false;
    const uint32_t buf_w = target->get_width();
    const uint32_t buf_h = target->get_height();
    const uint32_t composite_h = std::max(buf_h,
        static_cast<uint32_t>(atlas->line_height()));
    const auto result = composite(text, *atlas, params.color, buf_w, composite_h,
        static_cast<float>(atlas->ascender()));
    if (!result) {
        MF_WARN(Journal::Component::Portal, Journal::Context::API,
            "repress(VKImage): no glyphs produced for '{}'", std::string(text));
        return false;
    }
    auto& loom = Portal::Graphics::get_texture_manager();
    const uint32_t new_h = composite_h;
    const bool needs_realloc = composite_h != buf_h || buf_w != target->get_width();
    const size_t buf_bytes = static_cast<size_t>(buf_w) * new_h * 4;
    std::vector<uint8_t> pixels(buf_bytes, 0);
    const uint32_t copy_h = std::min(result->h, new_h);
    for (uint32_t row = 0; row < copy_h; ++row) {
        std::memcpy(
            pixels.data() + static_cast<size_t>(row) * buf_w * 4,
            result->pixels.data() + static_cast<size_t>(row) * buf_w * 4,
            static_cast<size_t>(buf_w) * 4);
    }
    if (needs_realloc) {
        target = loom.create_2d(buf_w, new_h, Portal::Graphics::ImageFormat::RGBA8,
            nullptr, 1);
        if (!target)
            return false;
        if (staging) {
            loom.upload_data(target, pixels.data(), buf_bytes, staging, true);
        } else {
            loom.upload_data(target, pixels.data(), buf_bytes);
        }
        MF_DEBUG(Journal::Component::Portal, Journal::Context::API,
            "repress(VKImage): reallocated {}x{}", buf_w, new_h);
        return true;
    }
    if (staging) {
        loom.upload_data(target, pixels.data(), buf_bytes, staging);
    } else {
        loom.upload_data(target, pixels.data(), buf_bytes);
    }
    MF_DEBUG(Journal::Component::Portal, Journal::Context::API,
        "repress(VKImage): updated {}x{} in-place", buf_w, buf_h);
    return true;
}
References MayaFlux::Journal::API, MayaFlux::Portal::Text::GlyphAtlas::ascender(), MayaFlux::Portal::Text::PressParams::atlas, MayaFlux::Portal::Text::PressParams::color, MayaFlux::Portal::Graphics::get_texture_manager(), MayaFlux::Portal::Text::GlyphAtlas::line_height(), MF_DEBUG, MF_ERROR, MF_WARN, pixels, MayaFlux::Journal::Portal, and MayaFlux::Portal::Graphics::RGBA8.