MayaFlux: MayaFlux::Nexus::add_audio_sink
add_audio_sink()
void MayaFlux::Nexus::add_audio_sink (std::vector< AudioSink > & sinks, Buffers::BufferManager & mgr, uint32_t channel, std::function< Kakshya::DataVariant(const InfluenceContext &)> fn = {}, std::string fn_name = {})
Create and register an audio sink on channel.
Parameters
sinks Sink vector owned by the calling Emitter or Agent.
mgr BufferManager to register the AudioBuffer with.
channel Output channel index.
fn Optional producer called each dispatch with InfluenceContext. Leave empty when data is supplied via push_audio_data().
fn_name Optional identifier for state encoding, empty if anonymous.
Definition at line 18 of file Sinks.cpp.
{
    auto buf = std::make_shared<Buffers::AudioBuffer>(channel, Buffers::s_preferred_buffer_size);
    auto writer = std::make_shared<Buffers::AudioWriteProcessor>();
    buf->set_default_processor(writer);
    mgr.add_buffer(buf, Buffers::ProcessingToken::AUDIO_BACKEND, channel);
    sinks.push_back(AudioSink {
        .buf = std::move(buf),
        .writer = std::move(writer),
        .fn = std::move(fn),
        .fn_name = std::move(fn_name),
        .channel = channel,
    });
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::Init,
        "Nexus: audio sink added on channel {}", channel);
}
References MayaFlux::Buffers::BufferManager::add_buffer(), MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Nexus::AudioSink::buf, MayaFlux::Journal::Buffers, channel, fn_name, MayaFlux::Journal::Init, MF_DEBUG, and MayaFlux::Buffers::s_preferred_buffer_size.
Referenced by MayaFlux::Nexus::Agent::sink_audio(), MayaFlux::Nexus::Emitter::sink_audio(), MayaFlux::Nexus::Agent::sink_audio(), and MayaFlux::Nexus::Emitter::sink_audio().