MayaFlux: MayaFlux::Yantra::compute_std_dev_statistic
compute_std_dev_statistic()
std::vector< double > MayaFlux::Yantra::compute_std_dev_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size, bool sample_variance = true)
Compute standard deviation statistic using zero-copy processing.
This function computes the standard deviation for a given data span. It calculates the square root of variance in each window.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
sample_variance If true, use sample variance (N-1), else population (N)
Returns
Vector of standard deviation values
Definition at line 397 of file AnalysisHelper.cpp.
{
    auto variance_values = compute_variance_statistic(data, num_windows, hop_size, window_size, sample_variance);
    std::vector<double> std_dev_values(num_windows);
    std::transform(std::execution::par_unseq, variance_values.begin(), variance_values.end(), std_dev_values.begin(),
        [](double variance) { return std::sqrt(variance); });
    return std_dev_values;
}
References compute_std_dev_statistic(), and compute_variance_statistic().
Referenced by compute_cv_statistic(), MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), and compute_std_dev_statistic().