MayaFlux: MayaFlux::register_node_network
register_node_network()
MAYAFLUX_API void MayaFlux::register_node_network (const std::shared_ptr< Nodes::Network::NodeNetwork > & network, const Nodes::ProcessingToken & token = Nodes::ProcessingToken::AUDIO_RATE)
Registers a node network with the default engine's node graph manager.
Parameters
network NodeNetwork to register
Adds the node network to the default engine's node graph manager. The network can then be used to manage nodes and their connections.
Definition at line 176 of file Graph.cpp.
{
    get_context().get_node_graph_manager()->add_network(network, token);
}
References get_context(), and MayaFlux::Core::Engine::get_node_graph_manager().
Referenced by create_node_network(), and register_network().