MayaFlux: MayaFlux::Kakshya::extract_group_bounds_info
extract_group_bounds_info()
std::unordered_map< std::string, std::any > MayaFlux::Kakshya::extract_group_bounds_info (const RegionGroup & group)
Extract bounds information from region group.
Parameters
group Region group to analyze.
Returns
Map containing group bounds metadata.
Definition at line 295 of file RegionUtils.cpp.
{
    std::unordered_map<std::string, std::any> bounds_info;
    if (group.regions.empty()) {
        return bounds_info;
    }
    const auto& first_region = group.regions[0];
    std::vector<uint64_t> min_coords = first_region.start_coordinates;
    std::vector<uint64_t> max_coords = first_region.end_coordinates;
    for (size_t i = 1; i < group.regions.size(); ++i) {
        const auto& region = group.regions[i];
        for (size_t j = 0; j < min_coords.size() && j < region.start_coordinates.size(); ++j) {
            min_coords[j] = std::min(min_coords[j], region.start_coordinates[j]);
        }
        for (size_t j = 0; j < max_coords.size() && j < region.end_coordinates.size(); ++j) {
            max_coords[j] = std::max(max_coords[j], region.end_coordinates[j]);
        }
    }
    bounds_info["group_name"] = group.name;
    bounds_info["num_regions"] = group.regions.size();
    bounds_info["bounding_min"] = min_coords;
    bounds_info["bounding_max"] = max_coords;
    bounds_info["group_attributes"] = group.attributes;
    return bounds_info;
}
References MayaFlux::Kakshya::RegionGroup::attributes, extract_group_bounds_info(), MayaFlux::Kakshya::RegionGroup::name, and MayaFlux::Kakshya::RegionGroup::regions.
Referenced by extract_group_bounds_info(), and MayaFlux::Yantra::infer_from_region_group().