MayaFlux: MayaFlux::Kakshya::get_bounding_region
get_bounding_region()
Region MayaFlux::Kakshya::get_bounding_region (const RegionGroup & group)
Get the bounding region that contains all regions in a RegionGroup.
Parameters
group RegionGroup to query.
Returns
Region representing the bounding box.
Definition at line 93 of file RegionUtils.cpp.
{
    if (group.regions.empty())
        return Region {};
    auto min_coords = group.regions.front().start_coordinates;
    auto max_coords = group.regions.front().end_coordinates;
    for (const auto& region : group.regions) {
        for (size_t i = 0; i < min_coords.size() && i < region.start_coordinates.size(); ++i) {
            min_coords[i] = std::min(min_coords[i], region.start_coordinates[i]);
        }
        for (size_t i = 0; i < max_coords.size() && i < region.end_coordinates.size(); ++i) {
            max_coords[i] = std::max(max_coords[i], region.end_coordinates[i]);
        }
    }
    Region bounds(min_coords, max_coords);
    set_region_attribute(bounds, "type", std::string("bounding_box"));
    return bounds;
}
References get_bounding_region(), MayaFlux::Kakshya::RegionGroup::regions, and set_region_attribute().
Referenced by get_bounding_region().