MayaFlux: MayaFlux::Portal::Forma::make_value_row
make_value_row()
ValueRow MayaFlux::Portal::Forma::make_value_row (const ValueSpec & spec, Layer & layer, const std::shared_ptr< Core::Window > & window, LayoutCursor & cursor, float x_min, float x_max, float row_h, glm::vec3 bg = glm::vec3(0.15F))
Construct one labeled value row, advance the cursor, and return it.
The returned row's link reads spec.reader each tick, repress's "label: value" into the text image, and binds the image to the row's FormaBuffer.
Definition at line 72 of file QueryUtils.cpp.
{
    const auto [tw, th] = row_pixel_dims(window, x_min, x_max, row_h);
    const std::string initial = spec.label + ": "
        + (spec.reader ? spec.reader() : std::string {});
    Portal::Text::PressParams params {
        .color = { 1.F, 1.F, 1.F, 1.F },
        .budget_h = th,
    };
    auto text_image = Portal::Text::press(initial, { tw, th }, params);
    auto staging = Buffers::create_image_staging_buffer(text_image->get_size_bytes());
    const uint32_t stride = Kakshya::VertexLayout::for_meshes().stride_bytes;
    auto buf = Portal::Forma::create_buffer(
        window, static_cast<size_t>(12) * stride,
        Portal::Graphics::PrimitiveTopology::TRIANGLE_LIST,
        { { "text", text_image } });
    const float top = cursor.y();
    const float bot = top - row_h;
    cursor.advance(row_h);
    std::vector<uint8_t> bytes(static_cast<size_t>(12) * stride, 0);
    write_row_quad(bytes, x_min, x_max, bot, top, bg);
    buf->submit(bytes);
    Element el;
    el.buffer = buf;
    el.bounds_hint = Kinesis::AABB2D { .min = { x_min, bot }, .max = { x_max, top } };
    el.interactive = false;
    el.name = spec.label;
    const uint32_t id = layer.add(std::move(el));
    Link link(
        [] { },
        [reader = spec.reader,
            label = spec.label,
            text_image,
            buf,
            staging,
            params]() mutable {
            if (!buf || !reader)
                return;
            Portal::Text::repress(text_image,
                label + ": " + reader(),
                params, staging);
            buf->bind_texture(0, text_image);
        });
    return ValueRow {
        .element_id = id,
        .buf = buf,
        .text = text_image,
        .link = std::move(link),
    };
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::LayoutCursor::advance(), MayaFlux::Portal::Forma::Element::bounds_hint, MayaFlux::Portal::Forma::Element::buffer, MayaFlux::Portal::Text::PressParams::color, create_buffer(), MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Portal::Forma::ValueRow::element_id, MayaFlux::Kakshya::VertexLayout::for_meshes(), id, MayaFlux::Portal::Forma::Element::interactive, MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Element::name, MayaFlux::Portal::Text::press(), MayaFlux::Portal::Forma::ValueSpec::reader, MayaFlux::Portal::Text::repress(), row_pixel_dims(), MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Portal::Graphics::TRIANGLE_LIST, and MayaFlux::Portal::Forma::LayoutCursor::y().
Referenced by make_value_group().