MayaFlux: MayaFlux::Nodes::atomic_inc_modulator_count
atomic_inc_modulator_count()
void MayaFlux::Nodes::atomic_inc_modulator_count (std::atomic< uint32_t > & count, int amount)
Atomically increments the modulator count by a specified amount.
Parameters
count The atomic counter to increment
amount The amount to increment by
Increases a node's modulator count, which tracks how many other nodes are currently using this node as a modulation source. This count is crucial for determining when a node's processed state can be safely reset, preventing redundant processing while ensuring all dependent nodes receive the correct modulation values.
Definition at line 87 of file NodeUtils.cpp.
{
    count.fetch_add(amount, std::memory_order_relaxed);
}
References count.
Referenced by MayaFlux::Nodes::ChainNode::process_sample(), MayaFlux::Nodes::BinaryOpNode::process_sample(), MayaFlux::Nodes::CompositeOpNode< N >::process_sample(), MayaFlux::Nodes::Filters::FIR::process_sample(), MayaFlux::Nodes::Filters::IIR::process_sample(), MayaFlux::Nodes::Generator::Impulse::process_sample(), MayaFlux::Nodes::Generator::Logic::process_sample(), MayaFlux::Nodes::Generator::Phasor::process_sample(), MayaFlux::Nodes::Generator::Polynomial::process_sample(), MayaFlux::Nodes::Generator::Sine::process_sample(), MayaFlux::Nodes::Generator::Counter::process_sample(), and MayaFlux::Buffers::FilterProcessor::process_single_sample().