MayaFlux: MayaFlux::Yantra::generate_span_sort_indices
generate_span_sort_indices()
std::vector< size_t > MayaFlux::Yantra::generate_span_sort_indices (std::span< double > data, SortingDirection direction)
Generate sort indices for a single span.
Parameters
data Input span
direction Sort direction
Returns
Vector of sorted indices
Definition at line 58 of file SortingHelper.cpp.
{
    std::vector<size_t> indices(data.size());
    std::iota(indices.begin(), indices.end(), 0);
    if (data.empty()) {
        return indices;
    }
    auto comp = create_double_comparator(direction);
    std::ranges::sort(indices, [&](size_t a, size_t b) {
        return comp(data[a], data[b]);
    });
    return indices;
}
References a, b, and create_double_comparator().
Referenced by generate_channels_sort_indices(), and generate_compute_data_indices().