MayaFlux: MayaFlux::Config::load_config_from_file
load_config_from_file()
MAYAFLUX_API bool MayaFlux::Config::load_config_from_file (const std::string & path)
Load engine configuration from a JSON file, applying any present fields to the pre-Init config structs.
Parameters
path Path to a mayaflux.json file.
Returns
True if the file was read and at least partially applied. False if the file could not be opened or parsed; last_error() will be set.
Note
Must be called before Init(). Fields absent from the file retain defaults.
Definition at line 164 of file Config.cpp.
{
    IO::JSONSerializer ser;
    auto result = ser.read<EngineConfig>(path);
    if (!result) {
        MF_ERROR(Journal::Component::API, Journal::Context::Configuration,
            "Failed to load config from {}: {}", path, ser.last_error());
        return false;
    }
    get_global_stream_info() = result->stream;
    get_global_graphics_config() = result->graphics;
    get_global_input_config() = result->input;
    get_global_network_config() = result->network;
    const auto& j = result->journal;
    if (!j.severity.empty()) {
        auto sev = Reflect::string_to_enum_case_insensitive<Journal::Severity>(j.severity);
        if (sev) {
            Config::set_journal_severity(*sev);
        } else {
            MF_WARN(Journal::Component::API, Journal::Context::Configuration,
                "Unknown journal severity: {}", j.severity);
        }
    }
    if (j.sink_to_console)
        Config::sink_journal_to_console();
    if (!j.log_file.empty())
        Config::store_journal_entries(j.log_file);
    for (const auto& name : j.disable_components) {
        auto comp = Reflect::string_to_enum_case_insensitive<Journal::Component>(name);
        if (comp) {
            Config::set_journal_component_filter({ *comp }, false);
        } else {
            MF_WARN(Journal::Component::API, Journal::Context::Configuration,
                "Unknown journal component: {}", name);
        }
    }
    for (const auto& name : j.disable_contexts) {
        auto ctx = Reflect::string_to_enum_case_insensitive<Journal::Context>(name);
        if (ctx) {
            Config::set_journal_context_filter({ *ctx }, false);
        } else {
            MF_WARN(Journal::Component::API, Journal::Context::Configuration,
                "Unknown journal context: {}", name);
        }
    }
    return true;
}
References MayaFlux::Journal::API, MayaFlux::Journal::Configuration, get_global_graphics_config(), get_global_input_config(), get_global_network_config(), get_global_stream_info(), MayaFlux::IO::JSONSerializer::last_error(), MF_ERROR, MF_WARN, MayaFlux::IO::JSONSerializer::read(), set_journal_component_filter(), set_journal_context_filter(), set_journal_severity(), sink_journal_to_console(), and store_journal_entries().
Referenced by main().