MayaFlux: MayaFlux::Nexus::remove_render_sink
remove_render_sink()
void MayaFlux::Nexus::remove_render_sink (std::vector< RenderSink > & sinks, Buffers::BufferManager & mgr, const std::shared_ptr< Core::Window > & window)
Unregister and destroy the render sink targeting window.
Parameters
sinks Sink vector owned by the calling Emitter or Agent.
mgr BufferManager the VKBuffer was registered with.
window Window passed to add_render_sink().
Definition at line 194 of file Sinks.cpp.
{
    auto it = std::ranges::find_if(sinks,
        [&window](const RenderSink& s) { return s.window == window; });
    if (it == sinks.end()) {
        MF_WARN(Journal::Component::Buffers, Journal::Context::Init,
            "Nexus: remove_render_sink called but no sink found for given window");
        return;
    }
    mgr.remove_buffer(it->buf, Buffers::ProcessingToken::GRAPHICS_BACKEND);
    sinks.erase(it);
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::Init,
        "Nexus: render sink removed");
}
References MayaFlux::Journal::Buffers, MayaFlux::Buffers::GRAPHICS_BACKEND, MayaFlux::Journal::Init, MF_DEBUG, MF_WARN, MayaFlux::Buffers::BufferManager::remove_buffer(), and MayaFlux::Nexus::RenderSink::window.
Referenced by MayaFlux::Nexus::Agent::remove_render(), and MayaFlux::Nexus::Emitter::remove_render().