MayaFlux: MayaFlux::Kinesis::ndc_size_to_pixels
ndc_size_to_pixels() [1/2]
glm::uvec2 MayaFlux::Kinesis::ndc_size_to_pixels (const AABB2D & region, uint32_t width, uint32_t height) inline
Convert an NDC AABB's extent to integer pixel dimensions.
Equivalent to ndc_size_to_pixels(region.max - region.min, width, height).
Parameters
region NDC axis-aligned bounding box.
width Window width in pixels.
height Window height in pixels.
Returns
Integer pixel dimensions of the region's extent.
Definition at line 443 of file Bounds.hpp.
{
    return ndc_size_to_pixels(region.max - region.min, width, height);
}
References MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, ndc_size_to_pixels(), and width.
Referenced by ndc_size_to_pixels(), MayaFlux::normalized_size_to_pixels(), MayaFlux::normalized_size_to_pixels(), MayaFlux::normalized_size_to_pixels(), MayaFlux::normalized_size_to_pixels(), and MayaFlux::Portal::Forma::Plot::place_label().