MayaFlux: MayaFlux::Portal::Forma::Plot::place_rect
place_rect()
MAYAFLUX_API uint32_t MayaFlux::Portal::Forma::Plot::place_rect (Surface & surface, std::shared_ptr< Buffers::FormaBuffer > buf, const RectSpec & spec, uint32_t relate_to = 0)
Place a filled rectangle element onto surface using a pre-built buffer.
buf must be a plain TRIANGLE_STRIP FormaBuffer with no texture slot. Buffer construction is the caller's responsibility.
Parameters
surface Target surface.
buf FormaBuffer sized for 4 vertices.
spec Rectangle geometry and color.
relate_to If non-zero, the produced element is related to this id.
Returns
Element id of the produced rect element.
Definition at line 53 of file Plot.cpp.
{
    const auto verts = Kinesis::filled_rect(spec.bounds, spec.color);
    buf->submit(verts);
    Element el;
    el.with_buffer(std::move(buf))
        .with_bounds(spec.bounds)
        .with_name(spec.name);
    if (!spec.interactive)
        el.non_interactive();
    const uint32_t id = surface.layer().add(std::move(el));
    if (relate_to != 0)
        surface.layer().relate(relate_to, id);
    return id;
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::Plot::RectSpec::bounds, MayaFlux::Portal::Forma::Plot::RectSpec::color, MayaFlux::Kinesis::filled_rect(), MayaFlux::Portal::Forma::Plot::RectSpec::interactive, MayaFlux::Portal::Forma::Surface::layer(), MayaFlux::Portal::Forma::Plot::RectSpec::name, MayaFlux::Portal::Forma::Element::non_interactive(), MayaFlux::Portal::Forma::Layer::relate(), MayaFlux::Portal::Forma::Element::with_bounds(), MayaFlux::Portal::Forma::Element::with_buffer(), and MayaFlux::Portal::Forma::Element::with_name().