MayaFlux: MayaFlux::register_audio_node
register_audio_node() [2/2]
MAYAFLUX_API void MayaFlux::register_audio_node (const std::shared_ptr< Nodes::Node > & node, uint32_t channel = 0)
Adds a node to the root node of a specific channel.
Parameters
node Node to add
channel Channel index
Adds the node as a child of the root node for the specified channel. Uses the default engine's node graph manager.
Definition at line 38 of file Graph.cpp.
{
    auto manager = get_node_graph_manager();
    if (!manager) {
        MF_ERROR(Journal::Component::API, Journal::Context::NodeProcessing,
            "Node graph manager not initialized - cannot register audio node");
        return;
    }
    if (channel >= manager->get_channel_count(Nodes::ProcessingToken::AUDIO_RATE)) {
        std::out_of_range err("Channel index out of range for audio node registration");
        std::cerr << err.what() << '\n';
    }
    manager->add_to_root(node, Nodes::ProcessingToken::AUDIO_RATE, channel);
}
References MayaFlux::Journal::API, MayaFlux::Nodes::AUDIO_RATE, get_node_graph_manager(), MF_ERROR, and MayaFlux::Journal::NodeProcessing.
Referenced by create_node(), MayaFlux::Nodes::ChainNode::initialize(), MayaFlux::Nodes::BinaryOpNode::initialize(), and register_audio_node().