MayaFlux: MayaFlux::Config::get_node_config
get_node_config()
MAYAFLUX_API Nodes::NodeConfig & MayaFlux::Config::get_node_config ()
Definition at line 43 of file Config.cpp.
{ return node_config; }
References node_config.
Referenced by MayaFlux::Nodes::get_active_channels(), MayaFlux::Nodes::ChainNode::initialize(), and MayaFlux::Nodes::BinaryOpNode::initialize().