MayaFlux: MayaFlux::Buffers::upload_structured_view
upload_structured_view()
template<typename T > requires GlmType<T> void MayaFlux::Buffers::upload_structured_view (const Kakshya::DataAccess & accessor, const std::shared_ptr< VKBuffer > & target, const std::shared_ptr< VKBuffer > & staging = nullptr)
Upload structured data with GLM double-precision types.
Template Parameters
T GLM type (glm::dvec2, glm::dvec3, glm::dvec4 for double precision)
Parameters
accessor DataAccess with structured dimensions
target Target GPU buffer
staging Optional staging buffer
Use this for high-precision structured data like audio samples interpreted as multi-dimensional vectors. Supports both single and double precision GLM types.
Definition at line 220 of file StagingUtils.hpp.
{
    if (!accessor.is_structured()) {
        error<std::invalid_argument>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Cannot upload structured view from non-structured data");
    }
    auto structured_view = accessor.view<T>();
    upload_to_gpu(structured_view.data(), structured_view.size_bytes(), target, staging);
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Kakshya::DataAccess::is_structured(), upload_to_gpu(), and MayaFlux::Kakshya::DataAccess::view().