MayaFlux: MayaFlux::is_engine_initialized
is_engine_initialized()
MAYAFLUX_API bool MayaFlux::is_engine_initialized ()
Checks if the default audio engine is initialized.
Returns
True if the engine is initialized, false otherwise
Definition at line 9 of file Config.cpp.
{
    return is_initialized();
}
References is_initialized().
Referenced by MayaFlux::Nodes::Generator::Impulse::update_phase_increment(), MayaFlux::Nodes::Generator::Phasor::update_phase_increment(), and MayaFlux::Nodes::Generator::Sine::update_phase_increment().