MayaFlux: MayaFlux::Portal::Forma::Plot::series
series()
Series MayaFlux::Portal::Forma::Plot::series () inline
Begin a Series chain.
Convenience constructor for GeometryFn<shared_ptr<PlotContainer>>. Illustrative, not idiomatic. The raw GeometryFn lambda is always the primary path and is preferred when the builder cannot express what you need.
// 7 SPATIAL_Y series -> 7 waveforms, blue palette
auto geom = Plot::series()
    .y(Role::SPATIAL_Y, AxisRange{}.auto_scale(), { 0.2F, 0.8F, 1.0F })
    .as_waveform()
    .thickness(1.5F)
    .done();
// Lissajous scatter, X and Y each with their own range
auto geom = Plot::series()
    .x(Role::SPATIAL_X, AxisRange{}.range(-1.F, 1.F))
    .y(Role::SPATIAL_Y, AxisRange{}.range(-1.F, 1.F), { 0.9F, 0.3F, 0.8F })
    .as_scatter()
    .point_size(3.F)
    .done();
Definition at line 109 of file Plot.hpp.
{
    return Series {};
}
Referenced by apply_auto_scale(), data_range(), MayaFlux::Portal::Forma::Plot::WaveformBuilder::done(), and MayaFlux::Portal::Forma::Plot::BarsBuilder::done().