MayaFlux: MayaFlux::Core::vk_format_bytes_per_pixel
vk_format_bytes_per_pixel()
uint32_t MayaFlux::Core::vk_format_bytes_per_pixel (vk::Format fmt) inline
Byte width of a single pixel for a given Vulkan format.
Covers all formats currently tracked in GraphicsSurfaceInfo plus the full set used by VKImage (depth, stencil, compute). Returns 4 with a warning for unknown formats, matching the previous VKImage fallback behaviour.
Parameters
fmt Vulkan format.
Returns
Bytes per pixel, or 4 on unknown formats.
Definition at line 92 of file VKEnumUtils.hpp.
{
    switch (fmt) {
    case vk::Format::eR8Unorm:
    case vk::Format::eR8Snorm:
    case vk::Format::eR8Uint:
    case vk::Format::eR8Sint:
        return 1U;
    case vk::Format::eR8G8Unorm:
    case vk::Format::eR8G8Snorm:
    case vk::Format::eR8G8Uint:
    case vk::Format::eR8G8Sint:
    case vk::Format::eR16Unorm:
    case vk::Format::eR16Snorm:
    case vk::Format::eR16Uint:
    case vk::Format::eR16Sint:
    case vk::Format::eR16Sfloat:
        return 2U;
    case vk::Format::eR8G8B8Unorm:
    case vk::Format::eR8G8B8Snorm:
    case vk::Format::eR8G8B8Uint:
    case vk::Format::eR8G8B8Sint:
    case vk::Format::eB8G8R8Unorm:
        return 3U;
    case vk::Format::eR8G8B8A8Unorm:
    case vk::Format::eR8G8B8A8Snorm:
    case vk::Format::eR8G8B8A8Uint:
    case vk::Format::eR8G8B8A8Sint:
    case vk::Format::eR8G8B8A8Srgb:
    case vk::Format::eB8G8R8A8Unorm:
    case vk::Format::eB8G8R8A8Srgb:
    case vk::Format::eR16G16Unorm:
    case vk::Format::eR16G16Snorm:
    case vk::Format::eR16G16Uint:
    case vk::Format::eR16G16Sint:
    case vk::Format::eR16G16Sfloat:
    case vk::Format::eR32Uint:
    case vk::Format::eR32Sint:
    case vk::Format::eR32Sfloat:
    case vk::Format::eD24UnormS8Uint:
    case vk::Format::eD32Sfloat:
    case vk::Format::eA2B10G10R10UnormPack32:
        return 4U;
    case vk::Format::eR16G16B16A16Unorm:
    case vk::Format::eR16G16B16A16Snorm:
    case vk::Format::eR16G16B16A16Uint:
    case vk::Format::eR16G16B16A16Sint:
    case vk::Format::eR16G16B16A16Sfloat:
    case vk::Format::eR32G32Uint:
    case vk::Format::eR32G32Sint:
    case vk::Format::eR32G32Sfloat:
        return 8U;
    case vk::Format::eR32G32B32Uint:
    case vk::Format::eR32G32B32Sint:
    case vk::Format::eR32G32B32Sfloat:
        return 12U;
    case vk::Format::eR32G32B32A32Uint:
    case vk::Format::eR32G32B32A32Sint:
    case vk::Format::eR32G32B32A32Sfloat:
        return 16U;
    default:
        return 4U;
    }
}
Referenced by MayaFlux::Core::VKImage::get_size_bytes(), MayaFlux::Kakshya::WindowAccessProcessor::on_attach(), MayaFlux::Kakshya::WindowAccessProcessor::process(), and MayaFlux::Kakshya::readback_region().