MayaFlux: MayaFlux::get_input_manager
get_input_manager()
MAYAFLUX_API Core::InputManager & MayaFlux::get_input_manager ()
Gets a handle to default input manager.
Returns
Reference to the InputManager
Definition at line 16 of file Input.cpp.
{
    return *get_context().get_input_manager();
}
References get_context(), and MayaFlux::Core::Engine::get_input_manager().
Referenced by register_input_node(), and unregister_input_node().