MayaFlux: MayaFlux::Reflect::enum_to_string
enum_to_string()
template<typename EnumType > constexpr std::string_view MayaFlux::Reflect::enum_to_string (EnumType value) constexpr noexcept
Universal enum to string converter using magic_enum (original case)
Template Parameters
EnumType Any enum type
Parameters
value Enum value to convert
Returns
String representation of the enum
Definition at line 57 of file EnumReflect.hpp.
{
    return magic_enum::enum_name(value);
}
Referenced by MayaFlux::Nodes::Network::WaveguideNetwork::get_metadata(), MayaFlux::Core::Engine::Init(), MayaFlux::Kakshya::EigenInsertion::insert_matrix(), MayaFlux::Kakshya::modality_to_string(), MayaFlux::Nodes::Network::NodeNetwork::output_mode_to_string(), MayaFlux::Kriya::BufferPipeline::process_operation(), MayaFlux::IO::to_string(), MayaFlux::Nodes::Network::NodeNetwork::topology_to_string(), MayaFlux::Kakshya::EigenInsertion::validate_matrix_dimensions(), MayaFlux::Journal::Archivist::Impl::write_to_console(), and MayaFlux::Journal::Archivist::Impl::write_to_console().