MayaFlux: MayaFlux::Yantra::generate_compute_data_indices
generate_compute_data_indices()
template<ComputeData T> std::vector< std::vector< size_t > > MayaFlux::Yantra::generate_compute_data_indices (const IO< T > & data, SortingDirection direction)
Generate sort indices for any ComputeData type.
Template Parameters
T ComputeData type
Parameters
data Data to generate indices for
direction Sort direction
Returns
Vector of index vectors (one per channel)
Definition at line 334 of file SortingHelper.hpp.
{
    if constexpr (RequiresContainer<T>) {
        auto channels = OperationHelper::extract_numeric_data(data.data, data.container.value());
        return generate_channels_sort_indices(channels, direction);
    }
    if constexpr (SingleVariant<T>) {
        auto channel = OperationHelper::extract_numeric_data(data.data);
        return { generate_span_sort_indices({ channel }, direction) };
    } else {
        auto channels = OperationHelper::extract_numeric_data(data.data, data.needs_processig());
        return generate_channels_sort_indices(channels, direction);
    }
}
References MayaFlux::Yantra::IO< T >::container, MayaFlux::Yantra::IO< T >::data, MayaFlux::Yantra::OperationHelper::extract_numeric_data(), generate_channels_sort_indices(), generate_span_sort_indices(), and MayaFlux::Yantra::IO< T >::needs_processig().
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::sort_indices_only().