MayaFlux: MayaFlux::Portal::Forma::make_value_group
make_value_group()
ValueGroup MayaFlux::Portal::Forma::make_value_group (std::string_view header_label, std::span< const ValueSpec > values, Layer & layer, Context & context, const std::shared_ptr< Core::Window > & window, LayoutCursor & cursor, float x_min, float x_max, float row_h, bool initially_open = false)
Construct a collapsible header followed by N value rows under it.
The header label may include its own dynamic data if the caller wants it visible while collapsed; once expanded, all rows in values become visible via the relation cascade.
Each value row is a separate Element relate'd to the header. Visibility tracks the header's open state.
Parameters
header_label Static text composited into the header's label image.
values Specs for each body row. Order is preserved top-to-bottom.
initially_open Default false so deep trees stay collapsed at construction.
Definition at line 138 of file QueryUtils.cpp.
{
    const auto [tw, th] = row_pixel_dims(window, x_min, x_max, row_h);
    auto header_text = Portal::Text::press(
        header_label,
        { tw, th },
        Portal::Text::PressParams {
            .color = { 1.F, 1.F, 1.F, 1.F },
            .budget_h = th,
        });
    auto header = make_collapsible(
        window, layer, context, get_bridge(), cursor,
        x_min, x_max, row_h, initially_open,
        glm::vec3(0.25F), glm::vec3(0.35F),
        header_text);
    std::vector<ValueRow> rows;
    rows.reserve(values.size());
    for (const auto& spec : values) {
        auto row = make_value_row(spec, layer, window, cursor,
            x_min, x_max, row_h);
        header.attach(layer, row.element_id);
        rows.push_back(std::move(row));
    }
    header.cursor_out = cursor;
    return ValueGroup {
        .header = std::move(header),
        .rows = std::move(rows),
    };
}
References MayaFlux::Portal::Text::PressParams::color, get_bridge(), MayaFlux::Portal::Forma::ValueGroup::header, make_collapsible(), make_value_row(), MayaFlux::Portal::Text::press(), and row_pixel_dims().
Referenced by MayaFlux::Portal::Forma::Inspector::buffer(), MayaFlux::Portal::Forma::Inspector::buffer_manager(), MayaFlux::Portal::Forma::Inspector::node(), MayaFlux::Portal::Forma::Inspector::node_graph_manager(), MayaFlux::Portal::Forma::Inspector::node_network(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_graphics_buffer(), MayaFlux::Portal::Forma::Inspector::scheduler(), and MayaFlux::Portal::Forma::Inspector::tasks().