MayaFlux: MayaFlux::Config::store_journal_entries
store_journal_entries()
MAYAFLUX_API void MayaFlux::Config::store_journal_entries (const std::string & file_name)
Stores journal entries to a file by adding a FileSink to the Archivist.
Parameters
file_name Path to the log file
Definition at line 77 of file Config.cpp.
{
    Journal::Archivist::instance().add_sink(std::make_unique<Journal::FileSink>(file_name));
    set_journal_severity(Journal::Severity::TRACE);
}
References MayaFlux::Journal::Archivist::add_sink(), MayaFlux::Journal::Archivist::instance(), set_journal_severity(), and MayaFlux::Journal::TRACE.