MayaFlux: MayaFlux::Portal::Forma::Plot::background
background()
MAYAFLUX_API GeometryFn< float > MayaFlux::Portal::Forma::Plot::background (Kinesis::AABB2D bounds, glm::vec3 color = glm::vec3(1.F), const std::shared_ptr< Core::VKImage > & texture = nullptr)
TRIANGLE_STRIP background quad for a plot area.
Produces a solid-color or textured full-screen quad covering bounds. Intended to be added to the same Layer as a plot element via Layer::relate, rendered before it.
When texture is non-null the quad uses the textured vertex path and the caller must pass a matching FormaBuffer with a texture binding. When null the quad is filled with color.
T is float (a dummy tick value — the background is static unless the caller drives it). Write any float to state->write() to refresh.
Parameters
bounds Plot area in NDC.
color Fill color when no texture is provided.
texture Optional GPU image. nullptr = solid color.
Definition at line 88 of file PlotSpec.cpp.
{
    return [bounds, color, texture](
               float,
               std::vector<uint8_t>& out,
               Element& el) {
        out.clear();
        if (texture) {
            const uint32_t stride = Kakshya::VertexLayout::for_textured_quad().stride_bytes;
            const std::array<std::pair<glm::vec3, glm::vec2>, 4> verts = { {
                { { bounds.min.x, bounds.min.y, 0.F }, { 0.F, 1.F } },
                { { bounds.max.x, bounds.min.y, 0.F }, { 1.F, 1.F } },
                { { bounds.min.x, bounds.max.y, 0.F }, { 0.F, 0.F } },
                { { bounds.max.x, bounds.max.y, 0.F }, { 1.F, 0.F } },
            } };
            out.resize(static_cast<size_t>(4) * stride);
            for (size_t i = 0; i < 4; ++i) {
                uint8_t* v = out.data() + i * stride;
                std::memcpy(v, &verts[i].first, 12);
                std::memcpy(v + 12, &verts[i].second, 8);
            }
        } else {
            const uint32_t stride = Kakshya::VertexLayout::for_meshes().stride_bytes;
            constexpr glm::vec3 k_normal { 0.F, 0.F, 1.F };
            constexpr glm::vec3 k_tangent { 1.F, 0.F, 0.F };
            constexpr glm::vec2 k_uv { 0.F, 0.F };
            constexpr float k_weight = 0.F;
            const std::array<glm::vec3, 4> positions = { {
                { bounds.min.x, bounds.min.y, 0.F },
                { bounds.max.x, bounds.min.y, 0.F },
                { bounds.min.x, bounds.max.y, 0.F },
                { bounds.max.x, bounds.max.y, 0.F },
            } };
            out.resize(static_cast<size_t>(4) * stride, 0);
            for (size_t i = 0; i < 4; ++i) {
                uint8_t* v = out.data() + i * stride;
                std::memcpy(v, &positions[i], 12);
                std::memcpy(v + 12, &color, 12);
                std::memcpy(v + 24, &k_weight, 4);
                std::memcpy(v + 28, &k_uv, 8);
                std::memcpy(v + 36, &k_normal, 12);
                std::memcpy(v + 48, &k_tangent, 12);
            }
        }
        el.bounds_hint = bounds;
    };
}
References MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Kakshya::VertexLayout::for_textured_quad(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, and MayaFlux::Kakshya::VertexLayout::stride_bytes.
Referenced by MayaFlux::Portal::Forma::Plot::WaveformBuilder::done(), MayaFlux::Portal::Forma::Plot::ScatterBuilder::done(), MayaFlux::Portal::Forma::Plot::BarsBuilder::done(), and MayaFlux::Portal::Forma::Plot::FilledWaveformBuilder::done().