MayaFlux: MayaFlux::Buffers::upload_resizing
upload_resizing()
MAYAFLUX_API void MayaFlux::Buffers::upload_resizing (const void * data, size_t size, const std::shared_ptr< VKBuffer > & target, const std::shared_ptr< VKBuffer > & staging, float growth_factor = 1.5F)
Upload size bytes to target, growing both buffers first if needed.
Parameters
data Source pointer.
size Byte count to upload.
target Destination GPU buffer.
staging Paired staging buffer, or nullptr for host-visible targets.
growth_factor Forwarded to ensure_gpu_capacity.
Combines ensure_gpu_capacity() and upload_to_gpu() into a single call. The upload is clamped to the post-resize capacity, which is always >= size after ensure_gpu_capacity returns.
Definition at line 326 of file StagingUtils.cpp.
{
    ensure_gpu_capacity(target, staging, size, growth_factor);
    upload_to_gpu(data, size, target, staging);
}
References ensure_gpu_capacity(), size, and upload_to_gpu().
Referenced by MayaFlux::Buffers::GeometryBindingsProcessor::processing_function(), MayaFlux::Buffers::GeometryWriteProcessor::processing_function(), MayaFlux::Buffers::NetworkGeometryProcessor::processing_function(), MayaFlux::Buffers::GeometryBindingsProcessor::upload_index_data(), MayaFlux::Buffers::MeshProcessor::upload_indices(), MayaFlux::Buffers::MeshNetworkProcessor::upload_ssbos(), and MayaFlux::Buffers::MeshProcessor::upload_vertices().