MayaFlux: MayaFlux::seconds_to_blocks
seconds_to_blocks()
MAYAFLUX_API uint64_t MayaFlux::seconds_to_blocks (double seconds)
Converts a time duration in seconds to the equivalent number of processing blocks.
Parameters
seconds Time duration in seconds
Returns
Equivalent number of blocks based on current sample rate and block size
Uses the sample rate and block size from the default engine. Falls back to 48kHz/512 samples if engine is not running.
Definition at line 253 of file Chronie.cpp.
{
    uint32_t sample_rate = 48000;
    uint32_t block_size = 512;
    if (get_context().is_running()) {
        sample_rate = get_context().get_stream_info().sample_rate;
        block_size = get_context().get_stream_info().buffer_size;
    }
    return Vruta::seconds_to_blocks(seconds, sample_rate, block_size);
}
References MayaFlux::Core::GlobalStreamInfo::buffer_size, get_context(), MayaFlux::Core::Engine::get_stream_info(), MayaFlux::Core::GlobalStreamInfo::sample_rate, and MayaFlux::Vruta::seconds_to_blocks().
Referenced by route_buffer().