MayaFlux: MayaFlux::IO::save_image
save_image()
bool MayaFlux::IO::save_image (const std::shared_ptr< Core::VKImage > & image, const std::string & filepath, const ImageWriteOptions & options = {})
Save a VKImage directly to disk via the ImageWriter registry.
Combines download_image() with ImageWriterRegistry::create_writer(). The file extension selects the writer. Format-variant compatibility is the writer's responsibility: saving a float VKImage as PNG will fail at the writer (uint8 mismatch), saving a uint8 VKImage as EXR will fail too.
Parameters
image VKImage to save.
filepath Destination path with extension.
options Format-specific writer options.
Returns
True on success.
Definition at line 148 of file ImageExport.cpp.
{
    auto data = download_image(image);
    if (!data) {
        return false;
    }
    auto writer = ImageWriterRegistry::instance().create_writer(filepath);
    if (!writer) {
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
            "save_image: no writer registered for extension of '{}'", filepath);
        return false;
    }
    const bool ok = writer->write(filepath, *data, options);
    if (!ok) {
        MF_ERROR(Journal::Component::IO, Journal::Context::FileIO,
            "save_image: writer failed: {}", writer->get_last_error());
    }
    return ok;
}
References MayaFlux::IO::ImageWriterRegistry::create_writer(), download_image(), MayaFlux::Journal::FileIO, image, MayaFlux::IO::ImageWriterRegistry::instance(), MayaFlux::Journal::IO, and MF_ERROR.
Referenced by save_texture_buffer().