MayaFlux: MayaFlux::normalized
normalized() [2/2]
MAYAFLUX_API std::vector< double > MayaFlux::normalized (const std::vector< double > & data, double target_peak = 1.0)
Normalize single-channel data (non-destructive)
Parameters
data Input data
target_peak Target peak amplitude (default: 1.0)
Returns
Normalized copy of data
Definition at line 593 of file Yantra.cpp.
{
    auto transformer = std::make_shared<Yantra::MathematicalTransformer<>>(Yantra::MathematicalOperation::NORMALIZE);
    transformer->set_parameter("target_peak", target_peak);
    Yantra::IO<std::vector<Kakshya::DataVariant>> input { { Kakshya::DataVariant(data) } };
    auto result = transformer->apply_operation(input);
    return std::get<std::vector<double>>(result.data[0]);
}
References MayaFlux::Yantra::NORMALIZE.
Referenced by MayaFlux::Nodes::Input::HIDNode::apply_deadzone(), MayaFlux::Nodes::Network::GraphicsOperator::apply_one_to_one(), normalized_channels(), and MayaFlux::Nodes::Input::HIDNode::parse_axis().