MayaFlux: MayaFlux::create_buffer_pipeline
create_buffer_pipeline()
MAYAFLUX_API std::shared_ptr< Kriya::BufferPipeline > MayaFlux::create_buffer_pipeline ()
Creates a new buffer pipeline instance.
Returns
Shared pointer to the created BufferPipeline
Uses the task scheduler from the default engine.
Definition at line 118 of file Chronie.cpp.
{
    return Kriya::BufferPipeline::create(*get_scheduler(), get_context().get_buffer_manager());
}
References MayaFlux::Kriya::BufferPipeline::create(), get_buffer_manager(), get_context(), and get_scheduler().