MayaFlux: MayaFlux::Yantra::find_peak_positions
find_peak_positions()
std::vector< size_t > MayaFlux::Yantra::find_peak_positions (std::span< const double > data, double threshold = 0.0, size_t min_distance = 1)
Find actual peak positions in the signal.
Returns sample indices where local maxima occur above a threshold.
Parameters
data Input data span
threshold Minimum absolute value to be considered a peak
min_distance Minimum samples between peaks (prevents clustering)
Returns
Vector of sample positions where peaks occur
Definition at line 235 of file AnalysisHelper.cpp.
{
    if (data.size() < 3) {
        return {};
    }
    std::vector<size_t> positions;
    positions.reserve(data.size() / 100);
    size_t last_peak = 0;
    for (size_t i = 1; i < data.size() - 1; ++i) {
        double abs_val = std::abs(data[i]);
        if (abs_val > threshold && abs_val >= std::abs(data[i - 1]) && abs_val >= std::abs(data[i + 1])) {
            if (positions.empty() || (i - last_peak) >= min_distance) {
                positions.push_back(i);
                last_peak = i;
            }
        }
    }
    positions.shrink_to_fit();
    return positions;
}
References find_peak_positions().
Referenced by MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::create_analysis_result(), and find_peak_positions().