MayaFlux: MayaFlux::Journal::fatal
fatal() [1/2]
template<typename... Args> void MayaFlux::Journal::fatal (Component component, Context context, std::source_location location, format_string< Args... > fmt_str, Args &&... args)
fmt-style overload of fatal().
Log a fatal message and abort the program.
Parameters
component The component generating the log message.
context The execution context of the log message.
location Source location (file, line, function) of the log call.
message The fatal message content.
Template Parameters
Args Types of the format arguments.
Parameters
fmt_str The format string.
args The format arguments.
Definition at line 249 of file Archivist.hpp.
{
    auto msg = format(fmt_str, std::forward<Args>(args)...);
    Archivist::instance().scribe(Severity::FATAL, component, context, msg, location);
    std::abort();
}
References FATAL, format(), MayaFlux::Journal::Archivist::instance(), and MayaFlux::Journal::Archivist::scribe().