MayaFlux: MayaFlux::std_dev_combined
std_dev_combined()
MAYAFLUX_API double MayaFlux::std_dev_combined (const std::vector< Kakshya::DataVariant > & channels)
Calculate standard deviation across all channels (mix then analyze)
Parameters
channels Vector of channel data
Returns
Single standard deviation value across all mixed channels
Definition at line 154 of file Yantra.cpp.
{
    auto data = Yantra::OperationHelper::extract_numeric_data(channels);
    if (is_same_size(data)) {
        auto result = std_dev_per_channel(channels);
        return std::accumulate(result.begin(), result.end(), 0.0) / result.size();
    } else {
        auto mixed = concat_vectors(data);
        return std_dev(mixed);
    }
}
References concat_vectors(), MayaFlux::Yantra::OperationHelper::extract_numeric_data(), is_same_size(), std_dev(), and std_dev_per_channel().