MayaFlux: MayaFlux::Yantra::transform_wrap
transform_wrap() [1/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_wrap (DataType & input, double wrap_range)
Wrap transformation (modulo operation) using C++20 ranges (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
wrap_range Wrap range [0, wrap_range)
Returns
Wrapped data
Definition at line 485 of file MathematicalHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    for (auto& span : target_data) {
        std::ranges::transform(span, span.begin(),
            [wrap_range](double x) {
                return x - wrap_range * std::floor(x / wrap_range);
            });
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References transform_wrap().
Referenced by transform_wrap(), and transform_wrap().