MayaFlux: MayaFlux::Core::to_vk_format
to_vk_format()
vk::Format MayaFlux::Core::to_vk_format (GraphicsSurfaceInfo::SurfaceFormat fmt) inline
Definition at line 25 of file VKEnumUtils.hpp.
{
    using SF = GraphicsSurfaceInfo::SurfaceFormat;
    switch (fmt) {
    case SF::B8G8R8A8_SRGB:
        return vk::Format::eB8G8R8A8Srgb;
    case SF::R8G8B8A8_SRGB:
        return vk::Format::eR8G8B8A8Srgb;
    case SF::B8G8R8A8_UNORM:
        return vk::Format::eB8G8R8A8Unorm;
    case SF::R8G8B8A8_UNORM:
        return vk::Format::eR8G8B8A8Unorm;
    case SF::R16G16B16A16_SFLOAT:
        return vk::Format::eR16G16B16A16Sfloat;
    case SF::A2B10G10R10_UNORM:
        return vk::Format::eA2B10G10R10UnormPack32;
    case SF::R32G32B32A32_SFLOAT:
        return vk::Format::eR32G32B32A32Sfloat;
    default:
        return vk::Format::eB8G8R8A8Srgb;
    }
}
Referenced by MayaFlux::Core::VKSwapchain::choose_surface_format(), MayaFlux::Kakshya::WindowAccessProcessor::on_attach(), and MayaFlux::Kakshya::WindowAccessProcessor::process().