MayaFlux: MayaFlux::Vruta::units_to_seconds
units_to_seconds()
double MayaFlux::Vruta::units_to_seconds (uint64_t units, uint32_t rate) inline
Convert processing units to seconds for any rate.
Parameters
units Number of processing units
rate Processing rate (samples/sec, frames/sec, etc.)
Returns
Time duration in seconds
Definition at line 130 of file ChronUtils.hpp.
{
    return static_cast<double>(units) / rate;
}
Referenced by blocks_to_seconds(), MayaFlux::Vruta::SampleClock::current_time(), MayaFlux::Vruta::FrameClock::current_time(), and MayaFlux::Vruta::CustomClock::current_time().