MayaFlux: MayaFlux::Yantra::transform_window
transform_window() [2/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_window (DataType & input, Nodes::Generator::WindowType window_type, uint32_t window_size = 0)
Windowing transformation using C++20 ranges (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
window_type Type of window to apply
window_size Size of window (0 = full data size)
Returns
Windowed data
Definition at line 101 of file SpectralHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    uint32_t size = window_size > 0 ? window_size : smallest_size(target_data);
    auto window = Nodes::Generator::generate_window(size, window_type);
    for (auto& span : target_data) {
        auto data_view = span | std::views::take(std::min(size, static_cast<uint32_t>(span.size())));
        auto window_view = window | std::views::take(data_view.size());
        std::ranges::transform(data_view, window_view, data_view.begin(),
            [](double sample, double win) { return sample * win; });
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References MayaFlux::Yantra::OperationHelper::extract_structured_double(), MayaFlux::Nodes::Generator::generate_window(), and smallest_size().