MayaFlux: MayaFlux::supply_buffer_to_channel
supply_buffer_to_channel()
MAYAFLUX_API void MayaFlux::supply_buffer_to_channel (const std::shared_ptr< Buffers::AudioBuffer > & buffer, uint32_t channel, double mix = 1.0)
Supplies a buffer to a single channel with mixing.
Parameters
buffer Source buffer to supply
channel Target channel index
mix Mix level (default: 1.0)
Convenience wrapper for single-channel buffer supply operations.
Definition at line 283 of file Graph.cpp.
{
    auto manager = get_buffer_manager();
    if (!manager) {
        MF_ERROR(Journal::Component::API, Journal::Context::NodeProcessing,
            "Buffer manager not initialized - cannot perform supply_buffer_to_channel");
        return;
    }
    if (channel < manager->get_num_channels(Buffers::ProcessingToken::AUDIO_BACKEND)) {
        manager->supply_buffer_to(buffer, Buffers::ProcessingToken::AUDIO_BACKEND, channel, mix);
    }
}
References MayaFlux::Journal::API, MayaFlux::Buffers::AUDIO_BACKEND, channel, get_buffer_manager(), MF_ERROR, mix(), and MayaFlux::Journal::NodeProcessing.
Referenced by supply_buffer_to_channels().