MayaFlux: MayaFlux::Kakshya::as_normalised_float
as_normalised_float()
MAYAFLUX_API std::span< const float > MayaFlux::Kakshya::as_normalised_float (const DataVariant & variant, std::vector< float > & storage)
Extract a DataVariant holding pixel data as a normalised float span.
Normalisation factors: uint8_t -> divided by 255.0f uint16_t -> divided by 65535.0f float -> zero-copy span directly into the variant's storage
Does not mutate the variant. Writes into storage only when conversion is required. Returns an empty span if the active alternative is not one of the three pixel types (double, complex, and GLM variants return empty).
Parameters
variant Source DataVariant.
storage Caller-supplied buffer. Reuse across calls to avoid per-frame allocation. Untouched when float is active.
Returns
Normalised float span. Points into storage for uint8/uint16, directly into the variant's internal storage for float.
Definition at line 61 of file DataUtils.cpp.
{
    return std::visit([&storage](const auto& vec) -> std::span<const float> {
        using T = typename std::decay_t<decltype(vec)>::value_type;
        if constexpr (std::is_same_v<T, float>) {
            return { vec.data(), vec.size() };
        } else if constexpr (std::is_same_v<T, uint8_t>) {
            storage.resize(vec.size());
            constexpr float k = 1.0F / 255.0F;
            std::transform(Parallel::par_unseq,
                vec.begin(), vec.end(), storage.begin(),
                [](uint8_t v) { return static_cast<float>(v) * k; });
            return { storage.data(), storage.size() };
        } else if constexpr (std::is_same_v<T, uint16_t>) {
            storage.resize(vec.size());
            constexpr float k = 1.0F / 65535.0F;
            std::transform(Parallel::par_unseq,
                vec.begin(), vec.end(), storage.begin(),
                [](uint16_t v) { return static_cast<float>(v) * k; });
            return { storage.data(), storage.size() };
        } else {
            return {};
        }
    },
        variant);
}
References storage.
Referenced by MayaFlux::Yantra::VisionAnalyzer< InputType, OutputType >::analyze_implementation(), MayaFlux::Buffers::download_and_normalise(), MayaFlux::Kakshya::WindowContainer::processed_frame_as_float(), and MayaFlux::Kakshya::VideoStreamContainer::processed_frame_as_float().