MayaFlux: MayaFlux::Kinesis::Discrete::normalize
normalize()
void MayaFlux::Kinesis::Discrete::normalize (std::span< double > data, double target_min = -1.0, double target_max = 1.0) noexcept
Normalize to [target_min, target_max] in-place Single-pass min/max reduction followed by a single transform pass.
No-op when all values are equal.
Parameters
data Target span
target_min Output minimum
target_max Output maximum
Definition at line 61 of file Transform.cpp.
{
    if (data.empty())
        return;
    double lo = data[0];
    double hi = data[0];
    for (double v : data) {
        if (v < lo)
            lo = v;
        if (v > hi)
            hi = v;
    }
    if (hi == lo)
        return;
    const double inv_src = 1.0 / (hi - lo);
    const double dst_range = target_max - target_min;
    std::ranges::transform(data, data.begin(),
        [lo, inv_src, dst_range, target_min](double x) {
            return (x - lo) * inv_src * dst_range + target_min;
        });
}
Referenced by cross_correlate(), MayaFlux::normalize(), MayaFlux::normalize(), MayaFlux::normalized(), and MayaFlux::normalized().