MayaFlux: MayaFlux::Portal::Forma::make_value_group
make_value_group()
ValueGroup MayaFlux::Portal::Forma::make_value_group (std::span< const ValueSpec > values, RowBuffer header_buf, std::span< const RowBuffer > row_bufs, Surface & surface, LayoutCursor & cursor, float x_min, float x_max, float row_h, bool initially_open = false)
Construct a collapsible header followed by N value rows under it.
The header and all row buffers are pre-created by the caller. Once expanded, all rows in values become visible via the relation cascade. Visibility tracks the header's open state.
Parameters
values Specs for each body row. Order is preserved top-to-bottom.
header_buf Pre-created buffer and text image for the header strip.
row_bufs Pre-created buffers and text images, one per entry in values.
surface Surface to register the header and rows on.
cursor Layout cursor. Advanced across header and all rows on return.
x_min Left edge in NDC.
x_max Right edge in NDC.
row_h Row height in NDC units.
initially_open Default false so deep trees stay collapsed at construction.
Definition at line 132 of file QueryUtils.cpp.
{
    auto header = Collapsible {}
                      .initially_open(initially_open)
                      .closed_color(glm::vec3(0.25F))
                      .open_color(glm::vec3(0.35F))
                      .label(header_buf.text_image)
                      .place(std::move(header_buf.buf), surface, cursor, x_min, x_max, row_h);
    std::vector<ValueRow> rows;
    rows.reserve(values.size());
    for (size_t i = 0; i < values.size(); ++i) {
        auto row = make_value_row(values[i], row_bufs[i], surface, cursor, x_min, x_max, row_h);
        header.attach(surface.layer(), row.element_id);
        rows.push_back(std::move(row));
    }
    header.cursor_out = cursor;
    return ValueGroup {
        .header = std::move(header),
        .rows = std::move(rows),
    };
}
References MayaFlux::Portal::Forma::RowBuffer::buf, MayaFlux::Portal::Forma::Collapsible::closed_color(), MayaFlux::Portal::Forma::ValueGroup::header, MayaFlux::Portal::Forma::Collapsible::initially_open(), MayaFlux::Portal::Forma::Collapsible::label(), MayaFlux::Portal::Forma::Surface::layer(), make_value_row(), MayaFlux::Portal::Forma::Collapsible::open_color(), MayaFlux::Portal::Forma::Collapsible::place(), and MayaFlux::Portal::Forma::RowBuffer::text_image.
Referenced by MayaFlux::Portal::Forma::Inspector::buffer(), MayaFlux::Portal::Forma::Inspector::buffer_manager(), MayaFlux::Portal::Forma::Inspector::event(), MayaFlux::Portal::Forma::Inspector::event_manager(), MayaFlux::Portal::Forma::Inspector::inspect_modulator_tree(), MayaFlux::Portal::Forma::Inspector::inspect_task(), MayaFlux::Portal::Forma::Inspector::node(), MayaFlux::Portal::Forma::Inspector::node_graph_manager(), MayaFlux::Portal::Forma::Inspector::node_network(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_graphics_buffer(), MayaFlux::Portal::Forma::Inspector::root_node(), MayaFlux::Portal::Forma::Inspector::scheduler(), and MayaFlux::Portal::Forma::Inspector::tasks().