MayaFlux: MayaFlux::Kinesis::interpolate
interpolate()
Eigen::VectorXd MayaFlux::Kinesis::interpolate (const Eigen::MatrixXd & control_points, double t, InterpolationMode mode, double tension = 0.5)
Generic interpolation dispatcher.
Parameters
control_points MxN matrix where columns are control points
t Parameter in [0,1]
mode Interpolation mode
tension Tension parameter (for applicable modes)
Returns
Interpolated point as Nx1 vector
Definition at line 262 of file MotionCurves.cpp.
{
    switch (mode) {
    case InterpolationMode::LINEAR:
        if (control_points.cols() < 2) {
            error<std::invalid_argument>(
                Journal::Component::Kinesis,
                Journal::Context::Runtime,
                std::source_location::current(),
                "Linear interpolation requires at least 2 points, but got {}",
                control_points.cols());
        }
        return (1.0 - t) * control_points.col(0) + t * control_points.col(1);
    case InterpolationMode::CATMULL_ROM:
        return catmull_rom_spline(control_points, t, tension);
    case InterpolationMode::CUBIC_HERMITE: {
        Eigen::MatrixXd endpoints = control_points.leftCols(2);
        Eigen::MatrixXd tangents = control_points.rightCols(2);
        return cubic_hermite(endpoints, tangents, t);
    }
    case InterpolationMode::CUBIC_BEZIER:
        return cubic_bezier(control_points, t);
    case InterpolationMode::QUADRATIC_BEZIER:
        return quadratic_bezier(control_points, t);
    case InterpolationMode::BSPLINE:
        return bspline_cubic(control_points, t);
    case InterpolationMode::COSINE: {
        if (control_points.cols() < 2) {
            error<std::invalid_argument>(
                Journal::Component::Kinesis,
                Journal::Context::Runtime,
                std::source_location::current(),
                "Cosine interpolation requires at least 2 points, but got {}",
                control_points.cols());
        }
        double mu2 = (1.0 - std::cos(t * M_PI)) * 0.5;
        return (1.0 - mu2) * control_points.col(0) + mu2 * control_points.col(1);
    }
    default:
        error<std::invalid_argument>(
            Journal::Component::Kinesis,
            Journal::Context::Runtime,
            std::source_location::current(),
            "Unsupported interpolation mode: {}",
            static_cast<int>(mode));
    }
}
References BSPLINE, bspline_cubic(), CATMULL_ROM, catmull_rom_spline(), COSINE, cubic_bezier(), CUBIC_BEZIER, cubic_hermite(), CUBIC_HERMITE, MayaFlux::Journal::Kinesis, LINEAR, quadratic_bezier(), QUADRATIC_BEZIER, and MayaFlux::Journal::Runtime.
Referenced by generate_interpolated_points().