MayaFlux: MayaFlux::Portal::Graphics::initialize
initialize()
MAYAFLUX_API bool MayaFlux::Portal::Graphics::initialize (const std::shared_ptr< Core::VulkanBackend > & backend)
Initialize Portal::Graphics Glue Layer.
Parameters
backend Initialized Vulkan backend
Returns
True if initialization succeeded
Initializes all Portal::Graphics managers:
TextureLoom (texture management)
SamplerForge (sampler creation)
ShaderFoundry (shader compilation + resources)
ComputePress (compute pipeline + dispatch)
RenderFlow (graphics pipeline + rendering)
Must be called after backend initialization (VulkanBackend::initialize()).
Definition at line 16 of file Graphics.cpp.
{
    if (!backend) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Cannot initialize Portal::Graphics with null backend");
        return false;
    }
    if (g_initialized) {
        MF_WARN(Journal::Component::Portal, Journal::Context::API,
            "Portal::Graphics already initialized");
        return true;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Initializing Portal::Graphics...");
    if (!TextureLoom::instance().initialize(backend)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize TextureLoom");
        return false;
    }
    if (!SamplerForge::instance().initialize(backend)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize SamplerFactory");
        return false;
    }
    if (!ShaderFoundry::instance().initialize(backend)) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize ShaderFoundry");
        return false;
    }
    if (!ComputePress::instance().initialize()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize ComputePress");
        return false;
    }
    if (!RenderFlow::instance().initialize()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize RenderFlow");
        return false;
    }
    g_initialized = true;
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Portal::Graphics initialized successfully");
    return true;
}
References MayaFlux::Journal::API, initialize(), MayaFlux::Portal::Graphics::ComputePress::instance(), MayaFlux::Portal::Graphics::RenderFlow::instance(), MayaFlux::Portal::Graphics::SamplerForge::instance(), MayaFlux::Portal::Graphics::ShaderFoundry::instance(), MayaFlux::Portal::Graphics::TextureLoom::instance(), MF_ERROR, MF_INFO, MF_WARN, and MayaFlux::Journal::Portal.
Referenced by MayaFlux::Core::GraphicsSubsystem::initialize_graphics_portal().