MayaFlux: MayaFlux::internal::live_arena_alloc
live_arena_alloc()
void * MayaFlux::internal::live_arena_alloc (const char * key, uint32_t size, uint32_t alignment) inline noexcept
Allocates size bytes from the arena with alignment.
Writes a directory entry under key. Returns nullptr if the arena is full, the key is already registered, or capacity is exceeded.
Definition at line 126 of file LiveArena.hpp.
    {
        auto* hdr = live_arena_header();
        if (hdr->entry_count >= LIVE_ARENA_MAX_ENTRIES) {
            return nullptr;
        }
        if (live_arena_find(key)) {
            return nullptr;
        }
        const auto object_region_capacity = static_cast<uint32_t>(LIVE_ARENA_CAPACITY - sizeof(LiveArenaHeader));
        const uint32_t aligned_bump = align_up(g_live_arena_bump, alignment);
        if (aligned_bump + size > object_region_capacity) {
            return nullptr;
        }
        const uint32_t idx = hdr->entry_count;
        auto& entry = hdr->entries[idx];
        std::strncpy(entry.key, key, LIVE_ARENA_KEY_MAX - 1);
        entry.key[LIVE_ARENA_KEY_MAX - 1] = '\0';
        entry.offset = aligned_bump;
        entry.size = size;
        entry.occupied = true;
        g_live_arena_bump = aligned_bump + size;
        ++hdr->entry_count;
        return live_arena_object_region() + aligned_bump;
    }
References align_up(), g_live_arena_bump, LIVE_ARENA_CAPACITY, live_arena_find(), live_arena_header(), LIVE_ARENA_KEY_MAX, LIVE_ARENA_MAX_ENTRIES, live_arena_object_region(), and size.
Referenced by MayaFlux::make_live().