MayaFlux: MayaFlux::Portal::Text::get_default_atlas
get_default_atlas()
MAYAFLUX_API GlyphAtlas & MayaFlux::Portal::Text::get_default_atlas ()
Return the default GlyphAtlas, or nullptr if set_default_font() has not been called successfully.
Definition at line 105 of file Text.cpp.
{
    GlyphAtlas* atlas = TypeFaceFoundry::instance().get_default_glyph_atlas();
    MF_ASSERT(Journal::Component::Portal, Journal::Context::API,
        atlas != nullptr, "call set_default_font before get_default_atlas");
    return *atlas;
}
References MayaFlux::Journal::API, MayaFlux::Portal::Text::TypeFaceFoundry::get_default_glyph_atlas(), MayaFlux::Portal::Text::TypeFaceFoundry::instance(), MF_ASSERT, and MayaFlux::Journal::Portal.
Referenced by create_layout().