MayaFlux: MayaFlux::on_network_message_from
on_network_message_from() [2/2]
MAYAFLUX_API void MayaFlux::on_network_message_from (std::shared_ptr< Vruta::NetworkSource > source, std::string sender_address, std::function< void(const Core::NetworkMessage &)> callback, std::string name = "")
Schedule an on_message_from handler with an existing NetworkSource.
Parameters
source Shared NetworkSource
sender_address Sender IP address to filter on
callback Invoked with each matching message
name Optional name for the event handler
Definition at line 313 of file Chronie.cpp.
{
    auto event_manager = get_event_manager();
    if (name.empty()) {
        name = "net_msg_from_" + std::to_string(event_manager->get_next_event_id());
    }
    event_manager->add_event(
        std::make_shared<Vruta::Event>(
            Kriya::on_message_from(std::move(source), std::move(sender_address), std::move(callback))),
        name);
}
References get_event_manager(), and MayaFlux::Kriya::on_message_from().
Referenced by on_network_message_from().