MayaFlux: MayaFlux::Yantra::transform_trigonometric
transform_trigonometric() [2/2]
template<OperationReadyData DataType, typename TrigFunc > requires std::invocable<TrigFunc, double> DataType MayaFlux::Yantra::transform_trigonometric (DataType & input, TrigFunc trig_func, double frequency = 1.0, double amplitude = 1.0, double phase = 0.0)
Trigonometric transformation using specified function (IN-PLACE)
Template Parameters
DataType OperationReadyData type
TrigFunc Trigonometric function type
Parameters
input Input data - WILL BE MODIFIED
trig_func Trigonometric function (sin, cos, tan, etc.)
frequency Frequency scaling factor
amplitude Amplitude scaling factor
phase Phase offset
Returns
Transformed data
Definition at line 314 of file MathematicalHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    for (auto& span : target_data) {
        std::ranges::transform(span, span.begin(),
            [trig_func, frequency, amplitude, phase](double x) {
                return amplitude * trig_func(frequency * x + phase);
            });
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References frequency, and transform_trigonometric().
Referenced by MayaFlux::Yantra::MathematicalTransformer< InputType, OutputType >::transform_implementation(), transform_trigonometric(), and transform_trigonometric().