MayaFlux: MayaFlux::Buffers::upload_host_visible
upload_host_visible()
MAYAFLUX_API void MayaFlux::Buffers::upload_host_visible (const std::shared_ptr< VKBuffer > & target, const Kakshya::DataVariant & data)
Upload data to a host-visible buffer.
Parameters
target Target VKBuffer to upload data into
data DataVariant containing the data to upload
This function handles uploading data from a Kakshya::DataVariant into a host-visible VKBuffer. It maps the buffer memory, copies the data, and marks the buffer as dirty for synchronization.
Definition at line 9 of file StagingUtils.cpp.
{
    Kakshya::DataAccess accessor(
        const_cast<Kakshya::DataVariant&>(data),
        {},
        target->get_modality());
    auto [ptr, bytes, format_hint] = accessor.gpu_buffer();
    if (bytes > target->get_size_bytes()) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Upload data size {} exceeds buffer capacity {}",
            bytes, target->get_size_bytes());
    }
    auto& target_resources = target->get_buffer_resources();
    void* mapped = target_resources.mapped_ptr;
    if (!mapped) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Host-visible buffer has no mapped pointer");
    }
    std::memcpy(mapped, ptr, bytes);
    target->mark_dirty_range(0, bytes);
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "upload_host_visible requires a valid buffer service");
    }
    auto dirty_ranges = target->get_and_clear_dirty_ranges();
    for (auto& [offset, size] : dirty_ranges) {
        buffer_service->flush_range(
            target_resources.memory,
            offset,
            size);
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Kakshya::DataAccess::gpu_buffer(), MayaFlux::Registry::BackendRegistry::instance(), and size.
Referenced by MayaFlux::Buffers::BufferUploadProcessor::processing_function(), and upload_to_gpu().