MayaFlux: MayaFlux::Nexus::dispatch_audio_sinks
dispatch_audio_sinks()
void MayaFlux::Nexus::dispatch_audio_sinks (std::vector< AudioSink > & sinks, const InfluenceContext & ctx)
For each sink that has a producer fn, call it and push the result.
Sinks without a fn are untouched.
Parameters
sinks Sink vector owned by the calling Emitter or Agent.
ctx Current InfluenceContext passed to each fn.
Definition at line 71 of file Sinks.cpp.
{
    for (auto& s : sinks) {
        if (!s.fn) {
            continue;
        }
        auto variant = s.fn(ctx);
        if (auto* vec = std::get_if<std::vector<double>>(&variant)) {
            s.writer->set_data(std::span<const double>(*vec));
        } else {
            Kakshya::EigenAccess acc(variant);
            const Eigen::VectorXd v = acc.to_vector();
            std::vector<double> samples(static_cast<size_t>(v.size()));
            Eigen::Map<Eigen::VectorXd>(samples.data(), v.size()) = v;
            s.writer->set_data(std::span<const double>(samples));
        }
    }
}
References MayaFlux::Kakshya::EigenAccess::to_vector().
Referenced by MayaFlux::Nexus::Emitter::invoke(), and MayaFlux::Nexus::Agent::invoke_influence().