MayaFlux: MayaFlux::concat_vectors
concat_vectors()
static std::vector< double > MayaFlux::concat_vectors (const std::vector< std::span< double > > & data) static
Definition at line 22 of file Yantra.cpp.
{
    std::vector<double> result;
    result.reserve(std::accumulate(
        data.begin(), data.end(), size_t(0),
        [](size_t sum, const auto& span) { return sum + span.size(); }));
    for (const auto& span : data) {
        result.insert(result.end(), span.begin(), span.end());
    }
    return result;
}
Referenced by mean_combined(), rms_combined(), and std_dev_combined().