MayaFlux: MayaFlux::Yantra::extract_onsets
extract_onsets()
std::vector< std::vector< double > > MayaFlux::Yantra::extract_onsets (const std::vector< std::span< const double > > & channels, double threshold, uint32_t region_size, uint32_t fft_window_size, uint32_t hop_size)
Definition at line 252 of file ExtractionHelper.cpp.
{
    std::vector<std::vector<double>> result;
    result.reserve(channels.size());
    for (const auto& ch : channels) {
        if (ch.empty()) {
            result.emplace_back();
            continue;
        }
        const auto pos = D::onset_positions(ch, fft_window_size, hop_size, threshold);
        result.push_back(D::slice_intervals(ch,
            D::merge_intervals(D::regions_around_positions(pos, region_size / 2, ch.size()))));
    }
    return result;
}
References MayaFlux::Kinesis::Discrete::merge_intervals(), MayaFlux::Kinesis::Discrete::onset_positions(), MayaFlux::Kinesis::Discrete::regions_around_positions(), and MayaFlux::Kinesis::Discrete::slice_intervals().
Referenced by MayaFlux::Yantra::FeatureExtractor< InputType, OutputType >::extract_implementation().