MayaFlux: MayaFlux::Yantra::compute_zscore_statistic
compute_zscore_statistic()
std::vector< double > MayaFlux::Yantra::compute_zscore_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size, bool sample_variance)
Compute z-score statistic using zero-copy processing.
Definition at line 841 of file AnalysisHelper.cpp.
{
    std::vector<double> zscore_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.empty()) {
                zscore_values[i] = 0.0;
                return;
            }
            double sum = 0.0;
            for (double sample : window) {
                sum += sample;
            }
            double mean = sum / static_cast<double>(window.size());
            double sum_sq_diff = 0.0;
            for (double sample : window) {
                double diff = sample - mean;
                sum_sq_diff += diff * diff;
            }
            double divisor = sample_variance ? static_cast<double>(window.size() - 1) : static_cast<double>(window.size());
            double variance = sum_sq_diff / divisor;
            double std_dev = std::sqrt(variance);
            if (std_dev > 0.0) {
                double sum_zscore = 0.0;
                for (double val : window) {
                    sum_zscore += (val - mean) / std_dev;
                }
                zscore_values[i] = sum_zscore / static_cast<double>(window.size());
            } else {
                zscore_values[i] = 0.0;
            }
        });
    return zscore_values;
}
References compute_zscore_statistic(), MayaFlux::mean(), and MayaFlux::std_dev().
Referenced by MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), and compute_zscore_statistic().