MayaFlux: MayaFlux::Resume
Resume()
MAYAFLUX_API void MayaFlux::Resume ()
Resumes audio processing on the default engine.
Convenience wrapper for Engine::Resume() on the default engine.
Definition at line 132 of file Core.cpp.
{
    if (internal::initialized) {
        get_context().Resume();
    }
}
References get_context(), MayaFlux::internal::initialized, and MayaFlux::Core::Engine::Resume().
Referenced by MayaFlux::Core::Engine::operator=().