MayaFlux: MayaFlux::Portal::Forma::Plot::scatter
scatter()
GeometryFn< std::shared_ptr< Kakshya::PlotContainer > > MayaFlux::Portal::Forma::Plot::scatter (AxisRange x_range = {}, AxisRange y_range = {}, AxisRange z_range = {}, const std::vector< glm::vec3 > & palette = {}, float point_size = 4.F)
POINT_LIST scatter plot for paired (X, Y[, Z]) series.
Pairs the i-th SPATIAL_X series with the i-th SPATIAL_Y series. If there are more Y series than X series, the last X series is reused. Each pair produces one run of PointVertex in the output bytes.
SPATIAL_Z series map to Z position, enabling a true 3D scatter cloud. A COLOR series modulates per-sample point color: samples are mapped through y_range.normalise() and blended between white and the series base color from palette.
Per-series color is resolved from palette cyclically.
Parameters
x_range Domain for X.
y_range Domain for Y.
z_range Domain for Z.
palette Per-series colors, cycled. {1,1,1} if empty.
point_size Point size in pixels.
Definition at line 209 of file Plot.cpp.
{
    return [x_range, y_range, z_range, palette, point_size](
               const std::shared_ptr<Kakshya::PlotContainer>& container,
               std::vector<uint8_t>& out,
               Element&) mutable {
        if (!container)
            return;
        container->process_default();
        const auto x_series = series_by_role(*container, Role::SPATIAL_X);
        auto y_series = series_by_role(*container, Role::SPATIAL_Y);
        const auto z_series = series_by_role(*container, Role::SPATIAL_Z);
        const auto c_series = series_by_role(*container, Role::COLOR);
        if (y_series.empty())
            return;
        apply_auto_scale(x_range, x_series);
        apply_auto_scale(y_range, y_series);
        apply_auto_scale(z_range, z_series);
        out.clear();
        for (size_t si = 0; si < y_series.size(); ++si) {
            const auto& ys = y_series[si];
            const size_t n = ys.size();
            if (n == 0)
                continue;
            const glm::vec3 base_color = palette_color(palette, si);
            // Reuse last X series if fewer X series than Y series.
            const bool has_x = !x_series.empty();
            const auto& xs = has_x
                ? x_series[std::min(si, x_series.size() - 1)]
                : std::span<const double> {};
            const bool has_z = si < z_series.size() && z_series[si].size() == n;
            const bool has_c = si < c_series.size() && c_series[si].size() == n;
            for (size_t i = 0; i < n; ++i) {
                PointVertex v;
                v.position.x = has_x
                    ? x_range.to_ndc(static_cast<float>(xs[std::min(i, xs.size() - 1)]))
                    : x_range.to_ndc(x_range.min
                          + static_cast<float>(i)
                              / static_cast<float>(std::max<size_t>(n - 1, 1))
                              * (x_range.max - x_range.min));
                v.position.y = y_range.to_ndc(static_cast<float>(ys[i]));
                v.position.z = has_z
                    ? z_range.to_ndc(static_cast<float>(z_series[si][i]))
                    : 0.F;
                if (has_c) {
                    const float t = y_range.normalise(
                        static_cast<float>(c_series[si][i]));
                    v.color = glm::mix(glm::vec3(1.F), base_color, t);
                } else {
                    v.color = base_color;
                }
                v.size = point_size;
                push_vertex(out, v);
            }
        }
    };
}
References apply_auto_scale(), MayaFlux::Nodes::PointVertex::color, MayaFlux::Portal::Forma::Plot::AxisRange::max, MayaFlux::Portal::Forma::Plot::AxisRange::min, MayaFlux::Portal::Forma::Plot::AxisRange::normalise(), palette_color(), MayaFlux::Nodes::PointVertex::position, series_by_role(), MayaFlux::Nodes::PointVertex::size, and MayaFlux::Portal::Forma::Plot::AxisRange::to_ndc().