MayaFlux: MayaFlux::Kakshya::calculate_output_region
calculate_output_region() [1/2]
Region MayaFlux::Kakshya::calculate_output_region (const std::vector< uint64_t > & current_pos, const std::vector< uint64_t > & output_shape)
Calculate output region bounds from current position and shape.
Parameters
current_pos Current position coordinates.
output_shape Desired output shape.
Returns
Region representing the output bounds.
Definition at line 183 of file RegionUtils.cpp.
{
    if (current_pos.size() != output_shape.size()) {
        error<std::invalid_argument>(
            Journal::Component::Kakshya, Journal::Context::Runtime,
            std::source_location::current(),
            "Position and shape vectors must have same size: current_pos size = "
                + std::to_string(current_pos.size()) + ", output_shape size = "
                + std::to_string(output_shape.size()));
    }
    std::vector<uint64_t> end_pos;
    end_pos.reserve(current_pos.size());
    for (size_t i = 0; i < current_pos.size(); ++i) {
        if (output_shape[i] == 0) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya, Journal::Context::Runtime,
                std::source_location::current(),
                "Output shape cannot have zero dimensions: dimension " + std::to_string(i) + " is zero");
        }
        end_pos.push_back(current_pos[i] + output_shape[i] - 1);
    }
    return { current_pos, end_pos };
}
References calculate_output_region().
Referenced by calculate_output_region(), calculate_output_region(), and MayaFlux::Kakshya::ContiguousAccessProcessor::process().