MayaFlux: MayaFlux::Portal::Forma::Geometry::radial
radial()
MAYAFLUX_API GeometryFn< float > MayaFlux::Portal::Forma::Geometry::radial (glm::vec2 center, float radius, float angle_start, float angle_end, glm::vec3 color = glm::vec3(0.9F))
Geometry function for a radial indicator in NDC space.
Parameters
center Arc center in NDC.
radius Arc radius in NDC units.
angle_start Start angle in radians (value = 0).
angle_end End angle in radians (value = 1).
color Line color.
Definition at line 61 of file Geometry.cpp.
{
    return [center, radius, angle_start, angle_end, color](
               float v, std::vector<uint8_t>& out, Element& el) {
        float angle = angle_start + v * (angle_end - angle_start);
        glm::vec2 tip = center + radius * glm::vec2(std::cos(angle), std::sin(angle));
        using V = Kakshya::LineVertex;
        std::vector<V> verts = {
            { .position = { center.x, center.y, 0 }, .color = color },
            { .position = { tip.x, tip.y, 0 }, .color = color },
        };
        write_verts(out, verts);
        el.bounds_hint = Kinesis::AABB2D::from_ndc(center, glm::vec2(radius));
        el.contains = Kinesis::circular_bounds(center, radius);
    };
}
References MayaFlux::Kinesis::circular_bounds(), MayaFlux::Kinesis::AABB2D::from_ndc(), MayaFlux::Kakshya::LineVertex::position, and write_verts().