MayaFlux: MayaFlux::Portal::Text::decompose_glyph
decompose_glyph() [2/2]
MAYAFLUX_API GlyphOutline MayaFlux::Portal::Text::decompose_glyph (uint32_t codepoint, float tolerance = 0.5F)
Decompose a Unicode codepoint using the default atlas pixel size.
Convenience overload that reads pixel_size from TypeFaceFoundry's default atlas. Requires set_default_font() to have been called.
Parameters
codepoint Unicode codepoint.
tolerance Flatness tolerance in pixels.
Returns
GlyphOutline, or empty outline on failure.
Definition at line 231 of file GlyphOutline.cpp.
{
    auto* atlas = TypeFaceFoundry::instance().get_default_glyph_atlas();
    if (!atlas) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "decompose_glyph: no default font set");
        return GlyphOutline { .codepoint = codepoint };
    }
    auto& foundry = TypeFaceFoundry::instance();
    FontFace* face = foundry.get_default_face();
    if (!face) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "decompose_glyph: default face is null");
        return GlyphOutline { .codepoint = codepoint };
    }
    return decompose_glyph(*face, codepoint, atlas->pixel_size(), tolerance);
}
References MayaFlux::Journal::API, MayaFlux::Portal::Text::GlyphOutline::codepoint, decompose_glyph(), MayaFlux::Portal::Text::TypeFaceFoundry::get_default_glyph_atlas(), MayaFlux::Portal::Text::TypeFaceFoundry::instance(), MF_ERROR, MayaFlux::Journal::Portal, and tolerance.