MayaFlux: MayaFlux::is_initialized
is_initialized()
bool MayaFlux::is_initialized ()
Checks if the default engine has been initialized.
Returns
true if the engine is initialized, false otherwise
Definition at line 50 of file Core.cpp.
{
    if (internal::terminating) {
        return false;
    }
    return internal::initialized;
}
References MayaFlux::internal::initialized, and MayaFlux::internal::terminating.
Referenced by MayaFlux::Config::get_buffer_size(), MayaFlux::Config::get_global_graphics_config(), MayaFlux::Config::get_global_input_config(), MayaFlux::Config::get_global_network_config(), MayaFlux::Config::get_global_stream_info(), MayaFlux::Config::get_num_out_channels(), MayaFlux::Config::get_sample_rate(), is_engine_initialized(), MayaFlux::Nodes::CompositeOpNode< N >::process_sample(), and MayaFlux::Config::set_node_config().