MayaFlux: MayaFlux::Portal::Forma::create_surface
create_surface()
MAYAFLUX_API Surface MayaFlux::Portal::Forma::create_surface (std::shared_ptr< Core::Window > window, std::string name)
Construct a Surface, creating Layer and Context internally.
Builds a fresh Layer and a Context wired to window using the EventManager stored by Portal::Forma::initialize. Equivalent to Portal::Forma::create_layer(window, name) plus owning the window pointer alongside.
For the power-tinkerer case (custom Context subclass, shared Layer across multiple Contexts, etc.), construct Surface directly via its (Window, Layer, Context) constructor.
Parameters
window Target window. Must outlive the Surface.
name Unique name scoping the Context's event coroutines. Must be unique across all live Contexts.
Precondition
Portal::Forma::initialize() must have been called.
Returns
A new Surface owning the window pointer plus the freshly created Layer and Context.
Definition at line 234 of file Forma.cpp.
{
    auto [layer, ctx] = create_layer(window, std::move(name));
    return { std::move(window), std::move(layer), std::move(ctx) };
}
References create_layer().
Referenced by inspect(), inspect(), inspect(), inspect(), inspect_buffers(), inspect_events(), inspect_node_graph(), inspect_scheduler(), and plot().