MayaFlux: MayaFlux::Yantra::validate_extraction_parameters
validate_extraction_parameters()
bool MayaFlux::Yantra::validate_extraction_parameters (uint32_t window_size, uint32_t hop_size, size_t data_size)
Validate extraction parameters.
Parameters
window_size Window size to validate
hop_size Hop size to validate
data_size Size of data to process
Returns
True if parameters are valid
Definition at line 460 of file ExtractionHelper.cpp.
{
    if (window_size == 0 || hop_size == 0) {
        return false;
    }
    if (data_size == 0) {
        return true;
    }
    if (data_size < window_size) {
        return data_size >= 3;
    }
    return true;
}
Referenced by extract_above_mean_data(), extract_high_energy_data(), extract_high_spectral_data(), extract_outlier_data(), and MayaFlux::Yantra::FeatureExtractor< InputType, OutputType >::validate_extraction_input().