MayaFlux: Lila::socket_error_string
socket_error_string()
static std::string Lila::socket_error_string (int code) static
Definition at line 33 of file Server.cpp.
{
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    // Keep it simple: return numeric WSA code (can be extended with FormatMessage)
    return "WSA error " + std::to_string(code);
#else
    return std::string(strerror(code));
#endif
}
Referenced by Lila::Server::handle_client(), Lila::Server::read_message(), and Lila::Server::server_loop().