MayaFlux: MayaFlux::Portal::Forma::Plot::bars
bars()
GeometryFn< std::shared_ptr< Kakshya::PlotContainer > > MayaFlux::Portal::Forma::Plot::bars (AxisRange x_range = {}, AxisRange y_range = {}, const std::vector< glm::vec3 > & palette = {})
TRIANGLE_LIST bar chart for FREQUENCY or SPATIAL_Y series.
Each FREQUENCY series produces one set of bars tiled uniformly across [x_range.min, x_range.max]. Bar height maps sample value through y_range.
Multiple FREQUENCY series are currently rendered on top of each other in the same X range. Side-by-side or stacked layout is not yet implemented; no three-caller evidence exists for those layouts.
Per-series color is resolved from palette cyclically.
Parameters
x_range Domain for X (bar positions).
y_range Domain for Y (bar heights).
palette Per-series colors, cycled. {1,1,1} if empty.
Definition at line 291 of file Plot.cpp.
{
    return [x_range, y_range, palette](
               const std::shared_ptr<Kakshya::PlotContainer>& container,
               std::vector<uint8_t>& out,
               Element&) mutable {
        if (!container)
            return;
        container->process_default();
        auto f_series = series_by_role(*container, Role::FREQUENCY);
        if (f_series.empty())
            f_series = series_by_role(*container, Role::SPATIAL_Y);
        if (f_series.empty())
            return;
        apply_auto_scale(y_range, f_series);
        out.clear();
        for (size_t si = 0; si < f_series.size(); ++si) {
            const auto& series = f_series[si];
            const size_t n = series.size();
            if (n == 0)
                continue;
            const glm::vec3 color = palette_color(palette, si);
            const float bar_w = (x_range.max - x_range.min)
                / static_cast<float>(n);
            const float y_base = y_range.to_ndc(0.F);
            for (size_t i = 0; i < n; ++i) {
                const float x_left = x_range.to_ndc(
                    x_range.min + static_cast<float>(i) * bar_w);
                const float x_right = x_range.to_ndc(
                    x_range.min + static_cast<float>(i + 1) * bar_w);
                const float y_top = y_range.to_ndc(
                    static_cast<float>(series[i]));
                const auto emit = [&](float x, float y) {
                    MeshVertex v;
                    v.position = glm::vec3(x, y, 0.F);
                    v.color = color;
                    push_vertex(out, v);
                };
                // Two triangles per bar (TRIANGLE_LIST).
                emit(x_left, y_base);
                emit(x_right, y_base);
                emit(x_left, y_top);
                emit(x_right, y_base);
                emit(x_right, y_top);
                emit(x_left, y_top);
            }
        }
    };
}
References apply_auto_scale(), color, MayaFlux::Nodes::MeshVertex::color, MayaFlux::Portal::Forma::Plot::AxisRange::max, MayaFlux::Portal::Forma::Plot::AxisRange::min, palette_color(), MayaFlux::Nodes::MeshVertex::position, series_by_role(), and MayaFlux::Portal::Forma::Plot::AxisRange::to_ndc().