MayaFlux: MayaFlux::Journal::format_runtime
format_runtime()
template<typename... Args> std::string MayaFlux::Journal::format_runtime (std::string_view fmt_str, Args &&... args) inline
Definition at line 36 of file Format.hpp.
{
#if MAYAFLUX_USE_STD_FORMAT
    return std::vformat(fmt_str, std::make_format_args(args...));
#elif MAYAFLUX_USE_FMT
    return fmt::vformat(fmt_str, fmt::make_format_args(args...));
#endif
}
Referenced by error(), error_rethrow(), MayaFlux::Core::RtAudioStream::open(), print(), scribe(), and scribe_rt().