MayaFlux: MayaFlux::Yantra::compute_mode_statistic
compute_mode_statistic()
std::vector< double > MayaFlux::Yantra::compute_mode_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute mode statistic using zero-copy processing.
Definition at line 801 of file AnalysisHelper.cpp.
{
    std::vector<double> mode_values(num_windows);
    constexpr double tolerance = 1e-10;
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.empty()) {
                mode_values[i] = 0.0;
                return;
            }
            std::map<int64_t, std::pair<double, size_t>> frequency_map;
            for (double value : window) {
                auto bucket = static_cast<int64_t>(std::round(value / tolerance));
                if (frequency_map.find(bucket) == frequency_map.end()) {
                    frequency_map[bucket] = { value, 1 };
                } else {
                    frequency_map[bucket].second++;
                    frequency_map[bucket].first = (frequency_map[bucket].first * static_cast<double>(frequency_map[bucket].second - 1) + value) / static_cast<double>(frequency_map[bucket].second);
                }
            }
            auto max_count_it = std::ranges::max_element(frequency_map,
                [](const auto& a, const auto& b) { return a.second.second < b.second.second; });
            mode_values[i] = max_count_it != frequency_map.end() ? max_count_it->second.first : window[0];
        });
    return mode_values;
}
References a, b, and compute_mode_statistic().
Referenced by compute_mode_statistic(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values().