MayaFlux: MayaFlux::bind_orbit_preset
bind_orbit_preset() [2/2]
MAYAFLUX_API void MayaFlux::bind_orbit_preset (const std::shared_ptr< Core::Window > & window, const std::shared_ptr< Buffers::RenderProcessor > & processor, const Kinesis::OrbitConfig & config = {}, const Kinesis::OrbitKeyMap & key_map = {}, const std::string & name = "default")
Bind the orbit navigation controller to a window and render processor.
Registers event handlers under the prefix "vp_<name>_". MMB drag rotates around the focal point; holding key_map.pan_modifier during MMB drag pans the focal point instead. Scroll dollies the distance. Ortho snap slots set to std::nullopt are silently skipped.
Parameters
window Window supplying input events
processor RenderProcessor that receives the ViewTransform source
config Orbit tuning parameters
key_map Key assignments; defaults to Shift pan modifier + KP snaps
name Unique prefix for registered events; must be unique per window
Definition at line 162 of file ViewportPreset.cpp.
{
    auto& record = s_registry[make_key(window, name)];
    record.saved_config = window->get_input_config();
    record.registered_events.clear();
    auto st = std::make_shared<Kinesis::OrbitState>(Kinesis::make_orbit_state(config));
    on_mouse_pressed(window, IO::MouseButtons::Middle, [st](double /*x*/, double /*y*/) {
        st->mmb_held    = true;
        st->first_mouse = true; }, event_name(name, "mmb_dn"));
    on_mouse_released(window, IO::MouseButtons::Middle, [st](double /*x*/, double /*y*/) { st->mmb_held = false; }, event_name(name, "mmb_up"));
    on_key_pressed(window, key_map.pan_modifier, [st] { st->pan_held = true; }, event_name(name, "pan_mod_dn"));
    on_key_released(window, key_map.pan_modifier, [st] { st->pan_held = false; }, event_name(name, "pan_mod_up"));
    on_mouse_move(window, [st](double x, double y) {
        if (!st->mmb_held) {
            st->first_mouse = true;
            return;
        }
        if (st->first_mouse) {
            st->last_x      = x;
            st->last_y      = y;
            st->first_mouse = false;
            return;
        }
        const auto  dx = static_cast<float>(x - st->last_x);
        const auto  dy = static_cast<float>(y - st->last_y);
        st->last_x = x;
        st->last_y = y;
        if (st->pan_held) {
            Kinesis::apply_orbit_pan(*st, dx, dy);
        } else {
            Kinesis::apply_orbit_rotate(*st, dx, dy);
} }, event_name(name, "mouse"));
    on_scroll(window, [st](double /*dx*/, double dy) { Kinesis::apply_orbit_scroll(*st, static_cast<float>(dy)); }, event_name(name, "scroll"));
    if (key_map.ortho_front)
        on_key_pressed(window, *key_map.ortho_front, [st] { Kinesis::snap_orbit_ortho(*st, 0); }, event_name(name, "kp_front"));
    if (key_map.ortho_right)
        on_key_pressed(window, *key_map.ortho_right, [st] { Kinesis::snap_orbit_ortho(*st, 1); }, event_name(name, "kp_right"));
    if (key_map.ortho_top)
        on_key_pressed(window, *key_map.ortho_top, [st] { Kinesis::snap_orbit_ortho(*st, 2); }, event_name(name, "kp_top"));
    if (key_map.ortho_flip)
        on_key_pressed(window, *key_map.ortho_flip, [st] { Kinesis::snap_orbit_ortho(*st, 3); }, event_name(name, "kp_flip"));
    processor->set_view_transform_source(
        [st, window_weak = std::weak_ptr<Core::Window>(window)]() -> Kinesis::ViewTransform {
            auto win = window_weak.lock();
            if (!win)
                return {};
            const auto& ws = win->get_state();
            const float aspect = (ws.current_height > 0)
                ? static_cast<float>(ws.current_width) / static_cast<float>(ws.current_height)
                : 1.0F;
            return Kinesis::compute_orbit_view_transform(*st, aspect);
        });
}
References MayaFlux::Kinesis::apply_orbit_pan(), MayaFlux::Kinesis::apply_orbit_rotate(), MayaFlux::Kinesis::apply_orbit_scroll(), MayaFlux::Kinesis::compute_orbit_view_transform(), MayaFlux::Kinesis::make_orbit_state(), MayaFlux::IO::Middle, on_key_pressed(), on_key_released(), on_mouse_move(), on_mouse_pressed(), on_mouse_released(), on_scroll(), MayaFlux::Kinesis::OrbitKeyMap::ortho_flip, MayaFlux::Kinesis::OrbitKeyMap::ortho_front, MayaFlux::Kinesis::OrbitKeyMap::ortho_right, MayaFlux::Kinesis::OrbitKeyMap::ortho_top, and MayaFlux::Kinesis::OrbitKeyMap::pan_modifier.
Referenced by bind_orbit_preset(), and bind_viewport_preset().