MayaFlux: MayaFlux::load_audio_file
load_audio_file()
MAYAFLUX_API std::shared_ptr< MayaFlux::Kakshya::SoundFileContainer > MayaFlux::load_audio_file (const std::string & filepath)
Loads an audio file into a SoundFileContainer with automatic format detection.
Parameters
filepath Path to the audio file to load
Returns
Shared pointer to loaded SoundFileContainer, or nullptr on failure
Provides comprehensive audio file loading with format detection, sample rate conversion, and bit depth optimization. Supports all FFmpeg formats including WAV, MP3, FLAC, OGG, etc. The container is immediately ready for use with buffer system integration. Returns nullptr on failure with error details logged to stderr.
Definition at line 18 of file Depot.cpp.
{
    auto reader = std::make_unique<IO::SoundFileReader>();
    MayaFlux::IO::SoundFileReader::initialize_ffmpeg();
    if (!reader->can_read(filepath)) {
        std::cerr << "Cannot read file: " << filepath << '\n';
        return nullptr;
    }
    reader->set_target_sample_rate(MayaFlux::Config::get_sample_rate());
    reader->set_target_bit_depth(64);
    reader->set_audio_options(IO::AudioReadOptions::DEINTERLEAVE);
    IO::FileReadOptions options = IO::FileReadOptions::EXTRACT_METADATA;
    if (!reader->open(filepath, options)) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO, "Failed to open file: {}", reader->get_last_error());
        return nullptr;
    }
    auto container = reader->create_container();
    auto sound_container = std::dynamic_pointer_cast<Kakshya::SoundFileContainer>(container);
    if (!sound_container) {
        MF_ERROR(Journal::Component::API, Journal::Context::Runtime, "Failed to create sound container");
        return nullptr;
    }
    sound_container->set_memory_layout(Kakshya::MemoryLayout::ROW_MAJOR);
    if (!reader->load_into_container(sound_container)) {
        MF_ERROR(Journal::Component::API, Journal::Context::Runtime, "Failed to load audio data: {}", reader->get_last_error());
        return nullptr;
    }
    auto existing_processor = std::dynamic_pointer_cast<Kakshya::ContiguousAccessProcessor>(
        sound_container->get_default_processor());
    if (existing_processor) {
        std::vector<uint64_t> output_shape = { MayaFlux::Config::get_buffer_size(), sound_container->get_num_channels() };
        existing_processor->set_output_size(output_shape);
        existing_processor->set_auto_advance(true);
        MF_DEBUG(Journal::Component::API, Journal::Context::ContainerProcessing, "Configured existing ContiguousAccessProcessor");
    } else {
        MF_TRACE(Journal::Component::API, Journal::Context::ContainerProcessing, "No default processor found, creating a new ContiguousAccessProcessor");
        auto processor = std::make_shared<Kakshya::ContiguousAccessProcessor>();
        std::vector<uint64_t> output_shape = { MayaFlux::Config::get_buffer_size(), sound_container->get_num_channels() };
        processor->set_output_size(output_shape);
        processor->set_auto_advance(true);
        sound_container->set_default_processor(processor);
    }
    MF_INFO(
        Journal::Component::API,
        Journal::Context::FileIO,
        "Loaded audio file: {} | Channels: {} | Frames: {} | Sample Rate: {} Hz",
        filepath,
        sound_container->get_num_channels(),
        sound_container->get_num_frames(),
        sound_container->get_sample_rate());
    return sound_container;
}
References MayaFlux::Journal::API, MayaFlux::Journal::ContainerProcessing, MayaFlux::IO::DEINTERLEAVE, MayaFlux::IO::EXTRACT_METADATA, MayaFlux::Journal::FileIO, MayaFlux::Config::get_buffer_size(), MayaFlux::Config::get_sample_rate(), MayaFlux::IO::SoundFileReader::initialize_ffmpeg(), MF_DEBUG, MF_ERROR, MF_INFO, MF_TRACE, MayaFlux::Kakshya::ROW_MAJOR, and MayaFlux::Journal::Runtime.
Referenced by MayaFlux::Kriya::BufferOperation::capture_file(), MayaFlux::Kriya::BufferOperation::capture_file_from(), MayaFlux::Kriya::BufferOperation::file_to_stream(), and MayaFlux::Creator::load_container().