MayaFlux: MayaFlux::Kinesis::Discrete::linear
linear()
void MayaFlux::Kinesis::Discrete::linear (std::span< double > data, double a, double b) noexcept
Linear map y = a*x + b applied in-place.
Parameters
data Target span
a Scale factor
b Offset
Definition at line 11 of file Transform.cpp.
{
    std::ranges::transform(data, data.begin(),
        [a, b](double x) { return a * x + b; });
}
References a, and b.
Referenced by MayaFlux::apply_gain(), MayaFlux::apply_gain(), MayaFlux::with_gain(), MayaFlux::with_gain(), and MayaFlux::with_gain_channels().