MayaFlux: MayaFlux::Parallel::dispatch_main_sync
dispatch_main_sync()
template<typename Func , typename... Args> auto MayaFlux::Parallel::dispatch_main_sync (Func && func, Args &&... args) -> decltype(auto)
Definition at line 140 of file Dispatch.hpp.
{
    return std::invoke(std::forward<Func>(func), std::forward<Args>(args)...);
}
Referenced by MayaFlux::Core::VKContext::create_surface(), MayaFlux::Core::WindowManager::destroy_window(), and MayaFlux::Core::WindowManager::process().