MayaFlux: MayaFlux::hook_sound_container_to_buffers
hook_sound_container_to_buffers()
MAYAFLUX_API std::vector< std::shared_ptr< Buffers::SoundContainerBuffer > > MayaFlux::hook_sound_container_to_buffers (const std::shared_ptr< MayaFlux::Kakshya::SoundFileContainer > & container)
Connects a SoundFileContainer to the buffer system for immediate playback.
Parameters
container SoundFileContainer to connect to buffers
Returns
Vector of shared pointers to created SoundContainerBuffer instances
Establishes connection between loaded audio container and engine's buffer system, enabling immediate audio playback through the standard processing pipeline. Creates SoundContainerBuffer instances for each channel and connects to AUDIO_BACKEND token. Multiple containers can be connected simultaneously for layered playback.
Definition at line 84 of file Depot.cpp.
{
    auto buffer_manager = MayaFlux::get_buffer_manager();
    uint32_t num_channels = container->get_num_channels();
    std::vector<std::shared_ptr<Buffers::SoundContainerBuffer>> created_buffers;
    MF_TRACE(
        Journal::Component::API,
        Journal::Context::BufferManagement,
        "Setting up audio playback for {} channels...",
        num_channels);
    for (uint32_t channel = 0; channel < num_channels; ++channel) {
        auto container_buffer = buffer_manager->create_audio_buffer<MayaFlux::Buffers::SoundContainerBuffer>(
            MayaFlux::Buffers::ProcessingToken::AUDIO_BACKEND,
            channel,
            container,
            channel);
        container_buffer->initialize();
        created_buffers.push_back(std::move(container_buffer));
        MF_INFO(
            Journal::Component::API,
            Journal::Context::BufferManagement,
            "✓ Created buffer for channel {}",
            channel);
    }
    return created_buffers;
}
References MayaFlux::Journal::API, MayaFlux::Buffers::AUDIO_BACKEND, MayaFlux::Journal::BufferManagement, get_buffer_manager(), MayaFlux::Buffers::SoundContainerBuffer::initialize(), MF_INFO, and MF_TRACE.
Referenced by register_container().