MayaFlux: MayaFlux::Portal::Forma::Geometry::position_picker
position_picker()
GeometryFn< glm::vec2 > MayaFlux::Portal::Forma::Geometry::position_picker (Kinesis::AABB2D bounds, glm::vec3 color = glm::vec3(0.9F), float size = 8.0F) inline
Geometry function for a 2D position picker in NDC space.
Parameters
bounds Full extent of the pick area in NDC.
color Point color.
size Point size in pixels.
Definition at line 151 of file Geometry.hpp.
{
    return [bounds, color, size](
               glm::vec2 v, std::vector<uint8_t>& out, Element& el) {
        float x = bounds.min.x + v.x * bounds.width();
        float y = bounds.min.y + v.y * bounds.height();
        using V = Nodes::PointVertex;
        std::vector<V> verts = {
            { .position = { x, y, 0 }, .color = color, .size = size },
        };
        detail::write_verts(out, verts);
        el.bounds_hint = bounds;
        el.contains = Kinesis::polygon_bounds(std::span<const glm::vec2> {
            std::array<glm::vec2, 4> {
                bounds.min,
                glm::vec2(bounds.max.x, bounds.min.y),
                bounds.max,
                glm::vec2(bounds.min.x, bounds.max.y) } });
    };
}
References color, MayaFlux::Kinesis::AABB2D::contains(), MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kinesis::polygon_bounds(), MayaFlux::Nodes::PointVertex::position, size, MayaFlux::Kinesis::AABB2D::width(), and MayaFlux::Portal::Forma::Geometry::detail::write_verts().