MayaFlux: MayaFlux::is_same_size
is_same_size()
static bool MayaFlux::is_same_size (const std::vector< std::span< double > > & data) static
Definition at line 12 of file Yantra.cpp.
{
    if (data.empty())
        return true;
    const auto expected_size = data.front().size();
    return std::ranges::all_of(data,
        [&expected_size](const auto& v) { return v.size() == expected_size; });
}
Referenced by mean_combined(), mix(), mix_with_gains(), rms_combined(), and std_dev_combined().