MayaFlux: MayaFlux::register_node
register_node() [2/2]
MAYAFLUX_API void MayaFlux::register_node (const std::shared_ptr< Nodes::Node > & node, const Nodes::ProcessingToken & token, uint32_t channel)
Definition at line 122 of file Graph.cpp.
{
    get_context().get_node_graph_manager()->add_to_root(node, token, channel);
}
References get_context(), and MayaFlux::Core::Engine::get_node_graph_manager().
Referenced by MayaFlux::CreationHandle< T >::apply_node_context(), operator|(), and register_node().