MayaFlux: MayaFlux::get_io_manager
get_io_manager()
MAYAFLUX_API std::shared_ptr< IO::IOManager > MayaFlux::get_io_manager ()
Retrieves the global IOManager instance for file loading and buffer management.
Returns
Shared pointer to the IOManager instance
Provides access to the central IOManager responsible for all file loading operations, container management, and buffer integration. This is the primary interface for performing file I/O tasks within the MayaFlux engine.
Definition at line 79 of file Depot.cpp.
{
    if (is_engine_configured()) {
        return get_context().get_io_manager();
    }
    MF_ERROR(Journal::Component::API, Journal::Context::Runtime,
        "Attempted to access IOManager before engine initialization");
    return nullptr;
}
References MayaFlux::Journal::API, get_context(), MayaFlux::Core::Engine::get_io_manager(), is_engine_configured(), MF_ERROR, and MayaFlux::Journal::Runtime.
Referenced by create_sampler(), create_samplers(), MayaFlux::Creator::load_image_buffer(), MayaFlux::Creator::load_mesh_buffers(), MayaFlux::Creator::load_mesh_network(), MayaFlux::Creator::load_sound_container(), and register_container().