MayaFlux: MayaFlux::Kinesis::Discrete::auto_correlate
auto_correlate()
std::vector< double > MayaFlux::Kinesis::Discrete::auto_correlate (std::span< const double > src, bool normalize = true)
Auto-correlation via FFT.
Parameters
src Input signal
normalize Normalise result to zero-lag peak
Returns
Auto-correlation, same length as src
Definition at line 141 of file Convolution.cpp.
{
    auto out = apply_convolution(src, src,
        [](const auto& s, const auto&, auto& r) {
            P::transform(P::par_unseq, s.begin(), s.end(), s.begin(), r.begin(),
                [](const std::complex<double>& a, const std::complex<double>& b) {
                    return a * std::conj(b);
                });
        });
    if (normalize && !out.empty()) {
        const double peak = *std::max_element(out.begin(), out.end());
        if (peak > 0.0) {
            P::transform(P::par_unseq, out.begin(), out.end(), out.begin(),
                [peak](double v) { return v / peak; });
        }
    }
    return out;
}
References a, apply_convolution(), auto_correlate(), b, MayaFlux::normalize(), and MayaFlux::peak().
Referenced by auto_correlate().