MayaFlux: MayaFlux::Journal::scribe_rt
scribe_rt() [1/2]
template<typename... Args> void MayaFlux::Journal::scribe_rt (Severity severity, Component component, Context context, std::source_location location, const char * msg_or_fmt, Args &&... args)
printf-style overload of scribe_rt().
Log a message in a real-time context with automatic source location.
Optimized for real-time usage and captures the source location automatically.
Parameters
severity The severity level of the log message.
component The component generating the log message.
context The execution context of the log message.
location Source location (file, line, function) of the log call.
message The log message content.
msg_or_fmt The format string.
args The format arguments.
Definition at line 174 of file Archivist.hpp.
{
    if constexpr (sizeof...(Args) == 0) {
        Archivist::instance().scribe_rt(severity, component, context,
            std::string_view(msg_or_fmt), location);
    } else {
        auto msg = format_runtime(msg_or_fmt, std::forward<Args>(args)...);
        Archivist::instance().scribe_rt(severity, component, context, msg, location);
    }
}
References format_runtime(), MayaFlux::Journal::Archivist::instance(), and MayaFlux::Journal::Archivist::scribe_rt().