MayaFlux: MayaFlux::Portal::Forma::create_element
create_element()
template<typename T > Mapped< T > MayaFlux::Portal::Forma::create_element (Layer & layer, std::shared_ptr< Core::Window > window, GeometryFn< T > geom, T initial, size_t capacity = 4096, Graphics::PrimitiveTopology topology = Graphics::PrimitiveTopology::TRIANGLE_STRIP)
Build a FormaBuffer, register it, construct a Mapped<T>, and add the element to layer.
BufferManager is taken from the stored initialize() state. Returns the fully constructed Mapped<T>. The caller holds it. element.id is stable and can be passed to Context callbacks and Bridge.
Template Parameters
T MappedState value type: float, glm::vec2, etc.
Parameters
layer Layer to register the element on.
window Target window for rendering.
geom Geometry function producing vertex bytes from T.
initial Starting value written into MappedState.
capacity Initial FormaBuffer capacity in bytes.
topology Primitive topology for the FormaBuffer.
Returns
Fully constructed Mapped<T> with element registered in layer.
Definition at line 155 of file Forma.hpp.
{
    auto buf = create_buffer(std::move(window), capacity, topology);
    auto mapped = make_mapped<T>(initial, std::move(geom), buf);
    mapped.element.id = layer.add(mapped.element);
    get_bridge().register_element(mapped);
    return mapped;
}
References MayaFlux::Portal::Forma::Layer::add(), create_buffer(), get_bridge(), and MayaFlux::Portal::Forma::Bridge::register_element().