MayaFlux: MayaFlux::Nodes::atomic_add_flag
atomic_add_flag()
void MayaFlux::Nodes::atomic_add_flag (std::atomic< NodeState > & state, NodeState flag)
Atomically adds a flag to a node state.
Parameters
state The atomic node state to modify
flag The flag to add to the state
Adds a specific state flag to a node's state without affecting other state flags. This is used to mark nodes with specific conditions (like PROCESSED or ACTIVE) while preserving other aspects of the node's current state.
Definition at line 60 of file NodeUtils.cpp.
{
    auto current = state.load();
    NodeState desired;
    do {
        desired = static_cast<NodeState>(current | flag);
    } while (!state.compare_exchange_weak(current, desired,
        std::memory_order_acq_rel,
        std::memory_order_acquire));
}
Referenced by MayaFlux::Nodes::Generator::Generator::enable_mock_process(), MayaFlux::Nodes::RootNode::process_frame(), MayaFlux::Nodes::RootNode::process_sample(), MayaFlux::Nodes::ChainNode::process_sample(), MayaFlux::Nodes::BinaryOpNode::process_sample(), MayaFlux::Nodes::CompositeOpNode< N >::process_sample(), MayaFlux::Nodes::Filters::FIR::process_sample(), MayaFlux::Nodes::Filters::IIR::process_sample(), MayaFlux::Nodes::Generator::Impulse::process_sample(), MayaFlux::Nodes::Generator::Logic::process_sample(), MayaFlux::Nodes::Generator::Phasor::process_sample(), MayaFlux::Nodes::Generator::Polynomial::process_sample(), MayaFlux::Nodes::Generator::Sine::process_sample(), MayaFlux::Nodes::Generator::Counter::process_sample(), MayaFlux::Buffers::FilterProcessor::process_single_sample(), MayaFlux::Nodes::RootNode::register_node(), and MayaFlux::Nodes::RootNode::unregister_node().