MayaFlux: MayaFlux::on_network_message
on_network_message() [2/2]
MAYAFLUX_API void MayaFlux::on_network_message (std::shared_ptr< Vruta::NetworkSource > source, std::function< void(const Core::NetworkMessage &)> callback, std::string name = "")
Schedule an on_message handler with an existing NetworkSource.
Parameters
source Shared NetworkSource; coroutine frame takes co-ownership
callback Invoked with each received message
name Optional name for the event handler
auto src = std::make_shared<Vruta::NetworkSource>(
    Core::EndpointInfo{ .transport = Core::NetworkTransport::UDP, .local_port = 8000 });
MayaFlux::on_network_message(src, [](const Core::NetworkMessage& msg) { });
Definition at line 289 of file Chronie.cpp.
{
    auto event_manager = get_event_manager();
    if (name.empty()) {
        name = "net_msg_" + std::to_string(event_manager->get_next_event_id());
    }
    event_manager->add_event(
        std::make_shared<Vruta::Event>(Kriya::on_message(std::move(source), std::move(callback))),
        name);
}
References get_event_manager(), and MayaFlux::Kriya::on_message().
Referenced by on_network_message().