MayaFlux: MayaFlux::Yantra::compute_mad_statistic
compute_mad_statistic()
std::vector< double > MayaFlux::Yantra::compute_mad_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute MAD (Median Absolute Deviation) statistic using zero-copy processing.
Definition at line 740 of file AnalysisHelper.cpp.
{
    std::vector<double> mad_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.empty()) {
                mad_values[i] = 0.0;
                return;
            }
            std::vector<double> sorted_window(window.begin(), window.end());
            std::ranges::sort(sorted_window);
            double median {};
            size_t n = sorted_window.size();
            if (n % 2 == 0) {
                median = (sorted_window[n / 2 - 1] + sorted_window[n / 2]) / 2.0;
            } else {
                median = sorted_window[n / 2];
            }
            std::vector<double> abs_deviations;
            abs_deviations.reserve(window.size());
            for (double val : window) {
                abs_deviations.push_back(std::abs(val - median));
            }
            std::ranges::sort(abs_deviations);
            size_t mad_n = abs_deviations.size();
            if (mad_n % 2 == 0) {
                mad_values[i] = (abs_deviations[mad_n / 2 - 1] + abs_deviations[mad_n / 2]) / 2.0;
            } else {
                mad_values[i] = abs_deviations[mad_n / 2];
            }
        });
    return mad_values;
}
References compute_mad_statistic().
Referenced by compute_mad_statistic(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values().