MayaFlux: MayaFlux::Yantra::generate_compute_data_indices
generate_compute_data_indices()
template<ComputeData T> std::vector< std::vector< size_t > > MayaFlux::Yantra::generate_compute_data_indices (const Datum< T > & data, SortingDirection direction)
Generate sort indices for any ComputeData type.
Template Parameters
T ComputeData type
Parameters
data Data to generate indices for
direction Sort direction
Returns
Vector of index vectors (one per channel)
Definition at line 128 of file SortingHelper.hpp.
{
    if constexpr (RequiresContainer<T>) {
        auto channels = OperationHelper::extract_numeric_data(data.data, data.container.value());
        return Kinesis::Discrete::channels_sort_indices(channels, direction);
    }
    if constexpr (SingleVariant<T>) {
        auto channel = OperationHelper::extract_numeric_data(data.data);
        return { Kinesis::Discrete::span_sort_indices({ channel }, direction) };
    } else {
        auto channels = OperationHelper::extract_numeric_data(data.data, data.needs_processig());
        return Kinesis::Discrete::channels_sort_indices(channels, direction);
    }
}
References MayaFlux::Kinesis::Discrete::channels_sort_indices(), MayaFlux::Yantra::Datum< T >::container, MayaFlux::Yantra::Datum< T >::data, MayaFlux::Yantra::OperationHelper::extract_numeric_data(), MayaFlux::Yantra::Datum< T >::needs_processig(), and MayaFlux::Kinesis::Discrete::span_sort_indices().
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::sort_indices_only().