MayaFlux: MayaFlux::Kakshya::find_references_in_region
find_references_in_region()
std::vector< std::pair< std::string, Region > > MayaFlux::Kakshya::find_references_in_region (const std::vector< std::pair< std::string, Region > > & refs, const Region & region)
Find all references in a reference list that overlap a given region.
Parameters
refs Reference list (name, Region) pairs.
region Region to check for overlap.
Returns
Vector of (name, Region) pairs that overlap.
Definition at line 155 of file RegionUtils.cpp.
{
    std::vector<std::pair<std::string, Region>> result;
    std::ranges::copy_if(refs, std::back_inserter(result),
        [&region](const auto& pair) { return region.contains(pair.second.start_coordinates); });
    return result;
}
References MayaFlux::Kakshya::Region::contains(), and find_references_in_region().
Referenced by find_references_in_region().