MayaFlux: MayaFlux::register_input_node
register_input_node()
MAYAFLUX_API void MayaFlux::register_input_node (const std::shared_ptr< Nodes::Input::InputNode > & node, const Core::InputBinding & binding)
Register an input node with specified binding.
Parameters
node The InputNode to register
binding Specifies what input the node wants
Convenience wrapper for InputManager::register_node() on the default engine.
Definition at line 21 of file Input.cpp.
{
    get_input_manager().register_node(node, binding);
}
References get_input_manager(), and MayaFlux::Core::InputManager::register_node().
Referenced by MayaFlux::Creator::read_hid(), and MayaFlux::Creator::read_midi().