MayaFlux: MayaFlux::Kakshya::extract_region_data
extract_region_data() [1/3]
template<typename T > std::vector< T > MayaFlux::Kakshya::extract_region_data (const std::span< const T > & source_data, const Region & region, const std::vector< DataDimension > & dimensions)
Extract a region of data from a flat data span using a Region and dimension info.
Template Parameters
T Data type.
Parameters
source_data Source data span.
region Region to extract.
dimensions Dimension descriptors.
Returns
Vector containing the extracted region data.
Exceptions
std::out_of_range if region is out of bounds.
Definition at line 69 of file RegionUtils.hpp.
{
    for (size_t i = 0; i < region.start_coordinates.size(); ++i) {
        if (region.end_coordinates[i] > 0 && (region.end_coordinates[i] >= dimensions[i].size)) {
            error<std::out_of_range>(
                Journal::Component::Kakshya, Journal::Context::Runtime,
                std::source_location::current(),
                "Requested region is out of bounds for dimension {}",
                std::to_string(i));
        }
    }
    uint64_t region_size = region.get_volume();
    std::vector<T> result;
    result.reserve(region_size);
    std::vector<uint64_t> current = region.start_coordinates;
    while (true) {
        uint64_t linear_index = coordinates_to_linear(current, dimensions);
        result.push_back(source_data[linear_index]);
        bool done = true;
        for (int dim = (int)current.size() - 1; dim >= 0; --dim) {
            if (current[dim] < region.end_coordinates[dim]) {
                current[dim]++;
                done = false;
                break;
            }
            current[dim] = region.start_coordinates[dim];
        }
        if (done)
            break;
    }
    return result;
}
References coordinates_to_linear(), MayaFlux::Kakshya::Region::end_coordinates, MayaFlux::Kakshya::Region::get_volume(), MayaFlux::Journal::Kakshya, MayaFlux::Journal::Runtime, and MayaFlux::Kakshya::Region::start_coordinates.
Referenced by extract_region(), extract_region(), extract_region_data(), and extract_region_data().