MayaFlux: MayaFlux::Kriya::mouse_dragged
mouse_dragged()
MAYAFLUX_API Vruta::Event MayaFlux::Kriya::mouse_dragged (std::shared_ptr< Core::Window > window, IO::MouseButtons button, std::function< void(double, double)> callback)
Creates an Event coroutine that triggers on mouse drag with specific button.
Parameters
window Window to listen to
button Mouse button that must be held for drag
callback Function to call on mouse drag with current position
Returns
Event coroutine that can be added to EventManager
Example:
auto task = mouse_dragged(window, IO::MouseButtons::Left,
    [](double x, double y) {
        // Handle mouse drag with left button at (x, y)
    });
Definition at line 173 of file InputEvents.cpp.
{
    auto& promise = co_await GetEventPromise {};
    auto& source = window->get_event_source();
    Vruta::WindowEventFilter filter;
    filter.event_type = Core::WindowEventType::MOUSE_MOTION;
    while (true) {
        if (promise.should_terminate)
            break;
        auto event = co_await WindowEventAwaiter(source, filter);
        if (!source.is_mouse_pressed(static_cast<int>(button)))
            continue;
        if (auto* pos = std::get_if<Core::WindowEvent::MousePosData>(&event.data))
            callback(pos->x, pos->y);
    }
}
References MayaFlux::Vruta::WindowEventFilter::event_type, and MayaFlux::Core::MOUSE_MOTION.
Referenced by MayaFlux::Nexus::Wiring::finalise(), MayaFlux::on_mouse_drag(), and MayaFlux::Portal::Forma::Context::register_handlers().