MayaFlux: MayaFlux::Yantra::compute_mean_statistic
compute_mean_statistic()
std::vector< double > MayaFlux::Yantra::compute_mean_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute mean statistic using zero-copy processing.
This function computes the arithmetic mean for a given data span. It calculates the average value in each window.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
Returns
Vector of mean values
Definition at line 336 of file AnalysisHelper.cpp.
{
    std::vector<double> mean_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            double sum = 0.0;
            for (double sample : window) {
                sum += sample;
            }
            mean_values[i] = sum / static_cast<double>(window.size());
        });
    return mean_values;
}
References compute_mean_statistic().
Referenced by compute_cv_statistic(), compute_mean_statistic(), MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::create_analysis_result().