MayaFlux: MayaFlux::Kakshya::find_region_for_position
find_region_for_position() [1/2]
std::optional< size_t > MayaFlux::Kakshya::find_region_for_position (const std::vector< uint64_t > & position, const std::vector< Region > & regions)
Find optimal region containing given position.
Parameters
position Coordinates to search for.
regions Vector of regions to search within.
Returns
Optional index of containing region.
Definition at line 369 of file RegionUtils.cpp.
{
    for (size_t i = 0; i < regions.size(); ++i) {
        if (regions[i].contains(position)) {
            return i;
        }
    }
    return std::nullopt;
}
References find_region_for_position().
Referenced by find_region_for_position(), and find_region_for_position().