MayaFlux: MayaFlux::Kakshya::extract_from_variant
extract_from_variant()
template<ProcessableData T> std::span< T > MayaFlux::Kakshya::extract_from_variant (const DataVariant & variant, std::vector< T > & storage, ComplexConversionStrategy strategy = ComplexConversionStrategy::MAGNITUDE)
Get typed span from DataVariant using concepts.
Template Parameters
T Data type (must satisfy ProcessableData)
Parameters
variant DataVariant to extract from
Returns
Span of type T, or empty span if type doesn't match
Definition at line 471 of file DataUtils.hpp.
{
    return std::visit([&storage, strategy](const auto& data) -> std::span<T> {
        using ValueType = typename std::decay_t<decltype(data)>::value_type;
        if constexpr (std::is_same_v<ValueType, T>) {
            storage = data;
            return std::span<T>(storage.data(), storage.size());
        } else if constexpr (is_convertible_data_v<ValueType, T>) {
            auto source_span = std::span<const ValueType>(data.data(), data.size());
            std::vector<ValueType> temp_source(source_span.begin(), source_span.end());
            auto temp_span = std::span<ValueType>(temp_source.data(), temp_source.size());
            return convert_data(temp_span, storage, strategy);
        } else {
            // throw std::runtime_error("Cannot convert from " + std::string(typeid(ValueType).name()) + " to " + std::string(typeid(T).name()));
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "No conversion available from {} to {}",
                typeid(ValueType).name(),
                typeid(T).name());
        }
    },
        variant);
}
References convert_data(), MayaFlux::Journal::Kakshya, MayaFlux::Journal::Runtime, and storage.
Referenced by MayaFlux::Kakshya::DynamicSoundStream::create_expanded_data(), and safe_copy_data_variant_to_span().