MayaFlux: MayaFlux::apply_gain
apply_gain() [2/2]
MAYAFLUX_API void MayaFlux::apply_gain (std::vector< double > & data, double gain_factor)
Apply gain to single-channel data (in-place)
Parameters
data Input data (modified in-place)
gain_factor Multiplication factor
Definition at line 491 of file Yantra.cpp.
{
    auto transformer = std::make_shared<Yantra::MathematicalTransformer<>>(Yantra::MathematicalOperation::GAIN);
    transformer->set_parameter("gain_factor", gain_factor);
    Yantra::Datum<std::vector<Kakshya::DataVariant>> input { { Kakshya::DataVariant(data) } };
    auto result = transformer->apply_operation(input);
    data = std::get<std::vector<double>>(result.data[0]);
}
References MayaFlux::Yantra::GAIN.
Referenced by apply_gain_per_channel(), mix(), and mix().