MayaFlux: MayaFlux::Yantra::find_zero_crossing_positions
find_zero_crossing_positions()
std::vector< size_t > MayaFlux::Yantra::find_zero_crossing_positions (std::span< const double > data, double threshold = 0.0)
Find actual zero-crossing positions in the signal.
Unlike compute_zero_crossing_energy which returns ZCR per window, this returns the actual sample indices where zero crossings occur.
Parameters
data Input data span
threshold Threshold value for crossing detection (default: 0.0)
Returns
Vector of sample positions where crossings occur
Definition at line 215 of file AnalysisHelper.cpp.
{
    std::vector<size_t> positions;
    positions.reserve(data.size() / 4);
    for (size_t i = 1; i < data.size(); ++i) {
        bool current_above = (data[i] >= threshold);
        bool previous_above = (data[i - 1] >= threshold);
        if (current_above != previous_above) {
            positions.push_back(i);
        }
    }
    positions.shrink_to_fit();
    return positions;
}
References find_zero_crossing_positions().
Referenced by MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::create_analysis_result(), and find_zero_crossing_positions().