MayaFlux: MayaFlux::Kinesis::apply_orbit_pan
apply_orbit_pan()
MAYAFLUX_API void MayaFlux::Kinesis::apply_orbit_pan (OrbitState & state, float dx, float dy)
Pan the focal point in the camera's local right/up plane.
Delta is scaled by distance so pan speed stays proportionate to zoom level.
Parameters
state Orbit state (focal mutated).
dx Horizontal pixel delta.
dy Vertical pixel delta.
Definition at line 52 of file OrbitState.cpp.
{
    const glm::vec3 forward = glm::normalize(st.focal - orbit_eye(st));
    const glm::vec3 right = glm::normalize(glm::cross(forward, glm::vec3(0.0F, 1.0F, 0.0F)));
    const glm::vec3 up = glm::normalize(glm::cross(right, forward));
    const float scale = st.distance * st.pan_sensitivity;
    st.focal -= right * (dx * scale);
    st.focal += up * (dy * scale);
}
References MayaFlux::Kinesis::OrbitState::distance, MayaFlux::Kinesis::OrbitState::focal, orbit_eye(), MayaFlux::Kinesis::OrbitState::pan_sensitivity, and scale().
Referenced by MayaFlux::bind_orbit_preset().