MayaFlux: MayaFlux::Journal::print
print() [1/2]
template<typename... Args> void MayaFlux::Journal::print (Component component, Context context, const char * msg_or_fmt, Args &&... args)
printf-style overload of print().
Log a simple message without source-location.
Intended for contexts where source location is unavailable or unnecessary. It is not effected by severity filters, so use sparingly.
Parameters
component The component generating the log message.
context The execution context of the log message.
message The log message content.
msg_or_fmt The format string.
args The format arguments.
Definition at line 212 of file Archivist.hpp.
{
    if constexpr (sizeof...(Args) == 0) {
        Archivist::instance().scribe_simple(component, context,
            std::string_view(msg_or_fmt));
    } else {
        auto msg = format_runtime(msg_or_fmt, std::forward<Args>(args)...);
        Archivist::instance().scribe_simple(component, context, msg);
    }
}
References format_runtime(), MayaFlux::Journal::Archivist::instance(), and MayaFlux::Journal::Archivist::scribe_simple().