MayaFlux: MayaFlux::Portal::Graphics::get_shader_foundry
get_shader_foundry()
MAYAFLUX_API ShaderFoundry & MayaFlux::Portal::Graphics::get_shader_foundry () inline
Get the global shader compiler instance.
Returns
Reference to singleton shader compiler
Must call initialize() before first use. Thread-safe after initialization.
Definition at line 681 of file ShaderFoundry.hpp.
{
    return ShaderFoundry::instance();
}
References MayaFlux::Portal::Graphics::ShaderFoundry::instance().
Referenced by MayaFlux::Yantra::GpuResourceManager::bind_descriptor(), MayaFlux::Yantra::GpuResourceManager::bind_image_sampled(), MayaFlux::Yantra::GpuResourceManager::bind_image_storage(), MayaFlux::Buffers::RenderProcessor::bind_texture(), MayaFlux::Buffers::ShaderProcessor::cleanup(), MayaFlux::Yantra::GpuResourceManager::cleanup(), MayaFlux::Buffers::ComputeProcessor::cleanup(), MayaFlux::Buffers::RenderProcessor::cleanup(), MayaFlux::Yantra::GpuResourceManager::dispatch(), MayaFlux::Yantra::GpuResourceManager::dispatch_batched(), MayaFlux::Yantra::GpuResourceManager::download(), MayaFlux::Yantra::GpuResourceManager::ensure_buffer(), MayaFlux::Buffers::ComputeProcessor::execute_shader(), MayaFlux::Buffers::RenderProcessor::execute_shader(), MayaFlux::Buffers::PresentProcessor::fallback_renderer(), MayaFlux::Buffers::ShaderProcessor::hot_reload_shader(), MayaFlux::Yantra::GpuResourceManager::initialise(), MayaFlux::Portal::Graphics::ComputePress::initialize(), MayaFlux::Buffers::RenderProcessor::initialize_descriptors(), MayaFlux::Buffers::ShaderProcessor::initialize_shader(), MayaFlux::Buffers::UVFieldProcessor::on_descriptors_created(), MayaFlux::Buffers::RenderProcessor::RenderProcessor(), MayaFlux::Buffers::RenderProcessor::set_fragment_shader(), MayaFlux::Buffers::RenderProcessor::set_geometry_shader(), MayaFlux::Buffers::RenderProcessor::set_tess_control_shader(), MayaFlux::Buffers::RenderProcessor::set_tess_eval_shader(), MayaFlux::Yantra::GpuResourceManager::transition_image(), MayaFlux::Buffers::ShaderProcessor::update_descriptors(), MayaFlux::Yantra::GpuResourceManager::upload(), and MayaFlux::Yantra::GpuResourceManager::upload_raw().