MayaFlux: MayaFlux::Buffers::download_audio_from_gpu
download_audio_from_gpu()
void MayaFlux::Buffers::download_audio_from_gpu (const std::shared_ptr< VKBuffer > & gpu_buffer, const std::shared_ptr< AudioBuffer > & audio_buffer, const std::shared_ptr< VKBuffer > & staging = nullptr)
Download GPU buffer to AudioBuffer (expects double precision)
Parameters
gpu_buffer Source GPU buffer (should contain double precision data)
audio_buffer Target audio buffer (always double[])
staging Optional staging buffer (auto-created if needed)
Downloads GPU data and copies to AudioBuffer. If the GPU buffer contains float data instead of double, DataAccess will handle the upconversion (though this is not recommended for audio precision).
Definition at line 373 of file StagingUtils.cpp.
{
    Kakshya::DataVariant downloaded_data;
    auto dimensions = std::vector<Kakshya::DataDimension> {
        Kakshya::DataDimension::time(
            gpu_buffer->get_size_bytes() / sizeof(double),
            "samples")
    };
    Kakshya::DataAccess accessor = download_to_view<double>(
        gpu_buffer, downloaded_data, dimensions,
        Kakshya::DataModality::AUDIO_1D, staging);
    auto double_view = accessor.view<double>();
    audio_buffer->get_data() = std::vector<double>(double_view.begin(), double_view.end());
    MF_DEBUG(Journal::Component::Buffers, Journal::Context::BufferProcessing,
        "Downloaded {} samples of double-precision audio from GPU", double_view.size());
}
References MayaFlux::Kakshya::AUDIO_1D, MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MF_DEBUG, MayaFlux::Kakshya::DataDimension::time(), and MayaFlux::Kakshya::DataAccess::view().
Referenced by MayaFlux::Buffers::TransferProcessor::process_gpu_to_audio().