MayaFlux: MayaFlux::Kinesis::Discrete::sort_span
sort_span()
void MayaFlux::Kinesis::Discrete::sort_span (std::span< double > data, SortingDirection direction, SortingAlgorithm algorithm = SortingAlgorithm::STANDARD)
Sort a single span in-place.
Parameters
data Mutable span
direction Sort direction
algorithm Algorithm to use
Definition at line 5 of file Sort.cpp.
{
    if (data.empty())
        return;
    execute(data.begin(), data.end(), double_comparator(direction), algorithm);
}
References double_comparator(), and execute().
Referenced by sort_channels(), and sort_span_into().