MayaFlux: MayaFlux::seconds_to_samples
seconds_to_samples()
MAYAFLUX_API uint64_t MayaFlux::seconds_to_samples (double seconds)
Converts a time duration in seconds to the equivalent number of audio samples.
Parameters
seconds Time duration in seconds
Returns
Equivalent number of audio samples based on the current sample rate
This function uses the sample rate from the default engine to calculate how many audio samples correspond to the given time duration in seconds. It's useful for scheduling tasks or processing buffers based on time intervals.
Definition at line 246 of file Chronie.cpp.
{
    uint64_t sample_rate = 48000;
    if (get_context().is_running()) {
        sample_rate = get_context().get_stream_info().sample_rate;
    }
    return static_cast<uint64_t>(seconds * (double)sample_rate);
}
References get_context(), MayaFlux::Core::Engine::get_stream_info(), and MayaFlux::Core::GlobalStreamInfo::sample_rate.
Referenced by route_network(), and route_node().