MayaFlux: MayaFlux::Yantra::sort_span_inplace
sort_span_inplace()
void MayaFlux::Yantra::sort_span_inplace (std::span< double > data, SortingDirection direction, SortingAlgorithm algorithm)
Sort a single span of doubles in-place.
Parameters
data Span of data to sort
direction Sort direction
algorithm Sort algorithm
Definition at line 5 of file SortingHelper.cpp.
{
    if (data.empty()) {
        return;
    }
    auto comp = create_double_comparator(direction);
    execute_sorting_algorithm(data.begin(), data.end(), comp, algorithm);
}
References create_double_comparator(), and execute_sorting_algorithm().
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::extract_chunked_data(), sort_channels_inplace(), and sort_span_extract().