MayaFlux: MayaFlux::Kinesis::generate_samples
generate_samples()
std::vector< SampleResult > MayaFlux::Kinesis::generate_samples (SpatialDistribution distribution, size_t count, const SamplerBounds & bounds, Kinesis::Stochastic::Stochastic & rng)
Generate a batch of spatially distributed samples.
Parameters
distribution Spatial distribution algorithm to apply
count Number of samples to generate
bounds Spatial domain
rng Stochastic engine (caller owns; enables reproducible sequences)
Returns
SampleResult vector of length <= count (exact for all deterministic modes)
All geometry is computed here. Callers convert SampleResult to their concrete vertex type via the projection helpers below.
Definition at line 328 of file VertexSampler.cpp.
{
    if (count == 0 || dist == SpatialDistribution::EMPTY) {
        return {};
    }
    switch (dist) {
    case SpatialDistribution::PERLIN_FIELD:
        return sample_perlin_field(bounds, count, rng);
    case SpatialDistribution::BROWNIAN_PATH:
        return sample_brownian_path(bounds, count, rng);
    case SpatialDistribution::STRATIFIED_CUBE:
        return sample_stratified_cube(bounds, count, rng);
    case SpatialDistribution::SPLINE_PATH:
        return sample_spline_path(bounds, count, rng);
    case SpatialDistribution::FIBONACCI_SPHERE:
        return sample_fibonacci_sphere(bounds, count);
    case SpatialDistribution::FIBONACCI_SPIRAL:
        return sample_fibonacci_spiral(bounds, count);
    case SpatialDistribution::TORUS:
        return sample_torus(bounds, count);
    case SpatialDistribution::LISSAJOUS:
        return sample_lissajous(bounds, count);
    default: {
        std::vector<SampleResult> out;
        out.reserve(count);
        for (size_t i = 0; i < count; ++i) {
            out.push_back(generate_sample_at(dist, i, count, bounds, rng));
        }
        return out;
    }
    }
}
References BROWNIAN_PATH, count, EMPTY, FIBONACCI_SPHERE, FIBONACCI_SPIRAL, generate_sample_at(), LISSAJOUS, PERLIN_FIELD, SPLINE_PATH, STRATIFIED_CUBE, and TORUS.
Referenced by MayaFlux::Nodes::Network::PointCloudNetwork::generate_initial_positions(), and MayaFlux::Nodes::Network::ParticleNetwork::generate_initial_vertices().