MayaFlux: MayaFlux::get_node_token
get_node_token()
MAYAFLUX_API Nodes::ProcessingToken MayaFlux::get_node_token (Domain domain) inline
Extracts node processing token from domain.
Parameters
domain The unified domain
Returns
Node processing token
Definition at line 174 of file Domain.hpp.
{
    return static_cast<Nodes::ProcessingToken>((domain >> 32) & 0xFFFF);
}
Referenced by operator|(), operator|(), register_network(), and register_node().