MayaFlux: MayaFlux::Kinesis::Discrete::peak_positions
peak_positions()
std::vector< size_t > MayaFlux::Kinesis::Discrete::peak_positions (std::span< const double > data, double threshold = 0.0, size_t min_distance = 1)
Sample indices of local peak maxima in the full span.
A peak at index i satisfies: |data[i]| > threshold, |data[i]| >= |data[i-1]|, |data[i]| >= |data[i+1]|, and i - last_peak >= min_distance.
Note
Produces sparse output; not vectorisable or suitable for compute kernels.
Parameters
data Input span
threshold Minimum absolute value to qualify as a peak
min_distance Minimum sample gap between accepted peaks
Returns
Sorted sample indices of detected peaks
Definition at line 646 of file Analysis.cpp.
{
    if (data.size() < 3)
        return {};
    std::vector<size_t> pos;
    pos.reserve(data.size() / 100);
    size_t last = 0;
    for (size_t i = 1; i + 1 < data.size(); ++i) {
        const double a = std::abs(data[i]);
        if (a > threshold
            && a >= std::abs(data[i - 1])
            && a >= std::abs(data[i + 1])
            && (pos.empty() || (i - last) >= min_distance)) {
            pos.push_back(i);
            last = i;
        }
    }
    pos.shrink_to_fit();
    return pos;
}
References a, and peak_positions().
Referenced by MayaFlux::Yantra::extract_peaks(), and peak_positions().