MayaFlux: MayaFlux::Kinesis::Discrete::spectral_energy
spectral_energy()
std::vector< double > MayaFlux::Kinesis::Discrete::spectral_energy (std::span< const double > data, size_t n_windows, uint32_t hop_size, uint32_t window_size)
Spectral energy per window using Hann-windowed FFT.
Note
Eigen::FFT dependency — not portable to compute shader contexts.
Parameters
data Input span
n_windows Pre-computed window count from num_windows()
hop_size Samples between window starts
window_size Samples per window (determines FFT size)
Returns
Per-window summed spectral energy, normalised by window_size
Definition at line 133 of file Analysis.cpp.
{
    std::vector<double> out(n_windows);
    std::vector<size_t> idx(n_windows);
    std::iota(idx.begin(), idx.end(), 0);
    const Eigen::VectorXd hw = hann_window(window_size);
    Parallel::for_each(Parallel::par_unseq, idx.begin(), idx.end(),
        [&](size_t i) {
            const size_t start = i * hop_size;
            auto w = data.subspan(start, std::min<size_t>(window_size, data.size() - start));
            Eigen::VectorXd buf = Eigen::VectorXd::Zero(window_size);
            for (size_t j = 0; j < w.size(); ++j)
                buf(static_cast<Eigen::Index>(j)) = w[j] * hw(static_cast<Eigen::Index>(j));
            Eigen::FFT<double> fft;
            Eigen::VectorXcd spec;
            fft.fwd(spec, buf);
            double e = 0.0;
            for (Eigen::Index j = 0; j < spec.size(); ++j)
                e += std::norm(spec(j));
            out[i] = e / static_cast<double>(window_size);
        });
    return out;
}
References spectral_energy().
Referenced by MayaFlux::Yantra::extract_high_spectral(), and spectral_energy().