MayaFlux: MayaFlux::add_processor
add_processor() [3/3]
MAYAFLUX_API void MayaFlux::add_processor (const std::shared_ptr< Buffers::BufferProcessor > & processor, const std::shared_ptr< Buffers::Buffer > & buffer, Buffers::ProcessingToken token = Buffers::ProcessingToken::AUDIO_BACKEND)
Adds a processor to a specific buffer.
Parameters
processor Processor to add
buffer Buffer to add the processor to
Adds the processor to the specified buffer's processing chain. Uses the default engine's buffer manager.
Definition at line 136 of file Graph.cpp.
{
    get_buffer_manager()->add_processor(processor, buffer, token);
}
References get_buffer_manager().
Referenced by create_processor(), create_processor(), MayaFlux::Kakshya::DataProcessingChain::DataProcessingChain(), and MayaFlux::Buffers::BufferProcessingControl::~BufferProcessingControl().