MayaFlux: MayaFlux::Kinesis::Discrete::mean
mean()
std::vector< double > MayaFlux::Kinesis::Discrete::mean (std::span< const double > data, size_t n_windows, uint32_t hop_size, uint32_t window_size)
Arithmetic mean per window.
Definition at line 200 of file Analysis.cpp.
{
    std::vector<double> out(n_windows);
    std::vector<size_t> idx(n_windows);
    std::iota(idx.begin(), idx.end(), 0);
    Parallel::for_each(Parallel::par_unseq, idx.begin(), idx.end(),
        [&](size_t i) {
            const size_t start = i * hop_size;
            auto w = data.subspan(start, std::min<size_t>(window_size, data.size() - start));
            double s = 0.0;
            for (double v : w)
                s += v;
            out[i] = s / static_cast<double>(w.size());
        });
    return out;
}
References MayaFlux::mean().
Referenced by MayaFlux::Yantra::extract_above_mean(), and MayaFlux::Yantra::extract_outliers().