MayaFlux: MayaFlux::normalize
normalize() [2/2]
MAYAFLUX_API void MayaFlux::normalize (std::vector< double > & data, double target_peak = 1.0)
Normalize single-channel data to specified peak level (in-place)
Parameters
data Input data (modified in-place)
target_peak Target peak amplitude (default: 1.0)
Definition at line 558 of file Yantra.cpp.
{
    auto transformer = std::make_shared<Yantra::MathematicalTransformer<>>(Yantra::MathematicalOperation::NORMALIZE);
    transformer->set_parameter("target_peak", target_peak);
    Yantra::IO<std::vector<Kakshya::DataVariant>> input { { Kakshya::DataVariant(data) } };
    auto result = transformer->apply_operation(input);
    data = std::get<std::vector<double>>(result.data[0]);
}
References MayaFlux::Yantra::NORMALIZE.
Referenced by normalize_channels(), MayaFlux::Yantra::transform_auto_correlate_fft(), MayaFlux::Yantra::transform_auto_correlate_fft(), MayaFlux::Yantra::transform_cross_correlate(), MayaFlux::Yantra::transform_cross_correlate(), and MayaFlux::Yantra::ConvolutionTransformer< InputType, OutputType >::transform_implementation().