MayaFlux: MayaFlux::register_network
register_network()
MAYAFLUX_API void MayaFlux::register_network (const std::shared_ptr< Nodes::Network::NodeNetwork > & network, const CreationContext & ctx)
Definition at line 41 of file Creator.cpp.
{
    auto token = get_node_token(ctx.domain.value());
    if (token == Nodes::ProcessingToken::AUDIO_RATE) {
        if (
            network->get_output_mode() != Nodes::Network::OutputMode::AUDIO_SINK
            && network->get_output_mode() != Nodes::Network::OutputMode::AUDIO_COMPUTE) {
            MF_WARN(Journal::Component::API,
                Journal::Context::Init,
                "Registering audio network in AUDIO_RATE domain without AUDIO_SINK  or AUDIO_COMPUTE mode. Forcing AUDIO_SINK mode.");
            network->set_output_mode(Nodes::Network::OutputMode::AUDIO_SINK);
        }
        if (ctx.channel.has_value()) {
            network->add_channel_usage(ctx.channel.value());
        } else if (ctx.channels.has_value()) {
            for (uint32_t ch : ctx.channels.value()) {
                network->add_channel_usage(ch);
            }
        }
    } else if (token == Nodes::ProcessingToken::VISUAL_RATE && network->get_output_mode() != Nodes::Network::OutputMode::GRAPHICS_BIND) {
        MF_WARN(Journal::Component::API,
            Journal::Context::Init,
            "Registering visual network in VISUAL_RATE domain without GRAPHICS_BIND output mode. Forcing GRAPHICS_BIND mode.");
        network->set_output_mode(Nodes::Network::OutputMode::GRAPHICS_BIND);
    }
    register_node_network(network, token);
}
References MayaFlux::Journal::API, MayaFlux::Nodes::Network::AUDIO_COMPUTE, MayaFlux::Nodes::AUDIO_RATE, MayaFlux::Nodes::Network::AUDIO_SINK, MayaFlux::CreationContext::channel, MayaFlux::CreationContext::channels, MayaFlux::CreationContext::domain, get_node_token(), MayaFlux::Nodes::Network::GRAPHICS_BIND, MayaFlux::Journal::Init, MF_WARN, register_node_network(), and MayaFlux::Nodes::VISUAL_RATE.
Referenced by MayaFlux::CreationHandle< T >::apply_network_context(), and operator|().