MayaFlux: MayaFlux::Kinesis::Discrete::regions_around_positions
regions_around_positions()
std::vector< std::pair< size_t, size_t > > MayaFlux::Kinesis::Discrete::regions_around_positions (const std::vector< size_t > & positions, size_t half_region, size_t data_size)
Build [start, end) intervals centred on a set of positions.
Parameters
positions Sample indices of region centres
half_region Radius in samples on each side
data_size Total span length for clamping
Returns
One [start, end) pair per position
Definition at line 52 of file Extract.cpp.
{
    std::vector<std::pair<size_t, size_t>> out;
    out.reserve(positions.size());
    for (size_t pos : positions) {
        const size_t s = (pos >= half_region) ? pos - half_region : 0;
        const size_t e = std::min(pos + half_region, data_size);
        if (s < e)
            out.emplace_back(s, e);
    }
    return out;
}
Referenced by MayaFlux::Yantra::extract_onsets(), MayaFlux::Yantra::extract_peaks(), and MayaFlux::Yantra::extract_zero_crossings().