MayaFlux: MayaFlux::Kinesis::Discrete::estimate_frequency
estimate_frequency()
MAYAFLUX_API double MayaFlux::Kinesis::Discrete::estimate_frequency (std::span< const double > data, double sample_rate, double fallback = 0.0, double threshold = 0.0)
Estimate the dominant cycle frequency of a sampled signal.
Detects zero-crossing positions in data and derives frequency from the mean inter-crossing interval. Each consecutive pair of crossings represents one half-period; the mean of all half-periods gives a robust estimate robust to occasional spurious crossings.
Returns fallback when fewer than two crossings are found (signal is silent, DC, or the buffer is shorter than one half-cycle).
Parameters
data Input span (any sampled sequence)
sample_rate Samples per second
fallback Value returned when estimation is not possible
threshold Zero-crossing detection threshold (default: 0.0)
Returns
Estimated frequency in Hz, or fallback
Definition at line 646 of file Analysis.cpp.
{
    if (data.size() < 2)
        return fallback;
    const auto crossings = zero_crossing_positions(data, threshold);
    if (crossings.size() < 2)
        return fallback;
    const double mean_half_period = static_cast<double>(crossings.back() - crossings.front())
        / static_cast<double>(crossings.size() - 1);
    if (mean_half_period < 1.0)
        return fallback;
    return sample_rate / (2.0 * mean_half_period);
}
References estimate_frequency(), MayaFlux::Kinesis::threshold(), and zero_crossing_positions().
Referenced by estimate_frequency().