MayaFlux: MayaFlux::Kriya::mouse_released
mouse_released()
MAYAFLUX_API Vruta::Event MayaFlux::Kriya::mouse_released (std::shared_ptr< Core::Window > window, IO::MouseButtons button, std::function< void(double, double)> callback)
Creates an Event coroutine that triggers on specific mouse button release.
Parameters
window Window to listen to
button Mouse button to wait for
callback Function to call on button release
Returns
Event coroutine that can be added to EventManager
Example:
auto task = mouse_released(window, IO::MouseButtons::Right,
    [](double x, double y) {
        // Handle right mouse button release at (x, y)
    });
Definition at line 126 of file InputEvents.cpp.
{
    auto& promise = co_await GetEventPromise {};
    auto& source = window->get_event_source();
    Vruta::WindowEventFilter filter;
    filter.event_type = Core::WindowEventType::MOUSE_BUTTON_RELEASED;
    filter.button = button;
    while (true) {
        if (promise.should_terminate) {
            break;
        }
        co_await WindowEventAwaiter(source, filter);
        auto [x, y] = source.get_mouse_position();
        callback(x, y);
    }
}
References MayaFlux::Vruta::WindowEventFilter::button, MayaFlux::Vruta::WindowEventFilter::event_type, and MayaFlux::Core::MOUSE_BUTTON_RELEASED.
Referenced by MayaFlux::Nexus::Wiring::finalise(), MayaFlux::on_mouse_released(), and MayaFlux::Portal::Forma::Context::register_handlers().