MayaFlux: MayaFlux::Portal::Text::press
press() [2/2]
MAYAFLUX_API std::shared_ptr< Core::VKImage > MayaFlux::Portal::Text::press (std::string_view text, glm::uvec2 render_bounds, const PressParams & params = {})
Composite a UTF-8 string directly into a new GPU texture.
No TextBuffer, no quad geometry, no registration required. The returned VKImage is RGBA8, shader-read layout, ready for binding into a FormaBuffer or any other descriptor slot.
Parameters
text UTF-8 string to composite.
render_bounds Texture dimensions and wrap boundary in pixels.
params atlas, color, budget_h. render_bounds field ignored.
Returns
GPU-resident VKImage, or nullptr on failure.
Definition at line 263 of file InkPress.cpp.
{
    GlyphAtlas* atlas = resolve_atlas(params.atlas);
    if (!atlas)
        return nullptr;
    const uint32_t buf_w = render_bounds.x;
    const uint32_t composite_h = std::max(render_bounds.y,
        static_cast<uint32_t>(atlas->line_height()));
    const auto result = composite(text, *atlas, params.color, buf_w, composite_h,
        static_cast<float>(atlas->ascender()));
    if (!result) {
        MF_WARN(Journal::Component::Portal, Journal::Context::API,
            "press(AsTexture): no glyphs produced for '{}'", std::string(text));
        return nullptr;
    }
    const uint32_t budget_h = composite_h;
    const size_t budget_bytes = static_cast<size_t>(buf_w) * budget_h * 4;
    std::vector<uint8_t> pixels(budget_bytes, 0);
    const auto copy_h = static_cast<uint32_t>(
        result->pixels.size() / (static_cast<size_t>(buf_w) * 4));
    for (uint32_t row = 0; row < copy_h; ++row) {
        std::memcpy(
            pixels.data() + static_cast<size_t>(row) * buf_w * 4,
            result->pixels.data() + static_cast<size_t>(row) * buf_w * 4,
            static_cast<size_t>(buf_w) * 4);
    }
    auto& loom = Portal::Graphics::get_texture_manager();
    auto image = loom.create_2d(buf_w, budget_h, Portal::Graphics::ImageFormat::RGBA8,
        pixels.data(), 1);
    MF_DEBUG(Journal::Component::Portal, Journal::Context::API,
        "press(AsTexture): {}x{} content in {}x{} texture",
        buf_w, result->h, buf_w, budget_h);
    return image;
}
References MayaFlux::Journal::API, MayaFlux::Portal::Text::GlyphAtlas::ascender(), MayaFlux::Portal::Text::PressParams::atlas, MayaFlux::Portal::Text::PressParams::color, MayaFlux::Portal::Graphics::get_texture_manager(), image, MayaFlux::Portal::Text::GlyphAtlas::line_height(), MF_DEBUG, MF_WARN, pixels, MayaFlux::Journal::Portal, and MayaFlux::Portal::Graphics::RGBA8.