MayaFlux: Lila::socket_errno
socket_errno()
static int Lila::socket_errno () static
Definition at line 24 of file Server.cpp.
{
#ifdef MAYAFLUX_PLATFORM_WINDOWS
    return WSAGetLastError();
#else
    return errno;
#endif
}
Referenced by Lila::Server::handle_client(), Lila::Server::read_message(), Lila::Server::server_loop(), and Lila::Server::start().