MayaFlux: MayaFlux::Yantra::transform_logarithmic
transform_logarithmic() [2/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_logarithmic (DataType & input, double a, double b, double c = 1.0, double base = std::numbers::e)
Logarithmic transformation y = a * log_base(b * x + c) (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
a Scale factor
b Input scale factor
c Offset to ensure positive argument
base Logarithm base (default: e for natural log)
Returns
Transformed data
Definition at line 246 of file MathematicalHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    double log_base_factor = (base == std::numbers::e) ? 1.0 : (1.0 / std::log(base));
    for (auto& span : target_data) {
        std::ranges::transform(span, span.begin(),
            [a, b, c, log_base_factor](double x) {
                double arg = b * x + c;
                if (arg <= 0.0)
                    return 0.0;
                return a * std::log(arg) * log_base_factor;
            });
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References a, b, and transform_logarithmic().
Referenced by MayaFlux::Yantra::MathematicalTransformer< InputType, OutputType >::transform_implementation(), transform_logarithmic(), and transform_logarithmic().