MayaFlux: MayaFlux::Portal::Forma::internal::create_buffer_impl
create_buffer_impl()
MAYAFLUX_API std::shared_ptr< Buffers::FormaBuffer > MayaFlux::Portal::Forma::internal::create_buffer_impl (std::shared_ptr< Core::Window > window, size_t capacity, Graphics::PrimitiveTopology topology, const std::string & texture_binding = {}, std::vector< std::pair< std::string, std::shared_ptr< Core::VKImage > > > additional_textures = {})
Core buffer construction — capacity-explicit path for internal use.
Called by public create_buffer overloads and by internal .cpp callers (plot, Collapsible) that know their capacity upfront.
Definition at line 101 of file Forma.cpp.
    {
        auto buf = std::make_shared<Buffers::FormaBuffer>(capacity, topology);
        g_buffer_manager->add_buffer(buf, Buffers::ProcessingToken::GRAPHICS_BACKEND);
        if (!additional_textures.empty()) {
            buf->setup_rendering({
                .target_window = std::move(window),
                .additional_textures = std::move(additional_textures),
            });
        } else if (!texture_binding.empty()) {
            buf->setup_rendering({
                .target_window = std::move(window),
                .default_texture_binding = texture_binding,
            });
        } else {
            buf->setup_rendering({ .target_window = std::move(window) });
        }
        return buf;
    }
References MayaFlux::Buffers::GRAPHICS_BACKEND.
Referenced by MayaFlux::Portal::Forma::create_buffer(), MayaFlux::Portal::Forma::create_buffer(), MayaFlux::Portal::Forma::create_buffer(), MayaFlux::Portal::Forma::create_buffer(), and MayaFlux::Portal::Forma::plot().