MayaFlux: MayaFlux::unregister_audio_node
unregister_audio_node() [2/2]
MAYAFLUX_API void MayaFlux::unregister_audio_node (const std::shared_ptr< Nodes::Node > & node, uint32_t channel = 0)
Removes a node from the root node of a specific channel.
Parameters
node Node to remove
channel Channel index
Removes the node from being a child of the root node for the specified channel. Uses the default engine's node graph manager.
Definition at line 60 of file Graph.cpp.
{
    auto manager = get_node_graph_manager();
    if (!manager) {
        MF_ERROR(Journal::Component::API, Journal::Context::NodeProcessing,
            "Node graph manager not initialized - cannot unregister audio node");
        return;
    }
    if (channel >= manager->get_channel_count(Nodes::ProcessingToken::AUDIO_RATE)) {
        MF_ERROR(Journal::Component::API, Journal::Context::NodeProcessing,
            "Channel index out of range for audio node registration");
    }
    manager->remove_from_root(node, Nodes::ProcessingToken::AUDIO_RATE, channel);
}
References MayaFlux::Journal::API, MayaFlux::Nodes::AUDIO_RATE, get_node_graph_manager(), MF_ERROR, and MayaFlux::Journal::NodeProcessing.
Referenced by MayaFlux::Nodes::ChainNode::initialize(), MayaFlux::Nodes::BinaryOpNode::initialize(), and unregister_audio_node().