MayaFlux: MayaFlux::Yantra::infer_from_region
infer_from_region()
std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_from_region (const Kakshya::Region & region, const std::shared_ptr< Kakshya::SignalSourceContainer > & container)
Infer structure from Region (placeholder since regions are markers)
Definition at line 54 of file StructureIntrospection.cpp.
{
    if (!container) {
        std::vector<Kakshya::DataDimension> dimensions;
        dimensions.emplace_back(Kakshya::DataDimension::time(1));
        return std::make_pair(std::move(dimensions), Kakshya::DataModality::UNKNOWN);
    }
    auto structure = container->get_structure();
    auto [dimensions, modality] = infer_from_container(container);
    if (!region.start_coordinates.empty() && !region.end_coordinates.empty() && region.end_coordinates[1] != container->get_frame_size()) {
        std::vector<uint64_t> shape;
        int size = static_cast<int>(region.end_coordinates[0] - region.start_coordinates[0]);
        shape.push_back(std::abs(size) + 1);
        shape.push_back(region.end_coordinates[1]);
        if (auto region_modality = region.get_attribute<Kakshya::DataModality>("modality");
            region_modality.has_value()) {
            dimensions = Kakshya::DataDimension::create_dimensions(region_modality.value(), shape, structure.memory_layout);
            modality = region_modality.value();
        } else {
            dimensions = Kakshya::DataDimension::create_dimensions(modality, shape, structure.memory_layout);
        }
    }
    return { dimensions, modality };
}
References MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Kakshya::Region::end_coordinates, MayaFlux::Kakshya::Region::get_attribute(), infer_from_container(), size, MayaFlux::Kakshya::Region::start_coordinates, MayaFlux::Kakshya::DataDimension::time(), and MayaFlux::Kakshya::UNKNOWN.
Referenced by infer_from_region_group(), infer_from_segments(), and infer_structure().