MayaFlux: MayaFlux::Nodes::Filters::shift_parser
shift_parser()
std::pair< int, int > MayaFlux::Nodes::Filters::shift_parser (const std::string & str)
Parses a string representation of filter order into input/output shift configuration.
Parameters
str String in format "N_M" where N is input order and M is output order
Returns
Pair of integers representing input and output shift values
This utility function converts a simple string representation of filter order into the corresponding shift configuration for the filter's internal buffers.
Definition at line 7 of file Filter.cpp.
{
    size_t underscore = str.find('_');
    if (underscore == std::string::npos) {
        throw std::invalid_argument("Invalid format. Supply numberical format of nInputs_nOutpits like 25_2");
    }
    int inputs = std::stoi(str.substr(0, underscore));
    int outputs = std::stoi(str.substr(underscore + 1));
    return std::make_pair(inputs, outputs);
}
Referenced by MayaFlux::Nodes::Filters::Filter::Filter(), MayaFlux::Nodes::Filters::Filter::Filter(), and MayaFlux::Nodes::Filters::Filter::set_shift().