MayaFlux: MayaFlux::create_sampler_from_stream
create_sampler_from_stream()
MAYAFLUX_API std::shared_ptr< Kriya::SamplingPipeline > MayaFlux::create_sampler_from_stream (std::shared_ptr< Kakshya::DynamicSoundStream > stream, uint32_t channel = 0, uint64_t max_dur_ms = 0)
Construct a built SamplingPipeline from an existing DynamicSoundStream.
Allows multiple SamplingPipeline instances to share a single loaded stream, one per output channel, without re-reading the file. The stream is typically obtained from a previously created sampler via get_stream(), or loaded directly via get_io_manager()->load_audio_bounded().
auto ch0 = MayaFlux::create_sampler("res/audio.wav", 48000 * 5);
auto ch1 = MayaFlux::create_sampler_from_stream(ch0->get_stream(), 1);
auto ch2 = MayaFlux::create_sampler_from_stream(ch0->get_stream(), 2);
Parameters
stream Loaded DynamicSoundStream to share.
channel Output channel index (default: 0).
max_dur_ms Optional maximum duration in milliseconds. 0 for infinite.
Returns
Built SamplingPipeline, or nullptr if stream is null.
Definition at line 43 of file Rigs.cpp.
{
    if (!stream)
        return nullptr;
    auto& mgr = *get_buffer_manager();
    auto& sched = *get_scheduler();
    const uint32_t buf_size = Config::get_buffer_size();
    auto sampler = std::make_shared<Kriya::SamplingPipeline>(
        std::move(stream), mgr, sched, channel, buf_size);
    if (max_dur_ms > 0) {
        sampler->build_for(max_dur_ms);
    } else {
        sampler->build();
    }
    return sampler;
}
References channel, get_buffer_manager(), MayaFlux::Config::get_buffer_size(), and get_scheduler().
Referenced by create_samplers().