MayaFlux: MayaFlux::Portal::Forma::Geometry::horizontal_fader
horizontal_fader()
MAYAFLUX_API GeometryFn< float > MayaFlux::Portal::Forma::Geometry::horizontal_fader (Kinesis::AABB2D bounds, float handle_w, glm::vec3 track_color = glm::vec3(0.3F), glm::vec3 handle_color = glm::vec3(0.9F))
Geometry function for a horizontal fader in NDC space.
Parameters
bounds Full extent of the fader in NDC.
handle_w Handle width in NDC units.
track_color Track quad color.
handle_color Handle quad color.
Definition at line 9 of file Geometry.cpp.
{
    return [bounds, handle_w, track_color, handle_color](
               float v, std::vector<uint8_t>& out, Element& el) {
        float x = bounds.min.x + v * (bounds.width() - handle_w);
        float yt = bounds.min.y + bounds.height() * 0.35F;
        float yb = bounds.min.y + bounds.height() * 0.65F;
        Kinesis::AABB2D track { .min = glm::vec2(bounds.min.x, yt), .max = glm::vec2(bounds.max.x, yb) };
        Kinesis::AABB2D handle { .min = glm::vec2(x, bounds.min.y), .max = glm::vec2(x + handle_w, bounds.max.y) };
        auto verts = Kakshya::to_mesh_vertices(Kinesis::filled_rect(track, track_color));
        auto herts = Kakshya::to_mesh_vertices(Kinesis::filled_rect(handle, handle_color));
        verts.insert(verts.end(), herts.begin(), herts.end());
        write_verts(out, verts);
        el.bounds_hint = handle;
        el.contains = {};
    };
}
References MayaFlux::Kinesis::filled_rect(), MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kakshya::to_mesh_vertices(), MayaFlux::Kinesis::AABB2D::width(), and write_verts().