MayaFlux: MayaFlux::Kakshya::set_or_update_region_data
set_or_update_region_data() [2/3]
template<typename T > void MayaFlux::Kakshya::set_or_update_region_data (std::vector< std::span< T > > & dest_spans, const std::vector< std::span< const T > > & source_data, const Region & region, const std::vector< DataDimension > & dimensions)
Write or update a region of data in planar storage.
Template Parameters
T Data type.
Parameters
dest_spans Vector of destination data spans (one per channel).
source_data Vector of source data spans (one per channel).
region Region to update (includes channel dimension).
dimensions Dimension descriptors (includes channel dimension).
Definition at line 374 of file RegionUtils.hpp.
{
    size_t channel_dim_idx = 0;
    for (size_t i = 0; i < dimensions.size(); ++i) {
        if (dimensions[i].role == DataDimension::Role::CHANNEL) {
            channel_dim_idx = i;
            break;
        }
    }
    size_t start_channel = region.start_coordinates[channel_dim_idx];
    size_t end_channel = region.end_coordinates[channel_dim_idx];
    for (size_t ch = start_channel; ch <= end_channel && ch < dest_spans.size(); ++ch) {
        size_t source_channel_idx = ch - start_channel;
        if (source_channel_idx >= source_data.size())
            continue;
        Region channel_region = remove_channel_dimension(region, dimensions);
        auto non_channel_dims = get_non_channel_dimensions(dimensions);
        set_or_update_region_data(
            dest_spans[ch],
            source_data[source_channel_idx],
            channel_region,
            non_channel_dims);
    }
}
References MayaFlux::Kakshya::DataDimension::CHANNEL, MayaFlux::Kakshya::Region::end_coordinates, get_non_channel_dimensions(), remove_channel_dimension(), set_or_update_region_data(), and MayaFlux::Kakshya::Region::start_coordinates.