MayaFlux: MayaFlux::Buffers::update_buffer_with_node_data
update_buffer_with_node_data()
void MayaFlux::Buffers::update_buffer_with_node_data (const std::shared_ptr< Nodes::Node > & node, std::span< double > buffer, double mix)
Apply node output to an existing buffer with mixing.
Definition at line 256 of file BufferUtils.cpp.
{
    if (!node) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "apply_to_buffer: null node");
        return;
    }
    static std::atomic<uint64_t> s_context_counter { 1 };
    uint64_t my_context_id = s_context_counter.fetch_add(1, std::memory_order_relaxed);
    const auto state = node->m_state.load(std::memory_order_acquire);
    if (state == Nodes::NodeState::INACTIVE && !node->is_buffer_processed()) {
        for (double& sample : buffer) {
            sample += node->process_sample(0.F) * mix;
        }
        node->mark_buffer_processed();
        return;
    }
    bool claimed = node->try_claim_snapshot_context(my_context_id);
    if (claimed) {
        try {
            node->save_state();
            for (double& sample : buffer) {
                sample += node->process_sample(0.F) * mix;
            }
            node->restore_state();
            if (node->is_buffer_processed()) {
                node->request_buffer_reset();
            }
            node->release_snapshot_context(my_context_id);
        } catch (const std::exception& e) {
            node->release_snapshot_context(my_context_id);
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Error processing node: {}", e.what());
        }
    } else {
        uint64_t active_context = node->get_active_snapshot_context();
        if (!wait_for_snapshot_completion(node, active_context)) {
            return;
        }
        node->save_state();
        for (double& sample : buffer) {
            sample += node->process_sample(0.F) * mix;
        }
        node->restore_state();
        if (node->is_buffer_processed()) {
            node->request_buffer_reset();
        }
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Nodes::INACTIVE, MF_RT_ERROR, MayaFlux::mix(), and wait_for_snapshot_completion().
Referenced by MayaFlux::Buffers::NodeSourceProcessor::processing_function().