MayaFlux: MayaFlux::Kinesis::Vision::gaussian_blur
gaussian_blur() [2/2]
MAYAFLUX_API std::vector< float > MayaFlux::Kinesis::Vision::gaussian_blur (std::span< const float > src, uint32_t w, uint32_t h, float sigma)
Separable Gaussian blur.
Kernel radius is ceil(3 * sigma). Kernel is normalised to unit sum. Decomposes into horizontal and vertical 1D passes via filter_separable.
Parameters
src Single-channel float span, size must be w * h.
w Image width in pixels.
h Image height in pixels.
sigma Standard deviation in pixels. Must be > 0.
Returns
Blurred float vector of length w * h.
Definition at line 512 of file ImageFilter.cpp.
{
    const size_t n = static_cast<size_t>(w) * h;
    std::vector<float> tmp(n);
    std::vector<float> out(n);
    gaussian_blur(src, tmp, out, w, h, sigma);
    return out;
}
References gaussian_blur(), and h.
Referenced by canny(), gaussian_blur(), and harris_response().