MayaFlux: MayaFlux::Kinesis::Discrete::zero_crossing_positions
zero_crossing_positions()
std::vector< size_t > MayaFlux::Kinesis::Discrete::zero_crossing_positions (std::span< const double > data, double threshold = 0.0)
Sample indices of zero crossings in the full span.
Note
Produces sparse output; not vectorisable or suitable for compute kernels.
Parameters
data Input span
threshold Crossing threshold (default: 0.0)
Returns
Sorted sample indices where sign changes occur
Definition at line 634 of file Analysis.cpp.
{
    std::vector<size_t> pos;
    pos.reserve(data.size() / 4);
    for (size_t i = 1; i < data.size(); ++i) {
        if ((data[i] >= threshold) != (data[i - 1] >= threshold))
            pos.push_back(i);
    }
    pos.shrink_to_fit();
    return pos;
}
References zero_crossing_positions().
Referenced by MayaFlux::Yantra::extract_zero_crossings(), and zero_crossing_positions().