MayaFlux: MayaFlux::Config::set_journal_severity
set_journal_severity()
MAYAFLUX_API void MayaFlux::Config::set_journal_severity (Journal::Severity severity)
Sets the minimum severity level for journal entries to be logged.
Parameters
severity Minimum severity level (e.g., INFO, WARN, ERROR, TRACE, DEBUG, FATAL)
Definition at line 72 of file Config.cpp.
{
    Journal::Archivist::instance().set_min_severity(severity);
}
References MayaFlux::Journal::Archivist::instance(), and MayaFlux::Journal::Archivist::set_min_severity().
Referenced by store_journal_entries().