MayaFlux: MayaFlux::mix
mix() [1/2]
MAYAFLUX_API std::vector< double > MayaFlux::mix (const std::vector< Kakshya::DataVariant > & streams)
Definition at line 1043 of file Yantra.cpp.
{
    if (streams.empty())
        return {};
    auto numeric_data = Yantra::OperationHelper::extract_numeric_data(streams);
    if (is_same_size(numeric_data)) {
        size_t channel_length = numeric_data[0].size();
        std::vector<double> result(channel_length, 0.0);
        for (const auto& span : numeric_data) {
            for (size_t i = 0; i < span.size(); ++i) {
                result[i] += span[i];
            }
        }
        double gain = 1.0 / static_cast<double>(numeric_data.size());
        apply_gain(result, gain);
        return result;
    } else {
        std::vector<std::vector<double>> double_streams;
        double_streams.reserve(streams.size());
        for (const auto& span : numeric_data) {
            double_streams.emplace_back(span.begin(), span.end());
        }
        return mix(double_streams);
    }
}
References apply_gain(), MayaFlux::Yantra::OperationHelper::extract_numeric_data(), is_same_size(), and mix().