MayaFlux: MayaFlux::load_image_file
load_image_file()
MAYAFLUX_API std::shared_ptr< Buffers::TextureBuffer > MayaFlux::load_image_file (const std::string & filepath)
Loads an image file into a TextureBuffer.
Parameters
filepath Path to the image file to load
Returns
Shared pointer to loaded TextureBuffer, or nullptr on failure
Supports common image formats such as PNG, JPEG, BMP, TGA, PSD, GIF, HDR, PIC, and PNM. Returns nullptr on failure with error details logged to stderr.
Definition at line 117 of file Depot.cpp.
{
    IO::ImageReader reader;
    if (!reader.open(filepath)) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "Failed to open image: {}", filepath);
        return nullptr;
    }
    auto texture_buffer = reader.create_texture_buffer();
    if (!texture_buffer) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "Failed to create texture buffer from: {}", filepath);
        return nullptr;
    }
    MF_INFO(Journal::Component::API, Journal::Context::FileIO,
        "Loaded image: {} ({}x{})",
        fs::path(filepath).filename().string(),
        texture_buffer->get_width(),
        texture_buffer->get_height());
    return texture_buffer;
}
References MayaFlux::Journal::API, MayaFlux::IO::ImageReader::create_texture_buffer(), MayaFlux::Journal::FileIO, MF_ERROR, MF_INFO, and MayaFlux::IO::ImageReader::open().
Referenced by MayaFlux::Creator::load_buffer().