MayaFlux: MayaFlux::Kinesis::compute_view_transform
compute_view_transform()
MAYAFLUX_API ViewTransform MayaFlux::Kinesis::compute_view_transform (NavigationState & state, float aspect)
Compute a ViewTransform from the current NavigationState.
Computes dt from state.last_tick, advances eye position by held movement flags scaled by move_speed * dt, updates last_tick, then constructs view and projection matrices.
Parameters
state Navigation state (eye and last_tick mutated by this call)
aspect Framebuffer width / height
Returns
ViewTransform ready for push constant upload
Definition at line 23 of file NavigationState.cpp.
{
    advance_navigation(st);
    return build_view_transform(st, aspect);
}
References advance_navigation(), and build_view_transform().
Referenced by MayaFlux::bind_fly_preset(), MayaFlux::Nexus::Locus::Locus(), and MayaFlux::Nexus::Locus::Locus().