MayaFlux: MayaFlux::Kakshya::convert_data
convert_data()
template<typename From , typename To > std::span< To > MayaFlux::Kakshya::convert_data (std::span< From > source, std::vector< To > & storage, ComplexConversionStrategy strategy = ComplexConversionStrategy::MAGNITUDE)
Convert a span of one data type to another (with type conversion).
Template Parameters
From Source type.
To Destination type.
Parameters
source Source data span.
dest Destination data span.
Returns
Span of converted data.
Definition at line 347 of file DataUtils.hpp.
{
    return DataConverter<From, To>::convert(source, storage, strategy);
}
References MayaFlux::Kakshya::DataConverter< From, To, Enable >::convert(), and storage.
Referenced by convert_complex(), convert_variant(), and extract_from_variant().