MayaFlux: MayaFlux::get_node_graph_manager
get_node_graph_manager()
MAYAFLUX_API std::shared_ptr< Nodes::NodeGraphManager > MayaFlux::get_node_graph_manager ()
Gets the node graph manager from the default engine.
Returns
Shared pointer to the centrally managed NodeGraphManager
Returns the node graph manager that's managed by the default engine instance. All node operations using the convenience functions will use this manager.
Definition at line 35 of file Graph.cpp.
{
    return get_context().get_node_graph_manager();
}
References get_context(), and MayaFlux::Core::Engine::get_node_graph_manager().
Referenced by operator*(), operator+(), operator>>(), operator|(), operator|(), operator|(), register_audio_node(), route_network(), route_network(), route_node(), route_node(), unregister_audio_node(), and unregister_node().