MayaFlux: MayaFlux::mix_with_gains
mix_with_gains() [1/2]
MAYAFLUX_API std::vector< double > MayaFlux::mix_with_gains (const std::vector< Kakshya::DataVariant > & streams, const std::vector< double > & gains)
Definition at line 1102 of file Yantra.cpp.
{
    if (streams.empty() || gains.size() != streams.size()) {
        throw std::invalid_argument("Streams and gains vectors must have the same size");
    }
    auto numeric_data = Yantra::OperationHelper::extract_numeric_data(streams);
    if (is_same_size(numeric_data)) {
        size_t channel_length = numeric_data[0].size();
        std::vector<double> result(channel_length, 0.0);
        for (size_t s = 0; s < numeric_data.size(); ++s) {
            const auto& span = numeric_data[s];
            double gain = gains[s];
            for (size_t i = 0; i < span.size(); ++i) {
                result[i] += span[i] * gain;
            }
        }
        return result;
    }
    std::vector<std::vector<double>> double_streams;
    double_streams.reserve(streams.size());
    for (const auto& span : numeric_data) {
        double_streams.emplace_back(span.begin(), span.end());
    }
    return mix_with_gains(double_streams, gains);
}
References MayaFlux::Yantra::OperationHelper::extract_numeric_data(), is_same_size(), and mix_with_gains().