MayaFlux: MayaFlux::register_audio_buffer
register_audio_buffer()
MAYAFLUX_API void MayaFlux::register_audio_buffer (const std::shared_ptr< Buffers::AudioBuffer > & buffer, uint32_t channel = 0)
Registers an AudioBuffer with the default engine's buffer manager.
Parameters
buffer AudioBuffer to register
channel Channel index to associate with the buffer (default: 0)
Adds the buffer to the default engine's buffer management system, enabling it to participate in the audio processing pipeline. The buffer will be processed during each audio cycle according to its configuration. Multiple buffers can be registered to the same channel for layered processing.
Definition at line 213 of file Graph.cpp.
{
    get_buffer_manager()->add_buffer(buffer, Buffers::ProcessingToken::AUDIO_BACKEND, channel);
}
References MayaFlux::Buffers::AUDIO_BACKEND, and get_buffer_manager().
Referenced by create_buffer(), create_input_listener_buffer(), and register_buffer().