MayaFlux: MayaFlux::Buffers::download_device_local
download_device_local()
MAYAFLUX_API void MayaFlux::Buffers::download_device_local (const std::shared_ptr< VKBuffer > & source, const std::shared_ptr< VKBuffer > & target, const std::shared_ptr< VKBuffer > & staging_buffer)
Download data from a device-local buffer using a staging buffer.
Parameters
source Source VKBuffer to download data from
target Target VKBuffer to store the downloaded data
staging_buffer Host-visible staging VKBuffer used for the download
This function handles downloading data from a device-local VKBuffer by utilizing a staging buffer. It issues a command to copy the data from the device-local buffer to the staging buffer, invalidates the staging buffer memory, and then copies the data into a CPU-accessible format to update the target buffer.
Definition at line 166 of file StagingUtils.cpp.
{
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "upload_host_visible requires a valid buffer service");
    }
    buffer_service->execute_immediate([&](void* ptr) {
        vk::BufferCopy copy_region;
        copy_region.srcOffset = 0;
        copy_region.dstOffset = 0;
        copy_region.size = source->get_size_bytes();
        auto cmd = static_cast<vk::CommandBuffer*>(ptr);
        cmd->copyBuffer(
            source->get_buffer(),
            staging_buffer->get_buffer(),
            1, &copy_region);
    });
    staging_buffer->mark_invalid_range(0, source->get_size_bytes());
    auto& staging_resources = staging_buffer->get_buffer_resources();
    auto invalid_ranges = staging_buffer->get_and_clear_invalid_ranges();
    for (auto& [offset, size] : invalid_ranges) {
        buffer_service->invalidate_range(
            staging_resources.memory,
            offset,
            size);
    }
    void* staging_mapped = staging_resources.mapped_ptr;
    if (!staging_mapped) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Staging buffer has no mapped pointer");
    }
    std::vector<uint8_t> raw_bytes(source->get_size_bytes());
    std::memcpy(raw_bytes.data(), staging_mapped, source->get_size_bytes());
    std::dynamic_pointer_cast<VKBuffer>(target)->set_data({ raw_bytes });
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Registry::BackendRegistry::get_service(), and MayaFlux::Registry::BackendRegistry::instance().
Referenced by MayaFlux::Buffers::VKBuffer::clone_to(), MayaFlux::Buffers::BufferDownloadProcessor::download_device_local(), and download_from_gpu().