MayaFlux: MayaFlux::Nodes::atomic_dec_modulator_count
atomic_dec_modulator_count()
void MayaFlux::Nodes::atomic_dec_modulator_count (std::atomic< uint32_t > & count, int amount)
Atomically decrements the modulator count by a specified amount.
Parameters
count The atomic counter to decrement
amount The amount to decrement by
Decreases a node's modulator count when it's no longer being used as a modulation source by another node. When the count reaches zero, the node becomes eligible for state resets, allowing the audio engine to optimize processing and avoid redundant calculations in the signal chain.
Definition at line 126 of file NodeUtils.cpp.
{
    count.fetch_sub(amount, std::memory_order_relaxed);
}
References count.
Referenced by MayaFlux::Nodes::ChainNode::process_sample(), MayaFlux::Nodes::BinaryOpNode::process_sample(), MayaFlux::Nodes::CompositeOpNode< N >::process_sample(), MayaFlux::Nodes::Filters::FIR::process_sample(), MayaFlux::Nodes::Filters::IIR::process_sample(), MayaFlux::Nodes::Generator::Impulse::process_sample(), MayaFlux::Nodes::Generator::Logic::process_sample(), MayaFlux::Nodes::Generator::Phasor::process_sample(), MayaFlux::Nodes::Generator::Polynomial::process_sample(), MayaFlux::Nodes::Generator::Sine::process_sample(), and MayaFlux::Buffers::FilterProcessor::process_single_sample().