MayaFlux: MayaFlux::Yantra::infer_structure
infer_structure()
template<ComputeData T> static std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_structure (const T & data, const std::shared_ptr< Kakshya::SignalSourceContainer > & container = nullptr) static
Infer dimensions and modality from any ComputeData type.
Template Parameters
T ComputeData type
Parameters
data Input data to analyze
Returns
Pair of (dimensions, modality)
Definition at line 133 of file StructureIntrospection.hpp.
{
    if constexpr (std::is_same_v<T, Kakshya::DataVariant>) {
        return infer_from_data_variant(data);
    } else if constexpr (std::is_same_v<T, std::shared_ptr<Kakshya::SignalSourceContainer>>) {
        return infer_from_container(data);
    } else if constexpr (std::is_same_v<T, Kakshya::Region>) {
        return infer_from_region(data, container);
    } else if constexpr (std::is_same_v<T, Kakshya::RegionGroup>) {
        return infer_from_region_group(data, container);
    } else if constexpr (std::is_same_v<T, std::vector<Kakshya::RegionSegment>>) {
        return infer_from_segments(data, container);
    } else if constexpr (std::is_base_of_v<Eigen::MatrixBase<T>, T>) {
        return infer_from_eigen(data);
    } else {
        return infer_generic_structure(data);
    }
}
References infer_from_container(), infer_from_data_variant(), infer_from_eigen(), infer_from_region(), infer_from_region_group(), infer_from_segments(), and infer_generic_structure().
Referenced by MayaFlux::Yantra::OperationHelper::extract_structured_double().