MayaFlux: MayaFlux::End
End()
MAYAFLUX_API void MayaFlux::End ()
Stops and cleans up the default engine.
Convenience wrapper for Engine::End() on the default engine.
Definition at line 136 of file Core.cpp.
{
    internal::terminating = true;
    if (internal::initialized) {
        internal::cleanup_engine();
    }
}
References MayaFlux::internal::cleanup_engine(), MayaFlux::internal::initialized, and MayaFlux::internal::terminating.
Referenced by main(), MayaFlux::Core::Engine::operator=(), and MayaFlux::Core::Engine::operator=().