MayaFlux: MayaFlux::Buffers::create_staging_buffer
create_staging_buffer()
MAYAFLUX_API std::shared_ptr< VKBuffer > MayaFlux::Buffers::create_staging_buffer (size_t size)
Create staging buffer for transfers.
Parameters
size Size in bytes
Returns
Host-visible staging buffer ready for transfers
Definition at line 224 of file StagingUtils.cpp.
{
    auto buffer = std::make_shared<VKBuffer>(
        size,
        VKBuffer::Usage::STAGING,
        Kakshya::DataModality::UNKNOWN);
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "create_staging_buffer requires a valid buffer service");
    }
    buffer_service->initialize_buffer(buffer);
    return buffer;
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Registry::BackendRegistry::instance(), size, MayaFlux::Buffers::VKBuffer::STAGING, and MayaFlux::Kakshya::UNKNOWN.
Referenced by MayaFlux::Buffers::MeshProcessor::allocate_gpu_buffers(), MayaFlux::Buffers::MeshNetworkProcessor::allocate_gpu_buffers(), MayaFlux::Buffers::GeometryBindingsProcessor::bind_geometry_node(), MayaFlux::Buffers::NetworkGeometryProcessor::bind_network(), download_from_gpu(), MayaFlux::Buffers::FormaProcessor::on_attach(), MayaFlux::Buffers::GeometryWriteProcessor::on_attach(), MayaFlux::Buffers::FormaProcessor::processing_function(), MayaFlux::Buffers::GeometryWriteProcessor::processing_function(), MayaFlux::Kakshya::readback_region(), MayaFlux::Buffers::GeometryBindingsProcessor::upload_index_data(), and upload_to_gpu().