MayaFlux: MayaFlux::Yantra::compute_harmonic_energy
compute_harmonic_energy()
std::vector< double > MayaFlux::Yantra::compute_harmonic_energy (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute harmonic energy using low-frequency FFT analysis.
This function computes the harmonic energy for a given data span. It focuses on the lower portion of the frequency spectrum (harmonics).
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
Returns
Vector of harmonic energy values
Definition at line 173 of file AnalysisHelper.cpp.
{
    std::vector<double> harmonic_energy(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    Eigen::VectorXd hanning_window(window_size);
    for (uint32_t i = 0; i < window_size; ++i) {
        hanning_window(i) = 0.5 * (1.0 - std::cos(2.0 * M_PI * i / (window_size - 1)));
    }
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            Eigen::VectorXd windowed_data = Eigen::VectorXd::Zero(window_size);
            const size_t actual_size = window.size();
            for (int j = 0; j < actual_size; ++j) {
                windowed_data(j) = window[j] * hanning_window(j);
            }
            Eigen::FFT<double> fft;
            Eigen::VectorXcd fft_result;
            fft.fwd(fft_result, windowed_data);
            const int harmonic_bins = std::max(1, static_cast<int>(fft_result.size() / 8));
            double energy = 0.0;
            for (int j = 1; j < harmonic_bins; ++j) {
                energy += std::norm(fft_result(j));
            }
            harmonic_energy[i] = energy / static_cast<double>(harmonic_bins);
        });
    return harmonic_energy;
}
References compute_harmonic_energy().
Referenced by MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::compute_energy_values(), and compute_harmonic_energy().