MayaFlux: MayaFlux::rms_combined
rms_combined()
MAYAFLUX_API double MayaFlux::rms_combined (const std::vector< Kakshya::DataVariant > & channels)
Calculate RMS energy across all channels (mix then analyze)
Parameters
channels Vector of channel data
Returns
Single RMS value across all mixed channels
Definition at line 110 of file Yantra.cpp.
{
    auto data = Yantra::OperationHelper::extract_numeric_data(channels);
    if (is_same_size(data)) {
        auto result = rms_per_channel(channels);
        double sum_squares = 0.0;
        for (double rms_val : result) {
            sum_squares += rms_val * rms_val;
        }
        return std::sqrt(sum_squares / result.size());
    } else {
        auto mixed = concat_vectors(data);
        return rms(mixed);
    }
}
References concat_vectors(), MayaFlux::Yantra::OperationHelper::extract_numeric_data(), is_same_size(), rms(), and rms_per_channel().