MayaFlux: MayaFlux::get_buffer_manager
get_buffer_manager()
MAYAFLUX_API std::shared_ptr< Buffers::BufferManager > MayaFlux::get_buffer_manager ()
Gets the buffer manager from the default engine.
Returns
Shared pointer to the centrally managed BufferManager
Returns the buffer manager that's managed by the default engine instance. All buffer operations using the convenience functions will use this manager.
Definition at line 131 of file Graph.cpp.
{
    return get_context().get_buffer_manager();
}
References MayaFlux::Core::Engine::get_buffer_manager(), and get_context().
Referenced by add_processor(), add_processor(), add_processor(), attach_quick_process(), MayaFlux::internal::attach_quick_process_audio(), MayaFlux::internal::attach_quick_process_graphics(), clone_buffer_to_channels(), clone_buffer_to_channels(), connect_node_to_buffer(), connect_node_to_channel(), create_buffer_pipeline(), detach_from_audio_input(), get_root_audio_buffer(), hook_sound_container_to_buffers(), operator|(), operator|(), operator|(), read_from_audio_input(), register_audio_buffer(), register_graphics_buffer(), remove_supplied_buffer_from_channel(), route_buffer(), route_buffer(), supply_buffer_to_channel(), unregister_audio_buffer(), and unregister_graphics_buffer().