MayaFlux: MayaFlux::Portal::Forma::Plot::plot_tick_labels
plot_tick_labels() [1/2]
MAYAFLUX_API std::vector< LabelSpec > MayaFlux::Portal::Forma::Plot::plot_tick_labels (const TickLabelsSpec & spec)
Generate construction-free tick label specs.
Values are evenly interpolated across spec.range. Label bounds are placed adjacent to spec.plot_bounds according to spec.edge.
Definition at line 237 of file PlotSpec.cpp.
{
    const uint32_t count = std::max(spec.count, 2U);
    const bool horizontal = spec.edge == TickEdge::Bottom || spec.edge == TickEdge::Top;
    std::vector<LabelSpec> labels;
    labels.reserve(count);
    for (uint32_t i = 0; i < count; ++i) {
        const float t = static_cast<float>(i) / static_cast<float>(count - 1);
        const float value = spec.range.min + t * (spec.range.max - spec.range.min);
        const std::string text = std::format("{:.{}f}", value,
            static_cast<int>(spec.decimal_places));
        Kinesis::AABB2D label_bounds {};
        if (horizontal) {
            const float cx = spec.plot_bounds.min.x + t * spec.plot_bounds.width();
            const float half_w = spec.plot_bounds.width() / static_cast<float>(count) * 0.5F;
            if (spec.edge == TickEdge::Bottom) {
                label_bounds = Kinesis::AABB2D {
                    .min = { cx - half_w, spec.plot_bounds.min.y - spec.label_h },
                    .max = { cx + half_w, spec.plot_bounds.min.y },
                };
            } else {
                label_bounds = Kinesis::AABB2D {
                    .min = { cx - half_w, spec.plot_bounds.max.y },
                    .max = { cx + half_w, spec.plot_bounds.max.y + spec.label_h },
                };
            }
        } else {
            const float cy = spec.plot_bounds.min.y + t * spec.plot_bounds.height();
            const float half_h = spec.plot_bounds.height() / static_cast<float>(count) * 0.5F;
            if (spec.edge == TickEdge::Left) {
                label_bounds = Kinesis::AABB2D {
                    .min = { spec.plot_bounds.min.x - spec.label_w, cy - half_h },
                    .max = { spec.plot_bounds.min.x, cy + half_h },
                };
            } else {
                label_bounds = Kinesis::AABB2D {
                    .min = { spec.plot_bounds.max.x, cy - half_h },
                    .max = { spec.plot_bounds.max.x + spec.label_w, cy + half_h },
                };
            }
        }
        labels.push_back(LabelSpec {
            .text = text,
            .bounds = label_bounds,
            .color = spec.color,
            .name = spec.name_prefix + "_" + std::to_string(i),
            .interactive = false,
        });
    }
    return labels;
}
References Bottom, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::color, count, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::count, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::decimal_places, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::edge, MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Portal::Forma::Plot::TickLabelsSpec::label_h, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::label_w, Left, MayaFlux::Kinesis::AABB2D::max, MayaFlux::Portal::Forma::Plot::AxisRange::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Plot::AxisRange::min, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::name_prefix, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::plot_bounds, MayaFlux::Portal::Forma::Plot::TickLabelsSpec::range, MayaFlux::Portal::Forma::Plot::LabelSpec::text, Top, and MayaFlux::Kinesis::AABB2D::width().
Referenced by plot_tick_labels().