MayaFlux: MayaFlux::Yantra::config_from_spec
config_from_spec()
GpuShaderConfig MayaFlux::Yantra::config_from_spec (const Portal::Graphics::ShaderSpec & spec) inline
Derive a GpuShaderConfig from a ShaderSpec.
Compiles (or retrieves cached) the shader via ShaderFoundry and packages the result with workgroup size and push constant size. Returns a config with INVALID_SHADER on compilation failure.
Callers use this alongside bindings_from_spec() to configure any concrete GpuExecutionContext subclass without depending on a specific executor type.
auto spec  = ShaderSpec::Assemble{}
    .ssbo("sig", BindingDirection::InOut, Kakshya::GpuDataFormat::FLOAT32)
    .pc("gain")
    .op(KernelOp::Scale)
    .build();
auto cfg      = config_from_spec(spec);
auto bindings = bindings_from_spec(spec);
auto exec = std::make_shared<ShaderExecutionContext<>>(cfg, bindings);
my_op->set_gpu_backend(exec);
Definition at line 90 of file ShaderSpecBinding.hpp.
{
    return GpuShaderConfig {
        .workgroup_size = spec.workgroup_size,
        .push_constant_size = spec.push_constant_bytes,
        .shader_id = Portal::Graphics::get_shader_foundry().load_shader(spec),
    };
}
References MayaFlux::Portal::Graphics::get_shader_foundry(), MayaFlux::Portal::Graphics::ShaderFoundry::load_shader(), MayaFlux::Portal::Graphics::ShaderSpec::push_constant_bytes, MayaFlux::Portal::Graphics::ShaderSpec::workgroup_size, and MayaFlux::Yantra::GpuShaderConfig::workgroup_size.
Referenced by MayaFlux::Yantra::ComputationGrammar::RuleBuilder::executes().