MayaFlux: MayaFlux::Yantra::Granular::make_granular_context
make_granular_context() [1/3]
ExecutionContext MayaFlux::Yantra::Granular::make_granular_context (uint32_t grain_size, uint32_t hop_size, const std::string & feature_key, AnalysisType analysis_type, const std::string & qualifier = {}, uint32_t channel = 0, bool ascending = true, uint32_t gpu_sort_threshold = 0) inline
Construct an ExecutionContext for the granular pipeline using a built-in AnalysisType.
AttributeOp will internally construct a default-configured analyzer for the given type and extract the scalar named by qualifier. Omit qualifier to use the canonical default for that type.
Parameters
grain_size Samples per grain.
hop_size Hop size between grain onsets.
feature_key Attribute name written onto each grain Region.
analysis_type Which analysis category to use for attribution. Supported: FEATURE, STATISTICAL.
qualifier Scalar to extract from the analysis result. Empty uses type default.
channel Source channel index.
ascending Sort direction for the subsequent SortOp.
gpu_sort_threshold Grain count at which SortOp switches to GPU path. 0 = CPU only.
Returns
Populated ExecutionContext.
Definition at line 282 of file GranularWorkflow.hpp.
                                 {},
    uint32_t channel = 0,
    bool ascending = true,
    uint32_t gpu_sort_threshold = 0)
{
    ExecutionContext ctx;
    ctx.execution_metadata["grain_size"] = grain_size;
    ctx.execution_metadata["hop_size"] = hop_size;
    ctx.execution_metadata["channel"] = channel;
    ctx.execution_metadata["feature_key"] = feature_key;
    ctx.execution_metadata["ascending"] = ascending;
    ctx.execution_metadata["gpu_sort_threshold"] = gpu_sort_threshold;
    ctx.execution_metadata["analysis_type"] = analysis_type;
    ctx.execution_metadata["analyzer_qualifier"] = qualifier;
    return ctx;
}
Referenced by process(), process(), process_to_container(), process_to_container(), and process_to_container_additive().