MayaFlux: MayaFlux::Config::get_sample_rate
get_sample_rate()
MAYAFLUX_API uint32_t MayaFlux::Config::get_sample_rate ()
Gets the sample rate from the default engine.
Returns
Current sample rate in Hz
Definition at line 45 of file Config.cpp.
{
    return get_context().get_stream_info().sample_rate;
}
References MayaFlux::get_context(), MayaFlux::Core::Engine::get_stream_info(), and MayaFlux::Core::GlobalStreamInfo::sample_rate.
Referenced by MayaFlux::Nodes::Network::ModalNetwork::initialize_modes(), MayaFlux::load_audio_file(), MayaFlux::Nodes::Generator::Logic::process_sample(), MayaFlux::Buffers::SoundFileBridge::setup_processors(), MayaFlux::Nodes::Generator::Impulse::update_phase_increment(), MayaFlux::Nodes::Generator::Phasor::update_phase_increment(), and MayaFlux::Nodes::Generator::Sine::update_phase_increment().