MayaFlux: MayaFlux::Nodes::try_reset_processed_state
try_reset_processed_state()
void MayaFlux::Nodes::try_reset_processed_state (std::shared_ptr< Node > node)
Attempts to reset the processed state of a node.
Parameters
node The node whose processed state should be reset
Evaluates whether a node's processed state can be safely reset based on its current modulator count and other conditions. This is essential for the audio engine's processing cycle, as it determines which nodes need to be recalculated in the next cycle and which can reuse their previous output values, balancing processing efficiency with signal accuracy.
Definition at line 97 of file NodeUtils.cpp.
{
    if (node && node->m_modulator_count.load(std::memory_order_relaxed) == 0) {
        node->reset_processed_state();
    }
}
Referenced by MayaFlux::Nodes::ChainNode::process_sample(), MayaFlux::Nodes::BinaryOpNode::process_sample(), MayaFlux::Nodes::CompositeOpNode< N >::process_sample(), MayaFlux::Nodes::Filters::FIR::process_sample(), MayaFlux::Nodes::Filters::IIR::process_sample(), MayaFlux::Nodes::Generator::Impulse::process_sample(), MayaFlux::Nodes::Generator::Logic::process_sample(), MayaFlux::Nodes::Generator::Phasor::process_sample(), MayaFlux::Nodes::Generator::Polynomial::process_sample(), MayaFlux::Nodes::Generator::Sine::process_sample(), MayaFlux::Nodes::Generator::Counter::process_sample(), and MayaFlux::Buffers::FilterProcessor::process_single_sample().