MayaFlux: MayaFlux::Kakshya::advance_position
advance_position() [2/2]
std::vector< uint64_t > MayaFlux::Kakshya::advance_position (const std::vector< uint64_t > & current_positions, uint64_t frames_to_advance, const ContainerDataStructure & structure, bool looping_enabled, const Region & loop_region)
Advance current positions by a number of frames, with optional looping.
Parameters
current_positions Current positions per channel.
frames_to_advance Number of frames to advance.
structure Container data structure (for total frames).
looping_enabled Whether looping is enabled.
loop_region Loop region for wrapping.
Returns
New advanced positions per channel.
Definition at line 153 of file CoordUtils.cpp.
{
    uint64_t num_channels = structure.get_channel_count();
    uint64_t total_frames = structure.get_samples_count_per_channel();
    if (current_positions.size() != num_channels) {
        throw std::invalid_argument(
            "Position vector size " + std::to_string(current_positions.size()) + " must match channel count " + std::to_string(num_channels));
    }
    std::vector<uint64_t> new_positions;
    new_positions.reserve(num_channels);
    for (size_t ch = 0; ch < num_channels; ++ch) {
        uint64_t current_frame = current_positions[ch];
        uint64_t new_frame = current_frame + frames_to_advance;
        if (new_frame >= total_frames) {
            if (looping_enabled && !loop_region.start_coordinates.empty()) {
                uint64_t loop_start = (ch < loop_region.start_coordinates.size())
                    ? loop_region.start_coordinates[ch]
                    : loop_region.start_coordinates[0];
                uint64_t loop_end = (ch < loop_region.end_coordinates.size())
                    ? loop_region.end_coordinates[ch]
                    : loop_region.end_coordinates[0];
                if (loop_end > loop_start) {
                    uint64_t loop_length = loop_end - loop_start + 1;
                    uint64_t overflow = new_frame - total_frames;
                    new_frame = loop_start + (overflow % loop_length);
                } else {
                    new_frame = loop_start;
                }
            } else {
                new_frame = total_frames - 1;
            }
        }
        new_positions.push_back(new_frame);
    }
    return new_positions;
}
References MayaFlux::Kakshya::Region::end_coordinates, MayaFlux::Kakshya::ContainerDataStructure::get_channel_count(), MayaFlux::Kakshya::ContainerDataStructure::get_samples_count_per_channel(), and MayaFlux::Kakshya::Region::start_coordinates.
Referenced by MayaFlux::Kakshya::SoundStreamContainer::advance_read_position(), MayaFlux::Kakshya::RegionProcessorBase::organize_container_data(), and MayaFlux::Kakshya::ContiguousAccessProcessor::process().