MayaFlux: MayaFlux::mix
mix() [2/2]
MAYAFLUX_API std::vector< double > MayaFlux::mix (const std::vector< std::vector< double > > & streams)
Mix multiple data streams with equal weighting.
Parameters
streams Vector of data streams to mix
Returns
Mixed output data (average of all streams)
Definition at line 1019 of file Yantra.cpp.
{
    if (streams.empty())
        return {};
    size_t max_length = 0;
    for (const auto& stream : streams) {
        max_length = std::max(max_length, stream.size());
    }
    std::vector<double> result(max_length, 0.0);
    for (const auto& stream : streams) {
        for (size_t i = 0; i < stream.size(); ++i) {
            result[i] += stream[i];
        }
    }
    double gain = 1.0 / static_cast<double>(streams.size());
    apply_gain(result, gain);
    return result;
}
References apply_gain().
Referenced by MayaFlux::Buffers::BufferProcessingControl::connect_node_to_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::connect_node_to_audio_channel(), MayaFlux::Buffers::BufferManager::connect_node_to_buffer(), connect_node_to_buffer(), MayaFlux::Buffers::BufferManager::connect_node_to_channel(), connect_node_to_channel(), mix(), MayaFlux::Buffers::NodeSourceProcessor::set_mix(), MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to(), MayaFlux::Buffers::BufferManager::supply_buffer_to(), supply_buffer_to_channel(), supply_buffer_to_channels(), and MayaFlux::Buffers::update_buffer_with_node_data().