MayaFlux: MayaFlux::Nodes::detail::composite_apply_semantics
composite_apply_semantics()
void MayaFlux::Nodes::detail::composite_apply_semantics (const std::vector< std::shared_ptr< Node > > & inputs, NodeGraphManager & manager, ProcessingToken token)
Definition at line 258 of file NodeCombine.cpp.
    {
        if (manager.get_node_config().binary_op_semantics != NodeBinaryOpSemantics::REPLACE)
            return;
        for (const auto& input : inputs) {
            for (auto ch : get_active_channels(input, 0))
                manager.remove_from_root(input, token, ch);
        }
    }
References MayaFlux::Nodes::NodeConfig::binary_op_semantics, MayaFlux::Nodes::get_active_channels(), MayaFlux::Nodes::NodeGraphManager::get_node_config(), MayaFlux::Nodes::NodeGraphManager::remove_from_root(), and MayaFlux::Nodes::REPLACE.