MayaFlux: MayaFlux::remove_processor
remove_processor() [2/3]
void MayaFlux::remove_processor (const std::shared_ptr< Buffers::BufferProcessor > & processor, const std::shared_ptr< Buffers::Buffer > & buffer)
Removes a processor from a specific buffer.
Parameters
processor Processor to remove
buffer Buffer to remove the processor from
Removes the processor from the specified buffer's processing chain. Uses the default engine's buffer manager.
Definition at line 153 of file Graph.cpp.
{
    get_buffer_manager()->remove_processor(processor, buffer);
}
References get_buffer_manager().
Referenced by MayaFlux::Kakshya::DataProcessingChain::DataProcessingChain(), and MayaFlux::Buffers::BufferProcessingControl::~BufferProcessingControl().