MayaFlux: MayaFlux::operator|
operator|() [4/7]
MAYAFLUX_API std::shared_ptr< Buffers::Buffer > MayaFlux::operator| (const TemporalWrapper< Buffers::Buffer > & wrapper, Domain domain)
Activates a buffer in a specific domain for the duration specified by the TemporalWrapper.
This operator overload implements the syntax:
buffer >> Time(2.0, 1) | domain;
It activates the wrapped buffer in the given domain for the specified duration and channel(s).
Parameters
wrapper The TemporalWrapper containing the buffer and timing information.
domain The domain in which to activate the buffer.
Returns
A shared pointer to the activated buffer.
Definition at line 45 of file Temporal.cpp.
{
    auto buffer = wrapper.entity();
    const auto& spec = wrapper.spec();
    auto buffer_token = get_buffer_token(domain);
    auto activation = std::make_shared<Kriya::TemporalActivation>(*get_scheduler(), *get_node_graph_manager(), *get_buffer_manager());
    if (spec.channels.has_value() && !spec.channels.value().empty()) {
        activation->activate_buffer(buffer, spec.seconds, buffer_token, spec.channels.value()[0]);
    } else {
        activation->activate_buffer(buffer, spec.seconds, buffer_token);
    }
    static std::vector<std::shared_ptr<Kriya::TemporalActivation>> active_timers;
    active_timers.push_back(activation);
    if (active_timers.size() > 100) {
        std::erase_if(active_timers, [](const std::shared_ptr<Kriya::TemporalActivation>& t) {
            return !t->is_active();
        });
    }
    return buffer;
}
References MayaFlux::TemporalWrapper< T >::entity(), get_buffer_manager(), get_buffer_token(), get_node_graph_manager(), get_scheduler(), and MayaFlux::TemporalWrapper< T >::spec().