MayaFlux: MayaFlux::Portal::Graphics::get_render_flow
get_render_flow()
MAYAFLUX_API RenderFlow & MayaFlux::Portal::Graphics::get_render_flow () inline
Get the global render flow instance.
Definition at line 328 of file RenderFlow.hpp.
{
    return RenderFlow::instance();
}
References MayaFlux::Portal::Graphics::RenderFlow::instance().
Referenced by MayaFlux::Buffers::RenderProcessor::cleanup(), MayaFlux::Buffers::RenderProcessor::execute_shader(), MayaFlux::Buffers::PresentProcessor::fallback_renderer(), MayaFlux::Buffers::RenderProcessor::initialize_descriptors(), and MayaFlux::Buffers::RenderProcessor::initialize_pipeline().