MayaFlux: MayaFlux::Yantra::infer_from_eigen
infer_from_eigen()
template<typename EigenType > static std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_from_eigen (const EigenType & eigen_data) static
Infer structure from Eigen matrix/vector.
Definition at line 48 of file StructureIntrospection.hpp.
{
    std::vector<Kakshya::DataDimension> dimensions;
    Kakshya::DataModality modality {};
    using Scalar = typename EigenType::Scalar;
    if constexpr (EigenType::IsVectorAtCompileTime) {
        if constexpr (MayaFlux::ComplexData<Scalar>) {
            dimensions.emplace_back(Kakshya::DataDimension::frequency(eigen_data.size()));
            modality = Kakshya::DataModality::SPECTRAL_2D;
        } else if constexpr (MayaFlux::DecimalData<Scalar>) {
            dimensions.emplace_back(Kakshya::DataDimension::time(eigen_data.size()));
            modality = Kakshya::DataModality::AUDIO_1D;
        } else {
            dimensions.emplace_back(Kakshya::DataDimension("vector_data", eigen_data.size(), 1,
                Kakshya::DataDimension::Role::CUSTOM));
            modality = Kakshya::DataModality::TENSOR_ND;
        }
    } else {
        auto rows = eigen_data.rows();
        auto cols = eigen_data.cols();
        if constexpr (MayaFlux::ComplexData<Scalar>) {
            dimensions.emplace_back(Kakshya::DataDimension::time(rows, "time_frames"));
            dimensions.emplace_back(Kakshya::DataDimension::frequency(cols, "frequency_bins"));
            modality = Kakshya::DataModality::SPECTRAL_2D;
        } else if constexpr (MayaFlux::DecimalData<Scalar>) {
            dimensions.emplace_back(Kakshya::DataDimension::time(rows, "samples"));
            if (cols == 1) {
                modality = Kakshya::DataModality::AUDIO_1D;
            } else if (cols <= 16) {
                dimensions.emplace_back(Kakshya::DataDimension::channel(cols));
                modality = Kakshya::DataModality::AUDIO_MULTICHANNEL;
            } else {
                dimensions.emplace_back(Kakshya::DataDimension::frequency(cols, "features"));
                modality = Kakshya::DataModality::SPECTRAL_2D;
            }
        } else if constexpr (MayaFlux::IntegerData<Scalar>) {
            dimensions.emplace_back(Kakshya::DataDimension::spatial(rows, 'y'));
            dimensions.emplace_back(Kakshya::DataDimension::spatial(cols, 'x'));
            modality = Kakshya::DataModality::IMAGE_2D;
        } else {
            dimensions.emplace_back(Kakshya::DataDimension("matrix_rows", rows, 1,
                Kakshya::DataDimension::Role::CUSTOM));
            dimensions.emplace_back(Kakshya::DataDimension("matrix_cols", cols, 1,
                Kakshya::DataDimension::Role::CUSTOM));
            modality = Kakshya::DataModality::TENSOR_ND;
        }
    }
    return std::make_pair(std::move(dimensions), modality);
}
References MayaFlux::Kakshya::AUDIO_1D, MayaFlux::Kakshya::AUDIO_MULTICHANNEL, MayaFlux::Kakshya::DataDimension::channel(), MayaFlux::Kakshya::DataDimension::CUSTOM, MayaFlux::Kakshya::DataDimension::frequency(), MayaFlux::Kakshya::IMAGE_2D, MayaFlux::Kakshya::DataDimension::spatial(), MayaFlux::Kakshya::SPECTRAL_2D, MayaFlux::Kakshya::TENSOR_ND, and MayaFlux::Kakshya::DataDimension::time().
Referenced by infer_structure().