MayaFlux: MayaFlux::mean_combined
mean_combined()
MAYAFLUX_API double MayaFlux::mean_combined (const std::vector< Kakshya::DataVariant > & channels)
Calculate mean across all channels (mix then analyze)
Parameters
channels Vector of channel data
Returns
Single mean value across all mixed channels
Definition at line 70 of file Yantra.cpp.
{
    auto data = Yantra::OperationHelper::extract_numeric_data(channels);
    if (is_same_size(data)) {
        auto result = mean_per_channel(channels);
        return std::accumulate(result.begin(), result.end(), 0.0) / result.size();
    } else {
        auto mixed = concat_vectors(data);
        return mean(mixed);
    }
}
References concat_vectors(), MayaFlux::Yantra::OperationHelper::extract_numeric_data(), is_same_size(), mean(), and mean_per_channel().