MayaFlux: MayaFlux::internal::cleanup_engine
cleanup_engine()
void MayaFlux::internal::cleanup_engine ()
Definition at line 18 of file Core.cpp.
    {
        std::lock_guard<std::recursive_mutex> lock(engine_mutex);
        if (engine_ref) {
            if (initialized) {
                if (engine_ref->is_running()) {
                    engine_ref->Pause();
                }
                engine_ref->End();
                Journal::Archivist::shutdown();
            }
            engine_ref.reset();
            initialized = false;
        }
    }
References engine_mutex, engine_ref, initialized, and MayaFlux::Journal::Archivist::shutdown().
Referenced by MayaFlux::End(), and get_or_create_engine().