MayaFlux: MayaFlux::Portal::Forma::Geometry::wire_canvas_drag
wire_canvas_drag()
MAYAFLUX_API void MayaFlux::Portal::Forma::Geometry::wire_canvas_drag (Context & ctx, uint32_t id, std::shared_ptr< MappedState< std::vector< float > > > state, Kinesis::AABB2D bounds)
Wire drag interaction for a drawable canvas element.
Registers a left-button drag callback on ctx that maps NDC cursor position to a sample index and amplitude, writes into state, and increments the version. Linear interpolation fills the range between the previously touched index and the current one, preventing sparse samples under fast drag.
Parameters
ctx Context owning the element.
id Element id from the Mapped.
state MappedState<vector<float>> to write into.
bounds Canvas NDC bounds — must match those passed to drawable_canvas().
Definition at line 334 of file Geometry.cpp.
{
    struct DragState {
        std::optional<size_t> prev_index;
    };
    auto ds = std::make_shared<DragState>();
    ctx.on_drag(id, IO::MouseButtons::Left,
        [state, bounds, ds](uint32_t, glm::vec2 ndc) {
            auto& v = state->value;
            if (v.empty())
                return;
            const float t = (ndc.x - bounds.min.x) / bounds.width();
            const float a = (ndc.y - bounds.min.y) / bounds.height();
            const size_t n = v.size();
            const size_t idx = static_cast<size_t>(
                std::clamp(t, 0.F, 1.F) * static_cast<float>(n - 1));
            const float amp = std::clamp(a, 0.F, 1.F);
            if (ds->prev_index && *ds->prev_index != idx) {
                const size_t lo = std::min(*ds->prev_index, idx);
                const size_t hi = std::max(*ds->prev_index, idx);
                const float v0 = v[*ds->prev_index];
                const auto span = static_cast<float>(hi - lo);
                for (size_t i = lo; i <= hi; ++i) {
                    const float f = span > 0.F
                        ? static_cast<float>(i - lo) / span
                        : 1.F;
                    v[i] = glm::mix(v0, amp, f);
                }
            } else {
                v[idx] = amp;
            }
            ds->prev_index = idx;
            ++state->version;
        });
    ctx.on_release(id, IO::MouseButtons::Left, [ds](uint32_t, glm::vec2) {
        ds->prev_index = std::nullopt;
    });
}
References a, MayaFlux::Kinesis::AABB2D::height(), MayaFlux::IO::Left, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Context::on_drag(), MayaFlux::Portal::Forma::Context::on_release(), and MayaFlux::Kinesis::AABB2D::width().