MayaFlux: MayaFlux::Yantra::extract_outliers
extract_outliers()
std::vector< std::vector< double > > MayaFlux::Yantra::extract_outliers (const std::vector< std::span< const double > > & channels, double std_dev_threshold, uint32_t window_size, uint32_t hop_size)
Definition at line 64 of file ExtractionHelper.cpp.
{
    std::vector<std::vector<double>> result;
    result.reserve(channels.size());
    for (const auto& ch : channels) {
        if (ch.empty()) {
            result.emplace_back();
            continue;
        }
        const uint32_t w = std::min(window_size, static_cast<uint32_t>(ch.size()));
        const uint32_t h = std::max(1U, std::min(hop_size, w / 2));
        const size_t nw = D::num_windows(ch.size(), w, h);
        const auto means = D::mean(ch, nw, h, w);
        if (means.empty()) {
            result.emplace_back();
            continue;
        }
        double gm = 0.0;
        for (double v : means)
            gm += v;
        gm /= static_cast<double>(means.size());
        double var = 0.0;
        for (double v : means)
            var += (v - gm) * (v - gm);
        const double gs = std::sqrt(var / static_cast<double>(means.size()));
        if (gs <= 0.0) {
            result.emplace_back();
            continue;
        }
        std::vector<size_t> starts;
        for (size_t i = 0; i < means.size(); ++i) {
            if (std::abs(means[i] - gm) > std_dev_threshold * gs)
                starts.push_back(i * h);
        }
        result.push_back(D::slice_intervals(ch,
            D::merge_intervals(D::intervals_from_window_starts(starts, w, ch.size()))));
    }
    return result;
}
References h, MayaFlux::Kinesis::Discrete::intervals_from_window_starts(), MayaFlux::Kinesis::Discrete::mean(), MayaFlux::Kinesis::Discrete::merge_intervals(), MayaFlux::Kinesis::Discrete::num_windows(), and MayaFlux::Kinesis::Discrete::slice_intervals().
Referenced by MayaFlux::Yantra::FeatureExtractor< InputType, OutputType >::extract_implementation().