MayaFlux: MayaFlux::create_sampler
create_sampler()
MAYAFLUX_API std::shared_ptr< Kriya::SamplingPipeline > MayaFlux::create_sampler (const std::string & filepath, uint32_t num_samples = 48000 *5, bool truncate = true, uint32_t channel = 0, uint64_t max_dur_ms = 0)
Construct a built SamplingPipeline from an audio file.
Loads the file into a DynamicSoundStream via SoundFileReader::load_bounded, constructs a SamplingPipeline with engine globals (BufferManager, TaskScheduler, buffer size), calls build(), and returns the result.
The returned sampler is ready for play() and play_continuous() calls. Voice slots are allocated on demand via load().
Parameters
filepath Path to the audio file (any FFmpeg-supported format).
num_samples Number of samples to load from the file (default: 48000 * 5).
truncate Truncate stream to num_samples if true (default: true).
channel Output channel index (default: 0).
max_dur_ms Optional maximum duration to build the pipeline for (in milliseconds). Defaults to 0 which is infinite (the pipeline will run until the sampler is destroyed).
Returns
Built SamplingPipeline, or nullptr if the file could not be loaded.
auto kick = MayaFlux::create_sampler("kick.wav");
kick->play(0, kick->slice_from_stream());
auto pad = MayaFlux::create_sampler("pad.wav");
pad->load(0, pad->slice_from_stream()).speed = 0.5;
pad->play_continuous(0);
Definition at line 15 of file Rigs.cpp.
{
    auto stream = get_io_manager()->load_audio_bounded(filepath, num_samples, truncate);
    if (!stream) {
        MF_ERROR(Journal::Component::API, Journal::Context::FileIO,
            "create_sampler: failed to load '{}'", filepath);
        return nullptr;
    }
    auto& mgr = *get_buffer_manager();
    auto& sched = *get_scheduler();
    const uint32_t buf_size = Config::get_buffer_size();
    auto sampler = std::make_shared<Kriya::SamplingPipeline>(
        std::move(stream), mgr, sched, channel, buf_size);
    if (max_dur_ms > 0) {
        sampler->build_for(max_dur_ms);
    } else {
        sampler->build();
    }
    return sampler;
}
References MayaFlux::Journal::API, channel, MayaFlux::Journal::FileIO, get_buffer_manager(), MayaFlux::Config::get_buffer_size(), get_io_manager(), get_scheduler(), and MF_ERROR.
Referenced by MayaFlux::Core::BackendResourceManager::~BackendResourceManager().