MayaFlux: MayaFlux::Yantra::sort_compute_data_inplace
sort_compute_data_inplace()
template<ComputeData T> void MayaFlux::Yantra::sort_compute_data_inplace (IO< T > & data, SortingDirection direction, SortingAlgorithm algorithm)
Universal sort function - handles extraction/conversion internally.
Template Parameters
T ComputeData type
Parameters
data Data to sort (modified in-place)
direction Sort direction
algorithm Sort algorithm
Definition at line 246 of file SortingHelper.hpp.
{
    if constexpr (RequiresContainer<T>) {
        if (!data.has_container()) {
            throw std::runtime_error("Region-like types require container use UniversalSorter instead");
        }
        auto channels = OperationHelper::extract_numeric_data(data.data, data.container.value());
        sort_channels_inplace(channels, direction, algorithm);
        return;
    }
    auto channels = OperationHelper::extract_numeric_data(data.data, data.needs_processig());
    sort_channels_inplace(channels, direction, algorithm);
}
References MayaFlux::Yantra::IO< T >::container, MayaFlux::Yantra::IO< T >::data, MayaFlux::Yantra::OperationHelper::extract_numeric_data(), MayaFlux::Yantra::IO< T >::has_container(), MayaFlux::Yantra::IO< T >::needs_processig(), and sort_channels_inplace().
Referenced by MayaFlux::Yantra::StandardSorter< InputType, OutputType >::sort_data_in_place().