MayaFlux: MayaFlux::bind_viewport_preset
bind_viewport_preset() [1/2]
MAYAFLUX_API void MayaFlux::bind_viewport_preset (const std::shared_ptr< Core::Window > & window, const std::shared_ptr< Buffers::RenderProcessor > & processor, ViewportPresetMode mode = ViewportPresetMode::Fly, const ViewportPresetConfig & config = {}, const std::string & name = "default")
Bind a navigation preset to a window and render processor.
Registers event handlers under the prefix "vp_<name>_". The specific handlers installed depend on mode; see ViewportPresetMode.
Currently only Fly mode is implemented, which does the following: Registers event handlers under the prefix "vp_<name>_": W/S/A/D forward, backward, strafe left, strafe right Q/E move down, move up along world Y RMB drag yaw and pitch (inverted) Scroll dolly along view direction KP1 front view KP3 right view KP7 top view KP9 flip to opposite view
Parameters
window Window supplying input events
processor RenderProcessor that receives the ViewTransform source
mode Navigation controller to install, defaults to Fly preset
config Tuning parameters
name Unique prefix for registered events; must be unique per window
Definition at line 35 of file ViewportPreset.cpp.
{
    if (mode != ViewportPresetMode::Fly) {
        MF_RT_ERROR(Journal::Component::API, Journal::Context::EventDispatch,
            "ViewportPresetMode {} is not yet implemented",
            static_cast<int>(mode));
        return;
    }
    auto& record = s_registry[make_key(window, name)];
    record.saved_config = window->get_input_config();
    record.registered_events.clear();
    auto st = std::make_shared<Kinesis::NavigationState>(
        Kinesis::make_navigation_state(config));
    on_mouse_pressed(window, IO::MouseButtons::Right, [st](double /*x*/, double /*y*/) {
        st->rmb_held    = true;
        st->first_mouse = true; }, event_name(name, "rmb_dn"));
    on_mouse_released(window, IO::MouseButtons::Right, [st](double /*x*/, double /*y*/) { st->rmb_held = false; }, event_name(name, "rmb_up"));
    on_key_pressed(window, IO::Keys::W, [st] { st->forward_held = true; }, event_name(name, "w_dn"));
    on_key_released(window, IO::Keys::W, [st] { st->forward_held = false; }, event_name(name, "w_up"));
    on_key_pressed(window, IO::Keys::S, [st] { st->back_held = true; }, event_name(name, "s_dn"));
    on_key_released(window, IO::Keys::S, [st] { st->back_held = false; }, event_name(name, "s_up"));
    on_key_pressed(window, IO::Keys::A, [st] { st->left_held = true; }, event_name(name, "a_dn"));
    on_key_released(window, IO::Keys::A, [st] { st->left_held = false; }, event_name(name, "a_up"));
    on_key_pressed(window, IO::Keys::D, [st] { st->right_held = true; }, event_name(name, "d_dn"));
    on_key_released(window, IO::Keys::D, [st] { st->right_held = false; }, event_name(name, "d_up"));
    on_key_pressed(window, IO::Keys::Q, [st] { st->down_held = true; }, event_name(name, "q_dn"));
    on_key_released(window, IO::Keys::Q, [st] { st->down_held = false; }, event_name(name, "q_up"));
    on_key_pressed(window, IO::Keys::E, [st] { st->up_held = true; }, event_name(name, "e_dn"));
    on_key_released(window, IO::Keys::E, [st] { st->up_held = false; }, event_name(name, "e_up"));
    on_mouse_move(window, [st](double x, double y) {
        if (!st->rmb_held) {
            st->first_mouse = true;
            return;
        }
        if (st->first_mouse) {
            st->last_x      = x;
            st->last_y      = y;
            st->first_mouse = false;
            return;
        }
        Kinesis::apply_mouse_delta(*st,
            static_cast<float>(x - st->last_x),
            static_cast<float>(y - st->last_y));
        st->last_x = x;
        st->last_y = y; }, event_name(name, "mouse"));
    on_scroll(window, [st](double /*dx*/, double dy) { Kinesis::apply_scroll(*st, static_cast<float>(dy)); }, event_name(name, "scroll"));
    on_key_pressed(window, IO::Keys::KP1, [st] { Kinesis::snap_ortho(*st, 0); }, event_name(name, "kp1"));
    on_key_pressed(window, IO::Keys::KP3, [st] { Kinesis::snap_ortho(*st, 1); }, event_name(name, "kp3"));
    on_key_pressed(window, IO::Keys::KP7, [st] { Kinesis::snap_ortho(*st, 2); }, event_name(name, "kp7"));
    on_key_pressed(window, IO::Keys::KP9, [st] { Kinesis::snap_ortho(*st, 3); }, event_name(name, "kp9"));
    processor->set_view_transform_source(
        [st, window_weak = std::weak_ptr<Core::Window>(window)]() -> Kinesis::ViewTransform {
            auto win = window_weak.lock();
            if (!win) {
                return {};
            }
            const auto& ws = win->get_state();
            const float aspect = (ws.current_height > 0)
                ? static_cast<float>(ws.current_width) / static_cast<float>(ws.current_height)
                : 1.0F;
            return Kinesis::compute_view_transform(*st, aspect);
        });
}
References MayaFlux::IO::A, MayaFlux::Journal::API, MayaFlux::Kinesis::apply_mouse_delta(), MayaFlux::Kinesis::apply_scroll(), MayaFlux::Kinesis::compute_view_transform(), MayaFlux::IO::D, MayaFlux::IO::E, MayaFlux::Journal::EventDispatch, Fly, MayaFlux::IO::KP1, MayaFlux::IO::KP3, MayaFlux::IO::KP7, MayaFlux::IO::KP9, MayaFlux::Kinesis::make_navigation_state(), MF_RT_ERROR, on_key_pressed(), on_key_released(), on_mouse_move(), on_mouse_pressed(), on_mouse_released(), on_scroll(), MayaFlux::IO::Q, MayaFlux::IO::Right, MayaFlux::IO::S, MayaFlux::Kinesis::snap_ortho(), and MayaFlux::IO::W.
Referenced by bind_viewport_preset().