MayaFlux: MayaFlux::Kinesis::generate_quad
generate_quad()
QuadGeometry MayaFlux::Kinesis::generate_quad (glm::vec2 position = glm::vec2(0.0F), glm::vec2 scale = glm::vec2(1.0F), float rotation = 0.0F)
Generate a textured quad centred on the origin.
Parameters
position Translation in XY (z remains 0). Default: no translation.
scale Extents in XY before rotation. Default: {1,1} → NDC-spanning quad.
rotation Rotation angle in radians around Z axis. Default: 0.
Returns
QuadGeometry ready for TRIANGLE_STRIP draw.
UV origin is bottom-left (0,1) to match Vulkan image layout. Base vertices sit at ±scale before rotation and translation are applied.
Definition at line 665 of file GeometryPrimitives.cpp.
{
    const float cos_r = std::cos(rotation);
    const float sin_r = std::sin(rotation);
    QuadGeometry out { .layout = Kakshya::VertexLayout::for_textured_quad() };
    for (size_t i = 0; i < 4; ++i) {
        const float x = k_unit_quad[i].position.x * scale.x;
        const float y = k_unit_quad[i].position.y * scale.y;
        out.vertices[i].position = {
            x * cos_r - y * sin_r + position.x,
            x * sin_r + y * cos_r + position.y,
            0.0F,
        };
        out.vertices[i].texcoord = k_unit_quad[i].texcoord;
    }
    return out;
}
References generate_quad(), MayaFlux::Kinesis::QuadGeometry::layout, position, and scale().
Referenced by MayaFlux::Buffers::TextureBuffer::generate_default_quad(), MayaFlux::Buffers::NodeTextureBuffer::generate_fullscreen_quad(), generate_quad(), and MayaFlux::Buffers::TextureBuffer::generate_quad_with_transform().