MayaFlux: MayaFlux::mean
mean() [2/2]
MAYAFLUX_API double MayaFlux::mean (const std::vector< double > & data)
Calculate mean of single-channel data.
Parameters
data Input data
Returns
Mean value
Definition at line 39 of file Yantra.cpp.
{
    auto analyzer = std::make_shared<Yantra::StatisticalAnalyzer<>>();
    analyzer->set_method(Yantra::StatisticalMethod::MEAN);
    auto result = analyzer->analyze_statistics({ Kakshya::DataVariant(data) });
    return result.channel_statistics[0].mean_stat;
}
References MayaFlux::Yantra::MEAN.
Referenced by MayaFlux::Yantra::compute_cv_statistic(), MayaFlux::Yantra::compute_kurtosis_statistic(), MayaFlux::Yantra::compute_skewness_statistic(), MayaFlux::Yantra::compute_variance_statistic(), MayaFlux::Yantra::compute_zscore_statistic(), MayaFlux::Yantra::EnergyAnalyzer< InputType, OutputType >::create_analysis_result(), and mean_combined().