MayaFlux: MayaFlux::Kinesis::Discrete::intervals_from_window_starts
intervals_from_window_starts()
std::vector< std::pair< size_t, size_t > > MayaFlux::Kinesis::Discrete::intervals_from_window_starts (const std::vector< size_t > & window_starts, uint32_t window_size, size_t data_size)
Build [start, end) intervals from window start indices.
Parameters
window_starts Starting sample indices of qualifying windows
window_size Samples per window
data_size Total span length for clamping
Returns
One [start, end) pair per window start
Definition at line 68 of file Extract.cpp.
{
    std::vector<std::pair<size_t, size_t>> out;
    out.reserve(window_starts.size());
    for (size_t s : window_starts) {
        const size_t e = std::min(s + static_cast<size_t>(window_size), data_size);
        if (s < e)
            out.emplace_back(s, e);
    }
    return out;
}
Referenced by MayaFlux::Yantra::extract_above_mean(), MayaFlux::Yantra::extract_high_energy(), MayaFlux::Yantra::extract_high_spectral(), MayaFlux::Yantra::extract_outliers(), and MayaFlux::Yantra::extract_silence().