MayaFlux: MayaFlux::Config::set_node_config
set_node_config()
MAYAFLUX_API void MayaFlux::Config::set_node_config (const Nodes::NodeConfig & config)
Sets the node configuration for the default engine.
Parameters
config The NodeConfig to set
Definition at line 47 of file Config.cpp.
{
    if (!is_initialized()) {
        MF_WARN(Journal::Component::API, Journal::Context::Configuration, "Engine is not running. Setting node config on context directly.");
    }
    get_context().set_node_config(config);
}
References MayaFlux::Journal::API, MayaFlux::Journal::Configuration, MayaFlux::get_context(), MayaFlux::is_initialized(), MF_WARN, and MayaFlux::Core::Engine::set_node_config().