MayaFlux: MayaFlux::Yantra::Granular::process
process() [2/2]
MAYAFLUX_API GranularDatum MayaFlux::Yantra::Granular::process (const std::shared_ptr< Kakshya::SignalSourceContainer > & container, uint32_t grain_size, uint32_t hop_size, const std::string & feature_key, AttributeExecutor executor, uint32_t channel = 0, bool ascending = true, uint32_t gpu_sort_threshold = 0)
Zero-config entry point for the full granular pipeline using a span-level lambda.
Parameters
container Source signal data.
grain_size Samples per grain.
hop_size Hop size between grain onsets.
feature_key Attribute name written onto each grain Region.
executor Lambda receiving grain samples and context, returning a scalar.
channel Source channel index.
ascending Sort direction.
gpu_sort_threshold Grain count at which SortOp switches to GPU path. 0 = CPU only.
Returns
GranularDatum containing the attributed, sorted RegionGroup.
Definition at line 671 of file GranularWorkflow.cpp.
{
    auto matrix = make_granular_matrix();
    auto ctx = make_granular_context(
        grain_size, hop_size, feature_key,
        std::move(executor),
        channel, ascending, gpu_sort_threshold);
    return matrix->with(make_granular_input(container))
        .then<SegmentOp>("segment")
        .then<AttributeOp>("attribute")
        .then<SortOp>("sort")
        .to_io();
}
References make_granular_context(), make_granular_input(), and make_granular_matrix().