MayaFlux: MayaFlux::Yantra::compute_skewness_statistic
compute_skewness_statistic()
std::vector< double > MayaFlux::Yantra::compute_skewness_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute skewness statistic using zero-copy processing.
This function computes the skewness (third moment) for a given data span. It measures the asymmetry of the distribution in each window.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
Returns
Vector of skewness values
Definition at line 408 of file AnalysisHelper.cpp.
{
    std::vector<double> skewness_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.size() < 2) {
                skewness_values[i] = 0.0;
                return;
            }
            double sum = 0.0;
            for (double sample : window) {
                sum += sample;
            }
            double mean = sum / static_cast<double>(window.size());
            double sum_sq_diff = 0.0;
            double sum_cube_diff = 0.0;
            for (double sample : window) {
                double diff = sample - mean;
                double sq_diff = diff * diff;
                sum_sq_diff += sq_diff;
                sum_cube_diff += sq_diff * diff;
            }
            double variance = sum_sq_diff / static_cast<double>(window.size());
            if (variance <= 0.0) {
                skewness_values[i] = 0.0;
                return;
            }
            double std_dev = std::sqrt(variance);
            double third_moment = sum_cube_diff / static_cast<double>(window.size());
            skewness_values[i] = third_moment / (std_dev * std_dev * std_dev);
        });
    return skewness_values;
}
References compute_skewness_statistic(), MayaFlux::mean(), and MayaFlux::std_dev().
Referenced by compute_skewness_statistic(), MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::create_analysis_result().