MayaFlux: MayaFlux::Kinesis::ray_cast
ray_cast()
std::optional< HitResult > MayaFlux::Kinesis::ray_cast (const SpatialIndex3D & index, const Ray & ray, float tolerance) inline
Find the closest entity to a ray within a tolerance radius.
Parameters
index Published SpatialIndex3D to query.
ray World-space ray (from screen_to_ray or constructed manually).
tolerance Maximum perpendicular distance from the ray axis for a hit.
Returns
Closest entity within tolerance, or std::nullopt if nothing was hit.
Iterates all entities in the published snapshot. Entities behind the ray origin (t < 0) are rejected. Among forward candidates within tolerance, returns the one with the smallest perpendicular distance. Ties broken by smaller t (closer to camera).
Definition at line 115 of file HitTest.hpp.
{
    float tol_sq = tolerance * tolerance;
    std::optional<HitResult> best;
    for (const auto& [id, pos] : index.all()) {
        float t = 0.0F;
        float d_sq = point_ray_distance_sq(ray, pos, &t);
        if (t < 0.0F || d_sq > tol_sq) {
            continue;
        }
        float d = std::sqrt(d_sq);
        if (!best || d < best->distance || (d == best->distance && t < best->t)) {
            best = HitResult { .id = id, .distance = d, .t = t };
        }
    }
    return best;
}
References MayaFlux::Kinesis::SpatialIndex< PointT >::all(), distance(), MayaFlux::Kinesis::HitResult::id, id, and point_ray_distance_sq().