MayaFlux: MayaFlux::get_random_engine
get_random_engine()
MAYAFLUX_API Kinesis::Stochastic::Stochastic & MayaFlux::get_random_engine ()
Get reference to the default random engine.
Returns
Reference to the Stochastic engine instance
Provides access to the default random engine for advanced usage and configuration.
Definition at line 9 of file API/Random.cpp.
{
    return *get_context().get_stochastic_engine();
}
References get_context(), and MayaFlux::Core::Engine::get_stochastic_engine().
Referenced by get_brownian_motion(), get_exponential_random(), get_gaussian_random(), get_poisson_random(), and get_uniform_random().