MayaFlux: MayaFlux::get_context
get_context()
MAYAFLUX_API Core::Engine & MayaFlux::get_context ()
Gets the default engine instance.
Returns
Reference to the default Engine
Creates the engine if it doesn't exist yet. This is the centrally managed engine instance that all convenience functions in this namespace operate on.
Definition at line 68 of file Core.cpp.
{
    return internal::get_or_create_engine();
}
References MayaFlux::internal::get_or_create_engine().
Referenced by Await(), create_buffer_pipeline(), get_audio_channel_root(), get_buffer_manager(), MayaFlux::Config::get_buffer_size(), get_event_manager(), MayaFlux::Config::get_global_graphics_config(), MayaFlux::Config::get_global_input_config(), MayaFlux::Config::get_global_network_config(), MayaFlux::Config::get_global_stream_info(), get_input_manager(), get_input_subsystem(), get_io_manager(), MayaFlux::Config::get_node_config(), get_node_graph_manager(), MayaFlux::Config::get_num_out_channels(), get_random_engine(), MayaFlux::Config::get_sample_rate(), get_scheduler(), get_window_manager(), is_configured(), Pause(), register_node(), register_node_network(), Resume(), samples_to_blocks(), samples_to_seconds(), seconds_to_blocks(), seconds_to_samples(), MayaFlux::Config::set_node_config(), Start(), and unregister_node_network().