MayaFlux: MayaFlux::Yantra::transform_normalize
transform_normalize() [2/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_normalize (DataType & input, const std::pair< double, double > & target_range = { -1.0, 1.0 })
Normalize transformation using existing infrastructure (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
target_range Target range [min, max]
Returns
Normalized data
Definition at line 536 of file MathematicalHelper.hpp.
                                                                                            { -1.0, 1.0 })
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    for (auto& span : target_data) {
        auto [min_it, max_it] = std::ranges::minmax_element(span);
        double current_min = *min_it;
        double current_max = *max_it;
        if (current_max == current_min)
            return input;
        double current_range = current_max - current_min;
        double target_min = target_range.first;
        double target_max = target_range.second;
        double target_span = target_max - target_min;
        std::ranges::transform(span, span.begin(),
            [current_min, current_range, target_span, target_min](double x) {
                return ((x - current_min) / current_range) * target_span + target_min;
            });
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References transform_normalize().
Referenced by MayaFlux::Yantra::MathematicalTransformer< InputType, OutputType >::transform_implementation(), transform_normalize(), and transform_normalize().