MayaFlux: MayaFlux::Yantra::fft_convolve_helper
fft_convolve_helper()
template<typename OperationFunc > std::vector< double > MayaFlux::Yantra::fft_convolve_helper (std::span< const double > data_span, std::span< const double > kernel, OperationFunc && operation, bool return_full_size = true)
Common FFT convolution helper to eliminate code duplication.
Parameters
data_span Input data
kernel Convolution kernel
operation Function to apply in frequency domain
Returns
Convolved result
Definition at line 17 of file ConvolutionHelper.hpp.
{
    if (data_span.empty() || kernel.empty()) {
        if (return_full_size && !data_span.empty() && !kernel.empty()) {
            return std::vector<double>(data_span.size() + kernel.size() - 1, 0.0);
        } else {
            return std::vector<double>(data_span.size(), 0.0);
        }
    }
    size_t conv_size = data_span.size() + kernel.size() - 1;
    size_t fft_size = std::max(256UZ, conv_size);
    fft_size = 1 << (32 - std::countl_zero(fft_size - 1));
    Eigen::VectorXd padded_input = Eigen::VectorXd::Zero(fft_size);
    Eigen::VectorXd padded_kernel = Eigen::VectorXd::Zero(fft_size);
    std::ranges::copy(data_span, padded_input.begin());
    std::ranges::copy(kernel, padded_kernel.begin());
    Eigen::FFT<double> fft;
    Eigen::VectorXcd input_fft, kernel_fft;
    fft.fwd(input_fft, padded_input);
    fft.fwd(kernel_fft, padded_kernel);
    Eigen::VectorXcd result_fft(fft_size);
    operation(input_fft, kernel_fft, result_fft);
    double scale_factor = 1.0 / fft_size;
    std::ranges::transform(result_fft, result_fft.begin(),
        [scale_factor](std::complex<double>& c) {
            return c * scale_factor;
        });
    Eigen::VectorXd time_result;
    fft.inv(time_result, result_fft);
    if (return_full_size) {
        std::vector<double> result(conv_size);
        std::ranges::copy(time_result | std::views::take(conv_size), result.begin());
        return result;
    } else {
        std::vector<double> result(data_span.size());
        std::ranges::copy(time_result | std::views::take(data_span.size()), result.begin());
        return result;
    }
}
Referenced by transform_auto_correlate_fft(), transform_auto_correlate_fft(), transform_convolve(), transform_convolve(), transform_cross_correlate(), and transform_cross_correlate().