MayaFlux: MayaFlux::on_key_released
on_key_released()
MAYAFLUX_API void MayaFlux::on_key_released (const std::shared_ptr< Core::Window > & window, IO::Keys key, std::function< void()> callback, std::string name = "")
Schedule a key release handler.
Parameters
window Window to listen to
key Key to wait for
callback Function to call on key release
name Optional name for the event handler
Example:
MayaFlux::on_key_released(window, MayaFlux::IO::Keys::Enter, []() {
    // Handle Enter key release
}, "enter_release_handler");
Definition at line 142 of file Chronie.cpp.
{
    auto event_manager = get_event_manager();
    if (name.empty()) {
        name = "key_release_" + std::to_string(event_manager->get_next_event_id());
    }
    auto event = std::make_shared<Vruta::Event>(
        Kriya::key_released(window, key, std::move(callback)));
    event_manager->add_event(event, name);
}
References get_event_manager(), and MayaFlux::Kriya::key_released().
Referenced by bind_viewport_preset().