MayaFlux: MayaFlux::Yantra::compute_min_statistic
compute_min_statistic()
std::vector< double > MayaFlux::Yantra::compute_min_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size)
Compute min statistic using zero-copy processing.
Definition at line 645 of file AnalysisHelper.cpp.
{
    std::vector<double> min_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            min_values[i] = *std::ranges::min_element(window);
        });
    return min_values;
}
References compute_min_statistic().
Referenced by compute_min_statistic(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values().