MayaFlux: MayaFlux::Journal::error_rethrow
error_rethrow() [2/2]
void MayaFlux::Journal::error_rethrow (Component component, Context context, std::source_location location = std::source_location::current(), std::string_view additional_context = "") inline
Catch and log an exception, then rethrow it.
This function is intended to be called within a catch block.
Parameters
Component The component generating the log message.
Context The execution context of the log message.
location The source location (file, line, function) of the log call.
additional_context Optional additional context to prepend to the exception message.
Definition at line 377 of file Archivist.hpp.
{
    auto ep = std::current_exception();
    if (!ep) {
        Archivist::instance().scribe(Severity::ERROR, component, context,
            "error_rethrow called outside of a catch", location);
        Archivist::instance().flush();
        std::terminate();
    }
    try {
        std::rethrow_exception(ep);
    } catch (const std::exception& e) {
        std::string msg = std::string(e.what());
        if (!additional_context.empty()) {
            msg = std::string(additional_context) + ": " + msg;
        }
        Archivist::instance().scribe(Severity::ERROR, component, context, msg, location);
        Archivist::instance().flush();
        std::rethrow_exception(ep);
    } catch (...) {
        std::string msg = "Unknown exception";
        if (!additional_context.empty()) {
            msg = std::string(additional_context) + ": " + msg;
        }
        Archivist::instance().scribe(Severity::ERROR, component, context, msg, location);
        Archivist::instance().flush();
        std::rethrow_exception(ep);
    }
}
References ERROR, MayaFlux::Journal::Archivist::flush(), MayaFlux::Journal::Archivist::instance(), and MayaFlux::Journal::Archivist::scribe().
Referenced by error_rethrow().