MayaFlux: MayaFlux::Portal::Forma::make_value_row
make_value_row()
ValueRow MayaFlux::Portal::Forma::make_value_row (const ValueSpec & spec, RowBuffer row_buf, Surface & surface, LayoutCursor & cursor, float x_min, float x_max, float row_h, glm::vec3 bg = glm::vec3(0.15F))
Construct one labeled value row, advance the cursor, and return it.
The returned row's link reads spec.reader each tick, represses "label: value" into the text image, and binds the image to the row's FormaBuffer. The buffer and text image are pre-created by the caller and travel together as row_buf.
Parameters
spec Label and reader for the row.
row_buf Pre-created buffer and bound text image.
surface Surface to register the row on.
cursor Layout cursor. Advanced by row_h on return.
x_min Left edge in NDC.
x_max Right edge in NDC.
row_h Row height in NDC units.
bg Background color for the row quad.
Definition at line 76 of file QueryUtils.cpp.
{
    const float top = cursor.y();
    const float bot = top - row_h;
    cursor.advance(row_h);
    const uint32_t stride = Kakshya::VertexLayout::for_meshes().stride_bytes;
    std::vector<uint8_t> bytes(static_cast<size_t>(12) * stride, 0);
    write_row_quad(bytes, x_min, x_max, bot, top, bg);
    row_buf.buf->submit(bytes);
    auto staging = Buffers::create_image_staging_buffer(
        row_buf.text_image->get_size_bytes());
    Portal::Text::PressParams params {
        .color = { 1.F, 1.F, 1.F, 1.F },
    };
    Element el;
    el.buffer = row_buf.buf;
    el.bounds_hint = Kinesis::AABB2D { .min = { x_min, bot }, .max = { x_max, top } };
    el.interactive = false;
    el.name = spec.label;
    const uint32_t id = surface.layer().add(el);
    Link link(
        [] { },
        [reader = spec.reader,
            label = spec.label,
            text_image = row_buf.text_image,
            buf = row_buf.buf,
            staging,
            params]() mutable {
            if (!buf || !reader)
                return;
            Portal::Text::repress(text_image,
                label + ": " + reader(),
                params, staging);
            buf->bind_texture(0, text_image);
        });
    return ValueRow {
        .element_id = id,
        .buf = std::move(row_buf.buf),
        .text = std::move(row_buf.text_image),
        .link = std::move(link),
    };
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::LayoutCursor::advance(), MayaFlux::Portal::Forma::Element::bounds_hint, MayaFlux::Portal::Forma::RowBuffer::buf, MayaFlux::Portal::Forma::Element::buffer, MayaFlux::Portal::Text::PressParams::color, MayaFlux::Buffers::create_image_staging_buffer(), MayaFlux::Portal::Forma::ValueRow::element_id, MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Portal::Forma::Element::interactive, MayaFlux::Portal::Forma::ValueSpec::label, MayaFlux::Portal::Forma::Surface::layer(), MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Element::name, MayaFlux::Portal::Forma::ValueSpec::reader, MayaFlux::Portal::Text::repress(), MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Portal::Forma::RowBuffer::text_image, and MayaFlux::Portal::Forma::LayoutCursor::y().
Referenced by make_value_group().