MayaFlux: MayaFlux::Portal::Forma::Plot::plot_cursor
plot_cursor()
MAYAFLUX_API GeometryFn< float > MayaFlux::Portal::Forma::Plot::plot_cursor (Kinesis::AABB2D bounds, bool vertical = true, glm::vec3 color = glm::vec3(0.75F), float thickness = 1.F)
GeometryFn<float> for a cursor or playhead line within a plot area.
Value in [0, 1] maps to a position within bounds. When vertical is true the line is vertical and the value maps to the X axis; when false the line is horizontal and the value maps to the Y axis.
Note
Pass PrimitiveTopology::LINE_LIST explicitly to create_element.
Parameters
bounds Plot area in NDC. The line spans the full perpendicular extent.
vertical True for a vertical playhead (X position), false for horizontal.
color Line color.
thickness LineVertex::thickness value.
Definition at line 182 of file PlotSpec.cpp.
{
    return [bounds, vertical, color, thickness](
               float v, std::vector<uint8_t>& out, Element& el) {
        const float t = std::clamp(v, 0.F, 1.F);
        using V = Kakshya::LineVertex;
        std::array<V, 2> verts;
        if (vertical) {
            const float x = bounds.min.x + t * bounds.width();
            verts = { {
                { .position = { x, bounds.min.y, 0.F }, .color = color, .thickness = thickness },
                { .position = { x, bounds.max.y, 0.F }, .color = color, .thickness = thickness },
            } };
            el.bounds_hint = Kinesis::AABB2D {
                .min = { x - 0.01F, bounds.min.y },
                .max = { x + 0.01F, bounds.max.y },
            };
        } else {
            const float y = bounds.min.y + t * bounds.height();
            verts = { {
                { .position = { bounds.min.x, y, 0.F }, .color = color, .thickness = thickness },
                { .position = { bounds.max.x, y, 0.F }, .color = color, .thickness = thickness },
            } };
            el.bounds_hint = Kinesis::AABB2D {
                .min = { bounds.min.x, y - 0.01F },
                .max = { bounds.max.x, y + 0.01F },
            };
        }
        Geometry::write_verts(out, verts);
    };
}
References MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kinesis::AABB2D::width(), and MayaFlux::Portal::Forma::Geometry::write_verts().