MayaFlux: MayaFlux::Yantra::bindings_from_spec
bindings_from_spec()
std::vector< GpuBufferBinding > MayaFlux::Yantra::bindings_from_spec (const Portal::Graphics::ShaderSpec & spec) inline
Derive a GpuBufferBinding list from a ShaderSpec.
Translates ShaderSpec binding declarations to the GpuBufferBinding vocabulary understood by GpuResourceManager and any GpuExecutionContext subclass. The result is suitable for passing to declare_buffer_bindings() overrides or directly to GpuResourceManager::initialise().
Definition at line 49 of file ShaderSpecBinding.hpp.
{
    std::vector<GpuBufferBinding> out;
    out.reserve(spec.bindings.size());
    for (const auto& b : spec.bindings) {
        out.push_back({
            .set = 0,
            .binding = b.binding_index,
            .direction = to_binding_direction(b.direction),
            .element_type = to_element_type(b.modality),
        });
    }
    return out;
}
References b, MayaFlux::Portal::Graphics::ShaderSpec::bindings, to_binding_direction(), and to_element_type().
Referenced by MayaFlux::Yantra::ComputationGrammar::RuleBuilder::executes().