MayaFlux: MayaFlux::Kinesis::interpolate_nddata
interpolate_nddata()
Kakshya::DataVariant MayaFlux::Kinesis::interpolate_nddata (const Kakshya::DataVariant & control_points, Eigen::Index num_samples, InterpolationMode mode, double tension = 0.5)
Process DataVariant through interpolation.
Parameters
control_points Input data as control points
num_samples Number of output samples
mode Interpolation mode
tension Tension parameter
Returns
Interpolated data
Definition at line 458 of file MotionCurves.cpp.
{
    Eigen::MatrixXd control_matrix = Kakshya::to_eigen_matrix(control_points);
    Eigen::MatrixXd interpolated = generate_interpolated_points(
        control_matrix, num_samples, mode, tension);
    Kakshya::EigenAccess input_access(control_points);
    if (input_access.is_complex()) {
        return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::COMPLEX);
    }
    if (input_access.is_structured()) {
        switch (input_access.component_count()) {
        case 2:
            return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::VEC2);
        case 3:
            return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::VEC3);
        case 4:
            return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::VEC4);
        default:
            return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::SCALAR);
        }
    } else {
        return Kakshya::from_eigen_matrix(interpolated, Kakshya::MatrixInterpretation::SCALAR);
    }
}
References MayaFlux::Kakshya::COMPLEX, MayaFlux::Kakshya::EigenAccess::component_count(), MayaFlux::Kakshya::from_eigen_matrix(), generate_interpolated_points(), MayaFlux::Kakshya::EigenAccess::is_complex(), MayaFlux::Kakshya::EigenAccess::is_structured(), MayaFlux::Kakshya::SCALAR, MayaFlux::Kakshya::to_eigen_matrix(), MayaFlux::Kakshya::VEC2, MayaFlux::Kakshya::VEC3, and MayaFlux::Kakshya::VEC4.