MayaFlux: MayaFlux::get_input_subsystem
get_input_subsystem()
MAYAFLUX_API const Core::InputSubsystem & MayaFlux::get_input_subsystem ()
Gets the input subsystem.
Returns
InputSubsystem for input device management
The InputSubsystem handles initialization and management of input devices. Access through Engine ensures proper lifecycle coordination.
Definition at line 10 of file Input.cpp.
{
    auto subsystem = get_context().get_subsystem(Core::SubsystemType::INPUT);
    return *std::dynamic_pointer_cast<Core::InputSubsystem>(subsystem);
}
References get_context(), MayaFlux::Core::Engine::get_subsystem(), and MayaFlux::Core::INPUT.
Referenced by find_hid_device(), get_all_input_devices(), get_hid_devices(), and get_midi_devices().