MayaFlux: MayaFlux::on_network_message_matching
on_network_message_matching() [2/2]
MAYAFLUX_API void MayaFlux::on_network_message_matching (std::shared_ptr< Vruta::NetworkSource > source, std::function< bool(const Core::NetworkMessage &)> predicate, std::function< void(const Core::NetworkMessage &)> callback, std::string name = "")
Schedule an on_message_matching handler with an existing NetworkSource.
Parameters
source Shared NetworkSource
predicate Filter; only matching messages invoke callback
callback Invoked with each matching message
name Optional name for the event handler
Definition at line 330 of file Chronie.cpp.
{
    auto event_manager = get_event_manager();
    if (name.empty()) {
        name = "net_msg_match_" + std::to_string(event_manager->get_next_event_id());
    }
    event_manager->add_event(
        std::make_shared<Vruta::Event>(
            Kriya::on_message_matching(std::move(source), std::move(predicate), std::move(callback))),
        name);
}
References get_event_manager(), and MayaFlux::Kriya::on_message_matching().
Referenced by on_network_message_matching().