MayaFlux: MayaFlux::Yantra::infer_from_region_group
infer_from_region_group()
std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_from_region_group (const Kakshya::RegionGroup & group, const std::shared_ptr< Kakshya::SignalSourceContainer > & container)
Infer structure from RegionGroup.
Definition at line 109 of file StructureIntrospection.cpp.
{
    if (!container || group.regions.empty()) {
        return { { { Kakshya::DataDimension::time(0) } }, Kakshya::DataModality::UNKNOWN };
    }
    auto structure = container->get_structure();
    auto bounds_info = Kakshya::extract_group_bounds_info(group);
    if (bounds_info.contains("bounding_min") && bounds_info.contains("bounding_max")) {
        auto min_coords = safe_any_cast_or_throw<std::vector<uint64_t>>(bounds_info["bounding_min"]);
        auto max_coords = safe_any_cast_or_throw<std::vector<uint64_t>>(bounds_info["bounding_max"]);
        std::vector<uint64_t> shape;
        int size = static_cast<int>(max_coords[0] - min_coords[0]);
        shape.push_back(std::abs(size) + 1);
        shape.push_back(max_coords[1]);
        Kakshya::DataModality modality = structure.modality;
        if (group.attributes.contains("modality")) {
            auto modality_result = safe_any_cast<Kakshya::DataModality>(group.attributes.at("modality"));
            if (modality_result)
                modality = *modality_result.value;
        }
        auto dimensions = Kakshya::DataDimension::create_dimensions(modality, shape, structure.memory_layout);
        return { dimensions, modality };
    }
    return infer_from_region(group.regions[0], container);
}
References MayaFlux::Kakshya::RegionGroup::attributes, MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Kakshya::extract_group_bounds_info(), infer_from_region(), MayaFlux::Kakshya::RegionGroup::regions, size, MayaFlux::Kakshya::DataDimension::time(), and MayaFlux::Kakshya::UNKNOWN.
Referenced by infer_structure().