MayaFlux: MayaFlux::Yantra::compute_cv_statistic
compute_cv_statistic()
std::vector< double > MayaFlux::Yantra::compute_cv_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size, bool sample_variance)
Compute CV (Coefficient of Variation) statistic using zero-copy processing.
Definition at line 787 of file AnalysisHelper.cpp.
{
    auto mean_vals = compute_mean_statistic(data, num_windows, hop_size, window_size);
    auto std_vals = compute_std_dev_statistic(data, num_windows, hop_size, window_size, sample_variance);
    std::vector<double> cv_values(num_windows);
    std::transform(std::execution::par_unseq, mean_vals.begin(), mean_vals.end(), std_vals.begin(), cv_values.begin(),
        [](double mean, double std_dev) {
            return (std::abs(mean) > 1e-15) ? std_dev / mean : 0.0;
        });
    return cv_values;
}
References compute_cv_statistic(), compute_mean_statistic(), compute_std_dev_statistic(), MayaFlux::mean(), and MayaFlux::std_dev().
Referenced by compute_cv_statistic(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values().