MayaFlux: MayaFlux::Yantra::compute_variance_statistic
compute_variance_statistic()
std::vector< double > MayaFlux::Yantra::compute_variance_statistic (std::span< const double > data, const size_t num_windows, const uint32_t hop_size, const uint32_t window_size, bool sample_variance = true)
Compute variance statistic using zero-copy processing.
This function computes the variance for a given data span. It calculates the sample or population variance in each window.
Parameters
data Input data span
num_windows Number of windows to process
hop_size Hop size for windowing
window_size Size of each window
sample_variance If true, use sample variance (N-1), else population (N)
Returns
Vector of variance values
Definition at line 359 of file AnalysisHelper.cpp.
{
    std::vector<double> variance_values(num_windows);
    std::vector<size_t> indices(num_windows);
    std::iota(indices.begin(), indices.end(), 0);
    std::for_each(std::execution::par_unseq, indices.begin(), indices.end(),
        [&](size_t i) {
            const size_t start_idx = i * hop_size;
            const size_t end_idx = std::min(start_idx + window_size, data.size());
            auto window = data.subspan(start_idx, end_idx - start_idx);
            if (window.size() <= 1) {
                variance_values[i] = 0.0;
                return;
            }
            double sum = 0.0;
            for (double sample : window) {
                sum += sample;
            }
            double mean = sum / static_cast<double>(window.size());
            double sum_sq_diff = 0.0;
            for (double sample : window) {
                double diff = sample - mean;
                sum_sq_diff += diff * diff;
            }
            double divisor = sample_variance ? static_cast<double>(window.size() - 1) : static_cast<double>(window.size());
            variance_values[i] = sum_sq_diff / divisor;
        });
    return variance_values;
}
References compute_variance_statistic(), and MayaFlux::mean().
Referenced by MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::compute_statistical_values(), compute_std_dev_statistic(), compute_variance_statistic(), and MayaFlux::Yantra::StatisticalAnalyzer< InputType, OutputType >::create_analysis_result().