MayaFlux: MayaFlux::Nodes::get_active_channels
get_active_channels() [1/2]
std::vector< uint32_t > MayaFlux::Nodes::get_active_channels (const std::shared_ptr< Nodes::Node > & node, uint32_t fallback_channel = 0)
Extracts active channel list from a node's channel mask.
Parameters
node Node to inspect (can be null)
fallback_channel Channel to use if node has no active channels (default: 0)
Returns
Vector of active channel indices
Definition at line 140 of file NodeUtils.cpp.
{
    uint32_t channel_mask = node ? node->get_channel_mask().load() : 0;
    return get_active_channels(channel_mask, fallback_channel);
}
References get_active_channels().
Referenced by get_active_channels(), MayaFlux::Nodes::ChainNode::initialize(), and MayaFlux::Nodes::BinaryOpNode::initialize().