MayaFlux: MayaFlux::Kinesis::Discrete::span_sort_indices
span_sort_indices()
std::vector< size_t > MayaFlux::Kinesis::Discrete::span_sort_indices (std::span< double > data, SortingDirection direction)
Indices that would sort a span in the given direction.
Parameters
data Source span (not modified)
direction Sort direction
Returns
Sorted indices into data
Definition at line 35 of file Sort.cpp.
{
    std::vector<size_t> idx(data.size());
    std::iota(idx.begin(), idx.end(), 0);
    if (data.empty())
        return idx;
    const auto comp = double_comparator(direction);
    std::ranges::sort(idx, [&](size_t a, size_t b) { return comp(data[a], data[b]); });
    return idx;
}
References a, b, and double_comparator().
Referenced by channels_sort_indices(), and MayaFlux::Yantra::generate_compute_data_indices().