MayaFlux: MayaFlux::Kinesis::Discrete::num_windows
num_windows()
size_t MayaFlux::Kinesis::Discrete::num_windows (size_t data_size, uint32_t window_size, uint32_t hop_size) inline noexcept
Compute the number of analysis windows for a given data size.
Parameters
data_size Number of samples
window_size Samples per window
hop_size Samples between window starts
Returns
Number of complete windows, 0 if data_size < window_size
Definition at line 39 of file Analysis.hpp.
{
    if (data_size < window_size)
        return 0;
    return (data_size - window_size) / hop_size + 1;
}
Referenced by MayaFlux::Yantra::extract_above_mean(), MayaFlux::Yantra::extract_high_energy(), MayaFlux::Yantra::extract_high_spectral(), MayaFlux::Yantra::extract_outliers(), MayaFlux::Yantra::extract_silence(), and onset_positions().