MayaFlux: MayaFlux::Portal::Forma::Geometry::crosshair
crosshair()
MAYAFLUX_API GeometryFn< glm::vec2 > MayaFlux::Portal::Forma::Geometry::crosshair (float arm_len = 0.04F, glm::vec3 color = glm::vec3(0.9F), float thickness = 1.F, float hit_radius = 0.05F)
Geometry function for a crosshair indicator in NDC space.
Parameters
arm_len Half-length of each arm in NDC units.
color Line color.
thickness Line thickness (maps to LineVertex::thickness).
hit_radius Hit region radius in NDC units.
Note
Pass PrimitiveTopology::LINE_LIST explicitly to create_element — the default TRIANGLE_STRIP will misinterpret the 4 vertices.
Definition at line 266 of file Geometry.cpp.
{
    return [arm_len, color, thickness, hit_radius](
               glm::vec2 pos, std::vector<uint8_t>& out, Element& el) {
        using V = Kakshya::LineVertex;
        const std::array<V, 4> verts { {
            { .position = { pos.x - arm_len, pos.y, 0.F }, .color = color, .thickness = thickness },
            { .position = { pos.x + arm_len, pos.y, 0.F }, .color = color, .thickness = thickness },
            { .position = { pos.x, pos.y - arm_len, 0.F }, .color = color, .thickness = thickness },
            { .position = { pos.x, pos.y + arm_len, 0.F }, .color = color, .thickness = thickness },
        } };
        write_verts(out, verts);
        el.bounds_hint = Kinesis::AABB2D::from_ndc(pos, glm::vec2(arm_len));
        el.contains = Kinesis::circular_bounds(pos, hit_radius);
    };
}
References MayaFlux::Kinesis::circular_bounds(), MayaFlux::Kinesis::AABB2D::from_ndc(), MayaFlux::Kakshya::LineVertex::position, and write_verts().