MayaFlux: MayaFlux::get_event_manager
get_event_manager()
MAYAFLUX_API std::shared_ptr< Vruta::EventManager > MayaFlux::get_event_manager ()
Gets the event manager from the default engine.
Returns
Shared pointer to the centrally managed EventManager
Returns the event manager that's managed by the default engine instance. Used for handling windowing and input events.
Definition at line 25 of file Chronie.cpp.
{
    return get_context().get_event_manager();
}
References get_context(), and MayaFlux::Core::Engine::get_event_manager().
Referenced by cancel_event_handler(), on_any_key(), on_key_pressed(), on_key_released(), on_mouse_move(), on_mouse_pressed(), on_mouse_released(), and on_scroll().