MayaFlux: MayaFlux::Nodes::atomic_remove_flag
atomic_remove_flag()
void MayaFlux::Nodes::atomic_remove_flag (std::atomic< NodeState > & state, NodeState flags)
Atomically removes a flag from a node state.
Parameters
state The atomic node state to modify
flags The flags to remove from the state
Removes specific state flags from a node's state. This is commonly used to clear processing markers after a node has been processed, or to remove special states like PENDING_REMOVAL when they're no longer applicable.
Definition at line 105 of file NodeUtils.cpp.
{
    auto current = state.load();
    NodeState desired;
    do {
        desired = static_cast<NodeState>(current & ~flag);
    } while (!state.compare_exchange_weak(current, desired,
        std::memory_order_acq_rel,
        std::memory_order_acquire));
}
Referenced by MayaFlux::Nodes::Generator::Generator::enable_mock_process(), MayaFlux::Nodes::Generator::Sine::process_sample(), MayaFlux::Nodes::RootNode::register_node(), MayaFlux::Nodes::ChainNode::reset_processed_state(), MayaFlux::Nodes::BinaryOpNode::reset_processed_state(), MayaFlux::Nodes::CompositeOpNode< N >::reset_processed_state(), and MayaFlux::Nodes::Node::reset_processed_state_internal().