MayaFlux: MayaFlux::Transitive::Protocol::write_blob
write_blob()
void MayaFlux::Transitive::Protocol::write_blob (std::vector< uint8_t > & out, const std::vector< uint8_t > & blob) inline
Append a length-prefixed blob padded to 4-byte boundary.
Format: [int32 size (big-endian)][data, zero-padded to 4-byte boundary].
Parameters
out Destination buffer.
blob Bytes to write.
Definition at line 173 of file BinaryBuffer.hpp.
{
    write_int32(out, static_cast<int32_t>(blob.size()));
    out.insert(out.end(), blob.begin(), blob.end());
    size_t padded = padded_size(blob.size());
    out.resize(out.size() + (padded - blob.size()), 0);
}
References padded_size(), and write_int32().
Referenced by MayaFlux::Core::OscParser::serialize().