MayaFlux: MayaFlux::Portal::Graphics::stop
stop()
MAYAFLUX_API void MayaFlux::Portal::Graphics::stop ()
Stop all Portal::Graphics operations.
Frees command buffers and stops active rendering. Call this AFTER graphics thread stops, BEFORE destroying resources.
Definition at line 69 of file Graphics.cpp.
{
    if (!g_initialized) {
        return;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Stopping Portal::Graphics...");
    ShaderFoundry::instance().stop();
    RenderFlow::instance().stop();
    ComputePress::instance().stop();
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Portal::Graphics stopped");
}
References MayaFlux::Journal::API, MayaFlux::Portal::Graphics::ComputePress::instance(), MayaFlux::Portal::Graphics::RenderFlow::instance(), MayaFlux::Portal::Graphics::ShaderFoundry::instance(), MF_INFO, MayaFlux::Journal::Portal, MayaFlux::Portal::Graphics::ComputePress::stop(), MayaFlux::Portal::Graphics::RenderFlow::stop(), and MayaFlux::Portal::Graphics::ShaderFoundry::stop().
Referenced by MayaFlux::Core::GraphicsSubsystem::stop().