MayaFlux: MayaFlux::Yantra::process_spectral_windows
process_spectral_windows()
template<typename ProcessorFunc > std::vector< double > MayaFlux::Yantra::process_spectral_windows (std::span< double > data, uint32_t window_size, uint32_t hop_size, ProcessorFunc && processor)
Common spectral processing helper to eliminate code duplication.
Template Parameters
ProcessorFunc Function type for spectral processing
Parameters
data Input data span
window_size Size of analysis window
hop_size Hop size between windows
processor Function to process spectrum in each window
Returns
Processed audio data
Definition at line 44 of file SpectralHelper.hpp.
{
    const size_t num_windows = (data.size() >= window_size) ? (data.size() - window_size) / hop_size + 1 : 0;
    if (num_windows == 0) {
        return { data.begin(), data.end() };
    }
    std::vector<double> output(data.size(), 0.0);
    auto hann_window = Nodes::Generator::generate_window(window_size, Nodes::Generator::WindowType::HANNING);
    Eigen::FFT<double> fft;
    auto window_indices = std::views::iota(size_t { 0 }, num_windows);
    std::ranges::for_each(window_indices, [&](size_t win) {
        size_t start_idx = win * hop_size;
        auto window_data = data.subspan(start_idx,
            std::min(static_cast<size_t>(window_size), data.size() - start_idx));
        Eigen::VectorXd windowed = Eigen::VectorXd::Zero(static_cast<Eigen::Index>(window_size));
        const size_t actual_size = std::min(window_data.size(), hann_window.size());
        for (size_t j = 0; j < actual_size; ++j) {
            windowed(static_cast<Eigen::Index>(j)) = window_data[j] * hann_window[j];
        }
        Eigen::VectorXcd spectrum;
        fft.fwd(spectrum, windowed);
        std::forward<ProcessorFunc>(processor)(spectrum, win);
        Eigen::VectorXd result;
        fft.inv(result, spectrum);
        for (size_t i = 0; i < static_cast<size_t>(result.size()) && start_idx + i < output.size(); ++i) {
            output[start_idx + i] += result[static_cast<Eigen::Index>(i)];
        }
    });
    return output;
}
References MayaFlux::Nodes::Generator::generate_window(), and MayaFlux::Nodes::Generator::HANNING.
Referenced by MayaFlux::Yantra::SpectralTransformer< InputType, OutputType >::transform_implementation(), transform_pitch_shift(), transform_pitch_shift(), transform_spectral_filter(), transform_spectral_filter(), transform_spectral_invert(), and transform_spectral_invert().