MayaFlux: MayaFlux::Kinesis::Discrete::reverse
reverse()
void MayaFlux::Kinesis::Discrete::reverse (std::span< double > data) noexcept
Reverse temporal order in-place.
Parameters
data Target span
Definition at line 90 of file Transform.cpp.
{
    std::ranges::reverse(data);
}
Referenced by MayaFlux::reverse(), MayaFlux::reverse(), MayaFlux::reverse_channels(), MayaFlux::reversed(), MayaFlux::reversed(), and MayaFlux::reversed_channels().