MayaFlux: MayaFlux::get_gaussian_random
get_gaussian_random()
MAYAFLUX_API double MayaFlux::get_gaussian_random (double start = 0, double end = 1)
Generates a gaussian (normal) random number.
Parameters
start Lower bound for scaling
end Upper bound for scaling
Returns
Random number with gaussian distribution
Uses the random number generator from the default engine.
Definition at line 19 of file Random.cpp.
{
    get_context().get_random_engine()->set_type(Utils::distribution::NORMAL);
    return get_context().get_random_engine()->random_sample(start, end);
}
References get_context(), MayaFlux::Core::Engine::get_random_engine(), MayaFlux::Utils::NORMAL, MayaFlux::Nodes::Generator::Stochastics::Random::random_sample(), and MayaFlux::Nodes::Generator::Stochastics::Random::set_type().