MayaFlux: MayaFlux::Nodes::safe_remove_callback
safe_remove_callback()
template<typename ContextT > bool MayaFlux::Nodes::safe_remove_callback (std::vector< TypedHook< ContextT > > & callbacks, const TypedHook< ContextT > & callback)
Removes all callbacks whose target_type() matches that of the supplied callback.
Returns
True if at least one entry was removed.
Definition at line 92 of file NodeUtils.hpp.
{
    bool removed = false;
    auto it = callbacks.begin();
    while (it != callbacks.end()) {
        if (it->target_type() == callback.target_type()) {
            it = callbacks.erase(it);
            removed = true;
        } else {
            ++it;
        }
    }
    return removed;
}
Referenced by MayaFlux::Nodes::Node::remove_hook(), MayaFlux::Nodes::Generator::Counter::remove_hook(), MayaFlux::Nodes::Generator::Impulse::remove_hook(), and MayaFlux::Nodes::Generator::Phasor::remove_hook().