MayaFlux: MayaFlux::Kinesis::Discrete::merge_intervals
merge_intervals()
std::vector< std::pair< size_t, size_t > > MayaFlux::Kinesis::Discrete::merge_intervals (const std::vector< std::pair< size_t, size_t > > & intervals)
Merge overlapping or adjacent half-open intervals.
Parameters
intervals Unsorted [start, end) pairs
Returns
Sorted, non-overlapping merged intervals
Definition at line 14 of file Extract.cpp.
{
    if (intervals.empty())
        return {};
    auto sorted = intervals;
    std::ranges::sort(sorted, [](const auto& a, const auto& b) { return a.first < b.first; });
    std::vector<std::pair<size_t, size_t>> merged;
    merged.push_back(sorted[0]);
    for (size_t i = 1; i < sorted.size(); ++i) {
        auto& last = merged.back();
        const auto& cur = sorted[i];
        if (cur.first <= last.second) {
            last.second = std::max(last.second, cur.second);
        } else {
            merged.push_back(cur);
        }
    }
    return merged;
}
References a, and b.
Referenced by MayaFlux::Yantra::extract_above_mean(), MayaFlux::Yantra::extract_high_energy(), MayaFlux::Yantra::extract_high_spectral(), MayaFlux::Yantra::extract_onsets(), MayaFlux::Yantra::extract_outliers(), MayaFlux::Yantra::extract_peaks(), MayaFlux::Yantra::extract_silence(), and MayaFlux::Yantra::extract_zero_crossings().