MayaFlux: MayaFlux::Yantra::transform_spectral_filter
transform_spectral_filter() [2/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_spectral_filter (DataType & input, double low_freq, double high_freq, double sample_rate = 48000.0, uint32_t window_size = 1024, uint32_t hop_size = 256)
Spectral filtering using existing FFT infrastructure with C++20 ranges (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
low_freq Low cutoff frequency (Hz)
high_freq High cutoff frequency (Hz)
sample_rate Sample rate (Hz)
window_size FFT window size
hop_size Hop size for overlap-add
Returns
Filtered data
Definition at line 181 of file SpectralHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    auto processor = [low_freq, high_freq, sample_rate](Eigen::VectorXcd& spectrum, size_t) {
        auto bin_indices = std::views::iota(0, static_cast<int>(spectrum.size()));
        std::ranges::for_each(bin_indices, [&](int bin) {
            double freq = (bin * sample_rate) / (2.0 * (double)spectrum.size());
            if (freq < low_freq || freq > high_freq) {
                spectrum[bin] = 0.0;
            }
        });
    };
    for (auto& span : target_data) {
        auto result = process_spectral_windows(span, window_size, hop_size, processor);
        std::ranges::copy(result, span.begin());
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References MayaFlux::Yantra::OperationHelper::extract_structured_double(), and process_spectral_windows().
Referenced by MayaFlux::Yantra::SpectralTransformer< InputType, OutputType >::transform_implementation().