MayaFlux: MayaFlux::internal::get_or_create_engine
get_or_create_engine()
Core::Engine & MayaFlux::internal::get_or_create_engine ()
Definition at line 32 of file Core.cpp.
    {
        std::lock_guard<std::recursive_mutex> lock(engine_mutex);
        if (!engine_ref) {
            engine_ref = std::make_unique<Core::Engine>();
            std::atexit(cleanup_engine);
        }
        terminating = false;
        initialized = true;
        return *engine_ref;
    }
References cleanup_engine(), engine_mutex, engine_ref, initialized, and terminating.
Referenced by MayaFlux::get_context(), MayaFlux::Init(), MayaFlux::Init(), MayaFlux::Init(), and MayaFlux::Init().