MayaFlux: MayaFlux::Nodes::safe_remove_callback
safe_remove_callback()
bool MayaFlux::Nodes::safe_remove_callback (std::vector< NodeHook > & callbacks, const NodeHook & callback)
Safely removes a callback from a collection.
Parameters
callbacks The collection of callbacks to remove from
callback The callback function to remove
Returns
True if the callback was found and removed, false otherwise
This function searches for the specified callback in the collection and removes it if found. It's used to unregister callbacks when they're no longer needed.
Definition at line 51 of file NodeUtils.cpp.
{
    bool removed = false;
    auto it = callbacks.begin();
    while (it != callbacks.end()) {
        if (it->target_type() == callback.target_type()) {
            it = callbacks.erase(it);
            removed = true;
        } else {
            ++it;
        }
    }
    return removed;
}
Referenced by MayaFlux::Nodes::Node::remove_hook(), MayaFlux::Nodes::Generator::Impulse::remove_hook(), and MayaFlux::Nodes::Generator::Phasor::remove_hook().