MayaFlux: MayaFlux::Yantra::transform_pitch_shift
transform_pitch_shift() [2/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::transform_pitch_shift (DataType & input, double semitones, uint32_t window_size = 1024, uint32_t hop_size = 256)
Pitch shifting using existing FFT from AnalysisHelper with C++20 ranges (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED
semitones Pitch shift in semitones
window_size FFT window size
hop_size Hop size for overlap-add
Returns
Pitch-shifted data
Definition at line 265 of file SpectralHelper.hpp.
{
    auto [target_data, structure_info] = OperationHelper::extract_structured_double(input);
    if (semitones == 0.0) {
        return input;
    }
    double pitch_ratio = std::pow(2.0, semitones / 12.0);
    auto processor = [pitch_ratio](Eigen::VectorXcd& spectrum, size_t) {
        Eigen::VectorXcd shifted_spectrum = Eigen::VectorXcd::Zero(spectrum.size());
        auto bin_indices = std::views::iota(0, static_cast<int>(spectrum.size()));
        std::ranges::for_each(bin_indices, [&](int bin) {
            int shifted_bin = static_cast<int>(bin * pitch_ratio);
            if (shifted_bin < shifted_spectrum.size()) {
                shifted_spectrum[shifted_bin] = spectrum[bin];
            }
        });
        spectrum = std::move(shifted_spectrum);
    };
    for (auto& span : target_data) {
        auto result = process_spectral_windows(span, window_size, hop_size, processor);
        std::ranges::copy(result, span.begin());
    }
    auto reconstructed_data = target_data
        | std::views::transform([](const auto& span) {
              return std::vector<double>(span.begin(), span.end());
          })
        | std::ranges::to<std::vector>();
    return OperationHelper::reconstruct_from_double<DataType>(reconstructed_data, structure_info);
}
References MayaFlux::Yantra::OperationHelper::extract_structured_double(), and process_spectral_windows().
Referenced by MayaFlux::Yantra::SpectralTransformer< InputType, OutputType >::transform_implementation().