MayaFlux: MayaFlux::Kakshya::coordinates_to_linear
coordinates_to_linear()
uint64_t MayaFlux::Kakshya::coordinates_to_linear (const std::vector< uint64_t > & coords, const std::vector< DataDimension > & dimensions)
Convert N-dimensional coordinates to a linear index for interleaved data.
Parameters
coords N-dimensional coordinates.
dimensions Dimension descriptors (size/stride/role).
Returns
Linear index into the underlying data storage.
Note
Only works with interleaved organization strategy. For planar data, use coordinates_to_planar_indices() instead.
Definition at line 6 of file CoordUtils.cpp.
{
    uint64_t index = 0;
    uint64_t multiplier = 1;
    for (int i = dimensions.size() - 1; i >= 0; --i) {
        if (i < coords.size()) {
            index += coords[i] * multiplier;
        }
        multiplier *= dimensions[i].size;
    }
    return index;
}
Referenced by MayaFlux::Kakshya::SoundStreamContainer::coordinates_to_linear_index(), MayaFlux::Kakshya::WindowContainer::coordinates_to_linear_index(), extract_region_data(), and set_or_update_region_data().