MayaFlux: MayaFlux::Portal::Text::initialize
initialize()
MAYAFLUX_API bool MayaFlux::Portal::Text::initialize (std::optional< Core::TextConfig > config)
Initialize Portal::Text.
Initialises TypeFaceFoundry. Must be called before constructing any FontFace or GlyphAtlas. Safe to call after Portal::Graphics::initialize().
Returns
true on success.
Definition at line 18 of file Text.cpp.
{
    if (g_initialized) {
        MF_WARN(Journal::Component::Portal, Journal::Context::API,
            "Portal::Text already initialized");
        return true;
    }
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Initializing Portal::Text...");
    if (!TypeFaceFoundry::instance().initialize()) {
        MF_ERROR(Journal::Component::Portal, Journal::Context::API,
            "Failed to initialize TypeFaceFoundry");
        return false;
    }
    if (config) {
        const auto& [family, style, pixel_size, atlas_size] = *config;
        if (!set_default_font(family, style, pixel_size, atlas_size)) {
            MF_ERROR(Journal::Component::Portal, Journal::Context::Init,
                "Failed to set default font '{}{}{}'", family, style.empty() ? "" : " ", style);
        }
    } else {
        MF_INFO(Journal::Component::Portal, Journal::Context::API,
            "No default font configured for Portal::Text");
    }
    g_initialized = true;
    MF_INFO(Journal::Component::Portal, Journal::Context::API,
        "Portal::Text initialized");
    return true;
}
References MayaFlux::Journal::API, MayaFlux::Journal::Init, initialize(), MayaFlux::Portal::Text::TypeFaceFoundry::instance(), MF_ERROR, MF_INFO, MF_WARN, MayaFlux::Journal::Portal, and set_default_font().
Referenced by MayaFlux::Core::GraphicsSubsystem::initialize().