MayaFlux: MayaFlux::Kakshya::detect_data_modality
detect_data_modality() [1/2]
DataModality MayaFlux::Kakshya::detect_data_modality (const std::vector< DataDimension > & dimensions)
Detects data modality from dimension information.
Parameters
dimensions Vector of data dimensions with role information
Returns
Detected DataModality type
Consolidates modality detection logic that was duplicated across analyzers. Uses dimension roles and count to determine appropriate processing approach.
Definition at line 72 of file DataUtils.cpp.
{
    if (dimensions.empty()) {
        return DataModality::UNKNOWN;
    }
    size_t time_dims = 0, spatial_dims = 0, channel_dims = 0, frequency_dims = 0, custom_dims = 0;
    size_t total_spatial_elements = 1;
    size_t total_channels = 0;
    for (const auto& dim : dimensions) {
        if (dim.grouping) {
            switch (dim.role) {
            case DataDimension::Role::POSITION:
                return DataModality::VERTEX_POSITIONS_3D;
            case DataDimension::Role::NORMAL:
                return DataModality::VERTEX_NORMALS_3D;
            case DataDimension::Role::TANGENT:
            case DataDimension::Role::BITANGENT:
                return DataModality::VERTEX_TANGENTS_3D;
            case DataDimension::Role::UV:
                return DataModality::TEXTURE_COORDS_2D;
            case DataDimension::Role::COLOR:
                if (dim.grouping->count == 3)
                    return DataModality::VERTEX_COLORS_RGB;
                if (dim.grouping->count == 4)
                    return DataModality::VERTEX_COLORS_RGBA;
                break;
            default:
                if (dim.grouping->count == 16)
                    return DataModality::TRANSFORMATION_MATRIX;
                break;
            }
        }
    }
    for (const auto& dim : dimensions) {
        switch (dim.role) {
        case DataDimension::Role::TIME:
            time_dims++;
            break;
        case DataDimension::Role::SPATIAL_X:
        case DataDimension::Role::SPATIAL_Y:
        case DataDimension::Role::SPATIAL_Z:
            spatial_dims++;
            total_spatial_elements *= dim.size;
            break;
        case DataDimension::Role::CHANNEL:
            channel_dims++;
            total_channels += dim.size;
            break;
        case DataDimension::Role::FREQUENCY:
            frequency_dims++;
            break;
        case DataDimension::Role::CUSTOM:
        default:
            custom_dims++;
            break;
        }
    }
    if (time_dims == 1 && spatial_dims == 0 && frequency_dims == 0) {
        if (channel_dims == 0) {
            return DataModality::AUDIO_1D;
        } else if (channel_dims == 1) {
            return (total_channels <= 1) ? DataModality::AUDIO_1D : DataModality::AUDIO_MULTICHANNEL;
        } else {
            return DataModality::AUDIO_MULTICHANNEL;
        }
    }
    if (time_dims >= 1 && frequency_dims >= 1) {
        if (spatial_dims == 0 && channel_dims <= 1) {
            return DataModality::SPECTRAL_2D;
        }
        return DataModality::TENSOR_ND;
    }
    if (spatial_dims >= 2 && time_dims == 0) {
        if (spatial_dims == 2) {
            if (channel_dims == 0) {
                return DataModality::IMAGE_2D;
            } else if (channel_dims == 1 && total_channels >= 3) {
                return DataModality::IMAGE_COLOR;
            } else {
                return DataModality::IMAGE_2D;
            }
        } else if (spatial_dims == 3) {
            return DataModality::VOLUMETRIC_3D;
        }
    }
    if (time_dims >= 1 && spatial_dims >= 2) {
        if (spatial_dims == 2) {
            if (channel_dims == 0 || (channel_dims == 1 && total_channels <= 1)) {
                return DataModality::VIDEO_GRAYSCALE;
            } else {
                return DataModality::VIDEO_COLOR;
            }
        }
        return DataModality::TENSOR_ND;
    }
    if (spatial_dims == 2 && time_dims == 0 && channel_dims >= 1) {
        if (total_spatial_elements >= 64 && total_channels >= 1) {
            return DataModality::TEXTURE_2D;
        }
    }
    return DataModality::TENSOR_ND;
}
References AUDIO_1D, AUDIO_MULTICHANNEL, MayaFlux::Kakshya::DataDimension::BITANGENT, MayaFlux::Kakshya::DataDimension::CHANNEL, MayaFlux::Kakshya::DataDimension::COLOR, MayaFlux::Kakshya::DataDimension::CUSTOM, MayaFlux::Kakshya::DataDimension::FREQUENCY, IMAGE_2D, IMAGE_COLOR, MayaFlux::Kakshya::DataDimension::NORMAL, MayaFlux::Kakshya::DataDimension::POSITION, MayaFlux::Kakshya::DataDimension::SPATIAL_X, MayaFlux::Kakshya::DataDimension::SPATIAL_Y, MayaFlux::Kakshya::DataDimension::SPATIAL_Z, SPECTRAL_2D, MayaFlux::Kakshya::DataDimension::TANGENT, TENSOR_ND, TEXTURE_2D, TEXTURE_COORDS_2D, MayaFlux::Kakshya::DataDimension::TIME, TRANSFORMATION_MATRIX, UNKNOWN, MayaFlux::Kakshya::DataDimension::UV, VERTEX_COLORS_RGB, VERTEX_COLORS_RGBA, VERTEX_NORMALS_3D, VERTEX_POSITIONS_3D, VERTEX_TANGENTS_3D, VIDEO_COLOR, VIDEO_GRAYSCALE, and VOLUMETRIC_3D.
Referenced by detect_data_modality(), MayaFlux::Yantra::infer_from_container(), MayaFlux::Yantra::infer_from_data_variant(), and MayaFlux::Yantra::infer_from_data_variant_vector().