MayaFlux: MayaFlux::Portal::Forma::make_collapsible
make_collapsible()
Collapsible MayaFlux::Portal::Forma::make_collapsible (const std::shared_ptr< Core::Window > & window, Layer & layer, Context & ctx, Bridge & bridge, LayoutCursor & cursor, float x_min, float x_max, float row_h, bool initially_open = true, glm::vec3 color_closed = glm::vec3(0.25F), glm::vec3 color_open = glm::vec3(0.35F), std::shared_ptr< Core::VKImage > label = nullptr) inline
Construct a collapsible header strip.
Creates and registers a FormaBuffer, constructs a Mapped<bool> whose geometry function produces the header quad, registers it with the Bridge sync loop, and wires the on_press toggle via ctx. Caller adds body elements to layer and calls layer.relate(col.header_id, body_id) for each one; set_visible cascades to all related ids on toggle.
Parameters
window Target window for rendering.
layer Layer to register the header element on.
ctx Context to wire the left-click toggle handler.
bridge Bridge owning the sync loop.
cursor Layout cursor. Advanced by row_h on return.
x_min Left edge in NDC.
x_max Right edge in NDC.
row_h Header strip height in NDC units.
initially_open Starting toggle state.
color_closed Background color when closed.
color_open Background color when open.
label Optional GPU image overlaid on the header as a label. When provided, the header uses the multi-texture shader; when null, a plain color-only shader is used.
Returns
Fully constructed Collapsible. cursor_out is below the header strip.
Definition at line 164 of file Collapsible.hpp.
{
    const size_t vertex_count = label ? 12 : 6;
    const size_t cap = vertex_count * Kakshya::VertexLayout::for_meshes().stride_bytes;
    auto buf = label
        ? create_buffer(window, cap,
              Graphics::PrimitiveTopology::TRIANGLE_LIST,
              std::vector<std::pair<std::string, std::shared_ptr<Core::VKImage>>> {
                  { "text", label } })
        : create_buffer(window, cap,
              Graphics::PrimitiveTopology::TRIANGLE_LIST);
    const float y_top = cursor.y();
    cursor.advance(row_h);
    auto open_state = std::make_shared<MappedState<bool>>();
    open_state->write(initially_open);
    Mapped<bool> mapped;
    mapped.state = open_state;
    mapped.geometry_fn = collapsible_header_geom(
        y_top, x_min, x_max, row_h, color_closed, color_open, label);
    mapped.element.buffer = buf;
    mapped.element.bounds_hint = Kinesis::AABB2D {
        .min = { x_min, cursor.y() },
        .max = { x_max, cursor.y() + row_h },
    };
    const uint32_t hid = layer.add(mapped.element);
    mapped.element.id = hid;
    open_state->id = hid;
    bridge.register_element(std::move(mapped));
    ctx.on_press(hid, IO::MouseButtons::Left,
        [open = open_state, &layer, hid](uint32_t, glm::vec2) {
            const bool next = !open->value;
            open->write(next);
            for (auto rel_id : layer.related_ids(hid))
                layer.set_visible(rel_id, next);
        });
    return Collapsible {
        .header_id = hid,
        .open = open_state,
        .buf = buf,
        .cursor_out = LayoutCursor(cursor.y()),
    };
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::LayoutCursor::advance(), MayaFlux::Portal::Forma::Element::bounds_hint, MayaFlux::Portal::Forma::Element::buffer, collapsible_header_geom(), create_buffer(), MayaFlux::Portal::Forma::Mapped< T >::element, MayaFlux::Kakshya::VertexLayout::for_meshes(), MayaFlux::Portal::Forma::Mapped< T >::geometry_fn, MayaFlux::Portal::Forma::Collapsible::header_id, MayaFlux::Portal::Forma::Element::id, MayaFlux::IO::Left, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Context::on_press(), MayaFlux::Portal::Forma::Bridge::register_element(), MayaFlux::Portal::Forma::Layer::related_ids(), MayaFlux::Portal::Forma::Layer::set_visible(), MayaFlux::Portal::Forma::Mapped< T >::state, MayaFlux::Kakshya::VertexLayout::stride_bytes, MayaFlux::Portal::Graphics::TRIANGLE_LIST, and MayaFlux::Portal::Forma::LayoutCursor::y().
Referenced by make_value_group().