MayaFlux: MayaFlux::Buffers::extract_single_sample
extract_single_sample()
double MayaFlux::Buffers::extract_single_sample (const std::shared_ptr< Nodes::Node > & node)
Extract a single sample from a node with proper snapshot management.
Returns
Extracted sample value
Definition at line 125 of file BufferUtils.cpp.
{
    if (!node) {
        MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "extract_single_sample: null node");
        return 0.0;
    }
    static std::atomic<uint64_t> s_context_counter { 1 };
    uint64_t my_context_id = s_context_counter.fetch_add(1, std::memory_order_relaxed);
    const auto state = node->m_state.load(std::memory_order_acquire);
    if (state == Nodes::NodeState::INACTIVE && !node->is_buffer_processed()) {
        double value = node->process_sample(0.F);
        node->mark_buffer_processed();
        return value;
    }
    bool claimed = node->try_claim_snapshot_context(my_context_id);
    if (claimed) {
        try {
            node->save_state();
            double value = node->process_sample(0.F);
            node->restore_state();
            if (node->is_buffer_processed()) {
                node->request_buffer_reset();
            }
            node->release_snapshot_context(my_context_id);
            return value;
        } catch (const std::exception& e) {
            node->release_snapshot_context(my_context_id);
            MF_RT_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
                "Error processing node: {}", e.what());
            return 0.0;
        }
    } else {
        uint64_t active_context = node->get_active_snapshot_context();
        if (!wait_for_snapshot_completion(node, active_context)) {
            return 0.0;
        }
        node->save_state();
        double value = node->process_sample(0.F);
        node->restore_state();
        if (node->is_buffer_processed()) {
            node->request_buffer_reset();
        }
        return value;
    }
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, MayaFlux::Nodes::INACTIVE, MF_RT_ERROR, and wait_for_snapshot_completion().
Referenced by MayaFlux::Buffers::DescriptorBindingsProcessor::update_descriptor_from_node(), and MayaFlux::Buffers::NodeBindingsProcessor::update_push_constants_from_nodes().