MayaFlux: MayaFlux::Kakshya::modality_to_string
modality_to_string()
std::string_view MayaFlux::Kakshya::modality_to_string (DataModality modality)
Convert DataModality enum to string representation.
Parameters
modality DataModality value
Returns
String view of the modality name
Definition at line 83 of file NDData.cpp.
{
    return Reflect::enum_to_string(modality);
}
References MayaFlux::Reflect::enum_to_string().
Referenced by MayaFlux::Kakshya::DataDimension::create_dimensions(), MayaFlux::Core::BackendResourceManager::initialize_buffer(), MayaFlux::Kakshya::DataInsertion::reserve_space(), MayaFlux::Kakshya::DataAccess::type_description(), MayaFlux::Kakshya::DataInsertion::validate_scalar_insertion(), MayaFlux::Kakshya::DataInsertion::validate_structured_insertion(), and MayaFlux::Buffers::VKBuffer::VKBuffer().