MayaFlux: MayaFlux::Buffers::upload_device_local
upload_device_local()
MAYAFLUX_API void MayaFlux::Buffers::upload_device_local (const std::shared_ptr< VKBuffer > & target, const std::shared_ptr< VKBuffer > & staging_buffer, const Kakshya::DataVariant & data)
Upload data to a device-local buffer using a staging buffer.
Parameters
target Target VKBuffer to upload data into
staging_buffer Host-visible staging VKBuffer used for the upload
data DataVariant containing the data to upload
This function handles uploading data from a Kakshya::DataVariant into a device-local VKBuffer by utilizing a staging buffer. It copies the data into the staging buffer, flushes it, and then issues a command to copy from the staging buffer to the target device-local buffer.
Definition at line 61 of file StagingUtils.cpp.
{
    Kakshya::DataAccess accessor(
        const_cast<Kakshya::DataVariant&>(data),
        {},
        target->get_modality());
    auto [ptr, bytes, format_hint] = accessor.gpu_buffer();
    if (bytes > target->get_size_bytes()) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Upload data size {} exceeds buffer capacity {}",
            bytes, target->get_size_bytes());
    }
    auto& staging_resources = staging_buffer->get_buffer_resources();
    void* staging_mapped = staging_resources.mapped_ptr;
    if (!staging_mapped) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "Staging buffer has no mapped pointer");
    }
    std::memcpy(staging_mapped, ptr, bytes);
    staging_buffer->mark_dirty_range(0, bytes);
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "upload_host_visible requires a valid buffer service");
    }
    auto dirty_ranges = staging_buffer->get_and_clear_dirty_ranges();
    for (auto& [offset, size] : dirty_ranges) {
        buffer_service->flush_range(
            staging_resources.memory,
            offset,
            size);
    }
    buffer_service->execute_immediate([&](void* ptr) {
        vk::BufferCopy copy_region;
        copy_region.srcOffset = 0;
        copy_region.dstOffset = 0;
        copy_region.size = bytes;
        vk::CommandBuffer cmd(static_cast<VkCommandBuffer>(ptr));
        cmd.copyBuffer(
            staging_buffer->get_buffer(),
            target->get_buffer(),
            1, &copy_region);
    });
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, cmd, MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Kakshya::DataAccess::gpu_buffer(), MayaFlux::Registry::BackendRegistry::instance(), and size.
Referenced by MayaFlux::Buffers::VKBuffer::clone_to(), MayaFlux::Buffers::BufferUploadProcessor::upload_device_local(), and upload_to_gpu().