MayaFlux: MayaFlux::Yantra::interpolate_linear
interpolate_linear() [1/2]
template<OperationReadyData DataType> DataType MayaFlux::Yantra::interpolate_linear (DataType & input, size_t target_size)
Linear interpolation between data points using C++20 ranges (IN-PLACE)
Template Parameters
DataType OperationReadyData type
Parameters
input Input data - WILL BE MODIFIED/RESIZED
target_size Target size after interpolation
Returns
Interpolated data
Definition at line 629 of file MathematicalHelper.hpp.
{
    auto [data_span, structure_info] = OperationHelper::extract_structured_double(input);
    std::vector<std::vector<double>> interpolated;
    for (auto& span : data_span) {
        if (target_size != span.size()) {
            std::vector<double> sub_data(target_size);
            interpolate(span, std::ref(sub_data), target_size);
            interpolated.push_back(std::move(sub_data));
        } else {
            interpolated.emplace_back(span.begin(), span.end());
        }
    }
    input = OperationHelper::reconstruct_from_double<DataType>(interpolated, structure_info);
    return input;
}
References interpolate_linear().
Referenced by interpolate_linear(), interpolate_linear(), and MayaFlux::Yantra::TemporalTransformer< InputType, OutputType >::transform_implementation().