MayaFlux: MayaFlux::Portal::Forma::Geometry::horizontal_fader
horizontal_fader()
GeometryFn< float > MayaFlux::Portal::Forma::Geometry::horizontal_fader (Kinesis::AABB2D bounds, float handle_w, glm::vec3 track_color = glm::vec3(0.3F), glm::vec3 handle_color = glm::vec3(0.9F)) inline
Geometry function for a horizontal fader in NDC space.
Parameters
bounds Full extent of the fader in NDC.
handle_w Handle width in NDC units.
track_color Track quad color.
handle_color Handle quad color.
Definition at line 59 of file Geometry.hpp.
{
    return [bounds, handle_w, track_color, handle_color](
               float v, std::vector<uint8_t>& out, Element& el) {
        float x = bounds.min.x + v * (bounds.width() - handle_w);
        float yt = bounds.min.y + bounds.height() * 0.35F;
        float yb = bounds.min.y + bounds.height() * 0.65F;
        using V = Nodes::LineVertex;
        std::vector<V> verts;
        verts.reserve(8);
        // track — two triangles as TRIANGLE_STRIP
        verts.push_back({ .position = { bounds.min.x, yt, 0 }, .color = track_color });
        verts.push_back({ .position = { bounds.min.x, yb, 0 }, .color = track_color });
        verts.push_back({ .position = { bounds.max.x, yt, 0 }, .color = track_color });
        verts.push_back({ .position = { bounds.max.x, yb, 0 }, .color = track_color });
        // handle — two triangles as TRIANGLE_STRIP
        verts.push_back({ .position = { x, bounds.min.y, 0 }, .color = handle_color });
        verts.push_back({ .position = { x, bounds.max.y, 0 }, .color = handle_color });
        verts.push_back({ .position = { x + handle_w, bounds.min.y, 0 }, .color = handle_color });
        verts.push_back({ .position = { x + handle_w, bounds.max.y, 0 }, .color = handle_color });
        detail::write_verts(out, verts);
        el.bounds_hint = Kinesis::AABB2D {
            .min = glm::vec2(x, bounds.min.y),
            .max = glm::vec2(x + handle_w, bounds.max.y)
        };
        el.contains = {};
    };
}
References MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Kinesis::AABB2D::max, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Kinesis::AABB2D::width(), and MayaFlux::Portal::Forma::Geometry::detail::write_verts().