MayaFlux: MayaFlux::Portal::Forma::row_pixel_dims
row_pixel_dims()
MAYAFLUX_API glm::uvec2 MayaFlux::Portal::Forma::row_pixel_dims (const std::shared_ptr< Core::Window > & window, float x_min, float x_max, float row_h)
Convert an NDC row rect into integer pixel dimensions.
Clamps width to at least 1 pixel and height to at least the default atlas pixel size to avoid degenerate textures.
Parameters
window Target window for pixel dimension calculation.
x_min Left edge in NDC.
x_max Right edge in NDC.
row_h Row height in NDC units.
Definition at line 57 of file QueryUtils.cpp.
{
    const auto& ws = window->get_state();
    const auto w = static_cast<uint32_t>(
        (x_max - x_min) * 0.5F * static_cast<float>(ws.current_width));
    const auto h = static_cast<uint32_t>(
        row_h * 0.5F * static_cast<float>(ws.current_height));
    auto atlas = Text::TypeFaceFoundry::instance().get_default_glyph_atlas();
    if (!atlas) {
        error<std::runtime_error>(Journal::Component::Portal, Journal::Context::Runtime,
            std::source_location::current(),
            "Failed to get default glyph atlas for row pixel dimension calculation");
    }
    const uint32_t min_h = atlas->pixel_size();
    return { std::max(w, 1U), std::max(h, min_h) };
}
References MayaFlux::Portal::Text::TypeFaceFoundry::get_default_glyph_atlas(), h, MayaFlux::Portal::Text::TypeFaceFoundry::instance(), MayaFlux::Journal::Portal, and MayaFlux::Journal::Runtime.
Referenced by MayaFlux::Portal::Forma::Inspector::buffer(), MayaFlux::Portal::Forma::Inspector::buffer_manager(), MayaFlux::Portal::Forma::Inspector::event(), MayaFlux::Portal::Forma::Inspector::event_manager(), MayaFlux::Portal::Forma::Inspector::inspect_modulator_tree(), MayaFlux::Portal::Forma::Inspector::inspect_task(), MayaFlux::Portal::Forma::Inspector::node(), MayaFlux::Portal::Forma::Inspector::node_graph_manager(), MayaFlux::Portal::Forma::Inspector::node_network(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_audio_buffer(), MayaFlux::Portal::Forma::Inspector::root_graphics_buffer(), MayaFlux::Portal::Forma::Inspector::root_node(), MayaFlux::Portal::Forma::Inspector::scheduler(), and MayaFlux::Portal::Forma::Inspector::tasks().