MayaFlux: MayaFlux::Portal::Forma::Plot::place_label
place_label()
MAYAFLUX_API uint32_t MayaFlux::Portal::Forma::Plot::place_label (Surface & surface, std::shared_ptr< Buffers::FormaBuffer > buf, const LabelSpec & spec, uint32_t relate_to = 0)
Place a text label element onto surface using a pre-built buffer.
buf must have been created with an additional_textures slot named "text" (or equivalent). Buffer construction is the caller's responsibility; Portal::Forma::plot() handles this automatically.
Parameters
surface Target surface.
buf FormaBuffer with a texture slot. One buffer per label.
spec Label geometry and style.
relate_to If non-zero, the produced element is related to this id.
Returns
Element id of the produced label element.
Definition at line 15 of file Plot.cpp.
{
    const auto render_bounds = spec.render_bounds.x > 0 && spec.render_bounds.y > 0
        ? spec.render_bounds
        : Kinesis::ndc_size_to_pixels(
              { spec.bounds.width(), spec.bounds.height() },
              surface.window()->get_state().current_width,
              surface.window()->get_state().current_height);
    Element el;
    el.with_buffer(std::move(buf))
        .with_bounds(spec.bounds)
        .with_name(spec.name)
        .with_text(spec.text,
            Portal::Text::PressParams {
                .color = spec.color,
                .render_bounds = render_bounds,
            },
            spec.bounds);
    if (!spec.interactive)
        el.non_interactive();
    const uint32_t id = surface.layer().add(std::move(el));
    if (relate_to != 0)
        surface.layer().relate(relate_to, id);
    return id;
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::Plot::LabelSpec::bounds, MayaFlux::Kinesis::AABB2D::height(), MayaFlux::Portal::Forma::Plot::LabelSpec::interactive, MayaFlux::Portal::Forma::Surface::layer(), MayaFlux::Portal::Forma::Plot::LabelSpec::name, MayaFlux::Kinesis::ndc_size_to_pixels(), MayaFlux::Portal::Forma::Element::non_interactive(), MayaFlux::Portal::Forma::Layer::relate(), MayaFlux::Portal::Forma::Plot::LabelSpec::render_bounds, MayaFlux::Portal::Forma::Plot::LabelSpec::text, MayaFlux::Kinesis::AABB2D::width(), MayaFlux::Portal::Forma::Surface::window(), MayaFlux::Portal::Forma::Element::with_bounds(), MayaFlux::Portal::Forma::Element::with_buffer(), MayaFlux::Portal::Forma::Element::with_name(), and MayaFlux::Portal::Forma::Element::with_text().