MayaFlux: MayaFlux::Portal::Forma::Plot::waveform
waveform()
GeometryFn< std::shared_ptr< Kakshya::PlotContainer > > MayaFlux::Portal::Forma::Plot::waveform (AxisRange x_range = {}, AxisRange y_range = {}, AxisRange z_range = {}, const std::vector< glm::vec3 > & palette = {}, float thickness = 1.5F)
LINE_STRIP waveform for TIME or SPATIAL_Y series.
Reads all SPATIAL_X series as explicit X sample positions. If none are present, generates uniform X positions across [x_range.min, x_range.max] for each Y series independently.
SPATIAL_Z series map to the Z position of each vertex if present, enabling 3D ribbon / parametric curve display. If a SPATIAL_Z series count does not match the corresponding Y series, Z defaults to 0.
Each Y series produces one LINE_STRIP run. Runs are separated by a degenerate vertex so they share one FormaBuffer.
Per-series color is resolved from palette cyclically.
Calls container->process_default() before reading processed_data.
Parameters
x_range Domain for X. auto_scale recomputes from data each frame.
y_range Domain for Y.
z_range Domain for Z. Ignored if no SPATIAL_Z series present.
palette Per-series colors, cycled. {1,1,1} if empty.
thickness Line thickness in pixels.
Definition at line 123 of file Plot.cpp.
{
    return [x_range, y_range, z_range, palette, thickness](
               const std::shared_ptr<Kakshya::PlotContainer>& container,
               std::vector<uint8_t>& out,
               Element&) mutable {
        if (!container)
            return;
        container->process_default();
        auto y_series = series_by_role(*container, Role::SPATIAL_Y);
        if (y_series.empty())
            y_series = series_by_role(*container, Role::TIME);
        if (y_series.empty())
            return;
        const auto x_series = series_by_role(*container, Role::SPATIAL_X);
        const auto z_series = series_by_role(*container, Role::SPATIAL_Z);
        apply_auto_scale(x_range, x_series.empty() ? y_series : x_series);
        apply_auto_scale(y_range, y_series);
        apply_auto_scale(z_range, z_series);
        out.clear();
        for (size_t si = 0; si < y_series.size(); ++si) {
            const auto& ys = y_series[si];
            const size_t n = ys.size();
            if (n == 0)
                continue;
            const glm::vec3 color = palette_color(palette, si);
            const bool has_x = si < x_series.size() && x_series[si].size() == n;
            const bool has_z = si < z_series.size() && z_series[si].size() == n;
            std::vector<float> xs;
            if (has_x) {
                xs.reserve(n);
                for (double v : x_series[si])
                    xs.push_back(x_range.to_ndc(static_cast<float>(v)));
            } else {
                xs = uniform_x(n, x_range);
            }
            for (size_t i = 0; i < n; ++i) {
                LineVertex v;
                v.position = glm::vec3(
                    xs[i],
                    y_range.to_ndc(static_cast<float>(ys[i])),
                    has_z ? z_range.to_ndc(static_cast<float>(z_series[si][i])) : 0.F);
                v.color = color;
                v.thickness = thickness;
                push_vertex(out, v);
            }
            // Degenerate separator between runs: repeat last vertex twice
            // with zero thickness so the LINE_STRIP draws no segment between runs.
            if (si + 1 < y_series.size()) {
                const float last_z = has_z
                    ? z_range.to_ndc(static_cast<float>(z_series[si][n - 1]))
                    : 0.F;
                LineVertex sep;
                sep.position = glm::vec3(
                    xs[n - 1],
                    y_range.to_ndc(static_cast<float>(ys[n - 1])),
                    last_z);
                sep.color = color;
                sep.thickness = 0.F;
                push_vertex(out, sep);
                push_vertex(out, sep);
            }
        }
    };
}
References apply_auto_scale(), color, MayaFlux::Nodes::LineVertex::color, palette_color(), MayaFlux::Nodes::LineVertex::position, series_by_role(), MayaFlux::Nodes::LineVertex::thickness, and MayaFlux::Portal::Forma::Plot::AxisRange::to_ndc().