MayaFlux: MayaFlux::Buffers::download_from_gpu
download_from_gpu() [3/3]
MAYAFLUX_API void MayaFlux::Buffers::download_from_gpu (const std::shared_ptr< VKBuffer > & source, void * data, size_t size, const std::shared_ptr< VKBuffer > & staging = nullptr)
Download from GPU buffer to raw data (auto-detects host-visible vs device-local)
Parameters
source Source GPU buffer
data Destination data pointer
size Size in bytes
staging Optional staging buffer (created if needed for device-local)
Convenience wrapper over StagingUtils that:
Auto-detects if buffer is host-visible or device-local
Handles staging buffer creation if needed
Copies data to destination pointer
Definition at line 337 of file StagingUtils.cpp.
{
    if (!source) {
        error<std::invalid_argument>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "download_from_gpu: source buffer is null");
    }
    if (size == 0) {
        return;
    }
    auto temp_target = std::make_shared<VKBuffer>(
        size, VKBuffer::Usage::STAGING, Kakshya::DataModality::UNKNOWN);
    auto buffer_service = Registry::BackendRegistry::instance()
                              .get_service<Registry::Service::BufferService>();
    if (!buffer_service) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "download_from_gpu requires a valid buffer service");
    }
    buffer_service->initialize_buffer(temp_target);
    if (source->is_host_visible()) {
        download_host_visible(source, temp_target);
    } else {
        std::shared_ptr<VKBuffer> staging_buf = staging;
        if (!staging_buf) {
            staging_buf = create_staging_buffer(size);
        }
        download_device_local(source, temp_target, staging_buf);
    }
    auto temp_data = temp_target->get_data();
    if (temp_data.empty()) {
        error<std::runtime_error>(
            Journal::Component::Buffers,
            Journal::Context::BufferProcessing,
            std::source_location::current(),
            "download_from_gpu: failed to retrieve data from temporary buffer");
    }
    if (temp_data.size() > 1) {
        MF_ERROR(Journal::Component::Buffers, Journal::Context::BufferProcessing,
            "download_from_gpu: unexpected multiple data variants in temporary buffer. Only the first will be used.");
    }
    Kakshya::DataAccess accessor(
        const_cast<Kakshya::DataVariant&>(temp_data[0]),
        {},
        source->get_modality());
    auto [ptr, bytes, format_hint] = accessor.gpu_buffer();
    std::memcpy(data, ptr, std::min(size, bytes));
}
References MayaFlux::Journal::BufferProcessing, MayaFlux::Journal::Buffers, create_staging_buffer(), download_device_local(), download_host_visible(), MayaFlux::Registry::BackendRegistry::get_service(), MayaFlux::Kakshya::DataAccess::gpu_buffer(), MayaFlux::Registry::BackendRegistry::instance(), MF_ERROR, size, MayaFlux::Buffers::VKBuffer::STAGING, and MayaFlux::Kakshya::UNKNOWN.
Referenced by MayaFlux::Nodes::GpuSync::ComputeOutNode::compute_frame(), download_from_gpu(), download_from_gpu(), and download_to_view().