MayaFlux: MayaFlux::Yantra::infer_from_segments
infer_from_segments()
std::pair< std::vector< Kakshya::DataDimension >, Kakshya::DataModality > MayaFlux::Yantra::infer_from_segments (const std::vector< Kakshya::RegionSegment > & segments, const std::shared_ptr< Kakshya::SignalSourceContainer > & container)
Infer structure from RegionSegments.
Definition at line 86 of file StructureIntrospection.cpp.
{
    if (segments.empty() || !container) {
        return { { { Kakshya::DataDimension::time(0) } }, Kakshya::DataModality::UNKNOWN };
    }
    bool consistent_coords = std::ranges::all_of(segments,
        [&](const auto& seg) {
            return seg.source_region.end_coordinates.size() == segments[0].source_region.end_coordinates.size();
        });
    if (consistent_coords) {
        return infer_from_region(segments[0].source_region, container);
    }
    auto max_coord_segment = std::ranges::max_element(segments,
        [](const auto& a, const auto& b) {
            return a.source_region.end_coordinates.size() < b.source_region.end_coordinates.size();
        });
    return infer_from_region(max_coord_segment->source_region, container);
}
References a, b, infer_from_region(), MayaFlux::Kakshya::DataDimension::time(), and MayaFlux::Kakshya::UNKNOWN.
Referenced by infer_structure().