MayaFlux: MayaFlux::Portal::Forma::Collapsible::place
place()
Collapsible & MayaFlux::Portal::Forma::Collapsible::place (std::shared_ptr< Buffers::FormaBuffer > buf, Surface & surface, LayoutCursor & cursor, float x_min, float x_max, float row_h)
Register the header element and wire the toggle callback.
Advances cursor by row_h. Populates header_id, open, buf, and cursor_out on this struct.
Parameters
buf Pre-created FormaBuffer sized for this header.
surface Surface to register the header on.
cursor Layout cursor. Advanced by row_h on return.
x_min Left edge in NDC.
x_max Right edge in NDC.
row_h Header strip height in NDC units.
Returns
*this, with results populated.
Definition at line 73 of file Collapsible.cpp.
{
    buf = std::move(in_buf);
    const float y_top = cursor.y();
    cursor.advance(row_h);
    auto open_state = std::make_shared<MappedState<bool>>();
    open_state->write(m_initially_open);
    Mapped<bool> mapped;
    mapped.state = open_state;
    mapped.geometry_fn = collapsible_header_geom(
        y_top, x_min, x_max, row_h, m_color_closed, m_color_open, m_label != nullptr);
    mapped.element.buffer = buf;
    mapped.element.bounds_hint = Kinesis::AABB2D {
        .min = { x_min, cursor.y() },
        .max = { x_max, y_top },
    };
    const uint32_t hid = surface.layer().add(mapped.element);
    mapped.element.id = hid;
    open_state->id = hid;
    mapped.sync();
    surface.ctx().on_press(hid, IO::MouseButtons::Left,
        [m = std::move(mapped), open = open_state, surface, hid](uint32_t, glm::vec2) mutable {
            const bool next = !open->value;
            open->write(next);
            for (auto rel_id : surface.layer().related_ids(hid))
                surface.layer().set_visible(rel_id, next);
            m.sync();
        });
    header_id = hid;
    open = open_state;
    cursor_out = cursor;
    return *this;
}
References MayaFlux::Portal::Forma::Layer::add(), MayaFlux::Portal::Forma::LayoutCursor::advance(), MayaFlux::Portal::Forma::Element::bounds_hint, buf, MayaFlux::Portal::Forma::Element::buffer, MayaFlux::Portal::Forma::Surface::ctx(), cursor_out, MayaFlux::Portal::Forma::Mapped< T >::element, MayaFlux::Portal::Forma::Mapped< T >::geometry_fn, header_id, MayaFlux::Portal::Forma::Element::id, MayaFlux::Portal::Forma::Surface::layer(), MayaFlux::IO::Left, m_color_closed, m_color_open, m_initially_open, m_label, MayaFlux::Kinesis::AABB2D::min, MayaFlux::Portal::Forma::Context::on_press(), open, MayaFlux::Portal::Forma::Layer::related_ids(), MayaFlux::Portal::Forma::Layer::set_visible(), MayaFlux::Portal::Forma::Mapped< T >::state, MayaFlux::Portal::Forma::Mapped< T >::sync(), and MayaFlux::Portal::Forma::LayoutCursor::y().
Referenced by MayaFlux::Portal::Forma::make_collapsible(), and MayaFlux::Portal::Forma::make_value_group().