MayaFlux: MayaFlux::IO::FileRegion::to_region
to_region()
Kakshya::Region MayaFlux::IO::FileRegion::to_region () const
Convert this FileRegion to a Region for use in processing.
Returns
Region with equivalent coordinates and attributes.
Definition at line 45 of file SoundFileReader.cpp.
{
    if (start_coordinates.size() == 1 && end_coordinates.size() == 1) {
        if (start_coordinates[0] == end_coordinates[0]) {
            return Kakshya::Region::time_point(start_coordinates[0], name);
        }
        return Kakshya::Region::time_span(start_coordinates[0], end_coordinates[0], name);
    }
    Kakshya::Region region(start_coordinates, end_coordinates);
    region.set_attribute("label", name);
    region.set_attribute("type", type);
    for (const auto& [key, value] : attributes) {
        region.set_attribute(key, value);
    }
    return region;
}
References attributes, end_coordinates, name, MayaFlux::Kakshya::Region::set_attribute(), start_coordinates, MayaFlux::Kakshya::Region::time_point(), MayaFlux::Kakshya::Region::time_span(), and type.