MayaFlux: MayaFlux::Kakshya::VertexLayout::for_points
for_points()
static VertexLayout MayaFlux::Kakshya::VertexLayout::for_points (uint32_t stride = 60) inline static
Factory: layout for PointVertex (position, color, size, uv, normal, tangent)
Matches PointVertex field order exactly (60 bytes): loc 0 offset 0 VERTEX_POSITIONS_3D position loc 1 offset 12 VERTEX_COLORS_RGB color loc 2 offset 24 UNKNOWN size loc 3 offset 28 TEXTURE_COORDS_2D uv loc 4 offset 36 VERTEX_NORMALS_3D normal loc 5 offset 48 VERTEX_TANGENTS_3D tangent
Parameters
stride Override stride (default: sizeof(PointVertex) == 60)
Definition at line 93 of file VertexLayout.hpp.
    {
        VertexLayout layout;
        layout.stride_bytes = stride;
        layout.attributes.push_back({ .component_modality = DataModality::VERTEX_POSITIONS_3D,
            .offset_in_vertex = 0,
            .name = "position" });
        layout.attributes.push_back({ .component_modality = DataModality::VERTEX_COLORS_RGB,
            .offset_in_vertex = 12,
            .name = "color" });
        layout.attributes.push_back({ .component_modality = DataModality::SCALAR_F32,
            .offset_in_vertex = 24,
            .name = "size" });
        layout.attributes.push_back({ .component_modality = DataModality::TEXTURE_COORDS_2D,
            .offset_in_vertex = 28,
            .name = "uv" });
        layout.attributes.push_back({ .component_modality = DataModality::VERTEX_NORMALS_3D,
            .offset_in_vertex = 36,
            .name = "normal" });
        layout.attributes.push_back({ .component_modality = DataModality::VERTEX_TANGENTS_3D,
            .offset_in_vertex = 48,
            .name = "tangent" });
        return layout;
    }
References attributes, MayaFlux::Kakshya::SCALAR_F32, stride_bytes, MayaFlux::Kakshya::TEXTURE_COORDS_2D, MayaFlux::Kakshya::VERTEX_COLORS_RGB, MayaFlux::Kakshya::VERTEX_NORMALS_3D, MayaFlux::Kakshya::VERTEX_POSITIONS_3D, and MayaFlux::Kakshya::VERTEX_TANGENTS_3D.
Referenced by MayaFlux::Kakshya::as_point_vertex_access(), MayaFlux::Nodes::Network::FieldOperator::get_vertex_layout(), MayaFlux::Buffers::FormaProcessor::on_attach(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointNode::PointNode(), and MayaFlux::Nodes::vertex_layout_for().