MayaFlux: MayaFlux::Kakshya::DataDimension::time
time()
DataDimension MayaFlux::Kakshya::DataDimension::time (uint64_t samples, std::string name = "time") static
Convenience constructor for a temporal (time) dimension.
Parameters
samples Number of samples/frames
name Optional name (default: "time")
Returns
DataDimension representing time
Definition at line 17 of file NDData.cpp.
{
    return { std::move(name), samples, 1, Role::TIME };
}
References name, and TIME.
Referenced by create_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Buffers::download_audio_from_gpu(), MayaFlux::Yantra::infer_from_container(), MayaFlux::Yantra::infer_from_eigen(), MayaFlux::Yantra::infer_from_region(), MayaFlux::Yantra::infer_from_region_group(), MayaFlux::Yantra::infer_from_segments(), and MayaFlux::Yantra::infer_generic_structure().