MayaFlux: MayaFlux::Kakshya::DataDimension::spatial
spatial()
DataDimension MayaFlux::Kakshya::DataDimension::spatial (uint64_t size, char axis, uint64_t stride = 1, std::string name = "spatial") static
Convenience constructor for a spatial dimension.
Parameters
size Number of elements along this axis
axis Axis character ('x', 'y', or 'z')
stride Memory stride (default: 1)
name Optional name (default: "pixels")
Returns
DataDimension representing a spatial axis
Definition at line 32 of file NDData.cpp.
{
    Role r = [axis]() {
        switch (axis) {
        case 'x':
            return Role::SPATIAL_X;
        case 'y':
            return Role::SPATIAL_Y;
        case 'z':
        default:
            return Role::SPATIAL_Z;
        }
    }();
    if (name == "") {
        name = std::string("spatial_") + axis;
    }
    return { name, size, stride, r };
}
References name, size, SPATIAL_X, SPATIAL_Y, SPATIAL_Z, and stride.
Referenced by create_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Yantra::infer_from_eigen(), spatial_1d(), spatial_2d(), and spatial_3d().