MayaFlux: MayaFlux::Kinesis::Tendency::fn
fn
template<typename D , typename R > std::function<R(const D&)> MayaFlux::Kinesis::Tendency< D, R >::fn
Definition at line 23 of file Tendency.hpp.
Referenced by MayaFlux::Kinesis::axial_blend(), MayaFlux::Kinesis::chain(), MayaFlux::Kinesis::clamp(), MayaFlux::Kinesis::combine(), MayaFlux::Kinesis::constant(), MayaFlux::Kinesis::distance(), MayaFlux::Kinesis::Tendency< D, R >::evaluate(), MayaFlux::Kinesis::invert(), MayaFlux::Kinesis::invert(), MayaFlux::Kinesis::lerp(), MayaFlux::Kinesis::Tendency< D, R >::operator()(), MayaFlux::Kinesis::ForceFields::point_attractor(), MayaFlux::Kinesis::scale(), MayaFlux::Kinesis::scale(), MayaFlux::Kinesis::select(), MayaFlux::Kinesis::sigmoid(), MayaFlux::Kinesis::smoothstep(), MayaFlux::Kinesis::spherical(), MayaFlux::Kinesis::threshold(), MayaFlux::Kinesis::transfer_curve(), and MayaFlux::Kinesis::ForceFields::turbulence().