MayaFlux: MayaFlux::Kakshya::MeshSubrange::to_region
to_region()
Region MayaFlux::Kakshya::MeshSubrange::to_region () const
Convert this subrange to a Region for use in RegionGroup.
Coordinates are [index_start, index_start + index_count). Attributes carry name, material_name, and vertex_offset.
Definition at line 11 of file MeshAccess.cpp.
{
    Region r(
        std::vector { static_cast<uint64_t>(index_start) },
        std::vector { static_cast<uint64_t>(index_start + index_count) });
    r.set_attribute("name", name);
    r.set_attribute("material_name", material_name);
    r.set_attribute("vertex_offset", static_cast<uint64_t>(vertex_offset));
    r.set_attribute("index_count", static_cast<uint64_t>(index_count));
    r.set_attribute("diffuse_path", diffuse_path);
    r.set_attribute("diffuse_embedded", diffuse_embedded);
    return r;
}
References diffuse_embedded, diffuse_path, index_count, index_start, material_name, name, MayaFlux::Kakshya::Region::set_attribute(), and vertex_offset.
Referenced by MayaFlux::IO::ModelReader::extract_single_mesh(), and MayaFlux::Kakshya::MeshInsertion::insert_submesh().