MayaFlux: MayaFlux::Kakshya::VertexLayout::for_lines
for_lines()
static VertexLayout MayaFlux::Kakshya::VertexLayout::for_lines (uint32_t stride = 36) inline static
Factory: Create layout for line primitives (position, color, thickness)
Returns
VertexLayout configured for LineVertex
Definition at line 111 of file VertexLayout.hpp.
    {
        VertexLayout layout;
        layout.stride_bytes = stride;
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::VERTEX_POSITIONS_3D,
            .offset_in_vertex = 0,
            .name = "position" });
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::VERTEX_COLORS_RGB,
            .offset_in_vertex = 12,
            .name = "color" });
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::SCALAR_F32,
            .offset_in_vertex = 24,
            .name = "thickness" });
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::TEXTURE_COORDS_2D,
            .offset_in_vertex = 28,
            .name = "uv" });
        return layout;
    }
References attributes, MayaFlux::Kakshya::VertexAttributeLayout::component_modality, MayaFlux::Kakshya::SCALAR_F32, stride_bytes, MayaFlux::Kakshya::TEXTURE_COORDS_2D, MayaFlux::Kakshya::VERTEX_COLORS_RGB, and MayaFlux::Kakshya::VERTEX_POSITIONS_3D.
Referenced by MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::PathGeneratorNode::PathGeneratorNode(), MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode(), and MayaFlux::Nodes::GpuSync::TopologyGeneratorNode::TopologyGeneratorNode().