MayaFlux: MayaFlux::Kakshya::DataDimension::create_dimensions
create_dimensions()
std::vector< DataDimension > MayaFlux::Kakshya::DataDimension::create_dimensions (DataModality modality, const std::vector< uint64_t > & shape, MemoryLayout layout = MemoryLayout::ROW_MAJOR) static
Create dimension descriptors for a data modality.
Parameters
modality Target data modality
shape Dimensional sizes
layout Memory layout strategy
Returns
Vector of DataDimension objects
Definition at line 136 of file NDData.cpp.
{
    std::vector<DataDimension> dims;
    auto strides = calculate_strides(shape, layout);
    switch (modality) {
    case DataModality::AUDIO_1D:
        if (shape.size() != 1) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "AUDIO_1D requires 1D shape");
        }
        dims.push_back(DataDimension::time(shape[0]));
        break;
    case DataModality::AUDIO_MULTICHANNEL:
        if (shape.size() != 2) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "AUDIO_MULTICHANNEL requires 2D shape [samples, channels]");
        }
        dims.push_back(DataDimension::time(shape[0]));
        dims.push_back(DataDimension::channel(shape[1], strides[1]));
        break;
    case DataModality::IMAGE_2D:
        if (shape.size() != 2) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "IMAGE_2D requires 2D shape [height, width]");
        }
        dims.push_back(DataDimension::spatial(shape[0], 'y', strides[0]));
        dims.push_back(DataDimension::spatial(shape[1], 'x', strides[1]));
        break;
    case DataModality::IMAGE_COLOR:
        if (shape.size() != 3) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "IMAGE_COLOR requires 3D shape [height, width, channels]");
        }
        dims.push_back(DataDimension::spatial(shape[0], 'y', strides[0]));
        dims.push_back(DataDimension::spatial(shape[1], 'x', strides[1]));
        dims.push_back(DataDimension::channel(shape[2], strides[2]));
        break;
    case DataModality::IMAGE_COLOR_ARRAY:
        if (shape.size() != 4) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "IMAGE_COLOR_ARRAY requires 4D shape [frames, height, width, channels]");
        }
        dims.push_back(DataDimension::time(shape[0], "index"));
        dims.push_back(DataDimension::spatial(shape[1], 'y', strides[1]));
        dims.push_back(DataDimension::spatial(shape[2], 'x', strides[2]));
        dims.push_back(DataDimension::channel(shape[3], strides[3]));
        break;
    case DataModality::SPECTRAL_2D:
        if (shape.size() != 2) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "SPECTRAL_2D requires 2D shape [time_windows, frequency_bins]");
        }
        dims.push_back(DataDimension::time(shape[0], "time_windows"));
        dims.push_back(DataDimension::frequency(shape[1]));
        dims[1].stride = strides[1];
        break;
    case DataModality::VOLUMETRIC_3D:
        if (shape.size() != 3) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "VOLUMETRIC_3D requires 3D shape [x, y, z]");
        }
        dims.push_back(DataDimension::spatial(shape[0], 'x', strides[0]));
        dims.push_back(DataDimension::spatial(shape[1], 'y', strides[1]));
        dims.push_back(DataDimension::spatial(shape[2], 'z', strides[2]));
        break;
    case DataModality::VIDEO_GRAYSCALE:
        if (shape.size() != 3) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "VIDEO_GRAYSCALE requires 3D shape [frames, height, width]");
        }
        dims.push_back(DataDimension::time(shape[0], "frames"));
        dims.push_back(DataDimension::spatial(shape[1], 'y', strides[1]));
        dims.push_back(DataDimension::spatial(shape[2], 'x', strides[2]));
        break;
    case DataModality::VIDEO_COLOR:
        if (shape.size() != 4) {
            error<std::invalid_argument>(
                Journal::Component::Kakshya,
                Journal::Context::Runtime,
                std::source_location::current(),
                "VIDEO_COLOR requires 4D shape [frames, height, width, channels]");
        }
        dims.push_back(DataDimension::time(shape[0], "frames"));
        dims.push_back(DataDimension::spatial(shape[1], 'y', strides[1]));
        dims.push_back(DataDimension::spatial(shape[2], 'x', strides[2]));
        dims.push_back(DataDimension::channel(shape[3], strides[3]));
        break;
    default:
        error<std::invalid_argument>(
            Journal::Component::Kakshya,
            Journal::Context::Runtime,
            std::source_location::current(),
            "Unsupported modality for dimension creation: {}", modality_to_string(modality));
    }
    return dims;
}
References MayaFlux::Kakshya::AUDIO_1D, MayaFlux::Kakshya::AUDIO_MULTICHANNEL, calculate_strides(), channel(), frequency(), MayaFlux::Kakshya::IMAGE_2D, MayaFlux::Kakshya::IMAGE_COLOR, MayaFlux::Kakshya::IMAGE_COLOR_ARRAY, MayaFlux::Journal::Kakshya, MayaFlux::Kakshya::modality_to_string(), MayaFlux::Journal::Runtime, spatial(), MayaFlux::Kakshya::SPECTRAL_2D, time(), MayaFlux::Kakshya::VIDEO_COLOR, MayaFlux::Kakshya::VIDEO_GRAYSCALE, and MayaFlux::Kakshya::VOLUMETRIC_3D.
Referenced by MayaFlux::Yantra::infer_from_region(), MayaFlux::Yantra::infer_from_region_group(), MayaFlux::Kakshya::SoundStreamContainer::setup_dimensions(), MayaFlux::Kakshya::VideoStreamContainer::setup_dimensions(), and MayaFlux::Kakshya::WindowContainer::setup_dimensions().