MayaFlux: MayaFlux::Portal::Forma::Collapsible::attach
attach()
void MayaFlux::Portal::Forma::Collapsible::attach (Layer & layer, uint32_t body_id) const
Relate a body element to this collapsible and sync its visibility to the current open state.
Parameters
layer Layer the body element lives on.
body_id Element id returned from layer.add(...).
Definition at line 117 of file Collapsible.cpp.
{
    layer.relate(header_id, body_id);
    layer.set_visible(body_id, open->value);
}
References header_id, open, MayaFlux::Portal::Forma::Layer::relate(), and MayaFlux::Portal::Forma::Layer::set_visible().
Referenced by MayaFlux::Portal::Forma::Inspector::event_manager(), and MayaFlux::Portal::Forma::Inspector::scheduler().