MayaFlux: MayaFlux::Core::InputValue::MIDIMessage::type
type()
uint8_t MayaFlux::Core::InputValue::MIDIMessage::type () const inline
Definition at line 226 of file InputBinding.hpp.
{ return status & 0xF0; }
Referenced by MayaFlux::Nodes::Input::MIDINode::extract_value(), MayaFlux::Nodes::Input::MIDINode::fire_midi_callbacks(), and MayaFlux::Nodes::Input::MIDINode::matches_filters().