MayaFlux: MayaFlux::Core::DescriptorSetLayoutConfig::add_binding
add_binding()
void MayaFlux::Core::DescriptorSetLayoutConfig::add_binding (uint32_t binding, vk::DescriptorType type, vk::ShaderStageFlags stages, uint32_t count = 1) inline
Definition at line 43 of file VKDescriptorManager.hpp.
    {
        bindings.emplace_back(binding, type, stages, count);
    }
References bindings, and count.
Referenced by add_sampled_image(), add_storage_buffer(), add_storage_image(), add_uniform_buffer(), MayaFlux::Core::BackendPipelineManager::create_descriptor_layout(), and MayaFlux::Portal::Graphics::ComputePress::create_pipeline().