MayaFlux: MayaFlux::Kakshya::StreamSlice::from_frame_range
from_frame_range()
static StreamSlice MayaFlux::Kakshya::StreamSlice::from_frame_range (std::shared_ptr< DynamicSoundStream > stream, uint64_t start_frame, uint64_t end_frame, uint8_t index = 0) inline static
Construct a slice spanning a frame sub-region across all channels.
Parameters
stream Source stream.
start_frame Inclusive start frame.
end_frame Inclusive end frame.
index Slot identity.
Definition at line 68 of file StreamSlice.hpp.
    {
        const uint64_t end_channel = stream->get_num_channels() > 0
            ? stream->get_num_channels() - 1
            : 0;
        return StreamSlice {
            .stream = std::move(stream),
            .region = Region::audio_span(start_frame, end_frame, 0, end_channel),
            .index = index,
        };
    }
References MayaFlux::Kakshya::Region::audio_span(), end_channel(), end_frame(), index, start_frame(), and stream.