MayaFlux: MayaFlux::Kakshya::ContainerDataStructure::get_samples_count_per_channel
get_samples_count_per_channel() [2/2]
uint64_t MayaFlux::Kakshya::ContainerDataStructure::get_samples_count_per_channel (const std::vector< DataDimension > & dimensions) static
Get samples per channel (time dimension only).
Parameters
dimensions Vector of dimension descriptors
Returns
Number of samples per channel
Definition at line 198 of file NDimensionalContainer.cpp.
{
    for (const auto& dim : dimensions) {
        if (dim.role == DataDimension::Role::TIME) {
            return dim.size;
        }
    }
    return 0;
}
References dimensions, and MayaFlux::Kakshya::DataDimension::TIME.
Referenced by MayaFlux::Kakshya::advance_position(), MayaFlux::Kakshya::advance_position(), MayaFlux::Kakshya::ContiguousAccessProcessor::store_metadata(), and MayaFlux::Kakshya::ContiguousAccessProcessor::validate().