MayaFlux: MayaFlux::Kakshya::ContainerDataStructure::get_total_elements
get_total_elements() [2/2]
uint64_t MayaFlux::Kakshya::ContainerDataStructure::get_total_elements (const std::vector< DataDimension > & dimensions) static
Get total elements across all dimensions.
Parameters
dimensions Vector of dimension descriptors
Returns
Total number of elements
Definition at line 134 of file NDimensionalContainer.cpp.
{
    uint64_t total = 1;
    for (const auto& dim : dimensions) {
        total *= dim.size;
    }
    return total;
}
References dimensions.
Referenced by MayaFlux::Kakshya::WindowContainer::clear(), MayaFlux::Kakshya::SoundStreamContainer::get_total_elements(), MayaFlux::Kakshya::WindowContainer::get_total_elements(), and MayaFlux::Kakshya::ContiguousAccessProcessor::store_metadata().