MayaFlux: MayaFlux::Kakshya::DataDimension::channel
channel()
DataDimension MayaFlux::Kakshya::DataDimension::channel (uint64_t count, uint64_t stride = 1) static
Convenience constructor for a channel dimension.
Parameters
count Number of channels
stride Memory stride (default: 1)
Returns
DataDimension representing channels
Definition at line 22 of file NDData.cpp.
{
    return { "channel", count, stride, Role::CHANNEL };
}
References CHANNEL, count, and stride.
Referenced by create_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), and MayaFlux::Yantra::infer_from_eigen().