MayaFlux: MayaFlux::Buffers::RootAudioUnit::get_chain
get_chain()
std::shared_ptr< BufferProcessingChain > MayaFlux::Buffers::RootAudioUnit::get_chain (uint32_t channel) const inline
Definition at line 26 of file TokenUnitManager.hpp.
    {
        return processing_chains[channel];
    }
References processing_chains.
Referenced by MayaFlux::Buffers::BufferAccessControl::add_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::add_audio_processor(), MayaFlux::Buffers::BufferProcessingControl::add_audio_processor_to_token(), MayaFlux::Buffers::BufferAccessControl::get_audio_processing_chain(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_channel(), MayaFlux::Buffers::BufferProcessingControl::remove_audio_processor_from_token(), and MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor().