MayaFlux: MayaFlux::Buffers::RootAudioUnit::get_buffer
get_buffer()
std::shared_ptr< RootAudioBuffer > MayaFlux::Buffers::RootAudioUnit::get_buffer (uint32_t channel) const inline
Definition at line 21 of file TokenUnitManager.hpp.
    {
        return root_buffers[channel];
    }
References root_buffers.
Referenced by MayaFlux::Buffers::BufferSupplyMixing::cleanup_completed_routing(), MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer(), MayaFlux::Buffers::BufferAccessControl::get_root_audio_buffer(), MayaFlux::Buffers::BufferAccessControl::remove_audio_buffer(), MayaFlux::Buffers::BufferSupplyMixing::remove_supplied_audio_buffer(), MayaFlux::Buffers::BufferProcessingControl::set_audio_final_processor(), MayaFlux::Buffers::BufferSupplyMixing::supply_audio_buffer_to(), MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers(), and MayaFlux::Buffers::BufferSupplyMixing::update_routing_states_for_cycle().