MayaFlux: MayaFlux::Core::InputValue::as_midi
as_midi()
const MIDIMessage & MayaFlux::Core::InputValue::as_midi () const inline
Definition at line 259 of file InputBinding.hpp.
{ return std::get<MIDIMessage>(data); }
Referenced by MayaFlux::Nodes::Input::InputNode::extract_value(), MayaFlux::Nodes::Input::MIDINode::extract_value(), MayaFlux::Core::InputManager::matches_binding(), and MayaFlux::Nodes::Input::MIDINode::matches_filters().