MayaFlux: MayaFlux::Kakshya::ContainerDataStructure::get_variant_size
get_variant_size() [2/2]
uint64_t MayaFlux::Kakshya::ContainerDataStructure::get_variant_size (const std::vector< DataDimension > & dimensions, DataModality modality, OrganizationStrategy organization, size_t variant_index = 0) static
Calculate size of a specific variant in the organization.
Parameters
dimensions Vector of dimension descriptors
modality Data modality type
organization Organization strategy
variant_index Index of the variant (0-based)
Returns
Number of elements in the specified variant
Definition at line 86 of file NDimensionalContainer.cpp.
{
    switch (organization) {
    case OrganizationStrategy::INTERLEAVED:
        return get_total_elements(dimensions);
    case OrganizationStrategy::PLANAR:
        switch (modality) {
        case DataModality::AUDIO_MULTICHANNEL:
            return get_samples_count_per_channel(dimensions);
        case DataModality::IMAGE_COLOR:
            return get_pixels_count(dimensions);
        case DataModality::VIDEO_COLOR:
            return get_frame_count(dimensions) * get_pixels_count(dimensions);
        default:
            return get_total_elements(dimensions);
        }
    default:
        return get_total_elements(dimensions);
    }
}
References MayaFlux::Kakshya::AUDIO_MULTICHANNEL, dimensions, get_frame_count(), get_pixels_count(), get_samples_count_per_channel(), get_total_elements(), MayaFlux::Kakshya::IMAGE_COLOR, MayaFlux::Kakshya::INTERLEAVED, modality, organization, MayaFlux::Kakshya::PLANAR, and MayaFlux::Kakshya::VIDEO_COLOR.