MayaFlux: MayaFlux::Buffers::RootGraphicsUnit::get_buffer
get_buffer()
std::shared_ptr< RootGraphicsBuffer > MayaFlux::Buffers::RootGraphicsUnit::get_buffer () const inline
Definition at line 49 of file TokenUnitManager.hpp.
{ return root_buffer; }
References root_buffer.
Referenced by MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers(), MayaFlux::Buffers::BufferAccessControl::get_graphics_buffers_by_usage(), MayaFlux::Buffers::BufferAccessControl::get_root_graphics_buffer(), MayaFlux::Buffers::BufferAccessControl::get_root_graphics_buffer(), MayaFlux::Buffers::BufferAccessControl::remove_graphics_buffer(), and MayaFlux::Buffers::BufferAccessControl::terminate_active_buffers().