MayaFlux: MayaFlux::Buffers::RootGraphicsUnit::get_chain
get_chain()
std::shared_ptr< BufferProcessingChain > MayaFlux::Buffers::RootGraphicsUnit::get_chain () const inline
Definition at line 51 of file TokenUnitManager.hpp.
{ return processing_chain; }
References processing_chain.
Referenced by MayaFlux::Buffers::BufferAccessControl::add_graphics_buffer(), MayaFlux::Buffers::BufferAccessControl::get_graphics_processing_chain(), MayaFlux::Buffers::BufferProcessingControl::remove_graphics_processor(), and MayaFlux::Buffers::BufferProcessingControl::set_graphics_final_processor().