MayaFlux: MayaFlux::Kakshya::DataDimension::frequency
frequency()
DataDimension MayaFlux::Kakshya::DataDimension::frequency (uint64_t bins, std::string name = "frequency") static
Convenience constructor for a frequency dimension.
Parameters
bins Number of frequency bins
name Optional name (default: "frequency")
Returns
DataDimension representing frequency
Definition at line 27 of file NDData.cpp.
{
    return { std::move(name), bins, 1, Role::FREQUENCY };
}
References FREQUENCY, and name.
Referenced by create_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), and MayaFlux::Yantra::infer_from_eigen().