MayaFlux: MayaFlux::Yantra::IO::has_container
has_container()
template<ComputeData T = std::vector<Kakshya::DataVariant>> bool MayaFlux::Yantra::IO< T >::has_container () const inline
Check if a container reference is associated.
Returns
True if a container is set
Definition at line 155 of file DataIO.hpp.
    {
        return container.has_value();
    }
Referenced by MayaFlux::Yantra::UniversalTransformer< InputType, OutputType >::create_safe_output(), MayaFlux::Yantra::sort_compute_data_inplace(), MayaFlux::Yantra::FeatureExtractor< InputType, OutputType >::validate_extraction_input(), and MayaFlux::Yantra::UniversalTransformer< InputType, OutputType >::validate_input().