MayaFlux: MayaFlux::Kakshya::ContainerDataStructure::get_channel_count
get_channel_count() [2/2]
uint64_t MayaFlux::Kakshya::ContainerDataStructure::get_channel_count (const std::vector< DataDimension > & dimensions) static
Extract channel count from dimensions.
Parameters
dimensions Vector of dimension descriptors
Returns
Number of channels
Definition at line 162 of file NDimensionalContainer.cpp.
{
    for (const auto& dim : dimensions) {
        if (dim.role == DataDimension::Role::CHANNEL) {
            return dim.size;
        }
    }
    return 1;
}
References MayaFlux::Kakshya::DataDimension::CHANNEL, and dimensions.
Referenced by MayaFlux::Kakshya::advance_position(), MayaFlux::Kakshya::advance_position(), MayaFlux::Kakshya::WindowContainer::get_value_at(), MayaFlux::Kakshya::ContiguousAccessProcessor::on_attach(), MayaFlux::Kakshya::ContiguousAccessProcessor::store_metadata(), and MayaFlux::Kakshya::ContiguousAccessProcessor::validate().