MayaFlux: MayaFlux::Kakshya::DataDimension::grouped
grouped()
DataDimension MayaFlux::Kakshya::DataDimension::grouped (std::string name, uint64_t element_count, uint8_t components_per_element, Role role = Role::CUSTOM) static
Create dimension with component grouping.
Parameters
name Dimension name
element_count Number of elements (not components)
components_per_element Components per element (e.g., 3 for vec3)
role Semantic role
Definition at line 72 of file NDData.cpp.
{
    DataDimension dim { std::move(name), element_count, 1, role };
    dim.grouping = ComponentGroup { components_per_element, 0 };
    return dim;
}
References grouping, name, and role.
Referenced by MayaFlux::Kakshya::detect_data_dimensions(), MayaFlux::Kakshya::detect_data_dimensions(), texture_coords(), vertex_colors(), vertex_normals(), and vertex_positions().