MayaFlux: MayaFlux::Kakshya::VertexLayout::for_points
for_points()
static VertexLayout MayaFlux::Kakshya::VertexLayout::for_points (uint32_t stride = 28) inline static
Factory: Create layout for point primitives (position, color, size)
Returns
VertexLayout configured for PointVertex
Definition at line 84 of file VertexLayout.hpp.
    {
        VertexLayout layout;
        layout.stride_bytes = stride;
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::VERTEX_POSITIONS_3D,
            .offset_in_vertex = 0,
            .name = "position" });
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::VERTEX_COLORS_RGB,
            .offset_in_vertex = 12,
            .name = "color" });
        layout.attributes.push_back(VertexAttributeLayout {
            .component_modality = DataModality::SCALAR_F32,
            .offset_in_vertex = 24,
            .name = "size" });
        return layout;
    }
References attributes, MayaFlux::Kakshya::VertexAttributeLayout::component_modality, MayaFlux::Kakshya::SCALAR_F32, stride_bytes, MayaFlux::Kakshya::VERTEX_COLORS_RGB, and MayaFlux::Kakshya::VERTEX_POSITIONS_3D.
Referenced by MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), MayaFlux::Nodes::GpuSync::PointCollectionNode::PointCollectionNode(), and MayaFlux::Nodes::GpuSync::PointNode::PointNode().