include_guard(GLOBAL)

file(GLOB_RECURSE NODES_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE NODES_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${NODES_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${NODES_HEADERS})
