include_guard(GLOBAL)

file(GLOB_RECURSE PORTAL_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE PORTAL_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${PORTAL_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${PORTAL_HEADERS})
