# Binaries (lila_server and any others)
usr/bin/*

# Libraries (MayaFluxLib and Lila)
usr/lib/*.so*

# Pkg-config and CMake configuration files
usr/lib/pkgconfig/*.pc
usr/lib/cmake/MayaFlux/*
usr/lib/libminiz.a
usr/lib/libtinyvdb.a

# Headers (MayaFlux and Lila)
usr/include/MayaFlux/*
usr/include/Lila/*

# Runtime data (Shaders, .version file, and PCH headers)
usr/share/MayaFlux/*
usr/share/MayaFlux/.version
