#version 460

layout(local_size_x = 8, local_size_y = 8) in;
layout(set = 0, binding = 0, rgba32f) uniform writeonly image2D out_image;
layout(push_constant) uniform PushConstants {
    uint width;
    uint height;
} pc;
void main()
{
    const ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= int(pc.width) || coord.y >= int(pc.height))
        return;
    imageStore(out_image, coord, vec4(0.0, 0.0, 0.0, 1.0));
}
