include_guard(GLOBAL)

file(GLOB_RECURSE CORE_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

if(APPLE)
    file(GLOB_RECURSE CORE_MM_SOURCES CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_LIST_DIR}/*.mm"
    )
    list(APPEND CORE_SOURCES ${CORE_MM_SOURCES})
endif()

file(GLOB_RECURSE CORE_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${CORE_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${CORE_HEADERS})
