include_guard(GLOBAL)

file(GLOB_RECURSE KINESIS_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE KINESIS_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${KINESIS_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${KINESIS_HEADERS})
