include_guard(GLOBAL)

file(GLOB_RECURSE JOURNAL_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE JOURNAL_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${JOURNAL_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${JOURNAL_HEADERS})
