include_guard(GLOBAL)

file(GLOB_RECURSE REGISTRY_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE REGISTRY_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${REGISTRY_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${REGISTRY_HEADERS})
