include_guard(GLOBAL)

file(GLOB_RECURSE KRIYA_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
)

file(GLOB_RECURSE KRIYA_HEADERS CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/*.h"
    "${CMAKE_CURRENT_LIST_DIR}/*.hpp"
)

list(APPEND MAYAFLUX_ALL_SOURCES ${KRIYA_SOURCES})
list(APPEND MAYAFLUX_ALL_HEADERS ${KRIYA_HEADERS})
