name: "Test Arch Linux CI (manual)"
on:
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/build-linux-arch.yml
    with:
      version: "0.4.0-ci-test"
      clean_version: "0.4.0"
      is_dev: "1"
      run_tests: false
      create_distribution: true
      artifact_name: "MayaFlux-ci-test-linux-arch"
      distribution_name: "linux-arch"
      os_display_name: "Arch Linux"
